### ISSUE TITLE
Changes in Iron Chests's upgrades recipes

### ISSUE THREAD

**Issue by MadRatSRP** [GTNewHorizons/GT-New-Horizons-Modpack#10001]
### Your GTNH Discord Username

MadRat96#9831

### Your Pack Version

2.1.2.1

### Your Proposal

Iron to gold chest upgrade takes regular plates, making gold chest takes double gold plates.

Wood to iron/wood to copper upgrades takes both double plates, making iron chest/copper chest takes double plates as well. 

My idea is that wood to iron/wood to copper upgrades are too expensive in usage of iron and copper especially when they're the first things player will have to make in early game when often you're lacking of resources.

So i have an idea how to make them more cheaper, but at the same time a bit more difficult to craft.

Using Carpenter's block instead of regular wood plank and using regular iron/copper plates instead of double ones will help to balance the recipes of wood to iron/wood to copper upgrades.

### Your Goal

null

### Your Vision

null

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Chaoschaot232** [comment]
Hmmmm, tbh I think that maybe the first few chest recipies should be a bit easier.
This means replacing the double plates with single plates but for now I find these crafting recipies fine.

Maybe I am good at finding the correct ore veins to get the ressources which I need or want so that I don't have that
trouble.

Using Carpenter's Blocks makes no sense for me here, tbh.

After all, this is my meaning/opnion to this.
