### ISSUE TITLE
AE outocrafting closes GUI in terminals

### ISSUE THREAD

**Issue by arik4326** [GTNewHorizons/GT-New-Horizons-Modpack#1001]
when clicking on craft it kicks out of the terminal screem  for some player while other player can use it normally
reloging and replacing it doesent help was nothing in ae system was changet not working on all terminals

**Comment by Dream-Master** [comment]
A bit more details please. What are you try to craft? Any Screeshot? fml log ?

**Comment by bigbass1997** [comment]
Doesn't matter what kind of terminal.

Sometimes when clicking on anything to craft, the GUI closes right away. Nothing out of the ordinary shows up in console or logs.

Yet even when this happens, sometimes other people are able to do with without issues.

Dietmar, on the EU server, also had this happen, however he was able to "fix" it by placing the terminal through his P2P network instead of directly to the controller. But even that doesn't always work.

Of the people I have seen report this so far, all of them have been in the void dimension and have had some kind of P2P set up. Not sure if either are connected to the issue, but something good to point out.

**Comment by Technus** [comment]
Might be the AE2 addon remote crafting terminal doing this shed.

**Comment by Dream-Master** [comment]
Please test it with the new version 1.3.0.0pre4. Wire Terminal get an update. If it not works we have to post it on wireless ae terminal side.

**Comment by Methes** [comment]
Sorry to necro this issue, just happened to me on private server so I'd like to clarify the bug for future uses. 

This bug is probably completely random.
When it occurs, having any item in a specific hotbar slot (random too, for me it's slot number 7 right now) fires this bug. Upon trying to autocraft any recipe in your AE system (clicking the item) the AE GUI closes without opening the Autocrafting GUI.
Removing items from that specific slot fixes that (until you put any item back).
Restarting the client/server doesn't fix that.

Original issue, sadly client/server don't produce any log record.
https://github.com/p455w0rd/WirelessCraftingTerminal/issues/151

**Comment by repo-alt** [comment]
As far as I know this issue still happens sometimes in 1.12 version too. No one was able to reliably reproduce it so that it might be debugged. It is probably wireless crafting terminal related indeed, but the author of WCT is even less cooperative that AE2 maintainer, and w/o a good reproducer I don't think it has any chance to be fixed .

**Comment by Dream-Master** [comment]
@repo-alt will it help if we work WCT or is this mod allready in us repo ?

**Comment by repo-alt** [comment]
I have no idea how to reproduce that anyway.
