### ISSUE TITLE
Remove Bedrockium TC nugget dupe

### ISSUE THREAD

**Issue by LewisSaber** [GTNewHorizons/GT-New-Horizons-Modpack#10147]
### Your GTNH Discord Username

Lewissaber#7231

### Your Pack Version

 2.1.2.3QF

### Your Proposal

Remove thaumcraft way to dupe bedrockium nuggets

### Your Goal

Make it less op

### Your Vision

It makes bedrockium too easy for how good it is

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Steelux8** [comment]
Bedrockium is very easy to make in the first place, for the high tiers that it (for some reason) is used in. Even more, the setups used for the cobble are often laggy, so it's a good thing to avoid the lag on cheap recipes by having options like this.

Also, if it was overpowered, everyone would be doing it, which I'm sure is not the case given how many people simply don't use TC. I don't know how any of the duping recipes can be considered OP by that standard.

**Comment by boubou19** [comment]
this is the recipe in question:
![image](https://user-images.githubusercontent.com/12850933/163279972-1b7ae8f7-0f74-4e77-bbfa-10ab9f96852c.png)

The bedrockium creation in it's normal way is totally automatable passively, and is boring. Also, players wanting to abuse bedrockium with cobble gen will most of the time destroy the TPS. Also, post 2.1.2.0, GT++ adds a multi to make cobble, making this even easier.

I'll add that as @Steelux8 said, almost no one will use thaumcraft, because it's thaumcraft.

Now, if we look at what is actually useful the bedrockium for, well you'll see that it's used in UHV component, in bedrockium drums (which are gated by moon anyways due to the normal drum in the recipe, so EV), some tools, a wire(which is useless as player can use better cables because they aren't lossless) and pipes (there too players can make pipes in better material to be able to make them in bulk). In any case, except UHV components, you don't need much bedrockium to achieve that. So even if the recipe gets removed, all the """overpoweredness""" of the bedrockium is still availiable. So i don't see the point except nerfing thaumcraft for the sake of it.

Leaving some advantages to use thaumcraft is a great way to get people's interest in it.
