### ISSUE TITLE
Additional processing options for Cactus Charcoal and Cactus Coke

### ISSUE THREAD

**Issue by TwoTailedFox** [GTNewHorizons/GT-New-Horizons-Modpack#10233]
### Your GTNH Discord Username

BritishCynic#9193

### Your Pack Version

2.1.2.3QF

### Your Proposal

To enable these fuels to be used in the Pyrolyse Oven, Coke Oven and Fluid Extractor with outputs relative to their burn value. Cactus Charcoal would return 25% of what 1 x Charcoal does now, while Cactus Coke would return 50% of what 1 x Coal does now.

### Your Goal

To add additional processing routes and ensure that players have valid reasons to craft these items rather than just to use as fuel.

### Your Vision

Right now, there is pretty much no reason to craft these items due to their burn value; however, making cactus fuels viable as an ultimate source of Benzene makes simple cactus farms viable for early game fuel production

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Cleista** [comment]
I am supportive of this proposal; recently started a new GTNH run with a bunch of people and some users asked me why cactus coke was both less useful and required more steps than just wood -> charcoal. 

Aside from the previously mentioned wood/coal tar recipes, perhaps enabling using them for smelting in the BBF at a reasonable ratio (2x or 4x the amount of charcoal needed?) would make them feel more integrated into the pack without significantly affecting balance.

**Comment by BeanBagel** [comment]
This is something I want pretty badly. You mentioned "alternative Coals and Charcoals" so you're likely aware, but I'll add that sugar charcoal and sugar coke are in the same state.

Additionally I believe that most of of the coal coke and charcoal recipes would be fine to include (with the right balancing). I created a simplified list of uses for coal coke, charcoal that could apply. I also added charcoal dust since it is in the same vein; however, Transferring recipes would probably require creating new cactus charcoal dust and sugar charcoal dust.

![image](https://user-images.githubusercontent.com/17522300/169672499-5fe9d927-abf8-4cb0-9804-c17d6e259600.png)
