### ISSUE TITLE
Bee concerns and suggestions 

### ISSUE THREAD

**Issue by Runakai1** [GTNewHorizons/GT-New-Horizons-Modpack#10230]
### Your GTNH Discord Username

Runakai ~ Docsyᵇᵒᵗ#7676

### Your Pack Version

2.1.2.3QF3

### Your Proposal

The industrial apiary is gated behind LuV and the assline, while crops and their counterparts of automation begin in LV. You cannot properly automate bees as you can with crops. Crops need 1 space and their crop manager and you can basically forget them.
You can automate bees with using Item conduits and alvearies/apearies, which takes more time, takes up more room and in the end, yields less than crops.

My proposal would be, in order to buff bees as they heavily need a buff, to start with the upgrades of the industrial apiary. While their recipes are gated behind the platline and is okay-ish, the "Upgrade Frame" needed for the upgrades should be reworked. Most of all: the need of mutagen should be removed or replaced.

The need of mutagen pushes the usage of industrial apiaries back to later tiers.

### Your Goal

This feature is needed because Crops and Bees are both renewable resources, yet one is dramatically better than the other. This change would allow bees to be used a bit earlier than they are now. While this doesnt buff bees alltogether, its a good step in my opinion. 

### Your Vision

The discrepancy of crops and bees would be a bit lower. People would stop using crops that much.
The proper rebalancing of both needs way more work, though. I mean, who thinks its a great idea to make some bees over crops in LV, right?  

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Steelux8** [comment]
Crops aren't just dramatically better than bees. They are placed at different stages of progression, due to WAs, because bees can be sped up in big quantities with a few WAs while crops need hundreds of them to cover a single multifarm, when crop-dedicated players like Sampsa have built entire towers of multifarms (very laggy, as you can imagine).

For bees to be used frequently in LV, you'd have to remove those long breeding chains before anything else, which I doubt is gonna happen. As it is, they seem to be intended for mid-late game.

**Comment by Runakai1** [comment]
> Crops aren't just dramatically better than bees. They are placed at different stages of progression, due to WAs, because bees can be sped up in big quantities with a few WAs while crops need hundreds of them to cover a single multifarm, when crop-dedicated players like Sampsa have built entire towers of multifarms (very laggy, as you can imagine).
> 
> For bees to be used frequently in LV, you'd have to remove those long breeding chains before anything else, which I doubt is gonna happen. As it is, they seem to be intended for mid-late game.

You can accelerate 4 crops with WA while you can accelerate 6 industrial apiaries, it's just that crops are dramatically better in every progression because bees are heavily gates behind materials and such

**Comment by boubou19** [comment]
you can accelerate 5 crops by placing a crop below the WA

**Comment by Runakai1** [comment]
> you can accelerate 5 crops by placing a crop below the WA

Oh true! That makes the crop and bee disbalance even worse, given how easy crops are to automate and early to get

**Comment by Steelux8** [comment]
I don't mind buffs to bees in early game, I'd support them. It's unlikely I would actually use bees in the early tiers, because there's still the problem of the huge breeding line which crops don't have, but I'm all up for bee buffs. The reason why I consider bees to be lategame is because you don't need as many individual WAs for them, and you'll have had the time to breed through all the paths to get to the best bees.

**Comment by boubou19** [comment]
crop breeding right now is purely rng, which is dumb. Some work has been done to change that and define breeding tree to make crops less rng based.

**Comment by Runakai1** [comment]
> > you can accelerate 5 crops by placing a crop below the WA
> 
> Oh true! That makes the crop and bee disbalance even worse, given how easy crops are to automate and early to get

Just something that came to my mind: You can accelerate 5 crops and 5 apiaries since you need to charge the WA somehow

**Comment by boubou19** [comment]
you can't WA 6 crops but you can WA 6 bees as microwave energy transmitters are a thing

**Comment by Eranicus** [comment]
While there are no multiblocks for bees they are absolute waste of time on any tier. I see you mentioned world accelerators , dont forget that WA's are top tps killers , it is possible to use several on some very specific cases but definitely not for bees or crops. By the way, crops became viable on zpm+ only because of new greenhouse multiblock. In my opinion the only way for bees to become viable is to introduce similar multiblock , and to restrict specific bees to energy tiers.

**Comment by Runakai1** [comment]
Maybe we can start buffing bees by unlocking gendustry earlier in game. RN, to use the fullest potential of Gendustry, you need UV components.

**Comment by Runakai1** [comment]
To furthermore argue that bees need a buff:

A 3x3 alveary needs 2160 honey drops. a 3x3 Multiblock for regulating 1 bee. Meanwhile, you can manage 9 crops without the cost of needing 2160 crop materials (like crop leaves) to make a multiblock for them because they don't require one.

Industrial Apiaries get incredibly laggy with WA, so that is not a long term solution.

Advanced Genetics should be removed and gendustry should be dramatically less costly, to get fully into gendustry you need UV components. Crops dont.

With the recent addition of the Crop manager, crops get another easy way to automation. Bees don't.

And as far as I know, correct me if I'm wrong, Crops dont need environmental stats as intense as bees. Fertilize and water your crops (not salty roots iirc) and you're good to go. With bees you need to have the correct Biome (Temperature and Humidity) to get the combs of the respective species. You need to emulate that with yet another expensive upgrade in the alveary or ind. apiary or you need to spread your bee setup across the whole world- crops don't need that treatment.

While that has nothing to do with GTNH's implementation: Crops have an OC script that allows them to breed easily, there is no working bee script afaik and all the ones in development are unfinished or don't work. It's easier to get crops, they're better in every tier, they are not as painful as bees and once you're able to properly use bees, they get redundant AND overrun by crops.

**Comment by minecraft7771** [comment]
I also think there are bees missing for resources that crops already give. Prime example would be the primordeal pearl which can be grown as a crop but not be gotten with bee combs. Also a bee that gives UU would be nice. In both cases the yield should be minimal that's for sure but right a bee alternative to such crops should exist imo.

**Comment by OrderedSet86** [comment]
The primary issues to me are:
1. Bees are almost always productively worse than crops, with very narrow exceptions
2. The breeding tree is much more painful
3. Bees are tiered later than crops (for practical purposes)
4. Setting up a productive bee complex is difficult
5. Bees are laggier
6. Bees lack an out of the box autobreeding solver

### Bees are almost always worse than crops, with very narrow exceptions
This is my copy-paste on #help:

> bees are good for thaum materials, early plat/zinc, early/mid game node printing, dragon eggs, diesel, a renewable source of late game ores (although miners are kinda just better), and 4xing certain resources

When comparing bees directly to crops, crops will almost always be better in multiple ways:
1. Density of production - one crop produces much more than one bee in one alveary (a 3x3 multiblock no less).
2. Ease of generation - while more bees can always be made with leftover drones, it usually takes 2-3 breeding steps to get a purebreed of the kind you want, with more if there are undesirable stat differences. With self-self crop breeds it's a roughly 60% chance to get back self again, which averages out to 1/0.6 = 1.67 breeds average. So you're putting in twice as much effort per productive unit itself.
3. Ease of infrastructure - an alveary costs 2160 honey drops, which is the marginal cost for *every single additional bee* you add to production. Apiaries have 10% production compared to alvearies, and therefore basically are not worth it. The marginal cost for adding an additional crop is one dirt, some water gen (free), and 1/100th the cost of a harvester or crop manager (for which the ratios are even lower).

Because the "worth" is worse in each of the categories described above, bees are always a suboptimal choice.

### The breeding tree is much more painful

Getting to "useful" bees - eg thaum material bees like Windy - can be 10 or more steps into the breeding tree, with each breeding step taking 10-20 tries. 

You can also totally lose progress, which is not possible with crops - the starting bees are consumed and new bees are generated from the originals. This leaves a small RNG change of a trait being completely deleted.

### Bees are tiered later than crops (for practical purposes)

Although bees can be practically started in LV (10% production apiaries, not alvearies), the breeding tree is exceptionally painful (as described above). Therefore, on average people practically avoid using bees at all until they can get oblivion frames (shortens crossing to 30s pre-WA) and have a thaumic restorer. Although this is technically MV, I usually see this HV+. Crops spike hard in MV, which means people will have already invested in them by this point.

### Setting up a productive bee complex is difficult

Because bees output themselves, you need a robust system for dealing with drone and princess outputs. (Think of if the crop harvester output the seedbags as well). This adds additional processing complexity. To sort these, my cheapest option was the apiarist's pipe from Buildcraft. But this led to problems as BC pipes don't play well with GT pipes. So I ended up using logistics pipes (which have BC integration) to import into the apiarist's pipe.

Without breeding special traits onto bees, they also will not survive/produce if you:

1. Don't give them clear line of sight to the sky (to bypass this, you need to breed cave dwelling trait onto the bees and use alveary lighting block).
2. Pack the alvearies too densely (because they are 3x3x3 multis, you need to have sufficient space around them, making them practically 4x3x4 units.
3. Don't provide the right environmental stats. The base environmental stat for bees cannot be changed, only the tolerance. Some bee outputs are locked out if you do not provide the right environment. To change environment (depending on which environment), you can need power, lava, and water. These must be provided to every single alveary multi for maximum flexibility. Crops are able to receive resources from a central block wirelessly/magically, bees are not. This leads to setups like this, which are much more complex than the comparable crop setup. I also later added an EFC (ender fluid conduit) line for lava/water supplies.
![image](https://user-images.githubusercontent.com/88752681/168673328-38820897-d360-4d71-9257-c645fa27f871.png)

### Bees are laggier
As described above by @boubou19 :
> I observed something like 0.2ms for a farm, while a WA can hit 2ms for 4 bees.
We need an alveary multi that solves a lot of these problems. It needs central collection and faster speed. It needs simplified logic or multiple bees that can be placed inside. It needs to not produce flowers in-world and grief everywhere near it. (It would be nice if it had an option for flower output, like a special bus).

### Bees lack an out of the box autobreeding solver
This isn't really a problem for devs to solve, but crops are now more interesting to late game players due to out of the box OC autobreeding solutions existing (https://gtnh.miraheze.org/wiki/Open_Computers_Crop_Breeding). I am not aware of anyone having an autobreeding bee system working in GTNH (although some exist for other modpacks). Because bees are later game skewed, this impacts bees especially heavily.

**Comment by Bigfluf** [comment]
I bascially agree with everything OrderedSet wrote. A few things I'd like to add in my experience with bees:

The main thing I feel is holding bees back is that the production cycles are locked at 27.5 seconds (without WAs) and every cycle can produce at most one of every comb the bee can produce no matter what. This basically severely limits the maximum output of every type of bee structure, resulting in just spamming more structures and/or WAs resulting in large amounts of lag. It destroys most of the variety in bee production as well, making a 5% chance for a comb the same as a 75% chance for a comb because both will likely be maxed at 100% with a few frames and decent production trait.

If this limit were removed allowing more than one comb per cycle, I feel it would open a lot of options for larger scale production. Especially if combined with a rebalance of chance to turn ignoble on higher than 16x production multiplier and the chance to lose ignoble bees in combination with those higher production multipliers, and a rebalance of the genetic stability of frames.
That way with enough frame housings and frame automation it could be possible to have very high production alvearies with the downside of losing princesses over time that you'd have to replenish somehow (and some downtime while the drones breed the new princesses back to the proper purebreed). Bonus points if it could be well balanced enough to be able to blacklist alvearies from WAs and/or make them competitive with industrial apiaries.
Maybe also increase the apiary production to make bees less useless before HV (like 50% of alveary instead of 10%), frames are impossible to automate in apiaries so they would still be very inferior to alvearies anyway.

My second point was a large annoyance while breeding through the bee tree, the 'biome shuffle'. Every bee has a required temperature and humidity that is hardlocked to the dominant species. With new mutations resetting tolerance alleles and species often flip-flopping between 3 species when trying to purebreed new mutations, having to switch bees between different biomes (through actual biomes or alvearies with heaters/fans/hygroregulators) became old really fast. Changing the better tolerances (both 2/3) to dominant with the worse ones changed to recessive would help a little, but in the long run I'd like to see some way to make fans/heaters/hygroregulators turn on or off depending on the currently active bee's needs automatically. The breeding will still be plenty of of a pain with all the foundation and specific biome requirements anyway.

**Comment by OrderedSet86** [comment]
Note also that WAs cannot be used on alvearies due to them being a multiblock. You can use them on industrial apiaries, but these are post platline and assline (LuV+). This either means you have to mega-parallelize and make a ton of alvearies until then, or work on frame I/O automation, which requires OC.

**Comment by redmage17** [comment]
Is any of the one with the knowledge working on this? Or interested, as lovely as an idea as this is I think working with forestry to get these running has been a huge issue. 

I'd like to add some possible easier fixes

Rework some of the lower tier recipes especially for the magic frames to be more viable without relying on the exploit with the thaumic restorer. Possibly adding some more new frames as well. The fact that you have to breed about ten lines of bees is ridicoulous just to get to the basic frames.

Increase the baseline mutation rates - this was nerfed very hard in the past. Even using an alveary with a mutation block it's very hard to get mutations. 

Or we can decrease the outputs of crop recipes to 1/4 and Triple their inputs along with "Tiering them"  
https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/10021

**Comment by Steelux8** [comment]
The whole problem is that there's nobody willing to work with Forestry on this. Not only when it comes to the code, but also learning the mechanics and numbers of the current system to properly balance changes to bee recipes. I, for one, am interesting in making bees viable but have no idea how they're supposed to work or what numbers would make them fit properly into the pack.

Additionally, I am against making bees strong and important to pursue, like crops currently are, if the intended way of using them is a mix of WAs or alveary spam. Those setups hurt performance or push for huge multiblock spam, which might detract from the overall experience of the pack. Those issues should be fixed first, but I'm aware that this is the hardest part to solve.

**Comment by Runakai1** [comment]
That's why I disagree to work on the hardest problem. Crop farms already use hundreds of blocks of space with crop managers. They already do have huge structures, it would be unfair to say bees shouldn't do the same. Industrial apiary has huge tps issues, that's true. But we're just delaying bee buffing by wanting to fix the most difficult issue

**Comment by Waisse** [comment]
What the alveary desperately needs is the following changes :

-Remove the 16x production multiplier limitation turning pristine into ignoble, let us squeeze as much out of a single multiblock as possible, because the alternative is just to build tons of alveary which is neither interesting nor lag friendly
-Uncap comb production chance. If I reach above 100% then I should be able to get more than one comb per cycle depending on the %.
-A way to tick accelerate the alveary.

**Comment by Steelux8** [comment]
> What the alveary desperately needs is the following changes :
> 
> -Remove the 16x production multiplier limitation turning pristine into ignoble, let us squeeze as much out of a single multiblock as possible, because the alternative is just to build tons of alveary which is neither interesting nor lag friendly -Uncap comb production chance. If I reach above 100% then I should be able to get more than one comb per cycle depending on the %. -A way to tick accelerate the alveary.

Tick acceleration will not be added for automation purposes. It is bad for performance and it becomes worse the more it is used (and bees are a place where it would be used a lot of this happened). New implementations have to focus on increasing the output of each bee tick, not making the ticks go faster.

**Comment by Waisse** [comment]
My other suggestions still stand, the alveary just need a massive boost in production to compete with the alternative. Being limited to one product per  cycle of ~30s is way, way, way too low, and single digit specialties aren't even guaranteed even at the highest frame multiplied and a good production trait.

And since I've run into the issue today : uncap the limitation on climate modulation with fan/heater/hygroregulator. Right now I can't get to icy temp (0%) in a 50% temp biome, which sucks.

**Comment by Runakai1** [comment]
Leaving this open for further suggestions. 
Balance PR: https://github.com/GTNewHorizons/GT5-Unofficial/pull/1166
