### ISSUE TITLE
[RFC] Make t2 rocket harder to build, and separate EV from IV

### ISSUE THREAD

**Issue by Steelux8** [GTNewHorizons/GT-New-Horizons-Modpack#10251]
### Your GTNH Discord Username

Steelux#1934

### Your Pack Version

2.1.2.3

### Your Proposal

Making the main gate to IV harder, the t2 rocket, in order to bring players to do EV content in EV instead of speedrunning to IV, and then spending a very long time stuck in that tier.

### Your Goal

I've talked with a lot of people and heard something pretty often, which is that IV has too much content and EV doesn't seem to have much to do. This is mostly because moving from EV to IV is very easy and can be done early, unlocking a lot of IV content, mainly the powerful GT++ multis. Tungsten can be sourced easily from t2 planets, making this step smooth if you can put together the relatively cheap t2 rocket.

There are many ways to put more weight on EV, but I think the main one is to change the difficulty of moving up a tier here. HV to EV is difficult, because the t1 rocket + the NASA Workbench are difficult pieces of autocrafting with no AE2 to speak of; IV to LuV is even more difficult because making the assline is required, and it needs 70-something max-tier IV circuits, a ludicrous expense. Meanwhile, EV to IV is much simpler than either of those.

As an example, here's a list of EV content that never, or rarely gets used in EV, only IV:
-> The best circuit of the EV epoxy line, the LuV circuit, rocket doesn't need it;
-> Big amounts of platinum, the plat part of the platline is EV but there's no need to fully automate it, just do it in EV;
-> Radon automation, very small amounts are needed and the rest can be obtained from uranium nukes in IV;
-> Titanium chemistry, small titanium ore exists in t2 planets and can skip the processing altogether;
-> Arguably, thorium nukes, since they are mostly for breeding and uranium is very easy to get from t2 planets, and more powerful, there are also more ways to make lutetium now;
-> Complex AE2, the t2 rocket is made easier by disassembling the t1 one, AE2 automation is just another IV task.

And here's a list of EV quests in the book that are actually IV content:
-> The fiber-reinforced epoxy line, it's literally an EV line and using a lapotronic energy orb to make a PA is not feasible because of the tungstensteel cost for most players, until you get to IV;
-> The quantum crystal, the quest itself says it's usable in IV;
-> The PSS quest, it's literally an IV multi!

As a result of all this, the EV tier seems minimal compared to the tiers before and after it, in part because it doesn't have a hard gate.

### Your Vision

Changing the t2 rocket and/or the t1 thermal padding to be required, and more expensive, would make more EV content be done in EV by more players. The end of the circuit line, in this case being LuV, should be needed, as they were for the t1 rocket and the assline after. Platinum should also be needed in large quantities, in order to reinforce the need for this part of the platline in EV and take away some chemistry of the several long processing lines that IV now has.

I welcome suggestions for what the change should be like. In general, I think that bringing more content to EV from IV is a good idea, and this is a good way to achieve it.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by glowredman** [comment]
The recipes of the T2 rocket components leave not much room for changes since many parts are also used in other rockets (e.g. Nose Cone, Fins, Boosters, etc.). The only items which could have a changed recipe are the "Lander Tier 2" and the "Rocket Control Computer Tier 2". Changing the CC recipe could only be done by having it require an EV Emitter/Sensor (the other items cannot be changed since all CCs use the same scheme).

**Comment by chochem** [comment]
I very much agree with this approach. At the moment EV can feel like a very short age with mainly AE2 as content which is of course not even required to proceed. The only gate to IV is easy access to Tungsten which is achieved by the T2 rocket. And it only takes 3 EV machines, a bunch of silicon rubber and 3 tungsten dust for the player to start crafting the T2 rocket and thus proceed to IV. Making some more EV content 'required' would be a great change taking some of the load of IV.

For me the obvious candidates are
- the LuV circui`t. maybe add it to the T2 control computer recipe. (Actually there always used to be a T+2 circuit in each rocket for a long time, maybe go back to that in general?)
- significant amounts of platinum (not sure where though, maybe in the IV motor?)

**Comment by Alrightsc** [comment]
> The recipes of the T2 rocket components leave not much room for changes since many parts are also used in other rockets (e.g. Nose Cone, Fins, Boosters, etc.). The only items which could have a changed recipe are the "Lander Tier 2" and the "Rocket Control Computer Tier 2". Changing the CC recipe could only be done by having it require an EV Emitter/Sensor (the other items cannot be changed since all CCs use the same scheme).

The problem is that changing T2 to require EV emitter/sensor mean the sifting recipes for radon become impossible until T2 planets. So instead you're forced to open nukes in start of EV by using uranium rods (obtained from thorium ore byproducts which spawn in Nether), then getting plutonium out of depleted uranium rods and smelting till you have enough for 1 ingot of plutonium to start the radon cycle. At that point I feel adding a T+2 circuit would be more thematic/in line with progression.

I also support making IV motors cost some form of platinum - platinum cables could be a smooth replacement for IV motors instead of tungsten wires (and keeping graphene wires, which could use super glue that Steelux was planning to do).

**Comment by Steelux8** [comment]
> The recipes of the T2 rocket components leave not much room for changes since many parts are also used in other rockets (e.g. Nose Cone, Fins, Boosters, etc.). The only items which could have a changed recipe are the "Lander Tier 2" and the "Rocket Control Computer Tier 2". Changing the CC recipe could only be done by having it require an EV Emitter/Sensor (the other items cannot be changed since all CCs use the same scheme).

If it has to be the Lander, so be it. I think the rocket is the best thing to change to push IV away from players speedrunning it, even if the final cost of the Lander becomes different from the others. 



> > The recipes of the T2 rocket components leave not much room for changes since many parts are also used in other rockets (e.g. Nose Cone, Fins, Boosters, etc.). The only items which could have a changed recipe are the "Lander Tier 2" and the "Rocket Control Computer Tier 2". Changing the CC recipe could only be done by having it require an EV Emitter/Sensor (the other items cannot be changed since all CCs use the same scheme).

> I also support making IV motors cost some form of platinum - platinum cables could be a smooth replacement for IV motors instead of tungsten wires (and keeping graphene wires, which could use super glue that Steelux was planning to do).

The glue line has a tungstensteel chemplant, it's too expensive to gate IV motors behind it. Graphene is also changing, from what I hear, still don't know how it's going to end up like.

Platinum wires is a great idea, though, although I'd like a bigger platinum wall to make people automate it in EV instead of batch crafting a few IV motors and then getting the rest from lootbags.

**Comment by MuXiu1997** [comment]
I hope it's not just about limiting players with a higher threshold, it's just as important to give ev more playable content

**Comment by POPlol333** [comment]
Yeah actually as an early UHV player I would feel bad if they continue adding component from the platinum line in early tier, past IV they are all mainly composed of these platinum metal, in dumb quantity. Since we still don't have any solution to fix the necessary lag we make by producing enough for our LuV+ need it would be even more unpleasant for everyone to add platinum in IV component that we still have use for

**Comment by boubou19** [comment]
stealing IV content to put it in EV is a bad idea because EV has no real content beside AE. That means there is nothing to do and it's natural to skip infrastructure exepansion. Shifting content one tier below just to fill stuff will just be seen as a useless nerf. Instead of stealing content from other tiers maybe we should look into adding new content first, so we could justify the need to take some content from IV to support the addition of such content.

**Comment by Steelux8** [comment]
> stealing IV content to put it in EV is a bad idea because EV has no real content beside AE. That means there is nothing to do and it's natural to skip infrastructure exepansion. Shifting content one tier below just to fill stuff will just be seen as a useless nerf. Instead of stealing content from other tiers maybe we should look into adding new content first, so we could justify the need to take some content from IV to support the addition of such content.

Adding content to EV is a better solution, but also much harder. There are things from IV that are hard to replicate in EV, like the GT++ multis for example, and there are also several EV multis that need lots of tungstensteel, a material that you can get before t2 planets but at a very slow rate. EV having no real content of its own is a bad idea, from my point of view, honestly speaking.

**Comment by miozune** [comment]
Since now we have complex lanthanide line, how about make PBI line EV tier?
