### ISSUE TITLE
make every advanced kind of goggles of revealing display altar's stability

### ISSUE THREAD

**Issue by boubou19** [GTNewHorizons/GT-New-Horizons-Modpack#10258]
### Your GTNH Discord Username

boubou_19#2706

### Your Pack Version

2.1.2.0

### Your Proposal

since this (https://github.com/GTNewHorizons/TCNEIAdditions/pull/6) is now a thing, it would be neat to have something to see visually the the instability level of the altar.

### Your Goal

This would just be a QoL change, as it's already possible with the arcane abacus from witching gadgets ~~(and from some waila packet abuses)~~

### Your Vision

It would add more roleplay to the goggles, as it could be justified by thaumcraft research progression, like techy version of the goggles, or new ability developped by warp idk, it would be kind of cool in my opinion.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Runakai1** [comment]
I really love the idea. Displaying things is always QoL. Especially altar Stability, makes thaumcraft less of a burden.
Would also be cool if the nugget duping list would name the nuggets so you don't have to hover over it :)

**Comment by Alastors** [comment]
Obviously this is meant to be a change to how certain advanced goggles work, so I'd just like to mention, you should potentially add the warped goggles potentially, it'd fit into their lore given that one of the lenses is corrupted by warp, but it should almost definitely be on the voidmetal goggles, given that those are technically the endgame set of "goggles" (yes I know the infinity set is technically goggles, and blah blah blah, but it really isn't) I just wanted to make sure the voidmetal ones got the love as well if this is the route y'all do.


############################################################################################

**However, I'd like to make a counter idea:**

What how about instead of making this a feature to the goggles specifically, we make a second slot for lenses, honestly we don't have enough lenses, but we could potentially do so much if we made a second exclusive slot for the new set of lenses, and we could make one that shows the instability of the infusion altar, so that every set of goggles could achieve the feature, and not just a few specific sets, since some people do wear them for aesthetic. (yes I know the apparel appearance infusion recipe does exist, it's kinda stupid in execution in my opinion, given that it legit eats the desired look's item.)

and honestly, we could even make the second lens slot lenses actually appear over one of your goggles, which would be sort of neat, if we could do it anyway, I feel like it'd be very possible, whether we make a system similar to the GTNH ingot and ore system where it just autofills into it but overriding the default texture and whatnot. I know this is probably a lot to ask, given that it'd be an entirely new texture system likely. But it could be a lil neat feature given that it's lame as fuck that the normal lenses don't show up physically on the goggles smfh.

idk feel free to let me know if it's a stupid idea or not, I just like the idea of having more lenses instead of just specifically adding a lil buff, given the potential for more later down the line, but maybe that's just me idk, but given that thaumic horizon's dev is dead obviously not suggesting y'all strip the lens code to make a second, but like, deadmen can't cease and desist so maybe it might be worth to peek at the code and compare notes? idk

**Comment by boubou19** [comment]
now that i think of it, we could even decline the lenses to add some crossmod compat, like mana lenses to see the exact amount of mana in the manapools, BM lenses to see progress on the altar, as well as different kind of infos, ... stuff like that.

**Comment by Alastors** [comment]
> now that i think of it, we could even decline the lenses to add some crossmod compat, like mana lenses to see the exact amount of mana in the manapools, BM lenses to see progress on the altar, as well as different kind of infos, ... stuff like that.

yeah more lenses would be a fun lil sideproject force Jakob to do it or whatever lmfao

**Comment by Rika-TH** [comment]
Bump, these suggestions sound cool and we do have an issue open regarding extra lenses, #13735 personally unless a dual lens foci pouch was added I wouldn't want this as a lens, similarly would be nice to have an auxilary lens slot to go with it
