### ISSUE TITLE
Aroma backup -> Yet Another Backup Mod

### ISSUE THREAD

**Issue by Zereff06** [GTNewHorizons/GT-New-Horizons-Modpack#10314]
### Your GTNH Discord Username

Кетцаль#0802

### Your Pack Version

2.1.2.1

### Your Proposal

"Aroma backup" is a crap backup mod, the only plus is set the backup from the game.

I suggest replacing it with "Yet Another Backup Mod", which has a lot of handy settings for creating backups.
For example, you can choose what to back up, where to back up to. has 2 modes for daily backups and weekly backups

This will make backups, storage, and restoration much easier

### Your Goal

.

### Your Vision

.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Chaoschaot232** [comment]
I am definitly against swaping Aroma Backup against any other Backupmod as this would end up in missing compatibalitiy with the new backup mod. Well, you can download the file and unpack it on you local machine and re-upload it but this is wasted time if you have commands for this or at last access to the servers consol.

Also it is definitly better to have every time a full backup and set in the config how many backups you want to store and how often you want to backup. For my server it is currently every 15 minutes with at last 5 backups in the folder. Doing only daily or eventually weekly backups is smth. what I am not recommend because when things going wrong and you get world corruption it wouldn't make fun to load a backup older than a few hours as players usualy don't want to do progress again and on top not with this modpack as some parts are realy pain in the ass -.-# 

That is my personal statement to this which results in permanently staying with Aroma Backup.

Maybe it could be altered and get some more functionality which is better then throwing it out for another mod.

**Comment by Zereff06** [comment]
The thing is that the problem may not be noticed immediately. For example, the player made a system to get steam and left the game. Boiler blew up, and the player noticed only the next day or even later (or any situation where you do not immediately see the problem).  If there's a backup like yours, it's a problem and there's no way to recover. If there is a weekly one, you can easily replace just the player base chunks.  

Think about different planets, like ROSS . Players increase the size up to +5gb, is it so necessary to back up ROSS?  

Not everyone has a server and not everyone is willing to allocate a lot of space for backups.
