### ISSUE TITLE
Add Gallium Arsenide Mixer Recipe Back

### ISSUE THREAD

**Issue by henrydukepickle** [GTNewHorizons/GT-New-Horizons-Modpack#10350]
### Your GTNH Discord Username

henryduke#0140

### Your Pack Version

2.1.2.4

### Your Proposal

Not a complex change, but add back the recipe to make 2 Gallium Arsenide Dust from 1 Arsenic Dust and 1 Gallium Dust in an LV mixer.

### Your Goal

MV Circuits should be available pre-EBF, in my opinion.

### Your Vision

MV circuits would be available before EBF, and thus the LV CA, and also gallium, which is in short supply in LV, would yield more.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by cubic-chariot** [comment]
One possible implementation is to add a new type of silicon boule (say, "primitive silicon boule") that can be made in the alloy smelter and which can be used to make diodes. Something like this:
- Add recipe `As + Ga -> 2 AsGa` in an LV mixer
- Add recipe `AsGa dust + 8x raw Si -> 1x primitive silicon boule` in an LV alloy smelter
- Add recipe `1x primitive silicon boule -> 8x wafer + 1x raw Si` in an LV cutting machine
- Remove all assembler recipes that make diodes from small gallium arsenide dusts.
This would allow players to produce Good Electronic Circuits without gating them behind the EBF, whilst still introducing players to the `silicon -> boule -> wafer -> circuit` pipeline. (It even requires players to use silicon to make MV circuits.)

If making silicon wafers without solar-grade silicon is undesirable, an alternative solution is to add a "primitive wafer" that is the output of cutting the primitive boule, and make it substitutable for the wafer for making diodes only.

Yet another alternative is reducing the output of cutting the silicon boule to just `4x wafer + 1 raw Si`, and adding recipes like `4x fine annealed copper wire + 1x wafer + 1000L molten glass -> 2x diode` to the assembler. Currently annealed copper can only be used with molten polyethylene; this would nudge players to use annealed copper instead of "regular" copper.

**Comment by Glease** [comment]
Some attention is needed here.

**Comment by chochem** [comment]
pretty sure dream is against it. This change was on purpose. Can stay closed imo.

**Comment by Glease** [comment]
So the intention was to push LV circuit assembler behind EBF? I thought EBF mark the begin of MV age, no?

**Comment by chochem** [comment]
you do EBF before MV circuits now, yes. Questbook was adjusted to that as well.
