### ISSUE TITLE
  About the unlocking of Lingbao in mysterious magic（有关神秘魔法灵宝解锁问题）

### ISSUE THREAD

**Issue by 847895947** [GTNewHorizons/GT-New-Horizons-Modpack#10380]
### Your Pack Version

2.1.2.3

### Your Server

sp

### Type of Server

Don't know

### Your Expectation

Unlock Lingbao researc（解锁灵宝研究）
![47IN0X6{~L{(09OA2WGSZ`B](https://user-images.githubusercontent.com/106101377/169862858-69834e8a-fc5e-481b-b34d-37494d9b3b3c.png)
h

### The Reality

Mysterious research and mod are all unlocked with research completer, but Lingbao has not yet appeared.（神秘研究及mod全部用Research Completer解锁，但灵宝仍未出现。）

### Your Proposal

Normal unlocking

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
I guess Lingbao means Ichorium. This is an old issue that was never really fixed or at least keeps coming back: https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/6343

Basically Ichorium has additional secret research requirements at the moment, so just keep on researching and it will unlock eventually. (or hope for a fix of course)

**Comment by PolkageistHS** [comment]
Right now it's locked behind all of the research in the first 6 tabs plus Thaumic Tinkerer, which wouldn't really be an issue... except now there's a new research called TINKERSAUGUMENTATION that I can't find any trace of.  I have no idea how to unlock it, I can't find where it's being added, and no idea if it's even intentional.  Unfortunately, I just got a new PC so I don't have a dev environment set up to try to debug in game, but hopefully someone else knows what it is.  I can only find it in test worlds by adding it with commands.  
![image](https://user-images.githubusercontent.com/9247381/171778787-8916e133-6eef-458f-8c29-aa9bc19601b5.png)

**Comment by chochem** [comment]
fixed by https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/pull/10535
