### ISSUE TITLE
Zinc sulfate inconsistency 

### ISSUE THREAD

**Issue by Miisi** [GTNewHorizons/GT-New-Horizons-Modpack#10431]
### Your GTNH Discord Username

Misi#3673

### Your Pack Version

2.1.2.4-4-zeta

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

processing rhodium sulfate solution needs 1 zinc dust and gives back 6 zinc sulfate, which should be recycled back into 1 zinc dust

### The Reality

zinc sulfate can be recycled into zinc dust at a 1:1 ratio, essentially materializing zinc out of nowhere
![image](https://user-images.githubusercontent.com/46682682/171745522-a3d950a7-6cad-44a8-8d5f-3ede03452864.png)
![image](https://user-images.githubusercontent.com/46682682/171745551-bc955309-0561-403f-8e89-452a5b70bb7b.png)

### Your Proposal

change the chemical reactor recipe or reduce the zinc sulfate output from processing rhodium sulfate solution

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
there is also this recipe (which is more sane):

![image](https://user-images.githubusercontent.com/40274384/172874003-0a293b77-cd79-4ad9-b0b2-e5c2e9e5edd1.png)

that is probably the older one.

Therefore the first recipe (zinc in, 6 zinc sulfate out) should not be changed. Rather change the second one to need 6 zincsulfate instead of one.

This is likely a new recipe. I guess the question is where from and how do thing work there? I guess its a naqline thing 
![image](https://user-images.githubusercontent.com/40274384/172874715-8eb1049b-5199-421b-b3bd-14fc80447acb.png)

I dont know anything about naqline though.
