### ISSUE TITLE
[Project Red] Inverted white lamp sometimes not having the light level

### ISSUE THREAD

**Issue by trollolal** [GTNewHorizons/GT-New-Horizons-Modpack#10453]
### Your GTNH Discord Username

timlam

### Your Pack Version

2.1.2.4-5-dev-pre-test

### Your Server

SP

### Your Expectation

Inverted white lamp should have light level of 15 all the time

### The Reality

It sometimes do not have the correct light level and let the mob spawn despite the area is lit

### Your Proposal

fix it

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by DarkAmbientNoise** [comment]
I'd like to add to this, that at least on GTNH 2.1.2.0, Inverted Project Red Lamps, and even a simple Glowstone Block all have a block light level of 13, but the Flat Lamps from Ztones register it as a block light level of 15.

Pressing F7 to see the spawn locations shows that nothing can spawn if you set up a grid of these lights in a 7x7 area, the corners being the Project Red Lamps, or 5 blocks between each light source, the spawning overlay says everything is good, but it leaves a block with BL:7, causing spawns.

Is this an intentional modpack change? I am running Optifine despite it not being recommended, not sure if this is yet another issue with Optifine, as it is with mobs spawning on GT Smooth Concrete, which is also the case in my scenario.
