### ISSUE TITLE
Space station chunkloading stops on server restart

### ISSUE THREAD

**Issue by greesyB** [GTNewHorizons/GT-New-Horizons-Modpack#10512]
### Your GTNH Discord Username

Greesy#2016

### Your Pack Version

2.1.2.3qf

### Your Server

Private

### Your Expectation

Space stations should be chunkloadable like other dims with either FTB or admin anchors.

### The Reality

After server restart, space station chunks are not loaded until visited even with admin anchor, resulting in siphons not running. I noticed this with admin anchors, but Mudspaw reported it happening with ftb as well - https://discord.com/channels/181078474394566657/234936569360809996/988076129686532096

### Your Proposal

Allow space stations to be chunkloaded like other dims

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by AlbertoPirillo** [comment]
Reopening as it is very related: this change has no effect on already existing space stations. To be accurate, I think it breaks them since chunk loading on my space station was working fine before switching to 2.2.0.0, where it does not work. 
I managed to fix it by manually entering in the GC config the dimension id of the space station.
Maybe you can find a better and automatic way.

**Comment by GTNH-Afx237v7** [comment]
I have the same issue. My space station was build in pack version 2.4.1, I have meanwhile updated to stable 2.5.1. According to xSkewer's change in the config, it should be static loaded, but when I start the game I have to manually visit the space station, otherwise the planetary gas siphon won't run. There is also an admin anchor to keep this chunk loaded.
