### ISSUE TITLE
Disable or fix the essentia condenser

### ISSUE THREAD

**Issue by chochem** [GTNewHorizons/GT-New-Horizons-Modpack#10522]
### Your GTNH Discord Username

chochom#0271

### Your Pack Version

2.1.2.4 5-dev-pre-test

### Your Proposal

There is a seriously game breaking bug caused by the essentia condenser (I assume there are probably reports on the hidden exploit github regarding details and have been for a while). This knowledge has been floating around for quite some time but has become more prominent to the point where a good number of people are abusing it now.

As there has not been any fix for all this time, I am assuming that it might not be easy to fix. Therefore, **I propose to disable the essentia condenser**. It can be re-enabled when it is fixed.

Essentia storage is still doable with AE essentia storage cells which are also quite affordable now since they got the circuit assembler recipe.

### Your Goal

Major bug exploits are bad.

### Your Vision

The game is better without serious bug exploits.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

Edit: removed some details to not make things worse :P.

**Comment by Alastors** [comment]
I also have nothing against it being fixed, but it will likely be a pretty decent amount of work. I'd take a wild guess and say that the issue is that it uses the jar interface from thaum, but it doesn't use the normal part of it where it would take in and give out essentia using pipes, but instead only takes the golem part and the part that allows jars to give infusion altars streams of essentia. With that, I would guess that it uses the infusion interface to attract essentia from jars, like we can obviously note from how it sucks directly out of jars like the infusion altar.

My best guess would be the AE compat addon doesn't actually detect if the jar can actually be taken out of, and instead detects whether this side could be input from and then pushes/pulls into that side if it can.

You use them golem bells on the top or bottom thirds of the condenser, if you try the middle it doesn't work.

This just so happens to be the two blocks that the essentia interface works on, and likewise not the middle, and since the condenser doesn't have any scripts to push/pull that way since I'd think the interface acts like it is pulling from a normal jar, because of the missing interactions, the condenser itself doesn't lose any essentia while the AE system pulls a point from nothing.

If anyone is confused by what I mean, sorry, I'm sleep deprived again, @me and I'll rewrite whatever

**Comment by repo-alt** [comment]
Valid side to interact the condenser for the storage bus is center btw. Also it does not allow inserting essentia this way, only extraction.

**Comment by chochem** [comment]
thanks for trying to fix this @repo-alt. Though according to @maniifestantes on zeta the fix didnt work. https://discord.com/channels/181078474394566657/181078474394566657/992494807228370964

Of course there is now also the alternative being discussed to move the recipe to UEV+ which is weird but I guess works as a solution.

**Comment by repo-alt** [comment]
The fix is not on Zeta

**Comment by chochem** [comment]
the fix did not work.

**Comment by Alastors** [comment]
One day...

**Comment by chochem** [comment]
still very much a major unresolved issue

**Comment by Alastors** [comment]
> still very much a major unresolved issue

agree to disagree but fair, this won't happen until the underlying issue itself is solved.

**Comment by OneEyeMaker** [comment]
@chochem @Alastors and everyone else. Nuke can wait. I found cause of dupe.

1) [*Every block of Essentia condenser*](https://github.com/GTNewHorizons/Gadomancy/blob/master/src/main/java/makeo/gadomancy/common/blocks/tiles/TileEssentiaCompressor.java#L622) returns aspects of master block of multiblock.
2) But adding and extracting essentia [*is allowed only on center block*](https://github.com/GTNewHorizons/Gadomancy/blob/master/src/main/java/makeo/gadomancy/common/blocks/tiles/TileEssentiaCompressor.java#L662).
3) ThE (when connected to non-center block of Essentia condenser) checks whether there are any aspects (check succeeds because condenser return aspects of master block) and then extracts essentia *without checking success of this action* and fills containers.

Ways to fix:
1) Disable `this.multiblockYIndex == 1` check of Essentia condenser to allow extraction and insertion on every block (accordingly to `getAspects` logic).
2) Change logic of `getAspects` to return aspects when accessing central block.
3) Add check to [ThE logic which performs real extraction](https://github.com/GTNewHorizons/ThaumicEnergistics/blob/master/src/main/java/thaumicenergistics/common/inventory/HandlerEssentiaStorageBusContainer.java#L250) so it returns item only when real action succeeds.

P. S. Alastors, I apologize for *this* ;)

**Comment by Alastors** [comment]
Lmfao yeah that's been known, someone attempted the 3rd fix like a year ago. But lmfao, don't worry about stopping my nuke, if you fix it there's no reason for the nuke to exist lmfao
