### ISSUE TITLE
AE2 Crafts will not start despite simulation showing it as valid.

### ISSUE THREAD

**Issue by TNaud** [GTNewHorizons/GT-New-Horizons-Modpack#10590]
### Your GTNH Discord Username

Default#1462

### Your Pack Version

2.1.2.4-dev-pre-test

### Your Server

SP

### Your Expectation

Queuing up large complicated crafts simulates a recipe and shows the recipe as valid and able to start.
![image](https://user-images.githubusercontent.com/35411589/176742909-47bf2ee4-a537-4c07-9d78-5a5e7192e452.png)

### The Reality

Clicking the start button does nothing and craft will not start. I have to re-simulate the recipe dozens of times before it will actually start.

### Your Proposal

I suspect based on my testing this occurs because some of the items it simulated in the craft disappeared in the time it took to simulation via an export bus or something of that sort. Maybe could be fixed by having the simulation actually pull the items out of the network and stop them from being exported or manipulated by other things. At the very least it would be nice if the UI would show what item is causing the failure.

From what I have heard on the discord this only occurs for people with really large networks and bases. If you don't have that to reproduce it I can supply my world which will almost always do the error whenever I try to craft a few UHV or UV field gens. 

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by TNaud** [comment]
You can actually reproduce this pretty easily by making a pattern that is something like 1 A -> 1 B, putting some A in your network, setting an export bus to export A out of the network, and then attempting to craft some B. If you wait long enough on the simulate the craft button will still be highlighted even after all the A are gone. Obviously in this example you have to wait a couple seconds but on a large enough network with a complicated craft and enough exporting going this can happen instantly.

**Comment by repo-alt** [comment]
It is an old bug, not fixed even in 1.18 and the proposed fix there is just to give meaningful error message.

**Comment by EnderProyects** [comment]
there are cases in which it happens and it's not a bug, for example if you use items that are in a compacting drawer, so applied has to remove "duplicate" items that really aren't, and doesn't let the process start

**Comment by repo-alt** [comment]
Well, the bug is failing silently. Reasons may be very different.

**Comment by repo-alt** [comment]
(upstream issue https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/5884)

**Comment by GTNHAfx237v7** [comment]
Then a log message about why it fails would be nice. Eventually it is not ae2‘s fault that items needed for a craft are gone while calculating takes place, this should be up to the user to manage.

**Comment by joshaup1999** [comment]
Just had this issue happen to me when requesting a sextuple compressed solar that was working. Had to reorder it since the server restarted, but i changed the recipe for 1 thing, Plastic CB to use PTFE instead of PE. This cause the craft to not start when I'd click start. Changed the recipe back to using PE and it worked just fine

**Comment by realthecaffiend** [comment]
This is a long-standing AE issue but I'm here github posting because I'm running into it, again. 

Reserving items that are simulated would seem like the best answer, at least as an *option* when trying to craft? I believe, based on AE showing things like: Copper plates, 300k, to craft, 400k, missing,: three, in the sim screen when I am out of something else unrelated, that it doesn't require you to be actually out of some item, just enough item movement (Or maybe one drive/storage bussed super chest runs empty?). So even though an error of "Couldn't make 3 copper plates" would help a little, it doesn't actually address the issue IMO.

Holding shift to change next, to start, sometimes helps: I'm presuming that this is simply due to less time between the simulation and kicking off the craft. Could holding shift to go straight to crafting *also* reserve the items as it's simulating? This should mean it doesn't impact casual users at all, and gives large scale bases an option other than doing some manual sub-crafts to baby it through, much of which is guessing on what may be "failing"

Also I admit that I think the label of minor for this is inaccurate, as it's becoming more and more annoying as we start stargate prep, and seems like it's going to result in having to constantly do small sub-crafts.

**Comment by Technici4n** [comment]
AE2 dev here. There is nothing we could do to fix the underlying issue. A few things to think about:
- There is no guarantee that items that are taken during a simulation can actually be put back in the network (e.g. extract-only storage bus).
- If part of the network is unloaded while the simulation is being ran, then there is no place to put the item backs if the simulation is cancelled.
- Currently the state of the simulation doesn't need to be persisted when the server stops because it can just be discarded. Reserving items would need the simulation to be serialized entirely; not necessarily hard but very painful.
- Etc...

**Comment by greesyB** [comment]
Aside from simulation persistence, wouldn't the same issues apply to cancelling an in progress craft? I've not heard any complaints about issues with craft cancelling.

**Comment by Technici4n** [comment]
Cancelling an in-progress craft keeps all the items in the crafting CPU's inventory as long as necessary (i.e. as long as the network doesn't accept them back).

**Comment by greesyB** [comment]
I understand. From the outside this sounds solvable (though hard to implement and make user friendly) with the addition of optional "simulation cpus" that, if any are available, handle the entire simulation process while reserving items and offload themselves to a crafting CPU when ready.

Or maybe a new craft option that allows you to select a crafting CPU before simulation, making the CPU do simulation work.

One potential bonus of either of these implementations is that it could allow starting and walking away from huge endgame simulations that may take several minutes even to simulate, instead of sitting on a simulation screen until it is ready.

**Comment by Technici4n** [comment]
I think this option also has its challenges, but it could be made to work. It would require some pretty significant changes in the underlying logic though. ;)

**Comment by realthecaffiend** [comment]
Yeah I don't think it's a trivial amount of work to implement, at all. Thanks Technici4n for dropping by also to lay out some difficulties; I never thought of an extract only storage bus, for example. There are always edge cases.

Also I made an assumption above: I *assumed* the below error was what was causing the craft to fail, when I have plenty of the item, can craft the item, and something somewhere moved. This only shows up however when something is actually short: Is this the bug or is this something different? Also any details as to what I could "fix" as a workaround, is this caused by wood pulp being in two different storages or just a single pulp of a hundred thousand being extracted somewhere?

![image](https://user-images.githubusercontent.com/8347355/191583661-5752a501-14d8-49cb-93f5-6ce68440570e.png)

**Comment by Szajkop** [comment]
What if there would be some kind of fast re-evaluation of the already calculated items where u already got all the ingredients and sub-ingredients. This check could run fast coz its not doing any in depth search, just going through the list of items to find out atleast the required ammount is exists.

This function would run when pressing start and could give back the error message if something actually missing. Otherwise it starts the job as calculated in the first step.

Or when the first calculation is done it returns an estimated byte ammount it needs to run the craft. Next step you reserve a cpu to do that job and the cpu will start loading in the ingredients. When something is missing it could wait until everything is available or the user cancels it.

**Comment by realthecaffiend** [comment]
As Sampsa mentioned in discord, the fix to at least error out to show what failed was applied upstream: Would this be difficult to backport?

**Comment by Tommeh1** [comment]
I do not believe that my issue is identical, as it can occur to even the most simple recipes with millions of the required items in stock.

**Comment by dahgul333** [comment]
had the same problem (2.2.0.0-eta) add vanila-AE 64k Crafting storage and craft finaly start ...

**Comment by chochem** [comment]
two bits of news about this one:
1. there now is an error message that lets you track down the culprit!
2.  it is worth reading this particular case https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/12826#issuecomment-1470986172 . This obviously wont be the cause all the time but AtomicGreg might not be the only one either. Basically they had certain materials accessible via 2 (!) storage busses which let the calculator think there is enough but then when AE finally wants to take it it cant actually get enough! This was only found due to the new error message.

**Comment by Tommeh1** [comment]
> two bits of news about this one:
> 
> 1. there now is an error message that lets you track down the culprit!
> 2. it is worth reading this particular case [AE2 pattern substitutions will break crafting further down the line #12826 (comment)](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/12826#issuecomment-1470986172) . This obviously wont be the cause all the time but AtomicGreg might not be the only one either. Basically they had certain materials accessible via 2 (!) storage busses which let the calculator think there is enough but then when AE finally wants to take it it cant actually get enough! This was only found due to the new error message.

This issue will still allow the crafting to start, but items will get stuck on scheduled if subs are enabled somewhere.

**Comment by chochem** [comment]
I did not link your ticket but that specific comment.
