### ISSUE TITLE
Give personal dimension at HV [RFC]

### ISSUE THREAD

**Issue by maniifestantes** [GTNewHorizons/GT-New-Horizons-Modpack#10616]
### Your GTNH Discord Username

maniifestantes

### Your Pack Version

2.1.2.4-14-pre

### Your Proposal

The personal dimension being tiered so high is weird, because by the time you get it, you already have your base planned, which makes moving it really annoying.

### Your Goal

Changing it to an earlier time would be better, i'd say to give it once you have done your t1 rocket, as that's when you get titanium, and when some people start their ae2 time, which makes it a perfect time to move.

### Your Vision

.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Devtron3D** [comment]
Ill be honest this makes sense.
Many when they get it have AE and a LOT of stuff automated, we could go the hard-luck way and say that's life. 
But we also need to consider what issues come from this.
When people start packing up their base in IV, they have a LOT of stuff, barrels, super tanks, ME storage cells, drawers and so forth.
Most when moving at that point want to do it is as few trips as possible, so they trow a lot of stuff in ME cells, or compressed chests, like dollys with drawers and barrels. 
I know from personal experience how easy it is to cause errors to your player file when doing this, or corrupting a chunk.

**Comment by Sovereignty89** [comment]
If we take the benefits of a personal dimension and place them in a list, we can better understand the possible balance implications.
Personally for me I see 3 benefits;
1. No monsters
2. Always day (is this still the case with Personal Space?)
3. FPS friendly and most headroom for expansion due to practically 'empty' world

1) Monsters
There comes a point in the pack, personally for me it's when I get a Nano Suit, that monsters aren't an issue anymore. Even with their crazy Infernal Mobs buffs, especially if you couple a Nano Suit with a good crossbow. The more you progress in this pack, the less you leave your base. You still need to go to specific dimensions to progress so you are still subjected to monsters. But long before HV mobs shouldn't be an issue in/around your base.

2) Always day
Acquiring always day 2 tiers earlier (at HV instead of IV) can be seen as a possible balance implication. However, I believe the difficulty that comes in creating (decent) solar panels outweighs the benefit of acquiring an always day dimension 2 tiers earlier. The solar panels themselves are still gated far beyond HV and it's impossible for someone to switch their base to completely solar just because they got their hands on a always day dimension at HV instead of IV. 

I don't think number 3 needs any explanation. This basically benefits everyone. There is the most overhead left to expand your base as you desire without the nagging feeling of 'I might've gotten x-amount of fps more had I moved and built in void'

As a final note, the infrastructure necessary to get to a tier 3 rocket (now coupled with tier 3 rocket fuel) is a lot. It might be too high of a mountain to overcome for some people, who struggle with the decision of moving dimensions (for whatever benefit). They end up burning out thinking of such a monumental task as moving a IV-tier base, I know I have.

I am for this change.

**Comment by realthecaffiend** [comment]
Honestly I'd say HV is a bit late still; I think that there is a great breakdown above of "what is the benefit". The always day is nice to have, but not really that important with the mentioned notes about solar. 

The mob balance is a bit trickier; Well before nano, we ignored monsters in and around our base (So, in another dimension as an analogue). All that you need to accomplish this is the F7 button and torches. We simply sealed every cave and lit the entire surface for over 200 blocks in every direction, in... Stone age? Maybe LV? And monsters *in the base* became a non-issue. It was still a concern doing magic progression, and mining, but those would still exist if your base was in a new dimension.

I feel that if someone wants to move/rebuild their base in HV, or EV, or IV, they can and will do so: Having a dimensional portal available earlier just opens the options and in no way stops someone from a rebuild later.

**Comment by Connor-Colenso** [comment]
@Dream-Master thoughts?

**Comment by Dream-Master** [comment]
i think HV is to early you just start to building a real base in the overworld. EV is better so you can start with your new ae system after visit the moon. There was a reason tier this dim so late so that we not have tons of abandoned bases because the users left.

**Comment by boubou19** [comment]
well from a server admin point of view, there is almost no diff between the amount of players who quit in HV and the players who quit in EV. Also, the mere existance of a dim takes 0.05 ms. So not a big issue. I don't really mind either way, as you cannot really redesign a new base fast without automating stuff with AE, which is EV.

**Comment by chochem** [comment]
hmm dream says 'HV is too early' but then he proposes the same thing as manii, putting it after the moon and with AE2. I guess just saying 'after T1 rocket/moon' is less ambiguous then trying to define where EV starts and HV ends :P.

I guess I'll make a PR based on that.
