### ISSUE TITLE
Fluid amounts for new endgame recipes

### ISSUE THREAD

**Issue by Florexiz** [GTNewHorizons/GT-New-Horizons-Modpack#10665]
### Your GTNH Discord Username

FalseColor#8524

### Your Pack Version

2.1.2.4-17-pre

### Your Proposal

With the new added recipes for endgame content (especially dtpf), we now have bunch of recipes that require random amount of fluids  for each of them (917? 7337?). This doesn't make these recipes more difficult or interesting, just increases frustration of creating universal systems for crafting and encourage spam of 1 machine - 1 recipe approach.
Almost all recipes in early and midgame have consistency in liquid quantity

### Your Goal

Rebalance recipes so they require adequate amount of fluids (multiplicity of 144/1000 at least)

### Your Vision

Make fluid crafting less of an annoyance while we still don't have bugless options for fluid ae

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Connor-Colenso** [comment]
In defence of the DTPF, the only thing to have non-ingot multiples is the fuels that are used in the recipes. This obviously cannot be a multiple of 144 because it is precisely calculated as to give a direct discount on regular EBF smelting depending on tier of fuel and coil of the DTPF. However this fuel is then shared across virtually every recipe so be consistent and use the same fuel tier and you will not have difficulty automating this as it can just be left in the hatch.

All metals/ingredients used in the other recipes are multiples of 144 for convenience sake, see https://docs.google.com/spreadsheets/d/1_n2HSFyzfNzkJHYBPFu3HTZvkh69GBi5LXw2c9FyG9o/edit#gid=0 for details on the maths behind the multi.

As for other things, usually it is an oversight but if you can name specific examples I'm all for fixing them because you are right taking 100L of iron instead of 144L in a recipe isn't difficult just frustrating.

**Comment by Runakai1** [comment]
Now with the introduction of AE2FC and the new assline working with fluid priority mode in fluid processing terminal, this issue is obsolete as fluid crafting makes it easy to craft with any amount of fluid.
