### ISSUE TITLE
Add an industrial infusion multiblock

### ISSUE THREAD

**Issue by realthecaffiend** [GTNewHorizons/GT-New-Horizons-Modpack#10723]
### Your GTNH Discord Username

thecaffiend#2253 

### Your Pack Version

2.1.2.3qf  (Some config changes, no recipe changes)

### Your Proposal

Add some sort of thaumic energistics-style infusion multiblock

Infusion looks super cool! The first dozen times you do it. However, when you want to industrialize it (See: Compressed solar, building BM altars, etc) it becomes a problem. I don't mind the automation so much, it's akin to asssline. The problem is that it just doesn't really scale well; 

The (awful, no good, very bad) speed can only be fixed with a lot of power from world accelerators (fine, ish)

The pedestals have some odd behaviours (A WR-CBE tile beside them will knock off the item roughly 40% of the time, for example)

There is too much FPS impact (Especially when WA'd)

Arguably most importantly, the fact that it isn't actually integrated into AE means that without some ugly hacks it cannot be entirely automated because you don't know if you have the essentia beforehand

### Your Goal

An infusion multi would allow for actual integration with the essentia system, encouraging more interesting automation as opposed to a field of items chucked into furnaces forever (Though I believe another project is underway to solve that, and I commend that). This should of course be post-infusion, you need to infuse up some things in order to make it; I could certainly see it being primordial pearl level, maybe ichorium. Since essentia input rate is a real consideration, some sort of multi-input or direct AE integration would presumably be best, as opposed to drawing through the air from the existing provider. 

### Your Vision

Infusion in thaumcraft is thematic, it's super cool visually, and it breaks down under "industrial" load. The stability thing is cool and neat visually, until you have essentially a multiblock the size of most megas just to deal with instability from automation and to make sure it works unattended. It just doesn't scale; A multi also would let you set the speed with hatches, fitting the rest of the pack, and could be limited in some way; You cannot infuse something costing more than your tier EU/t in total essentia in order to prevent people from using incredibly low power systems? (32768, LuV, then would just cover the last compressed solar, and I'd envision this around LuV tier) 

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by realthecaffiend** [comment]
Full disclosure; I certainly ~~stole~~ borrowed this idea from another pack that shall remain nameless

**Comment by King65868** [comment]
Heh, I’m sure you did

**Comment by Alastors** [comment]
I think instead of a multi we could possibly add in new tiers of infusion altars, and possibly new versions of the little pedestal things with better automation possibility.

The problem is how infusion pulls essentia

But if we could add a multi that would output to the pedestals automatically from hatches underneath it in the correct order instead and pull from the center instead, it would offer more QoL. and likewise additional tiering possibility to perhaps pull more than one type of essentia at a time, I'll come back and respond more on my idea for this after I finish my project due in 2 hours.

**Comment by realthecaffiend** [comment]
I don't really trust the pedestals and I'd prefer hatches but sure, that could also work, I think there are a lot of potential routes here to infusion 2: Electric infusaloo

**Comment by Alastors** [comment]
> I don't really trust the pedestals and I'd prefer hatches but sure, that could also work, I think there are a lot of potential routes here to infusion 2: Electric infusaloo

That's why I said we could probably make a new better version of the pedestals. You literally have no reason not to trust them anyway, they do what they are supposed to.

 I'm going to be real with you, I'm fully against replacing literally every unique magic multi with an ugly ass box with hatches. that's why I'm suggesting something in line with the current magic multis, (specifically the new LEG) in how they tend to shit on conventional multi structure concept.

A concept that utilizes the current structure for the infusion altar as part of the structure while using hatches to input the items to each pedestal could be great, we could even figure out a method for essentia input so that it doesn't use the infusion altar itself for pulling in the essentia to speed up that process. This is a much better concept than just "infusion 2: electric infusaloo"

Use a base structure for the multi that fits the design process behind the LEG and fits in with thaum, and then put an infusion altar or whatever on top of it and use it to do the infusion itself while dealing with it's essentia internally, the essentia is the current issue anyway.

And holy fuck, no I will smite you if it runs off electricity, we don't need more magic multis running off electricity, we have the opportunity to make something unique, magic running off electricity specifically is a spit in the face to the concept design of literally every magic mod in the pack. Sure you could make the argument about electromagic, but the lore behind the electric gear is that you are artificially recreating the magical effects with mechanical means as well as a few spells here and there.

No, this does not mean that "piss ugly infusion box fits in the lore" it literally is the exact opposite, dealing with the essentia pull in the base part itself fits within the lore while utilizing the infusion as part of the spell bit. Given that it's a multi, we could just have x hatches tied to x pedestals, and putting an item in the hatch makes it appear on the pedestal, unless it's been consumed by the infusion, then the hatch wouldn't replace the item until the next infusion round.

**Comment by Alastors** [comment]
I'm not saying the multi would use the infusion altar itself as per original infusion mechanics, I'm saying the infusion altar would be part of the multi, and it would use some of it's visual affects to achieve the same bs while it's done internally.

**Comment by Alastors** [comment]
> The pedestals have some odd behaviours (A WR-CBE tile beside them will knock off the item roughly 40% of the time, for example)

My dude, are you not stabilizing your infusion altar? the infusion claw adds 20 instability to infusions it starts, I've literally never had that happen to my stabilized infusions and I do that crap constantly. Use an abacus and find out.

**Comment by joshaup1999** [comment]
I also want to comment that i have 0 issues with items being knocked off, I WA both the claw and the altar. I've made 10 sextuples and have had 0 complications. Only thing that is really needed to make the altart quicker is change how fast it drawes the essentia in. Dont believe we really need a multi for it at all, let alone an electric version. Defeats the point of magic systems

**Comment by DianeXD** [comment]
GTNH has the most automation options, you can easily automate things like infusion. And thanks to ae2fc, you should now be able to make essentia gas on demand. More multi is not always better.

**Comment by LewisSaber** [comment]
> GTNH has the most automation options, you can easily automate things like infusion. And thanks to ae2fc, you should now be able to make essentia gas on demand. More multi is not always better.

you can make essentia together with recipe even without ae2fc

**Comment by KamenriderZO** [comment]
> GTNH has the most automation options, you can easily automate things like infusion. And thanks to ae2fc, you should now be able to make essentia gas on demand. More multi is not always better.

I would agree to add a machine to do this job not because of the automation, but the process cost too much time.
With a tiered machine may do large amount of infusion jobs quickly.
We don't care about how beautiful the process of infusion is.

**Comment by Alastors** [comment]
> GTNH has the most automation options, you can easily automate things like infusion. And thanks to ae2fc, you should now be able to make essentia gas on demand. More multi is not always better.

it is currently a god awful and hacky solution and shouldn't be considered

**Comment by Alastors** [comment]
> > GTNH has the most automation options, you can easily automate things like infusion. And thanks to ae2fc, you should now be able to make essentia gas on demand. More multi is not always better.
> 
> I would agree to add a machine to do this job not because of the automation, but the process cost too much time. With a tiered machine may do large amount of infusion jobs quickly. We don't care about how beautiful the process of infusion is.

First off, you could already make essentia on demand (don't call it a gas, it isn't a gas, it's canonically a fluid) using Thaumic AE, it directly allowed for this already

2nd off, screw that noise, we 100% care about how beautiful the process is, if it isn't at least partially doing the same fanfare of the original infusion altar, you won't ever see me support that bull. Given that I'm one of the only people who cares about making new magic multis and wants to code that shit in, that's a 0/10 review to me. 

You can talk about wanting a tiered machine all you like, but if you don't have a dev that gives a crap about making something, you aren't gonna get that thing, and quite frankly very few devs have an interest in it, most have things they actually wanna do. So take your "we don't care about how beautiful the process is" bs elsewhere.

I'm aware I'm not a dev, but you can count the current number of magic multis on one hand for a reason.

**Comment by Alastors** [comment]
Genuinely, what are you doing that you need an entire infusion multi? I genuinely can't think of many things besides the solar line, and the solar line is hardly a reason to add in a new ugly multi and screw any future potential for an actual nice looking multi for thaum that's consistent with what the current designs introduces in magic multis such as the LEG

**Comment by realthecaffiend** [comment]
Honestly, it is though. The current infusion altar was never meant for something ridiculous like the solar line. It's hella slow, the automation of it is basically all jank, and more and more people are doing solars. If I'm waiting for an EBF I can upvolt it or make more or move to a mega or a volcanus or whatever. For infusion, the option is: Wait longer to input the esssentia into your latest panel, or tickwarp it. That's it. 

Currently the status is "kind of working" and I'm uninterested tbh in arguments of what the future may, or may not hold, vs something that could be working now. I'd support something like the AIM from divine journey 2. I'd support some sort of direct connection to feed essentia faster. I'd support upgraded matrixes or pedestals. I'd support a boring grey placeholder box to be made fancy later if it solved the problems: Speed, triggering, and patterning essentia. 

The old cliché is: don't let perfect be the enemy of good. Right now, we have bad, Alastors seems to want perfect, but that doesn't mean it would be reasonable to shout down something good. 

Fact is, plenty of people *don't* care how beautiful it is. It's not BS. Some people do care, but I admit I'm supremely uninterested in someone trying to hold something back because it doesn't meet their form requirements when people are currently suffering with the function.

**Comment by realthecaffiend** [comment]
As for the comments about instability; It's not instability, we have almost 300 stability. Thaum pedestals have undocumented behaviour: This setup, with nothing around it, will kick the item off when there is a block update next to it, but will stay there until there is an update. You can add an item to a pedestal if the block above it is occupied, but it will eject it into the world if there is a block update next to it. I just re-read the entire thaumonomicon entry for infusion and this isn't mentioned. This, and the jank with triggering, and the lack of essentia recipe support, and the fact thaumcraft is ARR, is why I proposed a new multi as the least-bad solution to the many problems. I'd be entirely happy with a cube with input and output busses, because that is a large step up from the current status. I won't attempt to shout down other fancier looking solutions because while I may actually *prefer* a boring cube personally, I for one wouldn't want to let perfect be the enemy of good. 

![image](https://user-images.githubusercontent.com/8347355/179657280-e1aa420d-9b2e-4614-adca-658327c01e31.png)

**Comment by Alastors** [comment]
Do you want me to send you the code

**Comment by Alastors** [comment]
get out of here with your cube crap my dude, if it exists, it's going to look good

**Comment by Alastors** [comment]
like I know you aren't saying it shouldn't look good, but we shouldn't praise more crappy cube multis

**Comment by Alastors** [comment]
Like genuinely, the only solution we need is a essentia dealing with base, and then the solar recipe would literally be nothing, we don't need an entire tierable multi system for one recipe line.

**Comment by Alastors** [comment]
> The old cliché is: don't let perfect be the enemy of good. Right now, we have bad, Alastors seems to want perfect, but that doesn't mean it would be reasonable to shout down something good.


here's the problem my guy, if no devs are interested in it, then it literally doesn't mean anything, and you're hardly going to get someone to waste their time on a multi just for the solar panels.

**Comment by Alastors** [comment]
I suggested this to caffiened on discord but: I offered to make an essentia base, I'm sure it wouldn't be that hard to uptick and consume the essentia of an infusion altar, I could just grab the TE, make the base copy it's essentia requirements, and pull the essentia from an essentia provider and tick down the altar. Assuming it works like an essentia container anyway, which I'm extremely certain it does. 

He seemed open to this, I'm gonna start working on it tomorrow

**Comment by Alastors** [comment]
I've confirmed that it does, grabbing the AspectList is private, so that might be an issue, but the Vis Reader from automagy actually does this directly and show's how many aspects are left: (https://ftbwiki.org/Vis_Reader) so I'm going to decompile automagy and see how it does it. 

Yes, I'm aware I can't use automagy code since it's ARR, but I could likely recreate a similar function if it just directly grabs the aspects left, and if that works, I may be able to reverse the process and force it to do the opposite.

**Comment by Alastors** [comment]
Aight, I figured out how the vis reader did it. I didn't take a single line of code, but it was abusing a hole in the infusion altar's code that allowed it to read out the aspects. 

As such, I figured that I could just directly grab it as a worldObj, and all that, and force it's aspect list on a block with essentia pipe functionality, and then in turn increase the suction of that block based off it's new list, and then if the two lists weren't the same, it'd force the block's list onto the infusion altar.

That worked, I copied my code from my essentia bee system, so it currently only does the opposite and increases the essentia cost on the altar, but given that I have it doing this now, I just have to reverse the process and make the block have suction and it'll work exactly as you want for the solars. 

https://discord.com/channels/181078474394566657/603348502637969419/998844972373659689

**Comment by Alastors** [comment]
[thaumicinsurgence-1.7.10.jar.zip](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/9241204/thaumicinsurgence-1.7.10.jar.zip)
It's still a bit glitchy, but I've got it mostly working, if any one wants to test, I have a few more things I gotta tweak like it doesn't update the nbt data (which doesn't have an affect on anything that matters in the context of of how the TE functions, it still consumes the same amount of essentia and takes a pause for about 3 seconds every 3 aspects, but otherwise it works perfectly

**Comment by Dream-Master** [comment]
the source we need the source :)
