### ISSUE TITLE
Titanium Ore quadrupling not working with Titanium Comb

### ISSUE THREAD

**Issue by MrWye** [GTNewHorizons/GT-New-Horizons-Modpack#10769]
### Your GTNH Discord Username

MyWye

### Your Pack Version

2.1.1.0

### Your Server

Epsilon

### Your Expectation

Quadrupling titanium ore using titanium combs in chemical reactor

### The Reality

Recipe shows titanium ore quadrupling in chemical reactor with titanium combs, yet it does not work.
Instead it works with chrome combs for some reason and the chrome comb recipe with titanium ore is not in NEI.

### Your Proposal

Needs a fix

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by zacharyandrews** [comment]
this is caused by an issue that is already fix in the dev #9161
to sum up what happen is that the titanium combs you tried to use were another combs before the server upgraded to 2.1.1.0 when there was a shift in the id values due to a new comb being added though metadata on which recipe the combs were originally for still remains
