### ISSUE TITLE
Make XL turbines more sane in their turbine consumption 

### ISSUE THREAD

**Issue by alexandre-tardif** [GTNewHorizons/GT-New-Horizons-Modpack#10779]
### Your GTNH Discord Username

AlexandreTardif#5582

### Your Pack Version

2.1.2.4-14-pre

### Your Proposal

Currently XL turbines need 12 turbines and act as 16 normal multis but they chew through turbines much faster than they reasonably should. For example an XL will chew through 12 infinity turbines in 18.45 days while 16 plasma turbines with 16 infinity turbines would last 97.385 days. I think it should be somewhat adjusted to be more in line with the consumption rate of normal turbines

### Your Goal

Make it so someone with a single compact MK3 fusion doesn't need to replace 240 infinity turbines every 18.45 day. 

### Your Vision

As much as everyone think that compact are OP right now they kind of suck to maintain because of the turbine cost or having to spam 320 turbines 

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by xSkewer** [comment]
In addition, fast mode with its 12x damage multiplier on top of the increased damage from increased power gen makes it completely unviable.

Large infinity turbines in a plasma XL on fast mode get destroyed in less than 24h of run time. The type of plasma used has no impact on this.

**Comment by Steelux8** [comment]
I made the change that breaks turbines much faster, so I must ask: is the accelerated durability consumption really that aggressive? From my quick math, I understand that the XL turbine in fast mode, which uses 12 turbines inside, runs at the speed of 48 turbines, while consuming them 12x faster. Since they run 4x faster and run out 12x faster, it's only 3x less EU generated per turbine, but at a much faster speed.

If the turbines are going out faster than that, it's probably because the durability consumption scales with the speed on top of the multiplier. I'll have to look at that, if infinity turbines last 97 days in regular plasma turbines, 18 days in normal mode XLs and less than 1 day in fast mode XLs.

**Comment by Pxx500** [comment]
So technically this MB wastes 2/3 of turbines durability in the fast mode. I think it's a little bit too much bow about x8 durability loss multiplier instead of x12?

**Comment by Pnc6lx** [comment]
durability loss in turbine is (EU/T)^0.6, 48X means 48^0.6 = 10.2X durability loss for every turbine. that is why they cost so much

**Comment by Steelux8** [comment]
https://github.com/GTNewHorizons/GTplusplus/pull/250
