### ISSUE TITLE
Change the Storage Monitor to no longer use channels

### ISSUE THREAD

**Issue by joshaup1999** [GTNewHorizons/GT-New-Horizons-Modpack#10771]
### Your GTNH Discord Username

Lord Peverell#3125

### Your Pack Version

2.1.2.1

### Your Proposal

Have the storage monitor not use up channels

### Your Goal

Make storage monitors no longer need channels

### Your Vision

Adds a stylish way to display stock levels in ae without needing to use channels. Storage monitor is just a visual display unlike its upgraded varient that interacts with the storage network (ME Conversion Monitor)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by leagris** [comment]
I am concerned about the potential TPS lag caused by overuse of the storage monitor if it has no channel cost.
Since it looks elegant, it would be tempting to make walls out of it to display AE storage to the world if it doesn't cost a channel to run.

Technically, a storage monitor refresh must query the state of the entire AE storage network, and communicate the updated amount via network messages to connected clients.

While from a single player perspective, one takes responsibility for the sources of lag, this has the potential to cause significant lag for a server.

At the very least, using a channel gives players a proportional sense of scaling cost and incentive to think twice before deploying a wall of storage monitors.

**Comment by Anarack** [comment]
Are they a tp issue though? iirr they are kind of slow to update the displayed number and if polling the network constantly is a issue wouldn't level emiters/crafting cards have the same issue and are much more heavily used and for crafting cards a much larger tps impact.

**Comment by vlaetansky** [comment]
https://github.com/vlaetansky/Applied-Energistics-2-Unofficial/commit/55d03449b52edc4873bb1211e28ee829a3652dcd
