### ISSUE TITLE
Personalized Dimension Portal doesn't get regenerated if you enter the dimension and the target portal is missing

### ISSUE THREAD

**Issue by Learwin** [GTNewHorizons/GT-New-Horizons-Modpack#10855]
### Your Pack Version

2.1.2.4-14-pre

### Your Server

Private Server

### Your Expectation

A bed blew up the portal block back to the overworld in my personalized dimension. My friend on the server tried to regenerate the portal back to the overworld by clicking on the portal block, like a nether portal would do. This was in hopes to get me unstuck in the dimension. We tried placing down a cheated in Personal Portal in hopes of it simply linking back to the overworld.

### The Reality

He clicked the portal and entered the personalized dimension but a new portal back wasn't generated. So we had to load a backup cause we both now where stuck in our personalized dimension. The placed down portal only presented us with "Personal dimensions can only be created from the overworld" and did not link back to the overworld as we would have hoped it would.

### Your Proposal

I see two options to fixing this:
1: Regenerate the portal in the Personalized Dimension when it's no longer placed down
2: Make Personalized Portals that are placed in a Personalized Dimension automatically link back to the overworld.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by eigenraven** [comment]
After discord discussions, we decided not to regenerate portals automatically, there's an op command if one gets lost. The reason is that it's too easy to dupe portals on multiplayer, and that gives a very OP way of interdimensional transport. Making newer portals obsolete/destroy old portals feels like an odd design choice to me, and also would be a somewhat more complex implementation - losing portals should happen very rarely in practice.

The portal blocks are immune to explosions already, I'll make the items more resilient too to make them less likely to be destroyed. Worst case, a new portal can be added in with a command, this was already the case with utilityworlds and according to officals' mods people didn't lose them frequently.
