### ISSUE TITLE
Thunder in personal dimension cannot be skipped

### ISSUE THREAD

**Issue by arbitrarystar** [GTNewHorizons/GT-New-Horizons-Modpack#10902]
### Your GTNH Discord Username

dxzfvzs#1259

### Your Pack Version

2.1.2.4-14-pre

### Your Proposal

![image](https://user-images.githubusercontent.com/56274079/182387087-b6d75e31-79f1-4550-a673-29925a2fa029.png)

New personal dimensiones allow weather: but since there is always day in them, the thunder weather does not trigger night, therefore the thunder cannot be skipped. I would suggest adding a way to skip thunder or maybe even rain. Rain would make sense to be skippable at least in the time during overworld's night.

### Your Goal

Thunder might be beatiful, but it is what is it.

### Your Vision

It would lessen the difference between weather in overworld and weather in personal dims.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by eigenraven** [comment]
Due to the way forge handles weather in non-ow dimensions, the weather is either off or a copy of the overworld weather so you can skip it by sleeping in the ow, e.g. put a bed next to your portal on the other side. Allowing sleeping in personal dimensions can cause crashes unless the dimension is perma-chunkloaded due to minecraft's broken respawn code, so I can't turn that on sadly.
