### ISSUE TITLE
Infinite crash loop (presumably bettercrashes)

### ISSUE THREAD

**Issue by ZaykieT** [GTNewHorizons/GT-New-Horizons-Modpack#10964]
### Your GTNH Discord Username

Terra#5770

### Your Pack Version

2.1.2.4-25-pre

### Your Server

SP

### Type of Server

Single Player

### Your Actions

on world creation on the version mentioned above using optine the game froze wich isnt suprising considering optifine.
unexpectedly the crash log had a size of 1.5Gb's due to the creation of a crash loop
![grafik](https://user-images.githubusercontent.com/108432213/183312243-aca987eb-07e1-4686-b9d4-76393a6d8637.png)
and ~1400 crash reports.
![grafik](https://user-images.githubusercontent.com/108432213/183312351-981acca7-b5bb-4cdf-9578-be77a660cb98.png)
i talked to a dev. on the discord about it and we came to the conclusion its most likely a loop created by the new bettercrashes mod

### Crash Report

the crash report only features one of the 1400+ crash reports created by the loop and its not really what this report is about because im already aware of crash reason.
[crash-2022-08-07_22.49.23-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/9277647/crash-2022-08-07_22.49.23-client.txt)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by chochem** [comment]
just to add since I was the person you talked to: 
- removing optifine solved the problem (its is sadly in by default in dev25mmc) however the worse part is the crashloop.
- The crash loop being related to BetterCrashes is pure speculation, but specifically the idea was that optifine might cause a crash trying to render the BetterCrashes crash screen, thus causing a loop. I dont know if thats true though, but if it is then BetterCrashes should get a counter of sorts and let the game crash properly after the 10th time. :P

**Comment by ZaykieT** [comment]
the game actually doesnt even give up, i had to force close it via task manager because it started eating to much
