### ISSUE TITLE
Ore based bee combs now with fluid chemical process much less usefull

### ISSUE THREAD

**Issue by Ngar1** [GTNewHorizons/GT-New-Horizons-Modpack#11147]
### Your GTNH Discord Username

Ngar

### Your Pack Version

2.1.2.4.-29

### Your Proposal

With the multiblock miners, ores are no scarce goods, relevant is a effective process.

With the change of function of Combs from a multipier to a production of pure crashed ores by means of hydrocloride, among other things, the use of Combs makes no sense. Especially because chloride is in short supply and is consumed (voided) in many processes.
 

### Your Goal

make combs/bees a benefit again

### Your Vision

Ideas: 
- General: less processes, were chloride will be fully "voided"
- Old centrifuge receipts, with lower yield, but dusts (not small/tiny)
- **Usage of combs for enforcing the yield of secondary/tertiary Output** (-> my favourite)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Dream-Master** [comment]
maybe we can make it recycle able like we did for the new silicon line use chlorine but get salt back

**Comment by Runakai1** [comment]
I disagree. 
You're what, UHV? Chlorine shouldn't be a problem for you at all. Additionally, the salt bee got a massive buff to compensate the consumption of HCL. 

Centrifuge recipes will be buffed by a lot in the next version, that's already done by me. 

Saying combs have no benefit anymore is an exaggeration. You can get ores directly out of them instead of quadrupling ore which no one, or at least very very few people used. 

Also since I wasn't able to test every comb and how that affects the gameplay, I may be in favour of reducing the consumption of acids in comb processing, but I don't thing HCL is a problem especially due to the reasons I provided.

**Comment by chochem** [comment]
hmm I think there are some interesting thoughts here, But chlorine really isnt a problem once you have multiblock fluid drill or salty root (or salt bee).

**Comment by Runakai1** [comment]
> hmm I think there are some interesting thoughts here, But chlorine really isnt a problem once you have multiblock fluid drill on a planet or have salty root (or salt bee).

The only useful thing that I'm already working on is the secondary and tertiary outcome for combs.

**Comment by Ngar1** [comment]
Independent of additional salt sources: 
Combs just to generate crushed ores makes no real advantage (only in special cases) over the massive output of the miners/voidminers. The new ore processes are complex and yielding enought, that combs now (mostely) useless. 
The confluence of combs and ores ensures these do not produce out of thin air.

@Runakai1: yes, I am UHV and my chloride production works continously but used for more important receipts. 
@chochem: this means: produce ores from base products of salt bees and ore bees? I prefere a dependence to real ores.

Again, a use of combs to force secondary products would be much more valuable.

**Comment by Runakai1** [comment]
> Independent of additional salt sources: Combs just to generate crushed ores makes no real advantage (only in special cases) over the massive output of the miners/voidminers. The new ore processes are complex and yielding enought, that combs now (mostely) useless. The confluence of combs and ores ensures these do not produce out of thin air.
> 
> @Runakai1: yes, I am UHV and my chloride production works continously but used for more important receipts. @chochem: this means: produce ores from base products of salt bees and ore bees? I prefere a dependence to real ores.
> 
> Again, a use of combs to force secondary products would be much more valuable.

Combs produce purified versions. Certain bees even produce liquid outcome. 
The new processing used 4 combs instead of 9 and additional acid. Why is that complex and thus useless?

What secondary output do you need?

**Comment by Runakai1** [comment]
This ticket was opened due to concerns about bees not being integrated in the ore processing anymore and thus the disliking of bees being able to produce resources directly. 
This feature will not be overhauled as the majority of people are in favour of that mechanic over the old one.

For further suggestions please use https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/10230

**Comment by Runakai1** [comment]
This ticket was opened due to concerns about bees not being integrated in the ore processing anymore and thus the disliking of bees being able to produce resources directly. 
This feature will not be overhauled as the majority of people are in favour of that mechanic over the old one.

For further suggestions please use https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/10230
