### ISSUE TITLE
NEI crush

### ISSUE THREAD

**Issue by LewisSaber** [GTNewHorizons/GT-New-Horizons-Modpack#11199]
### Your GTNH Discord Username

Lewissaber#7231

### Your Pack Version

2.1.2.4-29-pre

### Your Server

SP

### Your Actions

![image](https://user-images.githubusercontent.com/39595617/188241650-c2531524-fdb2-44a4-b642-852993760bb2.png)
idk how this button is name, but clicking on it crushes me
i have 29-pre + Galaxy Space updated

### Crash Report

https://paste.ubuntu.com/p/XYkwNz2swc/

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [x] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by chochem** [comment]
[crash-2022-09-02_23.39.55-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/9481360/crash-2022-09-02_23.39.55-client.txt)

easy enough to reproduce

**Comment by chochem** [comment]
Fixed for me by updating NEI to latest (NotEnoughItems-1.7.10-2.2.334-GTNH). Can you confirm that?

Possibly fixed by this https://github.com/GTNewHorizons/NotEnoughItems/pull/276. But that PR is very cryptic, might just be an accidental fix.

I still have no idea what that function is the supposed to do. The whitelist/blacklist have zero effect.

**Comment by LewisSaber** [comment]
Fixed For me with latest NEI too

**Comment by slprime** [comment]
Yes, PR https://github.com/GTNewHorizons/NotEnoughItems/pull/276 fix this crash
