### ISSUE TITLE
Slime backpack makes player run extremely fast and may cause game not responding

### ISSUE THREAD

**Issue by ChromicRedBrick** [GTNewHorizons/GT-New-Horizons-Modpack#11245]
### Your GTNH Discord Username

ChromicRedBrick#6260

### Your Pack Version

2.1.2.4-29-pre

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

Players should not run so fast.

### The Reality

When equipped with an adventure backpack (slime), walk on blocks having speed boost effects and then release walk button, player's speed can get extremely fast, and can even move millions of blocks in a few ticks on blocks like ice, causing game not responding.

Moreover, running on these blocks does not give player extreme speed bonus, but can make hunger value drop many times faster.

Video: https://youtu.be/7q-6M1k7qss

### Your Proposal

Fix it.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by MirceaZisu** [comment]
This bug is also present in 2.1.2.3qf. My Discord username is Tree#0707. I saw it most often when using it in water:
Step 1, get in water, on a portion with the same y level
Step 2, tap any directional key slightly, but don't hold it
Step 3, enjoy getting launched in that direction.

I think this could be used to travel thousands of blocks or even crash servers. Haven't tried to do either yet.
