### ISSUE TITLE
Infinity booster card (WCT) and view cells (AE2) slip out when hotkeying

### ISSUE THREAD

**Issue by Alexdoru** [GTNewHorizons/GT-New-Horizons-Modpack#11274]
### Your GTNH Discord Username

Alexdoru#9395

### Your Pack Version

GTNH 2.2.0.0 RC1

### Your Server

solo

### Your Expectation

opened the wireless terminal, placed my mouse hover blocks in my terminal and pressed the key "4" on my keyboard.
Expected the blocks to end up in the 4th slot of my hotbar

### The Reality

the infinity booster card ended up in the hotbar instead

### Your Proposal

fix

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by eigenraven** [comment]
I've looked into this and it's an issue with base ae2. The clientside gui adds `SlotME` instances dynamically for each visible AE slot in the gui, the problem is their `slotNumber` is never set so defaults to 0 - meaning that any code that relies on this number (hotkey swap, mouse scroll moving, previously dragging with mousetweaks, etc.) thinks you're actually hovering over the first slot instead of the ME slot. You can reproduce this in base ae2 by putting a view cell in the first view cell slot of a terminal, emptying your hotbar and pressing `1` while hovering an item in the ME grid - it swaps the viewcell with the first hotbar slot.

The issue is how to fix this: giving the slots proper slot numbers crashes the game because the slots exist only clientside, and when the slot count between the server and client doesn't match the vanilla packet handling code crashes. Adding a dummy null slot to every container at index 0 seems like a workable solution, but it just makes these hotkeys not work instead of fixing the problem. Adding ME slots to the server would be ok, but because it's a dynamic number dictated by the client side there's timing problems of packets that would create/destroy them, which could cause random crashes when the slot counts don't match between sides.

@repo-alt any thoughts?
