### ISSUE TITLE
Monthly Report for quests that need to be edited

### ISSUE THREAD

**Issue by Alastors** [GTNewHorizons/GT-New-Horizons-Modpack#11385]
### Your GTNH Discord Username

Alastor's Game

### Your Pack Version

RC3

### Your Proposal

If you have a quest that needs to be changed, please post it in a comment here

### Your Goal

To make a cohesive list of quests that need to be changed by the devs.

### Final Checklist

- [x] All of the quests in this ticket are fixed, and/or it is a new month, in which the unfinished quests will move to the next ticket.

**Comment by hallucinogender** [comment]
Wooden crossbow bolt quest. Details here: #11301

**Comment by ChromicRedBrick** [comment]
### Quest Changes
- [ ] **Quest.45 Multiblock Tanks... Railcraft Tanks**
  > Use only Buckets to move fluids because cells get destroyed.

  This is fixed in https://github.com/GTNewHorizons/Railcraft/pull/28.

  And https://github.com/GTNewHorizons/Railcraft/pull/26 fixed external drain of RC tanks, so it's better to mention that you can use pumps to increase output rate.

- [ ] **Quest.1520 Large Aluminium Fluid Cells**
  > If you're trying to get water, unfortunately the larger cells don't really work well with the RC Water Tanks, try moving the water to one of the GregTech or GT++ tanks such as the ultra low voltage fluid tank or super tank first.

  Also fixed in https://github.com/GTNewHorizons/Railcraft/pull/28.

- [ ] **Quest.1898 MV Advanced Steam Boiler**
  > Aside from producing one MV amp of Steam, it regulates its fuel more efficiently if it ends up being full.

  MV advanced steam boiler can only produce 1500L/s (=75L/t) steam, far from 1A MV.

- [ ] **Quest.1901 HV Advanced Steam Boiler**
  > Aside from producing one HV amp of Steam, it regulates its fuel more efficiently if it ends up being full.

  HV advanced steam boiler can only produce 2250L/s (=112.5L/t) steam, far from 1A HV.

- [ ] **Quest.1391 Wand Focus Experience Drain**
  > This focus can be upgraded at the Focal Manipulator.

  It can't be upgraded.

- [ ] **Quest.1397 Wand Focus Time**
  > This focus can be upgraded at the Focal Manipulator.

  It can't be upgraded.

- [ ] **Quest.1398 Wand Focus Meteorology**
  > This focus can be upgraded at the Focal Manipulator.

   It can't be upgraded.

- [ ] **Quest.2856 Advanced MB Construction**
  > not everything can be rotated. Exceptions include: ... the MVF can, but the MBF and MDT cannot.

  It sounds weird, but literally MDT can be rotated.

- [ ] **Quest.1419 Who Cares About a Little Cancer...**
  > It will charge armor and tools at the tier and below.

  I don't know if it is a bug or intented, GT++ Wireless Charger actually can charge armor and tools (and batteries) at tier higher than the charger. (If it is not intended, just fix it.)

- [ ] **Quest.1305 For Fluid Recipes**

  It's better to mention that "AE2FC do fluid recipes better" or something in this quest, imo. EC2 is slow and buggy.

- [ ] **Quest.2824 Absorbing Magic Energy to Produce EU LV**
  > These produce power by absorbing magic energy from nodes, dragon eggs, etc.

  Creeper Egg can produce power too, this is not mentioned in either quest or tooltip.

- [ ] **Quest.1481 What Was That? I Can't Hear You Over the Engine!**
  > It needs 80 L/s, so you will need more than one Vacuum Freezer to supply it continuously: for an ECE that is always running, you will need a quad Vacuum Freezer, 1 EV and 3 HV.

  https://github.com/GTNewHorizons/GT5-Unofficial/pull/1385 reduced the LOX amount to boost the ECE from 80 L/s to 40 L/s.
  
  - In addition, **Quest.3022 Extreme Combustion Engine** is also a quest for ECE, they ask for the same stuff. Make them one single quest might be better.

- [ ] **Quest.2708 Pluto Dungeon**

  Add "you can also find draconic core schematic in Pluto dungeon" or something would be good.

- [ ] **Quest.85 - Smelt All the Things Stack-Wise...**
  > ...with this great invention! Uses power to smelt up to 2 stacks of items at once! Can't go any faster! Unless you use better coils, of course.

  https://github.com/GTNewHorizons/GT5-Unofficial/pull/1310 make multi smelter able to do 8192 parrallels max, and https://github.com/GTNewHorizons/GT5-Unofficial/pull/1108 allow it to parallel different items. Quest should be updated due to the changes.

- [ ] **Quest.1894 - Gas Turbine**

  Since LGT will be capped to 8192 EU/t in the future, it's better to mention Large Adv Gas Turbine in the quest. (Or add a quest for that multi) (And solid-oxide fuel cell can also be listed as an alternative)

- [ ] **Quest.62 The Power of the Sun** and **Quest.2389 HP Solar Boilers**

  https://github.com/GTNewHorizons/GT5-Unofficial/pull/1290 disabled calcification when using distilled water. It is unable to make distilled water in steam age, but adding that "you can use distilled water to avoid calcification when you get to LV" or something would be helpful for later game.

- [ ] https://github.com/GTNewHorizons/GT5-Unofficial/pull/1146 reworked turbine materials, so quests related to turbine materials need to be checked to confirm if any changes are needed.

### New Quests

- [ ] Add quests for AE2FC fluid cells in AE tab. They are good alternatives to EC2 ones.

- [ ] Add a quest for Quadruple Input Hatch, or mention it in some multiblock quests (for example, EBF).

- [ ] Add a quest in Multblock Goals tab listing what GT tools can do with multiblock controllers. (Or add them to each multi's tooltip or quest) Examples are as follows:
  - Screwdriver: (Right Click) Toggle mode for some multis, lock recipe for LCR, set prioritise circuit for MEBF, toggle input bus seperation for PA, EBF, etc. (Shift Right Click) Lock recipe for PA
  - Soldering Iron: (Right Click) Toggle void excess for GT++ multis
  - Wire Cutter: (Right Click) Toggle UEV+ treated as UHV for PA, toggle input bus seperation for AdvEBF, MEBF, Industrial Wiremill, ABS, etc.
  - Plunger: (Right Click) Clear output hatch for GT++ multis

- [ ] Add a quest for Integrated Ore Factory in Multiblock Goals tab (maybe add a link in UHV tab as well). It is the ultimate solution for ore processing in late game.

- [ ] Add a quest for tesla tower in Multiblock Goals tab. It is a powerful power transmission option in HV~ZPM that should be mentioned in questbook.

- [ ] Add a quest/quests for YOT in Multiblock Goals tab. It is the ultimate fluid storage solution in middle & late game.

- [ ] Add a quest for infinite oil/gas/fluid drilling rig. There is already a quest for Void Miner, so add one for infinite rig is reasonable.

- [ ] Add a quest for GT++ solar tower in How to Generate Power tab, it is now a power generation option in IV, since https://github.com/GTNewHorizons/GTplusplus/pull/290 fix it.

- [ ] Add XL gas turbine and XL plasma turbine in How to Generate Power tab, they are good upgrade for the large ones. XL steam/HP steam turbine have a quest in Working with Oil tab already, might need a link in How to Generate Power tab too?

- [ ] Add a quest for turbine housing in How to Generate Power tab, it makes automating large turbine possible.

- [ ] Add a quest for industrial forgehammer in GT++ tab.

- [ ] Add a quest for boldarnator (industrial rock breaker) in GT++ tab.

- [ ] Add a quest for algea farm in GT++ tab (I'm not sure whether this multi actually needs a quest).

- [ ] Add a quest for indium bee in Bee Breeding tab. https://github.com/GTNewHorizons/GT5-Unofficial/pull/1282 added this bee. It is useful for obtaining indium. In addtion, a quest listing all indium obtaining methods would be good.

**Comment by danbka33** [comment]
I would add to the quest where fluorine is required that it can be obtained in sufficient quantities from Cryolite

**Comment by LooseEthics** [comment]
Running 2.1.2.3, so this might already be outdated, but Advanced Heat Exchanger quest wants Component Heat Exchangers in the first step, even though AHE recipe uses the basic ones.

**Comment by chochem** [comment]
yea thats outdated

**Comment by bjin2000** [comment]
Can anyone help me to add the below features to the quest book? I'm not a native English speaker.
Add some new features of Nature's Compass to the question book
- [ ] Quest.1510 Biomes Everywhere, But Not the One You Want?
1. search bar
    a. search base on the name shown on the "sort by" button(case insensitive), ex. bamboo forest(when Sort By: Name)
    b. search with key, ex1. name: bamboo forest ex2: climate: warm ex3: bh: -1.8 ex4: tag: forest
        all available keys: name(a lot), climate(hellish, hot, warm, normal, cold, icy), baseheight | bh(float, can be negative),
        heightvariation | hv(float), rainfall | rain(float), temperature | temp(float), humidity(damp, normal, arid),
        tags | tag(a lot, ex. forest)
    c. combine search, ex. climate: warm, humidity: damp
2. after the biome search is done, the gui will only show the available biome in 10k if the select biome is not found,
    shift + right click to clear all set
3. change search range in config(be careful, a very large sample number will freeze the game)
4. change hud position in config, TOPLEFT, TOPRIGHT, BOTTOMLEFT, BOTTOMRIGHT

https://user-images.githubusercontent.com/48137054/192126361-87f9c40e-b653-4cfc-89d7-65d20fc6a79b.mp4

**Comment by ChromicRedBrick** [comment]
- [ ] **Quest.1225 Mainframes, Your First IV Circuit**

This quest asks for 16 annealed copper wires, but to craft a mainframe in HV(using SMD or non-SMD capacitor) needs 24.
![quest](https://user-images.githubusercontent.com/85604068/192271866-48d58a0b-e06b-4cc5-b066-fa4015d22ea8.png)
![recipe](https://user-images.githubusercontent.com/85604068/192272318-817e3b27-e6a8-4e84-8e73-82ab3f1f6c91.png)

**Comment by Dream-Master** [comment]
> * [ ]  **Quest.1225 Mainframes, Your First IV Circuit**
> 
> This quest asks for 16 annealed copper wires, but to craft a mainframe in HV(using SMD or non-SMD capacitor) needs 24. ![quest](https://user-images.githubusercontent.com/85604068/192271866-48d58a0b-e06b-4cc5-b066-fa4015d22ea8.png) ![recipe](https://user-images.githubusercontent.com/85604068/192272318-817e3b27-e6a8-4e84-8e73-82ab3f1f6c91.png)

yes this is a bug indeed. Maybe two recipe for one item. Maybe we can add it 16 Annealead and 24 copper wire or so

**Comment by TwoTailedFox** [comment]
"BEGONE, LAG! Also, Bats"

Quest needs to be updated as Hydrogen Cyanide has a recipe, and possibly to change "Complain to Alk" to "Raise a ticket on the GitHub".

Also, the Pest Killer item itself in GT++ should have its tooltip changed from "Be weary of your neighbours" to "Be wary of your neighbours".

**Comment by TwoTailedFox** [comment]
"Enhanced Farm Logic"

The optional task with the 2 x Electronic Circuit should instead call for 2 x circuitBasic as per the Carpenter recipe.

**Comment by TwoTailedFox** [comment]
"Refined Farm Logic"

The optional task with the 2 x Good Electronic Circuit should instead call for 2 x circuitGood as per the Carpenter recipe.

**Comment by TwoTailedFox** [comment]
"Intricate Farm Logic"

Since the Intricate Circuit Board is HV, one of the quest reward choices should be changed from 2 x Good Integrated Circuit (MV) to 2 x Processor Assembly (HV).

**Comment by chochem** [comment]
> * [ ]  **Quest.1225 Mainframes, Your First IV Circuit**
> 
> 
> This quest asks for 16 annealed copper wires, but to craft a mainframe in HV(using SMD or non-SMD capacitor) needs 24. 

some recipes need 16, some 24. so asking for 16 is correct.

**Comment by ChromicRedBrick** [comment]
> > * [ ]   **Quest.1225 Mainframes, Your First IV Circuit**
> > 
> > This quest asks for 16 annealed copper wires, but to craft a mainframe in HV(using SMD or non-SMD capacitor) needs 24.
> 
> some recipes need 16, some 24. so asking for 16 is correct.

But for now only advanced-SMD recipes need 16, which is undoable in HV.

**Comment by chochem** [comment]
ah, thats the point

**Comment by ChromicRedBrick** [comment]
- [ ] **Quest.2564 Making the Vat More Efficient!**
The first line of the third paragraph is white.  Hard to see clearly.
![vat](https://user-images.githubusercontent.com/85604068/193442338-dd3b4b05-5aa5-4cd8-8b2c-e249bd8fe3ba.png)

**Comment by Connor-Colenso** [comment]
"A lead about lead that leads to lead" should be changed to take lead ingots, not lead dust. Since you get galena and lead ore from the prior vein it wants you to mine and you may process either into lead. I processed galena and therefore the quest would not complete.

**Comment by glowredman** [comment]
- [ ] This quest should be adjusted because as of https://github.com/GTNewHorizons/NewHorizonsCoreMod/pull/313 the "Custom 1-5" aspects are no longer dummy aspects.
![grafik](https://user-images.githubusercontent.com/35727266/193647117-ca360023-e93b-4692-9895-70652e2d2a01.png)

**Comment by chochem** [comment]
> * [ ]  This quest should be adjusted because as of [Improve legacy GT++ Thaumcraft aspects NewHorizonsCoreMod#313](https://github.com/GTNewHorizons/NewHorizonsCoreMod/pull/313) the "Custom 1-5" aspects are no longer dummy aspects. (There may be other quests mentioning the Custom aspects, I only noticed this because Alucard Shadows posted this on Discord.)
>       ![grafik](https://user-images.githubusercontent.com/35727266/193647117-ca360023-e93b-4692-9895-70652e2d2a01.png)

adjusted in what way is the question. Do you know what one can scan for them? and in what order?

**Comment by glowredman** [comment]
I don't know if they can be obtained via scanning, they can be obtained by combination:
- Cognito + Ordo -> Aequalitas
- Cognito + Vitium -> Vesania
- Vacous + Motus -> Primordium
- Lux + Primordium -> Astrum
- Humanus + Iter -> Gloria

Speaking of aspects - I'm not sure if the Avaritia aspect (Terminus) is in that list either, the combination for that one is Lucrum + Alienis.

**Comment by SPMoo66** [comment]
The requirements for the Palladium questline in IV are wrong.

- [ ] Quest 2309 - Another Acid to Worry About!

-Sodium Hydroxide Dust should be changed from 4 to 12 in step 1
-Sodium Sulfate Dust should probably be changed from 2 to 14 in step 3

- [ ] Quest 2878 - Palladium

-Reprecipitated Palladium Dust should be changed from 2 to 4 in step 1
-Water Cell should be removed from step 2 and Ammonia should be increased from 2 to 4

It might also be nice to see the tiny piles of dust in Quest 2310 - Palladium changed to full piles if someone uses the circuit 9 recipe.

The IV Platinum line seems to have changed too.
Quest 2304 - Platinum Group Processing - All the Other Metals and Quest 2305 - First Separation - Rhodium have wrong amounts for Potassium Disulfate cells. 2322 - Fluid From Sulfur Gas seems to have the wrong amount of Molten Potassium cells. I'm not sure if anything else further in that line are wrong since I haven't gotten any further to test.

**Comment by chochem** [comment]
> You can get Terminus from crystal matrix ingots iirc

that is in the list, yea.

**Comment by SPMoo66** [comment]
- [ ] Quest 3125 - Skipped into Ammonia

The quest text currently mentions Nitrogen and Oxygen in the second sentence when it should be Nitrogen and Hydrogen.

**Comment by NotAPenguin0** [comment]
SMD inductors now have a recipe, so they should probably be mentioned in the relevant quest. I'll update this comment when I find them in-game later.

**Comment by Glease** [comment]
- [ ] Quest 829 (oxygen compressor), 820 (launch pad) and 821 (fuel loader) should all be mandatory prereq for 1433. You cannot survive without completing oxygen compressor quest, and you cannot take off at all without launch pad and fuel loader.

**Comment by NotAPenguin0** [comment]
- [ ] Quest 77 (EBF-Time)

Mention somewhere that the RC crowbar should not be used to craft the maintenance hatch as it won't work when not at full durability, and is fully consumed. The EBF is the first time you need to craft a maintenance hatch, so it should go here.

**Comment by Skid-Inc** [comment]
As per this old but still open issue: https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/9858

- [ ] Quest 887 (A Wizard's Staff Has a Knob on the End): Has incorrect task materials (takes Lich Bones and Energetic Screws to craft, not Hydra Blood and Titanium Screws).
- [ ] Quest 1191 (Magic "Staffter"): Has incorrect task materials (takes Lich Bones and Energetic Screws to craft, not Hydra Blood and Titanium Screws).
- [ ] Quest 878 (Magic Staff Core): Due to the above, I would also suggest the requirement for this quest be changed from 263 (A Silverwood Wand at Last), to 266 (More Energetic Screws), as the sub-quests need neither Fiery Blood nor Virant Alloy Screws.

**Comment by McFrugal** [comment]
This isn't about the questbook exactly, but the other types of issues don't seem to include text edits like this.
Some Thaumonomicon entries for blood magic contradict eachother.  The Rune of the Orb entry says that 4% of the Weak Orb is 100 LP, which would mean that the Weak Orb has 2500 max LP.  The entry for the Apprentice Orb says it has 5 times the capacity resulting in 25000 LP, but that's 10 times 2500.  So what's the capacity of a Weak Orb?  The entry for the Weak Orb doesn't state how much LP it contains.

**Comment by minecraft7771** [comment]
- [ ] Quest 2712 (Xenoxene Xenoxenis). The chance of getting the Xenoxene culture is 7.5% not 4%. In coremod it is added without stating any chance and the default chance of the called constructor will set it to 7.5%.

**Comment by wlhlm** [comment]
Quest 40 (You Shall Proceed) does not detect used/damaged Wooden Form.

![Screenshot 2022-10-19 224024](https://user-images.githubusercontent.com/1928113/196799583-b00c1776-2c50-4181-9085-9833b084148f.png)

**Comment by SPMoo66** [comment]
Corrections for the Polybenzimidazole questline in IV, changes italicized

- [ ] Quest 1703 (Potassium Nitrade) <- _Quest title and quest description are misspelled as "Nitrade", correct to "Nitrate"_
Change to _2 Potassium Dust_ + _2 Nitric Acid Cell_ = _10 Potassium Nitrate Dust_

- [ ] Quest 1704 (Chromium Trioxide)
Change to _2 Chrome Dust_ + _6 Oxygen Cell_ = _8 Chromium Dioxide Dust_ and _8 Chromium Trioxide Dust_

- [ ] Quest 1702 (Potassium Dichromate)
Change to _10 Potassium Nitrate Dust_ + _8 Chromium Trioxide Dust_ = _11 Potassium Dichromate Dust_

- [ ] Quest 1700 (Phtalic Acid)
Change to 18 1,2-Dimethybenzen Cell + 2 Potassium Dichromate Dust + _108 Oxygen Cell_ = 18 Phthalic Acid Cell

- [ ] Quest 1691 (Polybenzimidazole)
Change to _72 Chlorine Cell_ + _36 Benzene Cell_ = _36 Chlorobenzene Cell_

- [ ] Quest 1692 (Nitration Mixture)
Change to _36 Sulfuric Acid Cell_ + _36 Nitric Acid Cell_ = _72 Nitration Mixture Cell_

- [ ] Quest 1693 (2-Nitrochlorobenzene)
Change to _72 Nitration Mixture Cell_ + _36 Chlorobenzene Cell_ = _36 2-NitroChlorobenzene Cell_

- [ ] Quest 1694 (3,3 Dichlorobenzidine)
Change to _36 2-Nitrochlorobenzene Cell_ + 2 Copper Dust = 18 3,3-Dichlorobenzidine Cell

**Comment by McFrugal** [comment]
- [ ] Quest 761 (Powderbarrels)

Quest says they are twice as good as dynamite in the implosion compressor.  In reality, they are 4x worse, and I suspect they are only intended to be used for seismic processing now.
They got nerfed at some point, but I couldn't find any issues or pull requests about it at all!  A nasty trick to be sure.

**Comment by minecraft7771** [comment]
[] Quest 2712 (Xenoxene Xenoxsis)
Quest states ~4% to get the culture, however it's 7,5%.

**Comment by guineawheek** [comment]
- [ ] quest 2203 (platinum)

quest states you need a platinum block to breed the bee but this was recently changed to a nickel block

**Comment by McFrugal** [comment]
- [ ] Quest 1279 (Firestone Ore/dust)

Quest states that IC2 nanosuit nightvision helps you see under lava.  It does not.  This was likely referring to the blindness effect you got by using nanosuit nightvision in the light, but that no longer happens.  It also implies you can make a hovering jetpack but that is not possible in MV.  Instead I think the only way to hover in MV is the thaumostatic harness.

**Comment by thePalindrome** [comment]
- [ ] Quest 1152 ( Fiery Bowstring)

The task points to the use of the bowstring pattern, but the extruder will only allow using the bowstring cast

**Comment by chochem** [comment]
> * [ ]  Quest 1279 (Firestone Ore/dust)
> 
> 
> Quest states that IC2 nanosuit nightvision helps you see under lava. It does not. This was likely referring to the blindness effect you got by using nanosuit nightvision in the light, but that no longer happens. It also implies you can make a hovering jetpack but that is not possible in MV. Instead I think the only way to hover in MV is the thaumostatic harness.

copterpack is a thing.


> The task points to the use of the bowstring pattern, but the extruder will only allow using the bowstring cast

?? there is no extruder involved with bowstrings

**Comment by chochem** [comment]
[ ] Mainframes, your first IV circuit.
Either one is 24 now:
![image](https://user-images.githubusercontent.com/40274384/198110222-60ece871-1577-4456-b3c9-7fa90c29e3e7.png)

**Comment by chochem** [comment]
@thePalindrome in case you are new to TiCon, the info of what a pattern can do is in the tooltip:

![image](https://user-images.githubusercontent.com/40274384/198120081-1998f880-9308-4c1b-a697-8a447f856b94.png)

**Comment by thePalindrome** [comment]
> there is no extruder involved with bowstrings as far as I remember.

There is an LV extruder recipe for turning flamestring into a flamestring bowstring and I was led somewhat astray by the fact the quest is indirectly dependant on having an extruder. You are correct though, and the quest does say to "Craft some fiery bowstring with it," although it uses the same wording with the magnalium crossbow pieces, even though they are not craftable via normal TiCo means.
