### ISSUE TITLE
GT Fluid Limiter Cover still has no recipe

### ISSUE THREAD

**Issue by albertopirillo** [GTNewHorizons/GT-New-Horizons-Modpack#11401]
### Your GTNH Discord Username

AlbyNexus#4160

### Your Pack Version

2.2.0.0-RC-3

### Your Server

Private 

### Type of Server

Vanilla Forge

### Your Expectation

It can be crafted and used in survival.

### The Reality

It has no crafting.

### Your Proposal

Add a crafting.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by NotAPenguin0** [comment]
Proposed recipe: Fluid limiter cover + Fluid shutter cover + Soldering alloy/molten tin/molten lead, in an assembler with Programmed Circuit #1 (same as all other related covers).

**Comment by fluffle** [comment]
+1 to this request. At the moment I haven't got a better solution than wireless fluid detector cover + advanced redstone receiver + shutter cover to limit the fill level of an input bus, because the normal fluid level emitters don't send their redstone signal internally to the hatch they are attached to. This is quite costly for the functionality.

FWIW I'd do:

    fluid limiter cover = shutter module cover + LV regulator + #1 + solder etc
