### ISSUE TITLE
Neutronium energy cell dont charge sub-ae buffers

### ISSUE THREAD

**Issue by dahgul333** [GTNewHorizons/GT-New-Horizons-Modpack#11540]
### Your GTNH Discord Username

@dahgul#1726

### Your Pack Version

2.2.0.0

### Your Server

Eta

### Your Expectation

Neutronium enenergy cell is used as a source of network energy, but it does not charge the buffers of sub-ae systems, which makes it necessary to make additional cells for each sub-ae

### The Reality

![image](https://user-images.githubusercontent.com/35747549/193905199-afba1120-4246-4897-8205-dffac5856c14.png)
![image](https://user-images.githubusercontent.com/35747549/193905228-7ce8b294-f846-46aa-bfb3-ff8cc4e99aff.png)

### Your Proposal

fix

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by YinScape** [comment]
I don't see why it should be otherwise?  It supplies energy as an infinite energy cell.  If you quartz fiber the subnetworks, it can pull from the cell just fine right?

**Comment by RaitGamerGR** [comment]
> 

Because you need to use Neutronium Cell on evey quantum ring you have. Ring cant connect instantly after server starts, so you need to use energy source to connect rings. Neutronium cell cant charge other energy cells, so you need to use Neutronium cell for every quantum ring. You cant connect ring to the energy acceptor because it will eat energy from your network like ytou haven't Neutronium energy cell, so for what you need Neutronium cell?
