### ISSUE TITLE
Lootgames Minesweeper phase change crash

### ISSUE THREAD

**Issue by mahorych00** [GTNewHorizons/GT-New-Horizons-Modpack#11609]
### Your GTNH Discord Username

mahorych00#9168

### Your Pack Version

2.2.0.0

### Your Server

SP

### Type of Server

Open To LAN

### Your Actions

Was playing Minesweeper with my friend, we made it to the end of phase 2, left-clicked on the last remaining block and instead of changing phases the world closed, and could only be reopened after reloading the client.

### Crash Report

[2022-10-09-4.log](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/9742548/2022-10-09-4.log)
[crash-2022-10-09_23.29.07-server.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/9742549/crash-2022-10-09_23.29.07-server.txt)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by TheIronBird** [comment]
same thing has happened to me very rarely 
[crash-2022-11-13_15.21.35-server.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/9998258/crash-2022-11-13_15.21.35-server.txt)
[crash-2022-10-13_02.27.23-server.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/9998259/crash-2022-10-13_02.27.23-server.txt)

**Comment by BritishCynic** [comment]
As this crash has not had new comments for a while, it is being closed. If you can reproduce this crash on current dev, please leave a comment to re-open with a full log report of the crash.

**Comment by captainjolt** [comment]
I just had this happen to me on my SP world.
[crash-2023-06-14_05.03.05-server.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/11744483/crash-2023-06-14_05.03.05-server.txt)

**Comment by SeseMueller** [comment]
Same here, 2.5.1. https://mclo.gs/Ab6vsAp

**Comment by leumasme** [comment]
Can confirm + full repro/cause:
This happens when winning by revealing a field which has 0 nearby mines.
- [`revealField`](https://github.com/GTNewHorizons/LootGames/blob/master/src/main/java/ru/timeconqueror/lootgames/minigame/minesweeper/GameMineSweeper.java#L296-L326)(1) will call `revealAllNeighbours` to  reveal all neighbors since it's a 0-mine field
- [`revealAllNeighbours`](https://github.com/GTNewHorizons/LootGames/blob/master/src/main/java/ru/timeconqueror/lootgames/minigame/minesweeper/GameMineSweeper.java#L328-L354) will call `revealField`(2) on each unrevealed neighbor
- `revealField`(2) will call [`checkWin`](https://github.com/GTNewHorizons/LootGames/blob/e76544a87a057bc314398e9865c983f6387edf38/src/main/java/ru/timeconqueror/lootgames/minigame/minesweeper/MSBoard.java#L105-L125). For the last field, this will return true and `onLevelSuccessfullyFinished` is called
  - `onLevelSuccessfullyFinished` also sets `board` to null until the next level is generated
- After `revealAllNeighbors`, `revealField`(1) will continue and call `checkWin` as its last action.
  - Since `onLevelSuccessfullyFinished`->`revealField`(2) has already called marked the level as finished, `board` is now null, so `checkWin` runs into a Null Pointer Exception
