### ISSUE TITLE
Incorrect en_US translation of Aluminum

### ISSUE THREAD

**Issue by ah-OOG-ah** [GTNewHorizons/GT-New-Horizons-Modpack#11616]
### Your GTNH Discord Username

OmniSlaves#6732

### Your Pack Version

2.2.0.0

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

While using en_US language, "Aluminum" should be the spelling. Searching for it in NEI should bring up all aluminum items.

### The Reality

Searching for "Aluminum" only brings up Aluminum Nitride. All other aluminum items are "Aluminium," the international spelling.

### Your Proposal

Change en_US localization to properly reflect US spelling.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by leagris** [comment]
Consider there is no `en_UK,` or other English localization regions for Gregtech, so the `en_US` locale serves English globally for all World regions understanding English. In this context international/scientific term feels more appropriate. It has also the advantage of requiring no change.

If you really want it to be changed the US way, you could contribute the various non-US English localization files, so the change does not backfire from non-US English users.

Otherwise, Feel free to modify your local copy of the locale file from resources so it suits your spelling expectations without impacting other non-US English users.
