### ISSUE TITLE
Nerf some MV chemical part

### ISSUE THREAD

**Issue by ArtherCasan** [GTNewHorizons/GT-New-Horizons-Modpack#11658]
### Your GTNH Discord Username

ArtherSnow#6574

### Your Pack Version

2.2.0.0

### Your Proposal

There are 2 nerf points:
1. If you dont want to craft PVC , Bio line and CBD,then it's no need to craft MV chemical reactor.
2. Si(sg) is crafted for transistor,but you can craft SMD transistor(with 1 Gaillum Foils and 8 Fine Annealed Copper Wire 120eu/t) to skip the Si(sg) line in MV time

### Your Goal

above 2 points, I suggest to change 4 recipes
1.SMD Transistor recipe
before:
![Skip_Transistor](https://user-images.githubusercontent.com/45914538/196016823-0ba63008-b618-4ff8-817a-28161b3a6407.png)
input:1 Gaillum Foils + 8 Fine Annealed Copper Wire
cost: 120eu/t 16s
output: 16 SMD transistor

after:
input:1 Gaillum Foils + 16 Fine Annealed Copper Wire
cost: 480eu/t  8s
output: 32 SMD transistor

2.HSiCl<sub>3</sub> Chemical Reactor
before:
![HSiCl3_1](https://user-images.githubusercontent.com/45914538/196016833-3bc37303-bee6-4678-9c46-a72db3d93f3c.png)
input : 1 Si + 3 HCl
cost: 30eu/t 15s
output: 2 H<sub>2</sub> + 1 HSiCl<sub>3</sub>

after:

input: 1 Si + 3 HCL
cost: 120eu/t 7.5s
output: 2 H<sub>2</sub> + 1 HSiCl<sub>3</sub>

3.SiCl<sub>4</sub> recipe
before:
![SiCl4_1](https://user-images.githubusercontent.com/45914538/196017104-798d8bb8-0a0f-4c49-aaa7-f60f957a4fba.png)

input: 4 Cl<sub>2</sub> + 1 Si
cost: 30eu/t 20s
output: 1 SiCl<sub>4</sub>

after:
input: 4 Cl<sub>2</sub> + 1 Si
cost: 120eu/t 10s
output:1 SiCl<sub>4</sub>

4.SiCl<sub>4</sub> and SiH<sub>4</sub> recipe
before:
![SiCl4_2](https://user-images.githubusercontent.com/45914538/196017105-a4b18094-2245-4f1c-aea1-e1974811a442.png)
input: 1 HSiCl<sub>3</sub>
cost: 30eu/t 12s
output: 1 SiH<sub>4</sub> +  3SiCl<sub>4</sub>

after:
input: 1 HSiCl<sub>3</sub>
cost: 120eu/t 6s
output: 1 SiH<sub>4</sub> +  3SiCl<sub>4</sub>

### Your Vision

Make Si(eg) line is on right positioin and MV chemical meaningful

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Dream-Master** [comment]
you need SiEg in Ae system later on so you not skip it but for smd components you are right.

**Comment by Dream-Master** [comment]
If we change the Transistor smd recipe to 480 eut/t we need to change the other smd transitor recipes as well.

**Comment by chochem** [comment]
> If you dont want to craft PVC , Bio line and CBD,then it's no need to build chemical reactor.

I have no idea what that is supposed to mean. you certainly need chem reactors. I also don't understand why it would be important to change the silicon recipes.

For the SMD thing you are wrong. That lets you skip normal transistors but it does not let you skip the si(sg) line! You need the si(sg) for wafers. You really can't skip it.

Nerfing smd transistors is still an okish move I guess but make sure the transistor skip quest is removed too if this gets nerfed.

**Comment by Dream-Master** [comment]
To be honest why we would need two parts of Transistord diodes etc if we can skip them? But this have not todo with SiEg. If we want people use the basic parts first and the smd later we need to make a recipe change for all smd parts

**Comment by ArtherCasan** [comment]
I think the every tier chemical reactor should be crafted in every volt stage.
So I want to change some key recipe to MV level let the MV CR be necessary.
It's a wired opinion I admit

**Comment by chochem** [comment]
ah, corrected to MV chem reactor. now I get what you are saying at least. yea the MV CR is not that important at the moment.

**Comment by NoX-programer** [comment]
My opinion is no need to nerf silicon that was recently already nerfed! And no need to nerf non-silicon crafts, because gallium is already expansive material!

**Comment by Glease** [comment]
> If you dont want to craft PVC , Bio line and CBD,then it's no need to craft MV chemical reactor.

I'm not sure why do these need MV chemical reactor at all.

> SMD Transistor recipe

Gallium isn't that rare at HV or above (due to HV macerator), but is next to nonexistent in tiers before. If the player went to that extra mile for gathering more gallium than necessary, I don't see why they skipping the chain for a little while should not be allowed. Honestly not sure what good this change serves, if any at all.

> Silicon recipes retier

The gap between needing silicon and MV chemical reactor is extremely small (only real gate is crafting the LV circuit assembler IIRC, there is a reason this is put in MV tab not LV tab) and a retier like this plays poorly with human mind. 
For less informed people, who actually setup the sodium chain, they aren't likely to change to the new recipe, as the existing setup works, albeit a bit slowly and a bit too power hungry.
For people with knowledge of all 4 recipe chains, they'll just handcraft a small batch and use the MV recipes, which, I'm not sure if it's a good thing at all. 
If you push it further back to HV then we have the most advanced silicon recipe in LCR, so it's not likely to be used either. 

What you are proposing isn't really improving the situation in any aspect I can think of.

> I think the every tier chemical reactor should be crafted in every volt stage.
So I want to change some key recipe to MV level let the MV CR be necessary.
It's a wired opinion I admit

Then I think you wouldn't mind I add the silly suggestion label? /s

Seriously though, I don't see the point of this. Chemical reactors are fairly cheap machines and skipping one isn't that big of a deal. 

We already have fewer and fewer choice in low tier (also due to silicon change). Let's not make the tech *tree* even more of a tech *line* than before.
