### ISSUE TITLE
Maintenance Hatch railcraft crowbar recipe consumes crowbar

### ISSUE THREAD

**Issue by McFrugal** [GTNewHorizons/GT-New-Horizons-Modpack#11681]
### Your GTNH Discord Username

McFrugal#5033

### Your Pack Version

2.2.3

### Your Server

SP

### Your Expectation

I made a maintenance hatch, using a full durability railcraft crowbar.  Expected the crowbar to be damaged.

### The Reality

The crowbar simply vanished from the workbench inventory.

### Your Proposal

Reduce durability on the crowbar when used in the recipe, like it does to other tools.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by joshaup1999** [comment]
This has been a known issue for a long long time, Use the GT crowbar instead

**Comment by chochem** [comment]
I just added a line to a quest to please use the gt crowbar and not touch this one. But maybe we should be more drastic and just remove the crafting recipe. Or is there any use case I dont know about?

**Comment by bombcar** [comment]
The railcraft crowbar does a lot of things in railcraft itself and I'm not anywhere nearly 100% to be able to say that the GT one will do the same things. The few I've done, the blue has worked as well as the red.

Proposal for discussion - what if we changed the recipe for the RED crowbar to require an iron BLUE crowbar at 100% and some red dye? Or something like that, so that it's not removed from the game, but it is harder to "accidentally" make.

And then change the tooltip noting that we think it might be not needed.
