### ISSUE TITLE
Fluid Storage Bus partitioning doesn't work

### ISSUE THREAD

**Issue by schliip** [GTNewHorizons/GT-New-Horizons-Modpack#11682]
### Your GTNH Discord Username

schlip#8417

### Your Pack Version

2.2.3.0

### Your Server

Private server

### Type of Server

Vanilla Forge

### Your Expectation

Partitioned fluid storage bus on dual interface/fluid interface allows only selected fluids

![image](https://user-images.githubusercontent.com/34576051/196568539-6fdf4a46-3dc2-4f1d-b00e-b2933d1a5e80.png)

### The Reality

If fluid storage bus is facing an interface, selected fluids are ignored, and all fluids can be inserted.

### Your Proposal

Fluid storage bus partitioning disallows non-selected fluids.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by joshaup1999** [comment]
You have to partition it with cells

**Comment by schliip** [comment]
> You have to partition it with fluid cells

This is only true for cells; the fluid storage bus partitioning works properly when it is attached to a tank.
(and it was partitioned with cells in this case anyways)

**Comment by kvieta** [comment]
Same in 2.2.7, attached to T.F.F.T Multi IO hatch in this case. Whitelisted fluids are ignored.

**Comment by joshaup1999** [comment]
Is the TFFT properly compatible with ae2fc anyways? Not sure how many people use it cause of how bad it’s been in the past with that multi fluid io hatch

**Comment by Jenyariy** [comment]
I have the same issue with T.F.F.T Multi I/O Hatch in the new 2.2.8 version of modpack. I believe that it's the Multi I/O Hatch issue, because on other tanks Fluid Storage Bus works fine, it disallows non-selected fluids as expected, but when you attach it to Multi I/O Hatch of T.F.F.T tank it ignores selected fluids and everything can be inserted.

**Comment by Impos913** [comment]
Same issue but with a different block. Using a fluid storage bus on a matter condenser as an overflow trash can for some fluids. But all fluids can be inserted, the filter is not working.

**Comment by Godelboard** [comment]
So we are having the issue too. Made some test setups and these are our results:

- Partitioned Fluid Storage bus -> Dual Interface (subnetwork) -> Fluid storage bus on Super Tank I
    - Super tank receives fluid outside of partitioned setup.
- Partitioned Fluid storage bus -> TFFT Multi IO hatch.
    - TFFT receives fluid outside of partitioned setup.
- Partitioned Fluid Storage bus -> Super tank
    - Tank receives only fluids inside of paritioned setup.

I'm going to guess that blocks having the ability to receive multiple fluids/have multiple tanks is what's breaking the fluid partitioning. I _believe_ this was working in 2.2.0.0 because we were using it on our TFFT then and it didn't have any problems that I remember. So this broke some time after 2.2.0.0.

> Is the TFFT properly compatible with ae2fc anyways? Not sure how many people use it cause of how bad it’s been in the past with that multi fluid io hatch

It just got a rework for 2.2.7. And yes, it is compatible, even the old version worked. It's definitely an issue with fluid storage bus, not TFFT.
