### ISSUE TITLE
Soldering iron now useless

### ISSUE THREAD

**Issue by Minepolz320** [GTNewHorizons/GT-New-Horizons-Modpack#11791]
### Your GTNH Discord Username

Minepolz320#9473

### Your Pack Version

2.2.0.0

### Your Proposal

wires should be connected only with a soldering iron and cut off with wire cutters

### Your Goal

Disable the ability to connect wires with wire cutters without using solder

### Your Vision

Maybe add recipes for joining wires using a soldering iron

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by boubou19** [comment]
won't be added. It's a game: if you need to spend metric tons of something just to do the same as before, without even gaining some new features, that's called pure tedium. And that is against the vision, as it's what kills the fun.

Also fun fact, you can use the autoconnect of the cable to bypass such an implementation, so that would be bypassed making this change useless.

i'm closing this.

**Comment by Minepolz320** [comment]
@boubou19 ok, thanks for reply
