### ISSUE TITLE
Thaumcraft Golems Do Not Work As Expected in Personal Dimensions

### ISSUE THREAD

**Issue by turkiman1337** [GTNewHorizons/GT-New-Horizons-Modpack#11829]
### Your GTNH Discord Username

turkiman1337#6378

### Your Pack Version

2.2.3

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

Tried to assign a golem to multiple blocks in a personal dimension, expected golem to be linked to the blocks I clicked

### The Reality

Golem could not be linked to more than one block, it would simply replace the last link.

### Your Proposal

Golems in personal dimensions should link to blocks in a manner consistent with other dimensions.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by albus12138** [comment]
When EntityGolemBase and ItemGolemBell load marker.dim from nbt, it cast int to byte. So, if dimensionId > 127, it will overflow, then removed by validateMarkers().

example:
dimensionId = 181, will be saved as -75

EntityGolemBase.func_70037_a
![image](https://user-images.githubusercontent.com/9742081/236741387-730ed3b0-25b2-4a73-a518-93507e6e62da.png)

ItemGolemBell.getMarkers
![image](https://user-images.githubusercontent.com/9742081/236741433-7e3f84da-dc8c-4fba-bcc8-43e8ce3b75d0.png)

EntityGolemBase.validateMarkers
![image](https://user-images.githubusercontent.com/9742081/236741581-5f4b8de3-d66f-4827-a666-cb65c7b19c39.png)

issue #8942 should be caused by this problems too.
