### ISSUE TITLE
Missing new persulfade ore processing inside NEI Diagram

### ISSUE THREAD

**Issue by FrancoisHarvey** [GTNewHorizons/GT-New-Horizons-Modpack#11842]
### Your GTNH Discord Username

FrancoisHarvey

### Your Pack Version

2.2.3

### Your Server

Private

### Type of Server

Vanilla Forge

### Your Expectation

Expecting to see the new recipes using persulfade for some ores processing added in https://github.com/GTNewHorizons/GT5-Unofficial/pull/1063 in the NEI Diagram for ore processing as some are very usefull for early tiers increase some rare dust output (rutile from bauxite)

### The Reality

The new recipes isn't visible inside the NEI Diagram (probably because the recipe is custom added and not using the WASHING_SODIUMPERSULFATE flag) 

### Your Proposal

Add these new recipes inside NEI Diagram

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Eldrinn-Elantey** [comment]
![image](https://user-images.githubusercontent.com/46845681/207591994-5fa97723-c59b-46e2-bfe8-102c16343842.png)
![image](https://user-images.githubusercontent.com/46845681/207591998-0f33582c-0ede-4091-a684-245fefc92bda.png)

**Comment by D-Cysteine** [comment]
Oops, this shouldn't be closed yet. Can be closed with https://github.com/GTNewHorizons/nei-custom-diagram/pull/15

The root cause is that the ore processing diagram previously was hard-coding the input fluid amounts (1000 for mercury, 100 for sodium persulfate). These new recipes are 500 sodium persulfate, so they were not found. The fix makes it so that the diagram will handle any amount of input fluid, instead of hard-coding it.

As a separate question, do we want to update the new recipes to also use 100 sodium persulfate, so that they are the same as the older sodium persulfate chemical bath recipes?
