### ISSUE TITLE
Fluid Regulator should mention machine controller instead of restone

### ISSUE THREAD

**Issue by AaYsAuNkAaMI** [GTNewHorizons/GT-New-Horizons-Modpack#11909]
### Your GTNH Discord Username

ASuKa_Zz#4038

### Your Pack Version

2.2.0.0

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

Fix the fluid regulator redstone control

### The Reality

When use the fluid regulator redstone control, If u choose transportation by ticks it works well, but when choose the other two options, there is something wrong about them. When u set work when detecting signal, it will works same as trans by ticks, and the redstone signal make no difference, and When u set invert mode, it just doesn't work, and also the redstone signal makes no difference. 

### Your Proposal

Just fix it up :)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Glease** [comment]
Fluid regulator does not react to redstone signal. Use a machine controller to take the redstone signal and pass it to the fluid regulator.

Be aware of what machine controller do though. You typically want to put fluid regulator on pipes/tanks/hatches, not singleblock machines...

---

To others: fluid regulators and other covers should mention machine controller cover and soft mallet instead of redstone in GUI/tooltip.
