### ISSUE TITLE
GC and GS generate no ores anymore

### ISSUE THREAD

**Issue by Dream-Master** [GTNewHorizons/GT-New-Horizons-Modpack#11900]
It seems GC and GS not generate GT ores on Planets anymore.
Tested with lates dev version.

link below:
https://www.dropbox.com/s/rd1547mnxqavlzk/Dev-Pak.rar?dl=0

**Comment by Dream-Master** [comment]
[fml-client-latest.log](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/10127433/fml-client-latest.log)
[latest.log](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/10127434/latest.log)
[GregTech.log](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/10127435/GregTech.log)

**Comment by GDCloudstrike** [comment]
after some testing I found out that this is caused by the latest version of galacticraft. 
Using this version http://jenkins.usrv.eu:8080/job/Galacticraft/150/ ores generate as they should,
but using the latest version http://jenkins.usrv.eu:8080/job/Galacticraft/153/ stops ores from generating.

This is how the ores on IO looked like when I spawned on the planet using galacticraft 3.0.49: 
![image](https://user-images.githubusercontent.com/93287602/205401430-09f09805-dbfc-4dbc-a532-ada10c426511.png)

and this is after flying a bit further out using galacticraft 3.0.52 (the ores in this picture are the bottom right corner of the picture above):
![image](https://user-images.githubusercontent.com/93287602/205401489-cbed2b3d-e6f0-4515-970d-36a47f4c4e2d.png)

**Comment by glowredman** [comment]
When enabling debug and trace logging in GalacticGreg, you get this (log is by Dream):
[fml-client-latest.log](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/10144862/fml-client-latest.log)
It is possible that this PR: https://github.com/GTNewHorizons/Galacticraft/pull/58, though I'm not sure how.

**Comment by chochem** [comment]
if I understand the jenkins versions GDC posted correctly (github releases would have been easier), then its has to be one of these commits:
![image](https://user-images.githubusercontent.com/40274384/205407347-b9de3f32-5475-4572-901f-a33652f79aed.png)

**Comment by chochem** [comment]
tested it myself now and can confirm what I posted in the last post. Latest master works fine, which is 3.0.50-GTNH. But latest version from the dev branch does not, which is 3.0.52-GTNH-pre.

**Comment by Dream-Master** [comment]
@chochem did you test with my testpack or a older version?

**Comment by chochem** [comment]
I have a 2.2.3 that has like 10-15 updated mods (including mixins and all that)

**Comment by Dream-Master** [comment]
so it is not the version i tested and possible cant be reproduced. i will upload my latest dev pack maybe you can check with this pack to make it reproduce able

**Comment by miozune** [comment]
It's working now: https://github.com/GTNewHorizons/Galacticraft/pull/60
