### ISSUE TITLE
Crafting Unstable Ingots gives stable ingots

### ISSUE THREAD

**Issue by MarloGr** [GTNewHorizons/GT-New-Horizons-Modpack#11998]
### Your GTNH Discord Username

Mako#8317

### Your Pack Version

2.2.7

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

Crafted Unstable Ingots with an activated Division Sigil that has durability, while holding shift. Expected to blow up or get lots of ingots that will explode within 10s. Tested with Crafting Table and Crafting Station in versions 2.2.3 and 2.2.7.
Posted a video detailing the bug on the GTNH Discord server: https://discord.com/channels/181078474394566657/1053325550690771024

### The Reality

Got stable Unstable Ingots that did not blow up, could be used for crafting and worked normally.

### Your Proposal

Blow up the player or get Unstable Ingots that will properly explode after 10s

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Rika-TH** [comment]
Shift click crafting more than one ingot
Making one ingot and using a saw on it
Crafting in an AE system
These are just some of the ways unstable ingots can be crafted as stable, as it stands a player who doesn't interact with the community or tries something that would be seen as really dumb is blatantly penalised in a sense by this with all these ways of making them stable
What's worse is that a player trusting in the pack would expect they can only do extruding etc once they have a stable sigil

Because of this I believe that "unstable" ingots should be removed, they should just always be stable with the stable sigil being used as an unbreakable sigil if there were any scenario where automated unstable is required
