### ISSUE TITLE
Significant FPS drops when opening Inventories/Machine GUIs

### ISSUE THREAD

**Issue by IsOobt** [GTNewHorizons/GT-New-Horizons-Modpack#12094]
### Your GTNH Discord Username

oobt#8431

### Your Pack Version

2.2.8

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

Opened up machines/invetories/terminals to look inside/place items in.

### The Reality

I was able to do this, but I noticed that my 100+ fps drops to below 30 fps when inside an inventory GUI.

### Your Proposal

Prevent major FPS drops when opening inventories/GUIs

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by DLowHP** [comment]
I noticed a similar thing on my instance. It seems that the problem is related to the NEI interface, because after disabling it, the frame rate seems to be stable when opening/closing the inventory interface - this, I think, is also a good enough temporary workaround.

---

Launcher: Prism Launcher 9.2
Modpack version: 2.7.1
Java: Adoptium 21.0.6
