### ISSUE TITLE
Coolant Tower doesn't consume steam (Good Generator)

### ISSUE THREAD

**Issue by Impos913** [GTNewHorizons/GT-New-Horizons-Modpack#12104]
### Your GTNH Discord Username

ImpossibleVT#3997

### Your Pack Version

2.2.8

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

Using Coolant Tower to cool off steam I get from SC steam turbines to get back the distilled water. It works fine with 1 input hatch but too slow, it consumes all the steam in the input hatch to make distilled water every 5 seconds. So i placed more input hatches to speed up the process.

### The Reality

If it has more than one input hatch filled with steam, it doesn't consume any steam but outputs distilled water.

### Your Proposal

Consume steam properly.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by fluffle** [comment]
I just wanted to leave a +1 for this still happening in 2.3.2, not super surprising since there haven't really been any meaningful changes to behaviour since the coolant tower was first implemented.

I'm guessing the call to `depleteInput` here on line 199 doesn't handle depleting >1 input hatch's worth of steam:

https://github.com/GTNewHorizons/GoodGenerator/blob/master/src/main/java/goodgenerator/blocks/tileEntity/CoolantTower.java#L199

`depleteInput` will return false if a simulated drain drains less than the fluid amount required:

https://github.com/GTNewHorizons/GT5-Unofficial/blob/master/src/main/java/gregtech/api/metatileentity/implementations/GT_MetaTileEntity_MultiBlockBase.java#L943

But the code for `checkRecipe_EM` doesn't check the return value. I don't think it's possible to use `depleteInput` here anyway. Even if it was called within the loop, because it does its own loop over the input hatches it would potentially end up depleting a different hatch to the one being processed in the recipe handler. This handler needs to loop over the hatches rather than the fluidstacks they contain, so that it can deplete them as they are accumulated in the recipe handler.

**Comment by fluffle** [comment]
It seems I have entered the ultimate GTNH endgame: sending PRs to fix bugs encountered while trying to complete the pack ;-)
