### ISSUE TITLE
Rebalance LootGames

### ISSUE THREAD

**Issue by KaneHart** [GTNewHorizons/GT-New-Horizons-Modpack#12227]
### Your GTNH Discord Username

StoneLegion#0026

### Your Pack Version

2.2.3

### Your Proposal

Remove it forever.

### Your Goal

I was told like 6+ years ago that it was staying as it was going be worked on... It was never worked on it's cheap. Hell people join my server and see or OC message at spawn we remove it and bitch and quit... When one single mod defines people to play or quit because of how cheap it is then it needs to go... It's also a eye sore and people use ore finder want with loot games to find it easier...

Time for it to retire... 

### Your Vision

My Vision is to come after Rogue Dungeons next ;) @mitchej123 says I will bitch anyways so here we go! 

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by KaneHart** [comment]
Suggestion: To add the Blocks into one the other mods or into a new Mod to replace it for the blocks themselves as people use them for base designs. Maybe also recipes to craft them.

**Comment by chochem** [comment]
I understand the mod is originally from Nami, but I have to agree with this. Lootgames is not in a good spot. People just play Minesweeper (usually by posting on discord and asking others what to do) and then use that to skip a lot in the early tiers. Or they cheat Game of Light by recording everything in chat instead of making circuits. And there is no exploration aspect to it either since it works with the Ore Finder Wand.

That is not exactly gregtech playstyle or otherwise what we are aiming for with this pack imo.

**Comment by Dream-Master** [comment]
Ok but we not remove the mod. We can lower the chance a room spawns.

**Comment by KaneHart** [comment]
> 

I think that is more fair. Maybe also make it so you can't use the ore finder wand to find it's blocks also?

**Comment by chochem** [comment]
I think blacklisting it from the ore finder wand would be a good move if that is possible. They don't even need to be that rare then.

That would at least remove my main issues with it because you cant reliably do one after the other to bypass the normal game.

**Comment by cainiaojun** [comment]
Lootgames need to be re-balanced indeed.
But could we find a way that allows players play the games without any rewards? I like those game. I want to play those game in my base instead of run around to find one.

**Comment by chochem** [comment]
I am at least changing the title based on what dream has already said.

@cainiaojun check out https://www.microsoft.com/en-us/p/microsoft-minesweeper/9wzdncrfhwcn ;)

**Comment by cainiaojun** [comment]
> I am at least changing the title based on what dream has already said.
> 
> @cainiaojun check out https://www.microsoft.com/en-us/p/microsoft-minesweeper/9wzdncrfhwcn ;)

I know that but isn't a minecraft-style minesweeper cooooooooooooool?

**Comment by Viktor-KN** [comment]
What the difference between spending time by playing game crafting circuits or playing mini-game in a game... Both time consuming. Loot games can be more enjoyable time-spending activity, have some excitement. Leave it as is. From all loot games I had completed maybe one item was really useful for me is Supertank II... Other staff is not so good, mainly cos you can't use it before you near its tier...

**Comment by Hikari1nVoid** [comment]
This is a speedrun strategy.Players do solve minigame and they deserve the reward.
Everyday I see players facing 2 unveiled block with one mine in it(aka deadly choice)in lvl4 minesweeper.All minigames are hand-solved and can not be automated.
PS:You could try a fresh restart with lootgames and you will find out you still have to build aluminium&silicon&plastic lines.not too much work was skipped,just some trash time waiting for materials.
Another example is Tic blast furnance.Are you going to remove village generations since it allows player to skip hand crafting the tic BF?

**Comment by vovaksenov** [comment]
I suggest make the loot contain less items each completion. Diminishing returns would make the lootgames still feel like a cool feature to those for whom the benefits are intended, but discourage grinding them like ross machines in the past. In best case scenario, this should apply to each tier of the rewards separately.

**Comment by chochem** [comment]
the loot is a bit reworked now. in particular no more HV parts and more non-tech rewards. happy to hear some feedback once people play with the new version. https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/pull/13069
