### ISSUE TITLE
Staballoy Constructs in the EEC are OP.

### ISSUE THREAD

**Issue by SweptWasTaken** [GTNewHorizons/GT-New-Horizons-Modpack#12355]
### Your GTNH Discord Username

Swept#2000

### Your Pack Version

2.2.8

### Your Proposal

The drop-rate for staballoy products from golems in the EEC should be heavily **HEAVILY** nerfed, since in a couple of minutes you can generate thousands of staballoy blocks/plates/ingots which can easily be macerated and centrifuged to get huge returns of uranium 238 and titanium.

![image](https://user-images.githubusercontent.com/49448379/214116337-7cedbc12-d612-4c19-902e-d3b10cb03e8c.png)
Correct me if i'm wrong but is this a guaranteed drop chance for a staballoy block from each golem?

![image](https://user-images.githubusercontent.com/49448379/214116537-11cb703b-549f-4de6-9656-d5743e979f28.png)

Output from a LuV EEC with a Looting 3 sword in it after leaving it running for less than 5 minutes.
![image](https://user-images.githubusercontent.com/49448379/214117167-cf0e10d4-4d52-40e7-9ccd-bb855826615d.png)

### Your Goal

In my opinion this is way too OP for ~~LuV tier~~ ZPM tier, and makes setting up mining/processing chains for Uranium 238 and Titanium basically useless. 

### Your Vision

It would improve the pack by making uranium 238 less cheesy to get.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Hikari1nVoid** [comment]
I can aquire similiar amount of staballoy with enderio spawner & WA working at HV@6A.(but more laggy)
RNG should apply here.
maybe a gtpp stuff?

**Comment by cainiaojun** [comment]
It is absolutely OP, but it needn't a nerf in this way.
In LuV or ZPM, Players can just mine U238 instantly, and they wouldn't need a lot of them. The amount of U238 in Radon cycle is small compared with the amount of it in Naquadah Fuel when players had not been care about it.
EEC is positioned as a lategame machine that could reduce lag and increase fps. We should try to limit the use of EEC in EV and IV instead of Luv.

**Comment by cainiaojun** [comment]
> I can aquire similiar amount of staballoy with enderio spawner & WA working at HV@6A.(but more laggy) RNG should apply here. maybe a gtpp stuff?

Isn't the Staballoy Constructs in ZPM?

**Comment by Hikari1nVoid** [comment]
> > I can aquire similiar amount of staballoy with enderio spawner & WA working at HV@6A.(but more laggy) RNG should apply here. maybe a gtpp stuff?
> 
> Isn't the Staballoy Constructs in ZPM?

In perspective of power comsumption I don't think there is anything wrong in it

**Comment by Hikari1nVoid** [comment]
>>In my opinion this is way too OP for LuV tier ZPM tier, and makes setting up mining/processing chains for Uranium 238 and Titanium basically useless.
And you keep your titanium line in ZPM,while you can get Titanium dust in bedrock dim and T6 You should have pure Titanium ore???

**Comment by Pxx500** [comment]
Even golems don't drop this much iron, also you get titanium by mining other things anyway so this doesn't really increase TPS or anything. I'd say it's suboptimal at best because of the fact that you unlock it at ZPM and don't really struggle with any of those resources.
I would nerf it for consistency though

**Comment by boubou19** [comment]
Why i wouldn't nerf this one: U238 is required in the radon loop. Radon is annoying to get in decent quantities, and this somewhat helps alleviating the issue.

**Comment by Tommeh1** [comment]
Imo these golems have no use by the time you can get to them, to the point that they may as well not exist.

**Comment by Pxx500** [comment]
I never used them and never had to since uranium is abundant as a byproduct from mining

**Comment by Hikari1nVoid** [comment]
I'll say it is hilarious to nerf them since you don't need them.
EEC as a QOL feature works pretty fine rn,saving everyone's tps from mobspawners.
Also since staballoy construct starts at zpm so you should already harvested tons of titanium from bedrock or VM.

**Comment by Steelux8** [comment]
Yeah, I think this is OP if used at EV/IV, but at ZPM it's a non-issue.

**Comment by tong-ge** [comment]
Staballoy constructs(x) Jews(√)

**Comment by gespispace** [comment]
I think this is OP, because you can get it in EV. You don't need to be at ZPM. Staballoy Golems spawn in the toxic biome, and with witchery you can change a biome to the toxic biome in early EV or ever in HV. So some players use it to get unlimite uranium and titanium in too early stage of the game.

**Comment by boubou19** [comment]
it's ok, it has the witchery gate
