### ISSUE TITLE
Output hatch Locked to Hydrazine changes it's variant once server restarts 

### ISSUE THREAD

**Issue by tommy307507** [GTNewHorizons/GT-New-Horizons-Modpack#12369]
### Your GTNH Discord Username

Hebi#2752

### Your Pack Version

2.2.8

### Your Server

GTNHSMP

### Type of Server

Thermos

### Your Expectation

It was locked to 
![image](https://user-images.githubusercontent.com/49487505/214305155-e3d27f30-8b5b-4b74-9491-631e23c55212.png)
this variant of hydrazine, I expect this to stay as it is 

### The Reality

, and
![image](https://user-images.githubusercontent.com/49487505/214305024-f580ed35-6a19-47aa-a570-291004bcf98f.png)
It changed to this variant once server restarts

### Your Proposal

Either group them up or made them not change.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
This is part of a family of bugs and problems (https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/10847, https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/10839, https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/10208) all caused by GTNH Lanth (formerly botdustries) registering fluids that already exist. Then FML does the rest. (see https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/10847#issuecomment-1198665516)

The obvious solution would be to remove them but sadly some other devs have actively working against that - without any explanation. (see https://github.com/GTNewHorizons/GTNH-Lanthanides/pull/44)

So don't hold your breath, this is unlikely to get fixed anytime soon. :(

**Comment by chochem** [comment]
@GlodBlock @miozune instead of pessimism, maybe I should just ping you guys:

Since you did not like my advice before, do you maybe have a different plan on how to fix these issues?

**Comment by Steelux8** [comment]
From what I know, the GT++ ones existed first. From my viewpoint, the only two reasonable solutions for this would have been to use the GT++ fluids on botdustries or, after GT++'s license changed to allow changes, move these fluids to coremod and use them from over there on GT++ and botdustries both.
