### ISSUE TITLE
Parallel Logic not working correctly in Industrial Centrifuge

### ISSUE THREAD

**Issue by BritishCynic** [GTNewHorizons/GT-New-Horizons-Modpack#12365]
### Your GTNH Discord Username

BritishCynic#9193

### Your Pack Version

2.2.9-5-dev-pre

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

The multiblock should be correctly judging how many parallels it can run, and then running accordingly.

### The Reality

When running at IV, for example, the Centrifuge will accept small numbers of Purified Naquadah Dust, but putting in bigger amounts results in it voiding an amount of dust (I think it was 28) and then shutting down complaining about lack of power. Identical unchanged setup in 2.2.8 processes this dust parallels correctly.

### Your Proposal

Fix the parallel logic.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by BlueWeabo** [comment]
How the fuck did you break it.

**Comment by BlueWeabo** [comment]
Can you show scanner infos?

**Comment by chochem** [comment]
was immediately able to reproduce. On 5-dev-pre which uses gregtech-1.7.10-5.09.41.237-pre and GT-PlusPlus-1.7.10-1.7.201

setup: IV centrifuge (single IV energy hatch, with 2A provided, so power should be fine)
input: stack of purified pile of Nq dust.
result: immediately shuts down

alternative input: 4 purified pile of Nq dust.
result: runs fine as expected

scan after shutdown: 
![image](https://user-images.githubusercontent.com/40274384/214526685-bbf7d55b-ddc8-4106-9438-8c48f3f6fc2f.png)
![image](https://user-images.githubusercontent.com/40274384/214526772-1ea978fb-b9f2-4446-9acd-585c5c025e0a.png)

![image](https://user-images.githubusercontent.com/40274384/214527140-2d0663bb-7186-430c-9252-25b03866f7de.png)
maybe it is related to the ULV stuff you were doing? dont know when you changed that.

Scan while running the 4 dusts:
![image](https://user-images.githubusercontent.com/40274384/214527682-e6261e19-da89-425b-a6b1-106c589c04be.png)

that looks slightly wrong too (assuming the scan is accurate):
- the eu/t means it doesn't have the discount! 4x5x4^4=5120, but 4x5x0.9x4^4=4608
- the 73 ticks look correct though.


More testing: the threshold is 13. up to 13 dusts work (well single recipe starting with full buffer). 14+ void.

Interestingly, for 14-15 it runs a bit before voiding, so there was time to scan:
![image](https://user-images.githubusercontent.com/40274384/214529988-f886594e-b94e-4b93-9751-02570a42b129.png)
well that looks bad lol, it uses 2.2A instead of max 1.
