### ISSUE TITLE
Move back the TGS multi to HV

### ISSUE THREAD

**Issue by k3nw4y** [GTNewHorizons/GT-New-Horizons-Modpack#12477]
### Your GTNH Discord Username

k3nw4_y#7664

### Your Pack Version

2.2.8

### Your Proposal

Move back the TGS to HV instead of gating to higher tiers, so that players use TGS instead of lagging the server by over using EIO farmiing station, if its making too much wood, why dont nerf the output? or  a way to make it wood with like fertilizer and make it renewable?

### Your Goal

Reduce the lags caused by Farming station while growing trees

### Your Vision

lets players scale better than spamming more tree farms?

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by chochem** [comment]
Having used the farmer a fair bit, its really not laggy for the amount of wood you need pre IV. only starts to have an impact when you go for multiple stacks per second. but by then you have TGS.

I say its fine as is.

**Comment by boubou19** [comment]
To be more specific, it's the frequency at which the trees are growing, as growing a tree is not a free operation TPS wise. TGS was balanced around using WA for tree growth + WA on the enderio farm. But if you use the farmer normally and with "small" trees, (ie not jungle trees, rainforest, sacred, redwood,...) it's not laggy.

If you want a really efficient wood farm at low tiers, do bonsai crops. Those are really good and don't spam tree growth.

So yeah i'm closing this ticket because it is fine as it is, as by the time you start to need stupid amount of wood, the TGS is availiable already.
