### ISSUE TITLE
ADD 4a 16A 64A wireless energy hatch

### ISSUE THREAD

**Issue by FoKuCNiK** [GTNewHorizons/GT-New-Horizons-Modpack#12518]
### Your GTNH Discord Username

FoKuCNiK

### Your Pack Version

last version

### Your Proposal

ADD 4a 16A 64A wireless energy hatch

### Your Goal

ADD 4a 16A 64A wireless energy hatch

### Your Vision

ADD 4a 16A 64A wireless energy hatch

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Connor-Colenso** [comment]
This won't happen for the time being, the intention is to use lasers for very energy intensive activities i.e. MEBF, MVF, DTPF OC or Adv AL. If you only want to transport < 2B EU/t then wireless suffices just fine. The purpose of this is to reduce cable spam, not make every single form of energy transport obsolete except wireless. Your LCRs, regular multis etc all benefit from this.

In addition to this with the new UEV capacitor you can transfer 1T EU/t into the LSC, so that should no longer be a serious bottleneck.
