### ISSUE TITLE
Add a reward type questline

### ISSUE THREAD

**Issue by chochem** [GTNewHorizons/GT-New-Horizons-Modpack#12598]
### Your GTNH Discord Username

chochom#0271

### Your Pack Version

2.2.9 (java19)

### Your Proposal

Here is the problem I want to solve: 

Completionists strive to complete all questlines for those juicy green checkmarks and full completion counters: 
![image](https://user-images.githubusercontent.com/40274384/218879895-22d167d8-c533-435f-acff-00655d668e82.png)
![image](https://user-images.githubusercontent.com/40274384/218880733-dd160308-5432-4e07-b300-9690fe151a2c.png)

However, that does not make much sense for the Coins or the Reward questlines. There is nothing to complete here!

Proposed solution: add a modifier to questlines like 'isrewardquestline'. Turn that on for the 'Coins, Coins, Coins' and the 'Reward Area'. When the modifier is on this should have 2 effects: 1) there is no completion counter on the top 2) in the list of questlines this questline always shows a green checkmark.

I am open to other solutions.

### Your Goal

To make completionists happy.

### Your Vision

There is nothing to complete on reward tabs, so they shouldnt have completion checks like counters or should always be complete like green checkmarks.

This should also be good for any use outside of GTNH.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by AbdielKavash** [comment]
Repeatable quests already mark the tab as complete when you complete each one at least once. I do not see a problem with having to complete each repeatable quest once for a "full completion" reward.

Even if the suggestion was implemented, a tab-wide option is too coarse. There are repeatable reward-like quests scattered in other tabs, for example ComputerCraft components in the Advanced Automation tab, and the Pure Tear quest in the Adept Thaumaturgy tab. If repeatable quests should not count towards full completion, this decision needs to be made per quest, not per tab.

A different issue (this is what the discussion started about on discord) is that if a completionist playthrough is to be supported, it needs to be ensured that the consumables for a repeatable quest can be infinitely farmed, so that the player is never locked out of completing the quest at least once because of poor choices. Currently at least the loot bag trades in Reward Area do not follow this principle; it is possible for the player to open every LV bag that is obtainable from quests, and then never be able to complete the LV > MV Lootbag Trade quest in that playthrough.

* **Suggestion 1:** _Add a repeatable way of obtaining loot bags needed for the trade quests, so that it is not possible to lock oneself out of completing every quest at least once._

This should _not_ be an easy, fast, or efficient way to farm items from the lootbag, only a (potentially very expensive) workaround to being able to complete the trade quests. Possible suggestions that were brought up in discord were consuming an expensive item from the tier for the trade (e.g. a Transmission Component for the voltage tier bags); locking the trade to two tiers above the bag tier when most of the rewards become irrelevant (so the LV bag trade unlocks in HV); and adding a very long cooldown to the trade (a day or even more), so that even if it is farmable it is not at all practical.

The second issue with full completion are XOR quests. To the best of my knowledge, there are (as of 2.2.0.0) three sets of XOR quests in the pack:
* "You are not prepared!!!" in Multiblock Goals (crafting a smeltery or looting it from a village)
* "The choice: [Aspect]" in Novice Thaumaturgy (giving you an aura node of a given aspect, the player chooses one of thesix primals)
* "Reward choice: Personal Dimension -or Loot" in Space Race (Either a personal dimension, or one of fairly meaningless random loot rewards)

While completing only one choice out of a set of XOR quests is required for completion of the tab itself (green checkmark); the other quest(s) in the set are still not marked as complete themselves. Therefore, a "complete every quest" goal (as opposed to "complete every chapter of the questbook") is currently unachievable.

* **Suggestion 2:** _Rework XOR quest groups and turn them either into OR quests, or into a single quest with choice rewards._

The only difference between the pair of smeltery quests is that making it yourself awards a minor reward (10 Aluminum Oreberries, 2 Steam Age lootbags, and 50 Technician coins). Looting the smeltery from a village gives no rewards. I think this could be turned into an OR quest; because the rewards are fairly trivial; and moreover, the crafting quest actually contains _crafting_ tasks for the smeltery components. It can not be completed simply by looting a village. Therefore, I think it is fair to still give the player the rewards if they eventually craft a second smeltery themselves, even if they looted the first one.

The node quests could be turned into one quest with choice rewards. While the "choose one, you will not be able to get the others" fits well with the Thaumcraft design (choices have permanent consequences), I do not think it justifies locking the player out of full completion of the pack. Although the consumable requirements of each of the 6 quests are different (6 clusters of the respective aspect), they could be easily merged into one quest that requires one of each and lets the player choose the node.

Finally, the reward choice in Space Race could trivially be merged into one quest. The only difference between the two quests is the description.

**Comment by chochem** [comment]
At the start there you are just mixing up a pure reward tabs with exchange quests like the pure tear. That is something completely different.

And no, we wont make lootbags farmable. Certainly not efficiently farmable lol. They are not balanced around that. We dont want passive circuit production based on a lootbag farm or similar stuff.

XOR quests are already completely fine from a completionist point of view. the counters were fixed and you get the checkmark too. Not that I particularly care about them, but that all works fine now.

**Comment by AbdielKavash** [comment]
That depends on what you define as "100% completion" of the quests. Do you define that as "completing (getting a ckeckmark for) every chapter"? Or as "completing (getting green icon) every quest"? The more exceptions, like tabs that are automatically completed, or quests that do not count towards the completion of their tab, you add, the more meaningful the distinction between the two definition becomes, and the more challenging the latter goal becomes compared to the former.

In my opinion either one is a valid definition. Currently, the former is possible; the latter is not.

**Comment by Alrightsc** [comment]
I don't think it's even realistically feasible to make the QB be fully completable. Even if it is, we're still talking 3000 quests (of which more are being added almost daily...) to do. It would be just a complete waste of time

**Comment by chochem** [comment]
> I don't think the QB can't be fully completed due to the Personal Dim quest that has a fork in it; one of those two will forever be uncompletable.

no, that is fine. xor quests are accounted for in the couter and the checkmark
