### ISSUE TITLE
Tinkers Crafting Station crashes when next to a Filing Cabinet/dynamically sized inventory

### ISSUE THREAD

**Issue by NoNameISNoMan** [GTNewHorizons/GT-New-Horizons-Modpack#12658]
### Your GTNH Discord Username

nooneinparticular#8014

### Your Pack Version

2.2.8

### Your Server

SP

### Java Version

Java 8

### Type of Server

Single Player

### Your Actions

Open a Tinkers crafting table with a backpack in hand. Works on slabs too. Easily replicated.

### Crash Report

https://paste.ubuntu.com/p/RcF2xfV5HR/

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by chochem** [comment]
I tried a backpack from the backpack mod, forestry, and adventure backback. I cant replicate this.

I assume 'tinkers crafting table'= Crafting Station. I dont know what you mean by Tinkers workbench though. that is not a thing.

**Comment by NoNameISNoMan** [comment]
It's still crashing if I just open the crafting station!
https://paste.ubuntu.com/p/PhDTRfsyRH/

**Comment by chochem** [comment]
any added mods or other modifications?

**Comment by NoNameISNoMan** [comment]
Test results:
Not fixed by full reload.

**Comment by NoNameISNoMan** [comment]
> any added mods or other modifications?

Optifine and FTB utilities with the library.

**Comment by NoNameISNoMan** [comment]
Seems to me that the cabinet is improperly loading its contents into memory when asked to do so, not from its own UI.

**Comment by NoNameISNoMan** [comment]
And that's that! There rest is probably on you. Tell me if something is needed.

**Comment by chochem** [comment]
so what are the steps to reproduce? have a filing cabinet next to it?

**Comment by chochem** [comment]
kind of. I got some graphical glitches and a slightly different crash:

[crash-2023-02-20_14.49.44-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/10785427/crash-2023-02-20_14.49.44-client.txt)

**Comment by chochem** [comment]
apparently this is an older problem, but whatever the fix was didnt work. https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/10933

My test was on 2.2.10 java9+.

**Comment by NoNameISNoMan** [comment]
> so what are the steps to reproduce? have a filing cabinet next to it?

You also need to unload the cabinet, be it going far away for a while or reloading the world.

**Comment by chochem** [comment]
I got a crash without any unloading. stood next to it the entire time.

**Comment by xiPakuL** [comment]
This also happens placing the tinkers station next to a drawer controller.
But very unreliably and over a chunk border.

**Comment by mitchej123** [comment]
```
java.lang.IndexOutOfBoundsException: Index: 47, Size: 47
    at java.util.ArrayList.rangeCheck(ArrayList.java:659)
    at java.util.ArrayList.get(ArrayList.java:435)
    at net.minecraft.inventory.Container.func_75139_a(SourceFile:104)
    at net.minecraft.inventory.Container.func_75131_a(SourceFile:390)
```

**Comment by wlhlm** [comment]
I've looked into this a little bit: This seems to be caused by a sync issue between client and server and is not specific to ExU, but any dynamically sized inventory (that a player can access, ie. `isUseableByPlayer()` is true) in general. I can trigger the same crash with an ME Chest adjacent to the Crafting Station.

What happens is, when the player opens the Crafting Station GUI, _on the client_, a `CraftingStationContainer` instance is created, which checks for adjacent inventories and adds slots to itself depending on the inventory size. This works fine for fixed size inventories like Chests for which `getSizeInventory()` returns a static value on both client and server. However, the Filing Cabinet for example has a dynamic inventory size depending on the type of items it contains. The problem is that _on the client_, unless the Filing Cabinet has been previously opened, the tile entity for the Filing Cabinet doesn't know about its contents and defaults to a size of 1.

What happens now when opening the GUI for the Crafting Station is that the corresponding container is initialized with an adjacent inventory size of 1. After that, the Crafting Station logic on the server sends the real inventory contents (via `S30PacketWindowItems`) to Crafting Station container on the client and the OutOfBoundsException is generated in `net.minecraft.inventory.Container#putStacksInSlots`.

Unfortunately, I'm not really sure what a good way to fix this is, specifically how to synchronize the adjacent inventory before opening the Crafting Station GUI.

Here is a more complete stacktrace from the devenv:
```
java.lang.IndexOutOfBoundsException: Index: 47, Size: 47
	at java.util.ArrayList.rangeCheck(ArrayList.java:659) ~[?:1.8.0_362]
	at java.util.ArrayList.get(ArrayList.java:435) ~[?:1.8.0_362]
	at net.minecraft.inventory.Container.getSlot(Container.java:130) ~[Container.class:?]
	at net.minecraft.inventory.Container.putStacksInSlots(Container.java:558) ~[Container.class:?]
	at net.minecraft.client.network.NetHandlerPlayClient.handleWindowItems(NetHandlerPlayClient.java:1202) ~[NetHandlerPlayClient.class:?]
	at net.minecraft.network.play.server.S30PacketWindowItems.processPacket(S30PacketWindowItems.java:70) ~[S30PacketWindowItems.class:?]
	at net.minecraft.network.play.server.S30PacketWindowItems.processPacket(S30PacketWindowItems.java:78) ~[S30PacketWindowItems.class:?]
	at net.minecraft.network.NetworkManager.processReceivedPackets(NetworkManager.java:241) ~[NetworkManager.class:?]
	at net.minecraft.client.multiplayer.PlayerControllerMP.updateController(PlayerControllerMP.java:317) ~[PlayerControllerMP.class:?]
	at net.minecraft.client.Minecraft.runTick(Minecraft.java:1693) ~[Minecraft.class:?]
```

**Comment by miozune** [comment]
One option would be adding compat for TiC side, as there're only a handful of TEs with dynamic amount of slots. Make crafting station Container send update packet for adjacent cabinet info.
Another option is just blacklisting them. Easy enough and only a few people would be sad. Especially nobody will use crafting station with ME chest.
