### ISSUE TITLE
"TiC Tooltips, Botania"sometimes crashes my game when hovering over an tool

### ISSUE THREAD

**Issue by Marvi44** [GTNewHorizons/GT-New-Horizons-Modpack#12722]
### Your GTNH Discord Username

Marvi444[Ger]#2788

### Your Pack Version

2.2.0.0

### Your Server

singleplayer

### Java Version

Java 8

### Type of Server

None

### Your Actions

there is not much to say here. i played like normal and when hovering over my wooden tinkers construct starter pickaxe from the bonus chest"TiC Tooltips, Botania" crashed crashes my game. it sometimes keeps happening whit other tools. one time it also crashed while holding shift while i was hovering over an tool. didint happen whit other types of items before

### Crash Report

https://paste.ubuntu.com/p/zJFdKVtKfq/
https://paste.ubuntu.com/p/B7pdvMz8GJ/

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by r1tsuu** [comment]
Botania causes the problem, so issue should be related to Botania, not TC. Probably before hovering your pickaxe you did hover with shift some Botania item that can be in Baubles slot.
It has fixed in 1.19.12-GTNH version of Botania by @jss2a98aj https://github.com/GTNewHorizons/Botania/pull/19
In your logs you haved 1.9.10-GTNH version of Botania.
Update the modpack and all should be fine.

**Comment by chochem** [comment]
so this is fixed already?
