### ISSUE TITLE
Increase amount of slots for industrial apiary

### ISSUE THREAD

**Issue by Team1Warlord** [GTNewHorizons/GT-New-Horizons-Modpack#12781]
### Your GTNH Discord Username

KOT_BHE_3AKOHA#7758

### Your Pack Version

2.2.12-2

### Your Proposal

Industrial apiary should get more slots for bee production from 9 to at least 16 or more

### Your Goal

If you use production cards bees can void some of its production because there is no slots for them

### Your Vision

Industrial apiary should be more usefull until you get mega apiary 

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by noobyaran9** [comment]
This also happens when you use acceleration upgrade with bees that have eon lifespan.

Recommendation:
1. Change the logic of industrial apiary to be like the usual apirary where the bees just produce at the end of every bee tick 
OR 
2. Change the inventory slot to behave like normal apiary where the items will be in a hidden queue when inventory is full until the player pulls the item out
