### ISSUE TITLE
Bound Pickaxe Tooltip flickers

### ISSUE THREAD

**Issue by LewisSaber** [GTNewHorizons/GT-New-Horizons-Modpack#12829]
### Your GTNH Discord Username

Lewissaber#7231

### Your Pack Version

2.2.3RC-2

### Your Server

SP

### Java Version

Java 8

### Type of Server

Single Player

### Your Expectation

Step to reproduce
Open Recipe of Wyvern Pickaxe in NEI
Hover over bound pickaxe
Tooltip flickers

### The Reality

,

### Your Proposal

.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by boathouse2112** [comment]
This happens to the bound pickaxe, axe, and shovel, in their wyvern recipes but not to the other bound tools/weapons.
Those 3 show "Deactived" in NEI, but the other bound items don't.
The flickering happens if you search for `wyvern pickaxe` and click the recipe.
If you get to the wyvern recipe by going to the `bound pickaxe` recipe, and then right clicking to get the `wyvern pickaxe` recipe, the bound pickaxe in the xtreme recipe shows a solid "Deactivated" instead of flickering.
