### ISSUE TITLE
AE2 pattern substitutions will break crafting further down the line

### ISSUE THREAD

**Issue by Tommeh1** [GTNewHorizons/GT-New-Horizons-Modpack#12826]
### Your Pack Version

2.2.10

### Your Server

Private Server

### Java Version

Java 8

### Type of Server

Vanilla Forge

### Your Expectation

/

### The Reality

Whenever substitutions are allowed recipes further down the line may get stuck at half the target amount, even if the target inventory is clear and ready to go it will stay scheduled forever.

### Your Proposal

/

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
please test in newer ae. there were like 10 crafting related fixes between 2.2.10 and RC3.

you are a bit vague, but I am pretty sure thats one of them

**Comment by chochem** [comment]
you are so vague that it is impossible to tell. Nobody else has the problem though.

**Comment by chochem** [comment]
yea thats not a thing

**Comment by chochem** [comment]
'need more info' means: A specific simple setup to reproduce your bug.

**Comment by Tommeh1** [comment]
> 'need more info' means: A specific simple setup to reproduce your bug.

In theory something as simple as making a dust in a mixer and that recipe allowing for substitutions to then use that dust to make ingots should be enough to trigger it when ordering the ingot if ME still has to make that dust first.

**Comment by chochem** [comment]
> In theory something as simple as ME making a dust in a mixer and that recipe/pattern allowing for substitutions to then use that dust to make ingots should be enough to trigger it when ordering the ingot if ME still has to make that dust first.

just tried. works flawlessly

**Comment by Tommeh1** [comment]
In that case, can we get a config entry that switches ALL patterns to not use substitutions as a workaround?

**Comment by eigenraven** [comment]
Can you confirm what is your exact ae2 version number on the server?

**Comment by Tommeh1** [comment]
> Can you confirm what is your exact ae2 version number on the server?

appliedenergistics2-rv3-beta-175-GTNH.jar

**Comment by Tommeh1** [comment]
> maybe dont come up with a problem 'in theory' but actually make a simple test setup. There might well be a bug but its not what you are describing.

If there is more to it than that then i wouldn't know what could result in substitutions causing issues.

**Comment by eigenraven** [comment]
Here's what I know can cause issues: If you have using substitutions enabled on processing patterns, and some ingredient has an oredict tag that encompasses a lot of unrelated items. There was the `lv`/`mv`/`hv` oredict tags for example before 2.3.0 that were the cause of most of these issues. Crafting pattern substitutions get validated, it's not possible for processing patterns because there is no recipe object attached to the pattern, it's just a loose set of inputs/outputs so ae2 has to guess.

**Comment by chochem** [comment]
it bricks the most simple things and you somehow cant give us a specific setup.

**Comment by chochem** [comment]
the dust one doesnt. but that was NOT specific

**Comment by Tommeh1** [comment]
> the dust one doesnt. but that was NOT specific

Another one from yesterday that bricked the crafting of a dyson part was nickel-zinc ferrite ingots because the mixer recipe for ferrite mixture dust had subs enabled.

**Comment by chochem** [comment]
so, test:
- first pattern: ferrite mixture mixing - allow substitutions enabled (god knows why)
- second pattern: then in ebf with oxy for ingots
- no ferrite mixture in the system

result: works flawlessly

**Comment by Tommeh1** [comment]
> so, test:
> 
> * first pattern: ferrite mixture mixing - allow substitutions enabled (god knows why)
> * second pattern: then in ebf with oxy for ingots
> * no ferrite mixture in the system
> 
> result: works flawlessly
> 
> I feel like you are not actually trying this yourself.

That and all other recipes with subs enabled cause issues in our ME, if a small setup somehow doesn't suffer from the same issue then idk where something fucks up over subs being enabled.

**Comment by joshaup1999** [comment]
I have noticed this issue as well in 2.3, example of it is the tesseract recipe. It failed due to Enriched Uranium needing glowstone. AE detected the enceladus varient which then stalled the craft when it was attempted. Similar example as well is the CAL getting stalled up with wrong tier circuits in it

**Comment by AtomicGrog** [comment]
> > so, test:
> > 
> > * first pattern: ferrite mixture mixing - allow substitutions enabled (god knows why)
> > * second pattern: then in ebf with oxy for ingots
> > * no ferrite mixture in the system
> > 
> > result: works flawlessly
> > I feel like you are not actually trying this yourself.
> 
> That and all other recipes with subs enabled cause issues in our ME system, if a small setup somehow doesn't suffer from the same issue then idk where something fucks up over subs being enabled.

Can confirm it’s worse with larger volumes. I put that down to poaching though. It seems that substitution now occurs in a craft even if there’s a substitute part available even if the original intent was to craft and use the original item in the pattern.

 Suggesting two underlying causes:

1. the way substitution is being applied has changed, and ae doesn’t really know when a gt etc machine can/can’t cope with equivalents such as cal crafting second/third tier circuits (arrays for example)
2. we shouldn’t really have the substitute enabled on most processing patterns, but because it didn’t matter prior and it was defaulting enabled as a result of using same pattern terminal for mollec recipes which needed it for some recipes with hammers/wrenches etc. it’s happened.

I suspect I have 1000s+ processing patterns with substitute enabled due to the terminal default action. Some will be fine but a notable number will require manual fixing unless we have a override flag

**Comment by kstvr32** [comment]
> > > so, test:
> > > 
> > > * first pattern: ferrite mixture mixing - allow substitutions enabled (god knows why)
> > > * second pattern: then in ebf with oxy for ingots
> > > * no ferrite mixture in the system
> > > 
> > > result: works flawlessly
> > > I feel like you are not actually trying this yourself.
> > 
> > 
> > That and all other recipes with subs enabled cause issues in our ME system, if a small setup somehow doesn't suffer from the same issue then idk where something fucks up over subs being enabled.
> 
> Can confirm it’s worse with larger volumes. I put that down to poaching though. It seems that substitution now occurs in a craft if there’s a substitute part available even if the original intent was to craft and use the original item in the pattern.
> 
> Suggesting two underlying causes:
> 
> 1. the way substitution is being applied has changed, and ae doesn’t really know when a gt etc machine can/can’t cope with equivalents such as cal crafting second/third tier circuits (arrays for example)
> 2. we shouldn’t really have the substitute enabled on most processing patterns, but because it didn’t matter prior and it was defaulting enabled as a result of using same pattern terminal for mollec recipes which needed it for some recipes with hammers/wrenches etc. it’s happened.
> 
> I suspect I have 1000s+ processing patterns with substitute enabled due to the terminal default action. Some will be fine but a notable number will require manual fixing unless we have a override flag

Seconded. Since updating to 2.3.0 I’ve had this issue all over the place. The solution seems to be updating almost every pattern. Maybe a better solution would be an optional script to turn all patterns in network to not allow substitutions.

**Comment by chochem** [comment]
hmm, I have no idea why you all have substitutions on if you dont want substitutions. I never did that.

But the more interesting claim is that this didnt cause any issues previously. That suggests something is different here that is fixable. Best try to narrow that down.

From what you seem to suggest a test setup to reproduce should not just include patterns but also what amount of certain items you have in the system. Ideally someone should provide such info.

**Comment by eigenraven** [comment]
Previously ae2 just ignored the substitution setting most of the time except for directly pulling items out of the system, the new implementation can resolve substitutions even for missing items to request them from different patterns, hence why we see more issues.

**Comment by chochem** [comment]
well that sounds like the new system is better then.

**Comment by eigenraven** [comment]
Adding a way to modify patterns in batch would be useful, not only to fix substitutions in old bases but also to swap out circuits for example. It could probably use a new block, kind of like the IO Port but for patterns

**Comment by Tommeh1** [comment]
> hmm, I have no idea why you all have substitutions on if you dont want substitutions. I never did that.
> 
> But the more interesting claim is that this didnt cause any issues previously. That suggests something is different here that is fixable. Best try to narrow that down.
> 
> From what you seem to suggest a test setup to reproduce should not just include patterns but also what amount of certain items you have in the system. Ideally someone should provide such info.

For us it started in 2.2.8 iirc and then got worse in 2.2.10 and even worse in 2.3.0

**Comment by Tommeh1** [comment]
> Adding a way to modify patterns in batch would be useful, not only to fix substitutions in old bases but also to swap out circuits for example. It could probably use a new block, kind of like the IO Port but for patterns

I would prefer a global toggle from the config, that resets them all on startup once and then disables it if the source of the problem can't be found.
It will be way easier re-enabling the need for subs on the handful of things that need it than the hundreds if not thousands of things that need to have it disabled now.
Yesterday i spend nearly an hour fixing more of these again.

**Comment by AtomicGrog** [comment]
> 

Answer is relatively simple (for me at least) previously it didn’t seem to matter and as the same pattern terminal is also used to make molec patterns which at times need substitutions it was easily just to leave it enabled. In hindsight we shouldn’t have done it.

At the same time however apart from a few use cases it still shouldn’t matter if the the substitution was working well. For example I was finding HSS-S dust substitution was taking place when the craft was being determined but then failing when attempting to start the craft. However when you check there is no real substitute for HSS-S dust.

**Comment by chochem** [comment]
if hss-s dust crafting gets stuck (or are you are crafting something else that uses it?) and none of the ingredients have any oredicts with other options, then maybe there is indeed a bug there on top somewhere. Maybe you can do what Tommeh didnt and specify a simple reproducable testsetup. starting with being able to reproduce it yourself.

**Comment by AtomicGrog** [comment]
> if hss-s dust crafting gets stuck (or are you are crafting something else that uses it?) and none of the ingredients have any oredicts with other options, then maybe there is indeed a bug there on top somewhere. Maybe you can do what Tommeh didnt and specify a simple reproducable testsetup. starting with being able to reproduce it yourself.

I’ll give it a try. Yes it get stuck, no nothing else is taking it (my ae is practically idle since 2.3.0 update as I haven’t repaired things like ability to make quantum circuits etc via optical). So in many ways it’s an ideal opportunity. How I can depict sufficient to reproduce it your end I don’t know though. To do that I’ll need to know what the craft calculation thinks it can use as a substitute, which I can’t see.

it’s also worse with higher volume output. For example if I request a uev precision laser it will almost certainly work. If I request a stack it will illicit tbe problem. I.e it won’t auto start, I get presented with a button to start which now logs a warning regarding something being missing. The logging is a real bonus, at least I can track down and change the pattern.

**Comment by AtomicGrog** [comment]
> 

Ok egg on my face time and apologies for wasting peoples time. My issues are not substitution related which makes sense because it shouldn't matter if the flag is enabled in a pattern if there are no actual substitutions. I tested this via a ordictionary export to a chest using dustHSSS in the pattern and it only exported HSS-S dust.

Test case (Produce 256 Tairitsu foil as required for Optical Circuit Board in PCB factory):

Carbon: available 4
Vanadium dust: available 3
Tungsten dust: available: 8
Naquadria dust: available 7
Black Plutonium dust: available 1
Bedrockium dust: available 4
Tairitsu dust: available 46, to craft 27
Tairitsu ingot: available 30, to craft 64
Tairitsu plate: to craft 64
Tairitsu foil: to craft 64
(All taken from craft screen)

Error returned on attempting to start craft was along lines of:
'Could not start craft, ingredient went missing: 46 * gt.bwMetaGenerateddust.10106 (gt.bwMetataGenerateddust.10106.name)'

.. The hint to resolution was i had 26 Tairitsu dust in my ae i.e. half the amount required, and the error was not the 27 required to craft.

Additionally this points the problem away from what is commonly considered the cause for these kinds of errors with ae. i.e. 'something else used the dust between calculation and starting', in my current situation this is very unlikely, i even went as far as to screenshot dust levels for hss-s overnight to sanity check that it wasnt changing.

And now the admittance... My ore and by inclusion all dust storage is a separate AE storage capability, and due to a historical 'type' and capacity limitations i used to feed all dusts back into the ore ae storage. To do this i used a high priority storage bus with a oredict configured with something like 'dust*' set to 'export only' and for some reason it seems to have reverted to bi-directional, when and why I don't know, which meant that the dust was shown directly via the storage bus intended export as well as the main one that sees the ore ae storage in general i.e. a duplication. 

It's also worth noting that i have pretty large material levels so this wouldnt really affect usage of things like redstone or iron, copper, even tungsten etc. they are typically in the 100 million to billions range. It's only the actual crafted (typically mixer) produced dusts that are low volume.

The reason it was so erratic is simply because there are different volumes in the patterns, the Tairtsu dust pattern is for 27 dust and the ingot is for 64. At times multiple dust crafts have to take place to meet the quota which makes the stored dust irrelevant which probably hides the issue, at other times it depends on the dust as a filler in which case the issue is exposed.

(Fwiw it would have been near impossible pre-V2 to identify this without the error message identifying the actual dust with an issue).

Tips for others: if you have a error complaining about materials missing and you see some in ae, try pulling it out to ensure that all of it is actually available.

**Comment by AtomicGrog** [comment]
![Screen Shot 2023-03-16 at 10 23 35 pm](https://user-images.githubusercontent.com/9132219/225767617-c9abf9c1-f76c-444d-b283-a2561e86a1d8.png)

I believe this is not correct. Whilst there may be an edge case where copper and annealed can be used interchangeably my far the majority of the time they cannot and as such Annealed should not be part of the more generic '*AnyCopper', this also occurs on processed annealed items such as bolts, wire and plates.
