### ISSUE TITLE
Add a machine that recreates geological processes to produce minerals from elements/simpler compunds.

### ISSUE THREAD

**Issue by Thor3005** [GTNewHorizons/GT-New-Horizons-Modpack#12899]
### Your GTNH Discord Username

Thor3005#8156 

### Your Pack Version

2.2.10 (If I recall correctly)

### Your Proposal

Since currently the only way to get mica, which you NEED for most EBFs, is a rare vein, and there are no great ways to renewably get various minerals such as lapis (except for thaumcraft), what if there was a multiblock that worked by recreating the geological processes/environment needed to produce different minerals. Put in some fluorine, aluminium, oxygen, water, etc, and the required circuit, and it makes mica, kyanite and pollucite (preferably in mineral form not ore form, since ores might have byproducts that are compounds you didnt insert into the machine, unless some precise sub-ore type is made that doesn't give byproducts that way). Like a fancier chemical reactor that makes good conditions for things to happen.

### Your Goal

To make mica, lapis, etc renewable not too late in the game. (I'm only in LV so far so I don't know which voltage to suggest it for) 

### Your Vision

Blast furnaces galore, renewable ic2 coolant, a new sci-fi technology machine. 

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by posiaden123** [comment]
this would trivialize the early game, and in later voltages there are already many sources of renewable minerals.

**Comment by King65868** [comment]
Mica already has infinite sources from both bees, crops, and a chemical line btw.

**Comment by BestMod** [comment]
not to mention the five meteor rituals that contain a boatload of it

**Comment by dest1n1s** [comment]
Despite there's various way to get those minerals, adding such a mechanism is a complement to this game. It's unreasonable that you couldn't get gallium hydroxide or other compounds from ways other than mining.

**Comment by boubou19** [comment]
The idea is nice, but here are the few issues i see with that:
- you want it so you can make mica more easily but:
  - mica is not needed in that much quantities, only for coils above cupronickel ones
  - When you discover mica, you get tons of it
  - fluorophlogopite exists and is able to replace mica in the creation of the mica insulator foils, so starting with nichrome coils you can totally make mica optional, so only a mica vein is really needed for the progression
- you want it so you can recreate compound materials but: you will need to get base materials for the compounds, which are all aluminium/alumina based, so you'll need to breakdown compounds first before making them, which is more tedious than just mining them.
- That multiblock will just be a more evolved version of equivalent exchange, which i'm not sure we want because the game is pretty much correctly balanced, so who knows what hidden damages it will have to the balance?
- Mining ores is tedious only below HV, after that tier you start having miners everywhere, so you don't waste your time mining for stuff, so its correct place would be below HV. But then it would trivialise early game progression, which is not something we want.
- This would be content below IV tier, and we all agreed in the dev team not to add content in IV tier or below without a good reason.

**Comment by EnderProyects** [comment]
If could be nicer if instead of creating ores is used for creating decoration blocks like basalt, for example
