### ISSUE TITLE
Inaccurate Shading with multiple different multiblock casings

### ISSUE THREAD

**Issue by CarbonatedTea** [GTNewHorizons/GT-New-Horizons-Modpack#13102]
### Your GTNH Discord Username

CarbonatedMilk#0125

### Your Pack Version

2.3.0

### Your Server

private server

### Java Version

Java 19

### Type of Server

Vanilla Forge

### Your Expectation

Trying to set up the Pyrolyse Oven multiblock. I expected the shading of the casings to be the same as the rest of the base.

### The Reality

As I was placing casings, I noticed the shading of the multiblock was significantly off compared to the rest of the base, as shown in the attached images. This also has happened while setting up an EBF, I don't have any screenshots of that.
![2023-03-31_18 40 34](https://user-images.githubusercontent.com/121204426/229250886-028d92f7-7df9-4aaf-83dd-fb5397f85158.png)
![2023-03-31_18 40 17](https://user-images.githubusercontent.com/121204426/229250890-45faaeb4-d64c-455a-bbfd-237f4c4a6db0.png)

### Your Proposal

Fix the shading of the casings in some way.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Connor-Colenso** [comment]
I've noticed this as well with J19, can I ask what system you are on? Curious if this is a mac issue.

**Comment by CarbonatedTea** [comment]
I am not on Mac, I am running the game on a windows PC.

**Comment by chochem** [comment]
can confirm myself (windows, java20, no fc/of but af/neod/nf).
its went away though and I dont know hot to reproduce it

**Comment by dvdmandt** [comment]
Not sure if related, but there's also a bug where "holes" are created in surfaces. It frequently happens near where this bug happens.

![image](https://user-images.githubusercontent.com/11985732/229617669-c535042e-9ca0-42fc-894b-dabbe0b13950.png)
Note the hole in the ground and the hole in the supertank corner.

Some reflections (copy&paste from Discord):

> It's not Java19 and it's not recent. It was at least in 2.2.3. Frequently happens around the super agressive ambient occlusion bug, though not exclusively.
> Once it happens, it stays after relog and until client is restarted. Placing blocks can remove the effect, but it comes back if the newly placed blocks are removed again.
> It still happens with 2.3.0 and Java8.
> It usually happens near GT multiblocks, and for some reason I feel like it happens mostly around multiblocks with coils, but that might just be coincidence. I've also had it happen in a vanilla village building (weirdly shaped hole on wall only, no super AO), several chunks from the nearest GT machine/whatever.
> What is most interesting about it is the weird shape of the holes. It's not just a displaced vertex or something that would make some form of sense, it's a very peculiar cutout from multiple block faces.

Other pictures:

These two images are in the same chunk, note how some machines are affected and others not:
![image](https://user-images.githubusercontent.com/11985732/229618081-2894adc5-ece2-4ad7-ab52-ba78817461ff.png)
![image](https://user-images.githubusercontent.com/11985732/229618159-234fb0c4-d626-472f-a168-d896cfd2f0f7.png)

From Discord again:
> Also note how the shadows/AO appears directed towards/away from specific blocks or something

Also, **@LewisSaber#7231** on Discord said:
> Happens after viewing multiblock preview in nei

**Comment by chochem** [comment]
oh yea, nice one lewis. I looked at a nei preview and 2 seconds later it started after not having it for at least a week. very reproducable.

**Comment by Rasa0** [comment]
Running single player directly from the client, that i shut down and restart every day.
I also havn't seen it happening when playing on days when i didn't build any multiblocks and thus not looking at any structures in NEI,

Did some testing, restarting the game a couple of times to narrow it down.

It seem to mostly trigger for the specific machine when viewing the NEI multiblocks structure, but viewing any coiled machine seem to slightly affect most coiled machines, though it become more severe for a specific machine if you look at it in NEI.
ExxonMobil Chemical plant need to be looked at specifically in NEI for it to be affected, even though it have coils so it isn't universal.

Casings only seem to get shading issues, but hatches and other iteractable blocks stops rendering whole sides.

Multiblocks with transparent blocks like the Large Sifter, Lapotronic Supercapacitor stops rendering the internal blocks past the transparent ones.

It becomes very noticible with the Lapotronic Supercapacitor since all the capacitors inside disapear, and you can look down into the void.
![image](https://user-images.githubusercontent.com/4034636/229870294-eb85c408-40e1-474f-b20a-e47ae6b5770c.png)
