### ISSUE TITLE
changing p2p me interface to other p2p modes eats the upgrade

### ISSUE THREAD

**Issue by miaowwwwww** [GTNewHorizons/GT-New-Horizons-Modpack#13246]
### Your GTNH Discord Username

LEO_PREMIUM#3437

### Your Pack Version

2.3.2

### Your Server

zeta

### Java Version

Java 8

### Type of Server

Don't know

### Your Expectation

it returns the upgrade to ae or just drop it

### The Reality

changing p2p me interface to other p2p modes eats the upgrade

![image](https://user-images.githubusercontent.com/49871378/232633796-319f4964-d174-4259-9343-0c344130f8cd.png)
![image](https://user-images.githubusercontent.com/49871378/232633825-12c87080-06f8-4e68-b417-b7b11af69b92.png)
![image](https://user-images.githubusercontent.com/49871378/232633852-0ee60dad-1fb9-4888-80c2-59ba9466ba1f.png)

### Your Proposal

it returns the upgrade to ae or just drop it

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by firenoo** [comment]
This will be fixed by making p2p interfaces no longer convertible to other types

**Comment by toenailsin** [comment]
With the addition of the P2P Dual Interface, this issue is back. Swapping between a normal and dual interface will void all Patterns, Cards and Inventory of the Interface.

![before](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/102740/f5d04fa3-170a-41e4-9b51-c598ef7378ae)
![action](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/102740/dd4251ae-6a4b-46c6-bfa9-b9268193d2f7)
![after](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/102740/ee8b0cb4-34d8-4a20-9e2c-cf405b6611ee)
