### ISSUE TITLE
Betterp2p - Can't type space or copy paste

### ISSUE THREAD

**Issue by madmacf** [GTNewHorizons/GT-New-Horizons-Modpack#13319]
### Your GTNH Discord Username

svendsved#8232

### Your Pack Version

2.3.3.3

### Your Server

Single player

### Java Version

Java 19

### Type of Server

None

### Your Expectation

When trying to write someting like "chemical reactors 2" in the advanced memory card, the space button (and ALT+CTR+right SHIFT) works as ENTER button. So it's not possible to write text like that when naming p2p tunnels.

Also it makes it impossible to copy paste text.
Annoying when naming a lot of new p2p.

### The Reality

See previous

### Your Proposal

Fix it, so it's easier to write and copy paste text in the interface :-)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by madmacf** [comment]
I'm on an english windows 11 danish keyboard layout.
No client mods. Just installed new 2.3.3.3 on java 19 on MultiMC.
Anything else you need?

**Comment by firenoo** [comment]
Going to reply to your other comment in https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/13073#issuecomment-1528842500 (which will be closed).

2.3.3 does not contain the patch yet. You can try downloading the latest release of BetterP2P from the github [here ](https://github.com/GTNewHorizons/BetterP2P/releases/tag/1.1.9) and inserting that version to your mods folder to see if that fixes, otherwise let me know/reopen the issue.
