### ISSUE TITLE
Easy Platinum - Valuable bee - ExtraBees

### ISSUE THREAD

**Issue by EIioH** [GTNewHorizons/GT-New-Horizons-Modpack#13452]
### Your GTNH Discord Username

ElioH#1043

### Your Pack Version

2.3.3

### Your Proposal

Remove Valuable bee or change bee products

### Your Goal

This is a very easy way to get platinum at the start of the game. There is no need to organize a platline. The honeycomb has a 1% chance, but with the help of frames it is quite easy to bring it to 100% and get 1 platinum ingot every minute without difficulty in processing. You can significantly increase your platinum supply by using accelerators and more apiaries.

### Your Vision

Exclude this method of obtaining platinum.

### Final Checklist

- [ ] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Runakai1** [comment]
Considering that in the early game the amount of PMP you get via nickel ores and Multiblock miners, this is insignificant due to direct smelting to nuggets. 
Also, platline will be more lucrative in the end of early game making the plat bee obsolete. 

It's supporting your early game production of the already easy gather able platinum while it's no match in the further tiers and the amount of platinum it will need.
