### ISSUE TITLE
Crash when opening a EV Seismic Prospector Book 

### ISSUE THREAD

**Issue by pokeball99** [GTNewHorizons/GT-New-Horizons-Modpack#13487]
### Your GTNH Discord Username

Kekel7#9661

### Your Pack Version

2.3.0

### Your Server

Private

### Java Version

Other versions in between

### Type of Server

Don't know

### Your Actions

Open a EV Seismic Prospector Book

### Crash Report

https://cdn.discordapp.com/attachments/401118216228831252/1106591714040348783/message.txt

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by wlhlm** [comment]
(BTW, I tried to reproduce this, but couldn't)

**Comment by wlhlm** [comment]
Reporter has provided a [save for testing](https://cdn.discordapp.com/attachments/401118216228831252/1107694010388205648/New_World.7z).

**Comment by wlhlm** [comment]
Reported has provided an [inventory for testing](https://cdn.discordapp.com/attachments/401118216228831252/1107800396161892372/a8403fe3-f778-49b8-9f7f-16753ed0225b.dat). Turns out, They had a Written Book without any NBT data, which the visualprospecting mixin wasn't expecting. Why the process produced an empty Written Book, I'm not sure about. Analyzing the item NBT, the Printed Pages out of the Scanner have the correct data from the prospector. Just the last step in the Assembler appears to strip the NBT somehow.
