### ISSUE TITLE
Crashing opening my Singleplayer World

### ISSUE THREAD

**Issue by ShinyPending** [GTNewHorizons/GT-New-Horizons-Modpack#13505]
### Your GTNH Discord Username

ShinyPending#0019

### Your Pack Version

2.3.2

### Your Server

SP

### Java Version

Java 8

### Type of Server

Single Player

### Your Actions

I was in the Twilight Forest when my game crashed, Crash report blamed it on BetterFPS, when trying to reenter nothing happened, after restarting PrismLauncher was no longer working. After restarting my computer and trying to open the world again a new crash error occurred. I then updated GTNH from 2.3.0 to 2.3.2 to see if that fixed the issue, and it did not.

### Crash Report

[crash-2023-05-14_21.41.15-server.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/11473749/crash-2023-05-14_21.41.15-server.txt)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by SquareOne376** [comment]
I had a similar crash and outcome in a 2.2.? instance in Prism. 

While riding a horse in OW, game crashed and CrashRep blamed it on FastCraft, unable to relaunch[1].  However, after I followed gtnh.miraheze.org "Migration" instructions to 2.3.4 (still within Prism), I was able to launch. But, opening any worlds imported from the previous instance gives the attached crash; blamed on "Unknown". 
[crash-2023-07-02_08.56.12-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/11927725/crash-2023-07-02_08.56.12-client.txt)
[1] Prism Log when 2.2.? instance launch attempt after initial "FastCraft" crash
"Prism Launcher version: 6.3
Launched instance in online mode
authserver.mojang.com resolves to:
    [99.86.178.18, 99.86.178.67, 99.86.178.52, 99.86.178.9]
session.minecraft.net resolves to:
    [13.107.213.59, 13.107.246.59, 2620:1ec:bdf::59, 2620:1ec:46::59]
textures.minecraft.net resolves to:
    [13.107.213.59, 13.107.246.59, 2620:1ec:46::59, 2620:1ec:bdf::59]
api.mojang.com resolves to:
    [13.107.213.59, 13.107.246.59, 2620:1ec:bdf::59, 2620:1ec:46::59]
Minecraft folder is:
C:/Users/.../AppData/Roaming/PrismLauncher/instances/gtnh_old/.minecraft
Java path is:
C:/Program Files/Java/jre1.8.0_333/bin/javaw.exe
Checking Java version...
Java is version 1.8.0_333, using 64 (amd64) architecture, from Oracle Corporation.
**Instance update failed because: Null jar is specified in the metadata, aborting.**"
