### ISSUE TITLE
Infernal Blast Furnace does not accurately do secondaries

### ISSUE THREAD

**Issue by Rakdarian** [GTNewHorizons/GT-New-Horizons-Modpack#13578]
### Your GTNH Discord Username

Rakdarian#7628

### Your Pack Version

2.1.2.0

### Your Server

Blackjack's /mlpol/ server

### Java Version

Java 20

### Type of Server

Don't know

### Your Expectation

Tried to use the Witching Gadgets Infernal Blast Furnace to make antimony out of tetrahedrite and I expected to get 9 nuggets each time

### The Reality

Across 64 crafts I got 11 nuggets

### Your Proposal

It should have given me 576 nuggets

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Rakdarian** [comment]
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/38307090/0dd627cf-e979-49e5-b8ba-d1bac438f034)

**Comment by wlhlm** [comment]
There seems to be a bit of a misunderstanding here about how the IBF works, both on part of the reporter and on part of the recipe maker (which is weird since it's bart who's also the author of WitchingGadgets...).

Here is the [code](https://github.com/GTNewHorizons/WitchingGadgets/blob/master/src/main/java/witchinggadgets/common/blocks/tiles/TileEntityBlastfurnace.java#L98-L105) that of the Infernal Blast Furnace that calculates the secondary output:
```java
if (recipe.getBonus() != null) {
    ItemStack bonus = Utilities.copyStackWithSize(recipe.getBonus(), 0);
    if (getBellows() == 0) {
        if (this.worldObj.rand.nextInt(4) == 0) bonus.stackSize += 1;
    } else for (int b = 0; b < getBellows(); b++)
        if (this.worldObj.rand.nextFloat() < 0.44F) bonus.stackSize += 1;
    outputItem(bonus);
}
```

A couple of notes on how it works:
1. the secondary output is chance-based; if there aren't any belows, a recipe has a 1 in 4 chance of yielding a secondary output
2. the number of secondary output items in the recipe is ignored; what determines it is the number of bellows (and if their dice rolls succeed). This is caused by the code `Utilities.copyStackWithSize(recipe.getBonus(), 0)`, no matter how high the secondary stack is in the recipe, the process starts with 0.

So, there are a couple of options here depending how we want things to be balanced, either:
- reduce the secondary item stack in the IBF recipe to one to avoid confusion somewhat

or

- rework the bonus logic to take the secondary stack size into consideration (also take note of handling exceeding max stack size)

**Comment by wlhlm** [comment]
BTW, here is the recipe code: https://github.com/GTNewHorizons/WitchingGadgets/blob/672cb050effe6adba57462bd385c47c48dd41b15/src/main/java/witchinggadgets/common/WGContent.java#L303-L313
