### ISSUE TITLE
new Recipes for minecraft leather armor

### ISSUE THREAD

**Issue by BLocky104** [GTNewHorizons/GT-New-Horizons-Modpack#13645]
### Your GTNH Discord Username

Blocky#0377

### Your Pack Version

latest nightly

### Your Proposal

leather armor is too cheap

### Your Goal

gtnh is not cheap, 
replace the leather with pams hardened leather

### Your Vision

gtnh is the hardest modpack and it should ne, thus i would suggest to rework most minecraft recipe

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Chaoschaot232** [comment]
I checked out the recipes for the leather armor and it's fine as it is.
I see no sense in making this or any other recipe related to it/around it harder.

From my side it would be better to buff some recipes instead of adding stupid new nerfed ones,
but not the leather amour ones.

Finally I wouldn't change any recipe for now until not other more important bugs are fixed at first place to be ready to get a new stable version release. Maybe just before it's release this could be looked at and discussed but currently it's the wrong time for this.

**Comment by Alastors** [comment]
Leather is stupid useless, just no
