### ISSUE TITLE
Replicator gives GT++ plutonium instead of GregTech plutonium

### ISSUE THREAD

**Issue by StarryArkt** [GTNewHorizons/GT-New-Horizons-Modpack#13748]
### Your Pack Version

2.3.2

### Your Server

SP

### Java Version

Java 19

### Type of Server

Single Player

### Your Expectation

I was looking through NEI for alternative ways to get plutonium for my radon loop, since I was getting unlucky with centrifuging Phobos stone dust. I saw there was a replicator recipe, so I tried going for that that.
![2023-06-18_13 57 17](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/51885347/4f2f4a07-2a97-4817-925c-af51660fc808)

### The Reality

The replicator recipe gave me GT++ plutonium (dustPlutonium239) instead of the expected GregTech plutonium (dustPlutonium), which can't be used interchangeably.
![2023-06-18_13 56 52](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/51885347/27f8139a-4b89-40c8-b6f5-cb3553643f5b)

### Your Proposal

Change the recipe to match what is shown in NEI (or vice versa of course).
There is a chemplant recipe to convert the GT++ dust into the normal one, but I don't have that yet.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
so I played around with this a bit and there seem to be a few layered problems here.

Of course, first of all the gt++ plutonium239 has no reason to exist in the first place. We have that material in GT.

However, even if I completely removed the GT++ plutonium, that still doesnt fix stuff. Then it just doesnt work at all.

The weird part is that this actually seems to be caused by bartworks. I am not entirely sure but it seems to rename the GT Plutonium to Plutonium239 which makes the look up for the dust fail.
