### ISSUE TITLE
Maintenance Hatch Revamp Idea (note these are completely new ideas unlike any other similar GitHub issue I’ve seen)

### ISSUE THREAD

**Issue by AltyMan** [GTNewHorizons/GT-New-Horizons-Modpack#13889]
### Your GTNH Discord Username

alty2x

### Your Pack Version

2.3.4

### Your Proposal

Ok so this idea is a long one, and I formed two options for how I plan to approach this rework. Note that I plan to develop this rework myself, but if any dev is interested and wants to reach out please do since I am very new to this (I might also require help from the devs working on multiblock madness depending on which option/solution I get the OK to approach). I made this GitHub request mostly to get feedback from the devs and any users going through GitHub issues by themselves.

Basically, as we know it, maintenance hatches suck. Most (including some devs I even saw) want it removed, but I personally like the idea behind them, I just feel like the gatekeeper of LuV for auto maintenance (on top of the stupidly costly requirements just to maintain one multiblock) and lack of other solutions until the auto tape in UV is the lead cause for everyone’s disapproval. One of the devs (forgot who) mentioned removing this mechanic as a whole, but knowing what’s happening with pollution I doubt it will be getting removed. So here’s my solution(s):

We begin with option 1, which is a basic but simple and logical solution, which is to design maintenance hatches by tier instead of just the default one. This is more of a solution for early game only, since by LuV the auto maintenance exists. Regardless, here’s my tiering idea for it:
    - LV: current maintenance hatch
    - MV: 20% less issues from LV
    - HV: 20% less issues from MV
    - EV: 20% less issues from HV
    - IV: 20% less issues from EV
    - LuV: Auto-maintenance hatch (perhaps buff)
    - ZPM: 20% less issues from LuV
    - UV: auto tape maintenance hatch, potentially for lag purposes make this as efficient as IV hatch
This solution would let the newly added IV maintenance hatch reduce the amount of maintenance issues by 80%, pushing the count of maintenance issues per multi to being 20% as often as what it is right now. However, as I understand from how GT multiblocks are designed, maintenance issues are tied to the controller block, not the maintenance hatch itself. This would mean either two things would be changed to accommodate this solution:
    - Multiblock controllers are re-designed to be dependent of the maintenance hatch for maintenance reports instead of being built in to the controller
    - Maintenance hatches can “simulate” the reduction of maintenance issues by automatically fixing a number of issues per another number of maintenance issues (ex. for IV, the hatch would fix 4 of the next 5 maintenance issues, perhaps in random or perhaps in order)

The second option I came up with is a new design for the auto maintenance hatch(es), which basically re-designs the auto maintenance hatch as it is right now, and allows for earlier tiers to use an auto maintenance solution. The idea I formed goes as followed:
    - Hatch would require only tape or another equivalent, and have an input slot similar to input busses for buffering the tape
    - Each tier adds more slots, and either:
        - Requires less tape to maintain
            - Ex. HV takes 1 tape per issue, EV is 1 tape per 2, etc.
        - Requires less maintaining (like option 1)
            - Ex. similar reduction per tier of issues
    - A circuit can be used/required for maintaining, but instead of consumption it could either be required as a catalyst or provide a durability factor and uses up the circuit after a bit of time. This could provide another customizable gatekeep to what the user requires within their tier to upgrade their hatch
This option would provide players with a way to automate their maintenance in earlier tiers. I personally prefer this option, since I can use this especially for my LSC and my XL GT so my power will never shut off and cause all the lines I have chunkloaded to be cut out. These blocks would be easy to implement, as it would just be a modification and duplication of the current auto maintenance hatch with new requirements and maintenance, and slight modification to each block tier for reduced maintenance issues or resources. This could also be potentially implemented with potential ME block alternative in the future, which could just be programmed to pull tape from a network when required.

Personally, I prefer option 2 over option 1 as I explained before. However, I prefer most to implement both features at the same time. Running both would provide players with the ability to automate maintenance for passive production lines and must-have auto maintenance multiblocks (like the cleanroom), while also having manual maintenance that is cheaper by nature for multis they don’t necessarily need running all the time. The balancing of adding both of them together would be as followed:
    - The auto maintenance hatch requires both a constant supply of tape (and potentially circuits), while the manual does not
    - Recipes for the auto maintenance hatch can be created to cost more
    - Most importantly, the manual hatch would reduce issues in either of the options more efficiently than the auto maintenance equivalent (ex. IV manual would reduce 80%, meanwhile auto would reduce 40% or something similar)

To sum up (TL;DR), a change to maintenance hatches can be made by creating tiered hatches, reducing maintenance issues, and adding/modifying the auto maintenance hatch to be more viable and better reflect a player’s tier level. And just to re-iterate, I plan on (at the very least attempting at) developing this myself, and the point of this GitHub issue is to receive feedback and approvals from other devs and players, as well as maybe even pull the interest of another dev who is more experienced and can better help me implement these features (specifically looking at devs working on multiblock madness and any dev who can help with redstone covers as well since these changes would open up new redstone cover features as well, but any dev who’s interested is free to reach out cuz I can use any help I can get lol).

Also again please comment any feedback you have and which option(s) you prefer so I don’t develop this and then find out when I schedule a pull request that this didn’t pass with other devs/players lmao

### Your Goal

The goal of the maintenance rework is to provide more viable and accessible solutions to players before UV tier with maintaining their multiblocks and processing lines by implementing either new manual maintenance hatches that are by tier and/or new auto maintenance hatches also by tier that reflect the player’s tier by cost of usage.
The goal is also to stop the hate of maintenance hatches and solve the problem without removing the mechanic as a whole.

### Your Vision

I came up with this from all my anger built up from constantly having to re-fix my entire nitrobenzene processing line because either my LSC or my turbines ran into a critical maintenance issue. My vision is to provide the current mechanics of maintenance issues some value and reduce the progression blockage that comes from annoyingly having to constantly fix important processing lines when they need to be maintained for the rest of the base to run and for progression to be made. My vision includes having a new base design that includes the usage of the auto maintenance hatches that as of now are gatekept to LuV and cost way too much for them to be worth it, or at the very least reducing the amount of times a player has to fly across their base repairing all their multiblocks that ran overnight.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Hikari1nVoid** [comment]
Moving down the auto maintenance hatch to lower tiers(EV?IV?) will probably solve your issue;but according to discord discussion channels someone is trying to introduce quantum computer uncertainty solver to normal multiblocks which imo was ridiculous...

**Comment by bombcar** [comment]
The issue I have with maintenance is it’s not predictable. I ran a quad EBF for what felt like half a year with no maintenance issues whatsoever, and had another multiblock that was in the shop more than a Saab. 

IMO all we really need is tiered “preventive maintenance” tools that give X hours of guaranteed running, after which the current setup applies. So if you want, you can run as we do, or you can apply whatever the consumable is regularly. 

Then balance the price of the pre maintenance tool so that it’s technically cheaper to just fix things as maintenance comes up (for those who live in the factory and run with alarms). 

I also would tune the LV maintenance hatch to be quite crappy because the EBF in LV should feel quite cobbled together and barely working. But once you upgrade it to MV power and an MV hatch it should become more reliable.

**Comment by Rika-TH** [comment]
> The issue I have with maintenance is it’s not predictable. I ran a quad EBF for what felt like half a year with no maintenance issues whatsoever, and had another multiblock that was in the shop more than a Saab.
> 
> IMO all we really need is tiered “preventive maintenance” tools that give X hours of guaranteed running, after which the current setup applies. So if you want, you can run as we do, or you can apply whatever the consumable is regularly.
> 
> Then balance the price of the pre maintenance tool so that it’s technically cheaper to just fix things as maintenance comes up (for those who live in the factory and run with alarms).
> 
> I also would tune the LV maintenance hatch to be quite crappy because the EBF in LV should feel quite cobbled together and barely working. But once you upgrade it to MV power and an MV hatch it should become more reliable.

Imo I'd like if also there was a grave period after repairs similar to Nomi, maybe only an hour or two (dependent heavily on whatever time these consumables give) but just *something* maybe manual repairs refresh this even if it isn't broken (preventative maintenance)

**Comment by ShyZShark** [comment]
Feel free to toss out this proposal, but most of these ideas could be blended together, while giving incentives that I don't think really exist. This might be a bit too complex to expect players to use, but I think late game GTNH is probably already there for most, so... Eh? I don't know anything about a "Grave Period" I've yet to play Nomi, I assume it's a cooldown after doing a repair?

Either way, let's get to it... I know it's long, I tried to short it. I'm rather talkative, heh.

Maintenance Hatches could be changed to display the 6 types of maintenance, (three on both sides of the interaction slot) with a percentage value displayed below each generic tool icon. (I'll get to that in a bit) If this can be done with nothing but a simple overlay, then it won't affect the GUI for texturepacks as well. When a multi has problems, inside the Maintenance Hatch, instead of showing a percentage it would show a simple red "X", indicating a fix is needed. This, supports the following system...

The percentage that is shown within the Maintenance Hatch would itself be a timer for a "Guaranteed Operation Period (GOP)" which would slowly tick down, exclusively during active machine operations, down to "0%". However, in this case "0%" would mean that a problem is capable of occurring, not immediately occurring. The percentage value acts as a quality indicator of that machine's attribute, once it hits 0, problems can then occur. This gives players a chance to do preventative maintenance if they choose to do it (which should be rewarded instead of letting machines run until they fail). This would allow the randomness of machine maintenance problems to not have such a huge range from literal minutes to months. Program it to have a higher chance to fail for each type sitting at "0%". Roll that chance every minute of operation, with a chance value at something around 1 in 1,440, producing an average of 1 problem in at least 24 hours for each expired maintenance type (if my math is correct), but lucky players could get more. The chances can be tweaked however necessary.

Here is where I think things would get interesting... However it would require a heavy balance check on tools and when they are acquired, to properly work.

The modpack already assigns a level value to the tool the player is using, and as far as I'm aware this is only useful for determining it's harvest level, but is chaotically broken for that use. For instance, a Manyullyn Wrench can be made in MV, but because it is fast and is LV 5, it is still a very valid wrench in mid IV. (I'd know, the one I made in MV just broke today in mid IV) There is practically zero incentive to improve your tools (I made a Shadow Metal HV Wrench a while ago, over half a year ago or longer, but that was only because I was curious, I only started using it today, because the other one was good enough and fast enough). 

Except...

Remember the percentage value earlier acting as a timer... the GOP? What if the tool's level would give a higher value towards that maintenance type on that machine? Higher quality tools, logically would produce higher quality work and would incentivize players to upgrade for convenience. (including getting people to get something better than a Soft (Wood) Mallet which I still use, it's so cheap) A list could be provided in the questbook explaining the maintenance quality (percentage value = GOP) for each tool level.

Electric tools could have an additional GOP value added to them. Although not all types support this...
LV = +10%, making electric tools early is more impressive, most don't seem do it, and it could be rewarded this way.
MV = +15%
HV = +20%
(Tweak values as needed, but it should make the effort worth it)
This would be useful, as it means to get the absolute best value, at any tier you would need an electric tool, which also make more logical sense and pushes people to make them sooner for that extra sweet GOP bonus! (Lets not talk about the Soft Mallets, Crowbars, and Hammers, unless the Jackhammer counts? Heh.) This would have to be workshopped, applied to only those types of tools, or excluded altogether. Perhaps their tool level could be disproportionally bumped to scale better with the rest of the tools.

Secondarily, a multiplier could be added to that GOP for the energy tier the multi is running at. This would allow a LV multi to have a 0.25x multiplier calculated into the GOP to make it feel like those machines are barely put together. Considering lots of multis people actually seem to use are MV or MV+, MV could be the 1x multiplier to the GOP. This system would also allow a penalty to overclocking, say a 0.75x reduction to the calculated GOP value of that machine (turning 12 hours into 9, or whatever values are finalized on), as running a machine harder (more amps in the same space / machine) would degrade it faster, in theory. This would incentivize players to actually get the next tier Energy Hatch faster. I could have made extra EV ones, but I've been running an OC HV EBF / Vacuum Freezer for over a year instead of making an extra EV Energy hatch, because there is nearly zero benefit excluding the... what, 4 EU/t savings I would get, and at EV power draw, I don't care about that. I can't justify the efforts needed for 4 EU/t, but significantly less maintenance? I'd be on that pretty quick.

Finally, the GOP value could be set at whatever base value allows for a decent balance. So if a 1% GOP value is equal to 30 minutes or 1 hour, then a level two tool (this would be something like Iron with the current system) could give... let's say, 8% GOP, giving 1 or 2 hours of a GOP respectively at LV (including the 0.25x multiplier for LV). But a level three tool (Steel) could give, let's say 12% GOP, giving 6 or 12 hours of GOP respectively at the MV multiplier of 1x. HV could be 1.2x or whatever works, etc... 

My OC HV EBF with a tier 5 tool (Shadow Metal HV Wrench) would give a 36 hour GOP if the math runs as follows...

(((Tool Level GOP Base Value+(Tool's Electric GOP Bonus)*Base GOP % Value Time)*Machine Energy Tier Multiplier)*Overclocking Reduction Penalty)

Or, presented in numbers... (Base GOP % Value Time is 1 Hour, Tool level is multiplied by 4%)

(((20+(20)1)1.2)0.75) = 36 Hours of GOP

But at LV with a standard LV EBF and a level 2 Iron Wrench, everything else being the same, you would have...

(((8+(0)1)0.25)1) = 2 Hours of GOP

A properly powered IV EBF with a level 8 HSS-E HV Wrench, again everything else the same... (IV Tier being 1.6 here)

(((32+(20)1)1.6)1) = 83.2 Hours of GOP.

Providing the tool materials can be properly balanced for their appropriate tiers, I think this could work and it would scale throughout the entire modpack, until players get the Auto Maintenance Hatches. It also...

- Makes maintenance more of a game than a chore, as you can reliably improve your experience. (Still a chore, but less... bluhh)
- Incentivizes players to not just use cheap Calcium Wrenches in IV and actually upgrade their tools (I've done this too, as Calcium is so cheap to process now, and I have thousands of it I'm not using with no intermediate steps required)
- Gives a better, more coherent meaning to the level of tool a player is using, rather than it just being for harvesting stuff, and gives a meaning to a level being assigned to Soft Mallets in the first place.
- Pushes players to actually advance their efforts / base and multis instead of piggybacking on stuff they've already crafted like Energy Hatches
- Gives the player more choice and control between knowing they can prevent themselves from losing that super rare material in their EBF or Vacuum Freezer the second they have a maintenance problem, MINUTES after fixing the exact same one... or they can risk it and be lazy. Lowering unpredictable player irritation, because they lost that circuit to maintenance because a pipe was loose when they just tightened it up 7 minutes ago.
- Reduces rage quitting. I'd bet some players quit this pack, because they just spent 10 hours getting those fancy new materials to run in their EBF only to lose it to "COMPLETELY STUPID, RANDOM GIMMICKS FOR POINTLESS TEDIUM!" or whatnot.
- Incentivizes people to power their Cleanroom with more than MV, of which I'm still using.
- Prevents the need to add separate tiered maintenance hatches for each voltage, which will likely just make most people mad.

Maintenance is a lovely addition to a pack like this, but it would be nice to make it into something that isn't just, exclusively a bland, boring chore, even if it technically would still be that... just more user-friendly and interesting.
