### ISSUE TITLE
LCR does not handle multiple recipes as expected

### ISSUE THREAD

**Issue by EzrealC** [GTNewHorizons/GT-New-Horizons-Modpack#14046]
### Your GTNH Discord Username

ezrealc

### Your Pack Version

2.3.5

### Your Server

SP

### Java Version

Java 8

### Type of Server

Single Player

### Your Expectation

Desulfurize all four crude oil distillation products (light fuel, heavy fuel, naphtha, refinery gas) using the very same LCR

### The Reality

**In recent updates, LCR does not void spilled product by default.** When the LCR is only processing one recipe, everything works fine. But when it processes two or more recipes, it may not process other still-progressive recipes because the output of one of the recipes fills up the output hatch (every hatch was locked by specific fluid).

In this example, I have five output hatch and locked for hydrogen sulfide, light fuel, heavy fuel, naphtha, refinery gas. When one of them was full, the LCR halts with "Not enough output space", other recipe will not be processed despite their output hatch is empty.

### Your Proposal

I wonder if this beheavior is by design or a bug

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by minecraft7771** [comment]
I'd call it a limitation. Atleast I wouldnt know how to change the current structure to re-check a different recipe next time, when the previous one failed due to no output space.

**Comment by desagas** [comment]
Paraphrasing Chochem: it is not the mods fault, it is the users fault. The user should have a separate machine for each recipe that is needed concurrently, and not doing so is not something they ever plan to fix, because it is, as he said, a user error.

I too recommended that they use code that already exists in multiblocks like the EBF, which will check all inputs for any valid recipes, and only fail once all have been checked and failed. Since the code already exists, I believe it would be relatively straight forward to adapt it to the newer multi blocks, however, he does not seem to think so, and will close all issues that suggest such a thing, without input from others.

**Comment by minecraft7771** [comment]
> Paraphrasing Chochem: it is not the mods fault, it is the users fault. The user should have a separate machine for each recipe that is needed concurrently, and not doing so is not something they ever plan to fix, because it is, as he said, a user error.
> 
> I too recommended that they use code that already exists in multiblocks like the EBF, which will check all inputs for any valid recipes, and only fail once all have been checked and failed. Since the code already exists, I believe it would be relatively straight forward to adapt it to the newer multi blocks, however, he does not seem to think so, and will close all issues that suggest such a thing, without input from others.

They use the same code and lcr keeps check recipes if e. g. One is incomplete but the next not. But it's the check if enough output space is available happens way later. Ebf would fail too in this case.

**Comment by desagas** [comment]
I’m wondering, if the code can check every input like that, why can’t it check all output hatches. Machines should have their output and input spaces caches in memory somewhere, would they not, to count a machine as valid. Would it not take then only a simple loop or iterative to check valid space for valid output space?

Instead, the code searches only for the first valid output bus or hatch, and stops completely if one is full, based ONLY on the first valid recipe check, and then, if that recipe can not run without voiding, the whole machine stops, rather than checking for another recipe. What I mean by using the same code would be here:

1. check if valid recipe exists, as in the current code.
1. do a void check, and IF IT WILL NOT VOID, 
 process recipe, as in the current code.
1. INJECT this into the code immediately above: Then, IF IT WILL VOID, continue recipe check loop. 

However, the code stops its iteration of valid recipe checks immediately if one recipe check would result in a void. I’m just saying, keep the recipe checks looping until complete when one fails.

**Comment by minecraft7771** [comment]
Feel free to PR a solution. Telling the actual recipe check to not do recipe X because it would void would require a rewrite of many systems, which atleast I will not touch.
