### ISSUE TITLE
Extruder Shape Chest for easier management of singleblocks in early game

### ISSUE THREAD

**Issue by AbdielKavash** [GTNewHorizons/GT-New-Horizons-Modpack#14048]
### Your GTNH Discord Username

abdiel_kavash

### Your Pack Version

2.3.4 with fixes from the wiki

### Your Proposal

Inspired by the Tinker's Construct Pattern Chest, which allows you to quickly change patterns for the Part Builder when placed adjacent to it:

![](https://i.imgur.com/dv6dBCM.png)

I suggest adding a similar chest that works as a storage for shapes for the Extruder. A very quick UI mockup:

![](https://i.imgur.com/4H2pFDp.png)

This would allow swapping between multiple shapes quickly without having to constantly navigate between the Extruder UI and a different chest UI.

Maybe a similar storage could be added for the Fluid Solidifier, Laser Engraver, and similar machines too.

### Your Goal

Microcrafting many different components in the same extruder is annoying due to having to swap shapes all the time. Having one extruder per shape is prohibitively expensive in the early game when you are most likely crafting parts by hand.

### Your Vision

QoL for microcrafting in the early game.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by desagas** [comment]
The same, then, would be useful for laser lenses. I am in a love hate relationship with this idea. I love good interactions, but I hate too much GUI. When too much gui overwhelms the screen, it loses attention. If this was collapsible, I would love it.

One of my favorite things about old school minecraft modded 1.7.10 1.12.2 etc, vs new school minecraft modded 1.12.2 until Create brought it back was the old immersive aspect of the world (tapping nodes in thaumcraft, fighting unique bosses in blood magic, atomic reconstructing in Actually Additions, and stuff like Create would add today), actually navigating the world to complete tasks, rather than the new gui stuff (simply sitting crafting in a single block or gui, where thaumcraft removed nodes and wands, where blood magic removed all bosses and world interaction).

**Comment by vovaksenov** [comment]
Remove stale
