### ISSUE TITLE
Allow shift clicking patterns into interface slots from interface terminal when possible

### ISSUE THREAD

**Issue by MaGeBZz** [GTNewHorizons/GT-New-Horizons-Modpack#14092]
### Your GTNH Discord Username

marvinhhmagebzz

### Your Pack Version

2.3.5

### Your Proposal

I thought it could be a nice idea if you search in the ME interface terminal for something and if there's only one kind of interfaces (for example bending machines) that you could shift click the recipes in it instead of drag and drop
It's a small thing but would be quite nice imo

### Your Goal

Making the interface section a bit nicer

### Your Vision

![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/133218866/a81d915f-13a3-43d3-b674-aa7086520ffb)

If you have something like this, that you could easily shift click recipes in the CoAL in it for example

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Godelboard** [comment]
Been a few years since this has been suggested; any chance of reconsideration?
AE in newer minecraft versions support this feature; shift clicking a pattern looks at where the GUI is currently scrolled to and places the pattern into the first visible open space.

It would be really nice to reduce mouse movement and amount of clicking needed for placing items into the interface terminal, especially with the many thousands of patterns needed to be mady.
