### ISSUE TITLE
Wireless from Lazy AE2

### ISSUE THREAD

**Issue by Oueio** [GTNewHorizons/GT-New-Horizons-Modpack#14107]
### Your GTNH Discord Username

oueio

### Your Pack Version

2.3.5

### Your Proposal

Is it possible to somehow make from one-block wireless connector p2p like version for preventing unnecessary connections?

### Your Goal

Just QoL when using square of me controllers with dense cables and wireless connectors

### Your Vision

Improve unnecessary connections if they haven’t already been fixed

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by greesyB** [comment]
Firenoo recently made wireless connectors colorable, which allows for preventing unwanted connections by coloring cables https://github.com/GTNewHorizons/ae2stuff/pull/11.

Wanting a wireless part instead of block is potentially still a valid request, but I think such a part would be unintuitive to use as it would behave very differently from other parts like p2p. Other parts take one channel from the cable they are connected to and interact in some way with the block they are facing.

A wireless part would presumably need to pass all channels from the cable it is connected to without consuming one itself, and would not interact at all with the block it is facing, but instead make those channels available to its wireless connection. Also since parts are not allowed on dense cables a wireless part would likely be capped at transferring 8 channels.

**Comment by AbdielKavash** [comment]
A different solution would be to let the wireless connector (and other AE full blocks while we're at it?) support GT covers. That way you could separate networks by using a wooden plank on one side of a block or something like that.

**Comment by Oueio** [comment]
> Firenoo recently made wireless connectors colorable, which allows for preventing unwanted connections by coloring cables [GTNewHorizons/ae2stuff#11](https://github.com/GTNewHorizons/ae2stuff/pull/11).
> 
> Wanting a wireless part instead of block is potentially still a valid request, but I think such a part would be unintuitive to use as it would behave very differently from other parts like p2p. Other parts take one channel from the cable they are connected to and interact in some way with the block they are facing.
> 
> A wireless part would presumably need to pass all channels from the cable it is connected to without consuming one itself, and would not interact at all with the block it is facing, but instead make those channels available to its wireless connection. Also since parts are not allowed on dense cables a wireless part would likely be capped at transferring 8 channels.

Maybe like what u wrote. p2p like part that will be face connected with cable and on other side just do nothing.
P.S. like me p2p, but without cable to connect

**Comment by Oueio** [comment]
Sry, missclick

**Comment by firenoo** [comment]
Already suggested here https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/13572

Personally, not a fan of wireless. Adding a multipart version of wireless is a no from me, maybe someone else can implement it
