### ISSUE TITLE
Higher tech rocket

### ISSUE THREAD

**Issue by drxsx** [GTNewHorizons/GT-New-Horizons-Modpack#14215]
### Your Pack Version

2.3.6

### Your Proposal

replace the current rocket engine and fuel, from using chemical to fission or fusion, for example

1.NSWR, using UBr4 solution
https://en.wikipedia.org/wiki/Nuclear_salt-water_rocket

2.Project Orion, using mini nukes
https://en.wikipedia.org/wiki/Project_Orion_(nuclear_propulsion)#Basic_principles

3.Project Daedalus, using deuterium and helium3
https://en.wikipedia.org/wiki/Project_Daedalus

### Your Goal

the rockets now can fly to other solar systems using only some chemical fuels that exist in real life, a bit weird isnt it

### Your Vision

Imagine you are riding a nuclear rocket, spewing out a steady stream of radioactive plasma, sending you to the outer solar system to mine precious minerals there, it will be super cool

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by cainiaojun** [comment]
No.

The chemical plant and rocket fuel line are tedious enough. If there will be T10+ rockets, your idea would be good, but just don't change the existed ones.

And the mothership uses naquadah fuel mk2, which maybe meet your needs.

**Comment by LooseEthics** [comment]
Rather than replacing rocket fuels entirely, I'd prefer for the Orion drive to be an alternative progression path.
Starting from T3 either make the schematic craftable into a pusher plate design, or have the schematic unlock both recipes in the workbench.
Regarding liftoff - you are literally setting off a nuke, meaning there's a blast and fallout to consider. Letting the rocket do appropriate block damage is a bad idea for obvious reasons. So I would propose that instead a multiblock structure that needs to be upgraded along with the rocket would be used instead of the basic platform. It could also double as a fuel loader. Instead of the rocket packing it up every time you'd need to build it on every planet you want to take off from, which could be compensated with simpler fuel production.
