### ISSUE TITLE
Fusion Reactor undesirable behavior/void protection

### ISSUE THREAD

**Issue by wagon153** [GTNewHorizons/GT-New-Horizons-Modpack#14315]
### Your GTNH Discord Username

hildibrandm

### Your Pack Version

2.3.7

### Your Server

Private server

### Java Version

Java 17

### Type of Server

Single Player

### Your Expectation

When a fusion reactor has room in an output hatch to do another recipe, to also check for energy buffer before beginning the recipe. 

### The Reality

When a fusion reactor is stopped due to having a full output hatch, it will turn back on once it detects there is room in the output hatch for another recipe. Which is fine. However, it does not check if there is enough energy in its buffer before running the recipe, resulting in it power failing and not turning on again until manually hit with a mallet. While this can be worked around using redstone, it's still very irritating(and redstone is not optimal for server performance anyway). 

### Your Proposal

Add a check for energy requirement before starting craft. This would get two birds with one stone. That being the original issue with the buffer and its behavior where it will turn on even if there is only room for one recipe, killing efficiency, since fusion reactor buffers take time to fill, and some recipes take a significant amount of EU for initial startup. 

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [x] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
shouldnt you deal with that as the player? it seems consistent with how other machines behave.

**Comment by chochem** [comment]
the void protection that was added to those machines is not about power failure but about stopping when outputs are full.

**Comment by combusterf** [comment]
Fusion did void previously when full. Now it does not - it will stop and effectively commits suicide doing so.

**Comment by chochem** [comment]
I see, thank you. So it got void protection but it looks like there is no toggle. All the other machines got a toggle.

**Comment by boubou19** [comment]
i guess what happens here is that if you keep hitting the full capacity of the fusion reactor in a short period, it kills the internal buffer of the fusion, which then needs to recharge, deleting a good amount of power.

(i hope it at least wait for enough energy before restarting, otherwise you have a fusion flickering)

But imo it's a false problem: if you want the fusion to trash the excess of output, you might as well extract everything from your fusion and store it in tanks with voiding mode. 

Given we are unifying behaviors of every multi to have common code so we can extract it, making the code way more cleaner and easier to deal with, not much we can do, unless there is an actual bug. But the fact it stops when full is intended.

**Comment by combusterf** [comment]
It doesn't wait for enough startup energy either. Void protection actually causes more voiding than without.

**Comment by boubou19** [comment]
i see then 2 issues:
- voiding mode not toggleable
- voiding mode restarting without checking internal buffer
