### ISSUE TITLE
Forming Press coinage mold tries too hard

### ISSUE THREAD

**Issue by hacatu** [GTNewHorizons/GT-New-Horizons-Modpack#14372]
### Your GTNH Discord Username

hacatu

### Your Pack Version

2.3.7

### Your Server

SP

### Java Version

Java 17

### Type of Server

None

### Your Expectation

The forming press should make printed silicon etc

### The Reality

If a material press has both the AE mold and a coinage mold, the printed silicon will have the nbt tag `{credit_security_id: xyz as long}` appended, and AE won't recognize it unless you manually update your crafts to use the tagged version or enable substitutions

### Your Proposal

Honestly?  Just never add that nbt tag even to coins.  Does anyone care about every forming press producing non-stacking coins?

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by hacatu** [comment]
Although actually, gold plates seem to get turned into blank coins instead of printed logic circuits when put in an overloaded bus so I guess the recipe order changed or something :(

This makes the incorrect applying of the tag matter a lot less because you can't share coinage + logic

Also would make sense to add this tag to the name remover if it doesn't handle it already

**Comment by WorldSpam** [comment]
Same on 2.7.4. I had coinage mold to simply preserve space in interface as they were still pricy for me, but the main purpose of that specific input bus was to create circuits for AE storage processors. In my situation, the mold seems to be adding "credit_security_id" to my Fluid Circuit Tier 1, so the system freaks out when instead of normal <dreamcraft:item.DiamondFluidCoreChip>it received <dreamcraft:item.DiamondFluidCoreChip>.withTag({credit_security_id: 260708502586200 as long}).

I literally spent the whole day troubleshooting this bs with taking apart everything involved, and the solution was simply to get rid of the coinage mold. Idk what magic this mold does, but it should check to what item it adds this tag. (And if this tag is even necessary)
