### ISSUE TITLE
Plasma Chain Changes RFC

### ISSUE THREAD

**Issue by Alaking** [GTNewHorizons/GT-New-Horizons-Modpack#14427]
### Your GTNH Discord Username

alaking

### Your Pack Version

2.3.5 with updated betterP2P

### Your Proposal

I have some changes to certain recipes in the Plasma power chain that I would like to implement.

1. reduce bedrockium needed for Force Plasma
72L per craft instead of 144L
2. reduce titansteel needed for Runite Plasma
4L per craft instead of 8L
3. reduce tartarite needed for celestial tungsten plasma
1/16th consumption (288 advanced nitinol plasma + 1L tartarite = 2000 celestial tungsten plasma in 32 ticks)

### Your Goal

- reduce overall power-cost for the mk3 plasma chain from about 16% of the production to about 6%

- cap power consumption of supplementary processes for fusion power chains at the maximum power consumption of the corresponding reactor tier (mk1 - LuV, mk2 - ZPM, mk3 - UV) 

### Your Vision

- fusion power shouldnt be primarily bottlenecked by non-fusion components that arent pure material costs.

- the fusion chain is currently very underused, with lots of players going for naq-fuel or EHE spam instead, this change alleviates 1 of the 2 causes for this, the other cause is the lack of higher tiers imo.

- I have ideas to resolve that aswell, but i consider this change higher priority currently.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by chochem** [comment]
> cap power consumption of supplementary processes for fusion power chains at the maximum power consumption of the corresponding reactor tier

Hmm, that is a strange goal considering that fusion is never very high on power consumption.

Overall 16% going back into the line sounds fine to me, not really like an issue. Pretty sure I have had more with benzene.

My main takeaway is that EHE is still pretty strong as that was largely (though not fully) excluded from the plasma nerfs.

**Comment by Alaking** [comment]
I realize that the wording there is kinda bad, my intended meaning is that any specific additional step doesnt take more power than the final step its leading up to. my wording makes it sound, to me atleast, like I was talking about the entire supplementary processes together.

doing a bit of the crude math puts regular benzene at around 16% pre efficiency, nitrobenzene lcr route at around 16% pre eff and nitrobenzene chemplant route at 5% pre eff. 
I'd overall argue that it doesnt change my point, benzene power is early game, fusion power is late game.
I probably wont bother getting exact numbers for naquadah fuel, but just counting the fusion step for mk1 and the mk1 cost + the lcr step for mk2 puts those at less than 0.1% and around 2% respectively, before the 275% efficiency from cryotheum.

EHE spam could possibly be discouraged by making the "intended" power plasmata have notably higher throughput and at the same time nerfing the throughput rate of the current big offenders, helium and tin plasma, but I am aware that theres other issues involved in the EHE issue.

overall my goal with this is to make the plasma chain into actually something useful and to that end these seem like the easiest, and least possibly problematic, changes.
a different approach to the tartarite part of this suggestion would be replacing it with something gated to UV tier, a quick glance leads me to suggest 'black titanium', which only has an ABS recipe, or 'enriched naquadria', which isnt actually locked to UV but has no actual uses and requires naquadria and molten fluxed electrum which might make it sufficiently expensive.

I apologize for the long response.

**Comment by fluffle** [comment]
I'm currently using the plasma chains via the EHE to generate 200M EU/t, but mostly I am using naq fuels. The things that bother me about these chains are:

- Creating millions of ingots of celestial tungsten as a byproduct seems kinda OP
- Getting enough tartarite is a hassle, I've been resorting to dumping ender quarries directly over tartarite veins but that's quite manual. So +1 to @Alaking's comments about this, but specifically for tartarite -- bedrockium bees are great and titansteel is not a problem post space elevator.

I'm going to re-air the suggestions I made on https://github.com/GTNewHorizons/GoodGenerator/pull/167 w.r.t. the EHE:

> A static 3x energy output multiplier for building a couple of additional, relatively cheap multis is too strong a buff to ignore. This has been addressed in other parts of the pack with multi tiering allowing variable multipliers and maybe this would work for the EHE too.
>
> The 3x multiplier happens in the extreme HX, and I think that is the multi most amenable to tiering. It uses pipe blocks of which multiple tiers already exist, so we could set things up such that better pipe materials produce better "heat transfer" (SC steam output multipliers) for plasmas. Furthermore we could require that some higher-tier plasmas needed the higher tier pipes or they would "melt" (explode) the HX -- thus forcing people to commit expensive resources for greater power output. It could even be asserted that the default tungstensteel pipes are completely unsuitable for use with plasmas.

How about, as a rough starting point:

- Standard tungstensteel pipes and pressure resistant walls only allow creation of SH steam. "Tier 1" EHE will not consume plasmas when using these blocks.
- 4 tiers of plasma-compatible pipe/wall combinations giving increasing multipliers and flow-rates.
    - Tier 1: Infinity pipes + titansteel walls for 1x plasma -> SC steam and 500mb/s max flow rate
    - Tier 2: Hypogen pipes + quantum walls for 2x plasma -> SC steam and 1000mb/s max flow rate
    - Tier 3: Transcendent metal pipes + ?? walls for 4x plasma -> SC steam and 2000mb/s max flow rate
    - Tier 4: Spacetime pipes and ?? walls for 8x plasma -> SC steam and 4000mb/s max flow rate

(Note I have not yet done any maths w.r.t. how manageable these are in terms of SC steam flow into turbines, the numbers above are for illustration only and not supposed to be considered as "balanced")

The idea is to make this multi scale with power tiers so less spam is necessary. If there's also appetite for making higher power tiers consume more resources to get the additional multipliers, perhaps more plasma mixer recipes could be added, that produce mixes intended for power generation use that can only be used in the high-tier EHEs.

**Comment by fluffle** [comment]
I made a sheet to explore this a bit more. Turns out 8x multiplier is a bit OP, mild shock, especially when the high tier rotor multipliers are also factored in.

https://docs.google.com/spreadsheets/d/14OF7kB3dzOwgBjZwB-6zo8TX4AqKKqyHgc09C4EHQXM/edit?pli=1#gid=0

I started the metals and multipliers a tier earlier, so 500mb/s max flow and 1x multiplier is aimed at UV materials. 500mb/s might still be too restrictive -- even with Celestial Tungsten plasma it's hard to meet the steam requirements of any half-decent rotor material in the XL SC Turbine when considering huge rotors, though Awakened Draconium looks pretty nice and 1.6 UIV amps (~53.7M EU/t) would produce more than a 64A UV output hatch could manage. Probably people would opt for smaller rotors?

UHV has some plausible options: one EHE with 1000mB/s Runite plasma can power one XL SC with Cosmic Neutronium rotors (~150M EU/t), or two with 1000mB/s Celestial Tungsten (~300M EU/t).

UEV you're probably looking at one XL SC with Metastable Oganesson rotors (~1B EU/t) or two with Transcendent Metal (1.28B EU/t) per EHE consuming 2000mB/s Celestial Tungsten.

In UIV obvs this tops out with a single EHE consuming 4000mB/s of Celestial Tungsten being able to power almost three XL SC Turbines with Shirabon rotors, each kicking out ~1.58B EU/t.

Perhaps this is too powerful still but it at least costs a bit more ;-)

I can probably manage the changes to recipe maps and the EHE tile entity code  if this proposal sounds interesting enough to warrant implementation. I have literally no idea how to create blocks / textures and I am sure you don't want programmer art anyway. We'd need 6 new blocks -- the four metal wall variants, and the higher tier pipes (quantum and shirabon) -- for this proposal. I will try to find some time to appear on Discord if this is interesting to the dev team.

@S4mpsa since I have enjoyed his naq fuel spreadsheets on stream recently and he was complaining again about the EHEs being OP.

**Comment by S4mpsa** [comment]
Making the EHE tiered is definitely one way to tackle the issue, and it also adds some cost to it with the suggested materials. It's questionable if plasma power will ever be viable post-DTPF though, as with the suggested Shirabon and Spacetime, the last tier of EHE would be past the Dyson Swarm, which plasma will never be able to compete against. I would maybe tier down the last two tiers slightly, replacing Spacetime with Hypogen and Hypogen with Transcendent Metal instead, but otherwise the numbers look good.

If you want to implement this and need the new textures, I can whip something up fairly quick, just let me know in Discord.

**Comment by fluffle** [comment]
Transcendent Metal still needs the DTPF, no? So that sort of rewards someone willing to grind out the Hypogen ingots in a MK4 fusion. Could happen, I guess.

I have an alternative proposal. The 4x multiplier at the top end still seems large, and it also bothers me a bit that the lowest tier has no multiplier at all, and thus no incentive for anyone to build the additional multis over an XL plasma turbine. So, given your comments about the Dyson, I took the down-tiering idea a bit further and went from ZPM to UEV, dropping the efficiency increase per tier to 0.5 but starting at 1.5, so the EHE maxes out at the same 3x efficiency multiplier it currently enjoys. This allows the walls to follow the standard Neutronium -> Cosmic Neutronium -> Infinity -> Hypogen path, and means we need one less block/texture. And technically now all of this can be done pre-DTPF, if people are feeling masochistic.

**Comment by Steelux8** [comment]
I am against having EHEs work with plasma, out of principle. The addition of this extra step triples EU/t from the reactors, from what I've heard from several sources, which was not clear upon its introduction and makes very little sense based on the cost of the EHE. I've never looked deep into the EHE plasma setup, because I want to deprecate it when fusion rework comes, so I have very little to say in regards to EHE changes.

**Comment by fluffle** [comment]
But if tripling energy output was locked behind a relatively significant amount of Hypogen, (infinity = 2.5x, cosmic neutronium = 2x, neutronium = 1.5x) would that go some way towards restoring balance? Or is there no price high enough to make such multipliers valid, in your eyes?

Sure, you dislike things as they are, but I'd appreciate some actual engagement with my idea :-)

**Comment by Steelux8** [comment]
I know very little about endgame balance, so I'd rather not comment on whether or not the bonuses are fitting for the costs. Additionally, I've never liked working with the EHE or the XL SH Steam Turbine, so I have little to contribute here.

**Comment by Alaking** [comment]
I had a neat idea after fluffles first reply to this issue of a single mute multi that replaces both the plasma turbines and the EHE + supercritical turbines, doing the "function" of either way depending on casings and casing tiers.
so for example you'd add/upgrade "steam compression" blocks and receive a power output increase in exchange for higher turbine consumption and (higher) consumption of water. also had the idea of locking higher tier plasmata to only the  'sc steam' mode so that you'd need to upgrade more parts of the multi later into the game.

I tried looking at mute development to make a working prototype but didnt get far, so I only have some notes on upgrade ideas.

also if its alright I'll close this issue once 2.4.1 gets released since that changes tartarite which was my main reason.

**Comment by fluffle** [comment]
If the answer is "no, don't work on this because we're going to delete it from the pack and push people towards XL plasmas or Naq Fuel for UV->UEV powergen" then that's fine too :-)

**Comment by Steelux8** [comment]
The only thing I want to do with fusion power is replace all the current multis, EHE and turbines included, with mute multis and rework all the mechanics involved. Until then, changes to the current multis are fine by me, as long as they aren't outrageous.

**Comment by fluffle** [comment]
Do you expect a MuTE-replacement of all of the current turbines + heat exchangers (and possibly the cooling tower) to be ready for whenever 2.5.x is slated? If so then doing making these changes is largely pointless, imo.

**Comment by LazyFleshWasTaken** [comment]
> I started the metals and multipliers a tier earlier, so 500mb/s max flow and 1x multiplier is aimed at UV materials. 500mb/s might still be too restrictive -- even with Celestial Tungsten plasma it's hard to meet the steam requirements of any half-decent rotor material in the XL SC Turbine when considering huge rotors, though Awakened Draconium looks pretty nice and 1.6 UIV amps (~53.7M EU/t) would produce more than a 64A UV output hatch could manage. Probably people would opt for smaller rotors?

> UHV has some plausible options: one EHE with 1000mB/s Runite plasma can power one XL SC with Cosmic Neutronium rotors (~150M EU/t), or two with 1000mB/s Celestial Tungsten (~300M EU/t).

> UEV you're probably looking at one XL SC with Metastable Oganesson rotors (~1B EU/t) or two with Transcendent Metal (1.28B EU/t) per EHE consuming 2000mB/s Celestial Tungsten.

I'd just like to mention that turbine durability damage scales with power output, so each of these examples are unviable due to the rotors lasting mere hours.
