### ISSUE TITLE
List of things for which PAs are actually better than any other alternative

### ISSUE THREAD

**Issue by boubou19** [GTNewHorizons/GT-New-Horizons-Modpack#14437]
This ticket is a placeholder to list every single aspect of the PA that makes them meta for specific tasks.
Please edit this post to list validated cases.

- Cleanroom replacement in IV and LuV for laser engraving (until LPF) (covered by https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/14444 if laser engraving multi is gated properly), assembling (until PrAss) (covered by https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/14449), and circuit assembling (until CAL)
- Electromagnetic separator for Tengam (and potentially for Monaline) (covered by https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/14445)
- Brewing Machine for various things (Bacteria being one) (covered by https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/14448)
- Circuit Assembler for AE2 storage components (Cannot be done in anything but SB Circuit Assembler) (covered by https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/14440)
- Canner & Fluid Canner for making coolant cells and some other things (covered by https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/14446)
- Unpackager (This is really just for like 1 recipe so whatever) (covered by https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/14447)

**Comment by S4mpsa** [comment]
- Brewing Machine for various things (Bacteria being one)
- Circuit Assembler for AE2 storage components (Cannot be done in anything but SB Circuit Assembler)
- Canner & Fluid Canner for making coolant cells and some other things
- Unpackager (This is really just for like 1 recipe so whatever)

**Comment by combusterf** [comment]
- Anything causing pollution

**Comment by nick-l-o3de** [comment]
I was going to use it to stack fluid extractors from coal to make benzene, since it doesn't make sense to overclock fuel production.

**Comment by Jocroy** [comment]
Assembler at EV-LuV (until the Precise Assembler becomes available through mona/bastline). Not really endgame, but the PA really helped there especially for circuit components.

**Comment by boubou19** [comment]
> Assembler at EV-LuV (until the Precise Assembler becomes available through mona/bastline). Not really endgame, but the PA really helped there especially for circuit components.

at what tier is gated the GT++ assembler? zpm?

**Comment by chochem** [comment]
yes.

**Comment by boubou19** [comment]
then we may want to downtier the GT++ assembler so it has a purpose, and we avoid both multis to coexist around the same time of the progression no?

What would be the implications of downtiering the GT++ assembler?

**Comment by querns** [comment]
The GT++ assembler can do recipes one tier over its energy hatches. This is built-in and required in ZPM+ tiering, but before then it breaks progression.

**Comment by chochem** [comment]
yep pretty much what querns says.
Precise Assembler is already in early LuV though.

**Comment by boubou19** [comment]
it's not clear which one you want to use then. I guess you go GT++ to do recipes of tier+1, and PrAss for recipe of current tier?

**Comment by querns** [comment]
> it's not clear which one you want to use then. I guess you go GT++ to do recipes of tier+1, and PrAss for recipe of current tier?

This is correct. The PrAss has superior parallel capacity, but cannot do recipes over its energy hatch tier. The GT++ assembler is only for doing recipes one over its energy hatch tier.

One way to reconcile this would be to give the LSAA the Maceration Stack treatment -- downtier it (and its casings), then put in a chip to upgrade it to a variant that can increase its tier by one.

**Comment by chochem** [comment]
I tend to use both for different things yea. precise assembler has more parallels and much space for hatches, ++ assembler has the extra tier.

If you want to bring one of them to IV right now that should probably be the precise assembler. would just need one recipe change: the mar-ce-m200 smelting (or where its being used).

**Comment by boubou19** [comment]
mhm, i'd like this idea yeah, even tho i'm wondering if getting PrAss in IV isn't too much of a buff.

**Comment by querns** [comment]
> If you want to bring one of them to IV right now that should probably be the precise assembler. would just need one recipe change: the mar-ce-m200 smelting (or where its being used).

Doing this unheeded would also de-facto move naqline to IV, I believe. You'd have to adjust the PrAss to only have precise mode available at LuV+. Probably by means of shifting all the PrAss tier casings up by one, and adding a new level 1 casing that flags the PrAss as unable to do precise mode.

**Comment by boubou19** [comment]
this looks reasonable imo

**Comment by chochem** [comment]
yea the mar-ce-m200 is only used in the precise casings, so some tier 0 casing could work nicely. without precise mode and probably just 16 parallels. the controller is already craftable in IV

**Comment by boubou19** [comment]
sounds like a plan. @chochem can you make a ticket summing this up nicely? i'm not much used to this part of the game and i don't want to talk non sense or dumbly copy/paste what has been said here.

**Comment by C0bra5** [comment]
Is the electromagnetic separator getting a multi? Because the Monazite Line uses one in the main path and I don't fancy having a wall of single blocks to keep up in a power-efficient manner. My line already sucks around 100K eu/t with most machines running on EV or IV hatches. I need 12 or 16 EV separators in a PA to keep up with an EV digester.

Also while we are at it can we consider why the multi dehydrator needs ZPM? I know it doubles as a vacuum furnace, but it would be nice not to have a random forced single block in the bast line. Lowering the tier at which you can craft the multi, making the stats somewhat worse and adding an upgrade chip to enable the vacuum furnace and restore the stats to the current stats would be my suggestion.

The recipe for solar-grade silicon made from HCL is way more complex in an LCR. It's a 7-step process that does give you slightly more sg-silicon per silicon (1:1.066...). I've heard of a couple using PAs for that recipe.

**Comment by chochem** [comment]
electromagnetic separator is on the list yea

**Comment by boubou19** [comment]
about cleanroom replacement for Circuit Assembler in IV and LuV, what would be the implications of downtiering the CAL? because given the multi already exists i proposed this: https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/14440

**Comment by S4mpsa** [comment]
Downtiering the CAL wouldn't change much as you need Praesolite or whatever for the imprints which is gated in LuV I believe (Don't quote me on that), so it would just make setting up dedicated CALs later on slightly cheaper.

**Comment by miaowwwwww** [comment]
downtier CAL? u can make hv soc sooner.

**Comment by chochem** [comment]
hmm, downtiering CAL sounds more tricky/not that desirable. it currently needs luv parts, the AL, and a bunch of rare ingredients which in part can be sourced on T4 and T5 planets. its like a big piece of LuV content.

hmm, not sure though what the alternative would be.
If circuit assembler is the only thing that needs a cleanroom in IV I could live with that, but I am sure some people would hate it.

**Comment by C0bra5** [comment]
> about cleanroom replacement for Circuit Assembler in IV and LuV, what would be the implications of downtiering the CAL? because given the multi already exists i proposed this: #14440

Would that mode care about item ordering? Like the CAL, like he regular AL cares about it. If it doesn't you'd end up with a 2 length CAL I presume since that's the only logical way to deal with that. Personally, I would prefer add a new multi.

**Comment by boubou19** [comment]
no, litterally you throw all your items in a bus and call it a day

**Comment by AbdielKavash** [comment]
Aside from those already mentioned:

* Use TecTech multi-amp hatches to get a large number of parallels for recipes on your tier. (*Some multis can be fit with 8-16 normal hatches for a similar purpose, some not so much due to casings required.*)
* Parallelization of different tasks among machines. Build 4 PAs, have them all share one input bus, put one machine in each. Insert 4 different recipes (without conflicts) into the input. Each machine will take one of the recipes and run them in parallel. Normally a single multiblock can't parallel different recipes together. (*This can also be solved with some advanced AE or by buffering large crafts.*)
* Use the stocking input bus with a singleblock machine. (*Solved if every singleblock gets a multiblock equivalent.*)
* Use multiple buffered (passived) fluid inputs with a singleblock machine. (*Ditto.*)
* A much more compact version of the chemical bath multiblock. The washing plant has enormous bonuses that make it worth for generic ore processing and such, but if you ever need just one slowly-running chem bath in a processing line somewhere, it is much easier to find space for a 3x3 cube than an olympic swimming pool. (*Suggestion: Add a smaller multi that can only do chem bath, not the ore processing recipes.*)
* Automatic packaging of small dusts before the Amazon Warehouse is available. Use a storage bus with an oredict card into a big bus or a subnet, into a PA with even one packager. (*Why is the Amazon tiered so incredibly high again, for a glorified crafting table?*)
* That one solar grade silicon recipe that doesn't run in an LCR: the most efficient way to run it right now is to stuff 64 LV chem reactors in a PA. (*Suggestion: add the recipe to the LCR with a circuit to distinguish it from the 4 fluids one.*)
* Achieve high levels of parallelism early on in the game. You can parallel some low EU/t recipes to the full 64x in a PA long before a GT++ multi will achieve that number of parallels with an equivalent input voltage. (*No immediate solution comes to mind, unless you want to buff existing multiblocks' parallels throughout all tiers.*)
* Precisely control the number of parallels vs. overclocking for a setup. This might be only a technicality, I don't know of any practical scenario that *needs* this level of control, but it is something that can currently not be done without a PA (or an equivalent system distributing inputs to an array of singleblocks).
* Endgame setups - this is a part of the game that I have no experience with, so I am just going off what I heard; where 64x parallels in a PA running on massive voltage can be more efficient than GT++ multis - please consult endgame players actually using this, I only know that this is something that exists.

Most of the above are relatively minor, they are not some huge holes that will be left unfilled if the blue box is gone. However there is one more gripe that I have with the potential removal, and that is:
* Give the player several options for scaling up mid-to-late game machines.

Right now, whenever a single block machine is insufficient, the player has a meaningful choice between using a multiblock or using a PA. (For evidence that the choice is in fact meaningful, consider the number of people who *are using PAs*, even for machines where a multiblock exists. Dedicated multis are not strictly better than PAs for every situation.) If PAs are gone, even if every machine gets a dedicated multiblock, this choice will be gone.

To me personally, removing player agency matters a lot more when considering the long-term vision of the pack, rather than some particulars about recipe efficiency. Even if everything is going to get moved to dedicated multis, please at least leave the player some choice of *which* dedicated multi to use.

**Comment by C0bra5** [comment]
Quick note: Since you need an extractor to process some crops (sugar beet is a good example), PA is very nice if you don't want to make an LPF specifically to do the extraction; it's a pretty steep cost for a simple extractor multi. It's the same with a few more machines that the LPF counts as,

**Comment by JodieRuth** [comment]
Using UMV PA is practically a no-brainer. Towards the end of the game, some GT++ machines are already significantly less efficient, and the latency from stacking them can be very high. That's when PA is a good solution: substantially higher power consumption, but lower latency. If some giant processing machines are acquired, then UMV PA will be removed from the available options.

**Comment by truenachtara** [comment]
I've been using them as a cleanroom replacement for ordinary circuit assemblers so I don't have to maintain a multiblock 24/7

**Comment by boubou19** [comment]
> I've been using them as a cleanroom replacement for ordinary circuit assemblers so I don't have to maintain a multiblock 24/7

the upkeep of a cleanroom isn't that much of an issue, power wise the hatch you give it just impacts on the warmup time before it reaches 100% efficiency, et for the maintenance hatch, it's just like any other multiblock that is busy 24/7, but you can use robots to apply tape if luck isn't with you so it's not really an issue. And if really you don't want to pay the upkeeps 24/7, just power the cleanroom just before you start to craft, so you dodge most of the issue, but then you have to face the warmup time.

I'd rather accept the complains about the size of the multi required or the lack of room in it than upkeep costs, it's just some lazyness.

**Comment by truenachtara** [comment]
> > I've been using them as a cleanroom replacement for ordinary circuit assemblers so I don't have to maintain a multiblock 24/7
> 
> the upkeep of a cleanroom isn't that much of an issue, power wise the hatch you give it just impacts on the warmup time before it reaches 100% efficiency, and for the maintenance hatch, it's just like any other multiblock that is busy 24/7, but you can use robots to apply tape if luck isn't with you so it's not really an issue. And if really you don't want to pay the upkeeps 24/7, just power the cleanroom just before you start to craft, so you dodge most of the issue, but then you have to face the warmup time.
> 
> I'd rather accept the complains about the size of the multi required or the lack of room in it than upkeep costs, as it's just some laziness.

I do honestly hate the size of the cleanroom as well as the warmup time- also, maintenance issues for the cleanroom can straight up just void recipes rather than simply make you spend more power

in addition, automating anything inside the cleanroom is just... well, you can't exactly pop a hole in the wall to run an ME cable so you need to make the quantum ring

**Comment by Borjomm** [comment]
So what do we do in IV-LuV, when we need lots of circuits (asslines, for example)? Just put more CAs in a cleanroom and parallel them with p2p interfaces? Because making a CAL for each circuit should be left where it is right now imho.
I usually just put a PA with 4-8 CAs for my circuits and do all of them in one

**Comment by Borjomm** [comment]
> in addition, automating anything inside the cleanroom is just... well, you can't exactly pop a hole in the wall to run an ME cable so you need to make the quantum ring

Wireless connector is a thing

**Comment by boubou19** [comment]
> in addition, automating anything inside the cleanroom is just... well, you can't exactly pop a hole in the wall to run an ME cable so you need to make the quantum ring

This is true only if you don't go with transvector interfaces. Transvector interfaces are good to access remotely machines through walls. Also if you don't like transvector interfaces, wireless blocks to go through the wall will not kill your power consumption in comparison to a quantum ring, and you have all the benefits of AE2 inside the CR.

**Comment by ivelieu** [comment]
I know this long term change sounds set in stone. I am probably much too late to comment. And I understand somewhat that the implementation for the current PA code is hacky... I still really frown upon these changes. 

Take this 'vision' to the extreme and in a few years we will have ten different types of LCR because the LCR was maybe too "generic".  Generic multis are important to have in a pack with so many specialised recipes, especially with automated expansion.

 The PA multiblock I have personally adored. As stated previously, it is a nightmare to manually verify there are no missing multiblock-specific recipes for single block counterparts - just creating tons of  development busywork imo. And they enable good voltage performance that is impossible to replicate in GT++ multis, without a ton of code hacking and otherwise unnecessary rebalancing anyway. 

But the main reason I am opposed to this change is in principle. The key advantage of PAs is that they are generic. With one generic setup, I can just keep repeating it and the only thing I need to change is the input machine and interfaces. In the past I have even used opencomputers to automatically assemble and place PAs en masse. The logistics of this - and one of my ultimate goals, a self-expanding base like in Factorio, is virtually impossible with PAs being removed. Like AbdielKavash commented, I at the very least think players should have the choice to use PA or GT++, especially when in endgame 64x PA is more performant.

It also has a big building style advantage - consistency. Making a mega base with a consistent style, unless you spam 10+ of each GT++ multi (killing TPS in the process), is virtually impossible. They all have very clashing colours, and I personally find the GT++ multis to have ugly textures, unintuitive operation (especially the 9 in 1), and I don't exactly have much respect for performance of GT++ in general. There is only so much a spraycan and covers can improve. As AbdielKavash also mentioned, wall sharing different multiblocks is also a intriguing creative challenge to minimise space while still having sufficient hatches for recipes and no recipe conflicts, and something which specialised multiblocks can't do with different specialisations. Not only is this an efficiency boost for parallel processing different recipes, but I think it is an interesting puzzle in its own right and would be sad to see it leave. 

I would so much prefer if PAs could just have a better implementation here. I don't know exactly how 1.12 GTCEu handles the PA implementation, but in my personal opinion that's one of the big highlights of 1.12 GT-centered packs.

I played to UHV in 2020 on prospercraft (my completed goal was infinity gear, not Stargate). I remember when they were added a few years ago and almost everyone in prospercraft was frowning at the GT++ multi additions -- frankly they seemed way too hacky at the time in terms of processing speeds and energy discounts. I don't feel that has changed much - in fact, I was hoping GT++ would get phased out. I can see that the opposite has happened. The inconsistency in style, in mechanics, and the huge recipe bloat makes GT++ one of my least liked mods in GTNH. To be clear I am not talking about a complicated recipe chain changes like aluminum or platline production, but, for example, flooding JEI with useless dusts and ingots and components makes recipe navigation so much more difficult. I suppose part of the blame for this falls on how GT tries to be generic, but GT++ just takes it the whole wrong way in my opinion. 

Tangent: I don't know if this has been considered, a kind of "lazy loading" where GT only generates recipes for material forms that are actually used in a meaningful recipe and not just for an auto-generated texture. For example, only registering the casing block if the casing is used in a recipe or for a multiblock.

**Comment by minecraft7771** [comment]
Just to clear some misconceptions: GT++ machines should no longer have a TPS or performance impact since 2.4.0 (atleast not a bigger one than GT machines in general), since all their recipe check logic was purged and replaced to use the one in GT5U. So if there is a performance issue now, it would affect all machines and not just GT++.

**Comment by PrezesE** [comment]
I remeber using them for oil processing (super heavy to heavy IIRC) which could be easily shifted to destilation tower and for automating assemblers on EV/IV though that was few versions ago

**Comment by Divran** [comment]
I would like to point out one of the only remaining advantages of PAs over gt++ machines after the batch mode change:
* Speed per TPS at the cost of energy.

Due to the fact that you can jam 64 UMV machines in the space of a 3x3x3 multi, while most gt++ machines don't reach 64 parallel by the time you completely max out their energy hatch, unless I'm wrong this means that even with the speed boost of gt++ multis, 64xUMV PAs are faster while using a ton more eu/t. It'd probably be bad to delete PAs before we get more megas to replace them, or an upgrade that can be inserted into gt++ machines that allows multi-amp + laser hatches, or anything like that for late game.

**Comment by Hikari1nVoid** [comment]
Just wonder how we are going to manufacture large amount of processor assembly/nano/quantum series circuits.CAL does not meet the standard as an replacement for PA.Guess we probably need a "primitive circuit assembler" which functions as singleblock cals,but with following features:
+Large input bus/hatch as other multis.
+Potential parallel abilities
+Cleanroom environment

**Comment by NikitaGamer64** [comment]
I wonder if Processing Array can hold several Integrated Circuit or Lens or whatever blueprint-like item types in one input bus each, because GT++ machines, as I remember, can only hold one blueprint-like item each. If PA can, that is less place occupied and less crafting needed.

**Comment by Divran** [comment]
> I wonder if Processing Array can hold several Integrated Circuit or Lens or whatever blueprint-like item types in one input bus each, because GT++ machines, as I remember, can only hold one blueprint-like item each. If PA can, that is less place occupied and less crafting needed.

both work exactly the same way in regards to this, not sure what made you think otherwise

**Comment by NikitaGamer64** [comment]
> > I wonder if Processing Array can hold several Integrated Circuit or Lens or whatever blueprint-like item types in one input bus each, because GT++ machines, as I remember, can only hold one blueprint-like item each. If PA can, that is less place occupied and less crafting needed.
> 
> both work exactly the same way in regards to this, not sure what made you think otherwise

GT++ machine can contain several blueprint items, but can’t it be more comfortable to put one in each PA input bus, or PA can’t contain too many input buses?

**Comment by Divran** [comment]
> > both work exactly the same way in regards to this, not sure what made you think otherwise
> 
> GT++ machine can contain several blueprint items, but can’t it be more comfortable to put one in each PA input bus, or PA can’t contain too many input buses?

both PA and gt++ can have more than one non-consumed item in each input bus, but yes it's much easier to only use one each most of the time. The number of input buses PAs can handle isn't really relevant to this ticket because by lategame you're only putting one stocking bus on each PA anyway. And lategame is the only time PAs can compete with gt++ now, and even then only sometimes.

**Comment by Rosenlied-Iris** [comment]
> Just wonder how we are going to manufacture large amount of processor assembly/nano/quantum series circuits.CAL does not meet the standard as an replacement for PA.Guess we probably need a "primitive circuit assembler" which functions as singleblock cals,but with following features: +Large input bus/hatch as other multis. +Potential parallel abilities +Cleanroom environment

Currently planning to make proposed code for a "Precise Soldering Array" or "Circuit Prototyping Array" that uses single block circuit assembler recipes. Intention is for it to have a footprint similar to current precise assembler, and for recipes to be gated via engraving system casing (recipe comparable to single-block circuit assembler of that tier).

Might not get around to it before someone else makes a comparable proposal or something that fills the same role, though. 

The intention is for that machine to serve the same role as "processing array filled with single-block circuit assemblers" in progression: "making the circuits needed to enable CAL use", and circuit production pre-CAL but post-iridium.

**Comment by slmnemo** [comment]
Seconding convenience on a benzene setup. LPF is really useful to have less trouble figurimg out logistics for benzene setups with more than 16 fluid extractors.

**Comment by combusterf** [comment]
I've found an edge case where I had to go back to a PA: To process the tungstate family you need two item and one fluid inputs in an autoclave. 

While the large processing factory supports autoclave functionality, it has separate inputs forced to on in the current version, which means that both the tungsten ores and the sodium have to be in the same input bus. This causes automation problems because a regular input bus would tend to fill up with one of the two once the other runs out, causing a gridlock. The same problem arises if you have unprocessed ores on a separate ME network like I do and can't use a single stocking input bus.

This could easily be resolved if the LPF would support split inputs, or as part of the dedicated multis suggestion.

**Comment by truenachtara** [comment]
Don't input buses have restricted insert capabilities? As in, they'll only
allow one stack of each item, allowing for multiple different types to be
auto stuffed in willy-nilly.

**Comment by combusterf** [comment]
Depending on which exact tungsten source you use, a one stack maximum input limits the parallelism to 8-10 out of the possible 64 with a PA.

**Comment by chochem** [comment]
PA is deprecated in 2.7.0
