### ISSUE TITLE
TF wrong ore vein

### ISSUE THREAD

**Issue by jjorge146** [GTNewHorizons/GT-New-Horizons-Modpack#14527]
### Your GTNH Discord Username

jjorge

### Your Pack Version

2.3.0

### Your Server

private server

### Java Version

Java 8

### Type of Server

Vanilla Forge

### Your Expectation

scanner found a gold vein in TF but when I mined it it turned out to be talc

### The Reality

vein was talc

### Your Proposal

round down relevant ores for TF to either remove them or move em

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
I dont understand the proposal.

**Comment by hallucinogender** [comment]
From the sounds of things, the issue is simply that Visual Prospecting is displaying one type of ore vein on the map, but the _actual_ ore vein in the world is different (i.e. the one displayed on the map is incorrect).

The "Your Proposal" section of the bug report makes zero sense; I can't see how changing which ores are able to spawn in the Twilight Forest would affect whether ores are accurately displayed.

Additionally, I can corroborate that this bug exists. I've experienced a similar issue in 2.4.0, where a lapis vein in the world shows up as perditio-ordo on the map. My Twilight Forest dimension was only generated after I updated, though the save is older.

**Comment by jjorge146** [comment]
Hi sorry, I was very very tired and/or sick when I submitted that so in
hindsight my words did not make a super large amount of sense. I think I
was basing it on this discord conversation
https://discord.com/channels/181078474394566657/234936569360809996/1152327903363739729
either way it's likely just a visual prospecting thing. I think my thought
about changing the generation is I'm not sure that a gold vein can spawn in
the twilight Forrest with the y level it comes at normally. Once again
though my suggestion was really not well formulated and that's my bad.

**Comment by chochem** [comment]
hmm, it might be vanilla ores confusing it?

**Comment by Rika-TH** [comment]
our conclusion on the discord at the time was that due to the height that the given gold vein spawns at it may incorrectly spawn in the TF and so the TF ores should be relooked at, with either removals made or a function to round down the y level of ores that are greater than the usual y level of the TF to make them correctly spawn (albeit right under dirt as opposed to being buried at all)
