### ISSUE TITLE
Сlarify warning "Not enough output space" for fluids or for items

### ISSUE THREAD

**Issue by DmitryScaletta** [GTNewHorizons/GT-New-Horizons-Modpack#14560]
### Your GTNH Discord Username

DmitryScaletta

### Your Pack Version

2.4.0

### Your Proposal

Change "Not enough output space" warning for different situations:

* "Not enough output space for fluids"
* "Not enough output space for items" 
* "Not enough output space for fluids and items" (if it's possible, don't know how it works internally)

Words "fluids" and "items" can be highlighted (with different color for example).

### Your Goal

\-

### Your Vision

It can help to find a problem with a multiblock quicker

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by bombcar** [comment]
For the EBF in particular, the void protection causes recipes _with pollutants_ to not run in confusing ways. Since everything else on an EBF has to be at the bottom (except the muffler) and NEI doesn't show something as a pollutant, many chat help requests come in with "it won't run" or "it won't run, and I have an output hatch".

I would go so far as to have an "Not enough output space for pollutants (upper output hatch)" message for the EBF specifically.

**Comment by AbdielKavash** [comment]
This might be out of scope here, but could the NEI diagram for the EBF be changed so that it has two fluid output spaces, one above and one below the item slots. This would visually communicate the idea, as well as giving a clear indication of which output goes where without having to FAAFO.

Quick mockup:

![](https://i.imgur.com/BPYD3Bx.png)

**Comment by miozune** [comment]
For EBF situation it's not trivial to implement, so I'm not touching it for now. Make another ticket if you think it's still relevant.
