### ISSUE TITLE
Add an Exact Amount to Fluid Regulators

### ISSUE THREAD

**Issue by LazyFleshWasTaken** [GTNewHorizons/GT-New-Horizons-Modpack#14610]
### Your GTNH Discord Username

LazyFlesh

### Your Pack Version

2.4.0

### Your Proposal

Currently fluid regulators will pull any amount under the imposed limit. I hope we can get an exact amount option that will make it pull/push Exactly the imposed amount instead of any amount below it. 

For example, it will currently pull anything below 100L/t, like 33 L/t for example. 
What I want is a the fluid regulator to Always pull 100L/t, and if it doesn't have enough to pull, It simply won't. 

### Your Goal

This will help with things like the dissolution tank, and other such setups.

### Your Vision

There's currently no good way to do this, at least none that I know of. The item buffer can already output an exact amount, ex. 36 for small/tiny dusts, so it'd be very nice to have on some other things too.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by vovaksenov** [comment]
Im not sure how i feel about this. There are already very few times you need to do something unconventional for automation after so many qol things added lately. This multi might be the first you run into that kinda makes you understand you cant just throw stuff at it hoping for a result, leading you to explore stuff like SFM or other more involving parts of the pack that lately have been fading into obscurity. This might not be as balance affecting as the stocking input bus, but with this one i cant understand why you would want to specifically remove one of the only accessible tech automation "challenges" left in the game.

**Comment by LazyFleshWasTaken** [comment]
... the dissolution tank isn't a challenger, just an inconvenience at best. There is already more than enough documentation on how to do it. The line itself is the challenge, not a single step in it. The Mona and bast lines are the two longest I know of, and the dissolution is a minor, inconvenient step in it.
And this was a single ilexample I could think of, there are others that are applicable, like the bacterial vata with their efficiency based on output hatches, or for power gen like the universal chemical engine.

Oh wait, I just remembered, didn't logistic pipes have something like this? I might be misremembering.

Regardless, I made this request because I felt it would be good for the pack. A QoL.

**Comment by boubou19** [comment]
We have this for the items with the chest buffers, i wouldn't be opposed to have something for the fluids. As for the "automation challenges" those are not challenges since years, as when someone finds a very convenient automation system, almost everyone is copying it. (see asslines for instance). Those who want to attempt the challenge on their own will do it with or without this addition.

**Comment by vovaksenov** [comment]
One of the points i want to make clear is that i am not specifically against this idea, it is indeed kind of cool. What i am against is the general tendency to simplify all aspects of automation in the past few years reducing them to a few "prefabricated" options you just kind of apply when needed, rather than making them yourself from more elementary "components".  This takes away a significant part of gameplay and kind of feels as if the modpack is slowly turning into an idle game like antimatter dimensions. While you are saying it is not a challenge, people frequently come to the help channel for advice, and get varying recommendations to take inspirarion from as opposed to assline. It would also be reasonable to assume many go through it without help as well despite finding it just as unconventional at first. If you give everyone an option so simple, it feels like is intended for a specific application, and you give it for every challenge there is in the pack (which i do feel like is gradually happening), even if the player loves a challenge, they will not feel such satisfaction from solving this problem, as it would be a self inflicted rather than an intended one. It is also important to leave enough challenges in early-mid game. Not just planning out the platline kind, but also like these. Automation cahllenge should be about automation, not about crafting an "automation block".

**Comment by vovaksenov** [comment]
And specifically to boubou, why would you claim the level maintainer terminal had to be gated in endgame while this is completely fine? Imo it should be the opposite. While that terminal adds very few actual **new** abilities to the maintainers apart from convenience of centralized control (instead of just running around clicking each maintainer), this addition indeed would implement a new function allowing for a what basically is a skip of 1.4 very unconventional multis.

**Comment by boubou19** [comment]
because AE2 is the main automation mod past a certain point, and while it's cool to have QoL, it's not to have it too early. The spirit of NH is to earn your QoL.

**Comment by vovaksenov** [comment]
I see your point, but how is this addition different?

**Comment by vovaksenov** [comment]
I see. Thanks for taking your time to explain.

**Comment by chochem** [comment]
I got to say I dont really see the inconsistency. why should items and fluids have to be the same? its much easier to count items than to measure an exact amount of fluid. however regulating aka throttling fluid to a certain maximum flow like it does right now makes a lot of sense.
