### ISSUE TITLE
Advanced Blocking Card can't block recipes that consist of only fluid

### ISSUE THREAD

**Issue by shiita0903** [GTNewHorizons/GT-New-Horizons-Modpack#14620]
### Your GTNH Discord Username

shiita0903

### Your Pack Version

2.4.0

### Your Server

SP

### Java Version

Java 19

### Type of Server

Single Player

### Your Expectation

Tring to use Advanced Blocking Card for fluid only recipe. Expect to work blocking mode.

### The Reality

I tried to use advanced blocking card to avoid conflicting fluid only recipe for LCR but fluid for two recipes are inserted to input hatch at once.

How to reproduce
1. Insert any fluid to input hatch
2. Craft two recipes that consist of only fluid. (Blocking mode works here)
3. Remove the fluid inserted by No.1 from the input hatch
4. Check all fluid are inserted to the input hatch at once

https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/20969270/988eeab5-f0a4-48ca-871c-53d06f9009d6

### Your Proposal

Change behavior of Advanced Blocking Card for fluid only recipe to work blocking mode.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Qwasyx** [comment]
This same issue also happens for me, even when using multiple normal input hatches + fluid storage busses (I was told in the discord that this issue was thought to be with the quad hatch, but that doesn't seem to be the case for me).

**Comment by vovaksenov** [comment]
Can not test it myself right now, but perhaps adding a fluid discretizer into the subnet could help? This might allow blocking mode to pick up that there are fluid drops in the network.

**Comment by shiita0903** [comment]
@vovaksenov 
Thank you for your suggestion. I tried it but unfortunately fluid discretizer doesn't solve this issue.

**Comment by AbdielKavash** [comment]
Since this is now mentioned in [issues for 2.5.0](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/15013), I can add my own example. This is from 2.4.1.

https://www.dropbox.com/scl/fi/urlmnpcst7phpogg5xorh/Jxw9W5dfmv.mp4?rlkey=ijq9zgufk7trkwxk3n3uf5rmr&dl=0

This is a very typical subnet setup, main net (blue) dual interface in blocking mode points to a subnet (red) dual interface with an advanced blocking card. The red network has storage buses on tanks and a chest. The patterns in the interface are:

* 1000 mB Water --> 1 Blue Wool
* 1000 mB Lava --> 1 Red Wool
* 1 Blue Wool + 1 Red Wool --> 1 White Wool.

Requesting a blue wool, then a red wool, correctly inserts water into the subnet and then blocks until the subnet is empty before inserting lava.

However, requesting white wool (which uses both red and blue wool as precrafts), inserts both water and lava into the subnet at the same time, getting around blocking mode.

Things that do not fix the issue:
* Adding a fluid discretizer to the red network, as @shiita0903 commented (this has no point, the red network never deals with fluid drops, only with actual fluids).
* Setting the interface on the red network to blocking mode (this would only affect patterns pushed by the red network).
* Setting the interface on the red network to loose mode (there are no circuits etc. in the red network).
* Changing the insertion mode on either of the interfaces.
* Setting the fluid storage buses to different priorities.

The problem persists even if one of the two patterns has an item input (add any item to one of the red/blue wool recipes) and the other pattern is fluid-only. When white wool is requested, both water and lava still get inserted into the subnet at the same time. The only way for the setup to reliably only process one recipe at a time is to make sure that every pattern contains at least one item input.

**Comment by AbdielKavash** [comment]
Noting that this is still an issue in 2.5.0. Replicating steps in the previous post still causes the same problem.

**Comment by Glease** [comment]
@AbdielKavash does it still break if the none of the output tank can hold the entire packet? In your example, it'd be 4 tank, 2 with 500mB space left for water and 2 with 500mB space left for lava
