### ISSUE TITLE
Putting Tconstruct tool into blood altar crashes you from server

### ISSUE THREAD

**Issue by Dr-Nye** [GTNewHorizons/GT-New-Horizons-Modpack#14622]
### Your GTNH Discord Username

DrNye

### Your Pack Version

2.4.0

### Your Server

Private Dedicated

### Java Version

Java 20

### Type of Server

Vanilla Forge

### Your Actions

Putting my TConstruct crossbow into a Blood altar (this blood altar was atop a enchantress ritual if that matters) puts you into a whitescreened minecraft followed by a caught crash screen. Identified erroneous mod is TConstruct. I am using optifine (it says i should note that). The server did not crash during this

### Crash Report

https://mclo.gs/pKoG4We

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by Rubijox** [comment]
Instead of a crash , when i put a tinker tool in a blood altar, the tool renders for 1 tick, then becomes invisible.
When i try to take the item back i get the item but it now has a bugged texture.
moving the item to a different inventory slot fixes the texture. 
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/32174232/854746f9-fc06-4708-ba2e-ea41c87a613e)
