### ISSUE TITLE
Add Recipes for Logistics Inventory System Connector and Logistics Item Card

### ISSUE THREAD

**Issue by RunAwayGoldfish** [GTNewHorizons/GT-New-Horizons-Modpack#14633]
### Your GTNH Discord Username

ntbtater

### Your Pack Version

2.4.1

### Your Proposal

Adding recipes to the:
Logistics Inventory System Connector
Logistics Item Card

### Your Goal

Logistics pipes while not the traditional inventory management mod of choice for most players is quite good for small scale farms and other smaller applications. Using this pipe would make connecting multiple inventories easier.

### Your Vision

Players could have the choice to use logistics pipes for cross dimensional and long distance item movement. This could be used for transporting items from farms located far away as mentioned earlier among other uses.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by truenachtara** [comment]
I'd like to reopen this issue- the logistics inventory system connector would be an invaluable tool to get LP inside your cleanroom, since both are highly relevant at the same point in progression. My proposal for a recipe is:

1 Logsistics Inventory System Connector:
Requires 120 EU/t (MV) in an assembler
1 Basic Logistics Pipe
1 Sensor (MV)
1 Emitter (MV)
4 Pulsating Chipset
Circuit #18

2 Logistics Item Card:
Requires 120 EU/t (MV) in an assembler
2 Blank Module
1 Item Filter
1 HV Circuit
2 Orange Illumar
8 Enderpearl Bolt
Circuit #18
