### ISSUE TITLE
Hand saw doesn't work on BOP mahogany logs

### ISSUE THREAD

**Issue by dgealow** [GTNewHorizons/GT-New-Horizons-Modpack#14664]
### Your GTNH Discord Username

droideka30

### Your Pack Version

2.5.1

### Your Server

private server, singleplayer

### Java Version

Java 21

### Type of Server

Don't know

### Your Expectation

Place a saw and a Biomes O' Plenty (not Forestry!) mahogany log in a crafting grid, get 4 planks.

### The Reality

Recipe doesn't work for BOP mahogany, can only get 2. (Or 6 with a cutting machine but that's a ways off)

### Your Proposal

Add hand saw recipe for BOP mahogany (and make sure it's there for other biomes o' plenty woods)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by dgealow** [comment]
You should add java 21 to the java version menu

**Comment by chochem** [comment]
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/40274384/4a0d75f7-2fde-4633-97f8-f1c08fd5354d)
works for me (on 2.4.1 but dont think anything was changed since stable)

**Comment by dgealow** [comment]
2.5.1:
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/31712479/c9711122-4a25-4041-8b23-e96ed74120fc)

**Comment by dgealow** [comment]
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/31712479/1062957c-d967-4184-ac79-08d4315db5d5)

**Comment by chochem** [comment]
its shaped, not shapeless.

**Comment by chochem** [comment]
if its not working, try a clean reinstall.

**Comment by dgealow** [comment]
Ohhhh there are two different types of mahogany wood
The forestry one is fine
The Biomes O' Plenty one has this issue

**Comment by chochem** [comment]
ohh...

**Comment by D-Cysteine** [comment]
I think this line is causing this problem (planks with meta 14 should be mahogany planks):
 * https://github.com/GTNewHorizons/NewHorizonsCoreMod/blob/bb11669eb33b789b7d1b7fce7c7481a3834145c7/src/main/java/com/dreammaster/recipes/RecipeRemover.java#L412

Most likely this line was added because of this:
 * https://github.com/GTNewHorizons/Mods-Get-Gregged/blob/af4efd950c015fc51b50d65a3810d5b25494eacb/Custom-Modpack-Scripts/GTNewHorizons/scripts/Biome-o-Plenty.zs#L101-L104

It's several years old, so not sure if there is still a reason to nerf it. I guess we can ask Dream.

---

If mahogany no longer needs special treatment, then there are a few other places we might be able to clean up, which might also have been added due to that old script:
 * https://github.com/GTNewHorizons/NewHorizonsCoreMod/blob/bb11669eb33b789b7d1b7fce7c7481a3834145c7/src/main/java/com/dreammaster/scripts/ScriptBiomesOPlenty.java#L106-L108
 * https://github.com/GTNewHorizons/NewHorizonsCoreMod/blob/bb11669eb33b789b7d1b7fce7c7481a3834145c7/src/main/java/com/dreammaster/gthandler/GT_Loader_OreDictionary.java#L53-L56

The searches I used to find these (might not be comprehensive):
 * https://github.com/search?q=org%3AGTNewHorizons+logs4&type=code
 * https://github.com/search?q=org%3AGTNewHorizons+%2F%28biomesoplenty%7Cbop%29.*planks.*14%2F&type=code

**Comment by chochem** [comment]
> I think this line is causing this problem (planks with meta 14 should be mahogany planks):
> 
>     * https://github.com/GTNewHorizons/NewHorizonsCoreMod/blob/bb11669eb33b789b7d1b7fce7c7481a3834145c7/src/main/java/com/dreammaster/recipes/RecipeRemover.java#L412
> 
> 
> Most likely this line was added because of this:
> 
>     * https://github.com/GTNewHorizons/Mods-Get-Gregged/blob/af4efd950c015fc51b50d65a3810d5b25494eacb/Custom-Modpack-Scripts/GTNewHorizons/scripts/Biome-o-Plenty.zs#L101-L104
> 
> 
> It's several years old, so not sure if there is still a reason to nerf it. I guess we can ask Dream.
> 
> If mahogany no longer needs special treatment, then there are a few other places we might be able to clean up, which might also have been added due to that old script:
> 
>     * https://github.com/GTNewHorizons/NewHorizonsCoreMod/blob/bb11669eb33b789b7d1b7fce7c7481a3834145c7/src/main/java/com/dreammaster/scripts/ScriptBiomesOPlenty.java#L106-L108
> 
>     * https://github.com/GTNewHorizons/NewHorizonsCoreMod/blob/bb11669eb33b789b7d1b7fce7c7481a3834145c7/src/main/java/com/dreammaster/gthandler/GT_Loader_OreDictionary.java#L53-L56
> 
> 
> The searches I used to find these (might not be comprehensive):
> 
>     * https://github.com/search?q=org%3AGTNewHorizons+logs4&type=code
> 
>     * https://github.com/search?q=org%3AGTNewHorizons+%2F%28biomesoplenty%7Cbop%29.*planks.*14%2F&type=code

yea found it myself. 2014 XD. literally broken since the first days of the pack.

**Comment by dgealow** [comment]
not sure why you'd want to nerf Mahogany--I guess the trees are pretty big, but that's counterbalanced by the fact that they're a pain to chop down due to their unique shape.

**Comment by chochem** [comment]
all logs are nerfed in GT. This was from the very first days of the pack when dream was still figuring stuff out. or maybe gt nerf came later for all I know.
