### ISSUE TITLE
Nanosuit Wings cause memory leakage of 30-40 MB per second when visible

### ISSUE THREAD

**Issue by ussdefiant60** [GTNewHorizons/GT-New-Horizons-Modpack#14680]
### Your GTNH Discord Username

ussdefiant60

### Your Pack Version

2.4.1

### Your Server

SP

### Java Version

Java 20

### Type of Server

Single Player

### Your Expectation

Being able to have my inventory open without causing memory usage of the JRE to balloon.

### The Reality

While i have my inventory open with the avatar visible or am in 3rd person mode while having Nanosuit Wings equipped, my RAM usage spikes well above the limits sets in the launcher at a rate of approximately 30-40 megabytes per second while not showing any inclination of decreasing when the Wings aren't being rendered. This fairly rapidly leads to all RAM/virtual memory on my PC being consumed, resulting in my JRE freezing and me letting forth a stream of expletives.

Notably, removing the Wings from being worn does not result in any of the RAM being recovered.

I will note that this happens to me on both Adoptium 20.0.2+9 and 17.0.8.1+1 

### Your Proposal

It seems possible that this issue is related to #13007 , as the symptoms are similar and both items require doing Thaumcraft things to unlock. I don't know enough of how the items are put together on the backend to be certain on that point.

I'll probably end up doing some VisualVM shenanigans to try and provide more info in the next couple of days.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Caedis** [comment]
Have you been able to recreate this in a creative world with just the nanosuite wings equipped?

**Comment by SKProCH** [comment]
With the help of some mod dev I managed to get some details. 

Memory traffic becoming higher when inventory opens or third person mode enabled.  
Here some memory traffic sampling screenshots:  
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/29896317/679048fc-eb80-4ec0-9ca6-00443726d93e)
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/29896317/5a08c35c-9ebe-43ba-b7fd-18075b8f0a68)
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/29896317/849f34c4-7fda-4e08-b8a6-29b2ef6ba783)

And here is the expanded graph from profiler: 
[Allocation-telemetry](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/14441140/Allocation-telemetry.txt) (change extension to html and open in browser, since GitHub doesn't allow to attach html files).

Seems like some strange allocations located at least here: now wonder why
https://github.com/GTNewHorizons/Electro-Magic-Tools/blob/master/src/main/java/emt/item/armor/chestplate/ItemInfusedQuantumChestplate.java#L392

Discord mod-dev message id: https://discord.com/channels/181078474394566657/603348502637969419/1212537688461148160
