### ISSUE TITLE
Project Red IC Gate inconsistent timings

### ISSUE THREAD

**Issue by THEWEZERNOW** [GTNewHorizons/GT-New-Horizons-Modpack#14781]
### Your GTNH Discord Username

the_wezernow

### Your Pack Version

2.4.0

### Your Server

Private

### Java Version

Java 8

### Type of Server

Ultramine

### Your Expectation

This gate accepts button inputs from Project Blue panel and toggles the corresponding channel, 1 at a time, if some channel is already ON-turns it off and powers the channel of the button pressed. 
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/74426546/06b74beb-4008-4ee2-95e7-7e32fd871f35)

### The Reality

In reality the only channels that do the thing are white,orange,magenta,lime, and blue, pretty strange pattern. I decided to rebuild the whole thing in world, and came to the conclusion that Buffer Gate on Black(reset) channel adds a small delay to the signal, and so XOR Gate is not working as intended, adding Buffer to the Button channel syncs the signal and XOR works. However this workaround only works in world, not in IC Gate
edit: forgot to mention that i tried assebling this gate and it did the same thing it did in IC Workbench
[Video Explanation](https://www.youtube.com/watch?v=xr62dqzcDIE)

### Your Proposal

Fix the time inside IC Gates, so it works like in world.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Cardinalstars** [comment]
Buffer gates (in world) do seem to add a delay. I'm not sure if this is intended because the wiki doesn't explicitly mention it. Looking at the set up you have in this picture and doing a lot of thinking myself based on a world I made with this setup and your video I feel that the behavior with the setup you have shouldn't work IF buffer gates have a delay (I'm assuming they might not in IC?)

If buffer gates have a delay then we can expect the following in the world:

Tick 1: Button is activated pulse is formed (pulse former has no delay) buffer is activated, xor is activated. Both have a 1 tick delay.
Tick 2: Xor outputs a pulse that activates the top buffer, the toggle latch is activated. Both have a 1 tick delay.
Tick 3: The toggle latch outputs when the buffer outputs. The and gate is activated and the output is activated.
Tick 4: The toggle latch is turned toggled. The output is turned off.

As far as I can see this is what happens when you press the button having your setup like it is in the world. It does seem weird that the IC circuit doesn't display this behavior. I will do my best to look into it, but ProjectRed is in Scala which I'm not super familiar with.

I can say there does seem to be be a bug here with the IC circuits. Two buffers how you have it in the video should give you the behavior you want. Seems like you're on the right track the XOR is a problem.

![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/42074409/84ff096e-382b-4932-bf74-0a880ec23479)

This setup somehow triggers the latch.. which is definitely wrong behavior, and it seems it has to do with the position of the XOR gate.
