### ISSUE TITLE
Stop Project Red Red Alloy Wire from connecting to GT cables and pipes.

### ISSUE THREAD

**Issue by AbdielKavash** [GTNewHorizons/GT-New-Horizons-Modpack#14794]
### Your GTNH Discord Username

abdiel_kavash

### Your Pack Version

2.4.1

### Your Proposal

See title.

It does not affect anything since the cables/pipes do not react to redstone signals, it is just ugly.

![](https://i.imgur.com/woDOTcC.png)

### Your Goal

Aesthetics.

### Your Vision

Aesthetics.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Cardinalstars** [comment]
Honestly I haven't looked a the code, but I assume it's this way because of motors and stuff that can be redstone controlled? I guess we could make a change to only connect if there is a component that could be redstone controlled on it. 

I do support this change though since I have seen some ugliness with this.
