### ISSUE TITLE
Game crash as soon as world load

### ISSUE THREAD

**Issue by LeoGuys1** [GTNewHorizons/GT-New-Horizons-Modpack#14902]
### Your GTNH Discord Username

LeoGuys

### Your Pack Version

2.4.0

### Your Server

SP

### Java Version

Java 8

### Type of Server

Single Player

### Your Actions

Startup pack fine.
Load single player world.
As soon as world loaded crash occurs.
Tried with backup but didn't work.
Any ideas?

### Crash Report

[crash-2023-11-18_08.08.30-server.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/13399049/crash-2023-11-18_08.08.30-server.txt)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by bombcar** [comment]
I see `Mohist Version: 1.7.10-46` which isn't officially supported (we barely support thermos and only because the officials run on it) - perhaps try a direct pack launch with `startserver` and see if it works.

If this is a "server with friends" you may want to run j17+ version of the pack with ServerUtilities instead.
