### ISSUE TITLE
Microblocks

### ISSUE THREAD

**Issue by aeksae** [GTNewHorizons/GT-New-Horizons-Modpack#14921]
### Your GTNH Discord Username

aeksae

### Your Pack Version

2.4.0

### Your Server

SP

### Java Version

Java 8

### Type of Server

None

### Your Expectation

https://www.twitch.tv/videos/1984186039
Z-Tone Myst and Cubits (chisel) half cuts turned in to Blood Rune Slabs
https://cdn.discordapp.com/attachments/948587114369548319/1176853528938041404/image.png?ex=65706142&is=655dec42&hm=7e17c2f9df68e5d784f8a259bf8ce2278a2360842e7093ad4b4db0b8d66b24ae&

### The Reality

above

### Your Proposal

fix if you can

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Pxx500** [comment]
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/81298696/d6330a40-02c5-41b9-a9b2-313153f9b092)
first link doesn't work

**Comment by aeksae** [comment]
https://www.twitch.tv/videos/1984186039

**Comment by AbdielKavash** [comment]
I am experiencing this too; on 2.4.1, Java 19 singleplayer. This used to be a reinforced glass window.

![javaw_Iio2pgT5Ga](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/19243993/2cc3af55-539f-432b-a9f8-fd0265083ff1)

Unfortunately I do not know what causes this, and I can not reproduce this consistently. However the issue is sporadically repeating every once in a while, on isolated structures (one window like above gets changed, other identical windows are unaffected).

I have seen different "source" blocks change, but the resulting block is always Blood Rune.

The change is not just visual, if something like slabs or panels change, I can harvest them and craft them back into functional blood runes.

**Comment by boubou19** [comment]
are all those corrupted microblocks in the same region file?

**Comment by AbdielKavash** [comment]
They are all in the same region file, but not all microblocks in the same region file get corrupted at the same time. When it happens the problem is very localized; this window is the only one that got changed in my entire base.

Unfortunately I don't remember off the top of my head if it is affecting all blocks in one *chunk* at the same time (the window in the picture is contained in one chunk).

**Comment by AbdielKavash** [comment]
Well this is new :concern:

![](https://i.imgur.com/yQRGflU.png)

**Comment by Sordfish42** [comment]
![2024-04-29_22 09 55](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/168485574/d3a157cb-09e7-4912-81bd-38851afd230c)
I'm recurrently having this problem. My base's nether brick and glowstone Microblocks often get replaced by blood rune slabs. They often are replaced in long lines or patterns, almost like its a spreading infection

**Comment by dvdmandt** [comment]
So microblocks work by having a "material" registered. These are often based on the unlocalized name of the block instead of the block id or whatever. There appears to have been a change to move over to block IDs at some points, and there's some form of remapping code here: https://github.com/GTNewHorizons/ForgeMultipart/blob/master/src/main/scala/codechicken/microblock/BlockMicroMaterial.scala#L169-L172

Perhaps that's the issue? The move to switch over to block ids (I assume that's what `Block.blockRegistry.getNameForObject(block)` gets?) happened like 10 years ago, but I've found that the unlocalized name is what is stored in the block for many block types.

@Sordfish42 could you run `/nbtedit` while looking at one of the changed blocks, expand all + icons and screenshot the results, then do the same with one of the unchanged blocks?

**Comment by DarkYuan** [comment]
@dvdmandt
> could you run `/nbtedit` while looking at one of the changed blocks, expand all + icons and screenshot the results, then do the same with one of the unchanged blocks?

I'd like to help with this too, but I couldn't find a command for `/nbtedit`, though I got the `/mt blockinfo` of them here:
```[Client thread/INFO]: [CHAT] Block info mode activated. Right-click a block to see its data.
[Client thread/INFO]: [CHAT] Block ID: ForgeMultipart:block
[Client thread/INFO]: [CHAT] Meta value: 0
[Client thread/INFO]: [CHAT] Tile entity data: {x: 1337, parts: [{shape: 16 as byte, material: "minecraft:stone", id: "mcr_face"}], y: 65, z: 319, id: "savedMultipart"}
[Client thread/INFO]: [CHAT] Block ID: ForgeMultipart:block
[Client thread/INFO]: [CHAT] Meta value: 0
[Client thread/INFO]: [CHAT] Tile entity data: {x: 1338, parts: [{shape: 20 as byte, material: "AWWayofTime:AlchemicalWizardrybloodRune", id: "mcr_face"}], y: 64, z: 319, id: "savedMultipart"}```

**Comment by Sordfish42** [comment]
@dvdmandt

Thank you for getting back to me. Here are the results:
![2024-06-09_19 20 30](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/168485574/c15daba6-91b5-4de6-9816-97ec1f61f43b)
![2024-06-09_19 20 54](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/168485574/d889e3e2-a602-4fdc-9d86-b5d158872d1e)

@DarkYuan 
Nbtedit is a seperate mod you can donwload and add to your modlist
https://www.curseforge.com/minecraft/mc-mods/forge-nbtedit-for-1-7-10

**Comment by BegeistertsLab** [comment]
Is this post still being ivestigated? Otherwise I will go ahead and mark it as stale.

**Comment by AbdielKavash** [comment]
I haven't seen this happen in a *long* time in 2.6.1. Either it has been fixed or whatever was causing the issue was incidentally fixed elsewhere. I will close the ticket for now; if anybody experiences this again on a recent version please reopen or make a new one.

**Comment by Ruling-0** [comment]
I think it's very likely it becomes blood rune slabs because that's probably the first registered material alphabetically.

**Comment by dvdmandt** [comment]
These seems to return "first" material if not found, or null if not found:

https://github.com/GTNewHorizons/ForgeMultipart/blob/f3a0ab05687fb225ea5f5fa504a36bba2674c835/src/main/scala/codechicken/microblock/MicroMaterialRegistry.scala#L214-L223

```scala
  def materialID(name: String) =
    nameMap.get(remap.getOrElse(name, name)) match {
      case Some(v) => v
      case None =>
        logger.error("Missing mapping for part with ID: " + name)
        0
    }

  def getMaterial(name: String) =
    typeMap.getOrElse(remap.getOrElse(name, name), null)
```

In case anyone experiences microblocks changing materials again, can you check for `Missing mapping for part with ID:` in your logs? If so, we can confirm that it's there somewhere.

The `nameMap` is initialized in a `FMLServerAboutToStartEvent` handler:
```scala
  @EventHandler
  def beforeServerStart(event: FMLServerAboutToStartEvent) {
    MicroMaterialRegistry.setupIDMap()
  }
```

Are there any circumstances where we might be loading chunk data in a background thread while that event is being processed?

**Comment by seabasslegend** [comment]
I have found `Missing mapping for part with ID:` in my logs. Sometimes loading into my world random Microblocks change into Blood Runes within a single chunk.

[fml-client-3.log](https://github.com/user-attachments/files/25085595/fml-client-3.log)

Currently on 2.8.4, i've been noticing this since before 2.7. (always on java 17+).

@dvdmandt

**Comment by dvdmandt** [comment]
> I have found `Missing mapping for part with ID:` in my logs. Sometimes loading into my world random Microblocks change into Blood Runes within a single chunk.
> 
> [fml-client-3.log](https://github.com/user-attachments/files/25085595/fml-client-3.log)
> 
> Currently on 2.8.4, i've been noticing this since before 2.7. (always on java 17+).
> 
> [@dvdmandt](https://github.com/dvdmandt)

This is interesting, but are the parts changing into blood runes exclusively glowstone blocks or are there others? This whole thing still confuses me. It's so strange that some blocks are changing while others aren't, even in a single chunk..

**Comment by seabasslegend** [comment]
Its not exclusive to glowstone. This recently happened again to my Greatwood Log Pillars.
It happened to other slabs as well, though i  cant remember what material they were originally.

<img width="3840" height="2160" alt="Image" src="https://github.com/user-attachments/assets/dde777a2-27c7-4986-a7f7-874c391294c1" />

The log also has a lot of "`Material with id foobar is already registered.`" errors relating to chisel and AE2.

**Comment by Caedis** [comment]
Issue found to be SP only, concurrency issue between the client and server threading writing to the same map.

Fix coming soon
