### ISSUE TITLE
Upgrading pack to 2.5.0-RC1 causes some EnderIO Fluid Conduit connections to lose their Insert status

### ISSUE THREAD

**Issue by norbby42** [GTNewHorizons/GT-New-Horizons-Modpack#15092]
### Your GTNH Discord Username

Quackers#6418

### Your Pack Version

2.5.0-RC1

### Your Server

Private Dedicated

### Java Version

Java 8

### Type of Server

Vanilla Forge

### Your Expectation

When updating the pack from 2.4.0 to 2.5.0, I expect my EnderIO Ender Fluid Conduits to retain their settings.

### The Reality

In pack version: **2.4.0**
I had an oil processing setup using EnderIO Ender Fluid Conduits.  In several locations, the conduits were configured to both Insert and Extract from the same block from the same conduit.
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/10271937/a504c0f6-4195-41be-b126-0d1b504f0f0a)

I then updated the pack to 2.5.0-RC1 after seeing it was available for testing on the Discord.  The world was kept as is.

In pack version: **2.5.0-RC1**
Some of the places where the dual-direction Insert/Extract on the Ender Fluid Conduits were used lost their Insert flag.  So they were only Extracting.  This didn't seem to happen universally - only some of the dual-direction Insert/Extract setups were affected.

![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/10271937/5d466846-0a86-4134-99de-dd5f4f946086)

Insert-only and Extract-only configurations did not seem to be affected, though my sample size is only about 50 connections so I may not have enough to encounter the true underlying issue.

### Your Proposal

Either implement migration logic when loading conduits from an older version of EnderIO, or give a warning to users for the 2.5.0 pack release

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Hikari1nVoid** [comment]
Hi my conduit from 2.2.x preserves their setting.Can't repro.

**Comment by boubou19** [comment]
yeah but what if you update to 2.4.0 then 2.5.0RC1?

**Comment by norbby42** [comment]
Thinking back and looking at the affected machines, I _think_ that the cases where the setting was lost may have been where I never changed the value of Insert away from the starting value.

The screenshot example above, I was using conduits to insert Water and extract Distilled Water, and I'm pretty sure I never had any reason to turn off the Insert flag because I always knew from the start that I needed to insert Water into the machine.

Other machines with more complex recipes, like making Acetic Acid or dealing with cells when heating Acetone, I do suspect I toggled Insert off/back on at least once, and those settings were retained after the pack upgrade.

But I have not tested this, just a theory.

**Comment by Kyrorichekku** [comment]
Experienced the same problem when upgrading from 2.3.0 to 2.5.1

it seemed most common in conduits that were not changed from their default directional settings and for specifics I found that searching around there were many with colored (+ some cases of filters) inputs ( though more rare ) that had been disabled  as well

one thing I noticed in particular is it seemed like most of these cases were contained to particular chunks where the most common place I ran into the issue was in a older part of my base where I'd spawned combustion engines and gas turbines

there were lots conduits in the same general area that all had the exact same issue while there were entire large setups elsewhere with tons of conduits and connections that had not a single issue

in all cases where a filter and or color was turned off by this issue those settings were preserved but the input setting was switched off

these were setups I had been using for months of playing and had been running for many days at a time prior to the upgrade (they were running perfectly fine before) so I know the problem was new

also something I would add that although it was far more rare there were cases where the state of the conduits were just "wrong" that I'm not sure if is directly related to this issue but I found one corner of my based where is almost seemed like the conduit directions had been scrambled into random directions ( although it was a portion of my base that was enough old and barely used enough to have been caused by an older problem for all I know )

**Comment by Kyrorichekku** [comment]
honestly speaking I would consider the issue a bit more than "minor" there are more than a few ways your base may blow up due to this issue especially if the cause isn't yet known and if it is truely contained to when updating the pack
