### ISSUE TITLE
EOH not voiding items/fluids "If no space in the network", just cached in a me output.

### ISSUE THREAD

**Issue by lordIcocain** [GTNewHorizons/GT-New-Horizons-Modpack#15291]
### Your GTNH Discord Username

lord_cocain

### Your Pack Version

2.5.1

### Your Server

ps

### Java Version

Java 19

### Type of Server

Vanilla Forge

### Your Expectation

<img width="1111" alt="image" src="https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/62835225/d4595024-3729-4d3c-ae2f-cf91df5c2849">

### The Reality

idk

### Your Proposal

idk

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Savallator** [comment]
This was never the case imho, just the description changed?
And i think it is good that it buffers, because otherwise it will void items on world load, since machines will start running way before ME is initialized.
Maybe that buffering should have a limit though, if it does not already, because i remember i once had a storage bus with millions of items inside
