### ISSUE TITLE
Wireless Energy Hatches probably broken (maybe fixed) / PCB Factory broken

### ISSUE THREAD

**Issue by MaGeBZz** [GTNewHorizons/GT-New-Horizons-Modpack#15313]
### Your GTNH Discord Username

marvinhhmagebzz

### Your Pack Version

2.5.1

### Your Server

SP

### Java Version

Java 17

### Type of Server

Single Player

### Your Expectation

I had the problem with QFTs before and not sure if it will happen again for them but it is definetely for the PCB Factory
I wanted to upgrade my energy from UXV 16k to UXV 1M wireless laser and it started powerfailing after that
I thought it can be a problem with the buffer which shouldn't be there but could be so I used an Active Transformer and then normal UXV 1M amp laser and it powerfailed again
Then I build a LSC with an UMV cap and the 1M UXV laser again but it powerfailed again

I thought I change the wireless laser back to UXV 16k and it powerfails again
Not sure if that is the bug I had with the QFTs before that they powerfail sometimes with wireless laser or if that's a PCB factory thing probably but the PCB factory is useless in that case rn after you change the hatch

### The Reality

PCB factory powerfails although it should have enough power

### Your Proposal

Make changing of the energy hatch from PCB factory viable again
Updated from 2.4.1 to 2.51 and after that it happened

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by lordIcocain** [comment]
try reproduce bug in new world if you can

**Comment by MaGeBZz** [comment]
@lordIcocain reproducing it won't help for the problem I guess but I will try in some minutes to make a whole new PCB factory at another space and try if they powerfail too, if not I don't know what the problem is but it's weird af tried literally everything I would know to fix it with normal lasers etc and without cribs and nothing worked for now

**Comment by MaGeBZz** [comment]
Tried to make a completely new PCB factory at another place in my base - same problem it will start powerfailing although it has enough energy

**Comment by MaGeBZz** [comment]
@lordIcocain I texted with upsidedown and I know what it is now but it isn't fixed
The PCB factory is broken in terms of you have to break minimum one block from the PCB factory itself, then from both modules and then let it autoplace and it will work
If you place them manually it won't work at all and that's fr a not fixed problem but I know how to fix it for myself for now at least lol

**Comment by boubou19** [comment]
for me, the pcb factory works well until i use a coolant tower.
Observations so far:
the input hatch of the coolant tower is not recognized (does not change its texture)
the multi is saying it always fails due to a lack of power (even with a 64A UIV energy hatch fed up by a power debug generator set up to 80A UIV)

I suspect it is because it cannot remove distilled water so it fails the recipe, and it's wrongly labeled as a power failure.

**Comment by HoleFish** [comment]
A forced structure check trigger may fix the issue

**Comment by MaGeBZz** [comment]
@boubou19 yeah it was definetely the coolant tower with super coolant for me, not sure what's wrong there but this module definetely fucks up something, I managed to get a fix for now but it needs to be fixed at all imo

@HoleFish no forced structure check didn't help, for me it was autoplacing it but the problem with autoplacing is that you need to break one block of the module (for example coolant tower) and one of the main multiblock middle structure thing
Then you can autoplace both with the holo projector and then it worked for me
But anyways it didn't work with 1M UXV hatch, UXV 16k worked haven't tried 65k and 262k but 1M UXV wireless didn't work with that
Sometimes it does but not for a long while and then it powerfails again

**Comment by HoleFish** [comment]
try set cooler Z offset to -10 , construct PCB and install normal input hatch on the coolant tower. if it still fails then the problem may exists in the processing logic

**Comment by fluffle** [comment]
I also ran into this; will try the fix. I also found that disabling the coolant tower fixed the "power fail" problem, which supports @boubou19's theory that it is not able to consume the coolant correctly.

While trying different things to understand the problem I noticed that the structure hologram projector was showing the extra build pieces in their original locations rather than the ones I had moved them to via the configuration GUI. Simply opening the configuration GUI and closing it again without changing any values caused the hologram to be displayed in the correct place.

Perhaps these configurations are getting desynced somehow and the structure checking code is looking for the coolant tower in the original location rather than the user-specified one?

**Comment by fluffle** [comment]
The fix does appear to work, but only with a normal hatch. Presumably the forced structure checks are populating `mCoolantInputHatch` correctly, because the ME hatch texture changes when they kick in, but taking coolant fails. After a while the holograms move back to their original locations when I hit the controller with a projector blueprint, but the multi continues to craft and consume coolant, so I'm guessing that's just a visual bug.
