### ISSUE TITLE
Holo Glasses do not render occassionally, requires world restart to fix.

### ISSUE THREAD

**Issue by PlayfulPiano** [GTNewHorizons/GT-New-Horizons-Modpack#15388]
### Your GTNH Discord Username

PlayfulPiano

### Your Pack Version

2.5.1

### Your Server

SP

### Java Version

Java 21

### Type of Server

Single Player

### Your Expectation

Holo Glasses continue to render no matter what as long as the keybind isn't toggled.

### The Reality

The lens stops rendering. The below image is with the lens in my mask slot, and the keybind toggled multiple times to see if that would fix it. It did not.
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/3158887/e4950f06-00ee-4df1-a07d-203137c06de2)

Logging out and in does fix it.
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/3158887/c6ce1a97-de56-4301-a25b-75fe35564c34)

### Your Proposal

Bugfix.

Log is attached in case there is anything of interest in there.
https://mclo.gs/bLznRGz

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by PlayfulPiano** [comment]
Update: It's due to dying when you have keepinventory enabled.

**Comment by ALongStringOfNumbers** [comment]
I have this issue as well, and it happens when dying or changing dimensions. KeepInventory does not affect it, from what I have seen. Logging out and back into the world fixes it.

Seen on Nightly 592

**Comment by BegeistertsLab** [comment]
have any of you found a way to consistently reproduce it?

**Comment by Yamnasm** [comment]
> have any of you found a way to consistently reproduce it?

Tested on Nightly build 728 with all the following combinations:
- Holo Glasses on head slot vs baubles slots 
- keepInventory gamerule true vs false
- Dying and changing dimensions.
- Enable/disable hotkey for Holo Glasses.

Not able to reproduce reported issue.

**Comment by BegeistertsLab** [comment]
Since the issue is old and unable to be reproduced in the current Nightly, I have marked it as stale.

**Comment by PlayfulPiano** [comment]
I'm pretty sure this issue has been resolved at this point, so yeah I'm going to close it (and if it happens again someone else can re-report it I guess).

**Comment by Technikcz** [comment]
in my one world (SP), holo glasses do not show inventories, only fluids
I have addon mods: GTNotLeasure, TwistSpaceTechnology, 123Technology

- tried multiple time toggle button (5) -> didn't fix it 
- reloading world (leave+join) -> didn't fix it
- closing game and start it again -> didn't fix it
- then I tried start another wolrd and there it worked, but then in original file not?? (worldfile related issue??)
<img width="2559" height="1401" alt="Image" src="https://github.com/user-attachments/assets/6b846fe0-94e1-41a1-b07b-ab9e6c028a63" />
but somehow it still shows fluids in bugged world? (in comparasion to prev issue + it is reacting to toggle too - on fluids)
<img width="1205" height="1093" alt="Image" src="https://github.com/user-attachments/assets/8214e02f-b144-4eef-ab77-4bed9c89b662" />

... EDIT: fixed by disabling yellow filter in NEI search (it filtered all intems out)
-> suggestion: write comentary to Holo Glasses that it uses this NEI filter (if someone forgot it from questbook...)
