### ISSUE TITLE
Supposedly 0 Essentia Cost Items suddenly requires essentia in an Infusion setup

### ISSUE THREAD

**Issue by Canthonk** [GTNewHorizons/GT-New-Horizons-Modpack#15544]
### Your GTNH Discord Username

P.O.G

### Your Pack Version

2.5.1

### Your Server

private server

### Java Version

Java 8

### Type of Server

Vanilla Forge

### Your Expectation

Trying to make Element of Darkness (Along with several items that supposedly costs 0 essentia) in an automated infusion setup, This should have ran fine and be crafted without any issues
![2024-02-17_13 15 11](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/83339226/a8c07038-877c-466d-af33-88fbea5746ef)

### The Reality

The Runic Matrix as shown in the photo, tells me that It is out of essentia and is stuck making the item
![2024-02-17_13 11 53](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/83339226/6201b0b1-1571-43e5-ac4b-e647d8a4b4a8). Replenishing The shown essentias Didnt make it go unstuck, It kept like that until I pulled out the item in the middle.

### Your Proposal

This might be an issue with the wrong display of costs in the NEI and Thaumomicon which makes me think that it has no essentia costs
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/83339226/0c399190-41f1-4c8d-a218-535576f16296)
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/83339226/3f8662a4-31ad-4f39-bcc6-241c66ea763b)
or a issue with the altar itself calculating essentia costs.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by AbdielKavash** [comment]
The issue here is that these two items specifically (I am not aware of any others) have a *randomly calculated* essentia cost. The aspects they need are the same, but the amount of each aspect will be different with every craft. Both the Thaumonomicon and NEI are unable to make sense of this.

I would personally be in favor of just removing this randomness, assign a fixed essentia cost to both, and make them consistent with every other infusion craft in the pack.

**Comment by Canthonk** [comment]
Alright, thank you for telling me this, However, I have the required essentia in the system, and still couldnt fill the need.

**Comment by AdolMors** [comment]
### The Randomness
According to ftbwiki pages of the two items, [Element of Darkness](https://ftbwiki.org/Element_of_Darkness) and [Aura Core](https://ftbwiki.org/Aura_Core) do have a max cost. I was able to confirm this in [Gadomancy's recipe registration file](https://github.com/GTNewHorizons/Gadomancy/blob/master/src/main/java/makeo/gadomancy/common/registration/RegisteredRecipes.java). Notice the recipes use a RandomizedAspectList class which is likely where the randomness come from. This custom AspectList class may also be why recipe does not show aspects.
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/47838758/80fb08a9-a0de-4fec-8f5e-a6cf4b027a97)
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/47838758/4d941775-8a03-4bf9-8a8d-9f7a65eaca25)

Looking at the class, the aspect list seems to be randomized every 500ms. With halfCap set to true this seems to align with ftbwiki's wording of required infusion aspect being a random value between max and half of max. From my personal testing, the aspect required for infusion should be randomized but should not fluctuate during infusion. I started infusion without any of the required essentia then inserted an essentia storage cell with the required aspects. The infusion interceptor was able to supply the essentia and infusion continues to completion.
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/47838758/045c20c2-dfd0-43a6-ae14-32f76b808a99)

### Stuck Infusion?
As for the infusion being stuck, one possibility is instability. Using abacus to check stability when infusion is ready and after infusion is started, without any stabilizers, abacus says stability drop to -1 in this setup.
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/47838758/920eceb5-5fec-46ce-a650-26795b595af9)
Unknown aspect. In this case the infusion is now perma-stuck. This seems to happen only when using the interceptor. Some item is destroyed/missing due to instability event, and this unknown is added after item absorbing has begun.
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/47838758/d8342a95-2bfa-43dd-9fd9-ca72ab60dda3)

### Solution
This really is just a general advice for infusion: add (many) infusion stabilizers. I personally never had issues with stuck infusion after having many stabilizers. For extra read, using Infusion claw further [adds instability](https://github.com/GTNewHorizons/Gadomancy/blob/master/src/main/java/makeo/gadomancy/common/blocks/tiles/TileInfusionClaw.java#L347).
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/47838758/9ebc9d81-d794-42c3-9e69-777b506203b8)

### For the Recipe Issue...
If this randomized aspects behaviour is kept, it is probably a good idea to add the max aspects to the recipe (likely because reading of RandomizedAspectList is not handled), but readers of Thaumonomicon should be also notified that the required aspects are randomized every infusion, between max and half of max.
