### ISSUE TITLE
when u double a pattern, quit terminal and come back, liquid stays as 2x but items goes back to 1x

### ISSUE THREAD

**Issue by miaowwwwww** [GTNewHorizons/GT-New-Horizons-Modpack#15605]
### Your GTNH Discord Username

MIAOW246

### Your Pack Version

2.6.0 build 3.6.1

### Your Server

zeta

### Java Version

Java 8

### Type of Server

None

### Your Expectation

item stay as 2x as well

### The Reality

 items goes back to 1x

https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/49871378/0868a827-f63f-4984-bc1d-8f60b9240c80

(if video doesn't play normally in gh, u can download)

### Your Proposal

make ae remember the numbers.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by oier-namespace-std** [comment]
Can reproduce in 2.5.1.


I guess the problem is that AE2FC tried to save changes on doubling pattern but AE2 didn't, thus resulting in a weird pattern. (If you double an item processing pattern then re-enter the terminal, it will be completely reverted to 1x)


So I think the solution is to synchorize the behavior of pattern doubling in AE2 to AE2FC, or conversely... depending on what the dev team thinks.
