### ISSUE TITLE
Pulling item with >2^31 in AE into subnet via ME IO port pulls too much

### ISSUE THREAD

**Issue by fluffle** [GTNewHorizons/GT-New-Horizons-Modpack#15916]
### Your GTNH Discord Username

fluffle

### Your Pack Version

2.5.1

### Your Server

private server

### Java Version

Java 21

### Type of Server

Vanilla Forge

### Your Expectation

This is a bit complicated, please bear with me. 

I have come up with a riff on @S4mpsa's universal automation to do stocking of EBF ingots. It uses partitioned drives (usually 4k/16k) filled by IO ports on an **input** subnet and moved with conduits into drives on **EBF** subnets with stocking buses pulling from them. Drive movement is triggered by level emitters pointed at conduits, one per ingot type.

The **input** subnet has a storage bus on extract-only to my main net, where all the dusts are. I recently extended this system to add storage to **input** itself, so I could add mixers that output level-emitter-maintained stocks of alloy dusts to this net without polluting my main network.

Since nothing is yet outputting to the increasingly-poorly-named **input** subnet, I *expected* that the storage drives on this network to remain clear of items until I started writing to them.

### The Reality

When a drive partitioned to contain an item *of which I have >2^31 of in my main network* is moved into the IO port so that it can be filled with that item, the storage drives on the **input** subnet are filled with that item as well. This does not appear to occur if there are fewer than 2^31 items.

I have validated that 2,136,561,636 does not cause the problem but 2,162,912,855 does so I am pretty sure it's 2^31 that is the problem.

I have not (yet) gone to dig out the ME IO port code, but I recall that AE has had to have other int32 hardening in the past so I was wondering if someone with more experience with the AE codebase might have a clue as to why this is happening.

### Your Proposal

I would like the IO port not to randomly fill other drives in its subnet with items when it is set to "move from network to drive".

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by tomprince** [comment]
I can't reliably reproduce this in 2.5.1 or 2.6.0 beta 2 with the following setup:                                                                                                                                                            
- storage drawer with creative vending upgrade containing some item (in this case fluix smart cable)                                                                                                                                          
- storage bus attached to drawer                                                                                                                                                                                                              
- empty disk drive                                                                                                                                                                                                                            
- interface                                                                                                                                                                                                                                   
- storage bus in extract only mode attached to interface                                                                                                                                                                                      
- IO port with                                                                                                                                                                                                                                
  - quantum cell partitioned to the item in the drawer                                                                                                                                                                                        
  - max accel cards                                                                                                                                                                                                                           
  - transfer direction to storage cell                                                                                                                                                                                                        
- disk drive with unpartioned quantum cell                                                                                                                                                                                                    
- neutronium energy cells attached to each network for power.                                                                                                                                                                                 
                                                                                                                                                                                                                                              
I also tried (on 2.5.1) with two storage drawers instead of one, and with 2 and 3 filled quantum storage cells in the first network.                                                                                                          
                                                                                                                                                                                                                                              
Note: I did seem to reproduce the described behavior once on 2.5.1, but could not reproduce it when I put in fresh drives to the system.                                                                                                      
I suspect that either:                                                                                                                                                                                                                        
- I inadvertently put a cell with items into the drive on the second network, and mistook the drive emptying for the drive filling.                                                                                                           
- I inadvertently switched the transfer direction on the IO port (perhaps by breaking and replacing it), causing it to empty into the second network for a time.

**Comment by fluffle** [comment]
Sorry, I didn't have time to produce a minimal test case before. Here's one now from a 2.5.1 testing world.

[2024-04-05-09-48-50.zip](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/14882532/2024-04-05-09-48-50.zip)

Notable differences to the test case outlined above:

- Filling partitioned **4k** cells instead of quantum cells.
    - This means there are still >2^31 items in the "main" net after filling the cell.
- Filling from digital singularities with >2^31 items (Nb in this case has ~200k more than 2^31).
    - Storage drawers only expose 2^31-1 items to the network so may not trigger the bug.
    - Not sure if using multiple drawers would trigger the bug, because if it's an int32 problem adding more drawers adds more 2^31-1's and this probably doesn't mean much due to overflow behaviour...
    - Interestingly, as the item count increases past 2^31, the drives on the subnet fill more.
- Stocking subnet only has **16k** drives.
     - Probably not meaningful but they fill more easily and show red => bug is easily observable.

All you should need to do to observe the bug is take the 4k drive partitioned to Niobium out of the tiny chest and put it into the right-hand IO port on the stocking subnet. https://imgur.com/a/rB1PhKt

Doing the same thing with the Yttrium-partitioned drive does not cause the drives to fill.

**Comment by tomprince** [comment]
I am able to reproduce it (on 2.6.0 beta 2) with a smaller drive. Without the drives there, the excess items would just be voided.

Based on the code, and some testing, it appears that the relevant detail is that the destination cell not have any of the given item on it, and that the IO port be able to more than fill it in a single operation. The drive on the subnet was also 
irrelevant, but caused the issue to be more visible. 

The codepath for adding a new item to a cell would return an incorrect amount of rejected items, when given a stack >2^31. That would cause the IO port to try to add more items to cell than would fit on the cell. The excess items would be injected back into the network, silently voiding them if they didn't fit.
