### ISSUE TITLE
CraftPresence sometimes stalls pack loading, possibly completely halts.

### ISSUE THREAD

**Issue by AbdielKavash** [GTNewHorizons/GT-New-Horizons-Modpack#15971]
### Your GTNH Discord Username

Abdiel Kavash

### Your Pack Version

2.6.0-beta-2

### Your Server

SP

### Java Version

Java 21

### Type of Server

Single Player

### Your Actions

Launch the pack via Prism launcher.

Occasionally, CraftPresence errors out with the following sequence of messages:

```
[06:38:50] [CraftPresence/ERROR] [craftpresence]: Unable to connect to Discord...
[06:38:50] [CraftPresence/INFO] [craftpresence]: Attempting to connect to Discord (7/10)...
[06:39:20] [CraftPresence/ERROR] [craftpresence]: Unable to connect to Discord...
[06:39:20] [CraftPresence/INFO] [craftpresence]: Attempting to connect to Discord (8/10)...
[06:40:00] [CraftPresence/ERROR] [craftpresence]: Unable to connect to Discord...
[06:40:00] [CraftPresence/INFO] [craftpresence]: Attempting to connect to Discord (9/10)...
[06:41:00] [CraftPresence/ERROR] [craftpresence]: Unable to connect to Discord...
[06:41:00] [CraftPresence/INFO] [craftpresence]: Attempting to connect to Discord (10/10)...
[06:42:00] [CraftPresence/ERROR] [craftpresence]: Unable to connect to Discord...
[06:42:00] [CraftPresence/ERROR] [craftpresence]: Unable to connect to Discord...
```

Note the timestamps, it attempts to reconnect in several up to a minute-long intervals. During this entire time the main game window is uninteractible (greyed out in Windows). Sometimes this recovers after several minutes; sometimes the game just hangs indefinitely and needs to be killed via the OS.

This does not happen every time, but often enough to be noticeable.

### Crash Report

https://mclo.gs/uEMMTrA

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by Glease** [comment]
try a thread dump. it's hard to be sure it's indeed craftpresence. I've noticed short period of unresponsiveness after main menu is reached even without craftpresence, but it has never reached "several minute", usually just couple of seconds

**Comment by CDAGaming** [comment]
The logging mentioned here is intentional. It represents that CraftPresence (MC) failed to connect to a discord client. In recent versions of CraftPresence, exponential backoff logic was added to allow for re-attempting connections, designed to be useful in cases where one is restarting the discord application or brief bouts of internet connection interruptions (Both were common feedback requests and issues users had, esp. those with less reliable connections).

As a reminder and has been stated several times on the GTNH discord, CraftPresence handles the majority of its operations within its own threads, and it shouldn't be possible for any part of the mod to lock up the game (Especially not for several minutes, as an issue that severe would have appeared on my radar and reproduced by now by multiple users).

With that being said, I believe there is enough reasoning to believe CraftPresence is not at fault here, though there is room for my statement to be incorrect if further evidence proves otherwise. I'll keep my eyes out on this for now in the meantime.

**Comment by AbdielKavash** [comment]
Just wanted to copy my reply from Discord here so that it is not lost:

> [10:57 PM]Abdiel Kavash: Thanks for the reply, this makes sense! I think what's going on then is something else is a cause for the hangup, and since CP uses its own thread, it continues printing its messages into the logs, while the client is already stalled. Which makes it (wrongly) look like it is the cause. 
> [10:59 PM]CDAGaming | CraftPresence: Exactly! I designed CraftPresence as an optional client-sided mod, and an optional mod should never have the capability to lock up/crash/interfere with the main game experience -- I designed it to be plug-and-play so it wouldn't be that noticable or interfering.
> 
> It would actually be quite difficult in normal operations to have CraftPresence lock up the main thread or even cause a game crash for that matter,
> v2 did a number on past cases of that and did its job in locking things down to its own threads.
> 
> It would be immensely impressive if someone managed to acheive that in the modern v2.3.x versions xD 
> [11:00 PM]Abdiel Kavash: I have removed it from my pack now (absolutely no offense), if I get the stall again that will definitely prove it is not at fault whatsoever.

Closing this as CNR for now, will reopen with more data if I get the problem again.

**Comment by Qian-F** [comment]
I have the same issue. MultiMC+java21+2.6.0
