### ISSUE TITLE
Fluid storage bus works bad with Fluid level emitter nearby

### ISSUE THREAD

**Issue by FireWarrior2** [GTNewHorizons/GT-New-Horizons-Modpack#16039]
### Your GTNH Discord Username

fire.warrior

### Your Pack Version

2.5.1

### Your Server

SP

### Java Version

Java 8

### Type of Server

Single Player

### Your Expectation

Fluid level emitter won't affect fluid storage bus with same fluid nearby .

### The Reality

Fluid storage bus near fluid level emitter with same fluid stops working if fluid level emitter changes its condition:
https://youtu.be/vNGpOs0Long
It can't even use "Partition storage" button to lock fluid.
Nothing similar happens to item analogues. 
Also, if different fluids are set, bug is not reproduced.

### Your Proposal

Fix this bug.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by hiroscho** [comment]
Note: While I was able to describe how this error comes to be I do not have any good idea how to fix this so someone with more knowledge of ae2fc this should take a look at it.

This seems to be caused by the full reset when updating the tile entity.
During the full reset of the fluid storage bus the internal handler is recreated. Before returning the created internal handler a cell update is executed. This cell update causes the `fluidMonitor` to be force updated which causes the `hasChanged` variable for the monitor to be set to true. If any of the following listeners now accesses the `storageList` of the monitor the stored item will be set to an amount of 0 since the cachedList is reset. 
The wrong amount is then also retrieved during the full reset which causes the changes in amount to be propagated.

Here is an easier setup to reproduce this which will keep triggering the bug
https://github.com/user-attachments/assets/17e2bdbf-f917-4ed1-8f9b-1719fceada85

**Comment by hiroscho** [comment]
https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/16925 is potentially related
