### ISSUE TITLE
Allow molten lead and silver to be poured to ingot cast

### ISSUE THREAD

**Issue by hron84** [GTNewHorizons/GT-New-Horizons-Modpack#16044]
### Your Pack Version

2.5.1

### Your Proposal

I bought few Native Lead Clusters and Native Silver Clusters from one of my visitor Pech Foragers. I value it so much so I put it into my smeltery, however I cannot pour it to lead ingots because there is no recipe for it. Would you mind if it is possible to let us pour these valuable materials into ingot form to be stored later usages?

### Your Goal

Molten Lead and Silver is useless especially if it isn't a worth of bucket. It is laying in the smeltery and occupies space.

### Your Vision

Pech foragers are important part of Thaumcraft. The business with them can lead to precious (or otherwise hard-to-obtain) items in exchange for an useless gold armors / weapons dropped by the mobs.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by DarkYuan** [comment]
I second this suggestion. Didn't even realize it was useless until I tried to pour it.

**Comment by BlueHero233** [comment]
This would break progression, lead and silver are supposed to be locked in LV age
theres a only a handful of metals that can be processed in the smeltery, it says so on the controller tooltip

**Comment by BlueHero233** [comment]
Im saying casting lead and silver ingots from the tinkers smeltery would break progression if you can get native clusters before LV age
The "molten silver" and "molten lead" added by tinkers dont function interchangeably with gregtech, you cannot even cast them into tool parts anyways, only way to get them is with TIC extrusion in MV

**Comment by LazyFleshWasTaken** [comment]
> Im saying casting lead and silver ingots from the tinkers smeltery would break progression if you can get native clusters before LV age The "molten silver" and "molten lead" added by tinkers dont function interchangeably with gregtech, you cannot even cast them into tool parts anyways, only way to get them is with TIC extrusion in MV

Again. How does this break progression, when you can smelt native clusters in a normal furnace? You can also macerate them in a steam macerator for 22 tinyt dust, which you can then, again, smelt in a normal furnace.

The reason there is a desire for being able to cast molten lead and molten silver is because otherwise it is stuck in the smeltery, useless. Not because its the only way to process it.

**Comment by Miklebe** [comment]
For context, out of 7 native clusters added by thaumcraft, 1 can't be used in smeltery (cinnabar), 2 can be used for everything (copper, iron), 2 can be used for various crafts or at least casted into ingots (gold, tin), and silver/lead can't be used in anything except bucket. 
In smeltery they make exactly 3 ingots, which is more than fluid extracting/macerating/furnace, but less than infernal blast furnace.

Progression part is weird since if user got it before going to Twilight, where silver and lead ore vein is, player can still smelt it in the vanilla furnace for 2 ingots instead of 3, or crush it in steam macerator for 2.5 ingots in small dust form.

**Comment by DarkYuan** [comment]
> The "molten silver" and "molten lead" added by tinkers dont function interchangeably with gregtech
It's fine if they're not interchangeable with gt fluids, but they could still cast in a smeltery without changing that.

**Comment by chochem** [comment]
the tinker lead is gone by the way. only gt now. so this is only about silver

**Comment by DarkYuan** [comment]
For more context, the ingots are already obtainable by smelting the clusters in a furnace. It's not the casting that would be breaking progression, if you see it as such, it would be the clusters from pechs.

**Comment by hron84** [comment]
Not just pechs. Basically, the clusters are in one of the Thaumcraft loot tables and sometimes TC lootbags also give you some clusters - altough it is much rarer than Pech trades. I personally do not see a progression break if you could obtain the ore cluster. If we do not want to the clusters be able to converted to ingot, then we should disable furnace and smeltery smelting to ingot/fluid and only keep the macerator recipes (since it basically locks it behind at least steam age).

**Comment by Undercoverer** [comment]
I have a 500 ingots of now worthless silver I just mined from the twilight forest in my smeltery. WHY is it being ingot castable not planned? If it's not supposed to be used in a smeltery, why are there recipes for it in the first place? No mention in the questbook either
