### ISSUE TITLE
Crash while mining naga blocks in TF

### ISSUE THREAD

**Issue by raellol** [GTNewHorizons/GT-New-Horizons-Modpack#16061]
### Your Pack Version

2.6.0-beta-2

### Your Server

Private server

### Java Version

Java 21

### Type of Server

Don't know

### Your Actions

i was mining naga blocks in the twilight forest. I get these crashes sometimes but not always, i don't know whether its the blocks i mine or the block behind them that cause the issue.

### Crash Report

https://mclo.gs/1uO6ZZh

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by sim2kid** [comment]
I am also consistently getting this crash as well.
In my case, I got the crash before mining while fighting the Naga (it was destroying blocks as well though).
Here are my logs for reference:
https://mclo.gs/6GasFug

**Comment by Flincae** [comment]
Since it was naga blocks in the crash message I put this here, but for me it was the server that crashed, not just the client.  I was exploring doing the kill quest not breaking blocks.  After first restart of the server, I crashed again in maybe 30sec to 1 min.  The second time, I ran back to my miner and it seems fine.  Server version: 2.6.0.  Server was updated from 2.3.0 on 02May2024. 
[crash-2024-05-06_11.11.25-server.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/15225270/crash-2024-05-06_11.11.25-server.txt)
[crash-2024-05-06_11.20.22-server.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/15225272/crash-2024-05-06_11.20.22-server.txt)

**Comment by Kyuuketsuki** [comment]
This also appears to be happening when a naga breaks blocks while fighting them, making this a progress blocker for the magic branch. If you try to reload the game at this point, it will almost instantly crash again.

Disabling mobGriefing does not appear to prevent nagas from doing this block breaking.

https://mclo.gs/By97wyn

**Comment by BlueHero233** [comment]
Have you updated Twilight Forest to 2.6.12?

**Comment by sim2kid** [comment]
@BlueHero233 
> Have you updated Twilight Forest to 2.6.12?

No. Both `2.6.0` and `2.6.1` run on Twilight Forest `2.5.23` and `2.5.25` respectively. 

It looks as though `2.7.0-beta-3` does run Twilight Forest `2.6.34`, so it may be fixed in that version. 
Testing will need to be done to confirm so. 

The crash is pretty reliable just be fighting the Naga on the 2.6.0 version of the pack.

It looks like this issue was addressed in the [twilightforest branch in PR #68](https://github.com/GTNewHorizons/twilightforest/pull/68) which was released with TF `2.6.9`.

**Comment by chochem** [comment]
thats because your issue is not the one in this ticket

**Comment by Enderithe** [comment]
This specific issue is due to the north-facing variant of the etched nagastone. It should only trigger when you pick up that block.

**Comment by Lyfts** [comment]
No, this particular crash is not related to yours in https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/17753.

**Comment by Flincae** [comment]
> Have you updated Twilight Forest to 2.6.12?

I did update my server/clients running 2.6.1 to run Twilight Forest 2.6.12 and it fixed our issue.

**Comment by BlueHero233** [comment]
Awesome
