### ISSUE TITLE
LSC can crash the server

### ISSUE THREAD

**Issue by boubou19** [GTNewHorizons/GT-New-Horizons-Modpack#16124]
### Your GTNH Discord Username

boubou_19

### Your Pack Version

2.6.0

### Your Server

eta

### Java Version

Java 8

### Type of Server

Thermos

### Your Actions

A player logged in his base after the update, expecting everything to be fine.

### Crash Report

[crash-2024-05-01_21.40.07-server.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/15180718/crash-2024-05-01_21.40.07-server.txt)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by boubou19** [comment]
https://github.com/GTNewHorizons/KekzTech/blob/59a09c23eff3d3bba9577eececf45a6fd3deb022/src/main/java/common/tileentities/GTMTE_LapotronicSuperCapacitor.java#L917

**Comment by jimgo514** [comment]
Met this too after I update from 251 to 260.
I remove ic2 nuclear control to solve it.
After some testing, I realize it's because I use GT sensor card on a single LRC controller to read wireless energy.
Put a sensor card whitch bind to a LRC controller into a information panel will instantly crash.
The Metrics Transmitter Cover don't crash, just sensor card do.

my server's crash report:
[crash-2024-05-01_13.39.18-server.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/15183905/crash-2024-05-01_13.39.18-server.txt)
