### ISSUE TITLE
Hard server crash on use of GT sensor kit in empty and/or unformed LSC

### ISSUE THREAD

**Issue by ogdae** [GTNewHorizons/GT-New-Horizons-Modpack#16167]
### Your GTNH Discord Username

rilliko

### Your Pack Version

2.6

### Your Server

Private Community Server

### Java Version

Java 21

### Type of Server

Vanilla Forge

### Your Actions

Hard tick exception crash was caused by a player on the server placing a GT sensor that had been programmed against a non formed LSC, into an advanced information sensor panel. Restoring the personal dimension folder from a backup to roll back fixed the issue.

### Crash Report

[crash-2024-05-05_09.44.08-server.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/15211362/crash-2024-05-05_09.44.08-server.txt)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [X] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by Darkmaxsas** [comment]
It seems this does still occur,
i had a completly formed an working LSC until it just decided to unform for whatever reason (i had a small time window to inspect it for damages but found nothing). 5min after unforming the server crashed with the same crash listed in this issue.
I am on Pack Version 2.6.1 and my Server is running Java 19 
The crash:
[crash-2024-07-15_02.27.08-server.txt](https://github.com/user-attachments/files/16229238/crash-2024-07-15_02.27.08-server.txt)

since this occured iam unable to restart the server, since it always crashes with the same error once its finished loading

**Comment by Darkmaxsas** [comment]
well, it seems it has been fixed, but the version shipped with the latest 2.6.1 still has a version of kekzTech were the crash persists.
Updating to the newest version of kekzTech fixed the Issue
