### ISSUE TITLE
java.lang.IllegalStateException: Already tesselating!

### ISSUE THREAD

**Issue by ReaganAR** [GTNewHorizons/GT-New-Horizons-Modpack#16183]
### Your GTNH Discord Username

shimmeringcircuits

### Your Pack Version

2.6.0

### Your Server

private server

### Java Version

Java 21

### Type of Server

Vanilla Forge

### Your Actions

Have encountered in various situations: (i.e. sitting afk watching an apiary and using an AE2 ME system)

This has happened with both plain 2.6.0 as well as changing to [the most recent AE2 release](https://github.com/GTNewHorizons/Applied-Energistics-2-Unofficial/releases/tag/rv3-beta-400-GTNH), if that matters

### Crash Report

[crash-2024-05-05_15.28.58-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/15214509/crash-2024-05-05_15.28.58-client.txt)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by Caedis** [comment]
Post your fml-client log file

**Comment by ReaganAR** [comment]
[fml-client-latest(1).log](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/15214537/fml-client-latest.1.log)

**Comment by ReaganAR** [comment]
Crash happened again, while doing bee stuff, but fml log says it was rendering an ender pouch this time.
[crash-2024-05-06_17.55.00-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/15227398/crash-2024-05-06_17.55.00-client.txt) 
[fml-client-3.log](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/15227400/fml-client-3.log)

**Comment by Noktuska** [comment]
I seem to be running into the same or a similar issue. I've attached 4 different log files, for me the culprits are QuantumSuit Armor parts, the helmet which has a gadomancy disguise applied and another one I cannot make out but has the NBT Tag "wasOnGround" (maybe the leggings for the boost?). Issue seems to be related to `net.minecraft.client.renderer.entity.RenderItem.renderItemAndEffectIntoGUI` and has been happening since the 2.6.0 update.
Crash doesn't seem consistently reproducable, happens very sporadicly while afking/running around (at least I don't notice a pattern). It's very annoying because the Tesselator cannot be reset resulting in an infinite loop forcing me to completely close the game.
The related lines are:
-latest.log - line 8120
-2024-05-09-2 - line 31355
-2024-05-09-3 - line 13589
-2024-05-10-1 - line 645
[2024-05-09-2.log](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/15281157/2024-05-09-2.log)
[2024-05-09-3.log](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/15281158/2024-05-09-3.log)
[2024-05-10-1.log](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/15281159/2024-05-10-1.log)
[latest.log](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/15281160/latest.log)
