### ISSUE TITLE
Removal of the explosion from the Active transformer

### ISSUE THREAD

**Issue by Reflex18** [GTNewHorizons/GT-New-Horizons-Modpack#16245]
### Your GTNH Discord Username

Reflex18#9829

### Your Pack Version

2.6.0

### Your Proposal

I propose that the Active transformer (AT) should not explode on breaking it while it is running or just the superconductor inside it should be removed.

### Your Goal

The goal for such a change is that the AT explosion in many cases is a great enough punishment that players instead just request a roll back from an admin taking up admin bandwidth or just results in a backup in a solo player environment.

Therefore the punishment itself is large enough that players simply load a backup rather then dealing with it.

### Your Vision

I hope that the change would move it from a total punishment to a more tolerable one if the explosion mechanic was reduced or if it was just completely removed. I truly believe that the player in the end is just walking on egg shells with the transformer and if they mess up its just an annoying load backup time that ultimately does not add anything to the game.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Rami114** [comment]
The only 2 multis that actually use `eDismantleBoom` are:
- Active Transformer
- Energy Infuser

Looking at `doExplosion` in https://github.com/GTNewHorizons/TecTech/blob/master/src/main/java/com/github/technus/tectech/thing/metaTileEntity/multi/base/GT_MetaTileEntity_MultiblockBase_EM.java#L1750:
- causes an explosion for each e-hatch/dynamo hatch/maint hatch/in-out hatch/etc in the multi of size `MAX_INT`
- adds one extra `MAX_INT` explosion at the end for good measure

I suppose the Infuser isn't used anywhere near as much or deconstructed whilst running, so people have just noticed it a lot with the AT. 

We could either:
A) Tweak the explosion values down in `GT_MetaTileEntity_MultiblockBase_EM.java` directly, affecting both multis (since I suspect the infuser will explode rather grandly too)
B) Override `explodeMultiblock` on the AT specifically to be less drastic

Option A sounds better given this affects 2 multis, one of which is obscure and rarely used and the other is the source of frustration for any player that has a boom. 

Setting the explosions to `V[8]` would dramatically reduce it, and be a simple change. 

Whilst we could consider to have each hatch explode according to its own `V` tier and then explode once more for good measure at size `V[8]`, at lategame we'd be back to `MAX_INT` explosions and this is where spam happens. So this isn't recommded.

Anything above 8 is `MAX_INT`, so that feels like the ceiling to aim for

**Comment by Rami114** [comment]
Needs confirmation, but MAX_INT explosions translate to ~15 block radius explosions (so the whole chunk goes).

We need to test what kind of radius `V[8]` and below approximately map to and find a suitable size
