### ISSUE TITLE
Nature's Compass cause crash

### ISSUE THREAD

**Issue by DarkAhri** [GTNewHorizons/GT-New-Horizons-Modpack#16311]
### Your Pack Version

2.6.0

### Your Server

SP

### Java Version

Java 17

### Type of Server

None

### Your Actions

Trrying use nature's compass,click "search",then game crash.
It can be used normally in Java 8 environment.

### Crash Report

https://mclo.gs/HO4LOVY

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [X] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by Dream-Master** [comment]
@DarkAhri try to use https://github.com/GTNewHorizons/NaturesCompass/releases/tag/1.4.1-GTNH-pre

**Comment by DarkAhri** [comment]
> @DarkAhri try to use https://github.com/GTNewHorizons/NaturesCompass/releases/tag/1.4.1-GTNH-pre

still crash

**Comment by Dream-Master** [comment]
same crash ? @DarkAhri

**Comment by Dream-Master** [comment]
try to use this version as well <https://github.com/GTNewHorizons/Angelica/releases/tag/1.0.0-alpha50>

**Comment by DarkAhri** [comment]
> same crash ? @DarkAhri 

Yes

**Comment by DarkAhri** [comment]
> try to use this version as well <https://github.com/GTNewHorizons/Angelica/releases/tag/1.0.0-alpha50>

After replacing the mod, it still has no effect.

**Comment by DarkAhri** [comment]
> same crash ? @DarkAhri 

yes

**Comment by DarkAhri** [comment]
Amazingly, in 2.6.1, it worked normally

**Comment by SeseMueller** [comment]
I won't reopen this issue because relaunching GTNH fixed it; but I want to point out that this exact error happened to me again, in 2.7.2: https://mclo.gs/KNcEFBt

Interestingly, when I just went to the title screen and tried to go back, it would crash to title screen again.

Also note that I was using the compass fine for quite some time in the overworld, but wanted to use it in the twilight forest right after loading it for the first time in ages and after updating, causing the crash. Maybe it requires the dimension to be loaded for some time?
