### ISSUE TITLE
Crash when entering certain area in overworld

### ISSUE THREAD

**Issue by ShenRedfield** [GTNewHorizons/GT-New-Horizons-Modpack#16531]
### Your GTNH Discord Username

kami_no_kotoba

### Your Pack Version

2.6.1

### Your Server

sp

### Java Version

Java 8

### Type of Server

Single Player

### Your Actions

When entering a certain area in overworld i get a crash. Tried playing via CurseForge and MultiMC. No difference.
1st crash report - curseforge
2nd - MultiMC

### Crash Report

[crash-2024-06-13_19.26.46-server.txt](https://github.com/user-attachments/files/15825489/crash-2024-06-13_19.26.46-server.txt)
[crash-2024-06-13_18.41.47-server.txt](https://github.com/user-attachments/files/15825509/crash-2024-06-13_18.41.47-server.txt)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by ah-OOG-ah** [comment]
What seed is your world using, and did you change the worldgen (with RTG+CC or something) or is this just the normal, unmodified pack?

**Comment by toastin0** [comment]
hey there! i'm also experiencing this crash.  in my personal experience, this is linked to a region file seemingly being wiped.

 just before the crash in my log, i found (after 8k lines of java exceptions, idk how java traces are both so verbose and tell you nothing) 
```
[20:49:50] [Server thread/INFO] [Hodgepodge/]: NULL chunk found at 0, 9, 15, returning Blocks.air
[20:49:50] [Server thread/INFO] [Hodgepodge/]: NULL chunk found at 15, 9, 15, returning Blocks.air
[20:49:52] [Server thread/INFO] [Hodgepodge/]: NULL chunk found at 15, 8, 8, returning Blocks.air
[20:49:53] [Server thread/FATAL] [Hodgepodge/]: Tile entity of type gregtech.common.blocks.GT_TileEntity_Ores (jar:file:/mnt/windows_drive/Users/<NAME OMITTED>/AppData/Roaming/PrismLauncher/instances/GT-NH%202.6.1(1)/.minecraft/mods/gregtech-5.09.45.168.jar!/gregtech/common/blocks/GT_TileEntity_Ores.class) reports coordinates of (-1216, 49, 1700) that lie outside of the bounds of chunk (x=-66, z=112) in dimension 0 - ending up with illegal in-chunk coordinates of (-160, 49, -92).
```
i crashed, and then restarted my game and carried on as normal, seemingly perfectly fine. however, when serverutils tried to backup, i got a solid error, and so I checked out the file it was complaining about, and, well: 
```
toast@boykisser-arch /m/w/U/S/A/R/P/i/G/.m/s/n/region> stat r.-3.3.mca
  File: r.-3.3.mca
  Size: 0               Blocks: 0          IO Block: 4096   regular empty file
Device: 259,2   Inode: 273899      Links: 1
Access: (0777/-rwxrwxrwx)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2024-07-08 11:03:10.185392700 -0400
Modify: 2024-07-09 20:48:23.779871900 -0400
Change: 2024-07-09 20:48:23.779871900 -0400
 Birth: -
```
it's gone. like, empty file, gone. this seems like an extraordinarily bad bug. i'm almost certain it isn't a drive issue, since this has happened to me twice, and only appears to happen to region files, and no other files in my filesystem. i've posted my logs [here](https://mclo.gs/g1ok6Kl). i omitted about 40k lines of nonsense that was just from me playing the game, leaving about 10k lines, of which i estimate around 9k are java exceptions, so look at this at your own risk.

please let me know if you need any more info! i can also be reached on discord with the username toastino.

**Comment by DemonDol** [comment]
I got confused and spent about 4 hours studying articles, but didn’t really find anything, but I solved this problem, although I need to remember how ':) I’ll describe the solution later, but I warn you: new crashes appear with this reason, but I think they can be solved
