### ISSUE TITLE
LFTR (Thorium Reactor) generates free energy during warm-up

### ISSUE THREAD

**Issue by gabriel-legros** [GTNewHorizons/GT-New-Horizons-Modpack#16584]
### Your GTNH Discord Username

Thratur#8432

### Your Pack Version

2.6.1

### Your Server

SP

### Java Version

Java 8

### Type of Server

Single Player

### Your Expectation

When turned on via a machine controller cover after a first successful run (which ran as expected), the LFTR warms up.  I expect one of the followings during warm-up : either generate no energy at all during warm-up, as it did on the first warm-up, and consume no fuel or to consume the fuel immediately and start generating energy either immediately scaled to efficiency.

### The Reality

![LFTR_free_energy](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/90198722/219174f8-e0b7-43bd-8be6-d6c78eba280c)
As it warms up, the LFTR generates energy, but consumes no fuel during warm-up.  If warm-up is interrupted for any reason (in my case, a redstone signal due to a filled up battery), the warm-up begins again, and the LFTR continues generating free energy.

While I was not able to ask anyone about it, I found confirmation of the bug from some old comments on the Discord.

### Your Proposal

I propose the LFTR should generate no energy whatsoever during warm-up, as it does on the initial warm-up.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by a3626a** [comment]
I have found this bug recently, under similar setup. 
![image](https://github.com/user-attachments/assets/e1f6925f-0fd1-42ca-8256-bcb4d97046b8)


There are two directions for this problem.

1) Make the reactor not produce power during warm-up.
2) Make the reactor consume and produce items and power during warm-up. 

As you suggested `1)` I tried to fix to follow 1). (`2)` might nerf the LFTR too much.)




Critical trigger to this bug is stopping machine intentionally, like using soft hammer, machine controller.

This intentional stopping prevent machine to reset its internal state, which causes this bug.


Following is the reset code for 'intentional stopping'
https://github.com/GTNewHorizons/GT5-Unofficial/blob/933650dd0a1267e8a33b686f8262300111d94acd/src/main/java/gregtech/api/metatileentity/implementations/GT_MetaTileEntity_MultiBlockBase.java#L561-L564

This is the reset code for 'emergency stopping'
https://github.com/GTNewHorizons/GT5-Unofficial/blob/933650dd0a1267e8a33b686f8262300111d94acd/src/main/java/gregtech/api/metatileentity/implementations/GT_MetaTileEntity_ExtendedPowerMultiBlockBase.java#L86-L90

https://github.com/GTNewHorizons/GT5-Unofficial/blob/933650dd0a1267e8a33b686f8262300111d94acd/src/main/java/gregtech/api/metatileentity/implementations/GT_MetaTileEntity_MultiBlockBase.java#L933-L950



fix 1) Call stop machine here (else statement)
https://github.com/GTNewHorizons/GT5-Unofficial/blob/933650dd0a1267e8a33b686f8262300111d94acd/src/main/java/gregtech/api/metatileentity/implementations/GT_MetaTileEntity_MultiBlockBase.java#L566-L568

fix 2) Set `letu = 0` here
https://github.com/GTNewHorizons/GT5-Unofficial/blob/933650dd0a1267e8a33b686f8262300111d94acd/src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/production/GregtechMTE_NuclearReactor.java#L415-L416


I will test in my server soon.
