### ISSUE TITLE
Ordering in wireless terminals (universal or crafting, at least) crashes either Server or Client only

### ISSUE THREAD

**Issue by OmdaCZ** [GTNewHorizons/GT-New-Horizons-Modpack#16769]
### Your GTNH Discord Username

ondrejmenzel

### Your Pack Version

nightly 543

### Your Server

Private server

### Java Version

Java 21

### Type of Server

Vanilla Forge

### Your Actions

I tried ordering Void Miner III controller through one and it crashed

### Crash Report

[fml-client-latest.log](https://github.com/user-attachments/files/16254488/fml-client-latest.log)
[fml-server-latest.log](https://github.com/user-attachments/files/16254480/fml-server-latest.log)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [X] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by Ruling-0** [comment]
Adding on - I am also experiencing a crafting-related quest on nightly 553. Logs look similar. Things I have gathered
- Specific item/mod appears to not matter - tested with HV transformer and vanilla gold helmet
- It happens most with attempting to ctrl-click the ? icon in NEI, which requests AE2 craft missing components for a recipe
- It only occurs when another craft is running - tried with a softlocked (improper blocking mode) ME stocking input hatch craft and crafting 256 formation cores in a molecular assembler (had no subcrafts running)
- I was unable to cause a crash for the same item in the same situation using a normal pattern craft instead of NEI ctrl-click, but I had a friend who apparently was able to with a normal pattern craft. I will update if I can cause this.
- Mine crashes client, but server also crashes due to ticking entity, and cites the client as the ticking entity. Mine is also being ordered through a normal crafting terminal

Server Crash: [crash-2024-07-16_20.29.22-server.txt](https://github.com/user-attachments/files/16258133/crash-2024-07-16_20.29.22-server.txt)
Client Crash: [crash-2024-07-16_20.29.23-client.txt](https://github.com/user-attachments/files/16258136/crash-2024-07-16_20.29.23-client.txt)
