### ISSUE TITLE
Pico circuits taking too much time to craft and made quest dependencies reversed

### ISSUE THREAD

**Issue by YueLengM** [GTNewHorizons/GT-New-Horizons-Modpack#16811]
### Your GTNH Discord Username

YueLeng_M

### Your Pack Version

2.6.1

### Your Server

SP

### Java Version

Java 17

### Type of Server

Single Player

### Your Expectation

Entering UIV, following the Quests.

![图片](https://github.com/user-attachments/assets/df9877eb-cd85-4f31-99f0-c90867e1373f)

![图片](https://github.com/user-attachments/assets/db6decd0-33de-4327-843b-abd455d87fae)

### The Reality

To craft Pico circuits, we need a UMV tier assembly line.

In older versions, we can use hi-amp laser hatch on a AAL to overclock to UMV.

Since it was limited, we have to use double UIV energy hatch on a normal AL. But in order to craft UIV energy hatch we need UIV motor which is the next quest.

---

Also its not following other circuits' pattern. UEV optical, UIV optical and UXV circuits all use one-tier-lower voltage to craft. UMV pico not following this pattern.

### Your Proposal

I think Pico should takes UIV voltage to craft.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by NotAPenguin0** [comment]
While not amazing, this is somewhat intentional to force you to eventually improve your AAL infrastructure to craft thousands of picos. Another reason they don't follow the standard pattern is because they're mostly placeholder circuits until a real circuit line takes their place.

Quantum circuits used to require UXV voltage, but this was tiered down to UMV because you need them in very large amounts even before UXV. I don't really think this should apply to pico circuits, since you only need relatively few of them to break into UMV and get your first UMV energy hatches going (you could get away with just 32 really, for a plasma mixer).

I do agree the quest dependency is a bit weird and could be reversed.

**Comment by YueLengM** [comment]
I fogot to mention that some UIV parts need pico to craft so its kind a loop. Maybe it's better to just remove the dependency?

**Comment by OlliedeLeeuw** [comment]
> I fogot to mention that some UIV parts need pico to craft so its kind a loop. Maybe it's better to just remove the dependency?
im removing the dependency all together yes, so UIV will need tesseract quest and UMV's will need optical mainframe and hypogen

**Comment by NotAPenguin0** [comment]
Quest issue is fixed and time won't be adjusted so this is done.
