### ISSUE TITLE
Thaumcraft bugged research

### ISSUE THREAD

**Issue by MrHeadshot-ui** [GTNewHorizons/GT-New-Horizons-Modpack#16921]
### Your GTNH Discord Username

mrheadshot

### Your Pack Version

2.6.1

### Your Server

Private Server

### Java Version

Java 8

### Type of Server

Vanilla Forge

### Your Expectation

Trying to research Thaumcraft Vis Storage research.

### The Reality

Trying to research Thaumcraft Vis Storage research, but there is a problem to reach auram point.
![image](https://github.com/user-attachments/assets/e6aae258-05d1-4a25-8e9b-02a1ef493dfe)

### Your Proposal

Repair this, pls

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Ethryan** [comment]
You ran into a chance based impossible page, I suggest deleting the page and retrying it again from the Thaumonomicon.
This sometimes happens and is intentional in my opinion.

It reflects you running into a problem during research and not having any path forward. So you have to go back to square one (Remake the page), and start over.
