### ISSUE TITLE
Loading Crash of 2.7.x nigthly (latest) due to wrong/missing JVM Args

### ISSUE THREAD

**Issue by Chaoschaot232** [GTNewHorizons/GT-New-Horizons-Modpack#17332]
### Your GTNH Discord Username

Marcel|Chaoschaot234

### Your Pack Version

GTNH Nightly build 2024-09-13+645

### Your Server

private mp server

### Java Version

Java 17

### Type of Server

Vanilla Forge

### Your Actions

I upgraded the 2.5.1 stable version to the current 2.7.x nigthly version and got then directly a nice crash report.

Resolving this is not the problem. It is more that there are no informations about these changes for this version (or already for 2.6.x?) within the Discords #faq channel. So running this wwith the old JVM Args seems not to be a good idea.

My intension here is to update the FAQ for each version with the correct JVM Args at last for newer Java Versions, thanks.

### Crash Report

https://paste.ee/p/4zFMK

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [X] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by fbfnysnshnsgnwg** [comment]
seems like a bad idea to update to a nightly

**Comment by fbfnysnshnsgnwg** [comment]
>System classloader not overwritten, add -Djava.system.class.loader=com.gtnewhorizons.retrofuturabootstrap.RfbSystemClassLoader to your JVM flags

Add this

**Comment by Chaoschaot232** [comment]
It's not the problem for me to add this argument correctly but it should be stated also with updated JVM args in the FAQ channel ;)

**Comment by Miklebe** [comment]
FAQ channel? Unless I am somehow missing it, I can't find anything (at least on discord (what channel implies))
New JVM arguments are listed in installation/migration guide on the wiki, where it's mentioned and separated: 
![Screenshot_2024-09-14-14-21-05-391_com android chrome](https://github.com/user-attachments/assets/f965943c-7623-40ce-b02e-b1c29d877673)

**Comment by Chaoschaot232** [comment]
Interesting, that they postet it there but not in the FAQ channel on discord where most ppl are ^^

Will take a look into them when I am home from work in arround 8h

**Comment by chochem** [comment]
thats just the wrong java. you downloaded modern java pack but use java 8.

**Comment by VasyaOrk** [comment]
Some experiments
0. usally i do not use launcher, instead I launch the modpack via a bat file, which generate launch string for minecraft
1. Nightly 641 : i cant run modpack client via a bat file ... ok, i run it via launcher (multimc, because i have win 7 on my PC) ... it works
2. Nightly 645 : there are no folders "patches", "libraries" in the archive, file mmc-pack.json has 3 components inside instead 5, no file lwjgl3ify-2.1.2.jar in mods folder.
ОК, i simply delete "patches", "libraries" folders from instance, replace file mmc-pack.json with new, delete old and replace with new folders "mods", "config", "resourcepacks"   ... but i can't run modpack
java arg -Djava.system.class.loader=com.gtnewhorizons.retrofuturabootstrap.RfbSystemClassLoader say
java.lang.ClassNotFoundException: com.gtnewhorizons.retrofuturabootstrap.RfbSystemClassLoader
... 
ОК
3. Only when i place folders "patches", "libraries" (from 641 version) in instance folder, flie  lwjgl3ify-2.1.2.jar in "mods" folder and file mmc-pack.json from 641 version in instance folder -  client successfully started
4. Question : in which file in modpack  a com.gtnewhorizons.retrofuturabootstrap.RfbSystemClassLoader class "lives" ?

**Comment by Lyfts** [comment]
https://gtnh.miraheze.org/wiki/Installing_and_Migrating
Sounds like you downloaded the java 8 version but just follow the guide

**Comment by Chaoschaot232** [comment]
Another update:

There seem to a problem with a changed made within this pack to some vanilla items like stone slabs because after this error I migrated from 2.5.x to 2.6.1 stable and it loaded in perfectly. After this I loaded the converted and saved world into this nightly build and here is what triggered this crash:

![image](https://github.com/user-attachments/assets/e778cb22-923d-473b-b507-04e28393b6eb)

As you can see the port flipps levers and regulare vanilla quartz slabs are turned into normal stone slabs at the wrong position. Unsure why this happends because our entire track is made out of nether quarz slabs so why where they turned into the wrong item? Sounds for me after a horrible wrong going migration bug.

here you can see that we are useing vanilla quarz slabs and not stone slabs:

![image](https://github.com/user-attachments/assets/aed8cfab-776b-4658-9812-5a11b5e17617)

**Comment by Chaoschaot232** [comment]
> thats just the wrong java. you downloaded modern java pack but use java 8.

Where have you seen this? Can you tell me this because I have downloaded the new-java packs and not the java 8 packs from the building page:

![image](https://github.com/user-attachments/assets/69c4a835-2a91-49ce-a416-eef2320cd1a8)
