### ISSUE TITLE
[OpenBSD] [FreeBSD] Game wont start, crashes

### ISSUE THREAD

**Issue by kkflto** [GTNewHorizons/GT-New-Horizons-Modpack#17554]
### Your GTNH Discord Username

kkflt

### Your Pack Version

All

### Your Server

doesnt really matter

### Java Version

Java 21

### Type of Server

None

### Your Expectation

Game works, as vanilla 1.7.10 works

### The Reality

Doesnt start, it ends with a oretty straightforward crash. Crash is the same on OpenBSD and FreeBSD. Log: https://mclo.gs/AUe6cBc

### Your Proposal

See if its possible to fix

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by kkflto** [comment]
I suspect this is the culprit `java.lang.NoClassDefFoundError: Could not initialize class org.lwjglx.LWJGLUtil`

**Comment by dvdmandt** [comment]
Does the Java 8 version work if you use Java 8?

**Comment by kkflto** [comment]
No, same thing

**Comment by kkflto** [comment]
Since I don't think its even supported, and I have never encountered someone trying to play on *BSD, I'll close this issue.

**Comment by jardhu** [comment]
@kkflt Looks like you've finally got someone else trying to play on a BSD =)

<img width="2262" height="1422" alt="Image" src="https://github.com/user-attachments/assets/15164fa5-7ef3-44b7-94aa-b9ebc784e22a" />

lwjgl3ify, the mod giving the `Unknown platform: OPENBSD` error, needs to be patched to recognize FreeBSD and OpenBSD as platforms. The issue is that the underlying lwjgl3.3.3 isn't compatible with neither FreeBSD nor OpenBSD. lwjgl3.3.4 does officially support FreeBSD which is tracked in the FreeBSD ports tree, and from what I can tell OpenBSD forked lwjgl3 to add in F+OBSD compatibility themselves. So potentially we'd need two different versions of lwjgl3ify, the first one bumping 3.3.3 to 3.3.4 to officially support FreeBSD, and the second pointing its lwjgl3 to OpenBSD's fork.

I have a [downstream lwjgl3ify](https://github.com/jardhu/lwjgl3ify) that bumps lwjgl3.3.3 to 3.3.4, this requires building the lwjgl3ify jar and moving it to the mods directory, then telling Java to look for the system-managed lwjgl3 via `-Dorg.lwjgl.librarypath=/usr/local/lib/lwjgl3`. There is a hack to detect OpenBSD because the `OPENBSD` enumeration doesn't exist in lwjgl3.3.4, but it's entirely untested because, annoyingly, 3.3.4 is ABI incompatible with 3.3.3 and I suspect OpenBSD's fork is too.
