### ISSUE TITLE
Add preconfigured storage bus / fluid storage bus

### ISSUE THREAD

**Issue by boubou19** [GTNewHorizons/GT-New-Horizons-Modpack#17821]
Context: when one has to set up in bulk setups automating item/fluid placement with precise order (typically the assline), when using AE2 you typically do this with storage buses / fluid storage buses with decreasing priority.

Current solution: the game has cards to memorise the priority settings, so you usually do the chore of building the setup, then you apply each prio with the card and repeat. It works, but setting up each storage bus is tedius.

Proposed solution: add shapeless crafting recipes with (fluid) storage bus + circuit config ranging from 1 to 24 to craft a storage bus with corresponding priority, so you cut the card setting part of the automation when done in bulk.

**Comment by lordIcocain** [comment]
Tool which place storage buses. With some modes like decrease priority by 1 until N then start with initial value and mb other useful modes. Auto apply storage bus settings like insert only etc.

**Comment by Divran** [comment]
alternative suggestion

instead of making it specific to storage buses, make a dynamic recipe where any blank ae component that has settings placed next to one or more ae component that have no settings configured will copy their settings onto that block. whether in a crafting grid or a specific machine doesnt matter. basically this would be the ability to copy settings like a memory card, but in a crafting way rather than a right click in-world way. then you could use your idea for anything rather than just storage buses

**Comment by boubou19** [comment]
it'd work, but you'd need the first one in the inv, i want the ability to precraft the first storage bus. But those ideas could coexist. Now i need to find someone knowledgeable on those advanced shapeless craft features to see how to implement this.

**Comment by EnderProyects** [comment]
Could also be added recipes for precraft p2p types? I don't think is already implemented, can't check atm
