### ISSUE TITLE
Server crash by Dreamcore OC script

### ISSUE THREAD

**Issue by StaffiX** [GTNewHorizons/GT-New-Horizons-Modpack#17931]
### Your GTNH Discord Username

StaffiX

### Your Pack Version

Nightly 730

### Your Server

private server 

### Java Version

Java 21

### Type of Server

Vanilla Forge

### Your Actions

Opened startserver-java9.bat

Downgrading the coremod version to 2.6.71 fixed the crash, so I think it's caused by https://github.com/GTNewHorizons/NewHorizonsCoreMod/pull/1049

### Crash Report

[fml-server-latest.log](https://github.com/user-attachments/files/17692387/fml-server-latest.log)
Line 27240

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by Chaoschaot232** [comment]
That's interesting as I haven't had any type of crash while I was re-adding this little fix to the pack.

Maybe something has changed between the development of this fix and it's test with the nigthly available at that time and with the current ones? Otherwise why was there no crash at that time where I did the thing and also tested it as this crash is directly at the loading stage of the game 🤔

**Comment by StaffiX** [comment]
Did you test the server version as well? Because it didn't crash with client I think

**Comment by Chaoschaot232** [comment]
No, only client sided join because the first attempt ended up in a bad dupe ones serverside and client side too.
Since there was non of the side-annotations for either client/server I didn't expected this to happen.

So maybe there would have been a need and test with a client side annotionen so that the server ignores this.
