### ISSUE TITLE
Potentially UniLib crash

### ISSUE THREAD

**Issue by ddimavo** [GTNewHorizons/GT-New-Horizons-Modpack#18244]
### Your GTNH Discord Username

wanderman_n

### Your Pack Version

2.7.0-RC3

### Your Server

SP

### Java Version

Java 8

### Type of Server

Single Player

### Your Actions

I'm trying to install the client on Gravit.Launcher, through Prism it works fine, but when I transfer the same files to Gravit - I get a crash. I attach logs, if you need more information - ask for it.

### Crash Report

[crash-2024-12-07_15.17.10-client.txt](https://github.com/user-attachments/files/18048302/crash-2024-12-07_15.17.10-client.txt)
[latest.log](https://github.com/user-attachments/files/18048303/latest.log)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by chochem** [comment]
we are neither working on gravit launcher nor on unilib.

not sure where cdagaming usually wants report but this is the website https://gitlab.com/CDAGaming/UniLib and there is a discord link among other things. I know even less about that launcher since its all in russian, no idea where they take reports.

anyway, best to just use prism, apparently everything is working fine for you there.
