### ISSUE TITLE
2.0.3.0 Cleanroom Forming Issue

### ISSUE THREAD

**Issue by Wolozo7** [GTNewHorizons/GT-New-Horizons-Modpack#2813]
Blocks don't take the right color when the Cleanroom is forming. Happens to multiple people.

![image](https://user-images.githubusercontent.com/34921674/38632056-dc8c679c-3dbb-11e8-82eb-de670d504905.png)

**Comment by bartimaeusnek** [comment]
@draknyte1 is this a GT++ issure? never saw this color of casings before

**Comment by draknyte1** [comment]
Gregtech Issue.
Don't use my IDs, won't get this issue. 

GTNH has to follow the texture/Meta allocations set by vanilla GT or else this happens.

**Comment by CalterOK** [comment]
I have the same color, but it does not interfere with a clean room.

**Comment by Technus** [comment]
https://github.com/Blood-Asp/GT5-Unofficial/blob/unstable/src/main/java/gregtech/common/blocks/GT_Block_Reinforced.java#L43

Nah GT5u has it borked too

**Comment by DualBallers** [comment]
Alloy Blast Smelter also get this type of error (2.0.4.0).
![image](https://user-images.githubusercontent.com/30087707/40562673-48b6d808-6062-11e8-9182-2719aac4b30a.png)

**Comment by richardhendricks** [comment]
Is this still happening?  I think we can close this issue.

**Comment by Wolozo7** [comment]
![image](https://user-images.githubusercontent.com/34921674/45445430-807b1880-b6ca-11e8-97f4-e1261cb99c2d.png)

Nothing changed. But it's also not that important, true.

**Comment by richardhendricks** [comment]
addToMachineList adds a hatch to the respective list
And passed in the texture ID for the hatch to take.
0-63 are GT, allocated to the first four casing blocks. 64-127 are reserved for GT++, of which is have 3 left.
 
moronwmachinegunToday at 1:05 PM
This code is all pure cancer IMO
 
АлкалусToday at 1:05 PM
Tec did some magic with bitshifting to allow for texture pages, since we couldn’t expand the original array of 128.
But since I support versions before that and predated the fifth casing block class, I get half the original block.

**Comment by DualBallers** [comment]
This is still present in 2.0.9.0.
![image](https://user-images.githubusercontent.com/30087707/94375400-a5a51d00-0113-11eb-92fc-fd7e0001ce8f.png)

**Comment by bombcar** [comment]
This is reported fixedindev on Zeta.
