### ISSUE TITLE
Change up High Octane Gasoline / Large Combustion Engines

### ISSUE THREAD

**Issue by richardhendricks** [GTNewHorizons/GT-New-Horizons-Modpack#2987]
Right now HOG is too complex and with too little benefit for use.  An idea is to make it the "high tier" gas fuel for the gas turbine instead, and up it's eu/b significantly.

Change it from liquid to gas (make sure to check other fuel uses like copterpack)

Up EU/b from 1.152 million to 2.3 million.  (Need to check efficiency)

Check on high tier rotors, could they use this for IV+ power?

**Comment by Dream-Master** [comment]
so you mean set burnvalue to 2.3 mio ? @richardhendricks

**Comment by richardhendricks** [comment]
yeah, and set it to gas instead of fluid.  let's leave this open for now for discussion, it can wait after 2.0.4.1

**Comment by richardhendricks** [comment]
Have you looked at the recipe? I doubt a single person has made it in-game seriously.

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/40442160-374bf4f4-5ec3-11e8-8f19-fbbe53f51b90.png)

**Comment by bartimaeusnek** [comment]
keep it as Fluid please, maybe add a High Octane Gas when HOG is put in the fluid heater, that would be awesome.

**Comment by richardhendricks** [comment]
That could work too I suppose.  But are you using the fluid version @bartimaeusnek ?

**Comment by richardhendricks** [comment]
Maybe call it jet fuel. https://en.wikipedia.org/wiki/Aviation_fuel

**Comment by bartimaeusnek** [comment]
@richardhendricks i used to rely only on diesel from LV- early EV. now im relying on Water and sunpower (IV-LuV) on my Delta Base, in the Epsi base i share with some other players, we rely on cetane

**Comment by Prewf** [comment]
I thumbs-upped this but it's mainly in the hopes that it acts as an incentive for future players to make it. If I'm being honest, I personally would never do it, even if it were bumped up to 2mio. This fuel is just in a really weird spot regardless of if it gets a buff or not. Cetane alone is EU-dense enough to carry you easily through HV and early into EV. By the time you need something as energy dense as HOG, you probably have the option to go EU-mode or Fluid-Mode nuclear which requires less infrastructure than this and is way less logically complex and is way more energy dense.

**Comment by Bluebine** [comment]
I support a buff to high-octane gasoline, but I don't support making it a gas turbine fuel, as the bigger gas turbines are more annoying to use than the large combustion engine. I'd keep it as a combustion fuel with a higher burn value.

Also I think it NEEDS to be way higher than cetane, since it's gonna be competing with nuclear and kinetic energy instead of charcoal and steam.

**Comment by richardhendricks** [comment]
@Bluebine Wait, what?  Aren't you the founding member of the Church of Benzene?!  This fuel would pair nicely with a high tier high output gas turbine rotor. Looking through the list, the Shadow turbine looks pretty good, 4800 EU/t raw, with the efficiency boost from a large turbine getting you to 6720. That would be something you could make at HV, if you get enough rutile from processing to make an EV machine hull.

The problem really is that the large combustion engine boosted with oxygen is just so damn good it overshadows the large gas turbines.  2048 at 100% with no oxy, and 6144 at 150% with oxy is really really good.  

Maybe we should just remove HOG completely?

**Comment by Bluebine** [comment]
@richardhendricks Yeah, I like gas turbines in general. But those multiblocks are a pain in the ass to use, far more than a large combustion engine, since you need to calculate so much and choke the fluid input or else it'll not run as efficiently.

Yeah, the large combustion engine is pretty good, but I don't really think that's a problem, honestly? You could maybe bump oxygen boosting down to 125% efficiency instead of 150%.

And nah, I like the idea of HOG, it seems fun to have a super complex processing line to make oil viable past HV.

**Comment by alphaNOVAircraft** [comment]
@Bluebine i would not bump oxygen boosting down to 125%, you are able to build the large combustion in ev and it should compete with reactor etc. lowering the efficency makes it way more anoying to use if you need to get on your oil much more often.

**Comment by richardhendricks** [comment]
What about this proposal - 

LCE with normal fuels(cetane included) + lube - Outputs 2048 EU/t
Add oxygen + lube 2x, get 150% efficiency boost and output boost to 3072. EU/t

LCE with HOG + lube 2x - outputs 4096 EU/t
Add oxygen 2x +lube 4x, get 150% efficiency boost and output boost to 8192 EU/t

This way LCE is still viable in EV and IV, but is not such a huge jump from 2048 -> 6144 with just some trivial oxygen.  And applies a little pressure on oxy and lube generation to get IV level power.  And using HOG gives you a nice output boost to IV levels of power.

Along with this, I think having moon rocks and endstone hand out tungstate (requires EV electrolyzer) instead of straight tungsten would be a good thing as well.  Right now you can get enough tungsten from moon rocks/dirt to upgrade all your mufflers to IV and use IV dynamos. Putting them behind the EV electrolyzer at least forces players to wait until they get alot more built up.

**Comment by Prewf** [comment]
Is this enough of an incentive to convince players to use HOG? I still wouldn't imo. I would like some insight into whether actual players at EV tier would bother with making HOG, with this buff xD

**Comment by richardhendricks** [comment]
It really depends on your power-path to that point.  If you are on biodiesel and cetane, maybe no because you don't have any of the ingredients for the HOG.  But if you did a full oil distillation tower setup, I think HOG is a lot easier then.

**Comment by Prewf** [comment]
I mean..realistically speaking, the people who have reached EV-tier are probably all running on some sort of (hopefully) renewable liquid or gas fuels by the time they are at this point, namely the two fuels you mentioned cetane and biodiesel. And for those that aren't, then honestly the best way to proceed is to not even bother with this spaghetti recipe and just go with nukes.

If this change were in effect, biodiesel/cetane players have 2 options. Set up additional infrastructure for HOG (which involves, at a minimum, a pyrolyse/distill combo for nonstop toluene production and a pyrolyse/distill combo for nonstop heavy oil production for renewable oil->raw gas and a number of new chem reactors solely dedicated for the various chemical subcomponents you need), OR just extend their current setup and make more cetane/biodiesel. With the proposed change, you still get a 150% efficiency boost from your basic fuels, and a full non-stop cetane production makes about 750-1000 Liters per second. 

Here's some math,
Amount of cetane/s required to run 1 3072 EU/t boosted LCE: (3072/(720*1.5)) * 20 = 57L/s
Amount of cetane/s you generate from a nonstop cetane setup: 750-1000L/s (the base minimum time for an HV mixer to make cetane, assuming you always have enough ingredients, which you should in a proper setup; 750 if you make it inefficiently from biodiesel or 1000 if you make it from diesel)
You can run, at a minimum, 13 LCE's with a proper cetane setup.

Biodiesel is trickier, since the involved recipe tiers are all varied. But at the bare minimum final LV tier chem reactor recipe, you can still run 1 LCE, since an LCE would require 160L/s, and the LV recipe generates 200L/s. Overclocking any aspect of a biodiesel setup could easily support several LCE's if a player wanted to do it. All it requires is more seed/fish oil production and maybe one more distill tower for more methanol/ethanol.

Both cetane and diesel setups require much less effort from the player if they just extend what they already have. The proposed LCE change hasn't changed any actual fuel values. You still get 150% efficiency even from base fuels, so HOG is STILL only marginally better than cetane, which is the problem we already have right now. A cetane/biodiesel player can just plop down another LCE, since they probably make more than enough cetane and biodiesel right now anyways. And again, for those that somehow miraculously made it this far in tier without relying on any combustible fuels..they could just go nukes instead. I just don't see the incentive.

**Comment by Prewf** [comment]
All this to say, at the very least, the efficiency bonus for HOG should be increased. Either that, or the fuel value should be increased. It's just not worth the effort making this thing, compared to sticking with cetane.

**Comment by WarlordWossman** [comment]
>All this to say, at the very least, the efficiency bonus for HOG should be increased. Either that, or the fuel value should be increased. It's just not worth the effort making this thing, compared to sticking with cetane.

That's a good point, do you think we should really touch the percentage or just have it make more raw EU? I think it kinda makes sense that it's 100% and 150% with oxygen, so I would say that we could rather increase the EU value.

**Comment by Prewf** [comment]
Agreed, I'd probably go with increasing the raw EU value. That way, it's buffed outside of the LCE too (if for some reason, someone decides to setup infrastructure for HOG, before they go to space and get titanium)

I was all for doubling the EU value, but alpha mentioned it might be too much. That's true if we were to just straight up double the raw value. Perhaps make it 1.5x what it is now for the raw value. And make it a further 1.5x better on top of that if you use it with an LCE (2.592mio EU per 1000L)? I feel like that'd be a decent place to start..

**Comment by Prewf** [comment]
It's a full amp of IV, yes but the value of the fuel you're using hasn't changed..which effectively means, you can get an amp of IV right now, it's just that it would take 2 LCE's to do instead of 1. 

Changing the LCE to output 1 IV amp..all that does is raise the consumption rate so you can basically "process" more fuel in the same physical space. **You're not getting more out of your fuel.** 

Is the goal here to make the LCE more space efficient or to actually balance the relative fuel density of HOG compared to other fuels? I thought it was the latter.

**Comment by richardhendricks** [comment]
Originally it was to make HOG worthwhile, but WW brought up that the LCE is kinda OP for what it does, with only oxy needed to triple the output power.

**Comment by WarlordWossman** [comment]
> It's  a full amp of IV, yes but the value of the fuel you're using hasn't  changed..which effectively means, you can get an amp of IV right now,  it's just that it would take 2 LCE's to do instead of 1. Changing the LCE to output 1 IV amp..all that does is raise the  consumption rate so you can basically "process" more fuel in the same  physical space. You're not getting more out of your fuel. Is the goal here to make the LCE more space efficient or to actually  balance the relative fuel density of HOG compared to other fuels? I  thought it was the latter.

Chill, nothing is set in stone. If you wanna go through the numbers right now we can probably judge if we should instantly buff the EU value by 1.5 or something along with the other changes.

I am just not instantly for it because I have not checked the numbers myself ;-)

**Comment by Prewf** [comment]
@richardhendricks 
> you can get an amp of IV **right now**, it's just that it would take 2 LCE's to do instead of 1.

@WarlordWossman 
Sorry if you thought I was being hostile. I just wanted to bold to emphasize that part heh. From what I've read so far of your responses I wasn't sure if you guys fully understood the implication of simply bumping up the EU/t output value of the LCE.

Anyways, I gave my 2centz. Hopefully other people can chime in as well.

**Comment by WarlordWossman** [comment]
Still a big fan of the changes we came up with for the LCE, I think once those are applied we can build HOG up ingame and judge if it needs a buff, it does sound like it but I would rather see the LCE changes first and mess around in creative.

**Comment by WarlordWossman** [comment]
The one from moron with the 5 upvotes, as I said I get the point but I would say that change should be made first and then we can look at the value of HOG after.

**Comment by Prewf** [comment]
Sorry if I sound really pushy, I just feel like there's nothing to "wait and see" about this.. the numbers haven't really changed much in what moron suggested. All he's suggesting is letting more HOG be fed into the LCE. I'm basically saying it's not significant enough of a change to expect any serious difference in usage compared to now (how could it? you're not getting any more out of HOG than you are now). 

I'm sad because it's been like 3 months and people seem more interested in changing things up only for LV-HV all the time. It's either that or people are extremely quick to jumping on the train to nerf things left and right (yes it's a "hard" pack, but it doesn't mean we shouldn't try new things). I really felt like this was a pretty straightforward: there's a fuel literally no one is using, so let's buff it in a way that gets people to notice it and actually try it out. A combustible fuel that could potentially help you sail through LuV+ and break up the nuclear monopoly? More people should be jumping on this!
