### ISSUE TITLE
Telepad\charm of dislocation recipes...

### ISSUE THREAD

**Issue by Cinobi** [GTNewHorizons/GT-New-Horizons-Modpack#3083]
#### Which modpack version are you using?
Epsi
#
#### If in multiplayer; On which server does this happen? 
Epsi
#
#### What did you try to do, and what did you expect to happen?
is ridiculosly overcosted. Even my team can't craft this shit now, are u serios?)
btw, u need 18 telepads to create a link, did u know it?

Suggestion: Reverse the recipes back to normal.

![2018-06-10_21 29 36](https://user-images.githubusercontent.com/25028786/41205136-5c14cf5e-6cf6-11e8-8077-f95786862496.png)
![2018-06-10_21 29 42](https://user-images.githubusercontent.com/25028786/41205137-5c3a5e86-6cf6-11e8-94dc-761549afd684.png)
![2018-06-10_21 34 52](https://user-images.githubusercontent.com/25028786/41205138-5c79b824-6cf6-11e8-96cf-295dbfcf1d6c.png)
![2018-06-10_21 34 57](https://user-images.githubusercontent.com/25028786/41205139-5ca050ec-6cf6-11e8-8280-0b62966e3117.png)

**Comment by 0lafe** [comment]
I'll probably have more opinions on this at some point, but I don't mind the charm nerf too much. That's 40 UV gens which might be a bit much, but if it was 20 or 10 I don't think I'd mind too much. Also, kind of a lot of infinity for the power banks, but not really enough for me to think it's unreasonable. 

Teleporters shouldn't be that hard though. Right now teleporters cost more than the charm by a lot lol. 36 capacitors for the teleporter and 8 for the charm, which is like infinite teleporters. Considering we got Witchery which just does the teleporters job for almost no cost, it should probably go down a little. Tiering them to LuV is fine, but even when they cost just LuV arms it was a little too costly. 

Charm I don't mind costing infinity and UV parts, even if it's a ton. However, the personal teleporter thing from gravisuite should probably get a Nerf too if it didn't, considering it's pretty much the same thing.

**Comment by Dream-Master** [comment]
Endgame stuff have endgame recipes.

**Comment by Cinobi** [comment]
This is not "Endgame", it's "Shit noone will craft". Telepads especially(need to craft 18 of this to make 1 link)

**Comment by 0lafe** [comment]
so I take it back, I'm starting to see some problems. Mostly that it costs almost 14,000 infinity ingots, while the infinity armor costs less than 70. Other than that, with UV parts as a whole getting a pretty big nerf in cost, I don't know if I mind that.

However the stargate-crystal dust is dumb. It takes one of the useless OW ores that no one mines endgame, partly because some servers dont alloy automining/quarries in the OW, and partly because it's super useless. Chrome dioxide is also a weird choice. Also why 54 jasper and 47 opal? Samarium too is kind of weird for this. Even tceti extract. The tiering on the items ranges from steam to UV, while these recipes are clearly made for tiers well beyond that. Maybe change it to be like 16 tritanium, 64 naq alloy, 16 neutronium, 16 of the other neutronium, 16 awakened draconium and 1 infinity. 

The stargate-radiation-containment-plate is also an issue in some ways. The 16 infinity blocks per is a little much, considering there really isn't a great way to make infinity in this pack that doesn't make getting more than 100 a huge pain in the ass. It also has an eternal singularity, which comes out to 6M of a lot of materials for the charm. That's not really doable now. Best you can really do is 4 quarries in each dimension, which will still take a fairly long time to get close to that, especially of things like tin which aren't in many dimensions. 16 UV sensors per is also a little much considering you need these in bulk. For the charm. thats 1.5k UV sensors, which is, well, and undertaking to say the least. A stack of them will even cost an endgame player quite a lot of time/resources. 24 stacks however might be a little more than I would ask of a higher tier player. Nanos are also pretty expensive, at 2 wetware mainframes per, making 1 nano cost 16 wetware base circuits, which east cost 16 stemcells. That comes out to 256 per nano, or something like 350k for 1 charm of dislocation. Which is a LOT. I had a zpm disassembler running full speed for ~4 months, and got 60k stemcells.  

If the stargate-radiation-containment-plate recipe is for 4 sensors and 4 nanos instead of 16, the charm goes from almost unobtainable, to doable at HIGH tiers. However, we do need more power for this kind of stuff. Realistically you need tons of assembly lines running at UV and at the same time. Then all the power for the UV machines that make parts, circuit making, and the general PA's making the parts for the assembly lines. The problem at endgame becomes that there isn't power aimed that high. Power pretty much stops around a couple amps of UV, and this kind of crafting is on the UIV+ scale. Higher mk reactors helps, but we NEED better plasma generators to make fusion doable for these tiers. Solars kind of work, but we really need more solar recipes. Higher naq gens could be interesting in some ways, maybe have processing chains for naquadria to make a better version for UHV+ gens, however for that we need better naquadah generation. Bees right now can not keep up with anything reasonable for this scale of power, and they're about the best we got. 


What I'm trying to say is that these recipes don't work with the limitations that are currently present. Power generation pretty much caps progression to a degree, unless you rely solely on UV solar spam, which isn't that interesting, and doesn't work as well as it needs to. They are endgame recipes, just not for the current endgame of gtnh.

**Comment by bartimaeusnek** [comment]
The decision that all Inter Dim TP will be moved to UHV was made with 2.0.3.0. Since its now Endgame stuff. We can talk about re-balancing them so they become equalvent to each other and their abilities, but we wont undo the change at all.

**Comment by 0lafe** [comment]
The thing is that's not UHV at all, making just the infinity part of the charm would cost in the hundreds of amps of UHV. It's like comparing UV power gen to LV, you can say UV is just 16384 LV gens, but expecting someone to make 16384 LV gens is a little much.

**Comment by noobyaran9** [comment]
>Endgame 

How is charm of dislocation or other interdim tp method endgame when i could just waste 10mins of my time travelling using other means? Its just something that helps in the late game travelling easier, and now its got a really dumb recipe. If this recipe was using the old recipe with the changes being replacing the plate with infinity plate, I would complain at all.

**Comment by noobyaran9** [comment]
This is my proposed change to the charm recipe and some other few item from draconic related to TP.

Charm of Dislocation:
![2018-06-11_11 50 36](https://user-images.githubusercontent.com/13598309/41212023-be32325e-6d6d-11e8-9194-abcf4efe108b.png)

Enhanced Charm of Dislocation
![2018-06-11_11 50 50](https://user-images.githubusercontent.com/13598309/41212024-be612fdc-6d6d-11e8-816a-9fd4775d4268.png)
The current recipe of enhanced charm of dislocation is just too expensive for what it does. Changing the old recipe to use infinity plate instead of draconium plate and chaos core instead of wyvern core seems to be a better balance for the item. 
Not to mention, you could change the amount of ender pearl usage for each tp to some stupid number like 1k pearl per tp. 
>Charm of Dislocation uses per Ender pearl
    I:"Teleporter Uses PerPearl"=1  ==> 1024 (or some other number)

Or if someone wanna make the charm able to take other item as fuel, feel free to do so. Currently, in my mind, I think the best fuel in this case would be neutronium ingot / IV field gens / infinity catalyst / nether star / quantum star / quantum eye / naquadria ingot or rod.

Dislocator Pedestal:
![2018-06-11_11 48 04](https://user-images.githubusercontent.com/13598309/41212025-be916580-6d6d-11e8-8c54-18ed5f43bf75.png)

Dislocator Recepticle:
![2018-06-11_11 49 18](https://user-images.githubusercontent.com/13598309/41212022-be008312-6d6d-11e8-8f2d-3dc65709fd41.png)
About this 2 recipe, there is no point including the charm of dislocation in the recipe as they still need the charm in order to function.

**Comment by Highbeam** [comment]
bump. I agree this recipe isn’t fair in any game and honestly if this is ‘late game’ then I’ll never bother playing when I get there. I too vote to reverse the recipes or make them more realistic and not just ‘grind’ please

**Comment by Teirdalin** [comment]
Wait- did you just say it takes 14,000 infinity ingots to make the charm?

Was looking to see if anyone was posting about how the charms cause client crashes and stumbled upon this;  but yeah that does seem a bit much for the advanced charm.    I think the above mentioned recipe  
https://user-images.githubusercontent.com/13598309/41212024-be612fdc-6d6d-11e8-816a-9fd4775d4268.png   
 would be a good option; although if wanting it to be more pricey could maybe use double or triple compressed infinity plates instead; or just use like 16 normal dislocators with that number of infinity plates; after all the adv charm essentially just is a bunch of dislocators put together in a reusable format.

**Comment by 0lafe** [comment]
That's not the main problem, so many singularities is just such a pain in the asssssssss. It's like hundreds of millions of so much stuff. Only like 96 awakend blocks at least lol

**Comment by barsikus007** [comment]
We need to do smth with that. This is still uncraftable without massive stacking of resource gen stuff (which may decrease tps on officials a lot).
We can make poll in discord for community mention about that. I like @noobyaran9 idea to make recipes more craftable and for example change fuel to smth else (Quantium eyes seems good for that).

**Comment by observeroftime02** [comment]
Can't be crafted anyways, since the Tricalcium phosphate singularity is broken atm.

**Comment by Dream-Master** [comment]
SG craft stuff are expensive because it's endgame stuff. Will check recipes.

**Comment by observeroftime02** [comment]
Expensive is fine, but not being able to craft them due to a broken uncraftable singularity is a problem.

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/65865017-14ba2b00-e373-11e9-9c87-6622a9bbe43b.png)
This was fixed in 2.0.7.6

**Comment by repo-alt** [comment]
I thought it is charm of dislocation discussed here, not stargates.

**Comment by barsikus007** [comment]
what do you think will happen if you start generating the amount of resources that you need to craft a dislocator or stargate, for example on Eta?
Tps will become unplayable, bcs this is ubtainable only by stacking matter and energy generation setups

**Comment by Dream-Master** [comment]
Portals was never designed to craft only be creative items for admins.

**Comment by barsikus007** [comment]
But this is utility thing just for save time, so it needs to be craftable atleast at max tier

**Comment by barsikus007** [comment]
how can we get 9 732 096 inficat dust + 35 831 808‬ neutronium dust to craft this? Fastest way to get inficatalysts it is mining in DD so you need to mine 1kk*1kk to craft this

**Comment by Dream-Master** [comment]
If you start to redone the whole teleporter recipes or make some suggestions we can change this recipe as well. All need to be balanced.
