### ISSUE TITLE
AE2 Storage in Void Worlds Deleting/Duping Items

### ISSUE THREAD

**Issue by Wolozo7** [GTNewHorizons/GT-New-Horizons-Modpack#3298]
#### Which modpack version are you using?
2.0.4.6
#
#### If in multiplayer; On which server does this happen? 
Delta
#
I doubt that this can really be fixed, I'm mostly just looking for tips on how to deal with this behavior and maybe why it happens:

So, I recently moved into a Garden Dimension. A lot of my items are stored in a combination of Storage Drawers and AE2 Storage Disks. That system used to work fine in the Overworld. Now, there's some pretty weird stuff going on. E.g. I have ~100k small Redstone dust in a single Drawer and ~30k going around in other Drawers or Disks. Now, I wanted to store it all in the big Drawer, so I exported the 30k dust. Everything went fine with exporting, all the dust was in one Drawer. However, after an undefined amount of time, I looked into my system and the 30k dusts in random Drawers reappeared, although I still had 130k dust in the big Drawer. So I had 160k dust now. The same thing appeared for other items, I have 4 of those Transvector Interface Binders now, 2 new Builders' Wands etc. On the other end, I'm pretty sure I gave orders to craft stuff like circuits, went offline and there were no results when I logged back in.

**Comment by MineAnPlay** [comment]
I don't think it's because it's a void world but because of the server itself. Delta and Epsilon will roll back to an earlier date if there is some errors/corruption etc. It most likely happened to you before but you didn't notice it. Still this doesn't mean this issue is done, if it could be fixed it should be debugged if possible.

**Comment by 0lafe** [comment]
I've noticed it in the overworld as well. If I teleport somewhere, place some stuff, then leave, it might remove what I put. I lost all the PAs for my fusion from that when I was setting it up. 

Also lost/duped so much stuff in the void. Wondering if playing on a server that's just forge makes a difference.

**Comment by MineAnPlay** [comment]
That's why I said it's not exactly void related (though it does seem more obvious/more likely maybe because people with void worlds are higher tier) and yes Forge will make a difference because forge doesn't rollback to earlier saves (will only rollback if it didn't save, so not actually a rollback but more like it didn't to save and went to latest save). Not sure if there is a "fix" for this but maybe there could be a "main" culprit.

**Comment by MineAnPlay** [comment]
I personally saw the dupe/loses when I reached HV on Epsilon, lost parts of my Distillation Tower because of it and saw that some stuff were missing (but I though it was people taking it, had too much rubber/plastic at the time etc :P ).

**Comment by MineAnPlay** [comment]
Yea I know that they are worse, I was just pointing it out that forge rarely does and if it does it's because of a failed save (if it's corruption it either crashes or just goes along). I agree with what the issue is most likely caused (or combination of) but it's just too hard to debug and pinpoint the main issues that it may never get fixed (unless Thermos/Cauldron gets rewritten to be better compatible with forge and mods :P). Also Dream it's both official servers and most likely all other unofficial servers too (if they are using Bukkit/Plugins too which they most likely are).

**Comment by Wolozo7** [comment]
What confuses me about this is that the whole thing is that the dimension is sufficiently chunkloaded. As the naive person that I am, I find it hard to understand why the server decides to rollback the dimension to a previous point when its chunks are loaded. Are there certain conditions that have to be met for changes in a dimension to be saved?

**Comment by Wolozo7** [comment]
For example, I crafted 12k Smd Capacitors this morning, some time between 4 am and 6 am. The crafting finished without issues, but I hadn't used them yet. Went afk and for some reason, the server decides it needs to restart at half past 8. Coming back at 9 am, all the Capacitors are gone again. So despite me being moderately active, the dimension was reset to a state quite some time before the restart. This is why I'm interested  in the  conditions under which the server decides to save my dimension.

**Comment by MineAnPlay** [comment]
It's not saving that's the issue, it's the server rolling chunks back to an earlier save. Nothing about chunk loading/unloading too, server saves chunks before it unloads them (unless forced too which isn't the case).

**Comment by Dream-Master** [comment]
Are you sure the server did it itself @MineAnPlay  ?
@Namikon any idea here ?

**Comment by Namikon** [comment]
This is a well aware problem and cannot be fixed. Our Servers are based (and rely) on several Bukkit-Plugins; This cannot be changed without some serious changes to how things work for us. I'm aware that it's not the best solution to run a server as of today, but we have what we have.

**Comment by draknyte1** [comment]
Any Bukkit plugin can be ported to forge.. nobody needs Bukkit

**Comment by richardhendricks** [comment]
Wolozo,
  When this occurred, were the chunks in question chunkloaded?  Did you do teleporting in/out of those chunks?

I've got a feeling the chunk rollback issue is tied to teleporting out of a chunk, and then teleporting back in a relatively short time.  My suspicion is that the chunk gets added to a queue to save to disk, and then when you teleport back, it hasn't been saved off yet.  Then the fetch algorithm pulls stale chunk data from the HD instead of re-activating the chunk on the save queue.

I recommend chunkloading all chunks of your base and seeing if the issue goes away.

**Comment by Wolozo7** [comment]
Chunkloading doesn't prevent the issue. But it also persisted after moving back to the overworld, I probably just didn't notice it before. I notice it happening a lot around the server restarts, but it doesn't necessarily only include items that were produced shortly before those restarts.
