### ISSUE TITLE
Fluid regulators not working when mounted on pipes

### ISSUE THREAD

**Issue by RaggedCaster** [GTNewHorizons/GT-New-Horizons-Modpack#3337]
#### Which modpack version are you using?
2.0.4.6
#
#### If in multiplayer; On which server does this happen? 
Private server
#
#### What did you try to do, and what did you expect to happen?
I placed a HV fluid regulator interrupting a fluid pipe. 
![javaw_2018-07-20_16-56-48](https://user-images.githubusercontent.com/30390927/43006290-fb886012-8c3d-11e8-9369-224b90cbfbc0.png)
#
#### What happend instead? (Attach screenshots if needed)
The pipe is constantly connecting and disconnecting, it's not visual only (fluid flow is affected).
![2018-07-20_16-58-00](https://user-images.githubusercontent.com/30390927/43006375-363f0990-8c3e-11e8-996a-af4d37231283.gif)
Oddly enough, when a regulator is placed on a GT block (input hatch, LV tank) it behaves normally.

**Comment by boubou19** [comment]
try to connect the pipe from the other side of the fluid regulator with a wrench

**Comment by bartimaeusnek** [comment]
Not a visual bug and i can confirm this, @boubou19 that does not help sadly.

**Comment by Dream-Master** [comment]
@bartimaeusnek any ideaq how to fix?

**Comment by richardhendricks** [comment]
I don't think fluid regulators make sense inline on a pipe.  They regulate how much fluid is in the destination per tick, and with a pipe as the destination you aren't going to get guaranteed flow rates since the pipe moves the fluid away in odd ways. Put on a pipe that ends in an input hatch or where you want the regulated amount delivered instead of inline with the pipe.

**Comment by Prewf** [comment]
I'm pretty sure I connect my fluid pipes for my LHE this way and it worked fine since 2.0.3.0 I can attach a screenshot in a few minutes. Are you sure you have the regulator screwdrivered properly (positive vs negative rate)?

**Comment by Prewf** [comment]
![regulator](https://user-images.githubusercontent.com/35204071/43015200-c33d2e20-8c03-11e8-9554-4ba749f974a2.png)
The pink cover at the top of the pipe is an ev fluid regulator. I wrenched it off and temporarily messed with it to show you the rate it's set at (positive 1340L/s).
![regulator2](https://user-images.githubusercontent.com/35204071/43015380-7ae93da2-8c04-11e8-9619-6797e6a04a7d.png)
This has been working since I set it up about 6 months ago (our server updates GT:NH often too and as of 2.0.4.6 it's still working)

**Comment by Prewf** [comment]
I also forgot to mention. I do the exact same thing (putting IV regulators on pipes) for my huge enderium pipes that feed into my Large HP Steam Turbine. You can also tell it works there because it's generating the correct amount of EU/t (overfeeding/underfeeding would cause a dropoff in EU/t).

Also as an update, I used HV regulators on my hydrogen production setup over the weekend (one attached to a super tank face and another attached to pipes again). It seems to work fine for both.

@bartimaeusnek are you sure this is an actual bug? Even if it doesn't look connected, it's still passing liquids at the correct rate on the other side of the regulator. What test did you do to come to your conclusion that it's not working?

**Comment by Prewf** [comment]
Ok so I found out some more funky things about the fluid regulator from my extensive tinkering this weekend.

One fluid regulator on a pipe is fine (i have 3 regulators at negative rates on my pipes to pull hydrogen out of them and into centrifuges for deuterium/tritium; it works fine 100% here).

More than 1 fluid regulator on a pipe is...not fine. My test was:

I had 3 fluid regulators on a single pipe. 1 was an "input" regulator, giving 240 L/s to the pipe. 2 were "output" regulators, sucking out 120L/s out of the 2 ends of the pipes. My expectation was that both ends of the pipe should be receiving 120L/s...but instead I got inconsistent jibberish numbers. I replaced the pipe with a tank and attached the regulators on the tank faces (same "1 input, 2 output" setup) and then it worked perfectly.
