### ISSUE TITLE
Rework how graves spawn skeletons

### ISSUE THREAD

**Issue by richardhendricks** [GTNewHorizons/GT-New-Horizons-Modpack#3366]
A bunch of people have died at the End spawn in Epsilon, leaving their graves everywhere.  These graves are now spawning in skeletons including infernals.

Should we disable this?  Do technical players use this for mobfarms? @WarlordWossman , thoughts?

**Comment by alphaNOVAircraft** [comment]
I would disable this feature. It can happen that you die to a super strong infernal. This happens a few times and you have an increadible amount of mobs spawning there. You get worse on gear and a increasing count of mobs is definitely not helping you to get your stuff back.

**Comment by draknyte1** [comment]
I had to fight the dragon in the end with about 10 skeletons floating in the air on my previous graves. The annoying thing is, as soon as one falls off, a new one instantly spawns. (Due to the lack of any existing in the end) this makes destroying your grave harder as skeletons just Insta spawn.

**Comment by WarlordWossman** [comment]
Yeah this feature is a gimmick, and esp with infernal mobs I wouldn't have skeletons spawning.

@richardhendricks you probably could make a mobfarm with that but since graves are implemented for people to recover their stuff and the skeleton spawning seems to interfer with that (makes it more annoying) I see no point in having it, not like you cannot get skeletons from a normal hostile mob farm or even a spawner...

**Comment by ItzzGamma** [comment]
I'm recommending that you lower the spawn rate of Brutish, Infernal and those types of Mobs because they are too strong. I had a person with me today on Zeta while we were fully geared (Dark steel, protection III diamond) and we both got one shot by a Brutish zombie which is insane and they spawn too often. If possible you can also lower their damage or something because they have too much damage and they aren't that easy to kill with weapons that are available to player under LV or even MV. This is especially annoying for new players and ruins the beginner experience because you have to kill a zombie that has too much health, too many abilities and can one shot you with a damn flint sword.
Also it would be nice if the grave spawning could be reduced a bit since i'm pretty sure i had mobs spawn every 10 seconds on my grave which made it almost impossible to get my items back without a weapon or something.

**Comment by richardhendricks** [comment]
Will remove skeleton spawning on gravestones

**Comment by Dream-Master** [comment]
No not remove it completly maybe make the spawnrate lower

**Comment by richardhendricks** [comment]
Look at https://github.com/GTNewHorizons/NewHorizons/blob/master/config/OpenBlocks.cfg#L209
change spawnrate, maybe there is a bug in how it is throttling spawns.

**Comment by richardhendricks** [comment]
https://github.com/OpenMods/OpenBlocks/blob/c90141626490293cc0f4d0f4b7f113e35aea29d5/src/main/java/openblocks/common/tileentity/TileEntityGrave.java

**Comment by richardhendricks** [comment]
Default value in the configs is .002. Will test with .0002 to see how bad ie a bunch of graves in the end look.

The source has been forked to our projects as well.

https://github.com/OpenMods/OpenBlocks/blob/c90141626490293cc0f4d0f4b7f113e35aea29d5/src/main/java/openblocks/common/tileentity/TileEntityGrave.java#L67

There is actually a 50% chance of skeleton or bat, could play with that a bit too, maybe adjust it to favor bats more (firebats in the nether I guess?) since they would be slightly less annoying to deal with than skeletons.
