### ISSUE TITLE
Nerfing/Rethinking Power Transfer

### ISSUE THREAD

**Issue by WizardSleve280** [GTNewHorizons/GT-New-Horizons-Modpack#3369]
Since I have started playing GTNH after a hiatus, I have noticed the addition of every tier superconducting cables. Thats cool and all, but the problem is that they are really only viable in lv and maybe mv/hv. This is because the power loss over a long distance is basically meaningless when you deal with recipes and tiers requiring 2048 eu/t or 8192 eu/t vs when you have recipes dealing with 32 eu/t or 128 eu/t. For instance, if your power supply is 8 blocks away and is lv, producing 32 eu/t, you have essentially lost 1/4 of your power transporting that power just 8 blocks. That loss is very dramatic and merits the use of superconducting lv cables. However, if you are in ev, you would need to go out 512 blocks to get that same 1/4 loss. Even if you are generating power using a kinetic wind turbine at  y = 255 and bringing that power down to y = 2, the power loss would only be 254 eu. (This is assuming the power loss is 1 eu/block) My proposal would be to either make power loss scale with the tier of power to make superconducting cables more viable or to rework the superconductors/cables (Not recipes)

**Comment by WizardSleve280** [comment]
Im saying to leave superconductors the way they are, just make them more viable by changing other cables

**Comment by Prewf** [comment]
Well I only asked because

>My proposal would be to either make power loss scale with the tier of power to make superconducting cables more viable or to rework the superconductors/cables

made it sound like an either/or situation. 

For an explanation of why I dislike the idea, I always viewed power loss as something you're supposed to naturally outgrow as you go higher in tier (like an implicit "reward" because you've reached the next tier). Similar to how you effectively outgrow pollution as you tier up because you have more methods of dealing with it. I know you haven't proposed any hard numbers yet, but I take it to mean that you don't want power loss to ever be trivialized without the help of superconductors? So something like

minimum 16 eu/block loss at HV
minimum 64 eu/block loss at EV
minimum 256 eu/block loss at IV
etc.

The numbers can obviously be adjusted but it gets the main point across: The loss is significant enough such that, no matter what tier you're in, you always need to worry about power loss. imo, superconductors are annoying as hell to make already, but to make large amounts of them basically mandatory just to have a decent looking base layout seems unnecessary.

**Comment by draknyte1** [comment]
Hardcore power loss already exists as a config option, which was the default loss rates for a VERY long time. This isn't a new idea and nobody sets it enabled.
