### ISSUE TITLE
Teleport with Witchery

### ISSUE THREAD

**Issue by Dream-Master** [GTNewHorizons/GT-New-Horizons-Modpack#3386]
Teleport with witchery is dirt cheap compared to other methodes so i need to balance it.

**Comment by PoptartOverlord-Xabedo** [comment]
true, its quite cheap and very easy to make, you only need to research witchery in thaumcraft and you've done the hardest part, all you need next is to startup witchery .
but still i  think that it should be cheap as an option for hv or higher but not as expensive as other teleporters, because not that many people, especially those who do alot of tech mods know that much about witchery so its unlikely they'll come across to it, , so in other words   making other lesser known ways of teleportation for those who take their time to do witchery can be considered outsmarting other players while still being bound by the grind of the game.

**Comment by 0lafe** [comment]
Probably shouldn't balance it on the idea of people not knowing about it. Other teleports are gated pretty far. 

DE is UV+ (and not really doable)
GT is UV+ (and maybe doable)
TC is IVish and doesn't do cross dimensions 
Eio is UV?

Witchery is worse than DE and GT, and those items seem more like creative stuff than anything else. Personally I think eio teleporters should be what you use pre endgame, but they'd need a bit of a change. Making them cost EV/IV parts and take a decent amount of eu/t to "maintain the opening" or something. Witchery is easier than that, but gating part of witchery past IV but before UV seems, weird.

**Comment by 0lafe** [comment]
They used to be barely UV. Took UV circuits, and a block of infinity for GT/DE teleporting. Wasn't that terrible but DE needs some work imo because with luck you can get the teleporter in EV, IV even easier. Easiest fix I can think of for witchery is to use planet stone to chisel stuff out of then. Huge amount of the item, while gated fairly well. Could need T6 which is after assembly line/fusion.
