### ISSUE TITLE
Lava fuel not work to "Large Steel Boiler"

### ISSUE THREAD

**Issue by 648643579** [GTNewHorizons/GT-New-Horizons-Modpack#3433]
https://image.ibb.co/bVLLBU/obrazek.png
Lava bucket not work (Input Bus)
Lava fluid not work (Input Hatch)
Lava cells not work (Input Bus)

Is this a bug?

**Comment by 648643579** [comment]
Yes I know what the wiki says, but I also know that there are many mods changed here.
What are the explanations for the recipe I sent?

**Comment by Bryfer** [comment]
yes it looks like a bug since NEI is lying and showing a lava bucket in large boiler
![image](https://user-images.githubusercontent.com/22825059/43986886-fe9af120-9d18-11e8-8965-9ef66f958dcc.png)

ps. we got an official wiki, but there is no page about the large boiler there.
https://gtnh.miraheze.org/
