### ISSUE TITLE
Remove RemoteIO from GTNH - too many crash related bugs

### ISSUE THREAD

**Issue by Highbeam** [GTNewHorizons/GT-New-Horizons-Modpack#3487]
#### Which modpack version are you using?
GTNH 2.0.4.6
#

#### If in multiplayer; On which server does this happen? 
Epislon
#

#### What did you try to do, and what did you expect to happen?
It WTF crashed the server
#

#### What do you suggest instead/what changes do you propose?
So basically there are multiple occasions that this mod has been crashy....

The latest happened when a Remote Interface block placed in my base caused the server to crash on restart because it wasn't linked properly.  Considering the functionality of this mod is already covered in other mods (ender chests/ender tanks/wireless energy), I suggest removing it entirely.

Other crash scenarios with the mod:

- Linking Remote Accessor to chests (other than vanilla) and attempting to use them from outside chunk range = client crash.
- Showing linked Remote Accessor in chat crashes any client that hovers over it.
- Linking Remote Interface to a GT machine and installing Energy upgrade crashes the game.  (tested only in Creative but I didn't want to try this on the server).

**Comment by Dream-Master** [comment]
the mod is Open source, if somone fix it.

**Comment by DoomSquirter** [comment]
you guys removed remoteio on epsi?  if so, did someone fix all the recipes requiring stuff from remoteIO to make?  example, player interface from random things I think has it, not sure of others....

**Comment by Bryfer** [comment]
It will be fixed properly in the next update
Until then we hope people does not need to craft these two? Items

**Comment by Dream-Master** [comment]
@DoomSquirter I am aware of it.

**Comment by XXxinsanityxX** [comment]
I would suggest just removing the recipes for the stuff that is causing issues, since remote io also adds its own water reservoir that is single block and is gated behind titanium also its probably the fastest way to get water later in the game since its only limited by how fast you can pull from it.

**Comment by boubou19** [comment]
everfull urn is also gated behind Titanium and is not limited too so as said by Highbeem, every aspect of the mod is already covered so the mod can be removed.

**Comment by richardhendricks** [comment]
That would be pretty unfair to ppl who already have the water reservoir and have not done Thaumcraft.

**Comment by Dream-Master** [comment]
yes but ender io water reservoir still exist.

**Comment by draknyte1** [comment]
It's speed limited though Dream.. 1bucket/sec..

The other two in discussion are limited only by your removal options. They offer infinite water/s, if you can drain them that fast.

**Comment by Dream-Master** [comment]
Ok but for one usefull item i wont keep a mod. Mabe we have to find an alternative.

**Comment by bartimaeusnek** [comment]
we can modify the mod so it only has the reservoir or add a recipe to convert it to an alternatertive and remove the crafting recipe, then remove the mod in a few patches...

**Comment by Dream-Master** [comment]
maybe we can fix the interface this would be the best thing. Or we need to add a gt machine producing water at a quicker rate.

**Comment by richardhendricks** [comment]
I propose a multiblock moisture trap, just line in *Dune*. :D

Upgradeable for higher speeds, output varies based on climate (even in desert should still have good output), more output at night.

**Comment by DoomSquirter** [comment]
THE SPICE MUST FLOW
wait, they drank their pee.  ewwww
no wonder their eyes glowed

**Comment by richardhendricks** [comment]
We all drink each others' pee, where do you think that water in the river came from, the sky? LOL!  I came from the city upstream of you.

**Comment by bigbass1997** [comment]
I think this mod should stay. I've used it before and it's quite helpful. The Remote Interface has a lot more capability than just item transfer. It can transfer EU (IC2 iirc) and RF, which in comparison, I don't believe there's any other inter-dimensional block that transfers EU. The EnderIO block only does RF. It can transfer essentia and AE channels!, in addition to the already stated items and fluids. All from just 1 or 2 blocks (which are justly fairly expensive).

I think the EU transfer and AE support alone makes it worth it to have; and it wouldn't be the first time where a player is given multiple options to solve a particular task. There's nothing wrong with having alternatives.

We have not had any new reports of this mod having problems for over a year. If there are still issues with the mod, then it would be nice if we could get actual crash logs for each issue, so that it can be fixed, rather than just throwing the mod away.
