### ISSUE TITLE
[RFC][Suggestion] New Lategame Content (Circuits, Generators)

### ISSUE THREAD

**Issue by bartimaeusnek** [GTNewHorizons/GT-New-Horizons-Modpack#3551]
Right now, the Game basically ends at UV, but many of the Infinity Items need higher Power or Items. This is what players have written in the Discord:

>Cheaper recipes, if you use ZPM - UHV machines
Maybe you remember, you added new types of waffles for creation circuits
I mean you can use Unknown Crystal for creation processors and it item using in Superconductor and Infinite circuits, not mainframe

> Eggs for stem cells is the dumbest thing anyone added to gt

> UHV Items are not a problem to make, the Power needed for them is, since there are no UHV Generators / Solars

> Because Infinite has one circuit, Superconductor 2, Ultimate 3
And using T Ceta biomass for more cheap recipes
Bioprocessors from T Ceta

This thread might be good to collect ideas and actual recipes for ZPM+ Stuff.

**Comment by richardhendricks** [comment]
The problem with TCeti ores has been fixed for some time, Bart fixed the runaway worldgen.

Requiring a material from a planet is kinda the core part of the game post-moon, so I don't understand the hate.

>vanilla chickens.
Maybe a new machine, CRISPR Genetic Resequencer or something that takes high tier materials and normal chicken eggs to make the mutant chickens.  Happens in the real world today with spider silk and goats.

>gate it hard and make it super power inefficient.
IMO, this just makes the pack boring and unfun.  Give it a unique way at least every few levels.

If there is a problem with obtaining the crystals/seaweeds, we should look at fixing that. IC2 crops? Some other methods?

> waffles for creation circuits
We must have this. Now.  *adds GT waffle iron*

**Comment by bartimaeusnek** [comment]
I dont see why we should just focus on ores... thats boring... hey go to stone 1 and get mineral x then go to stone 2 and get mineral y....
why dont we make it a bit different?

**Comment by 0lafe** [comment]
>The problem with TCeti ores has been fixed for some time, Bart fixed the runaway worldgen.

Requiring a material from a planet is kinda the core part of the game post-moon, so I don't understand the hate

The thing is it's at least usually of tier planets. No moon stuff for LuV, etc... Not really hate but like, there's actually high tier stuff, and mining/even enderquarries are of pretty old tiers, and there's no real need to rely on them as much. GT++ is sorta working on removing mining from late game with the void miner, I feel like the seaweed brings us in the wrong direction. 

Also didn't know it was meant to have ores, always thought the point was that it didn't. 

>If there is a problem with obtaining the crystals/seaweeds, we should look at fixing that. IC2 crops? Some other methods?

If you spice up the recipes, make it like getting a dragon egg the new way. That's the kind of stuff I think you should be aiming for, not mining stuff in the world. I don't really care if you're making an item that already exists or not, but the emphasis should be on processing chains, not exploration

>I dont see why we should just focus on ores... thats boring... hey go to stone 1 and get mineral x then go to stone 2 and get mineral y....
why dont we make it a bit different?

Because lategame ores means quarries, which isn't any different than MC or TC seaweed. Fluxed electrum needs steps to make it, which makes it more interesting than just setting up a quarry and never running out. Also, anything that's using gt machines gets faster the higher in tiers you go, but manual mining/quarries never get faster than what you get in ZPM/UV/way before this tiers really matter as much. It's like how machines take parts that come from other machines, instead of you being able to find an LV electrolyzer ore.

**Comment by richardhendricks** [comment]
Well we can make the seaweed a gate, but not a requirement for production.  Something like

seaweed + items -> bio-ooze
Bio-ooze + other items -> more bio ooze
...bunch of steps...
profit!
It would be like nether stars, once you have one you can make more

**Comment by Dream-Master** [comment]
i started  in the dev branch with new Bio circuits from ZPM to UEV

**Comment by 0lafe** [comment]
On the topic of lategame gens, solars would be nice, UHV, maybe more later. Some other ideas I had were multiblocks fluid naq gens for UHV UEV and UIV, relying on naq, enhanced naq, and naquadria for each, but a heavily HEAVILY processed fluid version. 

Fusion can go super far, like wow kinds of far, if turbines didn't suck for anything over 1-2 reactors. Infinity rotors remedied that, sort of, but it could still use some looking into. Problem is that each turbine can only output about 450,000eu/t without infinity, and I think almost twice that for infinity. That's not too bad, but when each reactor feeds a little over 8 turbines, it starts getting to be too much. The dumb problem is that there's nothing really stopping you from doing it. All the stuff is cheap enough, the problem is setting up hundreds of turbines. I ran an 8 turbine setup that fed 84 turbines with awakened draconium, and I think 39 with infinity. That's just too many turbines to handle, and when each makes less than an amp of UV, there's no real reason not to just use solars, which is so much less interesting to setup/run. If there was a fusion mk2 turbine or something. Just make it super expensive and work like the normal plasma turbines, but it takes 10x the input and makes 10x the power. Normal one is UV and this could be UEV, which is when you do start noticing the turbine space problem. Huge note here, it doesn't need to, nor should it really boost the EU from the fuel, or do anything more than do the throughout of 10 normal turbines. Especially with mk4 reactors, a 16 reactor setup would then need 157 infinity turbines or 337 awakened draconium ones, which is just too much space. Need generators for the tiers of power that we're producing is really what I'm trying to get at. 

That brings the 3 main powers from LuV-UV into UHV-UIV. Considering power generation isn't an issue for late game, and you can easily make more power than anyone could use. There's also not really useful machines past IV for any generic stuff, and you rarely use the higher tier ones for stuff (or at least don't have to). Power generation isn't really a huge issue right now, not as much as finding things to spend that power on.

**Comment by Anarack** [comment]
Couldn't you sacrifice efficiency and use lose mode turbines to get a much higher flow rate per turbine?

**Comment by 0lafe** [comment]
>Couldn't you sacrifice efficiency and use lose mode turbines to get a much higher flow rate per turbine?

So yes, but in what you lose in power, you need to make up for with again tons of multiblocks for powering more reactors. The reactors aren't much of the multiblock cost, making the plasma is fairly painful for multiple reactors, especially if you want to use lose mode turbines

**Comment by richardhendricks** [comment]
@draknyte1 said he was open to adding more turbine rotor options based on what we need, come up with some proposals for high tier turbine materials and their stats.

**Comment by yukieiji** [comment]
Since it's hard to produce UHV1A with current power generation, how about adding more productive plasmas with higher fuel values?

**Comment by 0lafe** [comment]
Bruh lol. Fusion needs a pretty hard nerf. The plasma and turbine buffs have really gotten out of hand. You can get 6A UHV in a reactor which is absurd

**Comment by GeicowithaBango** [comment]
Frankly speaking, I dont see the boost of ~5M eu/t (atlest the last time I was told) for the effort to craft Infinity Turbines. The infrastructure to craft those ingots is at a minimum. Its like investing an Amp of UV to for the WA and void miner to get amps of UHV in return. Very questionable.

**Comment by 0lafe** [comment]
They aren't meant to produce any power over 180%, but they also seem to be throughputting more than they should. Hopefully things like that, Sn plasma, and other dumb fusion mechanics will change if we ever make fusion good.

**Comment by GTNH-Colen** [comment]
> They aren't meant to produce any power over 180%

You keep saying this as if it's a fact but in reality it's just your opinion.

**Comment by GeicowithaBango** [comment]
Then what about my argument, @GTNH-Colen ?

**Comment by 0lafe** [comment]
It would be nice to see the reason behind the efficiency bonus, considering throughput does result in a better turbine, and fusion power/reactor isn't the issue. Maybe something that actually addresses the power values in relation to anything

**Comment by GTNH-Colen** [comment]
> Then what about my argument, @GTNH-Colen ?

I feel like your argument isn't taking Og gas isn't account which Bart hasn't properly balanced for yet.

**Comment by GeicowithaBango** [comment]
I actually had that conversation yesterday. I was told that the Og is so low now that It can be easily replicated (even past-nerf). Even then, my argument would still be the same; 2 amps of UV for few UHV in return seems odd. What were you thoughts for your suggested numbers?

**Comment by GTNH-Colen** [comment]
> I actually had that conversation yesterday. I was told that the Og is so low now that It can be easily replicated (even past-nerf). Even then, my argument would still be the same; 2 amps of UV for few UHV in return seems odd. What were you thoughts for your suggested numbers?

I'm aware, I was there but I think Bart wants to rebalance it so that it doesn't get replicated at all. Then you would need 2 extra MK3s just to support 1 void miner

**Comment by GTNH-Colen** [comment]
@0lafe you actually gonna say anything useful or just spam laughing emotes and hide?

**Comment by 0lafe** [comment]
I'm waiting on ice to reply to me so I can figure out if it's me or you who's being really retarded here lol

**Comment by GeicowithaBango** [comment]
afaik, the new numbers are the rebalanced ones, it went from alot of Og/t to almost nothing. 
I obviously cant tell now how much the void miner would need to run with full boosting, if thats even necessary. 

> I'm aware, I was there but I think Bart wants to rebalance it so that it doesn't get replicated at all. Then you would need 2 extra MK3s just to support 1 void miner

Then wait for Bart to change it first before doing anything with now knowledge smfh.

**Comment by GTNH-Colen** [comment]
This thread is derailing, if you want to argue further about the efficiency boosts then take it to the necessary thread. I really don't get why you believe that infinity should get the same power boost as cosmic neutronium though, it would just make it totally obsolete.

> Then wait for Bart to change it first before doing anything with now knowledge smfh.

How about you stop complaining about something that isn't finished yet, there is a reason the update hasn't made it to the officials yet because there is still work to be done. You're more than welcome to join the zeta-dev testing group and come help out if you wish?

**Comment by 0lafe** [comment]
Imagine getting Sn plasma, and then still thinking you need more efficiency and more throughput. Smh

**Comment by mitchej123** [comment]
Please keep it on subject @0lafe

**Comment by 0lafe** [comment]
The buff of ~2x EU/reactor, combined with the *insane* drop in simplicity, is quite a large buff. In combination with trinium rotors having usable durability, and SpNt existing, there's quite a lot there. 

Reactor count for a given output was lowered by 2x with Sn, then another 1.5x with 270% eff, and infra for fuel gen was essentially removed. Turbine count was drastically reduced with Ke and SpNt, with infinity being increased to what is almost a 4x reduction. 

3x output on reactors, ~2x output on turbines, ~20x reduction or so to infra (hard to calc this as simply a value). 

If you're aware of the changes made to fusion, that comment was very much on topic
