### ISSUE TITLE
Thaumcraft Research dinstinguisher.

### ISSUE THREAD

**Issue by LogicFalls** [GTNewHorizons/GT-New-Horizons-Modpack#3557]
#### Which modpack version are you using?
V 2.0.4.8
#
It is currently ambiguous in the early game to distinguish if a recipe is gated through Thaumcraft. I am requesting an NEI plugin that simply tells the user TC research is necessary on checking the recipe, no other information.

**Comment by DoomSquirter** [comment]
I had commented some time ago that they should tooltip all the disabled things in the pack.  things that even with all the research, you can't craft in the first place.  

If you did that, it'd be pretty simple to assume that anything else that you can't see a recipe for, is gated through thaum research.

BUT, since then, I've found some gt++ things that the recipes don't work correctly for and they show no recipe if you click on them.  thus that would get a bit more confusing if you then had all these other items that were back in the same boat, seemingly gated behind thaum but they aren't.

**Comment by Dream-Master** [comment]
We could add a tooltip to all items that need a thaumcraft research and not be a thaumcraft/addons mod item.
