### ISSUE TITLE
Align multiblock ore drilling rig with chunks similar to oil drill and other changes

### ISSUE THREAD

**Issue by richardhendricks** [GTNewHorizons/GT-New-Horizons-Modpack#3735]
So to help with placing anchors, and potentially adding future chunkloading support to the ore drilling rig, start looking at some changes.

- [ ] Adjust ore rig X/Z boundaries so that they are always mining whole chunks.  Similar to how oil drill works.  This way there are no "I got a few blocks sticking out over a partial chunk" problems.
- [ ] Adjust ore rig dimensions to new philosophy. 3x3 chunks for first one, 6x6, then 9x9?  Need to look into radius currently and find good middle range.
- [ ] Adjust block removal algorithm so it spends time in 1 chunk to do 1 whole layer then moves to next chunk. Not perfect, but fits in with philosophy of drilling down 1 Y level and mining it out.

**Comment by Highbeam** [comment]
I would like to add a question:

If the GT Miner changed to do chunk by chunk, can the chunks be chunkloaded automatically like the Ender Quarry as it scans through?  Only a chunk loader is needed on the miner then instead of 9 anchors.

technical:  Namikon mentioned getBlock() should load a chunk from disk?

**Comment by DoomSquirter** [comment]
ummm so nerfing the ore drill rigs like that is pretty harsh.  T2 does a 9x9 or 8x8 area.  

honestly I don't see how ppl having overlapping blocks over the chunk is a big deal.  I don't see why you'd spend time on that.  overall, I'm not thinking any code fixes need to be addressed in this at all.  it works just fine the way it is.  

acceptance that you have to take care of your own chunkloading is the primary concern and we've discussed that extensively and seems like a bad idea to implement.  given that, all the fixes you describe seem to address really inconsequential problems.

**Comment by richardhendricks** [comment]
I wasn't planning on a nerf, it was just a guess as to the current settings.  We'll make sure it isn't significantly different than before.

Limiting it to whole chunks would be a benefit, not a loss.

And if we can (eventually) do a chunk with it, it would also save on server resources since only 9+1 chunks would need to be loaded vs the whole areas.

Also, when server TPS <10, any/all performance enhancements should be on the table.

https://www.reddit.com/r/feedthebeast/comments/3lfjpp/1710_post_mortem_investigating_mystery_chunk/

**Comment by BlackFlameTNT** [comment]
How about adding new chunk loaders?

**Comment by Highbeam** [comment]
Should the higher tier ore drills mine a little faster with each tier?

I ran my T3 ore drill and it took such a long time to clear just a 9x9 area.  It should be able to do upto 13x13.

It also seems to crash for unknown reasons.  I'm guessing because it's trying to mine/mining in a chunk while it's unloaded.

I am currently loading 81 chunks just to cover the 9x9 area.  I'd probably have to load 225 chunks with 25 chunk loaders to cover the full area which is unnecessary...

If the ore drill is updated to only mine 1 chunk at a time and load the chunk (as long as controller is chunk loaded).  Then we're only looking at 9+1 at any time as was suggested.

**Comment by richardhendricks** [comment]
The speed does increase with tier
Tier 1 - 960 ticks
Tier 2 - 800 ticks
Tier 3 - 640 ticks
Tier 4 - 480 ticks

We can discuss if those are fair or whatever.

Size increase, and speed difference vs tier 1
T2 - 2.46x, 1.20x
T3 - 4.6x, 1.50x
T4 - 7.36x, 2.0x

As you go up in tiers, I think the speed can be increased more - higher tier players need more output.  How does this sound?

T2 - 1.5x faster, total time 1.64x T1
T3 - 2.0x faster, total time 2.3x T1
T4 - 3.0x faster, total time 3.68x T1

So the larger drills will still take longer overall, but have improved output velocity.

**Comment by richardhendricks** [comment]
Might as well chunk-align singleblock drills as well, and use similar chunk-by-chunk ore removal. long term would like to add self-chunkloading as well as active area chunkloading via Forge tickets.
