### ISSUE TITLE
Nerf neutronium shaping through smelting->moulding

### ISSUE THREAD

**Issue by DualBallers** [GTNewHorizons/GT-New-Horizons-Modpack#3820]
Right now neutronium takes a lot of time and energy to shape to all the different plates/rods/gears and so on, but this can be completely circumvented by using a Fluid Extractor and transfer the molten neutronium to a Solidifier with the correct shape molds. 
This is done in a couple of seconds at the EV machine tier, and for almost no EU. 

I would suggest that this process is nerfed so that the time/energy spend is comparable with the "normal" process of shaping plates/rods/gears.

I think the full nerf should be put on the fluid extraction of the neutronium. 
Increase the required tier and energy consumption here, and let the solidifying be as it is.

**Comment by 0lafe** [comment]
I always saw that as encouraging the fluid versions because it was the fusion product, which is even more relevant with fusion changes making Nt fusion worth it. Making it longer is a good idea, but the times in the bender/extruder/etc.. are a little much imo. Maybe like 4-16x current times, or make it need higher tier stuff (LuV+?)

**Comment by Dream-Master** [comment]
The time difference is because I set some recipes manually and some are autogenerated. Autogen calculates mass and Neutronium is in code much more massive than all the other materials. I could add all recipes to a manual time to make it More balance or let the fluid one short to force players use fusion.

**Comment by Teirdalin** [comment]
It honestly feels odd for Neutronium to be melted down into fluid.

**Comment by Hakameda** [comment]
Fusion makes it a liquid though. I'd assume it cooling into shape is not that bad. You have to ebf it to then melt it or use fusion. Encouraging fusion for it instead of cheaty ores would be better

**Comment by DualBallers** [comment]
As I see it, the fix in 2.0.6.0 is a buff?
It looks like it is now easy to shape neutronium both through moulding and through all the regular machines. 
Was the idea not to let neutronium keep its density and make shaping difficult all the way around?

**Comment by 0lafe** [comment]
That's probably not the way to do it. I'd personally like to see it just take more, but reasonable, EU to mold it, and not let it be made other ways/keep the old times of like 2500s. So like LuV 30s to make a rod with the fluid, or LuV 2500s to make it with the extruder. Mostly because I think I remember something about fluid extracting/solidifing parts being the best way to make them, so why not encourage that and allow neutronium to fit in better that way.

**Comment by Dream-Master** [comment]
so you want i revert it ? @DualBallers @0lafe

**Comment by 0lafe** [comment]
My vote is for changing the neutronium recipes to the times from before 2.0.6, but the EU/t changed to LuV. So bending a plate is like 2500s at LuV and solidifying it is like 5s at LuV. Then add a huge time gate on the fluid extractor recipe to encourage fusion production of it

**Comment by Hakameda** [comment]
Should be faster in liquid form but not the extraction process itself. To
encourage using fusion to make parts

**Comment by Teirdalin** [comment]
The reason fluid solidifying was the best way to make them to begin with is because it auto-genned it to be ridiculously easy in contrast to all other forms of forming it.  Maybe we could lock fluid solidfier recipes for neutronium behind either ZPM or UV though as LuV is rather early.

**Comment by Dream-Master** [comment]
@0lafe autogenerated recipes cant be changed they can only be overriden.

**Comment by 0lafe** [comment]
>maybe even UHV as we do lack a bit of UHV recipes that would make that tier more worthwhile

But it's a UV material, so making it UHV probably would cause an issue or two 

>I honestly don't see much logic in liquifying neutronium again as the natural form of neutronium in a star is as a liquid; so I'd think the harder part logically should probably be solidifying it. Or maybe the harder part would be liquifying it considering the temperatures- in which case I still would think a LuV fluid extractor would be too early for that.

Yeah the mk3 reactor does that, and even has a tool tip about a star or something 

>@0lafe autogenerated recipes cant be changed they can only be overriden.

Maybe do all the Nt ones by hand then? Remove the current ones and only have fluid ones maybe? 


Super related, I'm in favor of removing pure Nt ore and using some more interesting/complicated/annoying method of Nt pre mk3 then buffing the fusion recipe to something similar to the return on the current ebf recipe, as right now it's like 2h per ingot or something crazy

**Comment by Hakameda** [comment]
That related bit, would be best to remove all fusion ores and buff fusion
outputs

**Comment by 0lafe** [comment]
Well, maybe. Remove europium yay, remove pure neutronium yay, but the mk3 reactor is late UV, gating UHV. Either Nt can't be the UV material, the mk3 reactor needs to be ZPM, or neutronium needs to be obtainable pre mk3. What about americium like recipes? So you can make Nt in mk2 but hard recipe, so you get an easier one with the mk3 once you're getting into the large Nt sinks

**Comment by Dream-Master** [comment]
ok i need a step by step info what i need to do here.

**Comment by richardhendricks** [comment]
@0lafe @Hakameda @Teirdalin Please make a checklist for Dream.
