### ISSUE TITLE
Tceti E Seaweed Dilemma (Bio-Circuits)

### ISSUE THREAD

**Issue by ScriptedPiky** [GTNewHorizons/GT-New-Horizons-Modpack#3852]
Currently, in the 2.0.6.0 version of GTNH, there exist many somewhat new recipes utilizing production of Tceti E Seaweed in the form of Bio-Medium. However, there aren't that many alternatives to obtaining this seaweed, aside from the main objective of going to the planet Tceti E and harvesting seaweed from there. Although that makes exploring and harvesting a task for the player to do. And while you may get a bunch of seaweed in a short time, it does require the player to go to the planet in some way, harvest large amounts of seaweed, and leave the planet desolate of its main resourceful purpose. Now if the player did not want to go this route and leave the planet to stay in its natural form, they would have to get Tceti E Seaweed from other sources. For instance, in a previous version, you might've noticed that a peculiar bee could produce Tceti E Seaweed at a very rare chance (0.01% or 0.001%). This currently does not exist in the latest version (possibly bugged or unintentional?). Adding to this, you would need exactly 64 Tceti E plants to extract into 1 seaweed.

Additionally, Bio-Circuits require Tceti E Seaweed in the form of Bio-Medium (16 Tceti E Seaweed, 16 Oriharukon, 16 Mysterious Crystal, 4 Cosmic Neutronium, 1 Tiny Infinity, and 4000L of Growth Medium to create 4000L of Bio-Medium). To create a single BioProcessing Unit (Bio CPU) for the first circuit (Bioprocessor - ZPM tier), it requires exactly 32 Biocells, each cell requires 1000L of Bio-Medium, 1 circuit board that costs 500L (you will have a leftover of 15 boards, recipe costs 8000L and makes 16 circuit boards). Then another 500L of Sterilized Bio-Medium to make the Bio-CPU. You now have a single unit that cost a whopping 128+ seaweed. As you can already tell, this makes the recipe entirely ridiculous and almost infeasible to accomplish on an industrial scale.

Furthermore, to create a single Bio Mainframe (UEV, final tier), you need to acquire 1024+ Tceti E Seaweed (65,536 normal Tceti E plant life to extract) for a single UEV circuit.

Here are some suggestions, relieve the amount of Tceti E seaweed required from the recipe and add other means of obtaining seaweed that does not force a massive exhibition of destroying a planet for its seaweed. Allow the Tceti E Planet Bee to produce seaweed again in some shape or form that does not rely extremely heavily on the Random Number Generation aspect (example: anything below 1% or 0.1%). Or another recipe that creates seaweed in a respectable amount. And while I do respect that the seaweed is meant to be a late tier resource, it should not be forced upon the player to extract an inconceivable amount of seaweed from a planet that already is possibly desolate on multiplayer servers. The Bio-Circuits should be obtainable, but not ludicrous to achieve.

**Comment by 0lafe** [comment]
Totally on board with it needing a change, but I don't like the bees for high tier stuff tbh. I'd rather see a mutagen/growth medium/new thing, type duplication recipe for it. So like 16 seeweed+72L growth medium = 128 seeweed. Like it just grew it. Can use EU/t and stuff that's high/other fluids and items to keep the tiering. Better than bees imo, and I never really wanna see bees as the only/best resource producer, especially for something T8+

**Comment by Dream-Master** [comment]
From a bee that produce seaweed I hear the first time. Sure I can add a seaweed bee.

**Comment by ScriptedPiky** [comment]
> From a bee that produce seaweed I hear the first time. Sure I can add a seaweed bee.

Can we also add @0lafe's idea as well? For more means of producing seaweed other than a bee (bees are nice, but they take a lot of work). 
Going to add onto 0lafe's idea too. There could be a chemical reactor or mixer recipe that uses seaweed and some other materials and "grows" it by multiplying the output. Perhaps it could use tiny infinity dust and other high tiered materials for it?

**Comment by Dream-Master** [comment]
ask @bartimaeusnek for a seaweed crop

**Comment by 0lafe** [comment]
A crop is as bad as bees, neither should be making high tier resources imo. Ones a stick and the other goes in a wood box. A simple dupe recipe in the LCR or something would be great.

**Comment by bartimaeusnek** [comment]
i dont see the issure on harvesting it, since it can be automated with OpenComputers...

**Comment by boubou19** [comment]
IMO the Tceti E seaweed should behave like sugar cane: you cut the first block and all the others drop instead of disappearing

**Comment by septemberWaves** [comment]
0lafe's idea is probably the most logical in my opinion. Just like how there are duplication recipes for other inconvenient products (I believe nether stars are one such product, if I recall correctly), having one of these kinds of recipes for Tceti E seaweed seems to make sense. If a substance is needed in the thousands for each individual item of a type which is also needed in bulk, I think it makes sense for players to be able to scale up production of the base substance (in this case, the seaweed) with GT machines - allowing the option to increase voltage tier rather than increasing physical space required - rather than forcing huge numbers of industrial apiaries or vast areas of farmland.

**Comment by ScriptedPiky** [comment]
Here is a change that I thought of for the Raw Biomedium recipe. Currently, in the official GTNH 2.0.6.8 modpack, there exists this recipe to create Raw Biomedium, a crucial component. 
![seaweed2](https://user-images.githubusercontent.com/41557212/52919178-7d590980-32b4-11e9-8a93-8f4efb7f9d1f.PNG) The materials shown: 16 Mysterious Crystal dust, 16 Oriharukon dust, 4 Cosmic Neutronium dust, 1 tiny pile of Infinity dust, 16 TCetiE-Seaweed Extract, and 4000mb of Raw Growth Medium. This then makes 4000mb of Raw Biomedium. However, this recipe exists:
![image](https://user-images.githubusercontent.com/41557212/52919238-01ab8c80-32b5-11e9-8135-a30a3cacd22c.png) Thus, requiring an absurd amount of seaweed extract just for these Bio-Cells.

Then comes my preposal of how this can change. 
![seaweed](https://user-images.githubusercontent.com/41557212/52919256-3c152980-32b5-11e9-850a-8cdc506f7ea1.PNG) Here is a crude way of showing the change. Here, the recipe cost, including the Raw Growth Medium which is at 64,000L/mb worth; all of which (except the tiny infinity) is increased by a large amount, as well as the output of the Raw Bio Medium.

But this doesn't stop there. Due to the nature of the Bio CPU cost, requiring 32 Bio Cells shown here:
![seaweed4](https://user-images.githubusercontent.com/41557212/52919373-bb572d00-32b6-11e9-9b30-af1942295513.PNG) It is noticed that before, you need 32 buckets worth of Raw Bio Medium, or rather 128 TcetiE-Seaweed Extracts and 8 tiny piles of Infinity dust (8/9 worth an entire infinity ingot!). Then comes this part of the change to the Bio Cells to reduce the amount of Raw Bio Medium required. Instead of 1:1 scale, it's now a 1:4 scale in some sense. So it will only require 2,500L/mb worth of Raw Bio Medium, 500L/mb of that turned into Sterilized Biomedium for the Bio CPU:
![seaweed5](https://user-images.githubusercontent.com/41557212/52919475-b6df4400-32b7-11e9-94b2-e3ce28f6049a.PNG) This way, it still requires the player to obtain an incredible amount of Seaweed to make the circuits, but it no longer is utterly ridiculous to acquire and is more logical to obtain.

**Comment by Dream-Master** [comment]
With bartworks we have batter ways to redesing it. @ScriptedPiky @0lafe @boubou19 @bartimaeusnek 
any recipe suggestions?

**Comment by 0lafe** [comment]
Spluff made an extensive bio thing for a good amount more than just bios, but lays frameworks for tons of new stuff. I'd hold off suggesting stuff until that's implemented as it's really a good system, and will give these things like 500000 new steps but mostly automatable stuff with new multi and items.

**Comment by Anarack** [comment]
Heres My suggestion on this as I like the concept of the vat It uses that, same eu cost atm

This is basically no possible to obtain in the bulk needed to make bio and wetware circuits viable even if you have all the other materials needed(
Recipes should be based around the bartworks vat as it is not really used and introduces a new machine, if late to the pack with specific requirements to operate well
Recipes should be more efficient if the player invested in bees, crops, or both for bio specialness 


Suggested crafting chain

may need to make multiple chains to support bio medium needs

Step 1 Prodce TCetiEis Fucus Serratus petri dish via biolab (not entirly sure this can be obtained right now due to strange fluid being needed)
assuming perfect chances
requires 40 seaweed
9e9 EU
1000 seconds per sample

if swapped for the extract
2,560 taceti seaweed 
1000 seconds-7200 depends how much power is tossed at the problem
46e9 EU


Step 2 vat to produce bio medium 

Input (taken from original recipe)
 Fucus Serratus petri dish
Raw Growth Medium 4000L
16 Mysterious Crystal dust (Don't see the point to this as its used later for bio cells)
16 Oriharukon dust
4 cosmic neutronium	
1 tiny pile of infinity

use crops/bees to boost some as well
Reward doing both sides and farming them

Output
4000 L raw Bio Medium 10% boost with crops/bees 20% with both? may be a tad too low

Energy cost (Not fully sure on this) (haven't heard any issues with energy costs but not fully sure how fast this should be)
150,000,000 total
500,000 Eu/t
15 seconds

For reference wetware/bio circuit cost by eu to produce bio materials and uum
Wetware
LuV 	2.38e10 EU
ZPM	5.02e10 EU
UV	1.06e11 EU
UHV	2.12e11 EU

Bio Circuits
ZPM	2.59e11 EU
UV	5.21e11 EU
UHV	1.05e12 EU
UEV	2.11e12 EU

**Comment by Prometheus0000** [comment]
Can these and related issues be closed now? You can make the seaweed but I have no idea if it's balanced or whatever
