### ISSUE TITLE
[suggestion] add a filter to the electric prospector's scanner

### ISSUE THREAD

**Issue by boubou19** [GTNewHorizons/GT-New-Horizons-Modpack#3922]
The electric prospector's scanner is a powerful item and in normal dimensions its use is really easy. 
But in a dimension like Deep Dark it becomes unreadable:
![image](https://user-images.githubusercontent.com/12850933/50179611-c1a54900-0307-11e9-8ac0-32202777fe83.png)

My suggestion is to add an option to let the player mask the ores he doesn't want to, or at least let the player recolor the ores he want to mine.

**Comment by richardhendricks** [comment]
IS the Deep Dark really a "I want to mine a specific ore" dimension though?  I see it more as a "I am going to mine 500x500 chunks" instead, so the prospector is pretty irrelevant.

**Comment by 0lafe** [comment]
Yeah that's what it is lol, I only scanned the DD once and it was to show someone what's there. Maybe once you first get there, but even lategame it's faster to just self quarry than check for stuff

**Comment by DualBallers** [comment]
Instead of a filter or recolour function, I think it would be great if you temporarily could highlight/point out a specific ore by clicking/hovering over the ore name. Highlighting could be a box/cross/marker on the ore in the scanner map. 

To use the example above - adamantium, arsenic, borax, cassiterite, and europium has more or less the same colour, and the same colour as the background, so it's really hard to pinpoint exactly where to go when you need a special ore. 
This is also an issue in many other dimension where ore colours are very similar and you have to guess where to go.

**Comment by Dream-Master** [comment]
@bartimaeusnek is this possible to implement?

**Comment by Dream-Master** [comment]
@richardhendricks @bartimaeusnek is there any change needed and who will code it?

**Comment by richardhendricks** [comment]
I don't think it would be too hard to implement.  1H2019. :D

**Comment by DualBallers** [comment]
IMO this is still are pretty relevant suggestion, to have some very basic form of filtering or highlighting of the specific ore you are searching for (especially when colour is the same as the background).

**Comment by Dream-Master** [comment]
I just close all old issues. If we found someone can implement this why not.

**Comment by Prometheus0000** [comment]
See https://github.com/GTNewHorizons/DetravScannerMod/pull/12
