### ISSUE TITLE
[Balance][Suggestion] Crop and Comb differences

### ISSUE THREAD

**Issue by flockenobsidian** [GTNewHorizons/GT-New-Horizons-Modpack#4116]
#### Which modpack version are you using?
2.0.6.8
#
#### What do you suggest instead/what changes do you propose?
Right now combs are superior when creating Materials, they only take in 9 Combs for 4 Purified Ore, while Crop drops take in 16 drops for 1 Purified Ore.
![2019-02-18_11 50 08](https://user-images.githubusercontent.com/41200844/52946214-cc19a880-3373-11e9-9300-1841a4375473.png)
![2019-02-18_11 49 46](https://user-images.githubusercontent.com/41200844/52946215-ccb23f00-3373-11e9-9868-bbfc8ad5fab8.png)

In my opinion crops are harder to get then bees. They take in way more time while you cant make anything else while breeding them, compared to bees, which are relativly simple. Both might be random, but crops are way more random and take more time. This is why i think that crops -> ore should be at least the same input/output like bees, or better.

**Comment by boubou19** [comment]
maybe lower the amount of crops needed to get purified ores? because you need a stack of crops to equalize 9 combs it's a bit too much imo.

**Comment by 0lafe** [comment]
Crops are also easier to spread out once you got them. They just need some sticks, bees need IAs frames, power and some type of inventory management of them.

**Comment by boubou19** [comment]
they don't need power if you don't use industrial apiaries as far as i know

**Comment by bartimaeusnek** [comment]
@0lafe thats just not true. you need power if you want an automated crop farm, and on top of that, high stat crops are way harder to automate, due to the requirement of fertiliser, air quality and water (or they will simply despawn). Bees on the other hand can be set up in an Alvery and forget. (when you use 2-3 enderIO conduits and a trashcan for drones) In addition, Bee breeding is quite linear which makes it easy to get what you want, while crops are more random than anything else in the pack and have the most specific needs of anything aswell. IMO they should be at least double as effective as bee combs.

**Comment by richardhendricks** [comment]
I disagree, getting massive amounts of outputs from crops isn't that hard. While getting a target crop might take some time, you get so many other incidental crops pretty easily. I have bauxite, titania, quantaria, etc crops while never "targeting" them. 

It is difficult to claim one way or another that one is easier/harder than the other due to just how different the two systems are in reality. And the difficulty involved also varies with the tech level of the player.

Crops are "easier" IMO for several reasons
1. Easy to increase size of mutation fields.
2. Even a poor seed can be placed in production fields while breeding better versions.
3. Automation with Forestry Farms has low tech requirements vs alveary or industrial apiary or world accelerators and accompanying infrastructure. "hardest" part would be automating fertilizer production with a pyro.
4. Forestry farm supports ludicrous amounts of crops, or even multiple crops, from a single farm. Farm blocks/stone bricks is a really low barrier to increase the size of the farm.
5. Byproduct seeds that can be kept/used for other things. 
6. Bees have more/varied environmental requirements vs seeds. (Maybe we could add them, but people would stab me with pitchforks no doubt)
7. Bees require finding queens, while all basic crops are fairly easy/trivial to find and you don't *require* different crops - you could breed up everything from 1 crop type if you really wanted.

The only real thing that makes crops "harder" imo is the amount of babysitting required vs bees.

All this said, does that mean bees *should* be 7.1x "better" than crops?  I dunno.  

If TPS on servers is a concern, I could see improving the crops output so that massive fields aren't required.

If I had to do it all over again, I would do crops over bees if I am starting at low tier, and bees if waiting until later tiers.

**Comment by boubou19** [comment]
i will add that you can use world accelerators on crops too (TE mode)

**Comment by bartimaeusnek** [comment]
>* Easy to increase size of mutation fields.

Once you have an alveary youll have so many drones that you can convert any bee to your desired bee aswell.

>* Even a poor seed can be placed in production fields while breeding better versions.

Same goes for bees

>* Automation with Forestry Farms has low tech requirements vs alveary or industrial apiary or world accelerators and accompanying infrastructure. "hardest" part would be automating fertilizer production with a pyro.

alveary. does. not. require. any. tech. but. the. carpenter.

>* Forestry farm supports ludicrous amounts of crops, or even multiple crops, from a single farm. Farm blocks/stone bricks is a really low barrier to increase the size of the farm.

true, bees have alverays

>* Byproduct seeds that can be kept/used for other things.

so can be drones which are an essential part of bee breeding.

>* Bees have more/varied environmental requirements vs seeds. (Maybe we could add them, but people would stab me with pitchforks no doubt)

initially, yes, with genetics(HV) or gendustry (LuV+), nope. you can create a bee that has max stats and **NO** difficult special requirements and still will produce its "special" product. 

>* Bees require finding queens, while all basic crops are fairly easy/trivial to find and you don't _require_ different crops - you could breed up everything from 1 crop type if you really wanted.

due to the pure amount of rock hives and hives on the surface this isnt really an issue

**Comment by richardhendricks** [comment]
> > * Easy to increase size of mutation fields.
> 
> Once you have an alveary youll have so many drones that you can convert any bee to your desired bee aswell.

I'm talking getting a target seed, not making more seeds. Drones can change more queens to the source bees, but you can't automate breeding a specific bee, you have to still manually look at it. I'm assuming before the genetic machines.

> > * Even a poor seed can be placed in production fields while breeding better versions.
> 
> Same goes for bees

But there isn't a "poor" output bee. IE, if I am crossing stickreeds to get to better stats and I get sugarbeets or coppons or whatever, those are crops that produce outputs now.

> > * Automation with Forestry Farms has low tech requirements vs alveary or industrial apiary or world accelerators and accompanying infrastructure. "hardest" part would be automating fertilizer production with a pyro.
> 
> alveary. does. not. require. any. tech. but. the. carpenter.

An alveary by itself isn't that useful, really. You need frames, and you'll need a lot of alvearies and frames to get any sort of decent output.  Not saying it's hard, but compared to a forestry farm?  Now that we know you can just throw a new layer onto it for essentially "free"? Look at the farms 20 layers tall players are abusing to farm XP for buckets.

> > * Forestry farm supports ludicrous amounts of crops, or even multiple crops, from a single farm. Farm blocks/stone bricks is a really low barrier to increase the size of the farm.
> 
> true, bees have alverays
> 
> > * Byproduct seeds that can be kept/used for other things.
> 
> so can be drones which are an essential part of bee breeding.

Yeah but you aren't going to randomly get a redstone drone while breeding for coal bees!

> > * Bees have more/varied environmental requirements vs seeds. (Maybe we could add them, but people would stab me with pitchforks no doubt)
> 
> initially, yes, with genetics(HV) or gendustry (LuV+), nope. you can create a bee that has max stats and **NO** difficult special requirements and still will produce its "special" product.
> EDIT: also alveary can disable rain, night and biome stuff, these mods can also disable all temp/biome/time requirements.

True. 

> > * Bees require finding queens, while all basic crops are fairly easy/trivial to find and you don't _require_ different crops - you could breed up everything from 1 crop type if you really wanted.
> 
> due to the pure amount of rock hives and hives on the surface this isnt really an issue

**Comment by bartimaeusnek** [comment]
>I'm talking getting a target seed, not making more seeds. Drones can change more queens to the source bees, but you can't automate breeding a specific bee, you have to still manually look at it. I'm assuming before the genetic machines.

isnt this issue about the UUM recipes, which are basically one tier above the genetic machinery (first genetic machinery can be build in MV, UUM recipes are HV)?

>But there isn't a "poor" output bee. IE, if I am crossing coppons with stickreeds to get better stats, even if a new seed is not better than my best, I can throw that in a production field and get more coppon leaves.

If i get more drones i can switch one of my freshly caught queens and throw that in an old alveray...

>An alveary by itself isn't that useful, really. You need frames, and you'll need a lot of alvearies and frames to get any sort of decent output. Not saying it's hard, but compared to a forestry farm? Now that we know you can just throw a new layer onto it for essentially "free"? Look at the farms 20 layers tall players are abusing to farm XP for buckets.

>When the Alveary were added to Forestry it was given the efficiency of the Apiary and the Apiary was reduced with 90%. At the same time Sengir also added frames and by adding 3 frames to the Apiary the efficiency is buffed up to 70% of the Alveary. 20% per frame.

I'd say 90% increase of production is useful. Also a forrestry farm needs AT LEAST fertilizer and water while the alvery does not. Doesn't mean that im pro-20+ tall high, multi-layer forestry farms. They are bugusing imo and we should limit that to 5 layers max. But thats another topic.

> Yeah but you aren't going to randomly get a redstone drone while breeding for coal bees!

you wont get weeds or simple berries / potatos / carrots aswell...

**Comment by richardhendricks** [comment]
BTW, it is 9 leaves + 1 crushed -> 4 purified right now, so if we do buff the no-crushed pathway, we need to change the crushed pathway as well.

**Comment by flockenobsidian** [comment]
@richardhendricks why? in chemical reactor its the same for crops and bees... but not in uum...
![2019-02-20_23 17 46](https://user-images.githubusercontent.com/41200844/53128735-d00d1c80-3565-11e9-8aaa-d678372e047d.png)
![2019-02-20_23 17 47](https://user-images.githubusercontent.com/41200844/53128736-d00d1c80-3565-11e9-8e81-1077fc3f97b0.png)

**Comment by richardhendricks** [comment]
Ah, I didn't know we added that for bee combs.  Change it I guess to make them identical.  If it is too OP one way or another we can change it later.

How much UUM does it take for the recipe?

**Comment by richardhendricks** [comment]
@Dream-Master I think we all agree to make the recipes same.

**Comment by Dream-Master** [comment]
all recipes are autogened with mass wight. What need to be changed exactly? @richardhendricks

**Comment by richardhendricks** [comment]
The only concern is 16 vs 9.  I think I've found where it's done in GT_MAchineRecipeLoader, will look this weekend.
https://github.com/GTNewHorizons/GT5-Unofficial/blob/experimental/src/main/java/gregtech/loaders/postload/GT_MachineRecipeLoader.java#L2164

There is something wonky since it shows there that any 1 crushed -> 4 purified should also get the molten byproduct, but it doesn't seem to always work.  IE malachite does give you copper, but not chalcopyrite.  Need to investigate.

https://github.com/GTNewHorizons/GT5-Unofficial/blob/experimental/src/main/java/gregtech/api/enums/Materials.java#L1161

**Comment by 0lafe** [comment]
the 9 was preserved from bees 9>1 recipe I think? I also feel like I might have advocated lower bee recipes, im not sure. However, bees also got essentially a 2x speed bonus from the new speed trait right? So 16 combs now, is a lower than getting 9x used to be. So maybe keep both recipes at 16? Bees can be that low with new trait, and I always feel like we should keep crop stuff sort of high simply with how many you can make vs bees.

**Comment by richardhendricks** [comment]
Please read Barts comments above, he makes good points in favor of leaves needing only 9+uum instead of 19.
