### ISSUE TITLE
Magical Energy Absorber/Converter not accepting fuel.

### ISSUE THREAD

**Issue by drayath** [GTNewHorizons/GT-New-Horizons-Modpack#4144]
#### Which modpack version are you using?
2.0.6.8 (Single Player)

#
#### What did you try to do, and what did you expect to happen?
In Magical Energy Absorber & Magical Energy Converter, add items that NEI shows a Fuel Value for Magical Energy Absorber; They should be processed and generate power.

#
#### What happens instead? (Attach screenshots if needed)
Won't accept most items as fuel
Void Metal Ingot - Not Accepted (worked prior to update in Magical Energy Converter)
Mercury ball - Not Accepted (worked prior to update in Magical Energy Converter)
Mercury fluid - IS Accepted
Void metal fluid - Not Accepted (just in case only worked with fluids)
Enchanted Books/Items - Is accepted in Magical Energy Absorber

#
#### What do you suggest instead/what changes do you propose?

Either make it work or if a deliberate design change don't show as fuels in NEI and update descriptions/thaumcraft text to describe what should be used as fuel.

**Comment by Dream-Master** [comment]
that error is new. will investigate

**Comment by Dream-Master** [comment]
@drayath are you on discord?

**Comment by Dream-Master** [comment]
leagrisToday at 9:56 PM
Yes, it is deliberate because now it does not need aspect beans as fuel but directly uses aspect gas from jar.
It absorb the jar content like the infusion crafting
So if you want to use your beans as fuel, you have to distillate them into gas and jar the gas
DreamMasterXXLToday at 9:57 PM
so it sucks the gas in and generate eu ?
leagrisToday at 9:57 PM
yes
did you see how Thaumcraft infusion altar works?
it works exactly the same as the infusion altar
DreamMasterXXLToday at 9:58 PM
ah ok thanks

**Comment by Dream-Master** [comment]
https://www.youtube.com/watch?time_continue=34&v=ZzuyhP1Xs-A

**Comment by Dream-Master** [comment]
leagris will make a fix for the missing part.

**Comment by bartimaeusnek** [comment]
https://github.com/GTNewHorizons/GT5-Unofficial/pull/178

**Comment by bartimaeusnek** [comment]
wait this is for the other machine, that one that uses magic items as fuel @Dream-Master

**Comment by Dream-Master** [comment]
@bartimaeusnek I chat with leagris yesterday and she will fix it asap
