### ISSUE TITLE
Recommendation Mod MoarSigns

### ISSUE THREAD

**Issue by shawnbyday** [GTNewHorizons/GT-New-Horizons-Modpack#4192]
#### Which modpack version are you using?
2.0.6.7c
#
#### If in multiplayer; On which server does this happen? 
Private
#
#### What do you suggest instead/what changes do you propose?
Just a mod that adds various signs. Aesthetics recommendation.

**Comment by Dream-Master** [comment]
@shawnbyday i think we have enough mods. Nei loads slower and slower and we have enough signs from Biblicraft and other mods.

**Comment by shawnbyday** [comment]
That's fair. You can close this if you want to. Thanks!

**Comment by Sederien** [comment]
Re-opening as there was some interest in Discord when discussing the state of signs:

![image](https://user-images.githubusercontent.com/66249229/147378242-4cf4c34b-befe-4291-a161-2eddc7dba590.png)

Well, turns out there is. And it's a LGPL 1.7.10 licensed mod covering a variety of signs.

https://www.curseforge.com/minecraft/mc-mods/moarsigns

```
ModPack Usage?
You are free to use my mod in your mod pack, make sure to link to this thread.
```

https://github.com/GoryMoon/MoarSigns/tree/1.7.10

Loaded up in 2.1.2.0 with no noticeable impact on load times (thanks in large part to the awesome work the team has been doing on script/recipe load updates). Have investigated further and found the following.

Pros: Pretty much drag and drop support in GTNH, other than some minor tweaks needed. Has a better interface than Bibliocraft signs. Adds metal signs, otherwise not existing. Uses most of the major metals in GTNH out of the box.

![image](https://user-images.githubusercontent.com/66249229/147379418-f8f6d3f1-8d53-4c79-a682-9a5cc543fc23.png)
(Note, Bibliocraft can actually do colors and icons, but I didn't know that when I made the shot because of the interface. Credit to Pao here.)
vs.
![image](https://user-images.githubusercontent.com/66249229/147379002-794251f2-d0cf-43b9-8d26-7e4660d6b3de.png)

Cons: Unless tweaked, adds unnecessary nuggets for tin, lead, copper, and refined iron. (made by hand) -> Could be tweaked to use typical nugget production or simply modify the metal signs to need full ingots. Additionally, wood signs use planks, not the greg recipes for plank (singular).

Otherwise, seems pretty lightweight, easy (comparatively) to add, and adds some great options to signage outside of just... wood.

Please reconsider.

**Comment by bombcar** [comment]
This looks better than bibliocraft signs and I like it and could work on gregified recipes (should be pretty straightforward)

**Comment by Sederien** [comment]
If you gregify this, I might recommend for metals limiting to only the ingot recipes for 9x metal signs (and commenting out the nugget recipes for single signs entirely) since not every metal used has a nugget by default and the mod otherwise adds a couple shapeless by hand nugget from ingot recipes. This probably includes emerald (if in).

Tool box could easily be shifted to iron/bronze to allow for early use.

Thanks for taking another look.

**Comment by bombcar** [comment]
I'd probably replace ingots with plates and involve screws somehow - but I need to test and run it.

**Comment by Sederien** [comment]
There are absolutely two open spots for screws (currently two rows of material atop one stick). Wood, as you will see, is currently planks, not the sawed plank.

Adding screws there as well would neatly keep them separate from the current oak sign recipes in game.

As a bonus, bibliocraft signs also recognize and accept MoarSigns as a recipe input for their larger sign space.

**Comment by shawnbyday** [comment]
I remember I looked into this but we are sort of compiling recipes instead of crafttweaker-ing them so I didn't really feel like doing it. Plus it doesn't support a lot of GT materials by default (which makes sense). If we don't need to add new textures for every GT material and just limit it to what's in the moarsigns it would be pretty easy. I just didn't feel like doing it all back when I opened the issue lol. I agree though...oak sign...biblio sign...meh.

**Comment by bombcar** [comment]
If @Dream-Master or @mitchej123 want to make a fork I’ll take a cleanup/recipe balance pass.

**Comment by bombcar** [comment]
If anyone wants to try (and report issues) https://github.com/bombcar/MoarSigns/releases/download/1.2.5/MoarSigns-1.7.10-1.2.5.jar should run against the latest GTNH - recipes are not yet updated but it builds.

**Comment by Dream-Master** [comment]
https://github.com/GTNewHorizons/MoarSigns

**Comment by shawnbyday** [comment]
> If anyone wants to try (and report issues) https://github.com/bombcar/MoarSigns/releases/download/1.2.5/MoarSigns-1.7.10-1.2.5.jar should run against the latest GTNH - recipes are not yet updated but it builds.

I should be able to look at it tonight and tomorrow. I've been putting off pulling the latest zeta anyway so probably a good time. Will report back.

**Comment by bombcar** [comment]
There's at least one known GUI crash when using the toolbox

**Comment by bombcar** [comment]
[crash-2021-12-29_14.32.53-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/7790763/crash-2021-12-29_14.32.53-client.txt)

**Comment by shawnbyday** [comment]
> There's at least one known GUI crash when using the toolbox

Okies. Do you have a crash report from that crash yet? I've never used the toolbox in the past on that mod but can definitely grab it.

**Comment by Sederien** [comment]
If that's my log, note... that was not on using the toolbox, but rather on placing a sign (at which point the write sign GUI should be shown). The Tool Box itself did not cause a crash, but I suspect it would if a sign was placed (can't yet) and you attempted to edit the sign loading up the GUI.

**Comment by shawnbyday** [comment]
Grabbed MoarSigns-1.7.10-1.2.4.jar from CurseForge and tested sign placement and toolbox usage to see if that crashes too. That did not crash.

The GTNH build 1.2.5 did crash on sign placement. Can't test the toolbox without the sign placed down so was unable to test that in our build.

**Comment by bombcar** [comment]
I think I know where this causes but need to figure out what to do about it

**Comment by bombcar** [comment]
<img width="460" alt="image" src="https://user-images.githubusercontent.com/533931/147712628-eb6a3e93-40f0-4f19-a779-52c26663b777.png">

Try this:  [MoarSigns-1.7.10-1.2.0-9-g2b173d0.zip](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/7791087/MoarSigns-1.7.10-1.2.0-9-g2b173d0.zip) (rename from .zip to .jar, don't actually extract it)

**Comment by bombcar** [comment]
Ah, toolbox is how you edit and works hmm.

**Comment by shawnbyday** [comment]
Cool I'll test here in a sec.

**Comment by Sederien** [comment]
> Ah, toolbox is how you edit and works hmm.

Yup. I'm out and about right now, but the tool box has editing, copying, rotation, movement, and preview functionality off the top of my head. It does need a placed MoarSign to interact with, though as it does not work on non-MoarSigns.

**Comment by shawnbyday** [comment]
@bombcar everything good on my side here now.

**Comment by bombcar** [comment]
Cool!

So gregificatiion of the recipes - too easy would be replace planks with panels, etc.

I think it makes sense that wood signs have hand crafting recipes (similar to what we have now) but the metal signs be restricted to the assemblers.

I've removed the automatic nugget creation but I think the next step will be to make it work directly with the GT-unified metals instead of hard-coding other mod interactions (this would prevent dual steel for example).

**Comment by Sederien** [comment]
Agreed.

Hopefully the textures are simply inherited for all the metals. I'm happy to take a look at what might be missing and see if there isn't a way to fix later.

**Comment by shawnbyday** [comment]
Sounds good to me. If you need any help or someone to test ping me somewhere lol.

**Comment by bombcar** [comment]
Let's be honest, there's like five metals with special textures and all the rest are "Gray" 😸 

[MoarSigns-1.7.10-1.2.0-10-g12266e4.zip](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/7791228/MoarSigns-1.7.10-1.2.0-10-g12266e4.zip)

This is the version with auto-nuggeting removed (it still uses existing nuggets for some things that have them) but it doesn't yet use GT materials.

Does "restricting" the toolbox to LV make sense? Or should we try to make some existing GT tool overload on the signs? Screwdriver might make sense ...

**Comment by Sederien** [comment]
Tool box should be available as soon as or shortly after (use steel?) the first metal sign is craftable (but for more resources, of course). I think it's okay to let players make it by hand with whatever set of rings, bars, screws, bolts they need in the end.

**Comment by Sederien** [comment]
But if you are making signs only by machine, it's also fine to balance for that. My opinion is simply that the tool box should come into play about that same time.

**Comment by bombcar** [comment]
What I’m wondering is if we should have the toolbox at all or if we can make a normal gt tool work on the signs. 

So instead of carrying a 🧰 you just hit the sign with your 🔧 or 🪛 that you’re already carrying.

**Comment by Sederien** [comment]
How would you deal with preview functionality to preview sign look? Or copy?

**Comment by bombcar** [comment]
I’ll need to check if the toolbox does more than just open the GUI

**Comment by Sederien** [comment]
Shift-click to go through the different modes while holding the tool box. (Assuming default controls)

**Comment by benjamin-kirkbride** [comment]
So did this just sort of fizzle out?

**Comment by mitchej123** [comment]
Yes
