### ISSUE TITLE
SSP Dysynchronisation

### ISSUE THREAD

**Issue by LogicFalls** [GTNewHorizons/GT-New-Horizons-Modpack#4272]
In V2.0.7.0, I'm finding resources I certainly consumed back in my storage system, and freshly made unused components vanishing. Other such oddities include armour stands replacing their contents with what I am currently wearing.

I haven't seen any other complaints about this, and I'm seriously at a loss as to why this is happening. It was suggested that dysyncs happen after crashes and unexpected closures, but even without these stuff seems to be moving around.

These are't ghosts, either. I swear I've processed the same 48 salt piles no less than 4 times and I've kept the chlorine.

I have installed extra mods: FTBLib, FTBUtils, AromaCore, Aroma Backup, but if these mods were causing problems then others should also be experiencing them.

**Comment by Anarack** [comment]
Is this in a void dim? I remember some issues in the past with them and ae. Although this sounds like the chunk is not saving and is getting reverted sometimes which is not a good sign.

**Comment by LogicFalls** [comment]
This is in the OW. Yes, I agree this sounds like chunks reverting but I have no idea why or how this would happen.

**Comment by richardhendricks** [comment]
Are you using tools to do a lot of teleporting, or moving from dim to dim quickly?  I *suspect* what can happen is this
You leave an area
The chunks get earmarked for retirement to the disk and go into a retirement queue of some kind
You come back
The chunk is not in active memory so it is requested from the disk again
*ROLLBACK JUST HAPPENED*
Chunk gets written out
But...When the active copy in memory is saved off, it would permanently overwrite the real chunk state.

Pulling the chunk out of active memory and into a save queue requires a lot of steps, and if any one of them does not notify the chunk fetch algorithm that the chunk is "in flight" and it should hold off on loading, or perhaps un-retire the chunk and put it back in the active queue, then race conditions can occur and data get lost.

I was able to trigger a rollback on Epsi by teleporting back and forth quickly out of my base.  I suspect it had to do with /home and /back counting separately for teleports for moderators or something.

What prevents this issue is chunkloading the chunks of interest since that way they only get retired when the server stops.

Try that and see if the rollbacks stop occuring

**Comment by LogicFalls** [comment]
All my chunks are chunkloaded. While I do hop dimensions (TF -> OW -> Ne -> OW) quickly, I don't do this using commands.

**Comment by richardhendricks** [comment]
It doesn't matter if you are using commands or not to teleport. 

Interesting that you are still seeing this with chunkloading active.

If you have time, you could try doing some testing. A hopper dropping items into a chest should make a nice 1s clock to record the time. Just make sure your hopper clock doesn't cross chunks, and put a block on top of the hopper. 

I don't think I'll ever be Java savvy enough to debug the race condition causing this in Forge though. :D

**Comment by LogicFalls** [comment]
What would I be testing, exactly? When rollbacks occur?

**Comment by Dream-Master** [comment]
@LogicFalls the thinks moron suggest.

**Comment by richardhendricks** [comment]
yeah that hopper thing might not work.  What I did was take or put 1 item in a chest, and TP away and back, repeatedly.  Every 1 in 20 or so it would be off in count, since it would load an old chunk with the old chest contents.  After I chunkloaded the chunk, I couldn't get it to happen again.  This is on the officials when I was helper/moderator so I didn't have the 5s teleport cooldown. I think the problem might still happen if you used other rapid teleport items like travel anchors, but I didn't test it. Nether portals usually have a builtin warmup time, but the TF portal does not I think.

Another possibility is that backup is locking the regions while copying the file and the chunk can't be retired to disk, and so when retrieved it gets an old chunk.

idk,  if we can find a repeatable way to duplicate the issue we would try debugging it somehow.

**Comment by LogicFalls** [comment]
I observed rollbacks often occur after a crash, but as far as I know this this is a vanilla issue.
I could try hopping in and out the TF repeatedly altering an inventory.

**Comment by richardhendricks** [comment]
OK so when, precisely, do you notice a rollback happening?  When restarting the server, or when TPing back and forth?  What is your disk subsystem, SSD or HD?

**Comment by LogicFalls** [comment]
HDD, so a read/write issue is very possible.

It's very difficult to pinpoint exactly when rollbacks occur, it's very much something I just notice as I'm playing. It doesn't seem to be blocks that are altered, more their inventories. If I had to guess, it would be after using a Nether or TF portal, or, as stated above, after a crash.

**Comment by LogicFalls** [comment]
I just now learned it can apparently happen after closing them game completely normally.
