### ISSUE TITLE
Suggestion: Add High Tier Battery Cluster (UHV+)

### ISSUE THREAD

**Issue by DietmarKracht** [GTNewHorizons/GT-New-Horizons-Modpack#4482]
#### Which modpack version are you using?
2.0.7.0
#
#### If in multiplayer; On which server does this happen? 
Delta
#
I suggest to add battery clusters for the tiers UHV+ because most of the endgame stuff requires huge amounts of power and the regular gt batteries dont last very long.

See #4127

**Comment by Spartak1997** [comment]
![2019-05-03_14 53 19](https://user-images.githubusercontent.com/29407630/57795232-1bdaf680-774e-11e9-9417-f6c78d868801.png)
![2019-05-03_14 53 20](https://user-images.githubusercontent.com/29407630/57795246-23020480-774e-11e9-8da2-cf5b335c3aa9.png)
![2019-05-03_14 53 25](https://user-images.githubusercontent.com/29407630/57795255-28f7e580-774e-11e9-8c6b-a20c1495ce55.png)

**Comment by richardhendricks** [comment]
GT++ has the energy buffers, which are available post ABS and store really large amounts and can be configured to output 1-16 amps (so you could uptier 2x). At-tier they are hours of power.  Also, they can be broken and picked up without losing power contents.

**Comment by DietmarKracht** [comment]
Anyway i like the classic gt battery buffers. gt++ energy buffer automation requires you to make assemblers for so many different liquids whereas the new clusters only require you to do assembly line automation. also gt++ doesnt add uev energy buffer iir

**Comment by draknyte1** [comment]
UHV is called MAX in GT++ because it’s the max tier in standard GT and I have no plans to ever add content beyond that point. 

Amperage on energy buffers is configurable.. 🤷🏻‍♀️

**Comment by 0lafe** [comment]
You can limit your buffer input with a diode/battery if it can't be limited itself. Multiple fluids in an assembler is fairly easy. You have a couple options to do it, varying from eio filters to sfm/OC. Buffing power at UHV+ is stupid easy with ultimates/really ultimates, and there's also the PSS which holds infinite ish. Single use UHV batteries shouldn't be good, you're meant to have stable power either through generation but storing it is also an option without small batteries. 

>most of the endgame stuff requires huge amounts of power

That's why you're given ways to make stupid amounts of power
