### ISSUE TITLE
Add back in basic elements comb and leaf centrifuge recipes

### ISSUE THREAD

**Issue by richardhendricks** [GTNewHorizons/GT-New-Horizons-Modpack#4506]
Only for common low tier materials: iron, copper, tin, silver, gold.

**Comment by Dream-Master** [comment]
so far i know some or all have centrifuge recipes

**Comment by DietmarKracht** [comment]
What is the purpose of higher tier combs if they don't have a centrifuge recipe?

**Comment by Dream-Master** [comment]
using autoclave recipe

**Comment by Ngar1** [comment]
I can´t understand, that bees are so "bad" in some one minds. I realy have no problems to get enough ores, If I can reache them ( I have 12 HV miners at work - cheep, fast build up and efficient). Bees combs (just by centrifuge) make it possible to produce materials automaticaly, but you have to work hard to breed the right bee, that you can do so.
So, there is on my opinion no reason, why to prevent also higher materials with bees.
If you need continously a small oder mid quantity of  resources, its make sense to let it done by bee.

To translate bees to the crop way (UUM), seems for me, to transfer it to EMC of old ages (Tekkit): you need a plenty of energy (UUM and Autoclave energy (also to reduce the time)), and you can get them all. Realy stupid in my (!) view. I never used GENDUSTRY machinery, because they are to technical and op for me. I like the farmers way of Forestry/Binnies Bee - not industrial, not magicaly, made by hand crafting as alternative to the other ways  :-) 

As sum: 
- let/ forestry/binnie bees comb products as they were originaly
- add the need of a block under the alvary on higher materials -> no material before reaching the right tier
- my be reducing the efficency ->but it is easily compensated by double the alvarys 
- need of higher energy for centrifuge for higher materials seems for me a good compromize

If someone want to make it harder, there are many ways to do it:
- no time speed machine with bees
- reduce GT Multiblock miner to x3 cruched ores
- as an idea: let Pristine queens only 10 times higher life cycle than Ignoble
