### ISSUE TITLE
Retier GT++ Mutagenic frame

### ISSUE THREAD

**Issue by richardhendricks** [GTNewHorizons/GT-New-Horizons-Modpack#4507]
Take out Pu-241 since it relies on trollplant. Use only U238 flamestring proven frame. Proven frame is available from TC and from beekeeper villagers. U238 is extractable from Thorium ores and from Red Granite blocks. Flamestring from nether spiders.

![image](https://user-images.githubusercontent.com/1214811/57974988-cccbd600-7986-11e9-9cd4-bf919c4c5c58.png)

**Comment by richardhendricks** [comment]
U238 is available in LV tier Thorium ores and Red granite ores.

**Comment by richardhendricks** [comment]
U235 and Pu-241 requires HV centrfuge (320 eu/t recipe)

**Comment by richardhendricks** [comment]
Could not get Pu-241 from trollplant, unless the chances are really low

**Comment by sthegreat** [comment]
U235 is available in MV and at a better ratio than centrifuging 238 via thaumcraft:

![](https://i.imgur.com/C7N5Hmr.png)

I suggest we change the Pu-241 to Pu-239 instead of changing it to uranium 238 or 235. Pu-239 is solidly EV (with the exception of fairly small amounts from HV U238 centrifuging), which makes sense as a tier for the mutagenic frames because there they will not overshadow the oblivion frames, which provide instakill but no 5x mutation. I think that the current issue with mutagenics isn't the tiering as much as the cost. They currently cost 2.25 Pu-241, which may not seem like a ton, but on average it's 101.25 Pu-239 in the centrifuge, which is kind of a lot for a frame with 2 uses. 2.25 Pu-239 would be a much more reasonable price.

**Comment by richardhendricks** [comment]
No, the big problem is that with the current upgrade blocks for the alveary, pretty much ALL frames are irrelevant after HV. The Electrical Stim and Mutator blow other frames out of the water. We need to sit down and write up exactly where bees *are now* and where we want them to bee before we fulfill any changes.

Moving the frame to LV requries significant justification, and "because way OP machines exist at HV that make it irrelevant" isn't enough.

Same of Industrial Apiaries, per my numbers they are way underpowered compared to alvearies and need a major rebalance.

**Comment by Gateswong** [comment]
+1 to sthegreat.

On EV you will requires centrifuging (HV) 60k+ phobos dust, which takes approximately 250+ hrs to do. That's way more a lot for a 2-use-frame.

**Comment by Rakdarian** [comment]
You can use metallic perfection thats much more reasonable

**Comment by Prometheus0000** [comment]
Hasn't this already been changed to use plutonium?
