### ISSUE TITLE
Bees vs Crops

### ISSUE THREAD

**Issue by kekzdealer** [GTNewHorizons/GT-New-Horizons-Modpack#4701]
Version 7.5

There may be a MINOR difference between crops and bees here.
![image](https://user-images.githubusercontent.com/31353359/59610132-0b38ea00-9119-11e9-85f7-d7034275fbef.png)

**Comment by SampsaxD** [comment]
The same difference is also in autoclaving from UUM, crops are always HV voltage and give 1 purified ore, while combs scale by material up to something like 8000+EU/t voltages, and always produce 4 purified ore.

**Comment by richardhendricks** [comment]
Yeah we really need to have an overall bees vs crops balance discussion as well.  After doing both for a bit, I think crops are way easier right now, and bees need a bit of a buff. Especially considering the Forestry farm + IC2 crops scaling.  The only mitigating factor is that crops do so much less than bees.

**Comment by sthegreat** [comment]
I made some comments about this on the general bee issue but they're probably more relevant here so copypasting all my opinions and stuff on crops vs bees:

On the topic of uum autoclave recipes (resources are generated from only the leaf/comb and uum):
Change the way that comb/leaf recipes are generated, currently they seem to be partially (time and uum required) autogenerated on the basis of... density(?). Bee combs however also have a tiering system, which decides the recipe eu/t. This leads to some odd behavior, for example naquadah combs are far more expensive to autoclave than lutetium, even though we can probably agree that lutetium should be the same price or more expensive. Another example is that it makes the nuclear fuel autoclave recipes, which are of special interest as many people will want to automate their fuel using bees, much more expensive than other combEv recipes due to their high density (thorium is 1470s + 24l uu, while titanium, also combEv, is 307s + 6l uu).

Instead, we should take a good look at the product tiering system and decide where everything needs to go. Then, each product in the same product tier can get an identical uu recipe, without the density weirdness causing mismatched costs. We should also use the same tiering system for crops, and use proportional recipe times and uu costs, with both divided by 4 for crops because crops are 16:1 instead of 9:4 crushed ores. This prevents the current weirdness where osmium crops have an hv autoclave recipe while the equivalent bees have a long expensive IV one.

On the topic of the ore duplication recipes: These should be done using the same system as uum recipes, and therefore be the same recipes for bees and crops. Essentially I just want to move the crop recipes to be the same as the bee ones here. We should also look at which bees can do which ores though, as currently there are some weird ones. Bee combs and crops should only be able to multiply ores for which that comb's/leaf's resource is the main product (after all processing) of that ore.

On the topic of non-ore bees, which are bees with centrifuge recipes instead of autoclave/ore processing ones: these seem mostly fine as is, but some like the infinity line should be changed to make them actually usable or removed.

On the 9-in-1 (gt++ autoclave): it currently has a massive impact on the viability of a lot of autoclave recipes. While the machine is decently tiered, being IV but very expensive within that tier, it's 3.5x speed boost and 80% eu/t multiplier is pretty huge and totally changes things, being the only reason that some bee combs like nuclear fuels are even close to viable right now. I think that the bee comb and crop autoclave recipes should be moved to chem reactor to prevent issues with balancing, for example something balanced for normal machines at ev-iv may be unbalanced with it, and balancing around it makes it absolutely required.

I made a spreadsheet with all the current autoclave recipes, and my proposed recipes, here:

https://docs.google.com/spreadsheets/d/1el609jCfXZWy_tSno_wsfRcRjjyH5AZsdiKNXq4L9_o/edit?usp=sharing

Thoughts? I wasn't totally sure on what to put for new recipes, I tried to reduce the cost overall by decreasing time significantly and increasing uu for some combs, decreasing for others so they fit tiers. Nor was I sure where to put some of the combs. These recipes are made with a change from autoclave to another machine such as chem reactor in mind due to the effect of the gt++ autoclave mentioned above.
