### ISSUE TITLE
Add Sky Stone to Mark of the Falling Tower ritual from blood magic

### ISSUE THREAD

**Issue by EmeraldsEmerald** [GTNewHorizons/GT-New-Horizons-Modpack#4794]
The Mark of the Falling Tower ritual from Blood Magic could be tweaked to contain Sky Stone from AE2. This provides a renewable, bee-less source of Sky Stone for, well, anything a player would need it for. Since sky stone is already obtainable from meteors, it seems reasonable that a ritual that literally summons a meteor would contain some, no?

The sky stone could also be restricted to the higher ritual tiers. (diamond/netherstar, maybe?)

**Comment by 0lafe** [comment]
It would also be kinda nice to add other ore type stuff to this, maybe for like tiered inputs or something if that's possible.

**Comment by Prometheus0000** [comment]
I know FTB Interactions added custom stuff to theirs, but I can't remember if they got it working correctly, I think they had trouble getting it to have Phosphorous or something. And they changed the activation item too I think. It would definitely be cool to have something like meteoric iron (only) gotten this way, but it doesn't sound like people use BM until they can make pure tears, so it might have to be a later material? I'm not sure people would use it for something other than Sky Stone, since you can just go mining for most things anyway if it isn't something you can only get this way. Maybe the Ross128b or Toxic Everglades ores, since they're kinda spread out (or whatever their oregen is).

**Comment by Anarack** [comment]
You can just add them to the blood magic config iirr.

**Comment by Prometheus0000** [comment]
I see that this is easy to do, but I can't see where to change the catalyst item though, but looking at the 1.12 version, it uses separate json files, so we probably can't make custom meteors with just the config I guess? Also, the nether star one has oreSunstone? oreMoonstone? and oreIridium! already set. Plus other stuff on the rest, mostly boring. Maybe the iridium one is unbalanced? I haven't started BM yet.

**Comment by Prometheus0000** [comment]
Ok, I've been playing around with it, and finally managed to get skystone added.
First, any entry needs to have an oredict to be added, so I had to figure that out for skystone.
Second, unless someone wants to fork+backport the later BM stuff, no custom catalysts for us. Or more than four types. Or custom filler material. Well, I guess they could be changed if you _just_ forked it. But it would be harder to adjust or add more.
Third, the amounts seem to be x out of 1000 chance, with less than that being filled with stone, and more ignored. So adding oreIron 1000, and the oreIridium 1000 would just get you iron.
Fourth, we can change the sizes, up to at least 64 (radius), but that's definitely too large. 
Fifth, with doMeteorsDestroyBlocks=false it won't destroy blocks below (blast damage) or replace what it hits.
Sixth, to actually do the ritual, you need to have a T4 altar and have 1M LP, so you need the Master orb. This means Tungstensteel and EV. But you can do all of them at once, so you can't scale them, only differentiate between the four types. The types are Stone, Iron Block, Diamond, Nether Star.

I can add stuff like Tungstate or Rutile for example, but I'm not entirely certain what I should add. Everything EV and below? Stuff that's useful at EV? What planets (and thus ores) could you even get to at EV? Should it even have other planet ores? How big should each of the meteors be? Is there a way to automine it? And so on. I'd appreciate some opinions. Do staff have any opinion?

**Comment by KaneHart** [comment]
Not a fan of Magic but I like the idea. We moved Meteors already to Twilight so we have a little less then normal.

**Comment by Prometheus0000** [comment]
I came up with a list. Comment if you want it changed. Assume they're all split evenly through the meteors unless otherwise stated. The NS one is kinda empty.

Stone (16): (Skystone and planet dusts. Not much to add, so added End stuff to compensate. Also gems.)
skystone
rockMoon
rockMars
rockPhobos
rockDeimos

Add all gems (from the small ore list) at very low chance?
Diamond
Emerald
Ruby (go for chromite instead)
Sapphire
Green Sapphire
Olivine
Topaz
Tanzanite
Amethyst
Opal
Jaspar
Blue Topaz
Red Garnet
Yellow Garnet
Jade
Vinteum
Firestone 

Really unsure about these, but you CAN get them in the End. Theoretically. Highly reduced amount?
Naquadah
Enriched Naquadah (reduced amount)
Lithium
Platinum
Palladium
Iridium


Iron Block (16): (Pre-space stuff that is rare or you would want more of)
Tantalite (tantalum)
Mica
Asbestos (1/3 mica amount)
Calcite?
Soapstone? (is more needed for drilling?)
Vanadium Magnetite (vanadium)
Salt (sodium+chlorine+boron)
Rock salt (potassium+chlorine+boron)
Sphalerite? (zinc+gallium)
Lead?
Silver?
Barite
Certus Quartz
Thorium
Molybdenum (higher amount due to rarity?)
Pyrochlore? (niobium)


Diamond (16): (all the rocket T1+T2 stuff)
Meteoric Iron (Highly reduced amount, since it's not a small ore anymore?)
Chromite (Chrome. Is it still needed a lot? Amount could be increased if so)
Bastnasite (Fluorine)
Monazite (Helium or Phosphorous+Rare Earth. Way better for RE ironically. Reduce amount to compensate?)
Neodymium
Barite (repeat)
Certus Quartz (repeat)
Desh
Uraninite (u-238)
Uranium 238 (get rid of above and below?)
Pitchblende (U-238+thorium)
Draconium
Electrotine
Oriharukon
Vyroxeres? (Is this even used?)
Mirabilite (No use? Other than being Electrolyzed for useless stuff?)
Arsenic
Bismuth
Antimony


Nether Star (24): (Anything else you need tons of. Suggest stuff okay?)
Rutile
Tungstate (reduced amount? Are there enough tungsten sources?)
Copper
Salt?
Rock Salt?

**Comment by Prometheus0000** [comment]
I finished adding the values, you can try it out for yourself or take a look at the files to complain about the amount. I reduced the sizes of the meteors too. Only problem is Miners (single or multi) don't pick up the ore. Does anyone want different colored meteors? Keep in mind netherrack and endstone would double the amount. But they could be red granite, black granite (what it is now), basalt, or marble. Leaving it as default ore type means some of them become other mod versions of ore.
[Meteor Files.zip](https://github.com/GTNewHorizons/NewHorizons/files/4226447/Meteor.Files.zip)

**Comment by Prometheus0000** [comment]
For people who don't want to go through the zip:

#Actual number of blocks in the meteor is ((radiusx2 cubed)x0.6) approx. So 8=2500, and 12=8300
#If you think it's unbalanced, reduce the size of the meteor or adjust the numbers below
#They currently use 845/810/1000/962 out of 1000 for each.

meteor {
    S:diamondMeteor <
        oreBlackgraniteMeteoricIron
        10
        oreBlackgraniteChromite
        50
        oreBlackgraniteBastnasite
        100
        oreBlackgraniteMonazite
        30
        oreBlackgraniteMolybdenum
        70
        oreBlackgranitePyrochlore
        50
        oreBlackgraniteNeodymium
        50
        oreBlackgraniteBarite
        25
        oreBlackgraniteCertusQuartz
        25
        oreBlackgraniteDesh
        50
        oreBlackgraniteThorium
        20
        oreBlackgraniteUraninite
        10
        oreBlackgraniteUranium
        10
        oreBlackgranitePitchblende
        20
        oreBlackgraniteDraconium
        50
        oreBlackgraniteElectrotine
        50
        oreBlackgraniteOriharukon
        50
        oreBlackgraniteArsenic
        50
        oreBlackgraniteBismuth
        50
        oreBlackgraniteAntimony
        50
        oreBlackgraniteBarite
        25
     >
    I:diamondMeteorRadius=12
    B:doMeteorsDestroyBlocks=false
    S:ironBlockMeteor <
        oreBlackgraniteTantalite
        60
        oreBlackgraniteMica
        60
        oreBlackgraniteAsbestos
        20
        oreBlackgraniteCalcite
        60
        oreBlackgraniteSoapstone
        20
        oreBlackgraniteVanadiumMagnetite
        60
        oreBlackgraniteSalt
        50
        oreBlackgraniteRockSalt
        50
        oreBlackgraniteSphalerite
        50
        oreBlackgraniteIron
        5
        oreBlackgraniteNickel
        15
        oreBlackgraniteCopper
        200
        oreBlackgraniteTin
        20
        oreBlackgraniteLead
        40
        oreBlackgraniteSilver
        50
        oreBlackgraniteGold
        50
     >
    I:ironBlockMeteorRadius=12
    I:maxChance=1000
    S:netherStarMeteor <
        oreBlackgraniteRutile
        100
        oreBlackgraniteTungstate
        100
        oreBlackgraniteCopper
        300
        oreBlackgraniteSalt
        200
        oreBlackgraniteRockSalt
        200
        oreBlackgraniteMica
        60
        oreBlackgraniteAsbestos
        20
        oreBlackgraniteSoapstone
        20
     >
    I:netherStarMeteorRadius=8
    S:stoneBlockMeteor <
        SkystoneBlock
        300
        rockMoon
        150
        rockMars
        150
        rockPhobos
        150
        rockDeimos
        150
        oreBlackgraniteDiamond
        1
        oreBlackgraniteEmerald
        1
        oreBlackgraniteRuby
        1
        oreBlackgraniteSapphire
        1
        oreBlackgraniteGreenSapphire
        1
        oreBlackgraniteOlivine
        1
        oreBlackgraniteTopaz
        1
        oreBlackgraniteTanzanite
        1
        oreBlackgraniteAmethyst
        1
        oreBlackgraniteOpal
        1
        oreBlackgraniteJasper
        1
        oreBlackgraniteBlueTopaz
        1
        oreBlackgraniteGarnetRed
        1
        oreBlackgraniteGarnetYellow
        1
        oreBlackgraniteJade
        1
        oreBlackgraniteVinteum
        1
        oreBlackgraniteFirestone
        1
        oreBlackgraniteNaquadah
        4
        oreBlackgraniteNaquadahEnriched
        1
        oreBlackgraniteLithium
        10
        oreBlackgraniteCooperite
        30
     >
    I:stoneMeteorRadius=8
}
