### ISSUE TITLE
.name blocks

### ISSUE THREAD

**Issue by boozzeeboom** [GTNewHorizons/GT-New-Horizons-Modpack#4795]
#### Which modpack version are you using?
2.0.7.5
#
#### If in multiplayer; On which server does this happen? 
Russian server. melkocraft.ru
#
#### What did you try to do, and what did you expect to happen?
sometimes gregtech machines transformed into .name block.  
#
#### What happened instead? (Attach screenshots if needed)
i'm "admin" of this server and cant do nothing with that.
plugin like Coreprotect cant turn back it into normal machine he replaced .name
And only thing i can do it's replace region file from old backup.

it happens randomly with <5% chance or less. but it happens, and idk why. 
some guys have big trubles) some less.
![2019-06-29_02-10-46](https://user-images.githubusercontent.com/21971234/60372717-ff9dcb00-9a16-11e9-8f09-032a65d4b8fa.png)
name remover machine doesnt help.
https://pastebin.com/CqFKaWAX - this gregtech.log
#

**Comment by draknyte1** [comment]
It's due to packet loss, lag or general bad times. Too much data in a chunk is usually the main reason. The machines never really lose what they are, the client just has no idea.

Does this happen on a pure forge server? (No kCauldron/Thermos)
Does this happen to every player?
Does this always happen in the same chunk?
