### ISSUE TITLE
slow building ring crashes delta

### ISSUE THREAD

**Issue by PoptartOverlord-Xabedo** [GTNewHorizons/GT-New-Horizons-Modpack#4818]
#### If in multiplayer; On which server does this happen? 
on delta

#### What did you try to do, and what did you expect to happen?
i made the slow buildìng ring from gt++ , wore it in ring slot and when i removed it, it crashed delta(3 times now, whoops, sorry delta players)
i disposed of it by killing myself so i dont cause crashes, it also has another bug is that its still slows you down even if you're not wearing it

**Comment by draknyte1** [comment]
Please report it here.
https://github.com/alkcorp/GTplusplus/issues/new

**Comment by PoptartOverlord-Xabedo** [comment]
i mean i'd love to but i dont know if it can be replicated and i dont have the crash report

**Comment by Pyromanc3r** [comment]
I also had this problem in version 2.0.7.5. When you dress the ring it works as it should be. The character moves with the sneak speed. But it is worth only trying to remove it as a server (dedicated located in the LAN network) crashed, and the game client dropped in the main menu. 
The most interesting thing is that even if you go into a single game, the effect of low speed remains on the player without a ring. It is very strange. You could get rid of it only in a separate new world. Dress down and remove the ring. I checked different conditions as it could happen. With\without equipment, enchants, concrete blocks (accelerating walk speed), but did not find out the pattern that crashing the server.
What else noticed, then on the current version of the game 2.1.0.0 after dressing the ring the character does not move slowly as it was in the old version. That is, he has a speed of ordinary walk, and not sneak. At the same time, it is also impossible to run. Perhaps because of this, this bug is not working in current version. 

Here is a crush report if still need. Maybe it somehow help. 
https://pastebin.com/2T9tcDb2
