### ISSUE TITLE
[RFC] Move AE down a tier

### ISSUE THREAD

**Issue by Methes** [GTNewHorizons/GT-New-Horizons-Modpack#4821]
Alright so I've been playing this pack since the very beginnings. I remember times where pressure plates and buttons were made normally, BBF had much easier recipe and animals didn't explode.
From the start AE was gated at titanium. It was fine. Playable, you progressed much quicker.
Then changes happend. Not at once, slowly. Things added up.
The last straw was chemistry-circuit update. Suddenly EVERYTHING was a lot slower, needed a lot more crafting and materials. AE was pushed away by a lot.
For some reason even low tier things get nerfed over and over, probably because once you nerf one thing too much, other things suddenly seem too easy. Or because a guy thinks of a cool new mechanics how to make something more complex, but fails to realize that it will impact EVERY step you take, even at low tiers. Take hatches for your first EBF as an example. For AGES you had to save up steel, make a few chests, glass, cable and a whole ton of hulls. Done. Now you have additional extra steps.
Your first rocket and therefore first AE is CONSTANTLY pushed away from you immensly increasing the time before you get there.

I say move AE to HV tier as time wise it fits the progression that has been here for the longest time.

**Comment by noobyaran9** [comment]
I recommend we make AE available at MV for solely storage purpose and open up autocrafting post HV.
So for MV you only have access to energy accepter, ME drive, ME chest and storage bus.

And once u unlock HV, you can access everything else.

**Comment by bigbass1997** [comment]
**_In response to Methes' post:_**
I have been playing this modpack for years, and I know what Methes is talking about - how it used to be. I've also fairly recently came back after a decently long break and almost entirely started over on Epsilon (had originally played on Delta). I'm now up to late MV tier, not too far off from starting HV. I completely understand that same feeling that Methes is describing.

There isn't anything wrong with specifically adding more complexity and thus more longevity to the pack as a whole. However, it has come to a point where there are soo many things you must do to progress in each additional tier, it makes me want for an AE system. And I know it will only get worse as I go through HV, and eventually EV tier.

I can see myself getting to HV just fine, without any need for an AE system. But I've looked ahead, I know the crafting becomes even more complicated with even more required bits and pieces. I cannot say for certain whether AE systems should be moved down to HV tier or not, but I will say that **it is definitely something that should be thoroughly considered**.


**_In response to noobyaran9's post:_**
There are plenty of good storage solutions available by MV tier! There is absolutely no need for AE storage at that point in the modpack. You can even make searchable/requestable storage using ProjectRed Transportation.

**Comment by observeroftime02** [comment]
Here's a mod idea: For Steam and LV age, get carrier pigeons to fetch your materials, and squirrels to autocrat for you. But the twist is, the squirrels take your materials and hide them, and there's only a 60% chance that each requested item can be fulfilled per request. Each chunk of distance traveled takes 1200 ticks, and depending on what tier of pigeon you've got it can only carry between 1 tiny dust or 3 items max. You communicate with the pigeons on what items to fetch via spelling out with breadcrumbs a unique pattern in a 9x9 grid on the ground. At first, you have to add pigeons to your network by catching wild ones, then improve them by breeding, similar to bees. There's no central item registry, instead you have to memorize which items are currently in your system. You may use the clipboard to assist you with this task.

**Comment by bigbass1997** [comment]
@observeroftime02 Not sure if that was an attempt at a joke, or just wanted to take this discussion far off-topic. Either way, please only post things actually relevant to the issue topic.

**Comment by DoomSquirter** [comment]
two words:  bat transport.

**Comment by Methes** [comment]
**Additional note:**
In every game system there should be a certain reward progression that this pack does quite well.
A new thing comes up. It's difficult, you dedicate a lot of time and effort into this novelty, understanding its concept. Then you progress and reach an easier method that takes away a lot of your efforts and gives you a huge sense of accomplisment. And lastly you reach a point where that previously difficult thing is just beyond you and you can (almost) completely forget about it.

Take iron plates for example. At first you have to mine, smelt and then hammer 2 iron ingots to get one plate. That's a lot of work and a lot of materials. When you get your first bending machine, it's amazing! You only need 1 iron ingot for one plate!
When you progress even further you have a farm which gives you "infinite" amounts of iron, so you can forget about it completely and focus on other, new, things.
Hunger works similarly. At first you eat stuff from gardens. Then you make a farm with a Lunch Box. Eventually you reach Hunger Axe, Cans, have a Lunch box full of "feast" food. Ultimately your armor just replenishes hunger automatically and you focus on other things.

This is good mechanics, as you are presented with an obstacle, learn how to get over it, make it smaller and eventually it's just a bump. However, you are constantly presented with new obstacles and that's how it should be, as it's a fundamental game mechanic - obstacle/reward.

**What the F am I dragging on about?**
Crafting gets boring eventually. Making plates and rods is hugely beneath you around HV time-wise. You shouldn't really bother with it because you've spent hundreds of hours in the game already making plates and rods. Reaching AE at that point is where you reach a plateau of fun from crafting and you can focus on new challenges (DT, vacuum freezer, implosion compressor, fuel, PTFE, iTNT, Rocket...).
_Also don't be stupidly afraid of unlimited resources! Stop nerfing them, they are part of a progression! I just wrote why!_

**Comment by observeroftime02** [comment]
It's a good Idea, because AE alleviates the tedium of highly repetitive crafting tasks, therefore it should be available at the very least at HV, if not earlier. I agree with the suggestion. Perhaps it shouldn't be limited by tier, but by materials involved in crafting it. Somebody in LV and MV is not going to have the resources to craft complex setups anyways, so usage would be limited anyways. Drive bays need titanium and HV circuits, so there's a limit right there. Those are my thoughts, but I agree with the OP.

**Comment by BlackFlameTNT** [comment]
I would say HV for AE only storage and the rest is EV

**Comment by observeroftime02** [comment]
Storage is a huge part of the challenge of early gregtech as well, akin to storage wars. I had no problem crafting things etc. but the logistical challenge was the big deal for me. So overcoming that with AE really changed the game into something enjoyable for me. Perhaps some people share that experience.

**Comment by bigbass1997** [comment]
observeroftime:
> but by materials involved in crafting it
Well that's effectively also limiting it by tier. So that's a mute point.


BlackFlameTNT:
> I would say HV for AE only storage and the rest is EV

Why? (rhetorical question). You don't need any other storage solutions, even at HV. For the same reasons that I already explained to noobyaran9 earlier.


observeroftime02:
> Storage is a huge part of the challenge of early gregtech as well

How so? Make some larger chests (Iron, Gold, Diamond chests), drawers/barrels for high quantity items. And if you really need something more complex, then combine drawers/chests with ProjectRed. That should be totally sufficient. If you have trouble organizing, put up a few signs to help you remember what's in each chest.

**Comment by BlackFlameTNT** [comment]
For me I mad it to early IV with using only chests its doable but after reaching the moon it was a mess and I didn't use any thing with chest no hopper nore ender io and with titanium nerf I see the point of lowering down the AE sys

**Comment by observeroftime02** [comment]
I'm well aware not everyone struggles with storage, but I do, and a couple of people I play with feel the same. I'm not going to get into why that is, because it's "off-topic", so let's accept that it's true for me. As far as PR goes, we had quite an elaborate setup on our server, that grew to the point of creating massive lag / drops in FPS anytime anyone went near it or used it. Let's not pretend that it's a viable replacement for AE. Nice to have, on a small scale if you don't have anything else, but a bigger system is not without its own problems. 

So yeah, I agree, move it down a tier, the sooner it's available the better imho.

**Comment by Methes** [comment]
Honestly I don't have issues with storage either, but I understand some people do.

As far as how much work this change would require:
Change titanium plate to stainless steel plate in the AE2.zs (done in 30 seconds with Notepad++)
Change EV assembler in Molecular Assembler to HV assembler (same time)
Change EV machine hull in Interface to HV machine hull (same time).

**Comment by AlexBucket** [comment]
That's a no from me.

It's tiered well where it is.

**Comment by Shattered2909** [comment]
Strongly agree with the post.

ESPECIALLY after the hard nerf to titanium!!!

**Comment by SampsaxD** [comment]
If this is to be done, having the controller still be gated behind Titanium would make it better IMO. You could set up some basic autocrafting with the 8 channels per network, or daisy-chain them for a fairly hefty cost (interface & storage bus for 5-7 more channels).

However I am also against this change as I feel after autocrafting the pace of the pack changes completely, and making the rocket is a kind of a nudge for the player, telling "Hey, wasn't I a bitch to craft? Wouldn't it be nice if you had autocrafting? Well, use me and get autocrafting!"

**Comment by Methes** [comment]
> "Hey, wasn't I a bitch to craft? Wouldn't it be nice if you had autocrafting? Well, use me and get autocrafting!"

That's exactly how I now feel after making circuits.

**Comment by SampsaxD** [comment]
> That's exactly how I now feel after making circuits.
Circuits are a great example of a thing that should be automated even pre-AE because they are in such a high demand with a complex crafting recipe. Why do you think I made the flowcharts for automating them?

**Comment by noobyaran9** [comment]
>"Hey, wasn't I a bitch to craft? Wouldn't it be nice if you had autocrafting? Well, use me and get autocrafting!"

Thats if you have the power setup a large system

**Comment by xtake** [comment]
How about we put it to Iv instead. I get it I would love to have it earlier too it's so nice but because of that it should also be hard to get. If you want something cheaper go for projectRed Transportation it can make a good system. Or just the enderio inventory interface thing. 
This is GTNH since when did it become some easy modpack you get free shit thrown at you?
Most people will vote for the buff to hv so it wont really matter but yeah just saying :man_shrugging:

**Comment by observeroftime02** [comment]
If you were to move it to LV it would basically be useless at that point, because you wouldn't have the amount of constant power needed to power your system, never mind the amount of machines that would really limit your autocrafting. I know you're joking, but still.

**Comment by combusterf** [comment]
I appreciate tiering and gating for what it does, It lets you off rotating around mods to improve each other.

Moving *everything* to one tier - say HV - does break the sense of technological progress tiering, so I think in HV one should settle where it makes sense to stick with a ProjectRed system. Some other open considerations:
- Match cell tiers with voltage tiers, i.e. 1k, 4k, 16k, 64k becomes HV through LuV. More arcane things like spatial and essentia storage can be gated at +1 from there.
- Specific features can be gated later, ME interfaces are the core of crafting and could be gated early EV. ME controllers (to support 32+ channels) and P2Ps could also be EV to have to juggle cable and network sizes in lower tiers. In similar thinking, smart and dense cables could also be tiered later (dense maybe even at IV) to have people do some P2P magic if they want bigger networks at earlier points in time.

I'm saying this from a theoretical perspective, I can't actually get in game at the time of writing and check if there's any obvious EV-IV+ tiering in place already, nor speak from experience since I haven't properly started AE in this pack yet.

**Comment by kekzdealer** [comment]
Having progressed to AE in more recent versions myself, I think HV is slightly early for autocrafting, however I also believe that if you can power the system pre EV, you have earned yourself AE. So a fair change.

**Comment by Bluebine** [comment]
Powering AE at HV, pre-nuclear, and pre LGT and LCE, is gonna be hella hard. If you can do that, you've earned it. EV will still make AE a lot easier with the much higher potential for power gen.

**Comment by SampsaxD** [comment]
It's like 400EU/t for a even a fairly sizable system, how is that hard at HV?

**Comment by Anarack** [comment]
You can do limited autocrafting in mv via project red, Most storage can be delt with by doing drawer controllers, though they only sort of work, or similar methods. 
This change would do basically nothing that can not be done with earlier systems as well as making said systems pointless to setup.

**Comment by skynsun** [comment]
i think ae is well tiered and the fact you have alternative mod to do things, help to discover them if you dont wanna make boring things until ev.

**Comment by 0lafe** [comment]
>there's too many parts to have fun not autocrafting

So uh, no lol. AE is in no way the only way to autocraft, in fact there's a whole bunch pre AE. They all take more setup and are harder to use, which is part of the point. There's also batch crafting which alleviates the issues of component crafting in a big way. Earlier AE wouldn't really solve an issue of no automation setups, as much as it would just make them easier, which isn't good. It's also a point semi tangential from the idea of needing better item handling for things like circuits.

**Comment by Scottishprog** [comment]
I am in agreement with moving AE functionality to HV... most of it at least.

Keep in mind, part of all this work is base building/rebuilding... Nice to eventually settle into something that doesn't need to torn up and redone very tier....

Also will agree with infinite materials being a part of the progression.  Otherwise you eventually get a drag from needing to acquire _all_ of the materials for everything. Left unchecked, this kills the enjoyment of the game.

**Comment by NoriSilverrage** [comment]
I wouldn't be opposed. Even if it was just crafting terminal, and storage bus it'd be a huge help. Could tier the cells so that you are forced to use 1k/4k cells or something.

**Comment by alphaNOVAircraft** [comment]
> Also will agree with infinite materials being a part of the progression

You are able to obtain large amounts of nearly all standart materials with a quarry later on, Endless resources just create fire and forget machinery for materials, dont see where you really need it. Due to the fact that you need higher tiers of materials whenever you get some work done forces you to setup a quarry anyways and you dont just get the new material you searched for...
E.g. after farming the platinum for the assembly line i had nearly a million iron etc., pushing for a higher tier material normally supplies you with enough basic materials.

**Comment by mitchej123** [comment]
Is there a consensus on this?  And if so, anyone willing to do it?  If not we should close it.

**Comment by Methes** [comment]
If there's consensus (there is in Vote channel), I can do it.

**Comment by bigbass1997** [comment]
Based on the Github reactions throughout this thread (especially the first handful of posts), the actual comments themselves, and the Discord reactions in #vote regarding this suggestion (56 upvotes, 19 downvotes, and 14 neutral, at this time), I think it's pretty safe to conclude that there is a clear consensus that this should be implemented.

Methes, if you're willing to do the work, then I think you should go ahead and do it.

**Comment by Methes** [comment]
Created a Pull Request.
I changed all Titanium Plates to Vibrant Alloy plates, so you need Clean Room + Vac. Freezer to reach AE.
Also left Molecular Assembler with EV Assembler so you're stuck with only autoprocessing (Interface is downgraded) and not autocrafting, unless you use a Workbench or similar stuff until you reach EV.

**Comment by mitchej123** [comment]
Please fill this out: https://forms.gle/qwupVhLfEcYg1HWA9

**Comment by 0lafe** [comment]
So how about not doing this? AE in EV is already early for what it does. The only benefit of AE is the ease of on demand crafting, which can be achieved with earlier crafting anyway. Moving AE to HV however means there's really no reason to use any other item handling options, as your need for autocrafting doesn't even really start until after HV. 

My issue with this whole thread is it doesn't really address the uniqueness of AE. While there's lots of stuff to craft there's always been ways for you to automate ALL of it pre AE. It's a little more difficult but that's kind of the point, as you'd get a fairly big benefit from it in these tiers.

Another issue is AE as it is now is already REALLY cheap. The only thing that ever stops us from making an item is certus which is because we're too lazy to make any. Changing Ti to vibrant means that it'll be even easier to make AE as you progress out of HV, and by EV you can pretty much make anything you'd want with no restriction. 

There's is absolutely 0 need for AE autocrafting pre EV, and even the arguement for moving it from EV to IV seems reasonable. The amounts of things needed are small enough that hand crafting is fine in batches, but you do also have tools to automate anything you could ever want to. AE doesn't provide anything new to HV if it gets moved, all it does is give you an easier way to do something that shouldn't be easier. 


The fact that this got so far kind of makes me sad :(

**Comment by kholat** [comment]
The majority is not always right. Think about where this leads to and ponder well.

**Comment by richardhendricks** [comment]
Well played @kholat 
![image](https://user-images.githubusercontent.com/1214811/70196154-70839600-16cd-11ea-8667-f2997b56497c.png)

@Methes Was your PR filed/accepted?

**Comment by bigbass1997** [comment]
@richardhendricks Methes' PR was closed and not merged. https://github.com/GTNewHorizons/NewHorizons/pull/4981#issuecomment-561806055

**Comment by richardhendricks** [comment]
Okay.  I think I like the idea of making the components need the Avarita table and using vibrant alloy, which is almost 1/2 EV tier to make anyways since it needs the vac freezer.

My knowledge of AE2 is really outdated, so I can't offer much in terms of tiering of individual components.

**Comment by Dream-Master** [comment]
let's discuss about recipes before make pr. I can take care about recipes after because we need to change the quest too.

**Comment by Dream-Master** [comment]
And if I rember right wasn't there some change allready ?

**Comment by shawnbyday** [comment]
I think the main point of gaining access to AE in HV is being able to gain control over your inventory system. Drawers and controllers work pretty well until you get a massive set then it starts to negatively impact your instance or a server (if you play on one). 

**Components that need to come to HV (in my humble opinion):**

- Energy Acceptor
- Storage Bus
- ME Terminal
- ME Glass Cable
- ME Chest
- ME Drive
- 1k Storage Cell
- 4k Storage Cell

Really all this allows is to start getting rid of drawer, chest and barrel systems but doesn't allow any automation or liquid storage. This also allows for this entry level AE system to interact with ProjectRed decently enough to encourage use of that mod as well.

# 

**Quests that should be added are:**

- A quest for the Storage Drawer Concealment Key (this could go in the quest for the Drawer Key in the Steam Age or given as a reward for early AE crafting along with an explanation of why it is important).

**Some changes that might be needed are:**

- Make the Drawer Controller craftable earlier? (Maybe earlier MV?)
- Remove the Drawer Controller reward from the last quest in ProjectRed since they should have it by then?

I haven't had a chance to look at the recipes or the AE quests yet for recommendations on those.

**Comment by Dream-Master** [comment]
@shawnbyday to make a realy basic ae system you need less items/blocks you listed.

Changing this recipes i am ok with chaninging the other not.

Cables and 4k cell is not needed to start with AE.

**Comment by botn365** [comment]
i think it should be 
energy acceptor (without it you can power the terminal)
chest
1K drive
cable
terminal
this will allow you to amke a network of 7 chests and 1 terminal to see the content of al the chests
a drive and storage bus is way to op in HV

**Comment by shawnbyday** [comment]
@Dream-Master what would be the minimum items in your mind?

@botn365 my only concern is giving people a way to interface with their drawer system. I originally didn't have the ME Drive or the 4k Storage Cell in my list. I realize this might make people build too large of a drawer system though and in that case it would lead me to questioning moving this to HV due to not really being a "practical" change so to speak. What are your thoughts on that?

**Comment by Dream-Master** [comment]
@shawnbyday the minimum a ae can be run and i mean the max miniumum

**Comment by Anarack** [comment]
Allowing the storage buss makes both project red and enderIO storage systems pointless when you hit vibrant.

**Comment by shawnbyday** [comment]
That's true. I've never messed with EnderIO storage system in this pack since it's not too much further to AE. I think that is the main thing for me is they systems sort of all become available in a short range of tiers (again in my opinion). Even having earlier access to the drawer controller (even if just for the ease of depositing items into your chest that helps a lot). Maybe making that available sooner would be all we need to do?

**Comment by Anarack** [comment]
There is a quest that makes it available in HV via the project red tab.

**Comment by botn365** [comment]
a storage bus with a drawer system make the me chest pointless and allows you to push items in to the system automaticly 
th ae system in hv should only allow for a convienient way to store items and access them

**Comment by richardhendricks** [comment]
@shawnbyday File a separate ticket for the concealment key.  I assume that's to prevent lag when looking at the drawer system?

https://ae-mod.info/Getting-Started/ - for noobs

**Comment by shawnbyday** [comment]
@richardhendricks I will I was trying to roll multiple early game storage issues up into this RFC because it feels like there is just a gap.

@botn365 I agree that's all I'm after is a way to stop hovering over chests trying to find what I want and not having to have a huge wall of drawers doing the same thing.

@Anarack Yea I know it is given as a quest reward but is there a reason it is so hard to craft? Before you get ProjectRed really all it lets you do is deposit items efficiently. Is that really necessary to gate? Why not let it be made early LV and then have the ProjectRed questline give something different?

**Comment by Anarack** [comment]
I wouldn't be opposed to it going down to mv whatever tier fully unlocks project red. Can't remember if its mv, or just mv circuits needed.

**Comment by AlexBucket** [comment]
@shawnbyday You can search for items in chests by hovering over them in NEI or your inventory and pressing 't' and doesn't require changing the tier that AE is unlocked at

**Comment by AtomicGrog** [comment]
Storage (even if it's a storage bus on a compact chest) and a crafting terminal and a way to get stuff in/out in HV, would prefer interface for the in/out over import/export, much more versatile and without controller it's channel efficient.
