### ISSUE TITLE
Blood Magic and Balance

### ISSUE THREAD

**Issue by LogicFalls** [GTNewHorizons/GT-New-Horizons-Modpack#4843]
The state of Blood Magic is currently (2.0.7.5) such that nobody wants to use it. It's a great mod that offers some unique and useful utility, and the infrastructure surrounding it is fun to create. As it stands, it may as well not be in the pack.

The creation of slates and other necessary items has been nerfed here such that it takes far too long to create anything. Top-tier slates in unchanged BM require supersized, TPS-harming structures fully decked out in the appropriate (and pricey) runes. With the nerfs present int he pack, simple goals such as bound armor and tools become useless. By the time the player has amassed enough resources to make use of these tools, they're overshadowed by the other equipment available.

I propose to balance BM by perhaps making slate and infused materials easier to create and automate.

Addendum - if possible, consider adding a socket module to bound armor that negates pollution debuffs.

**Comment by Anarack** [comment]
We may also looking into tweaking the warp amounts for blood magic as that can be a significant turn off to wanting to start the mod.

**Comment by Anarack** [comment]
Ok totaling up the bm tab research reaches 234 warp... thats around 1/3 the total warp in the pack in one tab.

**Comment by DoomSquirter** [comment]
it's really not so bad tho?  Getting past the LP hurdle before WoS was solved by primordial greaves infused with terra standing on a cactus and setting a autohotkey to hold rmb down while I watched a movie :)  

warp with bm?  yeah, it's a lot but honestly, I didn't do bm till after I did the tear so warp was meaningless for me.  

please tell me what bm offers as useful things that are applicable here that don't have much easier ways elsewhere.  

I made flight potions for venus.  can make a bunch of other diff potions but those are the ones I needed.
I made a bound pick which is awesome till you run out of LP

I didn't do demon ritual cause literally just got bored.  

none of the armor compares to other things you can get.  weapons, same.  

green growth won't work on ic2 crops and if you want to speed up normal crops, you might as well use sprinklers.

teleposers could be useful for teleporting.

what else is there?

**Comment by DoomSquirter** [comment]
oh, someone reminded me of this the other day.  sigil of magnetism would be a decent option for magnets.

**Comment by BlackFlameTNT** [comment]
Life and soul shard is needed for some end game quest for DE and you need max tier alter for some infinity stuff there few toys but I didn't see that good use for me.

For balancing I would say remove some of the warp I understand high warp because it's forbidden magic using blood and maybe moving some infuser to arcan table making 200+ infusion for the deamon city is not fun it's tedious I would say it's OK for servers because ppl can share the city and the project but in single player it's not.

**Comment by redmage17** [comment]
1. Progression can be made easier by adding a fucking use in the shop for the coins you get from the quests.(This need done PERIOD).

2, All the recipes need re-examined and buffed. Keep in mind you need to make thousands of the alchemic materials. Most rituals and components in blood magic requires these to be functional. If I can get a GT machine that has less progression, can do more and only requires energy. You have essentially made a  large portion of the mod USELESS. 

Individual examples incoming

**Comment by 0lafe** [comment]
>moving some infuser to arcan table making 200+ infusion for the deamon city is not fun it's tedious

That's where I'd disagree, that's mainly used as a lategame ritual for entrance to DE. The infusions aren't tedious unless you make them tedious. WA infuser will kill that in a matter of minutes at most. Kind of a tier appropriate challenge in many ways. If anything it's a little simple to do, but considering it's just a stepping stone it's not the worst thing. 

>Progression can be made easier by adding a fucking use in the shop for the coins you get from the quests.(This need done PERIOD).

Not really a great thing though. Adding more free stuff isn't really going to help this. 


I'm with doom on finding what's useful. I've heard the pick is amazing, well beyond other hand mining options. There's some good stuff I've seen, things I'd use BM for, but after IVish. Magnet is probably best pre DE, other sigils are amazing too. Haste/mining speed is super nice, and potions of saturation aren't bad. 

There's super easy to do tiering withing the mod, as each tier up will need the orb which is already gated kind of hard on some. 

Overall it seems like the intent is to make this a midgame magic mod, sort of like an upgrade to thaum. I'm not mad at that, and I've heard it has some useful ass shit, but idk much of the mod so I'm not sure if it deserves it. If BM is meant more for midgame, all the recipes are pretty ok in terms of item amounts.

**Comment by mitchej123** [comment]
> WA infuser will kill that in a matter of minutes at most

Anything balanced around WAs is badly balanced :-/


I'm fine with the endgame stuff being challenging and gated, but it should open up earlier on and be less grindy/tedious for that purpose.

**Comment by ScriptedPiky** [comment]
> > WA infuser will kill that in a matter of minutes at most
> 
> Anything balanced around WAs is badly balanced :-/
> 
> I'm fine with the endgame stuff being challenging and gated, but it should open up earlier on and be less grindy/tedious for that purpose.

A process I could find in reducing the tedium associated with BM recipes is reducing the time on infusion recipes by lowering the essentia, but increasing cost possibly and doing the same for a lot of other recipes as well? I will have to look back onto BM more from my last previous playthrough of it. As I can say for certain, even at the EV-LuV+ stage, it was horrible doing EVERY infusion without a WA. Everything took ages, the altar itself took ages to do recipes as well. Even having constant auto mob killing, the farming took hours to get a few items just to slowly boost the altar. But yes, I do agree with you that balancing around a WA instead of looking into balancing the problems themselves is not a great way of going at it.

**Comment by 0lafe** [comment]
>it's too slow

>No I won't speed it up 


Mhmm......

**Comment by ScriptedPiky** [comment]
> > it's too slow
> 
> > No I won't speed it up
> 
> Mhmm......

Using a WA to deliberately increase the entity to process X amount of times faster than originally intended is certainly not a way to balance the recipe. No, using EU/t does not balance it whatsoever. You can achieve extremely fast speeds with 4 LV world accelerators and for what, that is your balance? Sending in MV EU/t on a cube instead of addressing the main core problems?

This is because you are not considering the rest of the playerbase that don't use WA's and instead have to suffer through the long recipe times and heavy resource & tedium recipes. You are also not addressing future problems with your bandaid solution. Should the WA EVER be disabled in any means, then this solution will fail in the end. It simply does not cope well with the rest of the community as many have their opinions on the view of WA's. Do not assume that I won't speed up the Thaumcraft tedious recipes because this is the only bandaid solution out there, I just heavily disagree with the overall balancing decision that you take.

Instead, we should balance the recipes associated with the heavy tedium as a whole. With careful consideration of the recipes we choose, we can address the tedious recipes while still retaining the overall difficulty and not enforcing a silly gimmick. Overall, the rest of the community will be happy, you can still WA as you please and these recipes will stand for a very long time without having to address them in the future in case something happens (WA disabled).

Hard fix over bandaid fix for a solution that can be solved with some careful consideration towards recipes.

**Comment by Folanlron** [comment]
I would like to use the spells, but until I get the purifying bauble I'm not even looking at the dam tab, there is just way too much warp for it to be even worth while, especially when just starting out.

The actual spells you can create, are amazing...

And on WA's my server is already crying at the amount of chunks we have too load, pumps on moon, mars, and everyones base, WA's are not the answer for everything..(we are thinking of just adding creative  tanks on Ender tanks, with Oil/Saltwater just too save TPS)
