### ISSUE TITLE
Revert ChiselTones Server-Config to Default Mode

### ISSUE THREAD

**Issue by finkledoodle** [GTNewHorizons/GT-New-Horizons-Modpack#4845]
#### Which modpack version are you using?
2.0.7.5
Since it was added, the ChiselTones mod has worked with the default mode below
![image](https://user-images.githubusercontent.com/12854704/61162535-e76d8780-a4bd-11e9-8c5a-f234c2b5e809.png)

As of a recent update however, the config was changed from 0 to 1, meaning that attempting to chisel a ztones block now results in this
![image](https://user-images.githubusercontent.com/12854704/61162559-04a25600-a4be-11e9-9e67-95d285363bde.png)

This new change makes Ztone blocks much more annoying to craft as they now require an array of various materials whereas before it was a simple matter to chisel to different types, and then use an Ofanix tool to select a sub-type block once chiseled. These blocks are purely aesthetic, and I see no reason for the change to make them more tedious to craft.

**Comment by Bryfer** [comment]
ChiselTones was never intended to be in mode 0. That was a misstake made when adding the mod.

**Comment by finkledoodle** [comment]
That seems to be the default mode for the mod however, and the server used that mode for 2 years now. Although not intended, the fact of the matter is that it is vastly superior and more convenient than the alternative mode that was recently changed to.

**Comment by draknyte1** [comment]
> more convenient

Welcome to GTNH,
Where convenience is being nerfed.

Honestly, This is one of those changes that don't effect gameplay and I'll stand by Bryfers late fix. I feel that while most Aesthetics shouldn't have much cost, these really don't. If the investment is 10k iron and 10k+ of other things, you're really barking up the wrong tree saying 'cost' when you've got an uber base size wise.

**Comment by DoomSquirter** [comment]
I actually prefer the way it is now and that's how I set it before change was made.  I prefer using chisel to change between the blocks of the same type versus holding down sneak and scrolling mouse wheel.  I guess there's an optional recipe with the thingie as well but yeah, I just flat out preferred using chisel.

the fact that you can change between the various other blocks really never was something I wanted to do.

**Comment by observeroftime02** [comment]
I've had a hot moment to think about it, and I've come to my conclusion.
The idea to change between different blocks via Chisel is silly. There's different crafting recipes for the different types of blocks, and bypassing those via Chisel is essentially an exploit. The chisel should change through the different variants of the same block and that's it.

Now, there is an issue with the crafting recipes for some of the blocks though, because items like blaze rods or ghast tears seem disproportionately expensive for a purely decorative block. Perhaps there's room for improvement there. Instead of using a ghast tear, use any other type of block from the nether that can be grabbed easily, like I think the ash block is not used for anything, so that could be a replacement. Or are nether fortress bricks being used for something? That too could be a replacement for the blaze rods, which drop pretty infrequent.

**Comment by DoomSquirter** [comment]
I wouldn't mind recipe changes for the blocks themselves.  My concern is one of convenience not of balance.  Since you can't do both at same time, it's one or the other and I prefer to visually choose what block I want in chisel.

**Comment by richardhendricks** [comment]
Instead of blaze rods it could by tiny piles of blaze powder. There are a couple of ways to get blaze powder so it is easier to obtain.

**Comment by observeroftime02** [comment]
That sounds like a reasonable suggestion. A tiny pile would make this much more bearable by a factor of 8 to those that don't have crops or bees or mob farms.

Also, I did not take into consideration that blaze rods and powder can be farmed from IC2 crops, but that's still somewhat iffy, because crossbreeding a certain IC2 crop can either happen really fast or you can wait until you're done your play through and never get it.

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/61175857-c341a180-a5b6-11e9-9357-0780d83b7183.png)
@observeroftime02 did you mean this recipe as an example ?

**Comment by Dream-Master** [comment]
if yes i never touche this mod recipe so need to make a new script file for it.

**Comment by voidlogic** [comment]
> I've had a hot moment to think about it, and I've come to my conclusion.
> The idea to change between different blocks via Chisel is silly. There's different crafting recipes for the different types of blocks, and bypassing those via Chisel is essentially an exploit. The chisel should change through the different variants of the same block and that's it.
> 
> Now, there is an issue with the crafting recipes for some of the blocks though, because items like blaze rods or ghast tears seem disproportionately expensive for a purely decorative block. Perhaps there's room for improvement there. Instead of using a ghast tear, use any other type of block from the nether that can be grabbed easily, like I think the ash block is not used for anything, so that could be a replacement. Or are nether fortress bricks being used for something? That too could be a replacement for the blaze rods, which drop pretty infrequent.

This argument is silly because Ztones are all just colored stone.  Mass producing the stone slabs and making the autochisel and ofanix patterns is challenge enough for such a simple decorative block.

+1 for revert to previous chiseltones behavior.
