### ISSUE TITLE
[RFC] Ore Overhaul

### ISSUE THREAD

**Issue by bartimaeusnek** [GTNewHorizons/GT-New-Horizons-Modpack#4885]
Currently, there are many pure ores on higher tier planets, like chrome, platinum and other elements. This does seem off in the pack as a whole, having increadible hard recipes, while on the other hand having rather easy ore processing.
As a solution for this, i would suggest removing all pure ores from planets (not the overworld) and replace the ores with other ores that at least need to be electrolysed/centrifuged into different materials.

**Comment by 0lafe** [comment]
Remove Ir, Pt for sure. Some Nq stuff at some point would be great too. Neodynium would be cool to change too probably.

**Comment by basdxz** [comment]
Agreed, I would suggest going a little more in-depth with some of the ores and requiring processing chains similar to that of Titanium for the base tier materials.

**Comment by Scottishprog** [comment]
If you get the same amount of end product, the change is only in the processing needed, sure.
Nice to have a reason to build an oversized ore processing system.

This means the veins would increase in density, correct?

However, I would be careful on how many titanium-type processing chains are needed. AT least, make is so one setup can be used for all of the ores for multiple tiers.

**Comment by observeroftime02** [comment]
> At least, make is so one setup can be used for all of the ores for multiple tiers.

Would be nice for sure, instead of having to deal with 20 different fluids. Something along the lines of the titanium processing chain is a good point of reference for this.

**Comment by basdxz** [comment]
I think having 'one' setup wouldn't fit with the nature of this pack, I'm sure some varying routes of chemical ore processing could be figured out for the ores with some overlap between them.

**Comment by richardhendricks** [comment]
What are the benefits of high tier planets?

1. New materials you can't get elsewhere.

2. Being able to get old materials easier.

I don't see a need to always make the processing chains ever longer and harder. It removes a big part of the "Yay, I invested all this work and now have easy access to X!" thrill of the higher tiers to always have ever-longer chains.

**Comment by PoptartOverlord-Xabedo** [comment]
Ah yes, I can clearly see it! The amount of filters everyone is going to use! This will be amazing to setup and even better for servers like delta!




3tps max here we come!

**Comment by combusterf** [comment]
Richardhendricks is entirely correct about game balance, and this is probably the prime argument for the recent move to add pure titanium back (#4839) - pretty much the opposite direction of this ticket. And for the people in the process, the titanium nerf was a pretty big one - be it validated by realism.

A platinum nerf would be counter-realism (platinum group metals are the next closest thing to noble gases and appear pure in reality) and counter-balance and would thus be a nerf for nerf's sake. 

There's certainly some wiggling room for balance and realism where there could be more incremental upgrades of relative ore yields compared to processing, but a blanket removal of pure ores is a bad idea IMO.

**Comment by 0lafe** [comment]
Another thing I'd like to add, is if we get more compounds that contain the materials in use, I vote that we change the bees/crops to give these as outputs instead of the pure ores. So autoclaving/centrifuging/drops would be something like rutile instead of Ti, or tungstate for W, etc. No pure drops from them, unless the pure ore is the only ore. Could also split bees into 2 and have the pure bee locked behind the pure ore, if one exists later.

**Comment by 0lafe** [comment]
>What are the benefits of high tier planets?

>New materials you can't get elsewhere.

>Being able to get old materials easier.

Doesn't make a ton of sense here though. The point in a way is to make those new materials you find not the easiest things to process. You get a new ore, but it's mostly just pure ores out there. Also, getting previous things easier also doesn't mean you need to get a pure form of it. Having a higher concentration of a useful material in a higher tier ore block would still be a benefit, and still follows the 2 goals of rockets you wrote. Not sure if I overall agree with them though, but that's less important

**Comment by Shattered2909** [comment]
Pure ores are always one or more tiers above, so no reason to remove. Impure titanium is EV, pure is IV, LUV or whatever. Absolutely nothing wrong with that. Stop the unnecessary nerfs. We already need MORE different ores on planets, this is counterproductive. Some planets are useless.

**Comment by 0lafe** [comment]
Pure Ir gives a bunch of Os, and shows up around the time you really start to need it, being in LuV. Plat is IV, which again is around the time you start using a lot of plat. Neodynium is given right when you need it. Moon chrome is given in the tier of stainless. Naq is always a pure ore. Tungstate is a very simple ore to ingot for IV. Trinium is just a small ore then a centrifuge. 

Compare almost any chem product to an ore one and it's kind of sad the lack of complexity they have.

**Comment by Shattered2909** [comment]
Moon chrome is not stainless tier. The moon is EV. For naq... well it is quite rare and a pain to process, nerfs not required. Tungstate is annoying, primarily cuz 1 tungsten from 7 tungstate and EVERYTHING in IV eats tons of tungsten.

**Comment by richardhendricks** [comment]
Thats...real life, you know?  Ores generally are Oxygen, Silicon, Aluminium, with a mix of other stuff. You're just not going to get the complexity you can with organics.

**Comment by 0lafe** [comment]
The processes of isolating the elements in the ores is usually not just a centrifuge or electrolyzers though. Implementing more complex extraction processes is mainly what I mean.

**Comment by observeroftime02** [comment]
Gold for example, is rarely ever just mined as a pure metal. Typically the gold containing Ore is dug up and extracted via cyanide or mercury processing which is a multi-step procedure. Electrolysis is used to refine the gold into a purer metal.

So there's some simple steps to it other than tossing the rock into a macerator and centrifuge and getting a highly pure dust out of it that can be smelted right away.

**Comment by richardhendricks** [comment]
That's true *now* because we've harvested much of the pure gold "metal" from the surface and are now picking through the less pure veins. Humans have mined gold without cyanide or mercury for thousands of years.

**Comment by observeroftime02** [comment]
Yeah that's true. I'm just using gold as an obvious example because I'm somewhat familiar with the process. Perhaps the gold from small ores could be a purer metal whereas the stuff from the deeper underground veins could require more processing. 

Maybe there can be a correlation between how deep the ore-bearing rocks are found and how much processing it requires?

**Comment by 0lafe** [comment]
This is absolutely a case by case thing, but Scheelite for one seems to have a more in-depth processing than what we have in game right now. I'm sure we can really expand on rare earth proc, with more interstage fluid mixes and stuff. 

Ir/Os might have something besides PGS, but with the chalco amounts on planets, I'm not mad at leaving that as a main source.

**Comment by noobyaran9** [comment]
I actually wouldn’t mind the pure ore removal if the following condition are fulfilled:
1) Impure ore variant outputs more when crushed (at least buff all the impure variant to output 4 crushed or even 6 rather than only 2 depends on the ore type)
2) Bees and Crops are not taken into consideration when applying this change (this can be discussed in a seperate thread and beed and crops are meant for supplement rather than a source
3) I would appreciate if we give more love to chemical bath in term of outputting certain impure stuff (gold from copper or platinum from nickle) but we would need to carefully think of the type of fluid to be used in the recipe. 
4) Reduce the time in certain ore processing especially centrifuging (some of the ore takes like fucking 100+ seconds to process a single one, please be considerate to the lower tier player)
5) Current way of processing impure ores should be untouched (only addition, no modifications)
6) If the impure version of the ore does not exist in the game, please do not force it to exist, the pack already have so many item in game and its really lagging out the pack. Im sure we can think of a way to extract those ore from other ore variant and leave the pure ore to be on Tier + 1 or 2 planet.
7) Pure ore's byproduct should be removed and solely giving only pure variant of the ore. For ex., iridium ore should only give iridium dust and nothing more.

**Comment by noobyaran9** [comment]
Also, please bring this thread up to the discord for the community to vote on, as this is quite a huge change to the pack.

**Comment by Scottishprog** [comment]
A related issue here is how BAD our tools are for dealing with more than 20 or so ore variants... at least pre AE2/SFM.
For us low tier players filtering ores around quickly grows to the point of impracticability. 

One nice thing would be blocks, filters etc. designed to make ore/dust sorting a bit more practical. (And perhaps have it a bit more computationally efficient...)

**Comment by 0lafe** [comment]
>A related issue here is how BAD our tools are for dealing with more than 20 or so ore variants... at least pre AE2/SFM.
>As a solution for this, i would suggest removing all pure ores from planets

Post both of those though. Filtering multiple fluids and items is something that's more than achievable by planet tiers.

**Comment by sthegreat** [comment]
Before AE tier there are only a few special ores to automate, and the normal ones can be easily covered using type filters and enderio conduits. Once you have titanium down AE is available, allowing the player to use its very powerful tools for item distribution.

**Comment by bartimaeusnek** [comment]
@Scottishprog @sthegreat as i wrote in the OP post, this change should only be applied to plantetary ore, not to Nether/Overworld veins.

**Comment by 0lafe** [comment]
What do about the stupid GC/metallurgy, or whatever they are, ores? Like oriharukon/orichalcum/mytryl/etc
