### ISSUE TITLE
Adjust recipes for UEV and UIV energy hatch

### ISSUE THREAD

**Issue by observeroftime02** [GTNewHorizons/GT-New-Horizons-Modpack#4977]
The current recipe for the UEV and UIV energy hatch is literally just a hull plus a wire. 

UEV is made with bedrockium plates and draconium wire.
![image](https://user-images.githubusercontent.com/43228249/64070827-78402400-cc20-11e9-97c7-f9076605e088.png)

UIV is made with black plutonium plates and nether star wire. 
![image](https://user-images.githubusercontent.com/43228249/64070828-7f673200-cc20-11e9-909b-b21889658ac7.png)

Obviously, this is extremely cheap and not in line with hatches from the previous tier. The UHV hatch has to be researched in the research station and requires the assembly line for construction.

![image](https://user-images.githubusercontent.com/43228249/64070833-9017a800-cc20-11e9-9b0c-53d791ae7424.png)

The UEV and UIV energy hatches could require higher tier materials, and a similar process with the research station and assembly line. Instead of using wire coils made from Awakened Draconium, these could require something harder like an Infinity wire coil or something. I'm not sure how exactly the recipes should look like, maybe you guys have some ideas? Right now they are much much to cheap to make.

**Comment by Dream-Master** [comment]
sure the recipes need to changed.

**Comment by Spartak1997** [comment]
@Dream-Master 
I recommend adding a new cooling cells
![sRtbRTRmqTU](https://user-images.githubusercontent.com/29407630/64075958-96149400-ccc7-11e9-988e-50b98319da07.jpg)
![gUSBw2xq6i8](https://user-images.githubusercontent.com/29407630/64075963-9dd43880-ccc7-11e9-93f0-b6fe14b01faf.jpg)

**Comment by Dream-Master** [comment]
@Spartak1997 did your repo have this one ?

**Comment by Spartak1997** [comment]
@Dream-Master I will try make it tomorrow. But what is a fluid using for this? Callisto Ice or Ledox?

**Comment by observeroftime02** [comment]
I would also suggest adding two new voltage coils made with a tier appropriate material for these. As far as proper IC chips go, maybe some form of Pico wafer?

**Comment by Dream-Master** [comment]
Need more wafers and more high tier circuits and pumps for it. Coils need new tiers too.

**Comment by Spartak1997** [comment]
And superconductors too

**Comment by yukieiji** [comment]
As of yet, these recipes have not been implemented....

**Comment by yukieiji** [comment]
The fact that the recipe hasn't been implemented allows for a powerful glitch when combined with the InfinityTurbine.

**Comment by Prometheus0000** [comment]
UHV for reference
![image](https://user-images.githubusercontent.com/8517039/115476470-f004fd00-a20f-11eb-86ee-5db567a89b4b.png)
![image](https://user-images.githubusercontent.com/8517039/115476467-e9768580-a20f-11eb-8877-49360469250e.png)
UEV
![image](https://user-images.githubusercontent.com/8517039/115476300-9f8d9f80-a20f-11eb-9137-790ebe608caf.png)
UIV
![image](https://user-images.githubusercontent.com/8517039/115476336-a74d4400-a20f-11eb-87df-f83c00989954.png)
UMV
![image](https://user-images.githubusercontent.com/8517039/115476345-acaa8e80-a20f-11eb-9e98-9872c1cd63bd.png)

I also did the dynamos. Since there aren't parts for most of this stuff, it's just x2 materials, power, etc each time since that seems to be the pattern.

Please understand that these are temp recipes, and I'm not going to make new parts, as that's a whole different thing in terms of balancing, what materials to use, etc, when the already existing stuff isn't necessarily balanced. And would take forever to discuss. This is to prevent people from abusing the low cost of these without disabling them.

**Comment by Prometheus0000** [comment]
Merged in our fork until technus reappears.
