### ISSUE TITLE
[RFC] Making pollution a pain again

### ISSUE THREAD

**Issue by richardhendricks** [GTNewHorizons/GT-New-Horizons-Modpack#5169]
This is just a fuzzy idea, not a serious proposal.

What if we made pollution two-tiered, like warp?  

Basically, add a "permanent pollution" number that acts as an adder to the current pollution number. This permanent pollution increases if your normal pollution exceeds a certain amount. So if your normal pollution exceeds, for the sake of discussion, 600k gibl, a small percentage goes into your permanent pollution number (with some maximum, perhaps 3x the current normal). And pollution effects are calculated from normal+permanent.  This would mean that being lazy now has much higher ramifications, and can lead to permanent effects that don't go away with time.

Normal pollution would dissipate as it does now, but permanent pollution could require some new simple "machines" - in quotes because they would be "parks".  Like you would setup a "machine" that grows plants or trees to filter the chunk's permanent pollution. Small 3x3 at low tiers to larger parks for more pollution removal.

In addition, pollution effects would be added to machines, with the pollution affecting the speed or power usage, or if we're feeling really mean, adding a void chance.

**Comment by Methes** [comment]
Cool idea with permanent pollution requiring advanced processes to get rid of.

I'd rather not see pollution affecting machines, only greenery. The way I see it there's 3 types of bases I think we should keep:
1) Lush garden - almost zero pollution, green gens, no problems with farms etc.
2) Tech city - regular base, middle pollution levels, certain parts have reduced greenery output due to high pollution (trees, crops, bees etc.), you have to deal with the pollution a bit but not much, collecting it and piping elsewhere (disposing or releasing into the nature)
3) Apocalyptic hellhole - Pollution levels have already transformed large surrounding area to BoP Wasteland biome, frequent rains/thunderstorms, absolutely nothing grows there, everything green must be transported from a completely different area, mutated mobs...

**Comment by KaneHart** [comment]
Not a fan myself of perm punishments even more so in a pack like this. Accidents happen, etc who wants to rebuild a base super late game from a mistake, etc.

I guess one way you could go with this is biome based though and transform it. Not sure if we have biome space left but could create 3-4 new ones with stages of effects and transformation that ends up making it not a fun place to live.

I think there could be so much fun and better shaping the pollution system then it is now, but I don't like the idea of pure perm... Long time sure and or expensive to clean but not forever.

**Comment by Anarack** [comment]
Yes lets fail to learn the lessons show by thaumcraft taint and abyssal craft. Also due to its spreading nature it would be very easy to grief people while ignoring current server protections.

**Comment by KaneHart** [comment]
> Yes lets fail to learn the lessons show by thaumcraft taint and abyssal craft. Also due to its spreading nature it would be very easy to grief people while ignoring current server protections.

Even outside we seen servers make money off clearing warp effects, etc. People willing pay money to fix what I can almost a game breaking feature. So that also shows you in my books that it's not as nice.

**Comment by Methes** [comment]
Well Moron was talking about permanent pollution you can get rid of with more advanced machinery than the basic ones. So it's more like advanced pollution instead of permanent.

Pollution dissipates, taint does not. Meaning pollution requires constant source. Transfering biomes would of course need long term high levels of pollution that would generally be only produced in high concentration of machines - bases. And pollution doesn't spread that far.
We already have taint. Have you seen anyone grief someone by using it already?

**Comment by richardhendricks** [comment]
Yeah, the "permanent" is that it will stick around after your machines shut off, not that there is no way to remove or mitigate it. Just that the current machines wouldn't do anything.

There would definitely need to be some situations we watch out for, like a base explosion that causes millions of gibbl. But the way I was envisioning it, the amount moved to permanent would be a fairly small percentage of what is pushed to adjoining chunks as dissipation.

Basically the logic for normal pollution would be identical to it now, except for when it checks for player effects it would then add the perma pollution. Spreading, dissipation, etc would be the same.

The perma pollution wouldn't spread chunk to chunk directly, just the normal pollution. Think of the perma as gunk absorbed into the soil/rocks/plants/etc. Since it doesn't spread, it would have exactly the same griefing potential as current pollution.

Instead of making it "permanent" permanent, it could also just be long term, like it decays 10 or 100x slower.

**Comment by Anarack** [comment]
Also... someone needs to mess with tech techs explosions as I think they set pollution to max int or something silly like that.

**Comment by 0lafe** [comment]
It would be nice to give pollution real downsides. You can really just leave it as it is now, and even with permanent pollution it'll just be more consistent versions of what it already is. Slowing players down, and for the most part any player based debuff, isn't really a detriment. Considering you can place machines in places no player needs to go, as well as the ways we have for removing/dealing with debuffs, the threat of pollution is really, really small. 

Imo, pollution should fuck with machines. It's a real noticeable detriment that actually makes you address the issue of pollution. Something that either elongates recipes randomly, or machines machines turn off could be a more fun way of actually punishing the player for letting pollution accumulate. If we really want to go hard with it, you could have it fully break machines at certain levels, forcing you to either replace them, or rebuild. Splosions could be fun too, on a few multis >:)
