### ISSUE TITLE
4x batbuff unable to provide continuous 4A power

### ISSUE THREAD

**Issue by richardhendricks** [GTNewHorizons/GT-New-Horizons-Modpack#5177]
4A batbuff connected to EBF is unable to provide 4A LV continuous power.
The batteries internally provide 1A/32 EU/t to the batbuff internal buffer. 
The internal buffer outputs the 4A/128 EU/t, but there is an overhead of 2 EU/t per A, so it really uses 136 EU/t, and the batteries cannot keep up.
This causes the internal buffer to drain in a few seconds.

Attaching one generator to the batbuff makes it work, because the generator 1A fills the batbuff internal buffer before it fills the batteries, topping it off.

This really should work since it isn't intuitive that a "4A" batbuff doesn't provide "4A".  My suggestion is to just allow the batteries inside the batbuff to provide 32 + tier loss EU/t instead of just 32.  That makes the most sense, and still costs the power.

**Comment by richardhendricks** [comment]
From some testing by bot, it looks like the batbuf does undervolt and can effectively provide about 120 EU/t output with 4 batteries.  I suggest modifying batteries to output the (tier + tier loss) amount into machines, so that batbuffs can release their full potential amps.

This also explains why glueing a buffer onto an EBF fixes it, since the output of 120 EU/t would be enough in that case.

**Comment by Sakura-sama** [comment]
Well,I think if you use a cable with 0EU/t cost,all the thing will go better.

**Comment by Methes** [comment]
Yes. And if you go only downhill on a bike with broken chain, you'll be able to go faster.
While your statement is true, it has very little to do with the issue at hand.

**Comment by richardhendricks** [comment]
No it won't go better.  0 EU cables for LV requires MV. This is a common and very typical problem for new players - they setup an EBF further away from their stuff, because we warn about pollution, and maybe they can make batteries easier than they can make generators so they try sneaker-netting it. The game should support that IMO.

**Comment by Cleista** [comment]
Same issue was [re-discovered in GTNH Discord](https://discordapp.com/channels/181078474394566657/181078474394566657/728311010292793455)
 just now and I agree it's counterintuitive to players who don't know how GT energy storage/emission works. 

Why would the amperage output of a battery buffer depend on whether it receives external power or not? If the batteries have power, the buffer should output however many amps it is capable of doing and drain from the internal batteries. Presence/absence of an external power supply should not affect it.

**Comment by dvdmandt** [comment]
So I've looked a bit at this. The logic that handles batteries and how they fill up buffers is in BaseMetaTileEntity here:
https://github.com/GTNewHorizons/GT5-Unofficial/blob/experimental/src/main/java/gregtech/api/metatileentity/BaseMetaTileEntity.java#L278

That class is however not a base class for all GT machines/buffers/whatever, but rather contains a reference to the machine type. The logic for batteries seems to be the same for regular machines as it is for battery buffers. If buffer is more than 50% full, charge any chargeables (batteries), else (if buffer is lower than 50%) drain batteries to fill buffer. It will always drain up to 1A afaict. The machine type can specify the number of slots containing batteries, then the generic code will loop through it. For any blocks outputting power, it'll drain it's amps + loss from the buffer. The machine type (in this case battery buffer) can't override the draining logic without refactoring.

We could perhaps change the logic to always drain batteries extra to account for loss. It's not super clean, but should fix this issue. For other machines powered by batteries, it would charge the internal buffer a little bit faster at first, but it would still give the same total energy from a battery so it wouldn't really have any significant long term effects as far as I can tell (it shouldn't be noticable really).

Thoughts?

**Comment by botn365** [comment]
that litle extra energy wont make difrence for normal machine being charged from it 
so to me this is fine

**Comment by dvdmandt** [comment]
So it looks like that method only forwards current tier and the max amount of energy it can accept to this:

https://github.com/GTNewHorizons/GT5-Unofficial/blob/a0a77f0b9868a4ca8a3df8ae8d50b4dcfb4030db/src/main/java/gregtech/api/util/GT_ModHandler.java#L1681-L1698

Which caps the amount of EU to the voltage tier and double checks that the item and machine have the same tier. Anyway, then it does this:
```
int rCharge = (int) Math.max(0, ic2.api.item.ElectricItem.manager.discharge(aStack, aCharge + (aCharge * 4 > aTier ? aTier : 0), tTier, true, !aIgnoreDischargability, aSimulate));
return rCharge - (rCharge * 4 > aTier ? aTier : 0);
```
Do batteries already have loss, but 1 per tier instead of tier^2 or am I misreading this?

Anyway, it would seem to me that if we change

`aCharge = (int) Math.min(aCharge, V[Math.max(0, Math.min(V.length - 1, tTier))]);` 
to
`aCharge = (int) Math.min(aCharge, V[Math.max(0, Math.min(V.length - 1, tTier))] + B[Math.max(0, Math.min(V.length - 1, tTier))]);`

and possibly remove that wierd `rCharge - (rCharge * 4 > aTier ? aTier : 0)` thing, it would behave as I expected it to. Keeping the weird thing would mean double loss for battery buffers, but it should still fix the ability to power stuff with only battery buffers as far as I can tell.

**Comment by boubou19** [comment]
if you do change the behavior of the batbuff, please edit this page: https://gtnh.miraheze.org/wiki/Electricity

**Comment by dvdmandt** [comment]
PR here: https://github.com/GTNewHorizons/GT5-Unofficial/pull/362

Is there anything in particular on that page that needs changing? Note that this does not change the amount of energy a battery provides or the cable loss of a battery buffer, it only drains batteries slightly faster to keep up with the output, so that it outputs full strength as long as batteries have power. For powering normal machines, it will make them start the process a few ticks quicker, but have no other effect.

**Comment by boubou19** [comment]
perfect then
