### ISSUE TITLE
Teleportation Balancing

### ISSUE THREAD

**Issue by KaneHart** [GTNewHorizons/GT-New-Horizons-Modpack#5186]
I think it's time we look into some sort of Teleport Balancing. Keep in mind Servers pretty much have their commands but other servers who want more legit transportation as well as SP users, etc it be nice for some balancing.

For example Compare Stargate with Waystones. Waystones honestly should not exist or be cramped really far away. Not sure how a tech based pack with some magic has things like startgates already a fun complex teleport system so far end game but Waystones are insanely cheap.

**Comment by Dream-Master** [comment]
Waystone from Witchery ? @KaneHart

**Comment by bartimaeusnek** [comment]
@KaneHart Witchery is unbalanced currently. Since its ARR Licensed, its quite hard to do it propperly. The roadmap for it is that we might balance Witchery in 2.0.9.X or 2.1.0.X, but we still need code changes for the mods, that change witchery behavior in a legal way.

**Comment by AlexBucket** [comment]
Probably don't use stargates as a comparison. It's been said time and time again that they were really only implemented for server usage, setup by admins kinda thing.

albeit they have a recipe if you're crazy enough.

**Comment by bigbass1997** [comment]
For a long time, stargates didn't have _any_ recipes. I can vouch for Alex, stargates were and still are (in practice) only available via creative/spawning them in.

So is this issue just about Waystones or are there other teleportation mechanics/items that you feel are unbalanced?

**Comment by KaneHart** [comment]
It's not I feel unless you compare it to your unbalanced servers it's that it's beyond pathetic recipe.

Why we adding "junk" that had licencing issues?

**Comment by richardhendricks** [comment]
Waystone have not yet been gregified. Their current recipe is obviously out of balance, and will be adjusted. 

Shit takes time, yo.

**Comment by mitchej123** [comment]
> Waystone have not yet been gregified. Their current recipe is obviously out of balance, and will be adjusted.

Next recipe will take your first born child.

**Comment by bigbass1997** [comment]
> your unbalanced servers

This isn't the place to debate how a server should or shouldn't be set up, that's up to the owner to decide.

I'm just trying to narrow down the issue here. You wanted to figure out some kind of teleportation balance, but so far only 3 methods of teleportation have been brought up.

Stargates are essentially for creative use, only recently having recipes added for those in end-game, just for fun. Server commands (e.g. Essentials etc) are for servers and go back to my earlier point that the server owner gets to decide whether or not to have them. In other words, teleport commands added on a server isn't relevant to this issue.

This leaves only Waystones. Which is why I'm wondering if there are any other teleport mechanics that should be considered for balancing.

**Comment by KaneHart** [comment]
Thanks guys, year the Waystone sort of almost a joke and that was my issue. Question is can me as a server admin adjust this in a way that I can run a server and change it?

My issues are not so much what to change it to or taking time to get around it more that because it's so out of balanced I like to just nip it in the butt for now till we can balance it in the future.


@bigbass1997 I brought up SG as the recipes are crazy and I do agree with the "Past" reasons. That being said there is not much of an excuse these days. I love them heard and heavy. That being said if that is how hard were doing it then why do we have like 1000 fold maybe more easier one like the Waystone method is where  I'm getting at.

Not sure if the Pack should have easy teleports or not I'm always against it but I know the servers you guys run cater to it but already has it's own in house method of teleporting anyways.

**Comment by 0lafe** [comment]
There's alternative teleportation. Witchery also has a ritual with a witch hand that is essentially a one way teleportation. Thaum has same dim teleport gated to IV. BM has interdim iirc, gated to uh, LuVish? Maybe IV if it's just the Pu gating the orb. Ic2 teleporter is a thing, but I think it's same dim and EV/IV ish? They all seem pretty ok where they are, maybe raising the BM one to solidly LuV? Keeping xdim xport to EV+ seems to fit with item movement for the most part. You really start needing it with rockets and dims that don't have portal type entrances. 

Waystones are really the big issue in it, but the issue seems to be changing witchery shit is hard. Witchery++ is kind of a thing tho iirc? I think alk said it's really on dream now to use it to change stuff, so that could be a solution. Tiering them to fit around other methods would probably put them in LuV, being on par with BM but having somewhat of a travel cost. Making the waystones semi costly for LuV is somewhat of a way to tackle this. 

Again, servers have control of easily available plugins to do better than most of these mods. So it's kind of up to you if you want to keep the teleportation nerf.

**Comment by richardhendricks** [comment]
@draknyte1 did Witchery++ to let us change the recipes for Witchery, but we need someone to propose what they should look like, and implement them. @Dream-Master has started doing this, so if you want them tiered appropriately, propose recipes here.

**Comment by richardhendricks** [comment]
https://twitter.com/DreamMasterXXL/status/1193474720617893893

**Comment by Dream-Master** [comment]
@richardhendricks witchery++ far away from done. I ask multies time Alkalus for finish this mod but until today I don't see it is finish. I will using it when the mod is done.

**Comment by draknyte1** [comment]
Why the fuck would I finish my mod if you're not willing to use it in the < 100% finished states it's in?
The implemented functions work perfectly and the lack of care shown towards Witchery as a whole for > 2 years is just sad.

![image](https://user-images.githubusercontent.com/3060479/70994978-49629680-20c7-11ea-9860-beef6e9c46fe.png)

As I said originally, like, 2 years ago, please test and implement what you can, then I will finish the rest. You've never bothered, so again, why would I? You seem to think your demands of me will get results, but you're not special.. I do what I do for free, because I enjoy it. Take what you're given, or pay someone for results. That's reality.

**Comment by Dream-Master** [comment]
I appreciate you doing this in your free time as most of the modders in mc. If you add the missing devices I will start imidetly but without I don't want to start sorry. If I work on witchery I will finish recipes at once. Thanks

**Comment by Prometheus0000** [comment]
Just so they're mentioned, there's also the Witchery Ruby Slippers, which are one-way to "their spawn point in the same dimension", as well as the DE dislocation charms and pedestal. Elevators and Travel Anchors are technically teleportation, but have range limits. The slippers are probably the only one needing nerfing out of these.

**Comment by richardhendricks** [comment]
All, please fill so we can have a coherent discussion.

https://docs.google.com/spreadsheets/d/1Rsz0rH9tIVJxr18b1Z6-QxOSaEKssxF7u2naQTq2Mqg/edit#gid=1377778496

**Comment by GTNH-Colen** [comment]
This has been a huge issue for ages, I get the stargate being extremely expensive as it's a meme item meant really for server operators and not even that useful. However other types of convenient teleportation devices really shouldn't be nigh impossible to craft, mostly concerning the gravisuite relocator and draconic evolution enhanced charm of dislocation.

The enhanced charm takes somewhere around _**13,824 infinity ingots**_ ALONE, never mind other materials.

The relocator uses the enhanced charm in its recipe, so same problem...

Honestly items that are meant to be crafted by players should not be using stargate components as they are deliberately ludicrously expensive.

**Comment by KaneHart** [comment]
Here I was complaining about how easy it was lol

**Comment by GTNH-Colen** [comment]
> Here I was complaining about how easy it was lol

I agree that the witchery waystone is massively underpriced but other forms of teleportation are insanely overpriced. Both ends need a rebalance imo, as the title states. ;)

(With exception to stargates as they're just a bit of fun)

**Comment by KaneHart** [comment]
I could see them all being balanced a bit. I'm never a fan of teleportation and such so I can't really offer much there. Heck I'm asking to have gliders nerfed haha. So you can't use it in Twilight and overworld for performance reasons and well really cheap. I plan on making our nether 1 to 1 ratio so people can't use nether as a shortcut haha.

That being said reading what you said there does seem to be some balance issues for sure.

**Comment by GTNH-Colen** [comment]
Did some thinking and perhaps this is a suitable recipe for the enhanced charm of dislocation? It tiers it behind UV and the legendary tier X quest line as it requires draconic cores.

Enhanced Charm recipe:

8x Wyvern Core
8x UV Sensor
12x Draconium Block
4x Field Generator (Tier VII)
4x Charm of Dislocation
1x Teleporter (From IC2)

<img width="340" alt="Screenshot 2019-12-22 at 04 21 07" src="https://user-images.githubusercontent.com/54497873/71317065-d8c6cb80-2472-11ea-9ce8-a11bc1b8eac7.png">

The relocator is essentially the same thing but from gravisuite instead, so just added a couple extra little things to essentially convert it over.

Relocator Recipe:

2x Large Naquadah Battery
2x Cooling Core
4x Data Orb
1x Enhanced Charm of Dislocation

<img width="119" alt="Screenshot 2019-12-22 at 04 21 18" src="https://user-images.githubusercontent.com/54497873/71317071-ee3bf580-2472-11ea-999f-3572c34d1a1d.png">

I really don't think these items should be locked behind infinity as all they do is make travelling around to your drills/homes a bit easier. In any case they desperately require a change as the current recipe is virtually impossible to craft.

**Comment by Illiux** [comment]
In my eyes, the problem we have to deal with in determining tiering of teleportation is that, for the most part, any sort of teleportation obsoletes all other methods of transportation. A second problem is that Galacticraft is buggy and unpleasant to solely rely upon as you progress further into space.

Taken together, this means that we should tier teleportation relatively late, but should unlock *some* form of interdimensional teleportation at least in early IV and possibly somewhere in EV. Of the teleportation methods in the pack, I think only two are eligible for that kind of tiering:

First, waystones. They differ from most teleportation methods in that they have per-trip material costs. Right now those costs are insanely low but it should be possible to find a sweet spot where they're possible but annoying at IV.

Second and more interesting, AE2 Spatial IO. Right now this is tiered to LuV (solely by energy requirements on a few recipes, it doesn't use anything above EV in terms of materials). Spatial IO differs from most other teleportation methods in that it requires significant setup at each destination and also requires logic (OpenComputers or ProjectRed) if you want to have a multi-destination network. Further, if you mess up you might trap yourself in a spatial cell, which is neat.

I suggest we tier most teleports to LuV+, but pull Spatial IO into early IV or perhaps EV.

**Comment by Methes** [comment]
I second the Spatial idea. You can make it slightly bigger and build a small spaceship inside for RP purposes.

**Comment by Prometheus0000** [comment]
I added more to the spreadsheet page, but since it's changed quite a bit I thought people would appreciate it if I made it a separate sheet, so it is.
