### ISSUE TITLE
Look at simple minetweaker optimizations

### ISSUE THREAD

**Issue by richardhendricks** [GTNewHorizons/GT-New-Horizons-Modpack#5333]
- Start with SHA-1 comparison between local and remote, and only send the script if there is a mismatch

- look at performance options discussed previously. collect the recipe changes, and do 1 pass through the recipe map

**Comment by Dream-Master** [comment]
Bart add the recipe to code. Hope we get a working version soon.

**Comment by KaneHart** [comment]
Awesome. This one my dream fixes in so many way especially multiplayer where you might leave / join a world due to a bug or something and have to go through that minute or so long connection time.

I tested locally and found that the scripts take pretty much the same time and it's just re-loading them that takes a bitch of a time.

Bonus fact: It loads when you open the client then join a server or world so your oddly enough getting taxed twice before you can play.

**Comment by richardhendricks** [comment]
Actually, looking at how MT works, we should create a list of executed scripts and not re-execute them if they match. So that way if scripts were executed during load, they don't get executed again.

Seems to be some confusion on if the scripts are run during forge load, SSP connection, or SMP connection.

**Comment by Dream-Master** [comment]
Or helping bart to get the scripts in code working 100% @richardhendricks

**Comment by draknyte1** [comment]
> SSP connection, or SMP connection.

Same thing. Integrated server fires the exact same events as a dedicated. I mean, it’s been a while, but I don’t ever recall seeing scripts execute during forge’s loading phases. Only when connecting to a server (of any kind).

Logical decision as well would be to only execute once a player loads into their preferred server. As desyncs between local scripts and server scripts would’ve caused many issues. Presumably, This would’ve been adjusted years ago if it wasn’t the original behaviour, as every modpack would’ve been running into this. 

My 2 cents, which may be wrong.

**Comment by Prometheus0000** [comment]
@mitchej123 Is this what you already did? Can this be closed?
