### ISSUE TITLE
Bucket of Concrete iron duplication

### ISSUE THREAD

**Issue by schliip** [GTNewHorizons/GT-New-Horizons-Modpack#5359]
#### Which modpack version are you using?
2.0.8.0pre4
#
#### If in multiplayer; On which server does this happen? 
Private server
#
#### What did you try to do, and what did you expect to happen?
Bucket of Concrete should be able to be processed to 1 bucket's worth of iron (3 ingots)
#
#### What happened instead? (Attach screenshots if needed)
![image](https://user-images.githubusercontent.com/34576051/72589687-ec2a5280-38c9-11ea-93d3-e6c0919e6538.png)
![image](https://user-images.githubusercontent.com/34576051/72589703-f51b2400-38c9-11ea-8ef6-8fadd7c4cfd4.png)
![image](https://user-images.githubusercontent.com/34576051/72589736-09f7b780-38ca-11ea-9965-79ddefeeeaf7.png)

#
#### What do you suggest instead/what changes do you propose?
These recipes should return the 3 ingots worth of iron used to make the Bucket of Concrete

**Comment by Prometheus0000** [comment]
It appears to be doing this automatically, I can't figure it out.

**Comment by Dream-Master** [comment]
Guess this outo output recipes. Maybe we need to overiide it with own ones.

**Comment by xcube16** [comment]
I feel like this is related to this issue, so I will post a comment here instead of creating a whole new issue. The Iron Tank Gauge can be made with ONE iron plate each however, macerating it gives TWO iron dust each. This allows iron to be duped with only a small addition amount of glass (version v2.1.1.0).
