### ISSUE TITLE
Crashes by items from Remote IO mod

### ISSUE THREAD

**Issue by monroth** [GTNewHorizons/GT-New-Horizons-Modpack#5362]
#### Which modpack version are you using?
2.0.7.5
#

#### If in multiplayer; On which server does this happen? 
Eta server. Couldn't replicate in single player.
#

#### What did you try to do, and what did you expect to happen?
Used location chip (shift+rightclick) on drawer controller and then used chip on remote interface (rightclick). Was expecting that remote interface will become linked copy of that drawer controller, so i would be able to pick and dispose items to and from that controller from a distance (worked in sp).
#

#### What happened instead? (Attach screenshots if needed)
Was crashlocked - immediately after linking minecraft crashed, and crashed again every time i logged in back. Last crashlog is here https://pastebin.com/UnYBNGTy . After Rizzok deleted remote interface, i was able to log in.

There was also some other crashes was caused by items from this mod, but they were not crashlocks, after relogging everything was fine. Other crashlogs for that day are here  https://drive.google.com/file/d/1jB0ZGnpNvkTSRG0JrRy3o4gwtcvWEKae/view?usp=sharing
#

#### What do you suggest instead/what changes do you propose?
Investigate and possibly fix? remote io is insanely cool

**Comment by richardhendricks** [comment]
@bigbass1997

**Comment by bigbass1997** [comment]
It looks like we might be using https://github.com/GTNewHorizons/RemoteIO/tree/master in the modpack. But I can't confirm that, nor can I even begin working on a fix, because it won't build.

The AE2 dependency is no longer available from the forge repository, and using a newer version breaks the mod entirely. If someone could figure out how to change the build.gradle file to fix this, then I can begin work. It looks like we have the version needed, over on http://downloads.gtnewhorizons.com/Mods_for_Jenkins/

**Comment by repo-alt** [comment]
I updated AE2 dependency to rv3 and the mod was built w/o any changes, see
https://github.com/GTNewHorizons/RemoteIO/pull/1
What do you mean by "newer version breaks the mod entirely"?
@bigbass1997
