### ISSUE TITLE
Suggestion: add morechisels mod

### ISSUE THREAD

**Issue by PoptartOverlord-Xabedo** [GTNewHorizons/GT-New-Horizons-Modpack#5409]
This is a very tiny mod that only adds more chisel tools, just for the builders who find diamond chisel breaking too fast.

https://www.curseforge.com/minecraft/mc-mods/morechisels

the mod is very tiny, i doubt it will affect performance so i dont see any harm in adding it as it will be a very nice help for the builders

**Comment by richardhendricks** [comment]
License looks acceptable.

**Comment by repo-alt** [comment]
What's the point though, it's not like obsidian chisel is very expensive and hard to make.

**Comment by PoptartOverlord-Xabedo** [comment]
i know right, but would you like your inventory full of chisels?

**Comment by bartimaeusnek** [comment]
I wouldnt mind it, we can add it to the test pack imo.

**Comment by mitchej123** [comment]
+1   Especially with the new things we're adding to chisel.

**Comment by leagris** [comment]
Another possibility is adding Chisels tools to Gregtech:

- `craftingToolChisel`: All Chisel tools
- `toolHeadChisel`: Chisel tool heads using all materials used for tool heads.
- Electric Chisel (LV,MV,HV): Various tiers of electric Chisel tool.

Probably no machine block, because Chiselling is purely decorative and the standard AutoChisel does the job appropriately.

**Comment by Prometheus0000** [comment]
I already added a chisel with max dur, so pointless.
