### ISSUE TITLE
Cooling Avaritia infinity ingot

### ISSUE THREAD

**Issue by ko5h** [GTNewHorizons/GT-New-Horizons-Modpack#5502]
#### Which modpack version are you using?
2083
![image](https://i.imgur.com/WAyGWES.png)
![image](https://i.imgur.com/zRiNjH4.png)
 ebf recipe using 2kk, but for cooling 20kk

https://github.com/GTNewHorizons/NewHorizonsCoreMod/blob/1e30fcc408bc085cb058894195988976f5b1bb5c/src/main/java/com/dreammaster/gthandler/GT_MachineRecipeLoader.java#L1484

#4952 similar rework

**Comment by Prometheus0000** [comment]
Could someone at UHV tell me if this is actually a thing that needs to be fixed? Can you even get this version?

**Comment by boubou19** [comment]
the recipe is still there, but you can only get infinity dusts by recycling GT infinity stuff (macerating ingot, plate, etc). So to turn back the dust into the ingots, you use an UEV ebf to get the hot infinity ingot. But then you have to cool it with the recipe listed below. Meanwhile, instead of recycling it by macerating it, you can fluid extract it at HV lmao. So yeah, at least, remove the extra 0 that makes it ridiculous (checked this in 2.1.0.0)
