### ISSUE TITLE
Mega blast furnace cannot be operated with a machine controller cover + redstone signal

### ISSUE THREAD

**Issue by Aggadahr** [GTNewHorizons/GT-New-Horizons-Modpack#5526]
#### Which modpack version are you using?
2.0.8.3
#
#### If in multiplayer; On which server does this happen? 
delta
#

The mega blast furnace is so constructed, that the controller block is surrounded by glass. Glass stops any kind of redstone signal and doesnt allow redstone signals to pass.
Thus, the Multiblock cannot be operated with a Machine controller cover as there is no way to trigger it with a redstone signal

![2020-02-06_14-52-43](https://user-images.githubusercontent.com/46688121/73944811-7d05b400-48f3-11ea-94ca-87c4895dba6c.png)

So far i have tried Vanilla Redstone and repeater, red alloy wire, enderIO Redstone conduit, Automagys Red crystal, wireless redstone emitter/receiver 
none of these work, the glass blocks any kind of signal

Please change the behaviour of the glass or the layout of the Mega Blast Furnace, or implement some kind of redstone emitter/receiver that passes through glass, so it can be operated with a machine controller cover + Redstone signal

**Comment by Bubunator** [comment]
also you cant trigger the Mega EBF with a redstone signal from the backside from inside of the hollow multiblock. Upon reloading the chunk it will give an incomplete structure until you remove the blocks (e.g. wireless receiver) from the hollow inside.

**Comment by GTNH-Afx237v7** [comment]
I don't think this is a bug - the MBF is simply designed this way. You can try a transvector interface. Although I doubt it makes much sense to operate this multi via a cover - it's intention is to mass process dusts.

**Comment by boubou19** [comment]
if you cannot control the controller itself, you still can control the inputs in the MBF: it cannot start if there is nothing to bake ;)

**Comment by Glease** [comment]
There is already wireless redstone cover. No need to implement anything new.

**Comment by Glease** [comment]
To add a bit of detail, you will need to **replace** your machine controller cover with Redstone Receiver (In). If the receiver detected a non negative signal on its configured channel it will **enable** the multiblock. If the receiver detected a zero signal on its configured channel it will **disable** the multiblock.


https://user-images.githubusercontent.com/4586901/122360878-53e64080-cf89-11eb-8121-94176dffbfa7.mp4

In this demo I was using a single block steam turbine as the block being controlled, but that's just because it's a block that have some nice animation showing whether it's working. It works for any GT tiles that can be disabled by a machine controller cover.
