### ISSUE TITLE
Infernal Mobs changelist

### ISSUE THREAD

**Issue by richardhendricks** [GTNewHorizons/GT-New-Horizons-Modpack#5553]

**Comment by richardhendricks** [comment]
To do list
- [ ] Check PR
- [ ] Fix regen display

**Comment by richardhendricks** [comment]
Investigate this. Do regen mobs keep regenerating past max health? https://cdn.discordapp.com/attachments/676137963914002526/676137984206176306/image0.png

**Comment by Entih** [comment]
Infernal mob regen increases max health, and damaging a regen mob decreases max health (which is itself why the hp display is faulty).

**Comment by wlhlm** [comment]
I have been looking a bit more closely at the Infernal Mobs code.

This isn't surprising since the health handling is literally called a 'hack' in the Infernal Mobs code. Unfortunately, I don't know how to manually spawn an Undying Regen Zombie Pigman to reproduce this (and I can't see obvious problems by just looking at the Infernal Mobs health code). I feel like undying is relatively rare among the Thaumcraft Champion mobs and having that stack with regen Infernal Mob modifier should have a pretty low chance, so I'd treat it as a rare edge case (until I can find a way to reliably spawn such a mob in-game).

**Comment by richardhendricks** [comment]
Any regen mob behaves this way from what I see.
