### ISSUE TITLE
Discussion on thaumcraft warp and balancing it

### ISSUE THREAD

**Issue by Prometheus0000** [GTNewHorizons/GT-New-Horizons-Modpack#5643]
Refer to #5604

This is so the discussion on warp balance can be separated from the discussion on warp research specifically for BM.

People have brought up: altering the warp theory configs (currently the highest effect is 80, it can go to 200), adding new effects (such as weaker monsters than the wither, or more 'scary' stuff), whether having a wither spawn is balanced (would blow up your base, at least on SP), the fact that pure tear is all or nothing, adding other stuff to reduce warp somewhat (An easier version of the pure tear that reduces it by, say 5? Something like heart canisters that are equippable, stack, and reduce warp by 1/2/3/etc?), a warp ward potion (presumably easier to get than the salt, or longer lasting), the fact that machines that exist (soul brazier and the tumor) have serious bugs, the very high amount of warp due to large numbers of addons, that people don't use BM because of the warp, that people who aren't familiar with TC can easily screw themselves over with warp, and probably some I missed.

**Comment by yukieiji** [comment]
#### Info on GTNH's warp #### 
・All Warp Amount: 
| Permanent | Normal　|
| ------------- | ------------- |
| 667  | 512  |

・Warp Effect: (+ TC Warp Effect)
| Warp Effect| Warp Amount |
| ------------- | ------------- |
| Fake explosion&Fake Creeper | 10  |
| Spawn bats | 15 |  
| Poison | 16 |
| Jump boost | 18 |
| Rain&Blood&Nausea | 25 | 
| Friendly Creeper | 26 | 
| Lightning |  30 | 
| Livestock rain | 32 | 
| Wind | 32| 
| Blindness | 43 | 
| Random teleport | 45 | 
| Acceleration&Decay&Random tree | 50 | 
| Chest scramble&Spawn Wither | 80 | 

・Item/Machine of reducing Warp
| Item/Machince name | Mod | Type and amount of warp to reduce |
| ------------- | ------------- |  ------------- |
| Sanitizing Soap | TC | Temp only |
| Tabacco Pile(Default) | Thaumic Bases | Temp only(probability) |
| Wand Focus:Flux Scrubber | Thaumic Bases | Normal and Temp(probability) |
| Warped Tumor | Thaumic Horizons | All(up to 50) |
| Soul Brazier | Thaumic Exploration | All |
| Pure Tear | Warp Theory | All |

・Item/Machine of prevent WarpEffect
| Item/Machince name | Mod | 
| ------------- | ------------- | 
| Arcane Spa | TC | Temp only |
| Thaumic Sauna Stove | Witchin Gadgets |
| Talisman of Remedium | Thaumic Tinkerer |

**Comment by Prometheus0000** [comment]
The soap has a chance (50%+?) to reduce normal warp as long as you're under warp ward/in the salted water.

**Comment by quedral** [comment]
Yes, We all know and hate warp. its an annoyance and unavoidable. 

Any case if you want to add an item (craftable by infusion i assume) that reduces warp you probably need to code an addon and add items that do that right? i don't see any other way.

Alternatively amount of warp added can be reduced by altering TC and its addons recipes which is kinda PITA going through 1 by 1 each one.

I would like to see amount of warp reduced/removed or managed by other item however both alternatives require serious work and i am doubtful that anyone would like to tackle that.

**Comment by Prometheus0000** [comment]
Well, I checked and figured adding a new item to warp theory wouldn't be that hard, and it wasn't! I added an item that reduces warp by 1, it goes temp -> norm -> perm so you still need to use soap for optimal usage. 

Some things to note: 
1) It reuses the texture of the pure tear, if someone wants to submit one with a change in the color slightly or something. The center red to blue or something?
2) I can't figure out how to get the research to unlock OTL. It shows up when you use the cheat thaumonomicon though. 
3) It needs a real recipe (for the pack), it's using a copy of the vanilla WT PT one. It should be much easier than the PT.
4) If approved, stuff like the recipe needs to be added to Warp-Theory.zs
5) I tried getting the version to update, it didn't for some reason

You can check out the code or use this file:
[WarpTheory-1.7.10-1.0k-Dev.zip](https://github.com/GTNewHorizons/NewHorizons/files/4252139/WarpTheory-1.7.10-1.0k-Dev.zip)

https://github.com/Prometheus0000/WarpTheory/tree/AddNewItemTest

**Comment by ScriptedPiky** [comment]
I like the sound of it being able to remove warp, but I wonder if there will be a chance to remove perm warp, as being able to remove it on a "lesser" tier item can be quite powerful. However, with some balancing of the recipe, we could strike a sweet spot for it.

**Comment by Prometheus0000** [comment]
Changed the Warp-Theory.zs, it now shows up properly after you have the pre-req (though, should it be eldritchmajor instead of minor? Will people clear all their warp before getting the second eldritch research?) It currently has the recipe for the Pure Tear as a placeholder.


[Warp-Theory.zip](https://github.com/GTNewHorizons/NewHorizons/files/4252234/Warp-Theory.zip)

**Comment by Prometheus0000** [comment]
How about this for the Warp Theory effects config:

Warp Effect | Warp Amount
-- | --
Fake explosion|10
Spawn bats | 15
Fake Creeper | 20
Blindness | 25
Poison | 30
Rain|35
Blood|40
Jump boost | 45
Nausea | 50
Friendly Creeper | 60
Livestock rain | 70
Wind | 80
Lightning | 95
Random teleport | 110
Acceleration|125
Decay|140
Random tree | 155
Chest scramble|170
Spawn Wither | 200

So until you get to 70, no crops will be damaged, and no blocks altered until 125.

**Comment by richardhendricks** [comment]
Lightning causes damage because it can knock carts off of rails or start fires

**Comment by yukieiji** [comment]
If we change the amount of warp effect and , we have to consider how much research is acceptable.
If you increase the effect of Wither Spawn to 200, you will be allowed to research Ichor(Until the release of Ichor, about 200 Warp(Permanent100, Normal100) accumulate)
@Prometheus0000 How much do you think research should be acceptable?

**Comment by repo-alt** [comment]
> Lightning causes damage because it can knock carts off of rails or start fires
Carts, bah, it can destroy a rocket...

**Comment by Prometheus0000** [comment]
Shouldn't you have carts underground to not get killed by normal lightning anyway? I guess fires are a thing, but all acceleration, decay and random tree (worse than it sounds) all change 'natural' blocks. And I imagine random teleporting is more annoying too.

Well, I don't really have any numbers for you about that. I just think it's too much too soon now, and I also rearranged them in a more logical order. Like, why was blindness 43, while lightning was 30? If people want it to max at 100 or 150, that would still be better than it is now. I do think you'd probably (guessing mostly) have around 100-150 to unlock ichor stuff? But that's just research, you could get that done almost immediately, in MV or HV, right?

Try using the salts for warp ward before going to a rocket. But I don't know if you can place water on other planets, so you might not be able to do the same thing before you come back if you didn't bring a teleportation option.

**Comment by ScriptedPiky** [comment]
I love that idea actually of increasing the warp effect requirement levels. And if the item to remove the warp is in combination with the re-arranged warp you presented, may I introduce something for this?
If the player has 50 or below permanent warp, the chance to remove 1 perm warp becomes 1% with that item (not the pure tear). For every extra warp above the minimum 50 line, add 1% extra chance for removing 1 warp until the 100% cap has been reached. And depending on the recipe given, this could be an interesting gamble, as removing perm warp is extremely powerful, but spending great amounts of resources for something early compared to the pure tear is certainly interesting

**Comment by richardhendricks** [comment]
That feels too powerful to me.  So at 100 warp the item guarantees removing permanent warp?

**Comment by ScriptedPiky** [comment]
Ah that seems a lot better actually. Yeah, at 100 & above you'll have a better chance, or anything below 100 will result at a 0% to prevent cheesy gambling methods?

**Comment by Prometheus0000** [comment]
I have no idea how to code that, so I'm gonna say no. I basically just copy-pasted and changed the names for most of it. Also, 1% sounds kinda low, maybe 2%? if someone else wants to do it. I'm not sure. It depends on what the configs end up like.

Uh, that's what it does now, just 1 point at a time. Piky suggested making it chance based.

**Comment by leagris** [comment]
I'd give my 2¢ opinion now.

Straight **Rule \#1**: No Permanent Warp should be gained, unless a Thaumaturge badly screws things up, rushes researches, acts stupidly or foolishly.

Permanent warp could be cut by 1 point every 6 real-life hours offline, that's 4 points of permanent warp removed each day, 28 per week, and a total redemption of maximum 200 permanent warp would be totally cleared after 50 days offline.

**Comment by yukieiji** [comment]
What Ichor can researched is the amount of warp that can complete all of her TC research and one other MOD research. And further research can be done using Wand Focus and its additional items.
Considering this, I think that the amount of warp in the wither spawn is about 100 to 150 is appropriate.

**Comment by yukieiji** [comment]
How about this for the Warp Theory effects config.
Shows the player that the warp is dangerous by adding a little tighter effect with a lower warp amount effect.

| Warp Effect| Warp Amount |
| ------------- | ------------- |
| Fake explosion&Fake Creeper | 10  |
| Spawn bats | 15 |
| Jump boost | 18 |  
| Poison | 20 |
| Rain&Blood&Nausea | 25 |
| Wind | 30 | 
| Friendly Creeper | 35 | 
| Livestock rain | 40 |
| Blindness | 45 |   
| Lightning | 50 | 
| Random tree | 70 |
| Random teleport | 80 | 
| Acceleration&Decay | 100 | 
| Chest scramble | 110 | 
| Spawn Wither | 120 | 

we may want to add some effect between 50-70 and 80-100

**Comment by Prometheus0000** [comment]
If you say you want to add more effects then why are you still combining some of them? And why is blindness so high up, it isn't really bad at all?

**Comment by yukieiji** [comment]
I think that Blindness effectively didn't make it much more difficult to explore and craft (some mobs attack used this effect).
The reason why add warp effect is because a new warp effect is considered as shown in #4270

**Comment by Prometheus0000** [comment]
When I said high up I meant in relation to how much warp you have (high=more warp). It's much less bad than lightning for example.

But someone has to code that (new effects). Are you going to code that? I certainly can't. We have to deal with the current reality rather than put it in space for effects that may never get coded. They can always be added in later.

What do other people think about when the Wither should spawn? I'm not particularly attached to 200. I just wanted to use the whole range so that they could be scaled.

**Comment by mitchej123** [comment]
Depends on what the effect is... There's a few people who might be willing to code it.

**Comment by ScriptedPiky** [comment]
I had an idea long ago that could replace the Wither effect with super powerful warriors instead. Enemies such as zombies or skeletons equipped with Void or Shadow fortress armor, along with enchanted gear & weaponry, they are, however, given 4 seconds of immunity and are unable to attack (or simply have the weakness & resistance and or absorption buff/debuff set to a very high amount). They either do not drop their armor or have a very low probable chance of dropping it. They could exist in the same similar fashion as the Eldritch Guardian spawns as well.

**Comment by Prometheus0000** [comment]
If you wanted to replace the Wither you could also use the bosses of the Eldritch dimension.

**Comment by 0lafe** [comment]
I always found the wither wasn't really a fighting problem as much as the destruction it would do ro the base. Much like pollution, the negative personal effects aren't that bad. Blindness, lightning, bats, poison, etc, don't do much to actually hurt you. It's only when you get things like lightning hitting rockets, ponds in your ebf, or withers blowing up your base, you start actually being negatively impacted. If there isn't much world based negativity to warp, there's more ability to pass the max warp and not even really need a tear. 

Id keep withers as they do provide a reason to REALLY not want to hit max warp, as opposed to simply being an annoyance.

**Comment by mitchej123** [comment]
Move withers up, but them or something similar should be kept in place near max warp.

**Comment by Anarack** [comment]
Well... minus the wither affect does nothing on any server with a protection system. So you are punished for not disabling it essentially outside of the officials.

**Comment by Prometheus0000** [comment]
I figured out how to use PSP to adjust the color of the new item. Anyone want to suggest a color? It only really affects the red in the middle.

**Comment by Prometheus0000** [comment]
I did some research on how much warp is needed to get the pure tear. Using commands gives the prerequisite researches too.

Using the command to unlock ICHOR_CLOTH gives 34+19=53 warp, but doesn't research everything in the TT or Vanilla tabs or unlock eldritch.
Using the command to unlock ICHORIUM gives 78+59=137 warp, and researches almost everything (including non-vanilla researches on vanilla tabs) in the TT and Vanilla tabs, and only the first eldritch research.
Using the command to unlock PURETEAR gives same as above, plus the second eldritch research.

So getting Ichorium to unlock requires minimum 137 warp it seems. Of course, this excludes various useful researches, and stuff on the GTNH, BM, or Witchery tabs. 

It seems Ichorium has weird requirements compared to unlocking compared to just the Ichor Cloth, which should be the requirement to unlock the research. Of course, this was a test instance, there might have been something I was supposed to scan, but I checked the code (and script) and couldn't find anything. And I thought you needed all the Vanilla-eldritch+TT research to unlock Ichor to begin with, but it seems that's not the case.

**Comment by richardhendricks** [comment]
Someone else pointed out that a player not knowing better is going to be stuck with more warp than a seasoned veteran who knows what they're doing. We can fix that by improving the quests, or by adding an information-only quest that has instructions on where to concentrate efforts if you want X/Y/Z.

**Comment by richardhendricks** [comment]
Also, AFAIK, nothing in Witchery gives warp.  Should it?  Are there separate penalties in Witchery for equivalent levels of abilities?

**Comment by Prometheus0000** [comment]
I have it open and there's 10 warpy researches there.

**Comment by yukieiji** [comment]
@richardhendricks What about moving WarpWarinig's research to the Vanilla TC Basic Information tab, as some players don't progress through the quests and don't know the effect of warp? (Those who do so think that they rarely see GTNH tabs)

**Comment by richardhendricks** [comment]
I think it's a good idea. File a separate ticket.

**Comment by yukieiji** [comment]
@richardhendricks Opened pull request #5659

**Comment by Prometheus0000** [comment]
Could someone tell me if I did this right? It seems to work ingame properly.

added import java.util.Random; at the top. Tutorials said import java.util.*, but I imagine that would call/import a bunch of unnecessary stuff?

	//add function to remove 1 warp
    public static void purgeWarpMinor(EntityPlayer player)
    {
        removeWarp(player, 1);
    }
Above changed to below
	//add function to remove 1 warp, chance based
	//warp < 50 = 0%, warp >= 150 = 100%
    public static void purgeWarpMinor(EntityPlayer player)
    {
		Random ran = new Random(); 
		int rn = ran.nextInt(101);
		rn = rn-50+getTotalWarp(player);
		if (rn >=100)
			removeWarp(player, 1);
		else
			return;
    }

**Comment by Prometheus0000** [comment]
I have finished making changes to the new item. It's now chance based, see above. I've also come up with a recipe for it:
![2020-02-29_20 58 17](https://user-images.githubusercontent.com/8517039/75618079-b1594280-5b36-11ea-81ec-0f5a96768be3.png)

The middle is hardened ice, the rest is quicksilver blocks, magicales, odor of purity, BM blood/life essence in a cell, aurelia petals, and max tomato. I tried to use some aspects that I didn't see too often, as well as auram and praecantatio. There's no sano since it's in the tomatos, and you probably used a ton to make soap anyway.

You can try it for yourselves: 
[Warp Theory with new item.zip](https://github.com/GTNewHorizons/NewHorizons/files/4271229/Warp.Theory.with.new.item.zip)

Do people agree with this? It uses parts from multiple mods to make it harder. I wasn't sure if making it require slates might be better than cells for example. Magicales might be too hard with the LP cost and the growth medium. Max tomatos is from the IC2 crop, I'm not sure what the drop rate is or how many people get the crop either. I can change the randomization range, but having it changed from a config would be too much for me. For the effects config discussion do we need to take a vote on when the wither should show up?

**Comment by Prometheus0000** [comment]
I have created a poll about when the wither should spawn, which order the warp events should be in, and whether people want more warp events:
https://www.surveymonkey.com/r/HMZKKX6

**Comment by Prometheus0000** [comment]
So as a result of the survey (only 12 responses, but I want to move forwards): https://www.surveymonkey.com/results/SM-GPFTT7HT7/
I'm submitting a PR based on it with the following:

Warp Effect | Warp Amount
-- | --
Fake explosion | 10
Spawn bats | 15
Fake Creeper | 20
Blindness | 25
Poison | 30
Rain | 35
Blood | 40
Jump boost  | 45
Nausea | 50
Friendly Creeper  | 60
Livestock rain | 75
Wind | 90
Lightning | 105
Random teleport | 120
Acceleration | 130
Decay | 140
Random tree  | 150
Chest scramble | 160
Spawn Wither | 170

It seems people want more warp effects, but that's probably better suited to another ticket. If anyone cares enough, you can open another issue to talk about that.

**Comment by richardhendricks** [comment]
How are the events weighted? Another way to make it less annoyingly dangerous would be to weight events based on (current warp - place in the chart). IE if your warp is 29:


Warp Effect | Warp Amount | Weight | Chances
--------------|--------------|------------|-------
Fake explosion | 10 | 19 | 41%
Spawn bats | 15 |  14 | 30%
Fake Creeper | 20 |  9 | 20%
Blindness | 25 |  4 | 9%

Total weight = 46

This would make the higher warp effects low chances until you get beyond them. Not 0, but low that gradually increases.

**Comment by Prometheus0000** [comment]
I think it makes ones your currently near more often? I'm not sure, I never thought about that, and that's beyond a config change too. But I didn't get the earlier ones as much when I had a decent amount of warp. You could try looking in the code yourself I guess.

**Comment by redmage17** [comment]
We should add more things to just screw with the player as warp is intended to be a mental corruption and symbolizes a descent into madness. Phantom mobs, noises etc are good(Things that are not there and mess with a players overall mental state).  

Also since we are tweaking things is this a good place to mention the tallow recipe? It is required for purifying soap, and it feels forced and arbitrary just using soap stone. For one soapstone is not used for tallow. FAT is.

 If we want to make adjustments for soap recipe specifically that may brew another discussion. But Tallow should used fat from things such meat and rotting flesh.

**Comment by McFrugal** [comment]
I wound up disabling the fake explosion and fake creeper effects in single player because I quickly got used to them and they became nothing more than a distraction.

My suggestion is to remove ALL of the Warp Theory effects.  Most of them have unintended consequences (wither griefing other players, lightning breaking rockets, swamp breaking multiblocks, chest scramble griefing other players, livestock rain trampling crops, etc etc etc.) and the ones that aren't glitchy or broken are either annoying, annoying and pointless, or immediately lethal in specific situations.

The vanilla warp effects are enough, I feel.  They even scale with how much warp you have!

**Comment by Prometheus0000** [comment]
> My suggestion is to remove ALL of the Warp Theory effects.

Dream will say no.

In addition, the vanilla warp effects are completely pathetic and totally ignorable. Especially since they stop happening after a while.

**Comment by Dream-Master** [comment]
NO as Prometheus said :P

**Comment by mitchej123** [comment]
We should adjust the warp levels and effects (and maybe add some alternative ones), but disabling them is silly.

**Comment by McFrugal** [comment]
Ok, let's look at the vanilla warp effects.
Unnatural Hunger: you will starve to death at higher amounts of warp, unless you eat rotten flesh immediately.  This is the main afk-killer.  I imagine the healing axe works to endure the hunger drain, but then you're stuck holding it for the entire length of the effect.
Blurred Vision: can't see shit
Blindness: same
Flux Flu: harmless unless you wanted to make something with vis.
Thaumarhia: leaves pools of flux goo lying about which you have to clean up, which is easy so it's pretty much harmless.  Unless you're afk, in which case it might spawn fibrous taint under you, which would kill you and taint your biome.
Flux Phage: contagious flux flu, doesn't transmit forever though.  Still mostly harmless.
Sun Scorched: fucks up your vision and makes you catch on fire in sunlight.  Ignorable if you have a pigman backpack.
Eldritch Guardians: not too tough, but if you go afk they might kill you.  Do magnum torches prevent them?
Deadly Gaze: not a problem for you, but could kill livestock, golems or villagers.
Mining Fatigue: is a real problem if you're mining or fighting when it happens.
Night Vision: actually positive?
Warp Reduction: I didn't know this existed until today.  Probably extremely rare, but reduces (sticky?  temporary?) warp.
None of these effects screw you over in any permanent way, and only Deadly Gaze could be used to grief.  The worst one is unnatural hunger IMO.
Why does warp theory also have a blindness effect?

All warp effects go away if you don't do anything that increases warp for a long period of time.  Even Warp Theory effects go away, don't they?  If they don't, that seems like a bug.  The reason they go away at all is to allow people to eventually go afk with moderate to high amounts of warp and not die from unnatural hunger or guardians; Azanor added that feature after people complained about not being able to afk.  Getting a bit of temporary warp from an Eldritch Guardian will cause a resurgence, so it's not like you can pretend you have 0 warp forever.

Warp will never ever be balanced if the way it's approached in this pack is "try to screw over the player for having high warp".  That just means players will either avoid thaumcraft as much as possible so that warp is never a problem, or completely eliminate it by using pure tears or whatever after unlocking all the research that requires warp, which means it's only briefly a problem.
Actually balanced warp would be possible to live with at the amounts you'd be expected to have for Ichor research.  Right now it's not, because Warp Theory is garbage and throws withers at you alongside ruining your base in other ways.

An alternative to messing with Warp Theory's settings is to reduce the amount of researches that give warp.  Thaumcraft's warp system is balanced around the amounts of warp you get from the base thaumonomicon, so with every addon present it gets further and further out of whack.  GTNH has all of the addons, so it's as bad as it can possibly get.  The default Warp Theory settings are presumably balanced for the base level of warp as well.

**Comment by Prometheus0000** [comment]
> Even Warp Theory effects go away, don't they? If they don't, that seems like a bug.

They do not. Because otherwise you'd just get all the warp, afk in a hole or something, and then never deal with it again.

> An alternative to messing with Warp Theory's settings is to reduce the amount of researches that give warp.

Did you not see the link up at the top?

**Comment by johnch18** [comment]
I'm not super familiar with thaumcraft, so bear with me here. What if all forms of warp, including "permanent", dissipated with time sort of like how pollution does?

**Comment by Prometheus0000** [comment]
Then you go back to afking in a hole.

**Comment by Rakdarian** [comment]
As someone who really likes to have permanent night vision on, blindness is fucking annoying. like getting caught out in the middle of the night

**Comment by Rakdarian** [comment]
But more to the point, even with the more frustrating warp effects like swamp or decay, both of those can be ignored or mitigated with base construction and the like. Being able to pursue more powerful things before you really ought to is a real fun and fluffy way to play the pack. So far my only complaint has been with the one ring implementation where eventually youll get the warp effect of your player.data folder corrupting. 

I spend quite a lot of time at high warp levels, for the most part it just changes how i build my bases.

**Comment by McFrugal** [comment]
> 
> 
> > Even Warp Theory effects go away, don't they? If they don't, that seems like a bug.
> 
> They do not. Because otherwise you'd just get all the warp, afk in a hole or something, and then never deal with it again.

Like I said, that doesn't work in the long run, because literally any warp-related activity will trigger a resurgence.  The warp effects come back, and you'd have to wait several hours again to get them to go away.
> 
> > An alternative to messing with Warp Theory's settings is to reduce the amount of researches that give warp.
> 
> Did you not see the link up at the top?

I did, but figured it was discussion related specifically to Blood Magic, since that's how you described it.  If research-warp is already being reduced that's good; when will that happen?

I thought of another option though!  Remove Warp Theory entirely.  No way to reduce permanent warp, but the warp effects aren't as debilitating.

**Comment by Prometheus0000** [comment]
> Like I said, that doesn't work in the long run, because literally any warp-related activity will trigger a resurgence. The warp effects come back, and you'd have to wait several hours again to get them to go away.

That's why you do all the warp stuff at once. and make all the stuff that needs it. Until IV when you can make the tears.

> I did, but figured it was discussion related specifically to Blood Magic, since that's how you described it. If research-warp is already being reduced that's good; when will that happen?

What? Read it. Dream said no.

> I thought of another option though! Remove Warp Theory entirely. No way to reduce permanent warp, but the warp effects aren't as debilitating.

Serious suggestions only.

**Comment by McFrugal** [comment]
> 
> 
> > Like I said, that doesn't work in the long run, because literally any warp-related activity will trigger a resurgence. The warp effects come back, and you'd have to wait several hours again to get them to go away.
> 
> That's why you do all the warp stuff at once. and make all the stuff that needs it. Until IV when you can make the tears.

Right, and then you have to: A, never make anything that gives you warp when crafted and B, never fight an ethereal guardian.
> > I did, but figured it was discussion related specifically to Blood Magic, since that's how you described it. If research-warp is already being reduced that's good; when will that happen?
> 
> What? Read it. Dream said no.

You wanted me to read an apparently-unrelated discussion to get a single post from Dream about not reducing warp at all?
> > I thought of another option though! Remove Warp Theory entirely. No way to reduce permanent warp, but the warp effects aren't as debilitating.
> 
> Serious suggestions only.

It was serious.  Warp Theory is a bandaid for excessive addon use that comes with a big injection of "screw the player".  In the end it's only purpose in the pack is to solve problems it itself produces.

**Comment by Prometheus0000** [comment]
> It was serious. Warp Theory is a bandaid for excessive addon use that comes with a big injection of "screw the player". In the end it's only purpose in the pack is to solve problems it itself produces.

Dream would not agree to it, thus it is pointless to suggest. Plus I'd rather have WT in so I can clear the warp completely eventually.

**Comment by Rakdarian** [comment]
what gives you warp when you make it, i know theres stuff that warps you when you hold it/wear it or eat. but i dont think of anything

**Comment by McFrugal** [comment]
Unless it was changed, making Ichor gives you warp.  Voidmetal gives warp when you craft items from it.  So does making flesh golems.  I'm sure there are a lot more things like that.

**Comment by Rakdarian** [comment]
huh, must not have noticed, i usually make tons of things out of voidmetal too

**Comment by bedrill64** [comment]
Normal and temporary warp that you gain during certain activities should be totally neglected in the discussion, due to the fact how trivial it is to get rid of of using calming flux scrubber focus.

**Comment by yukieiji** [comment]
>Warp will never ever be balanced if the way it's approached in this pack is "try to screw over the player for having high warp".

I don't think trying to screw over, because I've been warned by both Quest and Research that Warp is dangerous.
I think it's just self-imposed.

**Comment by Prometheus0000** [comment]
You're supposed to be smart enough to not 'research all the things'. And you have impure tears if you do. There's definitely too much warp in BM, at least for the sigils, but most of it is just kinda spread around, but there's so many researches. And I have no idea why dream added it to the witchery researches.

**Comment by repo-alt** [comment]
The problem with impure tears is that you have to gain _a lot_ of warp to make them. Especially in BM, but also for other ingredients.

**Comment by McFrugal** [comment]
> Plus I'd rather have WT in so I can clear the warp completely eventually.

If WT wasn't in the pack, only vanilla warp effects would be present.  You said those were nothing to worry about, so why would you need to clear the warp?

**Comment by bedrill64** [comment]
You can get impure tears in less than 80 warp, no risk of withers, and you can reduce your warp below 50 with them, to be fair if you are not going all in, all you need is an altar which is not that much of a problem warpwise.

**Comment by McFrugal** [comment]
Why is the bot lying about this being fixedindev for "quite a while"?  It literally just added the label.
I am quite interested in exactly how this is fixed at all, since last I heard it was stonewalled.

**Comment by DrParadox7** [comment]
While I do see an improvement with the changes brought forward, I don't believe these have been optimal.

Thaumcraft 4 and its addons do a great job on providing immersive options for making warp manageable and with the Warp Theory changes these inherent gameplay challenges have become a mere progression checkbox to the Pure Tear, making any interesting warp management implementation obsolete.

My belief is that features should complement each other rather than override them completely.

Naturally I do agree that these wheezing levels of warp are far excessive but ultimately the issue falls largely in the near immutable levels of **Permanent Warp**.

Rather than have Warp Theory cleansing method outright stomp all other methods it instead compliments it by converting permanent warp into sticky warp.

My proposed changes would be:

- **Impure Tear:**
Converts 1 Permanent Warp into 1 Normal Warp for every 25 permanent warp over 50 but also generating an equivalent amount of temporary warp.

/r Now, if only there were easy ways to remove temporary warp...

__Theme:__
_Effectively taking poison as medicine increasing temporary warp for more compatibility to depravity and madness.
If we consider Permanent Warp as PTSD then let us consider the impure tear as embracing insanity. Sigmund Freud proposed that madness develops often as a self preservation mechanism for when reality becomes too much to bear with insanity taking its place reducing frequency of such episodes._

-**Pure Tear:**
Convert up to 200 permanent Warp into Normal Warp. Every point of Normal & Temporary creates dissonance, lessening its potency.

If the dissonance is too high the process will fail and a backlash of 5 permanent warp and 5 normal warp is given to the player and warp events ensue proportional to the difference.

__Theme:__
_The " just take this one ailment to cure ALL madness"  is but a delusion. Warp is but a consequence of your own actions of not respecting that of which should be left alone. Redemption ought to be earned by first doing everything that is in your power to deal with the repercussions before seeking more permanent solutions._

-**Mirror:**
Rapidly ejects the __normal__ warp of its users into the environment causing warp events in the process.
Synergizes well with a both tears to get rid of large amounts of warp fast.

Should be gated extremely lategame.

**Comment by McFrugal** [comment]
The Pure Tear outright failing if your Normal Warp is too high seems like a nasty failure state.  If you had too much Normal warp at that point, before the mirror, what would you use to remove it?

**Comment by yukieiji** [comment]
I think this Impure Tear change is OP considering that temporary and normal warp can be easily removed with Wand Focus:Flux Scrubber

**Comment by DrParadox7** [comment]
> The Pure Tear outright failing if your Normal Warp is too high seems like a nasty failure state. If you had too much Normal warp at that point, before the mirror, what would you use to remove it?

Wash off as much sticky warp as possible, clear all temporary warp and dump what you can in a Soul Brazier or similar before attempting.

**Comment by DrParadox7** [comment]
Ok, I've changed things a bit based on feedback received:

- Amulet:
Constantly removes Sticky Warp creating warp events in the process.
If under Warp Ward, the benefit continues without the warp events.

- Impure Tear:
Converts Permanent Warp into Normal Warp exponentially to total permanent warp (Permanent Warp/100)^3) producing an equivalent amount of Temporary Warp.

- Pure Tear:
Purges all non-permanent warp AND:

IF **Total Warp** > 70:
Clear Permanent warp exponentially to total warp (75/Total Warp)^4*50) and backlashing with warp events equivalent to its benefit (Total Warp^2/500, Capped at 250 Warp).
*This backlash is reduced by half if under Warp Ward.*

IF **Total Warp** < 70:
Purge all warp with no downsides.

Additionally recipe takes 3 primordial pearls, returned unpowered on crafting.

**Impure Tear vs Pure Tear:**
![image](https://user-images.githubusercontent.com/47131096/159171818-aeef7772-5365-451c-b3ac-fd772724a0dc.png)

These changes make sub-200 warp attainable (dare I say a necessity with withers) without having to purge all warp. 

Purging is still possible but requires more effort and progression from the player, aimed at rewarding those who managed warp well instead of benefitting all indiscriminately.

**Comment by McFrugal** [comment]
Looks pretty cool to me.  Cleaning your warp becomes a process using many different items if you've got high warp (amulet, soap, bath salts, impure tears) and eventually a painful one when you swap to Pure Tears.

**Comment by Cata-bre** [comment]
While I'm happy with the new warp theory numbers, it really was just kicking the can down the road. You can research a bit more, but it doesn't address the core problem that pure tears are the best (and least interesting) way to remove warp. Your warp management suggestion looks great.
