### ISSUE TITLE
Make zpm suck less RFC

### ISSUE THREAD

**Issue by 0lafe** [GTNewHorizons/GT-New-Horizons-Modpack#5736]
#### Which modpack version are you using?
2.0.8.new
#
#### What do you suggest instead/what changes do you propose?

Rn, zpm is probably the first big drop in interesting GT content. The materials used are fairly straightforward, and the complexity of progression is almost negative if anything. 

EV has nukes and new fuels, and a few materials that are harder to make than HV. You start using multis more heavily, and get AE. Epoxy also starts being a big thing, introducing some chem. 

IV has indium, more power gen, some Pt proc, assline, and a few more materials. You get a bunch of ++ multis, and start needing better rubber chains. Automation becomes a little more challenging with things like the assline, and efficient chem designs. Some uu gets into the picture, but not much yet. 

LuV gets fusion, more Pt proc, Cassline, and a few other fun things. PBI adds onto chem, and fusion gives some fun power/mat gen times. More assembler recipes with different fluids bringing a bit more automation fun. Uu becomes more prominent, requiring more energy. 

Zpm doesn't get much. Mostly you ebf your materials, with maybe a mixer. Pure dusts are essentially simple ore products, and chem essentially stagnates. Power production is basically just uptiering a reactor, and maybe swapping to another plasma. 

---

Ideas I have atm aren't that useful, but I got a few. We could make the basic materials more complex to produce. Give Ke something other than an ore byproduct in simple ore proc. 
>Unrefined it is extremely brittle, and unsuitable for manufacturing purposes. When refined, however, the metal is approximately 100 times lighter and stronger than steel.

If we wanna keep lore shits, we can give it some kind of refinement stage. Could integrate some fusion into it if we want to swap Ke in fusion coils with something else. 

We could use ++ cyclotron. Iirc it's like IV/LuV, so it could make some useful isotopes or something for us. Id suggest not enabling uu for these, or making it significantly worse than this method to keep the large setup the staple of zpm. 

Kevlar was suggested as a chem product a while ago, we could probably implement that for some zpm parts. Seems to have some electrical applications. 

Fusion could also be used at least a bit more than currently. Mostly being power gen/1 tier mat, we could give it more chains to make more zpm materials. 

Wetwares could probably use with more BW vat integration, but I haven't used the vat enough to know how to implement that.

**Comment by ivelieu** [comment]
Really, I would be interested in more TecTech integration, as those are one of the unlocks post ZPM but its utility is very limited. I feel that the lategame potential of TecTech exceeds both GT++ BW, especially as suggested by some of the vast unimplemented multiblocks like the black hole generator. 

GT++ is the most difficult to tailor to GTNH lategame, since it's used in other modpacks and getting special features coupled to GTNH exclusive content is difficult. I think it is better for the pack if main progression does not directly force the usage of GT++/BW machines. 

One of the features in TecTech that I think would be interesting to use as a late game mechanic in GTNH is variable-size multiblocks. For EBFs, we have the classic, volcanus and mega -- imagine if you could get varying efficiency and speed bonuses based on the EBF size -- maybe it is even possible to use multiblock validation in a way that circumvents chunk boundary restrictions to go past the current mega size. 

I think a big theme of GTNH that I want expanded on further is _really big machines_ - and I think that BW is taking the idea in a good direction, but it could be more well developed to the point of being a core mechanic similar to overclocking.

Kevlar sounds good as a late game chemical addition. I think it would be interesting to add some unique challenges in its production - compared to the current state of bio circuits where it's just number crunching on infinity and infinity catalyst. I wonder what the ZPM equivalent of "low gravity" could be...

**Comment by bartimaeusnek** [comment]
@ivelieu BartWorks is litterally build for GTNH lol.
