### ISSUE TITLE
OpenComputers & Thermos issues with Debug Card & Commands...

### ISSUE THREAD

**Issue by KaneHart** [GTNewHorizons/GT-New-Horizons-Modpack#5777]
Not sure if anyone willing to check this out. It's a known bug not even sure if we have a OC build or not out there.

So I have simple program that spreads players and then sets their spawn point using spreadplayers then spawnpoint.

The Program:
https://gist.github.com/KaneHart/074d219e18cfb0e512f200f2b00c39ee

Either way the best way to test it is a debug card and using lua command and using the following commands:
![image](https://user-images.githubusercontent.com/425853/77147836-9b1f1200-6a64-11ea-9126-7c75728146c5.png)

If you use Forge both work but if you use Thermos only the spreadplayers work it's strange 99% of commands don't work some do but yeah most don't and it makes no sense since spreadplayer and spawnpoint are both vanilla commands too...

Of course I did open computer fake player UUID, etc etc... 

Also it's a known bug reported here before:
https://github.com/MightyPirates/OpenComputers/issues/763

Why all this?
I just want a simple system where players go to a certain area and it teleports the player in a random location and sets their spawnpoint so they die they spawn there again... I know it's stupid but yeahhhhhhhh

**Comment by boubou19** [comment]
admin dislocator for RTP + command block edit via debug card (you get the pos via a player object) then trigger the command block.

**Comment by KaneHart** [comment]
Yeah I can't get the debug card to work at all with command block with it enabled via the OC Configs... Not sure if it's another bug with OC or I'm doing something wrong I tried for hours.

**Comment by Dream-Master** [comment]
@GTNewHorizons/core @GTNewHorizons/developers

**Comment by mitchej123** [comment]
![homer_disappear](https://user-images.githubusercontent.com/1894689/77258893-d6733980-6c3a-11ea-9349-f96c17be90e5.gif)

**Comment by juanmuscaria** [comment]
That's something that can't be fixed, oc uses forge way to run commands which by this command you can already understand why no command will work "Cauldron - do not register vanilla commands replaced by Bukkit", if the command has a bukkit equivalent it will not work because it's handled by the bukkit command map, command blocks have a fix, it uses bukkit command map. looking through it there's no way to make it go through the command map.
Since there's no easy fix because of bukkit the only method I can see to call command and make it go through bukkit's command map is adding the command to the server's pendingCommandList which is available only on server side only or make fake players have a modified "NetHandlerPlayServer" and call handleSlashCommand.

**Comment by boubou19** [comment]
@KaneHart try to sneak and right click with the debug card while being in creative. It should bind you to the card, then put it in the computer again. I got it to work that way.
