### ISSUE TITLE
Remove Deep Dark Dim, Recipe and Quest because of Bart Works Void Mine

### ISSUE THREAD

**Issue by Dream-Master** [GTNewHorizons/GT-New-Horizons-Modpack#5797]
Remove Deep Dark Dim, Recipe and Quest because of Bart Works Void Mine.

When Voidminer works well we remove this dim.

**Comment by Alexdoru** [comment]
This will be a big nerf, because mining with a regular drilling plant in the deep dark is completely different than crafting and powering a void miner :p

**Comment by chochem** [comment]
this definitely shouldn't happen soon (like 2.0.8.9??). the void miner is still WIP according to bart.

**Comment by GTNH-Colen** [comment]
The void miner from what I can tell reads the dimension it's in and produces ores based on that. How exactly will this work if we remove the DD? Since there will be no dimension in which there are basically all ores?

**Comment by GTNH-Colen** [comment]
> This will be a big nerf, because mining with a regular drilling plant in the deep dark is completely different than crafting and powering a void miner :p

1A UV isn't a lot for all ores at this tier in fairness, if we remove the DD then you will just have to craft this up instead which from the looks of the recipe seems to be fair.

**Comment by 0lafe** [comment]
I'm super on board with needing a few of these around different planets, but we might want to put some of the DD unique ores on T7-8 places in that case. It seems like the only thing the DD does that's unique for the void miner is the ore list it has, which can be distributed around. Many T7-8s are kind of boring and don't have a ton of unique ores, this could be an opportunity to add more to some of those places. 

D*, If catalyst ore, and bedrockium are really all that come to mind

**Comment by GTNH-Colen** [comment]
I'd rather this would be able to go in peoples bases, even if we needed multiple. Chunkloading multiple planets worth of miners/pumps becomes an absolute pain on servers since you need to revisit each loader after a restart which is every 12h (Not including crashes >.>).

**Comment by Dream-Master** [comment]
Yea not changed now maybe in 1 or 2 updates when all is balanced . Don't worry

**Comment by Houstonruss** [comment]
I feel like the void miner will cause more problems than it solves. More chunkloading, and really no way to prioritize ores besides dims.

**Comment by GTNH-Colen** [comment]
> I feel like the void miner will cause more problems than it solves. More chunkloading, and really no way to prioritize ores besides dims.

It's virtually impossible to prioritise ores in the DD anyways just because of the insane density, however for other planets you're still able to do this as normal. Ideally if we can get this to go in peoples bases then we will have even less chunks loaded, from what i've heard GC planets are horrific for TPS as every air block seems to be a tile entity for some bizarre reason.

**Comment by richardhendricks** [comment]
The air blocks are tile entities to enforce oxygen equipment, AFAIK. I think though using chunkloaders is much better load-wise than a player, since the area is much smaller, and doesn't change with time - a player moving around is loading/unloading lots of airblock tile entities. So chunkloading 1 or even 3x3  chunks is a lot less than a full player exploring a planet.

DD (or anywhere really) could be somewhat prioritized by only loading specific chunks with the prior implementation of the miner.  (Using anchor sentinels one can load 1 chunk) @repo-alt I recall you did add a control option to disable auto-chunkloading?

**Comment by bartimaeusnek** [comment]
Main point here is to reduce stress on the servers from actual mining, chunk loading in DD, lightchecks in DD, code cleanup due to reducing the needed ammount of veins which spam both config and code with DD only veins, reduce confusion for newer players via removal of ultra late game veins from NEI and making late game a bit more challenging than just mine in that one dimension

**Comment by richardhendricks** [comment]
Will the void miner work cross-dimension? I could see a method that uses a block from the dim to allow the miner to target that dim.  IE, Europa ice block allowing Europan ores.  It would probably need something to prevent players from sharing blocks, maybe.

**Comment by bartimaeusnek** [comment]
@richardhendricks no.

**Comment by Prometheus0000** [comment]
So, since the VM needs to be in a dim to grab ores from it, I assume this isn't happening anymore? If so, I'll change the quest and/or add a followup one about the VM.

**Comment by Dream-Master** [comment]
modifying the wuest for DD and add a vm quest if you like
