### ISSUE TITLE
Seismic Prospector doesnt see BW ores correctly

### ISSUE THREAD

**Issue by Impos913** [GTNewHorizons/GT-New-Horizons-Modpack#5814]
#### Which modpack version are you using?
2.0.8.8

Seismic prospector results say there is Cinnabar Bornite Roquesite Wittichenite vein, but there is a Cinnabar Terlinguaite Temagamite Atheneite vein.
(Dimension moon)

**Comment by Dream-Master** [comment]
@bartimaeusnek need help here

**Comment by Cleista** [comment]
Issue still occurs in 2.0.9.0QF4. May be related to #5588 and #5133 

#### Which modpack version are you using?
2.0.9.0QF4 update

#
#### If in multiplayer; On which server does this happen? 
Private Server 

#
#### What did you try to do, and what did you expect to happen?
Used EV Seismic Prospector and scanned/printed the results, expecting ores to match what the book says. 

**Seed:** 63350368
**World:** Ross128b
**Scan results:** [Page 1](https://cdn.discordapp.com/attachments/648321618615205893/727980424969846794/unknown.png), [Page 2](https://cdn.discordapp.com/attachments/648321618615205893/727980526207762552/unknown.png)

#
#### What happened instead? (Attach screenshots if needed)
Ore positions were offset by 1 ore chunk north and west. 

Arsenopyrite was not found at -3368 -2216, cleared a 7x7 hole in the middle of the chunk to verify. 

Scanned with prospector scanner, found Arsenopyrite was [at medium range](https://cdn.discordapp.com/attachments/181078474394566657/727973028620664844/unknown.png) instead. Turns out it was located at **-3416 -2264** instead (one ore chunk north and west of the prospector report). 

#
#### What do you suggest instead/what changes do you propose?
Fix Seismic Prospector report to show correct ore locations.

**Comment by shawnbyday** [comment]
Also confirm on 2.0.9.0QF4 reports Roquesite where there is none (Ross128b) Not sure if related to the off by one thing since I put a T2 ore drill down right on top of the place where it said there was roquesite and I didn't get a single piece of it so none of the veins around it have it either.

**Comment by repo-alt** [comment]
perhaps in this version ore drill did not support BW ores?

**Comment by repo-alt** [comment]
did you actually checked if the ores are there?

**Comment by hainguyen1107** [comment]
Confirmed on 2.0.9.0 QF4 that what happened to shawnbyday happened to me!
I placed ore drilling plant exactly on the site noted in the book -> no roquesite!
I mine manually several other locations noted in the book -> no roquesite too
I cheated an electric prospector -> no roquesite ores found!!!!!!!!!!!!!!

**Comment by boubou19** [comment]
can you replicate on a fresh world? I did wipe ross128b and ross128ba on the officials, and on delta ross128ba had no ores listed on the electric prospector scanner UV. Bart told me to reset again the dim, and it worked.

**Comment by hainguyen1107** [comment]
Wew... I used electric prospector to locate some roquesite veins and... it worked well

**Comment by shawnbyday** [comment]
@repo-alt yes I scanned originally with EV Seismic Prospector and then put down T2 Ore Drilling Plant on where the Roquesite was listed in the book. Let the drilling plant drill for a few days until it was finished. Checked to see if I had any roquesite and didn't. Checked to make sure AE2 wasn't voiding it either. Then decided to dig down to see if maybe ore drill wasn't mining it and nothing was there/was all mined out.

I had 2 other locations listed in the scan book so I went to check those manually (no drilling plant on these) and neither of those had roquesite either.

Ore Drilling Plant is picking up all of the bartworks ores for me just fine so no issue there.

@boubou19 technically speaking this world is "fresh". I created it on 2.0.9.0QF4. So it's not a world that was started in an older version or anything.

Also as suggested by @hainguyen1107 I grabbed a Prospector's Scanner (UV) and scanned and there was no Roquesite in the general area where the book said it was. I found an area where the Prospector's Scanner (UV) said there was some Roquesite so I checked and it was there.

Seems to be just with the Seismic Prospector which seems odd to me but I guess anything is possible. I can check on other things too if you want more information.

**Comment by repo-alt** [comment]
Weird, it should work for BW ores at least on the latest version. It won't work for the GT++ ores though, so perhaps I'll fix it

**Comment by repo-alt** [comment]
Ok, BW ores may be filtered if they have metadata > 16000. I added support for generic "ores", but they may include some stray ores that do not have GT association.

**Comment by repo-alt** [comment]
https://github.com/GTNewHorizons/GT5-Unofficial/pull/361
