### ISSUE TITLE
RFC Multiblocks and recipe special requirements 

### ISSUE THREAD

**Issue by 0lafe** [GTNewHorizons/GT-New-Horizons-Modpack#5835]
#### Which modpack version are you using?
2.0.8.8

#### What do you suggest instead/what changes do you propose?

With the ability to force GT multis to be within a cleanroom/lowgrav, apparently we need support to do this or something. 

This change would force PAs/LCRs to be within a cleanroom for cleanroom recipes. It would also force PAs in lowgrav for those recipes. I don't think Circuit asslines would go in the cleanroom, but that can be talked about here as well. ++ Multis for now would stay outside of the cleanroom, and also still wouldn't need lowgrav. 

I'm very much on the side of these multis going in the cleanroom. It seems like that's the point of the cleanroom. You aren't really pushed to make a very big cleanroom, or use it past IV or so currently, which is kind of sad. A single larger sized cleanroom can hold multis for tiers up to UV at least, with much room to spare. Imo the segregation of certain multis into a larger multi is kind of a cool concept, and it's sad we just give up on it with multis. 

While lowgrav/cleanroom recipes are different, I proposed both here. If you like one but not the other, feel free to only support one side of it. These don't need to both happen for one to happen.

**Comment by leagris** [comment]
The AssLine is a clean-room on its own because it its operations are in a contained environment.

Low gravity, why not, but why all this nerf? What problem does nerfing even more does it solve?

**Comment by 0lafe** [comment]
It just extends the lifespan of the cleanroom past IV, and keeps it as a circuit production multi indefinitely as opposed to being phased out rather early.

**Comment by quedral** [comment]
No its just senselss attempt of nerf cuz just you wanted. any lower tier tech is bound to be obsolete in somepoint and circuit room is no exception.

**Comment by Anarack** [comment]
- PA/LCR already checks low gravity I think, or at least the PA does.
- Clean room can't fit a max sized assline, so thats already a hard no. though if this becomes a thing somehow I would want #5825 done first. 
- hiding a fancy looking multi/setup in a white box is dumb sounding, cubes are boring.
- circuit assline is already dedicated to making circuits, making a multi require the multi it replaces is stupid.

**Comment by GTNH-Colen** [comment]
Great another attempt from you to push a nerf, finally actually got this into a RFC thread before you lot attempted to stealth nerf it in a PR. Only because Bart forced your hand though by locking the thread. 

This is a really silly nerf and the only reason you're actually pushing this at all is because you want to kick GT++ out of the pack, that is always the agenda with you. You're insanely active in this community, why can't you be constructive for once?

Quote from you:
<img width="664" alt="Screenshot 2020-03-28 at 16 37 19" src="https://user-images.githubusercontent.com/54497873/77828309-8866a600-7112-11ea-9db7-6c3622849b0d.png">

**Comment by mitchej123** [comment]
> * hiding a fancy looking multi/setup in a white box is dumb sounding, cubes are boring.

This

**Comment by Folanlron** [comment]
No, I don't feel like seeing massive white boxes all over builds.

**Comment by richardhendricks** [comment]
FYI, cleanrooms have supported reinforced windows for months. So you could have a bunch of white boxes with windows to look inside!

**Comment by General-Ike** [comment]
My 2 cents:

Low grav recipes should not be bypassable IMO. It's a super neat concept, that requires integration with the cool space station mechanic.

Cleanroom as it is now is great, because it is always required, but can eventually be phased out, and it's not really pretty anyways. I would personally like it if the circuit assembler recipes couldn't be bypassed, so that you cant phase out your cleanroom without CALs.

If GT++ machines can't be included, no changes should be implemented. As awesome as requiring a space statio is. We have no reason to punish someone for electing not to use GT++ machines.

**Comment by Dream-Master** [comment]
We can't put multies in cleanrooms but a cleanroom chipset or a low gravity chipset which emulate it would be nice.
