### ISSUE TITLE
[RFC] Ross-128b Tier Change | Machine Huts Change

### ISSUE THREAD

**Issue by 0lafe** [GTNewHorizons/GT-New-Horizons-Modpack#5878]
#### Which modpack version are you using?
2.0.8.8
#

#### What do you suggest instead/what changes do you propose?

At the moment Rossb is a T3 planet that gives lots of free machines very useful in IV. I propose 2 possible changes to the planet. 

The ideal solution in my opinion is to lower the stuff you find to EV and below items. This seems like the best solution, but Bart seems to not want to do this, and personally I have no idea how to. 

Alternatively we can raise the planet tier to T4. Doesn't mess up the planet too much, lots of the ores are still useful in LuV, and it better places the free IV stuff. Main reason for this option is that it's much easier, as planet tier is just in the config

**Comment by quedral** [comment]
Suggesting this kind of nerf after reaping benefits for months if not years is by the book definition of hypocrisy.

I am sure beside the machines there may be ores that are needed to progress through IV which i cannot recall atm.

**Comment by Anarack** [comment]
I don't believe any ore is needed to progress, till possibly the circuit assline, but that would be unchanged from this change.
Alternative is simply reducing hut spawn rate.

**Comment by 0lafe** [comment]
Nothing for progression, I still haven't been to the planet and I'm on T5. It's nice for boron for glasses, and has an IV alternate glass source. Think some circuit assline parts as well. All things that don't need it/are used post T4

**Comment by quedral** [comment]
> Nothing for progression, I still haven't been to the planet and I'm on T5. It's nice for boron for glasses, and has an IV alternate glass source. Think some circuit assline parts as well. All things that don't need it/are used post T4

Borosilicate glass alternative? maybe i want to build a mega ebf for shiz and giggles in IV

This has been like this for years and changing it will effect lower tier players. Because you advanced to UV+ you cannot ignore everyone else. 

As i said after reaping benefits for years this is just hipocrisy nothing else.

**Comment by sthegreat** [comment]
So for the ideal solution of nerfing the machines found it appears there are two main places to mess with. (I'm a bit too lazy to try again on doing a nh dev environment)

https://github.com/bartimaeusnek/bartworks/blob/7d875ff69f1667b763f736f33531e07c50dabb60/src/main/java/com/github/bartimaeusnek/bartworks/system/worldgen/MapGenRuins.java#L136

is where machine tiers come from, this could just be reduced to 5 for ev or better yet given a config thingy.

https://github.com/bartimaeusnek/bartworks/blob/7d875ff69f1667b763f736f33531e07c50dabb60/src/main/java/com/github/bartimaeusnek/bartworks/system/worldgen/MapGenRuins.java#L189 as well as lines 199 and 241 is where generator, batbuff, and machine types are decided. Desired machines could probably just be disabled by adding a little check for undesirable meta, and breaking out of the if it's detected. Ideally try again at least once so something else can generate if it fails, and have a config for which metas to not like.

As for which machines should be disabled, I think max tier should be reduced to EV, and additionally the remaining two lightning rods as well as possibly ev naqs and the remaining massfabs/replicators should go.

**Comment by mitchej123** [comment]
> Edit: not a big fan of reducing hut spawn rate, I think that just makes the problem less evident rather then properly solving

I don't see the problem :sunglasses:

**Comment by bartimaeusnek** [comment]
> 
> 
> So for the ideal solution of nerfing the machines found it appears there are two main places to mess with. (I'm a bit too lazy to try again on doing a nh dev environment)
> 
> https://github.com/bartimaeusnek/bartworks/blob/7d875ff69f1667b763f736f33531e07c50dabb60/src/main/java/com/github/bartimaeusnek/bartworks/system/worldgen/MapGenRuins.java#L136
> 
> is where machine tiers come from, this could just be reduced to 5 for ev or better yet given a config thingy.
> 
> https://github.com/bartimaeusnek/bartworks/blob/7d875ff69f1667b763f736f33531e07c50dabb60/src/main/java/com/github/bartimaeusnek/bartworks/system/worldgen/MapGenRuins.java#L189 as well as lines 199 and 241 is where generator, batbuff, and machine types are decided. Desired machines could probably just be disabled by adding a little check for undesirable meta, and breaking out of the if it's detected. Ideally try again at least once so something else can generate if it fails, and have a config for which metas to not like.
> 
> As for which machines should be disabled, I think max tier should be reduced to EV, and additionally the remaining two lightning rods as well as possibly ev naqs and the remaining massfabs/replicators should go.

5 would make the minumum tier LV instead of steam

im all in for the suggestion of @Anarack but not for changing the generation at all, since in my opinion, its properly gated behind a rather costly machine, the IV Assembler and a Rocket.

**Comment by draknyte1** [comment]
> years

Because this planet had been around for that long? No. 😂

**Comment by chochem** [comment]
While I do want to see Ross changed, pushing it to T4 is not a viable option. Thorianite is absolute crucial at this stage. Not just for tiered glass, but also for th232.

changing spawn rate sounds decent. Maybe it would also be possible to just remove Mk2 Naqs and maybe one or two other late IV machines from the IV huts? After all the rocket is early IV (and rushable in early EV)

**Comment by Prometheus0000** [comment]
I agree with olafe that this stuff is too much, and I haven't been there and recently got to IV too. People on the discord yesterday were talking about how they rushed the T3 rocket so they could search ross. Personally I think if they were all non-usable machines you arc furnace it'd be fine, but going to ross skips building machines for looting stuff. I'd also like a config so you could cap the tier, however that would work in code. I think people previously mentioned that just reducing the rate would make people search more/longer. And the size of ross on servers with all these people exploring must be huge too. I'm also not sure it'd be realistic to be building a MBF in IV, I still only have the one, so more boron is irrelevant to me. And people should be making indium themselves instead of searching for a super-rare vein.

**Comment by draknyte1** [comment]
> Not just for tiered glass, but also for th232

Already has a recipe in the chem plant since my old recipe was being overridden. Not an issue moving forwards.

**Comment by GeicowithaBango** [comment]
hmm, its just about the mk2, isnt it? although, everything that contains a field generator may be considered as op or atlest very lucky. im actually fine with that since crafting the components is a lot quicker to do

**Comment by Prometheus0000** [comment]
Also lightning rods and grandmaster magic things. I also forgot to mention that it has thorianite, which allows for an alternative IV-tier glass for both MBF and making IV-tier machines (you need 9 molten tungsten for the normal one).

**Comment by chochem** [comment]
> 
> 
> > Not just for tiered glass, but also for th232
> 
> Already has a recipe in the chem plant since my old recipe was being overridden. Not an issue moving forwards.
> 
> Plus there’s fuel rods for it.

looking forward to that chem plant recipe. Its not in yet though. I might have considered the fuel rod path, but the recipe is pretty weird/possibly bugged as it only works for single fuel rods.

The glass remains a problem. The tungsten variant is crazy expensive.

**Comment by draknyte1** [comment]
> only works for single fuel rods.

Intended. Breeder reactors make fuck all power. There’s tickets regarding this feature already as people find it confusing.

**Comment by Bluebine** [comment]
So, I'm early IV and just reached Ross.
It's clearly overpowered. You can get free IV machines, as well as a few things that are late IV/LuV such as lightning rods, naq gens, and mass fabs, all at early IV. I found machines I can't even make yet, as well as a bunch of IV machines that would be a huge pain to make, all in a few hours.
The suggestion to make it T4 seems like the most logical one to me, as that'd gate it behind LuV so everything you find would be craftable. Thorianite would need to be looked at though, since IV glass is incredibly expensive without it. This could be easily solved by letting it spawn on a T3 planet, or by adding a chem reactor recipe for it as discussed.

**Comment by botn365** [comment]
even if it was pushed to T4 i think it would stil be to OP i think we should just disable the spawn of IV machine

**Comment by Extremity4** [comment]
In my opinion, the lightning rods and both tiers of naquadah generators absolutely need to go. Those are by far and away the most useful things to find, as they let you completely cheese power generation for effectively nearly two tiers (I was able to skip directly from a few HV gas turbines to IV naquadah gens, as the T3 rocket is almost too easy to rush). The magic energy absorbers are also quite powerful and give you completely free energy, so they can go too.

In my opinion, the random IV machines are okay, but I can understand why people want to remove them, so if the opinion sways that way then so be it. You find a lot of junk machines and it's extremely impractical to fly around looking for a particular machine type you need; it's more of a different way to gather materials (making use of the arc furnace). All machines requiring ZPM & LuV circuits should definitely get removed. I think the amount of tungsten/platinum you can gather should get looked at too; the battery chargers and 12x cables give you a ridiculous amount of tungsten by arc furnacing.

Also it might be good to remove the electrolyzer too, since it needs osmium which is quite difficult to obtain in late EV/early IV.

**Comment by ahmetsad** [comment]
Hv lightning rods should go but nag gens can stay they only give 1 amp of tier and if you are going stay in ross to find more of those gens in the same time you could have already progressed forward. Zpm and LuV circuit requiring machines can stay you can make them in the same tier you are on ross. If anyone against the loots they can change the config to make them almost impossible to find.

**Comment by Extremity4** [comment]
Just because the T3 rocket and IV naquadah reactors are technically in the same tier means nothing. Being able to mass produce the ZPM circuits as well as some of the other assorted bits and pieces required for a lot of MK2s (HSS-S, Plutonium 241) requires a massive amount of work whereas you can basically make the T3 rocket with a single IV machine. In my own singleplayer world, it took over a month of consistent daily gameplay (with my entire base being powered by MK2 naquadah reactors found on Ross) to even reach the point of being able to craft one of them. It's slightly less egregious in the case of MK1 naquadah reactors, but you can still get them significantly earlier than you can comfortably craft them by rushing the T3 rocket....
Also, one amp of tier is kind of a lot, which is why they're so damn expensive to craft in the first place. In conjunction with a PSS you can easily get through the entirety of IV solely on a few MK2s.

**Comment by ahmetsad** [comment]
1 amp of tier being a lot is another issue that means high tiers lack in energy generation you need at least 4 amp to get work the ebf and another few amps to run machines.

**Comment by Impos913** [comment]
Btw Pu241 is ez with trollplant. Just saying

**Comment by Houstonruss** [comment]
Increase the machine hut spawn rate dramatically, but only HV machines. It makes sense because the abandoned bases are all the people that give up at HV.

**Comment by combusterf** [comment]
You do need a painful amount of machines to hit LuV with all its platinum group requirements nowadays, so I'm not convinced the hut stuff is a killer.

On the other hand, bumping the planet means indium and particularly boron sources will get bumped as well, and with Bart's new glassware and the amount of machines needed for the platinum stuff, that is going to be an issue.

**Comment by SpwnX** [comment]
i haven't reached IV machinery yet (just got some random circuits) and havent made a t3 rocket yet, because my team is a bunch of weirdos (including me i guess), so take my opinion with a grain of salt:

maybe reduce tier of machines on ross to EV and increase hut size and amount of machinery spawned so looting them would be worth for materials and production, but not as much tech-wise.
Skipping tech by looting is 90% of the times bad imo.
maybe reduce tier of machines on ross to EV and increase hut size and amount of machinery spawned so looting them would be worth for materials and production, but not as much tech-wise.
Skipping tech by looting is 90% of the times bad imo.

**Comment by Retster** [comment]
I'm at End of LuV and start of ZPM now and newer looted any machines on Ross, but that plannet is one of the most recent planets of all after 3 tier rockets. Because Bedrock lava, Thorianite glass, boron useful ores etc. So my wote against to make ross T4 planet, but maybe to change machines spawn.

**Comment by redmage17** [comment]
Am I the only one that finds it funny that he is asking to nerf content his is past? AGAIN?!

**Comment by 0lafe** [comment]
If I just chill in stone age forever does that mean I can nerf anything I want?

**Comment by redmage17** [comment]
> If I just chill in stone age forever does that mean I can nerf anything I want?

Contribute something positive instead of focusing on ruining everyone else's experience once you don't have to deal with it

**Comment by 0lafe** [comment]
If your experience is ruined by not being given free tier machines, I got nothing

**Comment by Bluebine** [comment]
I'm precisely at the tier, and usually one of the first people to complain about 0lafe's dumb nerfs, but I agree with him here. Ross is incredibly OP and I feel like a lot of people voting haven't even been there. 
Voting for content you've experienced is a lot better than voting for content you've never reached, and if you can't have an opinion on content you're past... when ARE you allowed to talk about it?

**Comment by mitchej123** [comment]
I vote we up the tier of machines on Ross to ZPM.  Free ZPM machines for 0lafe!

**Comment by chochem** [comment]
according to dream we are not voting on if there is a problem here, but on if the solution is to move the planet to T4. That is why I vote no, even though the free T2 naq gens need to be nerfed.

**Comment by quedral** [comment]
It is obvious moving ross to tier 4 is a mistake.
Regarding the generator tiers, Bart himself declared that he will accept any PR if it is coded properly and has a config option. He said that on discord so anyone can check it. So if you want to nerf/tier down or remove the generators start coding and stop suggesting stupid nerfs.

**Comment by Prometheus0000** [comment]
I voted for yes because I thought that was the only option. Optimally we would restrict the tiers of the machines, but the people who really want it don't understand the code enough, and bart doesn't want to add the config himself for some reason. Maybe someone like mitch who can code could do this for us? If no-one's willing to make the appropriate PR, what other choice is there if we want to stop the OP machine grabbing?

**Comment by 0lafe** [comment]
ill update the post, but i feel like it somewhat explains that. Ideally the machine tiers drop to EV, and the tier stays the same. Imo it seems better to restrict the planet to T4 if it's not possible to change the items. It really just pushes lots of non uu'd boron to post assline, which isn't that bad. 

Enough Boron for the mega ebf can be obtained through uu if you want, and W glass works for IV pre assline. The indium vein is a joke

**Comment by leagris** [comment]
The other option, is spawn the machines with random UUID owner and a lock upgrade ;D

**Comment by Prometheus0000** [comment]
Would that:
a) be possible?
b) make it so that you can't use them, only arc furnace/macerate them?
If so, I like that idea.

**Comment by leagris** [comment]
This is possible since these are just NBT data
You would not be able to wrench them out though

**Comment by SKYCATV587** [comment]
Why not add a Machine Huts in Ross128ba , there will have frome  iv to zpm Machine,

**Comment by johnch18** [comment]
>Thorianite is absolute crucial at this stage
This. And frankly on the topic of IV glass, I wouldn't mind if it were easier to get.

**Comment by 0lafe** [comment]
What is it so crucial for? I personally still havent been to rossb and made it through IV with no glass issues

**Comment by Prometheus0000** [comment]
It was mentioned previously a recipe could be added to make it, or add it to another planet. If we raise the tier, we should do one of these.

It's for the alternative IV-tier glass. Thorium-Yttrium is way easier to make than 9 tungsten per glass.

**Comment by 0lafe** [comment]
Is putting the easier option for it behind a rocket towards the end of the tier a bad thing? It seems the easier option shouldn't be the first way to do it

**Comment by chochem** [comment]
Its already gated past a rocket!? also, you forgot again that its currently the best way to Th232. Moving Thorianite to a later age is a big nerf that you are trying to sneak in here.

**Comment by Prometheus0000** [comment]
You can choose to make the t3 rocket and go to ross, or make it with tungsten. The rocket is not exactly easy to make. Though not super hard either. So it's not the first way to do it. And if it's bumped to t4, then you wouldn't really need the IV-tier glass any more since you would've made the IV machines already most likely.

You may also want it to get Thorium 232 to make arcanite for the 9-1 and arc furnace multis as mentioned. Assuming you want to make them.

**Comment by bartimaeusnek** [comment]
@mitchej123 thats a config option now, you can make a pr, even uhv will work, or you restrict it to one tier only and restrict the machines

**Comment by richardhendricks** [comment]
How about adding some traps and monsters to the huts? Like if you pull this reactor, a timer starts before a nuke goes off. Easy stuff like that. :D

**Comment by SpwnX** [comment]
traps can be avoided and if its too complex, it is just enough coding to instead config the machines.

I like the lock idea, if it actually makes the machine unusable, it makes the machine spawn very lovely (troll)

**Comment by richardhendricks** [comment]
Well that's the point, the traps make it more difficult to just wander the planet looking for huts to raid. And "traps" could be a variety of types so that players have to really pay attention to what they're doing. Like "filling the room with lava" etc.

**Comment by Anarack** [comment]
or say... a active tesla coil, stuff like that, player sensors wired to tnt, mob spawners with nasty infernals preset in em. annoying potion effects, there are a lot of ways to annoy people, That one screaming crop.

**Comment by mitchej123** [comment]
> Well that's the point, the traps make it more difficult to just wander the planet looking for huts to raid. And "traps" could be a variety of types so that players have to really pay attention to what they're doing. Like "filling the room with lava" etc.

I'm a big fan of this idea vs the other ones.  I think it's how easy they are to get that's the problem, not that they're there.  

We had also talked about making them "broken" and requiring a random part to fix it.

**Comment by richardhendricks** [comment]
I like that idea too.

Player detectors would allow for all kinds of fun. Like doors that slam shut, spawners that activate to release monsters, triggering a timer with a nuclear control alarm going off, flooding the area with slow potions and water or lava, etc

**Comment by redmage17** [comment]
So I took a look around and the huts have randomized tiers, In the time it would take you to find an IV hut it would be easier to build an IV machine this nerf is stupid.

**Comment by GeicowithaBango** [comment]
but bart changed the platinum line @redmage17

**Comment by redmage17** [comment]
He also took some thought and expanded both it the LuV tier. He added content instead of taking a nerf bat. I would not be against some traps since there are no mobs on Ross and removal of lightning rods and Nauqadah gens.

**Comment by Prometheus0000** [comment]
So, on the newer versions, there's now a config for the machines you get on ross, with the numbers correlating to the metadata of the machines you can get. Maybe we should discuss what to remove (now that we actually can), and if IV tier machines should be there at all, or just remove the egregious ones like naq gens.

**Comment by leagris** [comment]
This would probably be another RFC on its own, but Gregtech machines could benefit from having a quality and lifespan to create an economy sink, and alternative solution for pillage, loot devices.

Imagine if machine efficiency would depend on the quality of its crafting components, like a circuit made of vacuum tubes and pinned components is less good than the same circuit tier made of SMD, Laser etched wiring...

Imagine if looted or pillaged machines/items/devices could have variable quality and even fail after some time.

Imagine if user B operating machine crafted by user A (Gregtech already has this data) would have some chances to degrade said machine or cause damages? Di you trust Joe farmer in his dirt hut operating the GUI of your plate bender. Sure he may stuck a plate wrong and only you owner (crafter) of the bender, can wack the stuck plate out.

Now guess what, this pillaged NQ Reactor is fine, but since it was not crafted by you, it has some chance to break even when wrenching it out. And if it ever fail, you will not be able to fix it since Gregtech knows you did not craft it.

**Comment by Prometheus0000** [comment]
So are we going to remove IV machines (or even just cables, they have lots of tungsten in them) or leave it like it is?

**Comment by botn365** [comment]
IV should be removed
