### ISSUE TITLE
Stemcells and Biocells need to be reworked

### ISSUE THREAD

**Issue by Dream-Master** [GTNewHorizons/GT-New-Horizons-Modpack#5898]
Stemcells and Biocells need to be reworked.

I need input here.

recipes now:
![image](https://user-images.githubusercontent.com/2970688/79022382-12385980-7b7e-11ea-9537-601ce53129dc.png)
![image](https://user-images.githubusercontent.com/2970688/79022392-15334a00-7b7e-11ea-8d77-418bdc79180b.png)
![image](https://user-images.githubusercontent.com/2970688/79022417-21b7a280-7b7e-11ea-8928-38c1a14b87d6.png)
![image](https://user-images.githubusercontent.com/2970688/79022427-25e3c000-7b7e-11ea-8b22-3a04fd917285.png)
![image](https://user-images.githubusercontent.com/2970688/79022429-28461a00-7b7e-11ea-8200-775c7f716962.png)
![image](https://user-images.githubusercontent.com/2970688/79022434-2d0ace00-7b7e-11ea-981b-dba313efdd70.png)
![image](https://user-images.githubusercontent.com/2970688/79022438-309e5500-7b7e-11ea-8c72-df3ceb0d7de1.png)
![image](https://user-images.githubusercontent.com/2970688/79022448-372ccc80-7b7e-11ea-9ab1-3349434ab374.png)
![image](https://user-images.githubusercontent.com/2970688/79022456-3dbb4400-7b7e-11ea-805a-a3125a61a402.png)

**Comment by GeicowithaBango** [comment]
the two things Im truly concerned about are the raw growth medium, the recipe ingredients don’t seem to be suitable and the tiny pile of infinity dust for the raw bio medium.

**Comment by GTNH-Colen** [comment]
Agreed, raw bio medium is far too expensive with the actual infinity pile. Perhaps replace it with a few dusts of infinity catalyst instead?

**Comment by Kiwi233** [comment]
The really expensive thing is the TCetiE-Seaweed Extract. Countless amounts of electricity, Bone and Minced meat...

**Comment by GTNH-Colen** [comment]
I didn't want to veer too far off course since this thread seems to be solely about balancing the above recipes but I do agree with you. So many recipes involved in creating UEV circuits take a ton of time at a really high voltage, it could use some fine tweaking.

**Comment by ScriptedPiky** [comment]
I have an entire ticket dedicated to this issue: #5005. But I will reiterate the basics of it; changes two recipes (Example [Bio Medium](https://user-images.githubusercontent.com/41557212/64915602-ba3c9000-d71f-11e9-989a-ad225a2a8345.png) and [Bio-cells](https://user-images.githubusercontent.com/41557212/64830160-0357dd00-d584-11e9-973c-57ba9085018f.png)). These two recipes can be added in to Bart's Bio Vat instead with some following requirements:
Raw Bio Medium requires materials above, as well as a continuous moderate-level radiation treatment of 25-50~ Sieverts (the vat has a special mechanic/requirement that we can use) at UV tier.

Biocells use the same materials and perhaps a chemical reactor recipe instead at UV tier.

Raw Growth Medium could use a recipe as the following: 4 Minced Meat, 4 Salt, 4 Calcium, 1 Agar, and 1 bucket of Distilled Water. A requirement of 25 Sieverts is needed to continuously process this, and once all the recipes are inputted, will output 1 bucket of Raw Growth Medium. Do note that due to the unique circumstances of the Bacterial Vat and its 100x (or 1000x as some might say, but this is entirely unsure) gradual increase over time, can make a large difference in this.

Stemcells... I'm entirely unsure of how to properly approach this. But we could use the Bacterial Vat once more for this process.

**Comment by Prometheus0000** [comment]
Wouldn't it make more sense to include the fluid or solid Growth Medium item to make Raw Growth Medium?

**Comment by GeicowithaBango** [comment]
(bio) stemcells shouldnt have a bacteria vat recipe, the unique gimmick of boosting fluids cant be used to boost items as output

**Comment by Dream-Master** [comment]
@ScriptedPiky thanks totaly forgot about this issue. Will look into it.

**Comment by GeicowithaBango** [comment]
a nice component for using would be bacterial sludge and mutagen. it really fits if you think about growing life from „nothing“. Which makes sense since the wetware/bioware are used to support life itself

**Comment by Prometheus0000** [comment]
Bacterial sludge is a huge pain to get though. Was there a recipe for it? I don't think there is. And mutagen is made out of it. If there's a recipe or you could pump it, that would be fine though. But I can imagine that the servers would have a serious lack of it.

**Comment by Dream-Master** [comment]
@Prometheus0000 why you judging about recipes that i recoding know. Let me do my work finish and we will see.

**Comment by GeicowithaBango** [comment]
he probably didnt know about it :p
