### ISSUE TITLE
Suggestion: Add a recipe for leather from oil chem

### ISSUE THREAD

**Issue by Anarack** [GTNewHorizons/GT-New-Horizons-Modpack#5918]
Leather is somewhat annoying to get sometimes.

Suggested, woven cloth + polyvinyl chloride in a fluid solidifier.

https://en.wikipedia.org/wiki/Artificial_leather

**Comment by Dream-Master** [comment]
i adding a recipe in the past use 2 Leather and some acid to get Tanned leather.
But sure i can add another recipe too.

**Comment by Dream-Master** [comment]
so you mean some synthetic leather. Ok i will do a new item and oredicted it.

**Comment by leagris** [comment]
It'd be less hassle if the synthetic processes could output tanned leather and regular leather rather than adding new items with predictable compatibility issues with all the recipes hard-coding an item reference rather than ore-dict names.

As for the industrial tanning process, I'd choose boron and, or salt solution in chemical bath.

**Comment by Dream-Master** [comment]
yea allready added but i will add more recipe to make tanning better
