### ISSUE TITLE
pollution effects discussion

### ISSUE THREAD

**Issue by Anarack** [GTNewHorizons/GT-New-Horizons-Modpack#5954]
Suggest effects/changes to make pollution not pointless, and I guess if you think it should have a point.

**Comment by Prometheus0000** [comment]
I didn't think it was off-topic to mention this stuff when mitch specifically asked for ideas, but whatever. I think that being able to just ignore pollution is bad, and it should be something that you have to counter or deal with the effects. Especially if you go over 1M. I have a pyro running constantly and still don't hit that. People need to be encouraged to upgrade mufflers, or what's the point of having upgrades for them.

Here are some ideas, some are not really realistic, or likely to be accepted admittedly.

Fog that increases with pollution (always active), eventually effectively being the blindness effect.
Reducing max hearts (temporary, but really long effect), also keeps reducing up to 1 heart left
Increasing amounts of hunger, or something similar
Directly taking damage
Adding warp
Chance of mob spawning, even in light (probably a new mob, like a pollution cloud, or dirty slime or something)
Some kind of 'nature lover' mob spawns, and tries to kill you (boss)
Placing some kind of 'sludge' block or fluid randomly
Killing bees
Making machines really loud
Adding 'dirtiness' textures to everything around randomly on top of existing ones
Sending chat messages to shame you
Changing light level required for mobs to spawn
Biome changes
Reduced machine speed, reducing more as it gets worse
Increased machine EU cost, increasing more as it gets worse
A chance for cables/pipes to randomly disconnect (this would cause explosions, so probably not)
Low chance of voiding at high levels of pollution
A chance for machines to 'break' and revert to casings at really high levels
Make coils effectively tier-1
Make DTs only output some of the normal outputs
Have programmed circuits revert to 0
Have cleanroom void 100% if any pollution
Interfering in wireless redstone signals
Make OC computers not work (they're complex computers after all)
Similar to above, but SFM, tectec, other stuff maybe
Add chance for hungry node to spawn (they don't eat tile entities, right?)

**Comment by 0lafe** [comment]
On multis it could decrease the interval for additional maint issues

**Comment by noobnoobnub** [comment]
for the top idea it seems good, but for the below it getting way crazier and annoying, even not making sense.

Imo, I think these ideas are quite cool. I would like to see captain planet earth or some Environmentalists hunting you and call for shutting down

Fog that increases with pollution (always active), eventually effectively being the blindness effect.
Reducing max hearts (temporary, but really long effect), also keeps reducing up to 1 heart left
Increasing amounts of hunger, or something similar
Directly taking damage
Chance of mob spawning, even in light (probably a new mob, like a pollution cloud, or dirty slime or something)
Some kind of 'nature lover' mob spawns, and tries to kill you
Adding 'dirtiness' textures to everything around randomly on top of existing ones
Sending chat messages to shame you
Biome changes

**Comment by dvdmandt** [comment]
I think it would make sense for cleanroom to be affected somehow. Maybe the cleanroom needs more energy to counter pollution (higher tier energy hatches)? I could also imagine multiple tiers of filter casings. Perhaps if the cleanroom had two stats, maybe air purity and efficiency. Pollution would decrease air purity, having the cleanroom running would improve it by a factor of energy tier, efficiency and possibly filter casing tiers. A side effect of this could be that cleanrooms wouldn't necessarily start voiding stuff as soon as there's a maintenance issue. There's a lot of variations on this, but the core idea is to make cleanrooms have to counter pollution.

IC2 crops having their stats reduced or production slowed down is another thing I basically expected to be there when I started dealing with them, especially as they have some air quality modifier or something.

Fishing and animal traps could have their chances/speeds reduced.

All crops and fruits growing a bit slower and/or having a chance to produce bad results (ie poisonous potato).

If not killing bees, perhaps killing flowers and/or lowering bee produce and/or lowering their mutation chances or something. Perhaps different bees could have different resistances (think hard coded values) so that beginners aren't too punished while making it an issue for higher tiers.

A less serious suggestion, but just throwing it out there, would be to turn water source blocks into that annoying type of poison that is found everywhere below ground. I don't think it's a great idea, and it would definitely have to be limited to very small pools of water, perhaps even single source blocks.

**Comment by Prometheus0000** [comment]
Also see the channel for it
