### ISSUE TITLE
Impure Tear Discussion

### ISSUE THREAD

**Issue by Anarack** [GTNewHorizons/GT-New-Horizons-Modpack#5978]
Current recipe
![image](https://user-images.githubusercontent.com/20565115/80284927-37cd7300-86e7-11ea-8bfc-4662c8654271.png)

Starts having a chance to remove 1 warp at 50 warp, 100% chance at 150 warp

Haven't used it for the affects but I dislike requiring ic2 crops for a purely thaumcraft related item.

**Comment by Prometheus0000** [comment]
It also requires BM for the cells with life essence, and the Magicales. I'm fine with any changes, this was just the initial recipe version I didn't expect to make into the pack anyway.

**Comment by quedral** [comment]
I wouldn't expect too many comments on this recipe and the item's property.

Any sane person will be like:

"ic2 crops + witchery + bm for just 1 warp at 1% chance? gtfo."

**Comment by Prometheus0000** [comment]
Then suggest changing those? They didn't seem _too_ hard to me for some of them. The odor of purity you make a bunch of anyway, and I dunno how many people avoid crops. The Magicales is probably too much, and I have no idea how to automate aurelia petals, but nobody complained, and it went through really fast. And people seemed to like the chance base stuff on that issue page. #5643

**Comment by Dream-Master** [comment]
@Anarack before we havent this item so i think the recipe are ok. i dont want to get an tear easy.

**Comment by Anarack** [comment]
I know don't think it should replace the main tear either, mainly made the issue as there was a blow up in discord about it, just glad it exists in some form.

**Comment by quedral** [comment]
I still think its useless. pushing through pure tear is much easier/smarter than having an item that has 1% of removing permanent warp by 1.

lets say you have 150 warp and crafted 10 of these babies
once you used one you have 149 warp and 99% chance removing another 1 point of perm warp

lets say you are lucky and got it down to 140. it really doesn't make much difference between two warp levels.

Below 90-80% percent chance of removal only a fool would craft and use this since the items are needed are not easily gathered. (you need bm / witchery / ic2 crops)
so this items effective range is betwen lets say..130-150 warp range?

If you think this is effectively usable then more power to you what can i say.

**Comment by quedral** [comment]
my suggestion for alteration is make it usable only between warp levels 110-150.
every 1 tear removes 5 perm warp 100% chance. so 10 tears is effectively put you on warp level 100 if you have reached 150.

only then the cost would be acceptable imo.

**Comment by richardhendricks** [comment]
I think the original idea was because on the officials the town protection was expanded to include warp levels. So if someone had excess warp, they could be banned from even the spawn area (due to TC warp ignoring town protection and causing damage). This item gives naughty players a slightly better way to get warp removed than the spa/soap method.

**Comment by repo-alt** [comment]
50 warp means not just lightnings but blocks decay (dirt -> sand) I don't think any sane person would set town warp protection above 30, to avoid random lightning guests. Which makes this item slightly useless. I mean - it is good idea in general to have a way to reduce permanent warp before pure tear, because pure tear is gated at  late IV and quite a bit of research (and warp), but 1% chance at 50, seriously? To get BM alchemy alone (especially automated) you would likely get quite a bit of warp.

**Comment by Prometheus0000** [comment]
The warp theory config was supposed to change too (#5690), but dream decided that we need more warp effects first for some reason. Even though there's no discussion on that or suggestions. If it had changed, the impure tear would be more useful, as the effects would have been pushed later. Also, I have no idea about server town protection stuff.

**Comment by repo-alt** [comment]
With the warp rebalanced as in that suggestion it may make sense. I would say that it needs to have that 1% chance at the level of warp 1 point below the lightnings (or decay - whatever is first), so that it would be possible to get rid of the block destroying warp, but punishing enough.

**Comment by Prometheus0000** [comment]
Lightning would've been at 105, so if you happened to step over that amount, it would've been easy to get back with soap+impure tears. But with the unchanged config, it is mostly useless.

**Comment by noobnoobnub** [comment]
Speaking of which, osmiridium can be obtained in a hard way at hv with mega blast furnace and mega distillation tower with a lot of hv energy hatches. So you should probably nerf it for people getting pure tear at hv for whatever cost it is.

**Comment by Prometheus0000** [comment]
Make the pure tear require an ABS fluid (and probably solidified) that needs a IV or LuV hatch then?

**Comment by repo-alt** [comment]
Is it really possible to build mega blast furnace at HV? If it is then it should probably be fixed?

**Comment by Anarack** [comment]
your still coil limited. so yes you can build it but no I don't think you can smelt it.

**Comment by Bluebine** [comment]
Physically? Yes, it's possible.
Realistically? If you manage to build the mega EBF in HV you damn well deserve to skip a tier or two

**Comment by redmage17** [comment]
I feel that the impure Tear recipe doesn't quite fit and should be made slightly more expensive. I think the recipe should swap the quicksilver blocks with ordo crystals, the biomes o'plenty hard ice with a ghast tear,also remove the darn tomotoes, and the life essence cells with sanctus(from blood magic.) Also for the essentia requirements remove veneum, gelum, and fames.

I'd rewrite the entry as:

You have dealt the warping effects of the darker side of thaumomancy to the point it has become irksome. Maybe it is time to delve into forces to purify the corruption.

Your solution was a small drop that provides some cleansing power. It's potency waxes and wanes corresponding to the corruption(You need 50 warp for a 1% chance for this to work, at 150 warp it has a 100% chance of removing warp this scales) Better regents may be required to fully purge yourself of warp.

This makes more sense thematically and if you accumulated that much warp you this recipe isn't that much more expensive

**Comment by redmage17** [comment]
It probably does need to be set to remove a standard amount of warp say 10-20 instead of this scaled crap

**Comment by redmage17** [comment]
Relying on RNG for mechanics is bad

**Comment by Dream-Master** [comment]
yes why not. Recipe sounds cool. Will do a check tomorrow

**Comment by Prometheus0000** [comment]
Changes should be in latest pack version.
