### ISSUE TITLE
make fusion suck less

### ISSUE THREAD

**Issue by 0lafe** [GTNewHorizons/GT-New-Horizons-Modpack#5990]
#### Which modpack version are you using?
New.current

Currently fusion pretty much as a whole sucks. It's fun to make the reactor, but after that it's one of the worst multis we have atm. All inputs are simply 2 usually boring fluids, and the power gen is incredibly simplistic. It would be nice to try to implement fusion recipes in a better way, and balances the power output more reasonably. 

The fusions id consider to be problematic mainly, are He and Sn plasma, simply due to their dominance. He is the best you can do for power in an mk1, and Sn is the best in mk2+. Both of these have absolutely retarded production chains at the moment. 

Plasma fusions with other issues imo would be Nb and Rn. They don't really produce enough to be viable as power or material generators, but also have stupidly simple setups. 

There's some non plasmas with issues as well, in the case of W, Os, and possibly In. These are simply not super worth using at the moment do to alternate options for generation. 

The final thing I'd like to highlight would be the power generation step post plasma gen. Right now, it's pretty trash. You make a multi that's essentially free, and use the same type of turbine items you use pre fusion. 

I have some ideas on how to fix some of these issues, but it's not the easiest thing to do. Complex powergen plasmas seem nice, but it's difficult to put irl fusion recipes into a GT context. He plasma ideally would take H-3 from nukes to start, then through running the reaction would produce neutrons to convert more Li into H-3. However, that's not exactly possible in GT, which presents an issue. Our current H-2/H-3 generation is kind of awful though, with the He-3 recipe being even worse. 

My idea for revamped He plasma would be two main points. One, would be to remove the He-3 recipe for the plasma. The next step would be to revamp the production of H-2 and H-3. Currently we just centrifuge them out of H2 at some very large amounts, but that's no fun for a fusion setup. 

First, H-2 gen should be changed. It seems irl that there's a chemical reaction that's used to produce H-2 in large quantities from water. Essentially water is mixed with H2S to isolate a ~20% concentration of Deuterium oxide, D2O. This is then further distilled into a high concentration of D2O, which is finally electrolyzed to produce pure H-2 gas. Putting this into GT recipes is a little weird as it works on a recursive process that will slowly increase levels of H-2 in the water, and do some wacky things. If you want to read more about how this works, I mostly just tried to understand this https://en.m.wikipedia.org/wiki/Girdler_sulfide_process 

Trying to put this new H-2 recipe into GT is possible though, and here is my best attempt. I'm purposely leaving voltages and times blank for the moment, I'd like more feedback on required infra/power loss to generation. Imo balancing it with non ++ D/T fusion is decent, but if we use more CR steps I could see it being raised to due to the scaling. 

1000L Water + Circuit integration (different than hotspring/steam) -> 1000L Hot water ~ (fluid heater)

1000L Hot water + 500L H2S -> 500L H2S (enriched) + 1000L hot water (depleted) ~ (chemical reactor) 

2000 Water + 500L H2S (enriched) -> 2000L water (enriched) + 500L H2S ~ (chem reactor) 

1000L Water (enriched) + some circuit integration -> 1000L hot water (enriched) ~ (fluid heater)

1000L Hot water (enriched) + 500L H2S -> 500L H2S (enriched) + 1000L hot water ~ ( chemical reactor) 

10000L Water (enriched) -> 6400L H20 + 3200L DHO + 400L D2O ~ (distillation tower)

3000L DHO -> 2000L Mixed DH gas + 1000L O2 ~ (electro)

3000L D2O -> 2000L Deuterium + 1000L O2 ~ (electro)

1000L Mixed DH gas -> 500L Deuterium + 500L H2 ~ (distillation tower)

The idea of this is to simulate the repetitive nature of the irl process with only 1 circular step. The initial H2S enrichment will only be completed once, at which point the H2S will cycle between hot/cold water, depleting the water of it's deuterium. Technically at a concentration of less than .5% deuterium per hydrogen, this process would need to be repeated a large amount of times even at 100% efficiency. While I'm not opposed to adding many many stages of D rich water/H2S, I'm not sure that's the best thing for GT. Id suggest simply elongating these recipes to be somewhat power intensive, and pretend we do the whole thing lol. The distillation afterwards is simply to separate out the H2O from D2O, and HDO, with an assumed quantity of ~20% D for every H. These are then electrolyzed, with HD gas then being distilled once again to achieve pure D isolation. 

For power/time values, I'd recommend setting a cost of ~10% loss without OCing, and putting the distillation voltages somewhere around EV to make use of the mega distillation tower. I'd also suggest a large power cost in the electrolysis/heating, as that would be the main step to encourage larger setups to be more efficient, as the LCR/MDT have perf OC for a while here. If this comes down to a single LCR, DT, electro and heater, that would be pretty boring imo. 

Tritium however is more complex. Primarily being produced through neutron bombardment of Li, we don't really have many options for it. Ic2 nukes do have tritium production, however it's unchangeable, meaning we would need to model this whole chain around current nuke production. We can also do some things with Nt dust, as it's essentially a pile of neutrons, however I'm unsure of a good way to do this. The cyclotron could be used here, however I've heard that we can't use ++ multis for this. I'd personally recommend modeling this with the idea of ic2 nuke tritium in mind, however that doesn't need to be the case. 

In all for He plasma, I'd like to see something around 1 LCR, 3 PA of heaters, 5 PAs of electros, 32x DTs, and 4 nukes to power an mk1. All having around a 200kv loss from efficient power usage. Keeping power output the same, this would be a net gain of almost 1Mv which seems pretty reasonable, and inline with current He gen. 

The next issue with plasmas, is the generation. Currently you simply run the plasma through a small turbine, and get power. I'd recommend we remove the plasma turbine, and switch to a generation that's more suited for ZPM+. Imo, a much larger, higher tier heat exchanger, coupled with a very large steam turbine would be the best solution. A 9x9 or so of tungstensteel/Osmiridium for a heat exchanger could be fun, coupled with a turbine similar in size to the mega ebf. Imo the way we currently do turbines isn't really suited towards later game mechanics, but I'm not entirely sure of a better alternative. Some level of maintenance such as a lubricant needing to be supplied would help, as well as possibly creating the turbines within the multi out of varying blocks for varying output. I'm somewhat against the idea of turbine death, but would rather see more done in the realm of needing to keep your turbines healthy or you loose the multi. This step as a whole isn't really needed, however the current plasma power gen options are pretty awful as zpm+ generators. I could see a single mk2 LHE being able to handle maybe 4Mv or so worth of plasma, with some fun spin up/down type efficiencies for sub 4Mv throughputs. A large turbine could possible do 2Mv at max eff, and use a scaling similar to current turbines or bot's LRE. 

I mostly suggest new LHE/Turbines as using our current multis results in either incredibly low machine counts of essentially free multis, or quantities of machines most people wouldn't want to place. 

I'll update this with thoughts on other plasmas, but atm I think fixing He should the focus due to it being the first/only power choice for Mk1 fusion. Sn is by no means balanced, but I don't have anything productive to do with it besides complete removal. More complex chains for Mk2/3 fuels would be nice, however there's some issues. We would need to divert from reality with these, as they aren't really usable in the way we do it. Imo we could add things such as Nq plasma, or other materials we already fabricate, but those production chains would probably just be made complex for the sake of complexity. Not against this in any way, I just don't have any ideas atm.

**Comment by Anarack** [comment]
Some thoughts.

On Fusion
- Lithium mass production is tricky without clay duplication, and most of the methods for that are not exactly server friendly to spam.
- One of the benefits to the base plasma is that it is fully renewable, while the breeding cost is low on reactor fuel usage its still removing the trivial renewable nature of this.
- Nothing stops us from adding our own version of the ic2 lithium cell for reactors, we have quite a few new cells.
- How many non mega distillation towers would we need? the thing is fugly as shit. Unless it can be made shorter but is still runs into issues if you make multiple high tier reactors makes it rather hard to fit into existing builds. 3 of the things per t3 reactor would be tricky to make look ok.

LHE/Turbine Thoughts
- Bricking every post fusion player is a non starter, need a way to allow transition over several major server versions to allow transition, or introduce it as a alternative.
- possibly leave it as the most basic rout to get power out? or at least 1 step above the singles.
- I'm not opposed to the LHE/turbine change, but I'd need more details on it, as long as at a minimum the number of turbines does not increase, they are rather hard on machines when turning on/off large amounts of them.
- Instead of losing the multi I'd look at the turbine items instead, they still have durability after all.
- As for the heating/cooling game on the MK2 LHE, what like a railcraft boiler? where it gets more efficient and more output the hotter it gets. Lets you indirectly force lower tier setups to use the basic turbines while rewarding people for the more plasma the can push, and I guess have it also scale whatever upkeep it needs so you can decide on a balance point.
- like with the mega distillation tower kind of iffy on its size, think something that you could say coil fusion reactors around would be a nicer size.

**Comment by finkledoodle** [comment]
Instead of focusing so much on the most basic plasma recipe, it would server the players much more to look at why other fusion recipes aren't being used, and buff those instead. Nerfing the mainstay fusion recipe that has been untouched and part of the pack for years, just because you feel that other recipes are underutilized, is not the solution. Instead, just give the same amount of examination to each other plasma to bring it up to tier with helium and make it more widely used.

**Comment by Bluebine** [comment]
so, my thoughts:

the new deuterium method sounds cool! much more interesting than centrifuging hydrogen. all for that.

tritium from nukes is super annoying atm and should definitely be looked at. 4 nukes is a lot to keep constantly fueled and running as well as constantly supplying lithium. if we do go that route, tritium's gonna need a buff.

the heaters, electrolyzers, and especially DT requirements are kinda ridiculous. that amount of electrolyzers and heaters is fine for a single T1 reactor, but what about when you're trying to fuel 10 T3 reactors? build 200 mega DTs and 500 PAs of machines? Especially the mega DT part. Those bitches are expensive and HUGE. One or a couple of them should be enough for a pretty huge fusion setup. Machine spam isn't fun. 

overall I think helium plasma should be one of the simpler options (as it is now), but it should also be one of the worst. requiring a ridiculous machine dump to fuel even 1 reactor is crazy. Just make 1 reactor make less- maybe 200-300kEU/t would be fair, if the deuterium processing chain requires like 20-30 machines and a DT or two instead of an entire chunk full of shit.

as for changing turbines, idk. I like the idea of big multiblocks, but I don't like the problems that come with removing turbines, namely fucking over everyone using them right now. Maybe reduce turbine output and add the multi as a higher-efficiency option? Certainly, just removing turbines would be obnoxious as hell.

Overall, as always from 0lafe, it's a decent idea but WAY overkill on the numbers.

**Comment by finkledoodle** [comment]
I still see no need to change helium plasma from where it stands right now. As more uses are added for UHV+ tier machines, helium plasma will become less viable naturally as players progress, or they'll have to scale it up to match. Just make the other existing plasma's more appealing at higher tiers and that would solve any problems without any of these other convoluted changes.

**Comment by feliser** [comment]
I like idea but maybe not mega distillation tower because that is too fat and hard to fit into a base

**Comment by 0lafe** [comment]
>anarack 
>fusion

We could fuck with the Li:T ratio a bit, and possible adjust overall recipe speeds to fit pretty much any Li gen rate. We could balance it for UU for example, but i think there's some other good Li gen sources. Ghast tiers are decent

>turbine shenanigans
we can disable the recipe for current turbine multis but leave them in. It would provide essentially no change. Then remove them all together a few versions later if we want. You could still use it with lower throughputs through buffering. We could allow for the mega DT to exist as a more efficient option. If we require say 32 DT's for max eff mk1, you could cover 2 Mk3's with one mega DT, while being able to use normal DT's at numbers of 16 or below with noticeable power loss. Rewards the larger setup, while allowing what is still a large setup to exist at a similarly worse efficiency. 

>I still see no need to change helium plasma from where it stands right now. As more uses are added for UHV+ tier machines, helium plasma will become less viable naturally as players progress, or they'll have to scale it up to match. Just make the other existing plasma's more appealing at higher tiers and that would solve any problems without any of these other convoluted changes.

The other plasmas will go through a similar concept. At the moment they all pretty much suck, I'm just starting with He as it's the first/only MK1 power plasma. At least one mk2 and one mk3 recipe will probably be made, that is more complex than He, and more rewarding. I was personally thinking something close to ~1Meu/t in an mk1, 3M in an mk2 and 8M in an mk3. I'd argue that almost all of the fusion recipes aren't in a good place at the moment, and He is a good starting point. Lots of the material generation is too bad, lots of plasmas are awful, and almost everything is produced in a pretty shitty way. Sn plasma in perticular is an incredibly disappointing plasma. Our most power productive fuel uses 2 EV machines to supply fuel. Personally I think He dominating mk1 seems ok, and this gives it a decent progression from late LuV. 

>the heaters, electrolyzers, and especially DT requirements are kinda ridiculous. that amount of electrolyzers and heaters is fine for a single T1 reactor, but what about when you're trying to fuel 10 T3 reactors? build 200 mega DTs and 500 PAs of machines? Especially the mega DT part. Those bitches are expensive and HUGE. One or a couple of them should be enough for a pretty huge fusion setup. Machine spam isn't fun.

I changed the DT one a bit. Thinking of 32x EV recipes at 1keu/t being required, then you can do it with normal DT's, and loose a small bit of power (~A LuV) running 16x IV's, or ~2A LuV loss with 8x LuV's. Gives a reasonable DT setup, while allowing a mega DT to run 2 mk3's at perfect efficiency. The heaters/electros aren't very substantial at the values provided. 32x PA's for mk3 He is roughly what it used to be. This is only for max efficiency though. When doing multiple reactors its reasonable to OC these arrays and keep a similar quantitiy. If these are roughly ~100keu/t, OCing the arrays twice would cost you 300keu/t to retain the 32 arrays. However, at this point you would be making close to 16Meu/t from the reactors fueled by that setup. While it has its limits, it does keep good array quantities with semi forgiving overclocking.

**Comment by GeicowithaBango** [comment]
A bigger variety of useful plasma fuels would be nice to have. my idea here would be to make players benefit when the combine diffrent plasma fuels —> infrastructure for to processing chains should be more rewarded then just the sum of the energy density etc.

**Comment by leagris** [comment]
Also regarding plasma turbine damage. I think it is unfair to have damage proportional to EU produced. If damage was only runtime based, it would incentivize using higher density fuels plasmas. For now, with EU produced proportional damage, running high density fuels is a penalty.

**Comment by GeicowithaBango** [comment]
this is incorrect, a more dense energy fuel „just lasts longer“ . the durability of a turbine is linked to its performance, independent from the given plasma fuel.

**Comment by leagris** [comment]
> this is incorrect, a more dense energy fuel „just lasts longer“ . the durability of a turbine is linked to its performance, independent from the given plasma fuel.

Compare running time of turbine of same material in:
1. Large Steam Turbine
2. Large Gas Turbine
3. Large Plasma Generator with He Plasma
4. Large Plasma Generator with Ni Plasma

Se how at equal turbine Material it last less in 2 than in 1, less in 3 than in 2, less in 4 than in 3.

**Comment by GeicowithaBango** [comment]
oh, excuse me. i thought you meant the durability lose specific for plasma turbines. :)

**Comment by botn365** [comment]
instead of using nukes to make tritium we could change the fusion reactor to allow you to make tritium from lithium

**Comment by 0lafe** [comment]
We could, do we want He to use 2 reactors for Max eff tho? I'm not opposed here but how would we want to do that? 2 reactors required? 1 and like 1/4 the run time of another? I'd assume we'd want to do more than 1Mw from both put together? Also, what kinda recipe? It seems like Li+neutrons is what will make our H-3. 


Crazy idea, we could try to be realistic here. He plasma will actually crate many stray neutrons, which irl seems to be the way to supply fuel. We could possible add another in/out to the reactor? Something to the idea of something that is held around the reactor, and can interact with neutrons. Could be a general way to add neutron collisions for other isotopes as well, which is neat. 


@GeicowithaBango how you feel about He plasma being in whatever mk2 recipe is better than it? Take 2 mk2 reactors to run, and it makes 6Mw or so? I'm not sure what it would be, but I'm sure we could come up with something

**Comment by botn365** [comment]
needign a second reactor would be stupid
im talking about making so the recipe map can handle more then 2 fluids or if you have a input hatch with litium water in it creates tritium if the reactor is running

**Comment by GeicowithaBango** [comment]
hmm, i really thinking that some red stone control would be enough to manage the fluid for the fusion reactor so that you wouldn’t need to run two. 
Of course using one for a more complex task will be less efficient, this might animate the player to craft a second fusion reactor to make better use of new fuel chains, etc.
