### ISSUE TITLE
[Electrotine] incorrect Mixer recipe

### ISSUE THREAD

**Issue by MotDT** [GTNewHorizons/GT-New-Horizons-Modpack#5998]
#### Which modpack version are you using?
2.0.8.3
#
#### If in multiplayer; On which server does this happen? 
eta.gtnewhorizons.com
#
Incorrect Mixer recipe Electrotine:
We have recipe: electrum + redstone  = 8 electrotine; 
using ULV and 10 sec.
![изображение](https://user-images.githubusercontent.com/47714084/80403932-175d0e80-88c9-11ea-9725-f948a89fa40b.png)
#
And we have recipe: redstone + electrum + programmed circuit 1 = 8 electrotine;
using MV and 90 sec.
![изображение](https://user-images.githubusercontent.com/47714084/80404142-6acf5c80-88c9-11ea-9d4f-48b2f91f60f9.png)

**Comment by chochem** [comment]
this is outdated. the recipe has already been changed 2-3 times since.

**Comment by Dream-Master** [comment]
fixed so far ik

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/80415085-4cba2a00-88d2-11ea-8f87-4e6e69f06369.png)
![image](https://user-images.githubusercontent.com/2970688/80415096-504db100-88d2-11ea-9e84-a723ea1d7650.png)
![image](https://user-images.githubusercontent.com/2970688/80415104-55aafb80-88d2-11ea-8566-1bd3a909ce61.png)
yes fixed in 2.0.9.0dev
