### ISSUE TITLE
Nerf Tanks? Discussion

### ISSUE THREAD

**Issue by noobnoobnub** [GTNewHorizons/GT-New-Horizons-Modpack#6006]
There is no point to make fluid canner for getting fluid out of the cell as tank can out cell without power supply.
So the best option for balancing it out is by slowing the canning speed of the tank?

To be honest I don't bother with it, but it feels too op for getting a cheaper recipe and not having proper power supply (maybe downvolt your power to lv from your processing line, or build the same tier of fluid canner). So I would like to raise up some discussion for this.

**Comment by Prometheus0000** [comment]
My understanding is that the lower tier tanks simply extend the super tanks' code, but are smaller. So, I would say it's intended.

**Comment by noobnoobnub** [comment]
The capacity of the tank is not the point.
ulv tank is so easy to make that you probably spam it everywhere as energy-free super speed fluid canner.

**Comment by Glease** [comment]
No. It is not OP in any sense. It is merely a bandaid fix for a problem that simply shouldn't exist in the first place.

**Comment by GTNH-Colen** [comment]
Seriously we've devolved to the point where we're nerfing tanks?

**Comment by Ldmf** [comment]
the next is wood lol *ironie off*
tanks are fine as ther are i think

**Comment by quedral** [comment]
on contrary i say they need buff. lets make small tanks portable. :D

**Comment by Prometheus0000** [comment]
I think Alk said the portability was disabled for GTNH, so this would actually be possible.

**Comment by Extremity4** [comment]
We already have drums and EIO tanks for portability. There’s really no need.

**Comment by Prometheus0000** [comment]
I'm not saying we should, just that we could. You forgot large cells too.

**Comment by Extremity4** [comment]
Yeah, and buildcraft tanks.... there’s already a lot of options

**Comment by leagris** [comment]
Bit of history for those that don't know:
First there was IC2 cells, that were intentionally voiding when filling a container (tank) with it.

Then there was Gregtech-addon to IC2 that added recipes returning cells once emptied because voiding tin was not pleasing GregT who also patched some of cell handling by other tile tans like Railcraft to return empty cells.

Then came IC2-Experimental that changes cells, deprecating IC2 cells for universal cells that could contain arbitrary amount of fluid and be natively reusable, but not stack-able (due to NBT fluid and amount), and GregT reworking everything for GT4 and then GT5,

But unfortunately returning IC2 cells needed more and new patching.  In the mean-time he coded/re-coded machines entirely with no GUI access to fluid slots. So he added fluid canner to move fluid to and from internal tank from and to cells.

After this, he re-implemented Quantum tanks that dealt with canning un-canning on their own.

As for many aspects and features of GT5 machines, the canners were implemented not only as a replacement for IC2 canner, but as a work-around to questionable design choices and increasingly divergent implementations between IC2 and Gregtech.

The reason you have to use a canner are as stupid as that:

- Questionable IC2 cell mechanic design
- Questionable Gregtech5 machines interaction design
- Unability of authors of both mods, to agree on common design and the resultant forking away.

The canners are:
- Neither a QOL.
- Neither an engineered gameplay feature.
- Neither backed by balancing rules.

Canners are the bucket you place under a leaky roof when it rains.

**Comment by richardhendricks** [comment]
"Canners are the bucket you place under a leaky roof when it rains."
I want that on a cape.
