### ISSUE TITLE
HEE changes End biome bee settings, making bees harder

### ISSUE THREAD

**Issue by Ngar1** [GTNewHorizons/GT-New-Horizons-Modpack#6015]
#### Which modpack version are you using?
2083
#
#### If in multiplayer; On which server does this happen? 
myFTB
#
#### What did you try to do, and what did you expect to happen?
Changed  biomes with Terrestrial Focus End, Nether, desert
Change of hum/temp doesn't work at End (sky biome)
It works at Nether
![Thaumcraft_biome_change01](https://user-images.githubusercontent.com/7759876/80786373-b745c100-8b83-11ea-999a-e740b56d6e4b.JPG)
but not at Sky
![Thaumcraft_biome_change02](https://user-images.githubusercontent.com/7759876/80786439-f2e08b00-8b83-11ea-9103-2da5e5c62692.JPG)

**Comment by Glease** [comment]
1. We don't have 2093.
2. This is not an issue with witching gadgets. The problem is with HEE. It overrides the End biome. Changing its name into *Sky* while also setting its humidity and temperature to default, i.e. Normal/Normal. This will not block any bee from being breeded, as one can always work around this with an alveary, but it would greatly ease the bee breeding process and also fits in the original forestry theme.

**Comment by Dream-Master** [comment]
@Glease what was the climate in End before? (without HEE)

**Comment by Glease** [comment]
It should be Cold/Normal

**Comment by Ngar1** [comment]
corrected to 2.0.8.3

**Comment by Ngar1** [comment]
In my view, change temp/humidity of end-biome is a failure, because end biome is defined as cold.

**Comment by Prometheus0000** [comment]
That's true, but someone has to figure out where in the code it's changed to fix it.

**Comment by Prometheus0000** [comment]
I found that in https://github.com/GTNewHorizons/Hardcore-Ender-Expansion/blob/master/src/main/java/chylex/hee/world/DimensionOverride.java there's a class that appears to be overriding the default and changing it to sky. It also uses .setDisableRain();, which might be related to #5860 if it just makes it invisible like deserts instead of actually disabling it. I'm not sure where (or even if) it sets the bee stuff though. Maybe it just defaults to normal/normal unless you specify it? I know BoP biomes are set properly, so it should be possible to do that if we don't want to just cancel the override. There's presumably some reason it does that, but I can't tell.

**Comment by draknyte1** [comment]
Why not ask @Chylex?

**Comment by chylex** [comment]
```
BiomeGenBase.sky = new BiomeGenHardcoreEnd(9).setColor(8421631).setBiomeName("Sky").setDisableRain();
```
is exactly how vanilla defines the end biome in 1.7, the only thing HEE changes is override mob spawn lists, and prevent other mods from also changing the biome.

**Comment by chylex** [comment]
```
new BiomeGenEnd(9).setColor(8421631).setBiomeName("Sky").setDisableRain();
```
is exactly how vanilla defines the end biome in 1.7, the only thing HEE changes is override mob spawn lists, and prevent other mods from also changing the biome.

**Comment by Prometheus0000** [comment]
Then maybe forestry was changing it to add the bee temp/humidity?

**Comment by chylex** [comment]
Idk, changing every single vanilla biome to add a few properties sounds silly. The HEE version of the End biome has the same ID and base class, so it should be possible to identify it as the End.

**Comment by Glease** [comment]
I just loaded up an instance with only forestry+binnie+MB+NEI. It says the end is Normal/Normal. All bees that are *supposed* to inhabitat the end can be successfully brought up in the end only because they all comes with a natural tolerance of at least up 1 (cold+1 is normal). I have also cross checked 1.12 version and it is still normal/normal. So I must say I'm wrong here. It is by design, not a fault of HEE or anything. End bees are supposed to be breeded with tolerance and then brought to a better habitat (or use alveary) after that. Everyone here, especially chylex, should have my apology. 

Regarding this weird behavior, I'd say let's keep this behavior as-is, but we should leave a note in the quests for these end bees so an innocent person won't fall for this trap. Leave a note in *Nameless* and *Spectral* should be enough, as they are the common ancestor of every end bee species.

**Comment by Ngar1** [comment]
The reason for this issue was that the bees, they need for specialy comb products their orign enviroment. But if the normal enviroment in sky biome is ok, may be naquadria bee should work in that biome, but it doesen't. 
-> close this issue and reopen https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/6013?

**Comment by chochem** [comment]
its still about icy/arid for that jubilant state, not about the biome. you just need to create icy/arid conditions in a different way than using the end.

**Comment by leagris** [comment]
icy and arid → AE2 Dimensional Storage

**Comment by Dream-Master** [comment]
ok but it isnt a bug?

**Comment by Prometheus0000** [comment]
It's not a bug, it's just that there may be no natural biome that has the optimal/jubilant state for this/other bees. Which is rare, but still happens. There's probably a BoP biome that fits though.
