### ISSUE TITLE
Mystical bee config seems to be related to botania mod

### ISSUE THREAD

**Issue by Ngar1** [GTNewHorizons/GT-New-Horizons-Modpack#6094]
#### Which modpack version are you using?
2.0.8.3
#
#### If in multiplayer; On which server does this happen? 
myFTB.de
#
#### What did you try to do, and what did you expect to happen?
Mystical Bee wants a Mystical flower, but TC flowers don´t work (simmering, cinderperl), as some documentation say.
Dokumentation on FTB (https://ftb.gamepedia.com/Mystical_Bee) say, normal "Flowers" were needed, but if Botania mod is configured, than Mystical flowers needed from Botania.

![Mystical_bee_01](https://user-images.githubusercontent.com/7759876/81660509-21d7e600-943b-11ea-8fcf-ac4d7253fecb.JPG)
![Mystical_bee_02](https://user-images.githubusercontent.com/7759876/81660512-23a1a980-943b-11ea-9b4d-8ad16baaa7a5.JPG)

**Comment by Prometheus0000** [comment]
Botania and botany are different mods.

**Comment by Dream-Master** [comment]
another thing is we can change this in magic bees code if we want.

**Comment by Ngar1** [comment]
It would be nice, if TC Magic flowers work, it's better than normal flowers

**Comment by Ngar1** [comment]
Is this correction realy hard, that it has to be shifted every version? 
My suggestion was to relate that to TC Magic flowers, it's better than normal flowers. Botania seems to take more time to integrate, or?

**Comment by Prometheus0000** [comment]
Because it's at super low priority, and that's just something dream does to all open issues I think.

If you want it done, try doing it yourself?

**Comment by Ngar1** [comment]
The easy way would be to configure, that there is no botania mod - this can be done without any programming.
Programming is not my thing, sorry. I tried to study it, but after 3rd semester I sold my XT 4,77Mz PC and since I do only hardware ;-) (and now functional safety analyses).

**Comment by Dream-Master** [comment]
@Prometheus0000 sorry but u have a real life a family and a full-time job. I  can't spend the whole day on my computer fix and close issues. @Ngar1 but if this is only a config fix everyone with a little bit knowledge can make a github pr. If not it stay open so long somone will fix/change it.

**Comment by Dream-Master** [comment]
https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/blob/master/config/MagicBees.cfg#L94

Botania Mod is = false in this cfg

I need to dig deeper

**Comment by Ngar1** [comment]
no one else seems to be interested

**Comment by Graymare** [comment]
This issue is still present as of version 2.3.0.
There are two genes present that (assumingly) work off Botania flowers; Flower:Mystical and Flower: Mystical Flowers.  The second works correctly, the former does not - not with normal botania flowers, tall flowers, or planted petals. Thaumcraft flowers are also refused.  A Princess/Queen with Flower:Mystical is bricked and cannot work.  

I propose that the Mystical Bee (Noble x Monastic) genes be changed to Flower:Mystical Flowers so they actually function as intended.

**Comment by TangentTurner** [comment]
This issue is still in the code.
I was bored, and figured I'd package dive to find it.

Was able to find it using the scientific name from the apiarists database.
Botaniapis

The species is laid out in Binnie/extrabees/genetics/ExtraBeeBranchDefinition.java 
Line 343

Which points to ExtraBeesFlowers.java

No idea how to fix this, or do pull requests or any of that.

I think the issue is the intended dynamic nature of the bee, I think it's supposed to produce the same petals as are planted around it.
But I'm not used to reading minecraft code, so this is just a guess.

Just pointing this to another flower type would probably break that.

Leaving this here in case it saves time for someone in the future.
