### ISSUE TITLE
Ideas for loading tips

### ISSUE THREAD

**Issue by jackowski626** [GTNewHorizons/GT-New-Horizons-Modpack#6125]
Hello!
I would like to get some ideas for tips that will be displayed while the pack is loading. I'm looking for both, serious and funny ones but the first should prevail. Try to recall things you were upset no one told you before when you discovered them.
Edit: tips will be named after locale codes (fr_FR.txt would mean French tips. They don't have to match the English file at all) and editable in config. "#" acts as comment (only at beginning of line)

Edit: thank you very much for the tips so far +1
there is a line with credits now, with github unames. If you prefer another uname, or I have fogotten you, ping me on #github-discussion/#mod-dev

What I have for now [05/18/2020]:
https://github.com/GTNewHorizons/BetterLoadingScreen/blob/master/src/main/resources/assets/betterloadingscreen/tips/en_US.txt

**Comment by interestingusernam3** [comment]
Translocators can cause TPS lag. Avoid using them in large numbers.

**Comment by glowredman** [comment]
Protect your machines from rain.

**Comment by Nvidiot** [comment]
Mouse tweaks usage: https://www.curseforge.com/minecraft/mc-mods/mouse-tweaks

**Comment by GTNH-Afx237v7** [comment]
Build multiblocks within the same chunk
You will lose your first piece of aluminium dust in the EBF

**Comment by boubou19** [comment]
Transvector interface helps you expand available sides for automating a block.
Lava bucket will burn you if you don't wear gloves.
Steam output from bronze machine or within pipes can harm you.
You can apply fortune to brittle charcoal if you use the Charcoal Pile Igniter.

**Comment by leagris** [comment]
> Transvector interface helps you expand available sides for automating a block.

Use a Machine Hull/Casing block, and it will feed power, fluid and item all taking a single side. Similar use if you want to extract fluid and items from a single side.

Why reinvent the wheel when at the fortunate too rare times Gregtech machines provides a service rather than fixing artificial problems created by Gregtech iteself like canners, food slicers, microwave oven...

**Comment by boubou19** [comment]
> Use a Machine Hull/Casing block, and it will feed power, fluid and item all taking a single side. Similar use if you want to extract fluid and items from a single side.

There are some edge cases where you can't use machine hulls if you want to make compact setups. Transvector interfaces cover those edge cases. But i do agree that the use of machine hulls is not well spread.

**Comment by yukieiji** [comment]
Please pay attention to Voltage and Amperage of cable/Machine, otherwise you may suffer a lot of damage!
Warp is so dangerous, it can destroy your base.
Voltage Tiers have 16 tiers from ULV(8V) to MAX(2147483647V).
Each time one tier is raised, Voltage required quadruples.
Currently (ver 2.0.9.0), 10 tiers from ULV(8V) to UV(524288V) are fully implemented, UHV(2097152V) and UEV(8388608V) are partially implemented, and the remaining 4 tiers are under development.

**Comment by glowredman** [comment]
Empty your Backpacks, when upgrading them, otherwise you'll have a bad day...

**Comment by chochem** [comment]
- Take your time to read the quest book, it explains many mechanics and offers more helpful hints and tricks.
- NEI has its own options menu with useful keybindings for bookmarks and other things.
- If it looks like an item does not have a recipe, it might be locked by Thaumcraft research.

**Comment by GTNH-Afx237v7** [comment]
It’s NEI, not JEI. Use it frequently.

**Comment by richardhendricks** [comment]
@jackowski626 Sounds like a great idea. There are a bunch of quotes collected from the Discord in the Readme

https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/blob/master/README.md

Some additional ones

Your pick is not ready
Put the "Mine" back in Minecraft

**Comment by Regian24** [comment]
Some more I wrote because I was bored:

If a fluid cell doesn't work, try using a fluid canner
Use /xu_tps to see if the server's lagging. 20 TPS is normal!
Use an elevator to get in your cleanroom, so you won't lose cleanliness!
If you aren't lucky enough, try enchanting your lootbags with Fortune III!
You can't enter the Twilight Forest without Quick And Dirty Portal Generator
Don't give a machine a higher voltage than it can handle. It will explode!
Press T while hovering on an item in NEI to see where is it in your world.
Using a circuit assembler will make circuits cheaper!
Using a cleanroom will make circuits even cheaper!
GT stands for Grind and Tedium
Don't go out at night! Mobs can have up to 300 HP
Steam is hot! It will burn wooden fluid pipes
Don't break rubber trees without a treetap
Make Muffler Moint Mup (Point up.)
Your EBF won't work if the muffler doesn't point to the sky!
Beware of pollution! 
Eating too many of the same food will make you hate it
Remember to check if there are Natura clouds when you launch a rocket!
Abandon all vanilla knowledge all ye who enter here
With the power of Duct Tape, I solved all of your maintenance problems!
When you open a Twilight Portal, you'll get hit by lightning
Sometimes it's better to flee than fight some mobs
You can power machines by putting a battery in their Energy slot
You can charge your jetpack by putting it in the Energy slot of LV machines
Be prepared to take hours to craft a single machine

**Comment by Regian24** [comment]
**I made more loading screen tips, cuz you guys seem to like it** 

--------------------------
Oil + Thunder = Fire. Remember to put cobblestone over your oil wells!
Nuclear Reactor configs give 20x the energy they give in IC2!
Remember to plant cotton - you'll need a ton of it
It's aluminIum, not aluminum
Many ingots can only be smelted in the Electric Blast Furnace
Multiblocks can share walls! 
Use F7 to see spots where mobs can spawn!
Use F9 to see chunk borders!
Need seed oil for forestry? Plant some peanuts
Microcrafting is love, microcrafting is life
Meta-Tip! You can see the list of loading screen tips in the config

**Comment by botn365** [comment]
reactors is 10x

**Comment by 0lafe** [comment]
'If it's too tedious you're doing it wrong'
'do you also watch your oven when baking food?'
'theres always something else you can do while you wait'

**Comment by Regian24** [comment]
Remember to automate your machines
Keep your blast furnaces running at all times!
If the pollution's too high, you can always try moving your machine

**Comment by jackowski626** [comment]
if dream says to jump in front of the bus, we jump in front of the bus - DoomSquirter

**Comment by Dream-Master** [comment]
Don't worry if we jump all together we will stop the bus because we are many!

**Comment by DoomSquirter** [comment]
great, we get to explore the trolley problem in gtnh.  fun times.

**Comment by PoroCoco** [comment]
You can open GregTech cover's GUI by Shift Right clicking them

**Comment by PoroCoco** [comment]
Right clicking the NEI/AE2 search bar remove the text
