### ISSUE TITLE
[Liquids Generate]Lack of liquid on planets

### ISSUE THREAD

**Issue by MotiasF33** [GTNewHorizons/GT-New-Horizons-Modpack#6147]
#### Which modpack version are you using?
2.0.8.3
#
#### If in multiplayer; On which server does this happen? 
eta.gtnewhorizons.com
### Flaw of liquid on planets:
Ross128ba - all liquids is missing
Vega B - missing  is naquadria luquid
Barnada c - all liquids is missing

**Comment by Prometheus0000** [comment]
Vega B naquadah/naquadria was removed (not sure what version). They were also changed recently. Also, not all planets have liquids underground.

**Comment by MotiasF33** [comment]
> 
> 
> Vega B naquadah/naquadria was removed (not sure what version). They were also changed recently. Also, not all planets have liquids underground.

I was guided by description in "Saltwater and Chlorbenzene on Mars" quest
![изображение](https://user-images.githubusercontent.com/47714084/82734759-b2f56980-9d25-11ea-90d8-40b4d615a1a2.png)

**Comment by chochem** [comment]
the naquadria is a duplicate issue and already fixed (the quests is fixed). check https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/5875

dont know about Ross128ba, but you version is pretty old, so this would at least need checking by someone on 8.8. Testing it in the beta is sadly impossible at the moment due to a unrelated bug.

**Comment by mitchej123** [comment]
Please check on a more recent version, a lot of this has been addressed.
