### ISSUE TITLE
teleposer dupe and broke gt blocks

### ISSUE THREAD

**Issue by DarkGaterau** [GTNewHorizons/GT-New-Horizons-Modpack#6186]
#### Which modpack version are you using?
2.0.8.3
#
#### If in multiplayer; On which server does this happen? 
ETA
#
#### What did you try to do, and what did you expect to happen?
telepose 7x7x7 miner from A to B
#
#### What happened instead? (Attach screenshots if needed)
compressed chest dupe(try other chest dupe only compressed), also gt blocks broke (batt buffer whith battery) and on B point they be .name 
#

**Comment by 0lafe** [comment]
How did the batt dupe play out? Also is the .name all of the tile entities from GT? Do they now have the undefined texture? If so you can fix that by unloading/reloading chunks usually. Same issue with AE spatial

**Comment by DarkGaterau** [comment]
broke when teleporting, I think. pull out of the block failed
![image](https://user-images.githubusercontent.com/52930644/83362026-1e32e180-a39f-11ea-84b4-c6a712a42fcd.png)

**Comment by 0lafe** [comment]
Yea that one seems to happen when tile entities are moved with some teleporters. If you're doing manual mining with it, just teleport it to the dim, then unload/reload the chunk it's in. It's not super convenient but it's easy enough to work around

The batteries are probably gone tho. At least with spatial IO, it'll delete the contents of the inventories of GT blocks. If you're doing miners I'd just suggest not giving them batteries due to this

**Comment by Prometheus0000** [comment]
There's a blacklist, so the chest can be added to it. A note should also be added to the teleposer quest telling people not to do this (there's one on the spatial quest).

**Comment by GTNH-Colen** [comment]
How many times do people need to be warned not to teleport modded blocks? It seldom ends well...

**Comment by boubou19** [comment]
idk what has been blacklisted yet, but if it can dupe the content of whatever block that keeps its inventory when broken, then eio machines, compressed chest and infinity chest must be blacklisted. (there may be others blocks, but that's all i can think of)

**Comment by Prometheus0000** [comment]
It's in the AWWayofTime.cfg file. Did you test all of the ones you mentioned? Also @DarkGaterau you didn't mention how the dupe occurred? Was there a compressed chest on the sending and receiving side?

I wonder if we can simply specify all GT blocks with a wildcard?

"teleposer blacklist" {
    # Stops specified blocks from being teleposed. Put entries on new lines. Valid syntax is: 
    # modid:blockname:meta
    S:Blacklist <
        minecraft:bedrock
        minecraft:end_portal
        minecraft:end_portal_frame
        HardcoreEnderExpansion:transport_beacon
        Thaumcraft:blockPortalEldritch
        Thaumcraft:blockEldritchNothing
        ThaumicHorizons:vortexTH
        appliedenergistics2:tile.BlockMatrixFrame
     >
}

**Comment by boubou19** [comment]
i did not test it but it looks similar to another duplication glitch (involving drawbridge, this is why they are disabled) So if it is works like this, you can dupe many things (item, fluid and even energy). Blacklisting the ones i mentionned should reduce drastically the way to abuse the dupe glitch.

**Comment by Prometheus0000** [comment]
It looks like it's just avaritia, since the draconic chest and the EIO machine I tested worked fine.
The dupe bug also only dupes the chest, not the contents, with the chest both being teleported, and popping off at the sending teleposer.

avaritiaddons:CompressedChest
avaritiaddons:InfinityChest

Both need to be added.
