### ISSUE TITLE
Proposal: Super Input/Output Hatch for Multiblocks

### ISSUE THREAD

**Issue by Aggadahr** [GTNewHorizons/GT-New-Horizons-Modpack#6209]
#### Which modpack version are you using?
2.0.8.3
#

#### What do you suggest instead/what changes do you propose?
There is the Super Input Bus, which is pricey, but super useful and very worth the cost.
The super bus adds a lot more capacity, can have items extracted and works extremely well with parallel processing multiblocks.

The regular input hatch is somewhat limited, both in capacity and flexibility, just like the regular input bus.
So I propose a complementary to the super bus, the super input/output hatch

The Super Hatch i have in mind:
 - can hold multiple fluid types at once (maybe increasingly more on higher tiers) 
 - can have fluids extracted (like the Super input Bus)
 - has higher capacity than the regular input/output hatch 
 - maybe has some kind of priority system, so that players can decide which fluid is used with 
    priority
 - a mechanism that prevents multiple slots getting filled with the same fluid type, because that 
    would just end up in summed up capacity and a bunch of practicability issues
 - the option to lock fluid types to certain slots, just like regular output hatches can be 
    locked to a certain fluid

The uses for such a Super Hatch seem endless to me, i leave the crafting cost to the balancing experts but in my opinion something like that should be available at IV+

**Comment by 0lafe** [comment]
Personally I've always been against multi fluid hatches. Due to the limitations of a single fluid, we end up with some semi complex logistics needed for fluid swapping in many multis. Being able to just dump all your fluids in the same hatch makes fluids about as interesting as items, which would be really sad to see. Makes things like multi fluid ebfs trivial, and increases simplistic chem automation effectiveness drastically. I'm not a fan of benefitting setups this simple, while essentially removing the bonuses of creating larger logistical systems to handle these fluids. 

I'm fairly sure you are able to pull from current fluid hatches, I've had to do it a handful of times with success. 

Larger input seems to fit with the rest, but it's not really that impactful. If they're IV+ I'm not sure how much use that would have alone. Personally I'd really like to avoid multiple fluids in the same hatch, so adding a hatch that's just larger doesn't seem super impactful. You can always feed hatches with cells/flasks/tanks/etc to get what is essentially an infinite storage in every hatch. 

In all I'm not a fan of mechanics that are seemingly QoL additions around lategame item/fluid handling. As it stands we really don't do as much as we should enforcing it, and this seems like a large step in the wrong direction.

**Comment by Prometheus0000** [comment]
You can (usually) just add another input hatch?
