### ISSUE TITLE
[Suggestion]Add very small tank to automation of crafts using cells.

### ISSUE THREAD

**Issue by yukieiji** [GTNewHorizons/GT-New-Horizons-Modpack#6212]
#### Which modpack version are you using?
2.0.9.0-RC2

#
#### What do you suggest instead/what changes do you propose?
Currently, when building automatic processing or crafting equipment using cells, it is necessary to temporarily store fluid in a tank and fill the cells with the fluid. at that point, the primary fluid stored is at least 16,000L(Ender IO Fluid Tank), and even if you need 1000L for a single cell, I feel that's a lot of waste.
Also, a large number of cells are needed to improve efficiency with stockkeeper and other tools.

So I would suggest adding a very small capacity tanks to automation of crafts using cells.

My suggested tank specs are as follows:
- Tiny tank:capacity 144L
- Small tank:capacity 1000L
- Both tanks have a output slot that item stackable count of 1

**Comment by Prometheus0000** [comment]
Check out the quest for the fluid interface. You can also use volumetric flasks.

**Comment by yukieiji** [comment]
Automatic crafting can be automated with Fluid Interface, but I think automated processing equipment such as Formic Acid requires a temporary tank to fill the cell with Fluid.
Volumetric flasks are useful for liquid transport, but they have no use in automatic processing equipment because of their cell.

**Comment by yukieiji** [comment]
When using the stock keeper to create an automated machining facility that uses cells, the output A large number of cells are needed as cells are filled until the slots are full(as shown in the image.). That means there could be wasted cell stocks and Fluids.
![2020-06-06_21 37 32](https://user-images.githubusercontent.com/40425798/83944420-4fe3f680-a83e-11ea-96c7-6f6a213251f7.png)

**Comment by Prometheus0000** [comment]
I don't fully understand what you mean, but you do know you can order a craft of a filled cell and then store it in AE, right? You can then send it to a machine in a recipe as an item, and empty it at the destination, even if it's not into a hatch. And you can set VFs to 144l, perfect for recipes. I also don't know why you would expressly want to use cells instead of fluids directly. You can just empty them at the destination in a super tank with a pump next to the input hatch. You can ask Olafe about using VFs in autocrafting, it definitely works. You can also use larger cells too if that would help.

It looks like you're using projectred? I don't use that, maybe if you used AE instead you wouldn't have this problem?

**Comment by yukieiji** [comment]
For example epoxy, I think that you will build an automated processing facility to craft an epoxy instead of all the processes up to epoxy are registered in the AE2 order, one by one. You would need to fill the cells with Fluid to do that, right?
I've given ProjectRed as a clear example, but I think it will happen even if you don't use it.

**Comment by Prometheus0000** [comment]
You can use an LCR that will run when the levels (determined by a fluid detector cover on primary epoxid storage) get low, with automatic sending of fluids to it, or send the filled cells and empty them into hatches or super tanks next to it, or send the fluids with a fluid interface (it sends multiple). If you use the fluid interface, no cells are used. EC2 is kinda buggy though, and I haven't done it much myself, so I suggested someone who knows more.

About the LCR auto-running, there's a wiki article too, but you can also send the RS from farther away, and also use shutters or machine controllers instead.

**Comment by yukieiji** [comment]
I don't like that kind of automated processing equipment because of the increased channels(Interface and Level) and the lag caused by switching between channels.
The lag caused by channel switching will increase, especially as the network becomes larger(such as using P2P)

AE2 is great for "auto-craft" and "storage", but what you need when building an automated processing facility is "logistics", and I think ProjectRed and GregTech is better at that.

**Comment by GTNH-Afx237v7** [comment]
Although I haven’t used it yet, maybe you want to check out 0lafe‘s video about LCR automation.
https://m.youtube.com/watch?v=CGPWCnDKxZU

**Comment by Prometheus0000** [comment]
Have you tried the TFFT? You can store 25 different fluids, with auto-voiding when full, and pull out any/all of them through the special hatch which is compatible with conduits and fluid storage busses.

I've never experienced lag with AE2, but I have heard about it, but I don't think 'channel switching' is a thing. That's not how they work, they either have a channel or not.

And back to the thing you want, I don't see the difference between a 144l tank and using a VF set to 144l? Not to mention you can't use that tank with cells anyway, since it's not 1000l. And a universal cell would just sit in it until you used all the fluid (or refuse to empty, I'm not sure). So you'd be using VFs anyway.

**Comment by yukieiji** [comment]
>Although I haven’t used it yet, maybe you want to check out 0lafe‘s video about LCR automation.
https://m.youtube.com/watch?v=CGPWCnDKxZU

It's great, but I don't think it will work on automated machining equipment because it only works on the AE2 order where the blocking mode works.

This tank I am suggesting is a no-waste tank that makes it easy to fill the cells with fluid. Since the amount of fluid in the tank is minimal, the tank can be refilled with a minimum of cells and without RS circuits, reducing wasteful processing. It has a different use than a flask.

**Comment by Prometheus0000** [comment]
> automated machining equipment
I have no idea what this is.

Where are you storing your fluid? A tank perhaps? Send the cell or flask to it, and then get it back, problem solved. You can probably fluid interface into a ULV tank to fill a cell/flask too if you store it in AE.

**Comment by yukieiji** [comment]
Here's what it says in the text
"at that point, the primary fluid stored is at least 16,000L(Ender IO Fluid Tank), and even if you need 1000L for a single cell, I feel that's a lot of waste. Also, a large number of cells are needed to improve efficiency with stockkeeper and other tools."

**Comment by Prometheus0000** [comment]
Send a flask? Like I suggested?
