### ISSUE TITLE
Nerf Ic2 crops

### ISSUE THREAD

**Issue by redmage17** [GTNewHorizons/GT-New-Horizons-Modpack#6238]
They take less rng than bees at the moment, have a  far lower technology requirement for infrastructure, and you can produce things like UU-matter. It makes no sense that bees have been nerfed to oblivion yet ic2 crops have been left untouched. 

Bring up the tech and energy requirements for the replicators, lower the mutation rate of crossbreeding, and lower their productivity.

**Comment by SampsaxD** [comment]
Replicators are already a fairly miniscule part of crops power, mutation rate doesn't matter at all, you would just make larger fields/play whack a mole for longer, and lowering productivity would just mean spamming even more crops.

Why not buff bees instead?

**Comment by redmage17** [comment]
> 
> 
> Replicators are already a fairly miniscule part of crops power, mutation rate doesn't matter at all, you would just make larger fields/play whack a mole for longer, and lowering productivity would just mean spamming even more crops.
> 
> Why not buff bees instead?

We don't buff things in GTNH only nerf

**Comment by ScriptedPiky** [comment]
Bees I feel like should be re-evaluated, as many of their bees often have very specific and or tedious conditions to properly get, as well as attempting to gain their specific products (often requiring certain biomes). In addition, some of them have extremely silly expensive autoclaving requirements comparably to their crop alternatives (Thorium Combs vs Thorium Leaves; one requiring IV voltage while the other requires the same 6000~ seconds but at a very lower-tier comparably).

My guess would be to instead to see what is causing bees to be frowned upon majorly and buff areas most necessary. However, some key points with bees and crops are that with crops, you can generally have a decent biome and stay in there if desired for crops. You can use Witchery to get the best possible humidity biome or if you're lucky enough, you may stumble across it. Although, for bees, you need a variety of things and biomes to ensure your bees work. Sometimes, the biomes required are VERY specific and may only require exactly one type of biome to get the perfect stats. This doesn't apply to every bee, but a good portion of the higher tiered bees require absurdly specific biomes that either, you use Witchery extensively to get the biome and using Aleaveries, or you go search for said biomes (sometimes you might not find the right one within 10k or even further distance!).

And as Sampsa said, if you lowered the mutation rate and productivity, people would just spam more to solve the problem. Especially for crops since a lower mutation rate wouldn't matter all that much in the end if I have fifty stickreeds to get the same RNG product, if not faster than before. A great example of this was the UUM replicator nerf, people like me and Sampsa just spammed more UUM production (Transformium berries for Samp and Mass Fabricators for me) to solve the problem.

**Comment by Dream-Master** [comment]
so time for make uum more expensive or remove replication completely

**Comment by Methes** [comment]
That's exactly what NOT to take from Piky's post.
First decide whether crops are at a good spot. Do they take a fair amount of work (breeding, getting the stats, spreading, moving)? Do they need specific conditions player can tinker with (height, light, dirt, biome, water, nutrition)? Are the care taking units in a good spot (forestry multifarm, cropmatron)? Is processing the outputs in a good spot?
Finally taking all of the above in equation, you should ask:
How does it compare to mining? Mining should be better, but the difference should be not huge to not make crops obsolete comparing the time and effort investment.
Now I don't know crops that well so Sampsa/Piky would have to provide their experience, but that's what we should strive for imho.

After you've considered that THAN you can start comparing crops vs bees as you'd have a baseline of productivity (crops) and can alter bees to get similar results.

Consider bees have:
Worse amount scaling - need pristine princess, need expensive housing in comparison to another cropsticks in a farm
Similar breeding - can be upgraded with machines
Varied ideal conditions - crops have all the same except light level
Sometimes atrocious production rates - even more prominent with bad scalability
Sometimes ridiculous processing demands - energy demands too high in fear of energy positivity (like why? So what?) plus even lowering the chances of outputs (infinity bee requiring thousands of cycles to get one tiny pile or similar?)
More performance issues - be it bee particles or bees&leaves interaction with butterflies

All bees need are improved production rates with a lot lowered processing costs, so that they're worth it in similar scale to crops.

**Comment by mrTeroblaze** [comment]
Crops are not a reliable source of almost everything (except some stuff) so lets nerf them even more. Good idea (no)

**Comment by ScriptedPiky** [comment]
Heh, that is a lot better than my response. But to put in experience (Sampsa knows a lot more, however, I did help him out) of crops overall, the trend of going from nothing to something starts off from breeding Stickreed from Reeds or another random crop, producing a large 'breeding field' of crops, then getting a 23/31/X related crop. Once there, you set up a field of average 23/31/X crops, then you start breeding around **40%** of the **entire** crop pool. Quite literally Stickreeds unlock the majority of the crops that you need to progress.

Finding or creating the right biome (there are around three or four biomes that support 100% humidity and only a singular biome that supports 120%, while there are many biomes that support 50-90% humidity) is also necessary for high demand processing crops. While someone may land in a 50% humidity biome, they can still progress and obtain crops at a decent, albeit slower rate.

However, the one thing that crops do require is a lot of patience, time, and babysitting until the final product.

Finally, some crops are arguably way more overpowered than others. Stonelily crops are no exception, as many of them produce insanity amounts from a single harvest (assuming max stats and good RNG). Although, many other crops are simply fine as is or are slightly underpowered. @SampsaxD You got any thoughts on comparing crops?

**Comment by SampsaxD** [comment]
Refer to [this sheet](https://docs.google.com/spreadsheets/d/1meLI4LofCBCAdMEg1niruNoQP8oBw_ILAMIINCHFG9g/edit#gid=0) for most of the important stuff the crops can produce.

Currently crops are inferior to just mining, although they can augment mining by being able to quadruple most ores. Relying 100% on crops for resources is generally harder, worse and more tedious than just mining the ores using the various autominers, but it _can_ be done, which is a good thing, because shoehorning everyone to just mining everything isn't that great either.

The problem isn't crops being too good, it's the bees being way overnerfed. UUM in general has nothing to do with this; Maybe for fairness we could add a UUM/UUA bee too, so both ways have that as an incentive to invest time into.

Replication deserves its own discussion, although my opinion is that it's a good addition to the resource game of the pack. The biggest problem with replication currently is the lack of alternatives: Buff those, and people will stop "abusing" replication.

**Comment by 0lafe** [comment]
The tier of the replicator should relate to the tier of the material.

**Comment by Prometheus0000** [comment]
I would think that people would use crops more for multiplying than replication if you aren't doing a no-rocket run. And non-mineral crops like enderblooms can't be used for that obviously.

**Comment by redmage17** [comment]
Isn't it great

> 
> 
> That's exactly what NOT to take from Piky's post.
> First decide whether crops are at a good spot. Do they take a fair amount of work (breeding, getting the stats, spreading, moving)? Do they need specific conditions player can tinker with (height, light, dirt, biome, water, nutrition)? Are the care taking units in a good spot (forestry multifarm, cropmatron)? Is processing the outputs in a good spot?
> Finally taking all of the above in equation, you should ask:
> How does it compare to mining? Mining should be better, but the difference should be not huge to not make crops obsolete comparing the time and effort investment.
> Now I don't know crops that well so Sampsa/Piky would have to provide their experience, but that's what we should strive for imho.
> 
> After you've considered that THAN you can start comparing crops vs bees as you'd have a baseline of productivity (crops) and can alter bees to get similar results.
> 
> Consider bees have:
> Worse amount scaling - need pristine princess, need expensive housing in comparison to another cropsticks in a farm
> Similar breeding - can be upgraded with machines
> Varied ideal conditions - crops have all the same except light level
> Sometimes atrocious production rates - even more prominent with bad scalability
> Sometimes ridiculous processing demands - energy demands too high in fear of energy positivity (like why? So what?) plus even lowering the chances of outputs (infinity bee requiring thousands of cycles to get one tiny pile or similar?)
> More performance issues - be it bee particles or bees&leaves interaction with butterflies
> 
> All bees need are improved production rates with a lot lowered processing costs, so that they're worth it in similar scale to crops.

But this would require effort and god forbid them buffing something in the name of balance! Instead let's nerf UU which no one asked for

**Comment by redmage17** [comment]
You have to reach zpm to use Gendustry which makes bees viable. Binnie's sucks ass as is. It is slow so slow. You have to breed an alveary to use it. Plus the thousands of other steps to get good bees. Ic2 crops you hit hv make a bunch of crop sticks and you are good to go. Made my initial comment out of spite because I figured gimping something would get more attention than ask for a buff and who would've guessed?
