### ISSUE TITLE
Change recipe for Unattuned Node Matrix

### ISSUE THREAD

**Issue by redmage17** [GTNewHorizons/GT-New-Horizons-Modpack#6316]
Recipe  for unattuned node matrix recipe got changed in the most recent release 2.0.9.0. It was changed from a  cheap arcane crafting recipe to an infusion recipe. I really don't have an issue with the nerf but it does not fit thematically. 

Currently it requires an energy crystal, and advanced circuit, some forbidden magic shards. For essential it requires 30 lucrum, 30 luxia, and 40 perfodio. With a jar at the center. 

I would change it to a infusion recipe with an energy crystal at it's center. 3 desidia shards, 3 balanced shards, and for essentia 16 dessidia, 16 superbia, 32 auram and 64 pracentio. I will PR it just want to get the go ahead first.

**Comment by psuemno** [comment]
Why not just change it back to what it was before? Even what you've suggested seems expensive given to me considering what it gets you and the alternatives.

If I need a small node for something, I can easily find something suitable just sitting out in the overworld. Maybe if I needed just a few cVis and was feeling anal about having it only have the aspects I want then I might consider making one from a node matrix, but if the recipe is more expensive then why bother?
If I need a large node, making one from scratch already has substantial costs in that it gives tons of warp. It doesn't need more of an upfront crafting cost. And there are alternatives like bees or even vanilla node bullying that I could use instead if I really wanted.

**Comment by redmage17** [comment]
You new? We don't buff things here. Otherwise  I would.

**Comment by psuemno** [comment]
I'm not new, but I am vehemently against the practice of arbitrarily making things harder for no reason. It's stupid and I think does this pack no favors, so even if it is just for some stupid niche item that barely anyone uses I will push back against it. 

If you have some reason why this recipe ought to be harder, then fine. Lets hear the logic and if it's good, I'll agree to it. I've laid out my logic as to why a cheap recipe for this item is fair and reasonable: there are free alternatives out in the overworld and it already has it's own unique cost in the form of warp. A more expensive recipe is unnecessary.

Based on what I've read in other discussion forums, this change was not even an intentional stealth nerf but a complete accident. It wasn't supposed to happen at all and should not be an invitation to muck around with the recipe further. The correct fix for this is to just change it back.

**Comment by mitchej123** [comment]
It was intended to happen 2 years ago but was accidently never shipped.

**Comment by mitchej123** [comment]
https://github.com/GTNewHorizons/Nodal-Mechanics/pull/1

**Comment by redmage17** [comment]
Update in this PR https://github.com/GTNewHorizons/Nodal-Mechanics/pull/4#event-3489570287
