### ISSUE TITLE
[ExtraCells] ME Fluid Interface

### ISSUE THREAD

**Issue by MotiasF33** [GTNewHorizons/GT-New-Horizons-Modpack#6324]
#### Which modpack version are you using?
2.0.9.0QF4
#
#### If in multiplayer; On which server does this happen? 
Eta
#
### When you try auto-crafting with a ME fluid interface, the interface deletes items.
How it works:
You are ordering a recipe;
ME Liquid interface loads liquids and items into hatch/bus;
If in 1 operation we transfer> 2^3 items, items above > are deleted.
#

**Comment by boubou19** [comment]
use a compressed chest as buffer and you are good, but this has been annoying me a few times

**Comment by MotiasF33** [comment]
> 
> 
> use a compressed chest as buffer and you are good, but this has been annoying me a few times

it removes in any buffer

**Comment by boubou19** [comment]
ok so i ordered 10 nanoCPU wafers through an extracells fluid interface, here is the recipe:
![image](https://user-images.githubusercontent.com/12850933/85434886-fc381380-b586-11ea-9670-4d342fc7942e.png)
I got all the ordered nanoCPU wafers. Here is my setup:
![image](https://user-images.githubusercontent.com/12850933/85435091-45886300-b587-11ea-85d6-3929c84787f7.png)

I'm playing on 2.0.9.0 QF4 (Delta). Can you tell me what recipe you tried to make? that way i could test it in my base.

**Comment by MotiasF33** [comment]
> 
> 
> ok so i ordered 10 nanoCPU wafers through an extracells fluid interface, here is the recipe:
> ![image](https://user-images.githubusercontent.com/12850933/85434886-fc381380-b586-11ea-9670-4d342fc7942e.png)
> I got all the ordered nanoCPU wafers. Here is my setup:
> ![image](https://user-images.githubusercontent.com/12850933/85435091-45886300-b587-11ea-85d6-3929c84787f7.png)
> 
> I'm playing on 2.0.9.0 QF4 (Delta). Can you tell me what recipe you tried to make? that way i could test it in my base.

i'm trying circuit boards
![изображение](https://user-images.githubusercontent.com/47714084/85436786-42df3b00-b592-11ea-8184-f22a7be7af7f.png)

**Comment by boubou19** [comment]
i tried both iron III chlorine version and sodium persulfate version, both worked: i got my 10 elite circuit boards each time. I am using these recipes in a LCR, and that ignores the cleanroom requirements. If you use the single block chemical reactor, check if the cleanroom has 100% efficiency.

**Comment by zgggz** [comment]
To avoid it use flat version of interface. It work fine.

**Comment by boubou19** [comment]
i use the block version and i have no problem

**Comment by MotiasF33** [comment]
> 
> 
> To avoid it use flat version of interface. It work fine.

i use block version too

**Comment by Devtron3D** [comment]
![image](https://user-images.githubusercontent.com/3405825/85922021-ad3cf780-b880-11ea-9a50-c061c1fdc6b8.png)
I just did a test and ran into the same issue, this is a single version test of the error
Order up raw carbon with the me system, fluids are put into the hatch and items into the bus, it voids the items when the bus is full.
First observed today on prospercraft after the server update.

[New World001.zip](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/4840501/New.World001.zip)
[New World002.zip](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/4840502/New.World002.zip)
[New World003.zip](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/4840503/New.World003.zip)
Here is a single player world map with the issues and just the basic setup to recreate it
Just feed carbon dust and polyethlene into the me system and start an autocraft with raw carbon

**Comment by Devtron3D** [comment]
Addon for this.
Made sure to not craft big orders, and i did not have any issues, just made a giant order and it happened again as it over flowed.
I manually filled the input bus this time to drain the hatch of the remaning  fluid. and it started to auto fill the dust again, IF it has fluids to input also.
So it looks like it is linked to the fluid input in the recipi, if there is more fluid to input and the input hatch could not hold more, when it starts to fill it again, it activated the input of carbon also.
As soon as it stops inputting more fluids, it stops with the carbon dust again. so they are linked somehow.

**Comment by boubou19** [comment]
does it happen if you put a tank next to the interface as intermediate fluid buffer?

**Comment by Prometheus0000** [comment]
When I was testing the fluid interface I used a machine hull as a buffer and didn't have any problems with big orders using a PA. Try seeing if that helps.

**Comment by Devtron3D** [comment]
![image](https://user-images.githubusercontent.com/3405825/86589654-56c16e80-bf8e-11ea-9571-573411e7c85b.png)
This is more or less the only thing that works for me, a buffer chest for items

**Comment by boubou19** [comment]
maybe it is related to the bandwith of the EIO ender fluid conduits, iirc they are limited to 200mb/t.

**Comment by Devtron3D** [comment]
Well ender io ones i can also use, but they are to slow with fluids, have them working like this on another setup
The problem is the items not the fluids, as if the input bus gets full it will void items.
As said before, if the hatch is full of fluid and the crafting recipe uses a bit of the fluid it will put more items in as well as fluid, but i had to first manually add items to do that, and it still voided a lot of item. only items get voided

**Comment by Devtron3D** [comment]
ok, I just did a few tests, it also voids fluids
So when crafting multiple recipies, it will deposit the items, but void the fluids if inputting two recipies.
I dont know if they are stuck in the fluid interface as the items are, but it stops outputting when the device it is inputting into gets full

**Comment by Devtron3D** [comment]
Extra Cells
-Fix fluid interface dupe
-This dupe issue will happen when you attach two or more tanks 
-to the same fluid interface and the fluid interface pushes some fluid as in some pattern
-Note to future programmers: this pushItems() logic is not as clean as it can be and can push 
-1 stack per tick whereas vanilla can push all stacks at the same tick.
-Update zh_CN.lang
-gradle updated
-backported Oredictionary Export Bus extended pattern matching
-updated ThaumicEnergistics integration

Figure the bug we have has something to due with fixing the dup issue ?

**Comment by Glease** [comment]
The aforementioned setup (raw carbon fibre) is no longer voiding any items in latest dev. I'd say Skiftcha's fix probably have fixed this one.

**Comment by Skiftcha** [comment]
this is already in 2.1.0.0

**Comment by Glease** [comment]
Then it ought to be closed.

**Comment by Devtron3D** [comment]
This is not fixed in 2.1 and has been verified to still be broken.
Do this, the setup I showed before in this issues, make the PA have a UV input hatch and lv input bus
fill the input hatch with 8.000 mb polyethene, and then have the crafter still use fluid crafting.
The fact that the input hatch is full means the fluid interface cant output fluid, it will try to output first, if it is unable, it won't output items, in this case, the carbon dust.

**Comment by Glease** [comment]
I still cannot see any **voiding**. They are indeed not visible in ME terminal, but they won't go away. Once you resolved the filled tank problem the item will be pushed out just as usual.

**Comment by Devtron3D** [comment]
It is not voiding the material per say, but it cannot output it cause the hatch is full of fluid, And you can lose a lot of material depending on how you stop the order (been a while since I did this, but I lost like 100k carbon dust this way)

Can you add an IF check to it so it checks if fluid is full is are there any items to push and is there room.
Atm once you start ordering larger orders it will stop running, the only way you can fix it, is either drain the fluid from the hatch and make a smaller order, or manually add items to make the machine craft what it should..

This becomes a problem early on fast, one of the first thing I see it on as you need a lot of it is raw carbon, think also there are some LCR recipes where you use glowstone where it becomes an issue also.

For me, it becomes a problem to use fluid interfaces this way early into getting AE, and I stop using them and use some other converluted way to fix it, like a supertank that empties cells that then pump it into the hatch.
While that is a valid option, it increases the steps needed, and you need to match cells/flasks, to get it to work right, and I know for a fact if you need 10k cells for an order and you monitor for lag, that 10k cells trough a super tank will show up on opis.

But as I said, atm fluid interfaces are unusable with larger orders, as they get stuck due to items not pushing when the fluid output is full. Even using a barrel or compressed chest with the raw carbon fiber (I did this) my orders got to big when making circuits in EV/IV  that it got stuck too often.

**Comment by Skiftcha** [comment]
i did not understand anything. can you please provide simple step-by-step guide and say what is wrong and when?
i cannot connect in my mind full input hatch and carbon voiding.
regular interface also stops when input bus is full and does not void anything.
this is completely normal situation when ME system is faster than crafting speed. and it just waits before new materials can be inserted

**Comment by Devtron3D** [comment]
Ok, let's see if I can simplify this.
Take a recipe that needs fluid and items,  like raw carbon fiber  (could be circuit board manufacturing also with the LCR)
make a crafting pattern for raw carbon fiber,  where you use a 144mb flash, and the carbon dust to create the raw carbon

Attach the fluid interface to the input bus of the PA so it will output carbon dust to the PA's input bus (I used an LV input bus for this test)
Use a pipe from the fluid interface to the input hatch to move the polyethene fluid into the hatch ( I used a ULV 8000mb hatch for this test, and instant transfer ender fluid pipes)

Now when you craft a really big order, say 4k raw carbon fiber, 
Now what goes wrong is this.
I cant remember the ratio of the recipe but say you need 144 poly fluid, and 16x carbon dust to make 4x raw carbon fiber

like with moth recipes, the ME will just start outputting EVERYTHING it can to the interface the recipe is in. in this case it is fluid and items
The problem is WHEN the hatch becomes full it will stop outputting fluid as it cant fit more in the hatch, which is normal. It ALSO stops outputting items, in this case, the DUST, so the recipe becomes stuck.
The ONLY two way to make it process again and output more items is either to remove some fluid from the hatch so there is room for another 144mb fluid, or add some dust to make it use some of the fluid.

Now, what the problem is, it has 2 items it needs to export(fluid and dust), but when the fluid CANT be output, it will stop adding items too, even though there is 8000mb of polyethene just begging for dust to come.
In essence, the order freezes and cant continue to process, even though the input bus is empty.

If this explanation is not good enough, poke me on discord and I can send you my test setup or show you on a screen share over voice chat.

This error did not happen before that dupe bug fix. 
,

**Comment by Skiftcha** [comment]
> The problem is WHEN the hatch becomes full it will stop outputting fluid as it cant fit more in the hatch, which is normal. It ALSO stops outputting items, in this case, the DUST, so the recipe becomes stuck.

interface outputs recipe step-by-step. 144 poly, 16 carbon, 144 poly, 16 carbon and so on
having full 8000 mb hatch means you also have 8000/144*16 carbon dust in input bus.
recipe is not stuck. it waits PA to process inputs. and then will put new poly and carbon.

https://drive.google.com/file/d/1jvj14zc2CEqI2NJWa7l0DKdPbgdeng8J/view?usp=sharing

**Comment by Skiftcha** [comment]
i'd say more

> I used an LV input bus

you cannot have 8000 mb of poly with LV input bus. because 4*64 carbon dust is only 2304 mb.
with LV bus i only have 2448 mb (2304 + 144 from next recipe)
![image](https://user-images.githubusercontent.com/2212585/122681281-29e88480-d1fc-11eb-90cd-0c982765e0f9.png)

looks like you use wrong liquid amount for craft in recipe so it floods input hatch and does not allow new crafts

**Comment by Glease** [comment]
Completely resolved after skiftcha talking with Devtron on discord in dm.
