### ISSUE TITLE
Higher Tier boilers have severe throughput problems that render them pointless.

### ISSUE THREAD

**Issue by Anarack** [GTNewHorizons/GT-New-Horizons-Modpack#6325]
Large boilers beyond the steel tier boiler do not have enough total output to make them worth considering at any level.

current boiler before turbine efficiency output
Bronze 400 EU/t can run several mv/lv machines
Steel 600 EU/t can run 1 hv machine
Titanium 800 EU/t runs half of 1 ev machine
Tungsten Steel 1000 EU/t runs 1/8 of a IV machine

From looking at the output amounts only bronze and steel are worth considering compared to other options available at the same time, and steel is a hard sell. Titanium can not even power one ev machines by itself, and tungsten steel is even worse.
I have to point out efficiency is not the problem or solution to this, final output is just not enough to be usable.

Suggestions to fix this issue.

- Buff output while keeping same power output per item (simplest solution)
 - make tungsten steel boilers boilers output super heated steam while buffing titanium normal steam output (will need to tweak output numbers for tungsten to keep the same output efficiency)
- allow boilers more output indirectly by using the LHE and hot coolant instead of steam (requires heavy changes to the boilers and more work to balance)

Discuss

**Comment by redmage17** [comment]
>allow boilers more output indirectly by using the LHE and hot coolant instead of steam (requires heavy changes to the boilers and more work to balance)
This would make them large heat exchanger please no

**Comment by redmage17** [comment]
Also they need buffed probably a little bit give that they pump out a decent amount of pollution and that is going to be a problem. I do think we need to be careful because you are strongly encouraged to stop using steam, also it's easy to automate with a treefarm and pyroluse oven. I run a steel large boiler with a large turbine for a little bit of power and distilled water.

**Comment by Cleista** [comment]
And benzene isn't easy to automate with a treefarm and pyrolyse oven? Biodiesel isn't?

There are plenty of non-steam power sources that are just as easy to automate if not easier, so I do not think that is a valid reason to deny an improvement to steam. Plus there is an existing questline telling you to build large steam turbines and a tungstensteel boiler, so I think it's fair to rework them into something that at least is worth the resource expenditure. 

Right now there is zero reason to build, say, 4 Tungstensteel boilers instead of 8 steel ones. This isn't in line with the other multiblocks such as the multiblock miner for which upgrading actually is enough of an improvement to be worth the higher tier of materials.

**Comment by GeicowithaBango** [comment]
boilers are good boys, they deserve better

**Comment by 0lafe** [comment]
Boiler fuels are bad bois, they deserve to be good
