### ISSUE TITLE
Buff Circuit Assembly Line

### ISSUE THREAD

**Issue by redmage17** [GTNewHorizons/GT-New-Horizons-Modpack#6326]
Instead of making the LuV Circuit Recipes costs 6 times the components why not just make the Circuit Assembly Line function like the normal Ass line. Allowing for multiple recipes per multi-block? I mentioned this is the discord you don't need to break another mechanic because people aren't using your implementation

**Comment by Prometheus0000** [comment]
You can change it for yourself in the config if you're not playing on a server.

**Comment by redmage17** [comment]
Why not make that the default? Again I feel like the recent change to the single block was due to people forgoing the multiblock

**Comment by Prometheus0000** [comment]
Wasn't the config added at the same time as the multiblock? And the idea is for it to be hard. Plus this is what Bart wanted, so go complain on his repo if you want to convince him to change it.

**Comment by finkledoodle** [comment]
It does seem to have been added purely to increase grind with no discernible contribution to the pack otherwise. When I first heard about it, I assumed that the multiblock was being added to allow bulk-crafting of circuits in some fashion as an alternative to the normal way they were crafted. I wasn't expecting the devs to nerf existing circuit recipes, although I'm used to pointless nerfs by now for the nebulous idea of "giving players a sense of pride and accomplishment" (coined by a certain infamous videogame corporation). However, I was unprepared to see that I'd be forced to build a new multiblock for every single circuit recipe, essentially resulting in a dozen mini assembly lines, each one permanently tied to a specific single circuit. Is it only a matter of time before we have to build an assembly line for each individual recipe as well, just because "the idea is for it to be hard", and to provide players with more of a sense of "pride and accomplishment" if they still bother playing the pack and making all of that redundant infrastructure that was accomplished with a single machine previously? (A single machine which I'm unaware of any complaints about how "easy" it was).

**Comment by Josh5minus1** [comment]
These are only ideas:
1. Make the CAL accept more than 1 imprints with a dedicate imprint input bus (or similar).
2. Reduce 6x to maybe 2x? And increase the CAL parallel from 16 to 20?32?
3.????? (Just accept the mechanic)
Free to agree and disagree.

**Comment by DualBallers** [comment]
I agree that getting to the point of 10+ of the same multiblock lined up next to each other is not really that interesting.

Like for many other multiblcoks, there is also the option of having a much more expensive second tier CAL controller, that can craft all/more circuit types.

**Comment by 0lafe** [comment]
I don't believe the ability to only craft one circuit in it is a design choice as much as a consequence of how it's made. If someone is able to PR in a change to give maybe a circuit line per CAssline, or assline like functionality, I think it would be added. 

Allowing singles to do 1:1 with the CAssline, is pretty bad. Realistically we should probably figure out a better tiering system than hatches, which would avoid tier skipping. Then remove the single blocks past IV. 

>I wasn't expecting the devs to nerf existing circuit recipes though, despite being used to pointless nerfs by now for the nebulous idea of "giving players a sense of pride and accomplishment" in forcing them through an ever increasing number of hoops to jump through for tasks previously accomplished with no issues or complaints

"Oh shit they changed something I've already done? No it can't be any different, that's not possible! Give me my singleblocks!" Lol 

~~~

Being able to do >1 recipe in a line would be nice, but I don't think anything's stopping that besides someone figuring out code that will work. You can probably swap controllers with PR, to cut down on total assembly lines structures if you want. Still a better system than circuit production in singles

**Comment by chochem** [comment]
> 
> 
> I don't believe the ability to only craft one circuit in it is a design choice as much as a consequence of how it's made. If someone is able to PR in a change to give maybe a circuit line per CAssline, or assline like functionality, I think it would be added.


This is most definitely a design choice and I think it is extremely unlikely that bart would accept such a PR. He has gone for the same design (one machine = one recipe) with the bacterial vat and made it clear he does not want it changed.

I am very much against this one machine per recipe approach myself, but realistically thats not gonna happen.

**Comment by redmage17** [comment]
I would also add it would be an idea with the tech tier and additional steps required to buff the amount of lower tier circuits it produces per recipe. When you say "assembly line" I assume their should be an increase in efficiency. I would even be willing to code this. Again improve your own implementation instead of breaking other peoples toys if you want people to use it.

**Comment by Prometheus0000** [comment]
You should go to Bart's repo or discord and ask what he's willing to have changed.

**Comment by redmage17** [comment]
Still relevant

**Comment by Prometheus0000** [comment]
And what did bart say?

**Comment by redmage17** [comment]
Bart can go fuck himself

**Comment by Dream-Master** [comment]
@redmage17 github isnt the place to berating people. Deal with it or leave the community!!!

**Comment by redmage17** [comment]
> 
> 
> @redmage17 github isnt the place to berating people. Deal with it or leave the community!!!

You let a group of people do this for months and some of them are mods now you fucking coward

**Comment by LewisSaber** [comment]
As making CAL for each recipe isnt cool mechanic  and making CAL accept all circuits will make it too easy , why not to buff CAL so one CAL can be able to make a line of circuits, like 1 CAL would be able to make all 4 types of quantumprocessors, another one all 4 types of Crystalprocessors

**Comment by Dream-Master** [comment]
I block redmage for 7 Days now.
@redmage17 when you come back using other words or i block you forever!!!

**Comment by 0lafe** [comment]
What's stopping someone from setting up an array of many CALs, then swapping all the controllers on recipe input, then running batches of some circuit? Seems to essentially remove the downside, in a way that scales with the ability of your setup, which imo might be even better than allowing the machine to function better on its own.

**Comment by Prometheus0000** [comment]
I think you assume far more people use frame movers than actually do, or want to risk world corruption.

**Comment by 0lafe** [comment]
I don't assume people do this considering I've seen no one argue for this mechanic to stay, which is why I'm trying to bring it up. You don't really have to just use frames for this, I'm sure there's some other interesting setups people could do with placers/breakers, or maybe even planes. Overall tho it seems like a cooler challenge than the nothing else the CAL brings to the table

**Comment by Prometheus0000** [comment]
Whatever way you remove the controller, it sounds like a recipe for world corruption. And is probably unintended.

**Comment by 0lafe** [comment]
I mean nothing is intended until we make it intended. I personally think that intending the player to do more novel actions is better than trying to make the gameplay less dynamic and less involved. Idk how world corruption comes into this. I do have a fair bit of experience with assembling/disassembling a bunch of multis, in weird ways. Never seen world corruption at all, and the worst I've noticed was client kick related issues with putting too many blocks on a single frame motor (hundreds+). There's some no nos to moving, like RIO, and iirc TVIs, but GT seems super stable, especially in such small quantities as multi controllers. 

This also does seem unnecessary, as people seem to be progressing even with locked multis. It seems like all red flags when it comes to trying to make the multi simpler to operate

**Comment by Prometheus0000** [comment]
So even if we let people who know nothing they aren't going to crash servers? Personally, I'd rather have a mechanic that makes the multi itself more interesting, rather than externally modifying it, like having only one ULV bus, and having to put the ingredients in in order or something. Though that would probably make them slow.

**Comment by 0lafe** [comment]
At the end of the day, imo the multi is only interesting if you need external modification. That's kind of a cool idea if you mean what I think you mean, but that seems kind of too easy to overcome. Unless I'm missing a big part of it, can't you just constant push from AE to the input, and have that work about as well as possible? 

Things like the assline imo stand out due to the external infra they force you to build in terms of handling logistics. Keeping those orders, while segregating recipes, and possibly stacking them allows for a lot of complexity in your setup. There was a time in which people were of the view point that automated asslines shouldn't be needed, for a handful of reasons. However since the increase of usage, and forcing decent automation for progression, we've seen a lot of really cool unique ways of tackling this problem, and generally I find it to be one of the better challenges we have overall. 

If we make the challenge too easy, it's not really a challenge. If we view it as a bug instead of a challenge, we just end up with a boring copy/paste machine that doesn't really differ itself in any way. However if we consider this an intended feature you need to work around, we suddenly have a fair bit of immergent gameplay surrounding the efficient handling of these recipes. Lots of depth, without us needing to change anything about anything. 



As to bricking servers. I've done some crazy stuff but never been able to fully take my server down with frames. If you have too many blocks on a frame, that can still move, you can possibly kick players in render distance. If you set this machine up to keep moving, it'll keep kicking people. This is difficult to do, and wouldn't really be possible to reach these numbers when doing this type of setup. Things like RIO/TVIs can crash servers and prevent launch, but only as all erroring tile entities do iirc. There's not a lot of no nos with frames, things like sfm/dimensional transceivers/chunk loaders/quantum rings/PR chips/and even OC can be moved without any issue, and seem to function just fine. If someone was able to accidentally break a server while trying to swap a controller, I'd be really surprised.

**Comment by Prometheus0000** [comment]
I mean only a a certain order to the ingredients, and if you put it in the wrong order, it just halts (or voids). Since there's only 1 ULV bus allowed, you wouldn't be able to put them in separate busses, or shove them all in the same one. It would probably require SFM or OC to automate that kind of thing though. Even more than it already basically is.

**Comment by leagris** [comment]
Here we are! A machine that is added as a self justified challenge rather than as a service. Player is forced to craft this gibberish, not because it provide faster, more efficient, circuit crafting, but because it is forced to like a bitter pill.

This CAL only exist to fulfill itself.

**Comment by 0lafe** [comment]
I mean we could also provide no challenge in it and have it make the players life easier, but I'm not sure that's really   the most interesting option. We already have a lot of multis that function like this, it definitely benefits from a little change up imo. At the end you can still consider it beneficial to the player, the challenge is just more than a recipe or an input. However completion of it provides more ability of production, which grants progression. Imo good trade-off which more unique and lategame inputs

**Comment by repo-alt** [comment]
I honestly see no reason why the cannot be something like external data storage perhaps available at ZPM, one tier later that the assembly line. I'd like to hear what the author thinks. @bartimaeusnek ?

**Comment by Prometheus0000** [comment]
That sounds like the best solution to me, but since the items are circuit imprints, maybe instead of a data hatch, some similar item that doesn't allow removal since they're soldered in sounds interesting. Or did you mean separate from the multi entirely?

**Comment by repo-alt** [comment]
Separate, like one from TecTech
