### ISSUE TITLE
Duplicating? oxygen

### ISSUE THREAD

**Issue by danshadow123** [GTNewHorizons/GT-New-Horizons-Modpack#6329]
#### Which modpack version are you using?
mod version 1.6.28

#
#### What did you try to do, and what did you expect to happen?
Smelting sand to glass (1 sand=2 glass) in mv arc furnace using 2mb oxygen. Macerating glass and centrifuging dust to get 2 dust of SiO2 which can be electrolyzed to get 2000mb oxygen

#
#### What do you suggest instead/what changes do you propose?
I dont know if making glass should require 2k oxygen per craft because of its too expensive, but there is an oxygen dupe for sure

**Comment by boubou19** [comment]
you'll get kilo buckets of oxygen later in the game so this exploit would be useful only early game, and you need 3A to power the arc furnace, plus the sand to make glass. Oxygen is barely used to make stuff in the ebf and to make some chemistry stages. This is not gamebreaking and attempt to fix this exploit would break too much the current balance IMO. I suggest to let it be, like a reward to those who fought with nei to see this bonus.

**Comment by danshadow123** [comment]
Thank you for answer

**Comment by boubou19** [comment]
Don't close it as others may have statements in favor of the exploit removal.

**Comment by Cleista** [comment]
This is not really a dupe because it's sand in -> silicon out, it can be logically explained as the oxygen coming from the sand itself. 

As for why this is much more efficient than electrolyzing sand into SiO2, could be explained as rewarding multi-step processing. I don't think this really needs to be fixed given that oxygen is often produced in such vast quantities that people void it.
