### ISSUE TITLE
I want to start translating this modpack to PT-BR

### ISSUE THREAD

**Issue by maniifestantes** [GTNewHorizons/GT-New-Horizons-Modpack#6331]
Hey guys I'm thinking of translating this mod  pack to Portuguese but I don't know where are the files and how to do it, can someone help me?

**Comment by Prometheus0000** [comment]
The primary quest file is https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/blob/master/config/betterquesting/DefaultQuests.json, but I don't really know how translations work. From looking at Kiwi's PR #6322, I guess you need to make/update an appropriate language file in the https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/tree/master/resources/minecraft/lang folder, and maybe update the other two? From looking at it on my local client, it looks like all the text in the DefaultQuests-us.json file is replaced with references to en_US.lang which will be swapped out if the language changes. You'd probably be better of asking kiwi about it, since it seems they're doing the same thing for Chinese though. If you don't know how to do PRs, the Readme in the same folder should help.

No idea how to translate things other than the quest book if you wanted to do that though.

**Comment by Dream-Master** [comment]
@maniifestantes go and ask @Kiwi233 he did it for chinese language.

**Comment by Kiwi233** [comment]
@maniifestantes other thing can tranlate by resource too, because gtnh have ResourceLoader mod.
some Thaumonomicon text maybe in script.
In addition, there are a small part of config.

You can refer to https://github.com/Kiwi233/Translation-of-GTNH
