### ISSUE TITLE
Buff Binnies?

### ISSUE THREAD

**Issue by redmage17** [GTNewHorizons/GT-New-Horizons-Modpack#6336]
Currently there is an ongoing discussion with the disparity between IC2 crop an bees. The one of the big sources of contention is the fact that Ic2 crops only requires HV and outside of RNG you can quickly reach the very high end crops. 

Bees in comparison are very tedious, with low mutation rates, and specific conditions and biomes(Using IC2 crops?! build in a swamp and you are good!) to breed each species. And until UHV you need to keep a queen and a few drones of each line in case you fuck something up. You  can use binnies but it's horrendously slow and takes a decent chunk of resources and bees to get and you NEED an alveary which is painful .

I would like to either create of bridge of some sort between HV and UHV as far as machines go with different tiers work faster. Unfortunately I am not well versed enough in Java to do this. 

So here is what I propose. Drastically reduce the processing times for Binnies, slightly increase the RF used, then bump the crafting tier to EV. I currently have a build I am working with toying around with these values. Otherwise we really need to nerf ic2 crops :)

**Comment by boubou19** [comment]
crops can't scale enough in comparison with bees: lets suppose that someone decided to make towers of crop with best possible stats and a cropmatron + a crop havester. granted this does not cost that many lv amps, but you need to design powerline. Also you need to supply water, but you can use the EV tiered everful urn. You also need tons of fertilizer, so you must have a steady fertilizer setup ( the easiest is the combo dark wood farm + extractor). Also you can't speed up whole fields of crops with a world accelerator. What do need some bees? only an apiary, some frames to boost the bees, and most importantly: you can speed them up with a world accelerator, which can be done already at LV. 1 world accelerator can speed 5 crops/5 apiaries if you use a cable to power it, 6 if you use energy microwave transmitters. bees are way more interesting because you need less maintenance. Granted crops have some unique resources like UUM. It may sound interesting, but i had like 15 bucket over a week, meanwhile, i have like 6mb/s uum with hv mass fab single block setups. So i decided to stop the use of my transformium crop fields (4 fields of 11*11 transformium with 22/31/10 stats and cropmatron/crop harvesters). What currently lack the crops, is the incredible scaling that be do have: you can start making them very early game, but you still can mess with them at endgame via gendustry. crops, there is not that much boost you can make past hv (what you can do with crops++ is creating from scratch with some uum the ideal crop, but the tier of the machine limits the maximum rank of the crops you can mess with). Also all the gt material bee combs are used either in boosting ore output by using combs with purified ores, or by giving uum, you can make purified ores from 9 combs. But like i said, transformium crops are terrible to produce uum (my 6 mb/s are obtained by using 256 HV mass fab, which cost 1A UV) So please stop proposing crop nerfs, because crops are weakier than bees

**Comment by chochem** [comment]
just 2 bits of advice, Redmage: 1) you dont need to keep around a queen of each species, thats just a waste of queens. you can just keep drones and convert all your queens to template queens or whatever you need them for. 2) speed up your binnies with WAs.

Outside of that, I have to agree that bees are not to great before late game with the exception of empowering and wither but thats a lot of work to get those early on. Crops are far superior for most of the game. boubou is the first person I have heard of that thinks otherwise. Using WAs on apiaries in LV as that post proposes (or even MV-HV) to produce stuff with bees is a really bad strategy that just wastes all your energy without producing anything really. you gotta get to industrial apiaries (or the magical ones) and need large amounts of excess energy for that to become viable.

**Comment by boubou19** [comment]
Again, just because it's not viable lv-hv does not mean it's not viable later ( for the WA). Also there are also extrabees that does not require uum to process them and it gives you many unlikely items, one bee does even let you bypass platinum chain by giving you platinum grain which can be turned into pure platinum (did not tested in 2090 but it was like that in 2083 and i don't remember seeing this issue on github).

**Comment by chochem** [comment]
Have you actually tried any of these 'strategies'? Getting Platinum from bees in EV-IV instead of making the platinum chain again ise a really bad strategy. not only do you need to build most if not all of the platinum chain anyway at the end of IV to get palladium etc. No, additionally its also insanely slow and/or takes huge amounts of energy. A MT beats that trivially.

**Comment by Dream-Master** [comment]
if someone take care and recode binni sure why not. Binni machines are nice but slow

**Comment by boubou19** [comment]
> Have you actually tried any of these 'strategies'? Getting Platinum from bees in EV-IV instead of making the platinum chain again is a really bad strategy. not only do you need to build most if not all of the platinum chain anyway at the end of IV to get palladium etc. No, additionally its also insanely slow and/or takes huge amounts of energy. Even a MT beats that.

I do agree that you need a platinum chain anyways, but the point of this is that you have faster platinum in average than with a platina field, like 16 platina leaf gives you with 20 mb of uum 1 purified platinum ore in a hv autoclave. (I do not take into account the other recipes in the chemical reactor to boost output from ores, as my concern is to get resources from crops/bees themselves). On the other hand, you have the platinum comb from extra bees that makes you 1 platinum grain with 100% chance while being an ulv recipe. so to get 1 actual platinum ingot, you just need 4 combs. Now if we we compare 22/10/x crops versus platinum bees from extra bees, with longest lifespan and production speed: blinding(200%), even like 5 of those bees beat a full 11 by 11 22/10/x platina crops field. So even if it's a bad strategy, bees yield more resources than crops. And i did not take into account the frames/alvearies/industrial apiaries/wa specific boosts. And you can find tons of similar exemples. 

I have nothing against buffing binnies, but crops are lacking similar mecanics, like why not make expensive block that could add growing/looting/mutating boost like what you can do with frames/alvearies/industrial apiaries? My only concern is that if you keep boosting bees, crops will be less attractive, that's what happened to solar panels after systematic nerfs. I do really like crops and i don't want it to be useless.

**Comment by 0lafe** [comment]
I'm not sure we need to buff binnies to make bees viable. Considering how many unique drops they have, and how you don't need to rely on genetics, they seem pretty ok to me. 

We might want to do some bee/crop reworks in terms of what they can produce, but I think that's a different discussion. We really should probably remove the bee line bou mentioned. I think it still has pure Os drops as well? 

>Give crops more bee like mechanics

They already have the crop replicator and mutator right? Crops in general have little mechanics wise, which imo fits them being more early game. I'm not sure we need to make crops viable all game, or increase in utility with tier ups. They do fit a good roll of being more early game focused, I don't think we need to give them bypasses with higher tiers.

**Comment by redmage17** [comment]
Bees should be preferable to crops due to the infrastructure required. Bumping machine tier to EV and drastically reducing processing times. Most of the "issues" stated above are due to the fact that people like 0lafe nerfed bees into oblivion. It took me two hours to get all the tier 12 ic2 crops. For bees it takes that time to get an alveary if you are lucky. Get fucked

**Comment by boubou19** [comment]
only hard nerf happened on gendustry's recipes, other nerfs like comb nerf were a good thing, i mean it's common sense that combs giving IV+ materials should not be processable at lv, otherwise with the recipe overclock it would be too easy to process them.

**Comment by redmage17** [comment]
I am not discussing products but rather the time and effort to get bee lines vs ic2 crops. Combs will not be affected by this PR

**Comment by redmage17** [comment]
> 
> 
> > Have you actually tried any of these 'strategies'? Getting Platinum from bees in EV-IV instead of making the platinum chain again is a really bad strategy. not only do you need to build most if not all of the platinum chain anyway at the end of IV to get palladium etc. No, additionally its also insanely slow and/or takes huge amounts of energy. Even a MT beats that.
> 
> I do agree that you need a platinum chain anyways, but the point of this is that you have faster platinum in average than with a platina field, like 16 platina leaf gives you with 20 mb of uum 1 purified platinum ore in a hv autoclave. (I do not take into account the other recipes in the chemical reactor to boost output from ores, as my concern is to get resources from crops/bees themselves). On the other hand, you have the platinum comb from extra bees that makes you 1 platinum grain with 100% chance while being an ulv recipe. so to get 1 actual platinum ingot, you just need 4 combs. Now if we we compare 22/10/x crops versus platinum bees from extra bees, with longest lifespan and production speed: blinding(200%), even like 5 of those bees beat a full 11 by 11 22/10/x platina crops field. So even if it's a bad strategy, bees yield more resources than crops. And i did not take into account the frames/alvearies/industrial apiaries/wa specific boosts. And you can find tons of similar exemples.
> 
> I have nothing against buffing binnies, but crops are lacking similar mecanics, like why not make expensive block that could add growing/looting/mutating boost like what you can do with frames/alvearies/industrial apiaries? My only concern is that if you keep boosting bees, crops will be less attractive, that's what happened to solar panels after systematic nerfs. I do really like crops and i don't want it to be useless.

These take infrastructure and with the horrid mutation rates it can take you days to get a line of bees. Also how many people are at UHV? I am not nerfing IC2 crops. Bees where nerfed into oblivion because you shitheads stop crying because they are getting a needed buff.

**Comment by boubou19** [comment]
Please be civil, insulting others because they do not share your vision is stupid and pointless, and ultimately, this is Dream who decides if nerfs/buffs are pushed live, not 0lafe nor me.

Also, gendustry is ZPM, not UHV and you need highend bee combs such as plutonium or naquadah combs, which is PAINFUL so this why I NEVER said they did not needed a buff. I just want to make sure that the buff is not to trivialize bees at mid game. Modifying time required and increasing energy consumed by binnies is fine, as long as it does not become ridiculously OP, so when you can, please post your numbers so we can discuss them. Also why put binnies at EV instead of HV? I mean, you buff them but lock them farther away ? It would make the bee breeding a little harder for 1 tier, then suddently easier ? Why not, but i would like to know what is your reasonning behind that @redmage17.

**Comment by redmage17** [comment]
> 
> 
> crops can't scale enough in comparison with bees: lets suppose that someone decided to make towers of crop with best possible stats and a cropmatron + a crop havester. granted this does not cost that many lv amps, but you need to design powerline. Also you need to supply water, but you can use the EV tiered everful urn. You also need tons of fertilizer, so you must have a steady fertilizer setup ( the easiest is the combo dark wood farm + extractor). Also you can't speed up whole fields of crops with a world accelerator. What do need some bees? only an apiary, some frames to boost the bees, and most importantly: you can speed them up with a world accelerator, which can be done already at LV. 1 world accelerator can speed 5 crops/5 apiaries if you use a cable to power it, 6 if you use energy microwave transmitters. bees are way more interesting because you need less maintenance. Granted crops have some unique resources like UUM. It may sound interesting, but i had like 15 bucket over a week, meanwhile, i have like 6mb/s uum with hv mass fab single block setups. So i decided to stop the use of my transformium crop fields (4 fields of 11*11 transformium with 22/31/10 stats and cropmatron/crop harvesters). What currently lack the crops, is the incredible scaling that be do have: you can start making them very early game, but you still can mess with them at endgame via gendustry. crops, there is not that much boost you can make past hv (what you can do with crops++ is creating from scratch with some uum the ideal crop, but the tier of the machine limits the maximum rank of the crops you can mess with). Also all the gt material bee combs are used either in boosting ore output by using combs with purified ores, or by giving uum, you can make purified ores from 9 combs. But like i said, transformium crops are terrible to produce uum (my 6 mb/s are obtained by using 256 HV mass fab, which cost 1A UV) So please stop proposing crop nerfs, because crops are weakier than bees

Lol yeah bees require seed oil, honey and various other materials(such a Pu-241) that are so much easier than Ic2 crops!. You don't know what you are talking about.

**Comment by boubou19** [comment]
i think there is a misunderstanding of my statements, so let me clarify them: bees are harder to setup, but once it's done, it's done, barely any maintenance performed on them. It also yields more resources than crops, and can be boosted several ways. So my question is why bother making crops, because it takes time to setup with optimal stats, need a decent fertilizer supply to not let the field die (also electricity but 1A LV but in optimum setup it's 1A LV per 2 crop fields so granted it's nothing once you reached mid MV tier). In the meantime, making bees take the same if not more amount of time to setup. (i know well how hard it is to do bees as i did all the bees needed to get gendustry with only forestry apiaries & beehouses). From my point of view, crops are still interesting to have HV-EV because they are still faster to setup than bees at those tiers (once you got two perfect crops, it's super easy to make the rest of the field). By speeding Binnies machines, i'm afraid that bees will become faster to make so there is no incentive to still do crops at HV-EV. But again, there is no point debating without the numbers you have in mind. So i will wait after those, and maybe i'll review my opinion after.

P.S. : extrabees' bees should be reworked somedays as they are OP in comparison to their GT bee equivalent.

**Comment by leagris** [comment]
> P.S. : extrabees' bees should be reworked somedays as they are OP in comparison to their GT bee equivalent.

Then rework the stupidly inept Gregtech bees so they produce more materials with less convoluted processing. And no, there is no OP when making bees a source of renewable material rather than having MP server die once the happy few pillage racers took all the easy loot materials.

**Comment by redmage17** [comment]
> 
> 
> i think there is a misunderstanding of my statements, so let me clarify them: bees are harder to setup, but once it's done, it's done, barely any maintenance performed on them. It also yields more resources than crops, and can be boosted several ways. So my question is why bother making crops, because it takes time to setup with optimal stats, need a decent fertilizer supply to not let the field die (also electricity but 1A LV but in optimum setup it's 1A LV per 2 crop fields so granted it's nothing once you reached mid MV tier). In the meantime, making bees take the same if not more amount of time to setup. (i know well how hard it is to do bees as i did all the bees needed to get gendustry with only forestry apiaries & beehouses). From my point of view, crops are still interesting to have HV-EV because they are still faster to setup than bees at those tiers (once you got two perfect crops, it's super easy to make the rest of the field). By speeding Binnies machines, i'm afraid that bees will become faster to make so there is no incentive to still do crops at HV-EV. But again, there is no point debating without the numbers you have in mind. So i will wait after those, and maybe i'll review my opinion after.
> 
> P.S. : extrabees' bees should be reworked somedays as they are OP in comparison to their GT bee equivalent.

Yes solar panels are so hard to make for 32 LV and the set-up takes weeks. It's like you haven't actually dealt with bees and are just looking at NEI

**Comment by redmage17** [comment]
![2020-07-02_16 14 16](https://user-images.githubusercontent.com/15355637/86405308-26708c00-bc7f-11ea-9757-6105ee4b2878.png) So HARD MUCH DIFFICULTY

**Comment by 0lafe** [comment]
>Then rework the stupidly inept Gregtech bees so they produce more materials with less convoluted processing. And no, there is no OP when making bees a source of renewable material rather than having MP server die once the happy few pillage racers took all the easy loot materials.

I'm very lost on that last statement. GT bees aren't an issue, but I'm assuming you mean the autoclave UU recipes suck? If so, that's fine, and yes it would be OP to make these produce lots with lowered cost. This isn't world generated loot, these are veins of ores that everyone will be able to find. Easy infinite ore gen just means you're not constrained by mat quantities, and have no need to mine anything, which does get very OP when they're both available at the same time. Nugget bees are just bad. Uu autoclave/ore dupe bees are pretty chill.

**Comment by redmage17** [comment]
To clarify I want to use bees to multiply my ore production and I think this is what they should be used primarily for. The "infinite resources" thing is really not rewarding enough for me to use it.

**Comment by boubou19** [comment]
> ![2020-07-02_16 14 16](https://user-images.githubusercontent.com/15355637/86405308-26708c00-bc7f-11ea-9757-6105ee4b2878.png) So HARD MUCH DIFFICULTY

once for all: I NEVER seid it was HARD, i say crops CANNOT COMPETE with bees.

**Comment by redmage17** [comment]
> 
> 
> > ![2020-07-02_16 14 16](https://user-images.githubusercontent.com/15355637/86405308-26708c00-bc7f-11ea-9757-6105ee4b2878.png) So HARD MUCH DIFFICULTY
> 
> once for all: I NEVER seid it was HARD, i say crops CANNOT COMPETE with bees.

AND BEES REQUIRE FAR MORE TIME, RESOURCES , AND SET-UP

**Comment by redmage17** [comment]
THIS PLAYS INTO BALANCE!

**Comment by boubou19** [comment]
you know what? just give your new numbers for the buff, and after we will talk about "balance", i'm not gonna lose my time with someone who just respond with caps.

**Comment by Ngar1** [comment]
The ore multipling is from my standpoint total boring, it the overtaken principle from IC2 crobs, i never liked or use. And uu i only used if i have to, because it feels equal to the old EMC (waste to every thing), that kills all log time play fun.

I like forestry and binnies concept to collect some materials in small volume by bees. It is hard to breed them, takes much more time than ore mining or taking higher technology levels.

On the other hand, it is much more effective to place miner and multiply ores by combs, instead to centrifuge a comb to tiny dusts.
I see only disbalance in direction comb-Ore multiplier as to centrifuge small materials.
The best seems to be: let both ways as they are...

**Comment by redmage17** [comment]
> 
> 
> > ![2020-07-02_16 14 16](https://user-images.githubusercontent.com/15355637/86405308-26708c00-bc7f-11ea-9757-6105ee4b2878.png) So HARD MUCH DIFFICULTY
> 
> once for all: I NEVER seid it was HARD, i say crops CANNOT COMPETE with bees.

An all ic2 crops requires are sticks and hv machines at best. I have to build an alveary to unlock some of the tech. Then MV, Thaumcraft, have to spend hours breeding up multiple lines of bees, and Gendustry is still locked beyond UHV. It takes far more time and effort to use bees. The payoff? They are a bit better than something that just requires sticks. Game balance. You can still use IC2 crops as it will still be far quicker to break into. This just makes bees a bit a more bearable and accessible. Otherwise you are crying someone is incentivizing another method of play than the one you prefer which is toxic.

**Comment by boubou19** [comment]
still wanting to argue uh? binnies is here to fill the gap. My only concern is to see if your numbers (which you still do not provide) are well balanced. That's nothing more. So stop trying to convince me that crops are easy because i know. But i also know that crops aren't as scalable as bees, and none of your arguments will can prove the contrary.

So please provide numbers, or this whole thread is useless.

**Comment by Dream-Master** [comment]
So before we buff or nerf binnies stuff we need to make a list with values

**Comment by redmage17** [comment]
Analyzer reduced time from 300 to 30

Genepool reduced time from 400  to 40, reduced enzyme consumption by 1/3

Incubator is left unchanged til I can figure out the math at some point and honestly it's not that bad, I am considering adding recipes for the fluids to GT machines(another discussion)

Inoculator this is the big one as it used to take an absurd amount of time and you need to Inoculate a ton of bees. 
Previously was 12,000 to 120

Isolator 480 to 48

Polymeriser 1,200 to 120

Sequencer changed from 15 minutes to 5 (it's done via an equation not 100% sure on the specific time frame)

Splicer 1,200 to 120

My next commit will be to crank the power required by about 2.5x per machine, increase internal RF by 10x to help compensate as well. This does not stop people from using IC2 crops, Bees take a ton of special infrastructure, realistically they are not viable til later in the pack and people should be rewarded for the extra time spent.

**Comment by Cleista** [comment]
With these buffs you can now stack it with WAs for all operations completed in seconds.

Is this intended?

**Comment by Dream-Master** [comment]
@redmage17 it's just a suggestion because I have to look at it too. We want it faster but we don't want it to cheap.

**Comment by Prometheus0000** [comment]
There's a WA blacklist if it's deemed necessary.

**Comment by Cleista** [comment]
I would rather have the option of using my power to WA it 16x/32x/more instead of dealing with a fixed 10x speed boost. 

If bees are as lategame as redmage says, whoever that is doing them can already easily afford HV WA (8x accel) and possibly even EV/IV WA for bursts of acceleration. I did tree breeding with HV WA and it didn't really feel that bad because just having the WA on for when I am actively trying to get genes out isn't that power hungry compared to the 24/7 running EBFs.

**Comment by Prometheus0000** [comment]
I'm just saying it's an option.

**Comment by 0lafe** [comment]
The speed increase was because red said WAs don't work on these machines. If they do, then nothing should change, but if they don't work, some of this isn't that bad of an idea. 

2.5x increase seems to be a little low, I'd rather see them using something like 1
~1A EV for a 10x speed increase (30x on enzyme creation right?). WA would be about 1A EV per 16x increase, not mentioning the HV- options.

**Comment by redmage17** [comment]
WA's do not affect Binnie's Machines. I've tested this

**Comment by mtesseracttech** [comment]
WA's do in fact affect Binnie's Machines. I can show this.

**Comment by boubou19** [comment]
So the question is now: should be the genetics machine blacklisted from WA or not?

**Comment by mtesseracttech** [comment]
I'd disagree with that. Because some are unbearably slow without it (like 30 minutes per DNA sample), at a server with half the tick rate.

**Comment by mtesseracttech** [comment]
https://imgur.com/a/3yhTdka This is the proof for that they do work @redmage17 .

**Comment by redmage17** [comment]
That still seems off. That's an EV(8x) WA right?

**Comment by mtesseracttech** [comment]
HV, I just happen to use the Zedderian Technology texture pack.

**Comment by redmage17** [comment]
We blacklist them then even with the power increase I propose easier than using WAs.

**Comment by boubou19** [comment]
As we can see on MTesseracT's gif, a HV WA (x8) is already more acceptable than default speed. We must not forget that WA speed boost is on all the machine: so speed boost, consumption boost, etc.

So new values would also get multiplicated by the world accelerator boost. it does not sound reasonable to let the WA work on them, because players not using the WA would get a buff, and players using WA would need to deal with a bigger drain.

But then, with a base x10 speed buff, everything could be made in a few seconds. So if we let WA, we should reduce the base speed buff, because it will be multiplicated by WA. This could be interesting, in a sense where if you judge the machine to be too slow, you'll have to upgrade your world accelerator, which will lead to a x4 in the WA power supply: 32A of the previous tier.

So i suggest a base speed boost of x1.5 and a power consumption multiplier of x2.5, so with HV WA it would become a speed boost of x12 and power consumption of x20, with EV WA it would become speed boost of x24 and power consumption boost of x40, and with IV WA it would become a speed boost of x48 and a power consumption boost of x80.

What do you think?

**Comment by interestingusernam3** [comment]
>I'd disagree with that. Because some are unbearably slow without it (like 30 minutes per DNA sample), at a server with half the tick rate

8 TPS is not a feature

**Comment by 0lafe** [comment]
If the WA works I'm not sure we need anything else. 16x at EV puts it faster than what a 10x non WA buff would do. Also gives good GT scaling. Leave speeds at unbuffed values puts the EV version at more than 1.5x the speed that was originally proposed for the tier. 

WA power scaling is also good, I'd say that nothing needs a change here with WAs

**Comment by Methes** [comment]
I thought the premise was that WAing things is inherently bad and should be avoided unless there's no way around it, like mod configs or edits.

**Comment by Ngar1** [comment]
The Alternatve to WA is parallize Machines, and if I reach the level of specific WA it seems for me better for server performance and joy to use WA.

**Comment by Methes** [comment]
Except using WA is NOT more server friendly as you're forcing a tile entity to update itself more often. All you're "saving" is perhaps additional cables and pipes for parallelized machines but the cables+pipes leading to your WAed TE still have to deliver stuff more often.
The only thing that's server friendly is lowering processing times with the same amount of TE updates - changing the configs.

**Comment by 0lafe** [comment]
>the only solution is to make sure I can use 1 machine and have it always work 

I'm not really sure thats true at all lol. More tps impactful doesn't mean it's actually a problem. Running things at sub gendustry voltages doesn't do much lag wise.

**Comment by Cleista** [comment]
@Methes I'm fairly certain a 256x WA'd TE is going to be substantially easier on TPS than 256 separate machines (or even 10 different machines) because it both allows the JIT compiler to optimize for repeated calls and is easier on branch predictors. 

Plus, I'm pretty sure the source of lag on large servers isn't WA'd TEs. My WA'd infusion altar doesn't even show up in Opis and the worst GT machine still took less processing time than one zombie.

**Comment by Methes** [comment]
That sounds reasonable. Thanks for the input.

**Comment by redmage17** [comment]
So are we in somewhat agreement to up the power scaling to equate to ~EV(Machine recipes now use EV parts as well) and not blacklist the machine for WAs?

**Comment by boubou19** [comment]
sounds reasonable to me

**Comment by 0lafe** [comment]
Only if you don't decrease times by 10x. If you also want to implement your time decrease they need a WA blacklist. 

WA just accomplishes everything you wanted from both the part tiering and the time decrease, meaning we don't need to change anything and it's fine. If you want to start changing stuff like speed, then you need to blacklist them from WAs, and increase power by a lot. Like 7200RF/t

**Comment by Cleista** [comment]
I also think no changes are needed. I would rather have the current WA-based tiering than the proposed solution.

**Comment by redmage17** [comment]
Yeah might as well give up. I am forking the pack at this point

**Comment by mtesseracttech** [comment]
I've got some mixed feelings about WA'ing in general.
Maybe there should be some more stuff that at least will push people into that direction so they know it's an option.
Since at the moment, it feels like genetics is in an awkward position with regards other progress.
