### ISSUE TITLE
Formic Acid Creates Sodium/Sulfur Positive Loop

### ISSUE THREAD

**Issue by Godelboard** [GTNewHorizons/GT-New-Horizons-Modpack#6437]
#### Which modpack version are you using?
2.0.9.0
#
#### If in multiplayer; On which server does this happen? 
Private server
#
#### What did you try to do, and what did you expect to happen?
Map out Formic Acid production chain; expected to find a material neutral or negative production chain.
#
#### What happened instead? (Attach screenshots if needed)
In mapping out the chemical reactions, I found it produced way too much sodium sulfate as a byproduct (7 instead of expected 1), causing the reaction to create sodium/sulfur out of thin air.

In addition, the reaction for processing sodium sulfate is also imbalanced.

![Formic Acid/Sodium Sulfate Reactions](https://cdn.discordapp.com/attachments/234936569360809996/736018739044155525/unknown.png)
#
#### What do you suggest instead/what changes do you propose?
Correct the amounts used in the recipes to balanced chemical equations correctly.
- Formic Acid Recipe
  - 2 Sodium Formate
  - 1 Sulfuric Acid
    - MAKES
  - 2 Formic Acid
  - 1 Sodium Sulfate _(instead of 7)_
- Sodium Sulfate Processing Recipe:
  - 1 Sodium Sulfate _(instead of 2)_
  - 2 Hydrogen Cell _(instead of 1)_
    - MAKES
  - 2 Sodium _(instead of 1)_
  - 1 Sulfuric Acid _(instead of 2)_
  - 2 empty cell _(instead of 1)_

This imbalanced recipe chain has been acknowledged several times in discord by other users as well but never submitted as a ticket:
https://discordapp.com/channels/181078474394566657/234936569360809996/734111528730492949
https://discordapp.com/channels/181078474394566657/234936569360809996/690381868268388422
https://discordapp.com/channels/181078474394566657/234936569360809996/663073966772060181
https://discordapp.com/channels/181078474394566657/234936569360809996/663073346220457985

**Comment by chochem** [comment]
As I am featured in there, let me explain: The reason I did not make a ticket is because it barely matters (obviously just my opinion) but a change will likely break everybody's palladium automation. Probably the same reason the other people there did not make a ticket.

Obviously everybody who has set up palladium knows about this as it causes the system to produce ungodly amounts of sulfuric acid.

Its not the only miscalculation/typo in the platinum group processing, the chlorine in the platinum chain itself is also not quite what its supposed to be, though its not as extreme. but yeah, every recipe change likely breaks everybody's automation, so there is a strong case for at least keeping that one if not the one here as well.

**Comment by Godelboard** [comment]
> As I am featured in there, let me explain

Oh no worries, I wasn't calling anyone out like "look at all these times it's been mentioned and no one is doing anything about it."

It's an obvious bug in the recipe and it's never been submitted in a ticket. If the decision is to keep it in because it's already been like this for so long, then this ticket will set the precedent that the issue has been reviewed and approved by the modpack author and they support keeping it as is.

**Comment by Dream-Master** [comment]
@chochem if there is an issue I appreciate somone make a ticket and even if this mean you need to redone your automation. There is no update out soon so relax.
