### ISSUE TITLE
Switch Rocket Crafting from the dire crafting table to the NASA workbench (or some other machine) [SUGGESTION]

### ISSUE THREAD

**Issue by Regian24** [GTNewHorizons/GT-New-Horizons-Modpack#6465]
I think its really dumb to have to kill 18 withers (or do a lot of thaumcraft) just to get to space. perhaps we could use the NASA Crafting Table from Galacticraft? or heck, even a custom crafting table?
also you only use the dire crafting table for rockets until late game so its pretty dumb to use it at hv

**Comment by boubou19** [comment]
it used to be nasa workbench, until rocket crafts moved to the avaritia table because it is easier to tune the recipes in it. you can grind the wither skeletons easily with a skeleton powered spawner in the nether and the skeleton broken spawner can be found easily in roguelike dungeons. If you don't want to bother with that, you can use the null catalyst from witchery, which requires 0 thaumcraft and salis mundus, which is made from balanced shards, and not far gated in thaumcraft. I don't see any issue here.

**Comment by Regian24** [comment]
> it used to be nasa workbench, until rocket crafts moved to the avaritia table because it is easier to tune the recipes in it.
i see, thanks. i will close this issue if you want.

i already got to the moon btw
