### ISSUE TITLE
Pico wafer recipe is weird

### ISSUE THREAD

**Issue by Alexdoru** [GTNewHorizons/GT-New-Horizons-Modpack#6495]
#### Which modpack version are you using?
GTNH 2.0.9.0 QF4
#

requires 100L of neutronium, could it be possible to make it 144L ?

![image](https://user-images.githubusercontent.com/57050655/89846942-e1475000-db82-11ea-8401-e3aa6ba7ead1.png)

**Comment by 0lafe** [comment]
i am personally in favor of using odder  fluid quantities in lategame stuff. Adds more complexity to it than the Nt material cost in a way. Recipes don't always need to be easy to do, and having some variance is an interesting mechanic

**Comment by GTNH-Colen** [comment]
> i am personally in favor of using odder fluid quantities in lategame stuff. Adds more complexity to it than the Nt material cost in a way. Recipes don't always need to be easy to do, and having some variance is an interesting mechanic

You could literally argue with yourself in a darkened room.

This would make the recipe more expensive but less deliberately awkward to automate, it is fairly standard practice that all recipes using molten materials should be in multiples of 144 or some factor of it. Not everyone is obsessed with using volumetric flasks for everything.

**Comment by draknyte1** [comment]
jUsT uSe FlAsKs

**Comment by 0lafe** [comment]
you could use cells here as well. Then theres all the sfm stuff. OC has to have something too. If you fluid extract you can batch process 36 recipes with 25 ingots. Hell, im sure PR has an option to craft this lol

More complex = good
Especially for a UHV recipe
This shits UHV lol, it can take a little more than

**Comment by leagris** [comment]
> More complex = good

@0lafe please elaborate how recipe complexity is good for higher tier recipes.

I don't agree with this. I think higher tier recipes are already good with higher tier machines, more energy requirements, because complexity is already a solved problem with infrastructure.

I think good recipes are providing content rather than complexity. Especially at higher tiers, complexity is not an incentive to deploy new machines and infrastructures. It is for lower tiers sure, especially when logistic requirements becomes a necessity between HV and IV.

**Comment by Cleista** [comment]
I am fine with either 100mL or 144mL costs, but I just want to say that I object to any balancing decisions being made around the existence of OC or SFM. Players should **never** be forced to use either solution to automate.

**Comment by 0lafe** [comment]
Adding complex recipes, or unique features that make them logistically different, employ an enjoyable and well done challenge mechanic. Power and stuff is fun and all, but unless there's some challenge in the creation of the power gen, or the processing of the infra, etc, it's not really going to be difficult. 

I'd argue infra as a lone req seems more fitting of HV-IV. While more complex mechanics add content in the sense of challenges the player needs to over come. The idea of handling a different type of input personally sounds a lot more interesting than simply a recipe with these ingredients. 

Especially when tiering up and "progressing" with much of these things, you're often tasked with simply doing the same thing over and over. Tiering up a hatch, adding more AE patterns, or even refilling a PA. It all doesn't really change much. It's nice to have some things to break up the mechanics, and offer some alternative gameplay. Combine that with it having a small challenge to it, and it seems like a pretty good thing to keep. 

>Boo sfm/OC 

I don't think you're ever put in a position in which that's the case. I'm also unsure how it's related due to the cells/flasks/ingots that work with this recipe

**Comment by Cleista** [comment]
It's because you brought it up, "Then theres all the sfm stuff. OC has to have something too."

It's good advice for people trying to automate it but should be irrelevant for discussions about balancing the pack.

**Comment by draknyte1** [comment]
For once, I agree with @0lafe...

I try do that same for my higher tier recipes as well. 

A bit of complexity at that point in the game isn’t really a costly challenge anyway, it’s moreso a logistical one. 🤷🏻‍♀️😂

**Comment by boubou19** [comment]
using 100 mb instead of 144 mb is just making it more difficult just for the sake of it, it adds nothing more: one stupid way to work around it would be to dedicate a lcr with a ulv input hatch and fill it constantly: where is the fun in that? If you are at uhv, neutronium is easy to make. Also it's not in line with others recipes using molten fluids from metal ingots so it should be changed to 144mb

**Comment by draknyte1** [comment]
Imagine not using cells of 1000L and doing batches of ten. 🤦🏻‍♀️

Making it cost 44% neutronium for the sake of consistency is a worse argument than what @0lafe and I are suggesting.

**Comment by 0lafe** [comment]
Trying to justify reduction in interesting gameplay mechanics by elongating recipes is pathetic. Trying to do it while not meaningfully impacting the recipe isn't good either.

**Comment by boubou19** [comment]
then make it a multiple of neutronium nuggets: 100 mb is 6.25 neutronium nuggets

**Comment by 0lafe** [comment]
*.*

**Comment by leagris** [comment]
A nugget is 16 mb or L. And I agree, forcing non-multiple of 16 on molten fluid is a pure pointless made-up annoyance. It just make the game experience worse.

**Comment by 0lafe** [comment]
Smh. You can use ingots alone in the 100L recipe, like what's the issue lol. I feel like you need to be more creative with your thinking here. Lots of things aren't ever forcing you down a specific path, but have many clever work arrounds.

**Comment by GeicowithaBango** [comment]
It would also think about changing certain materials, Pico wafers come pretty late, and those components just arent represantative enough. *cough* Dreamcraft circuits *cough* *cough*

**Comment by boubou19** [comment]
what is the issue with using 96 mb instead of 100? like you can use nuggets to automate it regularly, but you can also use oc/sfm

**Comment by leagris** [comment]
> what is the issue with using 96 mb instead of 100? like you can use nuggets to automate it regularly, but you can also use oc/sfm

He wants you to batch 4 recipes at a time or loose 4mB of Neutronium for each circuit.

I bet if was @0lafe decision, he'd choose a prime number like 101, so you are forced to streamline the production to a dedicated set of machines or use OC/SFM/EC2 to feed the exact 101mB.

**Comment by GTNH-Colen** [comment]
> Imagine not using cells of 1000L and doing batches of ten. 🤦🏻‍♀️
> 
> Making it cost 44% neutronium for the sake of consistency is a worse argument than what @0lafe and I are suggesting.

That doesn't solve anything though, neutronium ingots are 144L each so how does making 10 at once help? You'd end up with 7 ingots making 1008L forcing you to waste 8L. Realistically what will happen is people will just add a dedicated hatch on their LCR for molten neutronium when these issues come up as @boubou19 states. Wow much complexity.

I and others would rather pay 44% more for a consistent recipe than deal with the pointless annoyance of using 100L of a fluid like this.

**Comment by leagris** [comment]
Using 100mB of Molten Neutronium per circuits, means you need to craft 3600 circuits before you return to a natural integer of neutronium ingots for 25 ingots.

**Comment by Anarack** [comment]
NUGGET: 100L of molten neutronium per pico wafer. LCM between 100 and 16 is 400, so 4 crafts at 25 nuggets.
INGOT If only using ingots thats 3,600 L of molten neutronium from 25 ingots for 36 pico crafts.

Not sure how you got 3600 circuits.

**Comment by leagris** [comment]
> Not sure how you got 3600 circuits. edited fix thank you for catching this!

**Comment by GeicowithaBango** [comment]
Whats the purpose of havin a higher tier if everything stays as convenient as it was before?

**Comment by boubou19** [comment]
sure pissing players with weird fluid amount is adding this much new challenging mechanic: you can deal with it with lowtier means in comparison to UHV. If you want to add challenge, pls use something that cannot be bypassed with stupidly cheap ways such as a constently filled ulv input hatches. When there is one way super easier than the others, the majority will go for the the super easier way, this seems to be common sense. Personnally, if the recipe stay like that, i'll just use the ulv input hatch. if the recipe uses a multiple of 16mb for fluid, i will consider to make the use of nuggets and make a little infra for it. A multiple of 144mb would be the best, but a 44% increase feels somewhat unreasonable.

**Comment by 0lafe** [comment]
The 44% increase barely changes the power. I'd suggest you check the math on the cost increase to see how little it does. Ulv hatch works, but it also locks down a hatch to Nt only. I wouldn't say it's the best, but simplest with the most drawbacks, which seems fair

**Comment by nikitinalexx** [comment]
This mechanis is not interesting because it can be easily bypassed.
For example I have 8 pretty stupid fluid amounts. What I do is make an ME Interface, attach 8 fluid tanks, each with a translocator to stock keep the Volumetric Flask for example with 99, 101,.. etc amounts. Now I just make an AE recipe, that says "when you push 1 ingot, you get a single 99 volumetric flask with that fluid out". And because I have a stock keeper for flasks, eventually sometimes, a 1 more 99 volumetric flask will go into AE network which is fine, because it will be simply used in the future.
But if there is a lot of different flasks, then it will be a certain problem, because automated LCR has a Buffer Chest which can hold only 9 different flasks, which will actually limit that LCR to 9 recipes. And building a new LCR is not a fun mechanic.
But if you think it is fun, then do the whole purpose of you introducing crazy fluid amounts is to force people to build more LCR? Makes no sense.

**Comment by Cleista** [comment]
It's a surprisingly common sentiment among the regulars that you're supposed to use one machine per recipe.

It's also a common occurrence that the official servers have less than 10 TPS. Completely unrelated I'm sure.

**Comment by 0lafe** [comment]
@nikitinalexx that is one way to do it that's very limited. You can easily do it without a recipe limit. Considering people use a single machine per recipe, this seems like a good idea to keep. Encouraging people to not be boring is always nice

**Comment by GTNH-Colen** [comment]
> Encouraging people to not be boring is always nice

Encouraging people to **play my way** is always nice.

Fixed that for you.

**Comment by leagris** [comment]
I propose to target maximum annoyance with prime number count of ingredients with prime number of output.

Lets say 1103 L of molten neutronium to produce 11 pico wafers using 7 Amp  @ 7919 EU/t for 16127 ticks.

**Comment by 0lafe** [comment]
Non multiple of 2 times are too easy, and why not 8191v? 😭

>Encouraging people to play my way is always nice.

Imagine being so bad you think that things can only be done with the ways I explain them. Is that why you use my GT filtering assline model? 😂😂😂😂🙏

**Comment by GTNH-Colen** [comment]
> Non multiple of 2 times are too easy, and why not 8191v? 😭

Lmao what trash are you on about this time, this isn't even comparable and anyone who knows the GT power system knows this. Thought you would know better 0lafe.

> Imagine being so bad you think that things can only be done with the ways I explain them. Is that why you use my GT filtering assline model? 😂😂😂😂🙏

Sorry I'll refrain from using GT pipes in future as they are patented under 0lafe 2020.
