### ISSUE TITLE
You can dig through the protected block to the block behind

### ISSUE THREAD

**Issue by Eason134HK** [GTNewHorizons/GT-New-Horizons-Modpack#6496]
#### Which modpack version are you using?
2.0.9.0
#
#### If in multiplayer; On which server does this happen? 
delta
#
#### What did you try to do, and what did you expect to happen?
I have nothing to do while waiting for my miner on Mars to mine but I accidentally found a bug
#
#### What happened instead? (Attach screenshots if needed)
You can dig through the protected block to the block behind

#
#### What do you suggest instead/what changes do you propose?
No suggestions, just found a bug

**Comment by interestingusernam3** [comment]
What?

**Comment by leagris** [comment]
A limitation of plug-ins.

Because the protection plug-in runs on server and just ignores the client pretending a block was broken.

Although the client still believes on itself the block has been broken and allows the player character to target the block behind with the raytrace computation client-side no longer blocked by the block that client think was removed.

Then it transmit player interaction with the block behind to the server. The server trust the client saying player interacts with a block, regardless if there is a line of sight to it since line-of sight check is a client-side only ray-trace computation.
