### ISSUE TITLE
GT bees mutation rate seems not doubled when i have researched mutation in Forestry escrotoire

### ISSUE THREAD

**Issue by TataTawa** [GTNewHorizons/GT-New-Horizons-Modpack#6513]
#### Which modpack version are you using?
2088

All the magicbees bees, binnie bees is correctly doubled when researched.
GT bees mutation rate seems not doubled when i have researched this mutation in Forestry escrotoire

**Comment by Glease** [comment]
> doubled 

This is simply not how bee researching works. As it is configured now, the increase of mutation chance is the maximum of 150% multiplier (relative) or 0.05 increase (absolute) , e.g. 

- a mutation with 0.30 chance (after housing, frame, etc modifiers) will become 0.35 when you have researched it. Here the limiting factor is that 0.05 cap.
- a mutation with 0.05 chance (after housing, frame, etc modifiers) will become 0.075 when you have researched it. Here the limiting factor is that 150% multiplier.

You might just not have experimented enough. Many advanced mutations have low base rate, so your feelings might just be the result of bad luck.

BTW this section of logic is pure vanilla Forestry, so either everyone fails or nobody fails. [Configuration options exists](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/blob/09bdd88729301fbbfd64030cad70844099a0136f/config/forestry/common.cfg#L46-L56) but they haven't been changed ever since this repo is created.

**Comment by leagris** [comment]
Been discussing this very topic with @Dream-Master a couple weeks ago as a way to incentivize escritoire research as individual involvement and teaming efforts as escritoire research papers can be given to othe rplayers to benefit from it.

**Comment by TataTawa** [comment]
thank you glease
