### ISSUE TITLE
[Mixer] Conflict Circuits

### ISSUE THREAD

**Issue by MotiasF33** [GTNewHorizons/GT-New-Horizons-Modpack#6534]
#### Which modpack version are you using?
2.0.9.0qf4
#

- Circuit 1:
- Cupronickel, Black Bronze, Black Steel dust
![изображение](https://user-images.githubusercontent.com/47714084/90967672-71728700-e4eb-11ea-9186-d315b4952268.png)
![изображение](https://user-images.githubusercontent.com/47714084/90967661-3c663480-e4eb-11ea-905a-8f8c779ec841.png)
![изображение](https://user-images.githubusercontent.com/47714084/90967693-b8f91300-e4eb-11ea-8b67-fcffafa0969d.png)

**Comment by Cleista** [comment]
@0lafe, we talked about this, the entire point of circuits is preventing overlapping recipes with the same circuit, so this should be fixed. 

You can disagree with this all day with your "it's technically possible to fix by making more multis" argument, doesn't make it good game design and this isn't a fix that has any sort of catastrophic consequences.

**Comment by 0lafe** [comment]
Way to remove interesting mechanics while keeping the optimal route as simple as possible lmao. What the fuck are you even tryna accomplish? No logistics mechanics on anything? No setup and press a button to make an item? God that sounds awful. 

The purpose is for recipes that *can't* exist without them. Say you had another recipe with Cu, Au and Sn, then that would need a different circuit than bronze. No they aren't to segregate recipes so your dumb ass can have a flawless setup with no work lol. 

What makes it good gameplay is that it gives many options for something, and scales the utility of the options pretty well with complexity. What makes the change here bad gameplay is that it flattens any difference between setups, and reduces complexity to essentially 0. 

>Why can I shove all my inputs in the machine at the same time and always have it work!!! >:(((((((( I want my AE to do it all for me and it's not and that makes me maddd

Lol don't do this. Try analyzing your options for achieving something in game, rather than attempting to make the game easier to fit your setup. Complex logistics are one of the few fairly interesting things we have in the pack, and really helps to break up the monotony of the fake idea of "progression". Really strengthens the idea of progression through achieving something novel, and introducing new challenges

**Comment by Anarack** [comment]
or just use a alloy smelter for the small list of things it can be used for. Though personally I don't care either way on this issue as by the time you reach ae this conflict in particular is rare.

**Comment by Cleista** [comment]
A recipe conflict that is practically not possible to know about until your automation fails isn't interesting game design and arguably likely not even intentional. 

Just because a design flaw forced you to make something slightly more complex than usual doesn't mean it isn't a design flaw and shouldn't be fixed. Your "complexity" is going to just be an extra hatch or machine for 99% of people who have this problem. 

Want complexity, get it via a new machine or mechanic, don't keep broke shit broken because it forced you to have a workaround.

**Comment by damug** [comment]
Yeah, but where is the recipe conflict here?  Is it just because some of these recipes on the same circuit share at least 1 of the same dust?  That's not really a conflict.

**Comment by Cleista** [comment]
The recipes share enough dusts that you will occasionally get unintended autocraft results.

**Comment by DuskNite** [comment]
Not ingame so cant check but if i remember correctly there is another conflict

Bronze (copper + tin)
Invar (nickel + iron)
Cupronickel (copper + nickel)
