### ISSUE TITLE
Blank Wooden Tiles

### ISSUE THREAD

**Issue by TheN1K0L4Z** [GTNewHorizons/GT-New-Horizons-Modpack#6552]
#### Which modpack version are you using?
2.0.9.0
#
#### If in multiplayer; On which server does this happen? 

#
#### What did you try to do, and what did you expect to happen?
Spawn Wood Tiles from Extra Trees
#
#### What happened instead? (Attach screenshots if needed)
![2020-08-28_12 16 20](https://user-images.githubusercontent.com/5202981/91596012-1ba64080-e92a-11ea-8c0c-0e825b3d9191.png)
Look under the doors! Are these normal?
#

**Comment by Prometheus0000** [comment]
Maybe? Are they? What's a wood tile?

**Comment by jonathan-ng** [comment]
Looks like extra trees custom patterned tiles made by the woodworker and glassworker. I was just trying it out and I can't make them normally, so it seems broken.

**Comment by Dream-Master** [comment]
I guess we break binnies mod code a few versions ago. Not sure what it cause

**Comment by leagris** [comment]
The wood type NBT data was removed from blocks because it was applied to doors, fences and so on, and not saved on harvest, so the harvested ones could not be stacked with the crafted ones. This piece of code need further fixes to:
Only enable wood type on wood tiles and the other combined wood/tinted glass blocks: (fences, gates, glass blocks and panes, doors?) and have this NBT data preserved on harvest so there must not be a difference between harvested and crafted item version of these, so they are again stackable.

**Comment by Dream-Master** [comment]
@leagris what you suggest ? reverse the commit or do some code changes that it will work again ?

**Comment by Prometheus0000** [comment]
I guess it's fixed?

**Comment by wildejackson** [comment]
This issue still persists in 2.1.1.0
