### ISSUE TITLE
[Eta] Is it possible to get "No Life" rank? 

### ISSUE THREAD

**Issue by MotiasF33** [GTNewHorizons/GT-New-Horizons-Modpack#6561]
#### Which modpack version are you using?
**2.0.9.0qf4**
#
#### If in multiplayer; On which server does this happen? 
**Eta**
### After adding the void miner , the passive income $ becomes 0
**Before reaching void miner, I was able to get 4kk**
I think that rank No Life can be obtained from some kind of passive income, not half a year of grinding
![изображение](https://user-images.githubusercontent.com/47714084/91687948-8e512f00-eb69-11ea-826b-a0ae2c1eecad.png)
_In the meantime, something like this_
### I think need another ways, have ideas? 🍵

**Comment by GTNH-Colen** [comment]
You can get ~60000 per hour max because of the money limit, this means it takes ~70 days to reach 100m grinding 24/7 (Unrealistic without automation tools). It was never meant to be reached, if they removed the money limit then it would be doable but in its current state 3+ months of solid grinding every hour is just not realistic.

**Comment by boubou19** [comment]
Ask Cinobi how he did it.

**Comment by GTNH-Colen** [comment]
> Ask Cinobi how he did it.

A staff member added the rank manually, he didn't earn it.

**Comment by MotiasF33** [comment]
Impossible
