### ISSUE TITLE
Suggstion make cadmium batteries actual nickel cadmium batteries

### ISSUE THREAD

**Issue by redmage17** [GTNewHorizons/GT-New-Horizons-Modpack#6576]
We don't use pure Cadmium Batteries IRL so why not  make a the batteries reflect that (Pet peeve as an IT guy)

**Comment by leagris** [comment]
Do you also want NiCd batteries to have charge memory and loose capacity if not fully depleted before recharge?

**Comment by redmage17** [comment]
Sure I may have to accept that to implement a buff.At the point cadmium is  kinda (but not really)viable it is hard to obtain. A 50/50 nickel cadmium compound would be a noticeable buff.

**Comment by Cleista** [comment]
No one really uses Cadmium batteries due to the scarcity but they're also inferior to Lithium IRL, so buffing Cd batteries isn't the appropriate way to give the element more use IMO. 

We could nerf the ProjectRed phosphors/illuminar powder to use tiny piles of rare metals like Cadmium/Selenium/etc. (which is a practical application of them IRL) and substitute dyes with those colored items in GT recipes, but that seems like a nerf for the sake of nerfing and I don't know if most people would like that.

**Comment by Prometheus0000** [comment]
See also https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/4893#issuecomment-569187348
