### ISSUE TITLE
[LeafDecay] BarnardaC  leaves - leaf decay bad working

### ISSUE THREAD

**Issue by MotiasNotMe** [GTNewHorizons/GT-New-Horizons-Modpack#6600]
#### Which modpack version are you using?
2.0.9.0.qf4
#
### Chopping Barnarda C trees no causes leaf decay.
![изображение](https://user-images.githubusercontent.com/47714084/92985015-735eb300-f4b7-11ea-82d5-e80b17c1e802.png)
### For leaf decay need update block of leaves.
![изображение](https://user-images.githubusercontent.com/47714084/92985029-a0ab6100-f4b7-11ea-9071-737e966b134c.png)

**Comment by Prometheus0000** [comment]
Do you mean fast leaf decay (from fastcraft), or any decay at all? Also, try removing fastcraft.

Also, are you chopping the trees normally, or using something like a lumber axe? I know BoP's bamboo also has this problem, but those break in a different way.

**Comment by Cleista** [comment]
Fast leaf decay works with most trees chopped with lumber axe, it just doesn't work with a few specific trees (slime trees also have this problem, you have to update a leaf).

**Comment by Prometheus0000** [comment]
I just saw that it's added by Randomthings through ASM? https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/6486#issuecomment-670883061

So try removing that as well. I really thought it was fastcraft though.

It would probably be best to fix it in GS or EP or whatever adds that planet, since I doubt removing either of those mods would fix it in any case.

**Comment by Dream-Master** [comment]
@glowredman can we changed that by any chance?

**Comment by glowredman** [comment]
@Dream-Master I'll look into it.
