### ISSUE TITLE
Negative cool-down in coins coins coins

### ISSUE THREAD

**Issue by 905Sunny** [GTNewHorizons/GT-New-Horizons-Modpack#6620]
#### Which modpack version are you using?
2.0.9.0
#
#### If in multiplayer; On which server does this happen? 
Modded Minecraft Club
#
#### What did you try to do, and what did you expect to happen?
So, I bought something in the quest, waiting for it to cool down. I expected it to count to zero and refreshes the quest
#
#### What happened instead? (Attach screenshots if needed)
It somehow dropped to negative value and everytime I connect to that server, it starts at 0s and starts dropping, meaning the quest is never refreshed
![2020-08-29_18 43 42](https://user-images.githubusercontent.com/44795811/93021349-b5e9d200-f614-11ea-9486-e11309a58ebf.png)

#

**Comment by Dream-Master** [comment]
known issue not sure if we can fix that .

**Comment by boubou19** [comment]
do you know if an operator entered edit mode? i know it freezes the cooldowns when it's on

**Comment by MotiasF33** [comment]
i think is only visual bug

**Comment by Prometheus0000** [comment]
Similar to #6360, #5540. The question is if it's _every_ repeatable quest, or just some of them. Like, if they're supposed to refresh right away, or the ones where you're supposed to wait a while.

**Comment by Prometheus0000** [comment]
![image](https://user-images.githubusercontent.com/8517039/93139956-a5d30080-f6af-11ea-9290-412555884f59.png)
![image](https://user-images.githubusercontent.com/8517039/93139744-512f8580-f6af-11ea-8c0a-c2f20dede1c9.png)
The main point here is Repeat Relative. However if the problem is with the unix server timestamp or whatever I heard before, I'm not sure if it would actually fix it. Plus it's only on servers.

Also, Locked Progress might be useful for a couple things, but not for most to avoid the mentioned performance hit.
