### ISSUE TITLE
[RFC] Should we increase the cooldown on rewards quests

### ISSUE THREAD

**Issue by Prometheus0000** [GTNewHorizons/GT-New-Horizons-Modpack#6634]
#### Which modpack version are you using?
2.0.9.0 QF4
# 
Apparently some people just buy all their parts until HV or something. This is pretty ridiculous, so I'd like to suggest increasing the cooldown on these quests from 20-60min to more like 6h-18h to prevent this.

The question is, why do these quests exist? So people can skip content like this? Or to allow people to get by if they have trouble finding a specific material? Of course this would mostly apply to circuit parts, and other machine parts.

We could also make them more expensive instead, as more quests have been added, the rewards have become cheaper comparatively after all.

**Comment by MotiasF33** [comment]
What kind of quests are u talking about?
Coins-coins-coins?
I think very few people use these quests at all, but with cd+, they will completely stop

**Comment by Prometheus0000** [comment]
Yes, the ones for circuit parts and such on that tab. I'm not saying it _has_ to be 6h, I want to see what other people think. After all, I didn't use them at all.

**Comment by NoX-programer** [comment]
IMHO, that quests are already are some kind of useless, because it's much easier to me (at MV) to calculate resources and craft stacks of circuits on my own rather than wait c/d to buy some very few components. I'm used to doing this in one operation (group of actions).

**Comment by Cleista** [comment]
I'm actually in favor of removing cooldowns from all buy quests or turning them into shaped crafting recipes. 

On servers, players already borrow infrastructure to skip tiers, and in single player people cheat in resources all the time because of timegates. Making the shop more viable to use would _increase legitimate play_ rather than the opposite. Doesn't the pack already have a problem with tons of people quitting at or before LV? Why nerf a mechanic that's not lucrative to people who know what they're doing?

**Comment by shawnbyday** [comment]
I've said this in the past and I don't mean it in an offensive way but "we" spend a lot of time over-tuning the hell out of the early game. Once you get to IV-ish the quests get fewer and further between - which is fine but it would be nice if "we" spent time on sections of the game at a time instead of always coming back to things like this or early game balance/nerf stuff somewhat randomly. Like bug fixes and quest fixes are always ok but pick a section to focus on for each "release" that is done and work them and the progression that way. Again just an opinion...not trying to stomp on feet.

**Comment by Prometheus0000** [comment]
If it's only a tiny minority that do this, or it's not really realistic, that's fine. I just want to see if it's a problem or not.

I just saw someone in discord a couple days ago who said they got to HV just buying stuff, so it seemed like there might be a problem.

**Comment by NoX-programer** [comment]
I see none of those are owerpowered/imba, also they become available only when you already reached the technology and crafted some. At least, at MV and below. So if you find a quest unbalanced, name it.

**Comment by Houstonruss** [comment]
Maybe remove the circuits from the shop and lower the microcrafting requirements? The nerf mindset is toxic. Make fixes instead.

**Comment by Dream-Master** [comment]
Longer cooling times are better. Remove the  circuits all idk?

**Comment by Prometheus0000** [comment]
Increasing the cooldown seems very unpopular

**Comment by Kiyanox** [comment]
I would start with increasing the cooldown by 10 or 20%
Why? Because you can simply skip making circuits in LV.

**Comment by Cleista** [comment]
Claims of being able to skip LV via shop circuits are mathematically unsound (you can buy like 4 circuits at a time when you actually need several stacks to progress). 

I suggest we disregard further unsubstantiated nerf recommendations unless they are accompanied by an uncut GTNH speedrun VOD proving the claim that you can skip making circuits in LV via shop only.

**Comment by Prometheus0000** [comment]
There is a consensus on there being no problem, so closing.
