### ISSUE TITLE
[RFC]Change to Large chemical reactors

### ISSUE THREAD

**Issue by LewisSaber** [GTNewHorizons/GT-New-Horizons-Modpack#6636]
#### Which modpack version are you using?
2.0.9.0QF4
#
#### If in multiplayer; On which server does this happen? 
private
#

#
#### What do you suggest instead/what changes do you propose?
Make Large chemical reactor(LCR) stop working when one of output hatches is full,it will lead to increasing of server perfomance because players wont need to build redstone scheme for each of their LCR to stop fluids from voiding, together with this it will also make it be easier to settup.

**Comment by Prometheus0000** [comment]
This behaviour is probably inherited by all multis, so it would probably be all or none. GT++ does this, so it's definitely possible. The question is, do we want to dumb down multis and their use? As convenient as it is, that may be too easy, and this is the tradeoff for using a multi. If you don't want this behaviour, use a singleblock would be my opinion.

**Comment by MotiasF33** [comment]
I think, it was useful to be switch the voiding mode with a screwdriver, like in T.F.F.T

**Comment by Devtron3D** [comment]
It would be useful for some setups to have the option to turn voiding on/off,  like the distillation tower I always leave running, and just void some stuff as the rest I need.
Same with LCR if a secondary output is to say water and or oxygen, and I don't want that, let it void and give me the main product I want.
I know some multis already stop if the output hatch is full

**Comment by 0lafe** [comment]
What if when hatches are full, they start placing fluid sources in the world

**Comment by Devtron3D** [comment]
I would love that, that would add another factor to the game play. But what about stuff that are only gas?. Fluids would work

**Comment by 0lafe** [comment]
Maybe fluid sources that rise instead of fall? Like thaum goo lol

**Comment by 0lafe** [comment]
If we wanna get real fun with it, it could be cool to have a corrosive mechanic to some of them. Make them eat through your pipes/logistics/building/etc

**Comment by Prometheus0000** [comment]
We could make use of that not gas-safe thing if we really wanted to go down that route.

**Comment by Impos913** [comment]
Multiblocks shouldn't be so dumb to void outputs as you use complex circuitry in its crafting. They should be able to stop running if the output is full ¯\_(ツ)_/¯. It would be more realistic also.

**Comment by feliser** [comment]
make multiblock explode if the hatches are full

**Comment by Impos913** [comment]
Stop with troll in github at least

**Comment by feliser** [comment]
The point is that you can think of the fluids clogging up the machine and causing damage. Maybe increased rate of maintenance issues could be cool

**Comment by interestingusernam3** [comment]
f***** casual

**Comment by Prometheus0000** [comment]
Try to keep the discussion polite, ok?

**Comment by leagris** [comment]
**There are ways to satisfy all of concerns:**
- Hardcore player prefer features which require effort and involvement.
- Casual players like QoL features and expects that: if single-block is smart enough to not overflow void its output, multi-block shall be capable of it.
- Server owners and users usually appreciate features to lower the computational load.
- Add-on authors appreciate changes not affecting the API their own implementations.

**A solution to satisfy all the above:**
- Add a `noVoid` or `smart` NBT tag to existing output hatches and buses.
- A Multiblock controller could check if the output is NBT tagged and decide if it checks the inventory or tank has enough room for the next recipe, before proceeding.

**No code change for existing controllers or add-ons:**
As a voluntary implementation, existing controller tiles would work unchanged, they would just ignore the NBT tag and not check inventory / tank, and void output if no room left as before.

**Good for hardcore or casual players:**
Mod-pack maintainers would have control on the kind of recipe or action is needed to enable the `noVoid` tagging on the output blocks.
- Could be a crafting recipe with block + (consumed) fluid / inventory level emitter cover to get a `noVoid` tagged version.
- Could be a screwdriver action on in-world block consuming tool durability.
- Could be a screwdriver in crafting-grid alongside itemblock consuming tool durability.

**100% Backward compatible:**
- Already assembled multi-blocks would not have a `noVoid` NBT tagged output blocks, so they would continue to operate exactly same as before.
- Add-ons, multi-blocks which are not code updated to know about the `noVoid` tag, would continue to use output blocks exactly same as before, regardless of NBT tag.
- Since it would only rely on an NBT tag; existing `checkMachine` methods would still recognise the output blocks because BlockID and Meta values would be unchanged.

**Comment by GTNH-Afx237v7** [comment]
Thanks for the detailed suggestion which I highly appreciate. Would love to see this implemented. Could also be a feature for output buses.

**Comment by 0lafe** [comment]
>Multiblocks shouldn't be so dumb to void outputs as you use complex circuitry in its crafting. They should be able to stop running if the output is full ¯_(ツ)_/¯. It would be more realistic also.

`>Implying the circuits you craft are more complex than the in world automation asked of you. Smh

**Comment by Impos913** [comment]
You wouldn't need much complexity for basic fluid amount reading and stopping the machine I believe.

**Comment by Prometheus0000** [comment]
I think if we allow non-voiding it should be a new, very expensive hatch. Or hatch upgrade, like the muffler item. Otherwise, it just seems like dumbing things down. Do you not enjoy setting up a system to turn it off when full? Are we going to allow turbines to turn off automatically when full next?

**Comment by Impos913** [comment]
It is the opposite of dumbing down. Multiblocks are so dumb to continue working when full. This is about making them smarter.

**Comment by Prometheus0000** [comment]
Yes, which dumbs down the _usage_ of them.

**Comment by leagris** [comment]
> Yes, which dumbs down the _usage_ of them.

You would be able to continue to run redstone signals for flow control as you did before if you feel like it makes the game more interesting and inline with your play style, and if it cause no significant issue on your server.

As a simple reminder for why multi-blocks were introduced in the first place:
- It was to save space and the number of required ticking tiles.

Now, when a multi-block requires an external infrastructure of ticking tiles redstone, logic blocks for flow control, this just nullify the saved ticking tiles compared to many single-blocks that don't need external flow control.

**Comment by mitchej123** [comment]
https://github.com/GTNewHorizons/GT5-Unofficial/pull/412

**Comment by Impos913** [comment]
Multiblocks voiding output should be considered as a major bug and be fixed in my opinion.

**Comment by Impos913** [comment]
Can we reopen this please? @leagris stated some very good ideas and people upvoted the idea and as it is not being worked on it looks like the downvoting minority wins this one ¯\_(ツ)_/¯. I would very much appreciate if someone works on this.
