### ISSUE TITLE
Possible issue with thermos/mod saving many files

### ISSUE THREAD

**Issue by BlackAce21** [GTNewHorizons/GT-New-Horizons-Modpack#6651]
#### Which modpack version are you using?
2.0.9.0
#
#### If in multiplayer; On which server does this happen? 
ProsperCraft
#
#### What did you try to do, and what did you expect to happen?
Nothing, expected the server to run smoothly xD
#
#### What happened instead? (Attach screenshots if needed)
Over the course of the last few months, and about a year ago before this, we ran into many problems with time outs occurring regularly every 5-10 minutes to the point where the server was unplayable. I managed to use a warmroast session during the server timeouts to figure out what was going on and I believe the same thing is happening again. https://i.imgur.com/dAN0rsw.png

I suspect that something in the code base either in a mod or in thermos is iterating through all the player data files and doing it very poorly. We have around 50,316 player data files on the server. I believe we had way more before when this happened. I am in the process of moving a majority of them out of the folder to correct the problem but I would much rather get to the source of this issue.
#
#### What do you suggest instead/what changes do you propose?
Uncertain. I mostly wanted to point out that this is a thing and it is happening and see if anyone else is having similar issues. Due to it potentially being the sheer amount of player data files, I have doubts although I'm sure someone could write a script to login a bunch of fake players and test this in a dev environment if they were so inclined. Mostly want to post about it and see if anyone has anything to add or discuss.

**Comment by Prometheus0000** [comment]
Is this the same as https://github.com/alkcorp/GTplusplus/issues/731?

**Comment by BlackAce21** [comment]
Most likely yes, it's as if the world stops but because it takes so long the client just times out. I know its related to saves because of the profile information I've been able to gather. I am fairly confident the source for us specifically is the sheer amount of player data files we have to work with. Every time I tidy up that folder the problem seems to lessen significantly.

**Comment by mitchej123** [comment]
Which folder do you cleanup? Player data, or chunk data?

**Comment by BlackAce21** [comment]
Player data, the server has time outs with and without this though because its pretty beefy already xD its several years old. I will update this if we find that removing a chunk of the player data files tones down the time outs though.

**Comment by KaneHart** [comment]
Without looking you said 5 Minutes Means your using Thermos. in the Bukkit file you have a save interval of 6000 I think = 5min in ticks so yes it's your world save (auto save) that is trashing it. 

We also have the same issue with forge not thermos as well.

At this point were considering actually switching to thermos as you can tweak this a bit better but also change the save interval from 45 seconds to 5 Minutes.

@Prometheus0000 wrong tag 100% a forge / mods issue sadly.

**Comment by KaneHart** [comment]
**Just wanted to add more to this and testing I have done:**

- I have the issue on Windows 10 & Ubuntu
- I have the issue on no java flags or shit ton of java flags
- Tried multiple diff Java Hotspots like sun, openjdk, graalvm, etc
- I have the issue on AMD & Intel 3900x and 9900k (Pretty much some the best cpu's especially per core performance. 
- I have the issue with Forge or Thermos. (Diff is 45 seconds and 5 Minutes (bukkit config setting).

At this point were considering moving to Thermos just so we can change it from 45 seconds to 5 Minutes or whatever time because we can via the bukkit config... But does not stop that stupid pauses...

**Comment by Prometheus0000** [comment]
Didn't you say on discord it was fixed by adding/removing fastcraft @KaneHart ? That's noteworthy even if it doesn't solve the main issue.

**Comment by KaneHart** [comment]
Yeah we don't have the issues at all anymore since adding fastcraft to the server side.

**Comment by Dream-Master** [comment]
isn't Fastcraft a Client-side only mod ?

**Comment by mitchej123** [comment]
> isn't Fastcraft a Client-side only mod ?

It works on the server, but likely has thermos incompatibilities... because Thermos.

**Comment by BlackAce21** [comment]
Was checking my email for an unrelated reason and saw that this got more traffic. Since we recently solved this issue I am going to update ya'll on what happened, at least with us.

Our server uses an M.2 solid state drive for the primary minecraft directory for performance reasons. Something I didn't actually realize however was that our logging system was also being tied into the m.2 drive and has been functioning like this since this server box was created about 5-6 years ago. In case you can't guess where this is going, to make a long story short, our "super fast" m.2 solid state drive was reading at a whopping 11mb/s and writing at about 7mb/s. This was causing MAJOR bottleneck during world saves and causing the timeouts and other issues we have been having.

I highly recommend to anyone having similar issues to install monitoring applications on your boxes to check drive read and write speed to make sure they are performing up to code and if they are, move onto GC settings for proper concurrent GC handling. Those 2 things seem to have the biggest impact on lag that occurs during save the world operations and random timeouts in general.

Since we replaced our hard drive I have yet to find a link between file amount in the player data folder and any meaningful lag but that could be because we replaced the drive with another m.2 which is just stupid fast even compared to an average solid state drive so I have no meaningful way to really test this out.

That's all from me, sorry for the delay in responding to this xD

**Comment by KaneHart** [comment]
Still old and wanted to say I have this issue even with Thermos / Crucible sadly. Like I said this happens in Windows, Linux, AMD, Intel, etc. The only fix that does not work now because were using Thermos / Crucible is fastcraft... They tweak something with the level.dat saving.... It's the bloody gzip stalling out it seems and or maybe collecting the data to throw into it.

Best I can do is stuck with a nasty lag every 30mins.

I tried checking logs, etc and monitor HD usage, but found no issues. Like I said I tried this on 2 totally diff pc's, specs, os, etc.

Unless there is some sort of tweak I can do on the OS itself maybe to allow it's job to handle better haha. At this point I highly doubt RAM Disk would solve it. Does not seem to be a read/write issues for us. 

So happy your issue is solved those BlackAce21 :)
