### ISSUE TITLE
Nerf TC4 Wand Focus

### ISSUE THREAD

**Issue by ENNISHIBUYA** [GTNewHorizons/GT-New-Horizons-Modpack#6670]
#### Which modpack version are you using?

#
2.0.9.0 QF4

#### If in multiplayer; On which server does this happen? 

#
Single Player

#### What did you try to do, and what did you expect to happen?

#
I tried to change the recipe of Wand Focus. Nerf TC4 Wand Focus

#### What happened instead? (Attach screenshots if needed)

#
![1](https://user-images.githubusercontent.com/34373971/93859050-b0b11500-fcef-11ea-8a0a-ef9388ac3794.png)
![2](https://user-images.githubusercontent.com/34373971/93859056-b3136f00-fcef-11ea-90e8-4599078055a1.png)
![3](https://user-images.githubusercontent.com/34373971/93859062-b4449c00-fcef-11ea-9887-b0ddc363dcb7.png)
![4](https://user-images.githubusercontent.com/34373971/93859065-b4dd3280-fcef-11ea-9812-31c7b9f37d66.png)
![5](https://user-images.githubusercontent.com/34373971/93859071-b60e5f80-fcef-11ea-9de7-dfa220d66227.png)
![6](https://user-images.githubusercontent.com/34373971/93859077-b73f8c80-fcef-11ea-9854-1864d4da21e9.png)
![7](https://user-images.githubusercontent.com/34373971/93859079-b7d82300-fcef-11ea-83a5-4e19f40e140e.png)
![8](https://user-images.githubusercontent.com/34373971/93859081-b9095000-fcef-11ea-986f-163d9048b71c.png)
![9](https://user-images.githubusercontent.com/34373971/93859085-b9a1e680-fcef-11ea-83ed-e20cffdc84da.png)

**Comment by Prometheus0000** [comment]
Maybe mention what recipes you're changing? The tier they change to? And what exactly changed X -> Y (you only have Y). Also the reason for nerfing them, unless it's just because they had default recipes.

**Comment by Rakdarian** [comment]
why would be nice, almost none of these make any sense.

**Comment by Rakdarian** [comment]
A harder recipe for the ichor robes is far from unwarranted though considering the costs of similar items

**Comment by ENNISHIBUYA** [comment]
Since the default recipes are too simple, some focus and their functions are too simple compared to the recipes. So I suggest changing them.
I suggest to change them to EV stage or EV+

**Comment by Prometheus0000** [comment]
Again 
> Maybe mention what recipes you're changing? And what exactly changed X -> Y (you only have Y). 

Did all of them have default recipes? Are all of them EV in your change? What do these even do? _More info needed._

**Comment by ENNISHIBUYA** [comment]
They all have default recipes.
Yes, they can all be made in the EV stage.

**Comment by dvdmandt** [comment]
IMHO, most of these are way too weak and already too painful to be EV+. Most of them are not default recipes and many of the ingredients are also already significantly nerfed. Maybe the warding one make some sense to nerf, but the other ones are IMHO pretty fine, especially as you need to foci manipulator for them to really be useful anyway.

**Comment by Prometheus0000** [comment]
Again Again

> _**Maybe mention what recipes you're changing? And what exactly changed X -> Y (you only have Y).**_

So apparently they're not default recipes too.

**Comment by ENNISHIBUYA** [comment]
The default recipe I said refers to the default recipe in GTNH

**Comment by ENNISHIBUYA** [comment]
The above is not the default formula of GTNH, but my suggestion ：）

**Comment by ENNISHIBUYA** [comment]
The picture is not GTNH’s default recipe, but my suggestion ：）

**Comment by dvdmandt** [comment]
They have slightly changed recipes atm, like clusters instead of shards and things like lenses instead of diamonds or glass panels. They also use more vis and essentia and stuff than normal TC4.

The damage ones can barely compete with entry level crossbows, even when fully upgraded. I keep a fire one for a flint and steel replacement and I used a chainlightning one against bats when I had that warp effect constantly. 

The Equal Trade one is nice for building or harvesting obsidian, which is nice, but not exactly game changing. At the moment, you can put some effort into crafting it while it's still useful, but imho not particularly overpowered. The excavation one is alright when fully upgraded, but you need a pretty decent wand or staff to make efficient use of them, which already requires serious effort. Portable hole is like really cool and all, but also not game changing. Gives very little practical advantage.

The primal one can supposedly make nodes, so I guess it makes sense to have that one somewhat nerfed if that's what the first one is. Should require one of those primal balls that you get in the maze in the regular recipe though, but since those can be found in loot bags or grown by crops, I guess it makes some sense to potentially nerf them. Warding can make blocks more or less indestructible, which is IMHO the only really strong one here.

**Comment by ScriptedPiky** [comment]
I do want to give in my thoughts that Firestone being required is rather aggravating due to the scarcity of trying to obtain it, as well as the Iridium. Additionally, a lot of these are pushed very far into the game and are essentially useless after obtaining a Tinker's sword/crossbow or another weapon that deals significantly higher damage than what you'd actually receive by using the various Thaumcraft wand focuses. Additionally, Steller Alloy is a ZPM+ material due to the Mysterious Crystal composition being required, apparently. In fact, the only way you can artificially increase the damage & usefulness of the wand focui is by using a Hardcore Ender Expansion Charm Pouch with three 60%+ additive(?) charms. But even then, you would still accomplish the same but better feat by using a regular weapon.
