### ISSUE TITLE
Allow SoC wafers to be crafted from higher tier wafers [Feature Request]

### ISSUE THREAD

**Issue by johnch18** [GTNewHorizons/GT-New-Horizons-Modpack#6728]
#### Which modpack version are you using?
2.0.9.0

#### What do you suggest instead/what changes do you propose?
Allow SoC wafers to be crafted from glowstone and up wafers at a more efficient ratio. This is in line with the pattern established by most other PLE recipes.

**Comment by Prometheus0000** [comment]
The problem with this is that the same lens are used on higher tier wafers to make different items, thus causing recipe conflicts. It might be possible if someone went through all of the wafers and lens and changed all the recipes, or separated them out more by exact type instead of colour, but that has its own problems.

**Comment by johnch18** [comment]
It should be noted that I meant Simple SoCs

**Comment by yukieiji** [comment]
I think the name of the issue refers to all SoC wafers(Simple SoC, SoC, ASoC)
The color of the lenses used to craft Simple SoC would compete with the high tier wafers recipes, and what kind of recipe do you have in mind?
