### ISSUE TITLE
The mega ebf and mega vacuum freezer are trash. 

### ISSUE THREAD

**Issue by redmage17** [GTNewHorizons/GT-New-Horizons-Modpack#6759]
Either buff or make a multiblock that isn't trying to be biggus dickus with a trannie

**Comment by Prometheus0000** [comment]
?

**Comment by redmage17** [comment]
They are oversized and the only thing they provide is parallel processing. Not time or energy reduction. They were made because the cryogenic freezer and volcanus exist. And they are shit even without the comparison

**Comment by Prometheus0000** [comment]
Why is this bad? People are all super complaining about how OP GT++ multis are, do you want them to be like that? You can just use several of the GT++ ones instead?

**Comment by botn365** [comment]
comparing to gt++ isent fair sinse that shit is to OP
compared to a normal ebf and vacuum freezer they are prety good multies
they are fore the what would be the same parrellel way cheaper and that parrallel will stop a lot of OC ing happening saving you energy

**Comment by redmage17** [comment]
It's shit even outside the context of GT++ existing

**Comment by Prometheus0000** [comment]
Again, why? What would you want changed?

**Comment by redmage17** [comment]
Either some form of energy or time reduction. For the sheer space both these blocks take(and amount of coils the mega ebf takes). You might as well just make few more multi-blocks. It doesn't have to be as "OP" as GT++ but make it fucking rewarding for fucks sake. I have a similar gripe about the exxon mobile mutli because this pack is insanely polarized over GT++

**Comment by Prometheus0000** [comment]
Do you mean more than the normal EBF bonus? Or are you saying it doesn't get that? My understanding is that it is equivalent to 256 normal EBFs and thus doesn't need 'bonuses', as what you're after is massive parallelization and maybe trading off the bonuses to get it, but I've never actually used it so I can't say for sure.

It's certainly smaller than 256 normal ones.

**Comment by GeicowithaBango** [comment]
You get more parallel processing for a lower cost of coils, i dont see whats the problem. 
for reference, the MBF costs less then 64 single ebfs and does 256 items in parallel- same goes for the mega frezzer.

**Comment by botn365** [comment]
sinse this thing is equal to 256 ebfs and 256 ebs need 4096(2560 with wall sharing)
while the mega ebf needs only 864 coils so if ypu would go for noral ebfs instead of the mega you would need 4.7 times more coils
freezer is ~21 casins per or 5375 casisngs for 256 of them
while the meag freezer is 1178 casings alsomst a 5x reduxtion
now to size
mega ebf is 4050 blocks volume
256 ebs with wallsharing is 6144 blocks volume (wall sharing power/item transport not included)
mega freezer is 3375 blocks volume 
256 freezers is 4608  blocks volume (wall sharing power/item transport not included)
so how are the megas more shit then the normal multies

**Comment by redmage17** [comment]
Who the hell would benefit from this except the 10 or so autists who have reached UV?

**Comment by botn365** [comment]
in IV sure this thing is not wortht it sinse you dont need that much ebf power but in LuV that gose up a LOT anf then is when it is worth making the mega ebf
aslo becous of barts autistic 120 eu/t 2500 second recipes

**Comment by redmage17** [comment]
> 
> 
> in IV sure this thing is not wortht it sinse you dont need that much ebf power but in LuV that gose up a LOT and then is when it is worth making the mega ebf
> aslo becous of barts autistic 120 eu/t 2500 second recipes

You run those in Dedicated EBFs at 120mv.

**Comment by botn365** [comment]
and wait 500 years to make a LuV motor sure

**Comment by redmage17** [comment]
I have 3 running in parallel. Also I think I hit a nerve. Don't want criticism? Don't come out with an under powered, oversized machine that caters to 5-10 people.

**Comment by bartimaeusnek** [comment]
> sinse this thing is equal to 256 ebfs and 256 ebs need 4096(2560 with wall sharing)
while the mega ebf needs only 864 coils so if you would go for normal ebfs instead of the mega you would need 4.7 times more coils
freezer is ~21 casins per or 5375 casisngs for 256 of them
while the meag freezer is 1178 casings alsomst a 5x reduxtion
now to size
mega ebf is 4050 blocks volume
256 ebs with wallsharing is 6144 blocks volume (wall sharing power/item transport not included)
mega freezer is 3375 blocks volume
256 freezers is 4608 blocks volume (wall sharing power/item transport not included)
so how are the megas more shit then the normal multies

"Based on these numbers, i think X or Y would be a valid solution."

Thats criticism. just writing:
> They are oversized and the only thing they provide is parallel processing. No time or energy reduction. They were made because the cryogenic freezer and volcanus exist. And they are shit even without the comparison

>Either some form of energy or time reduction. For the sheer space both these blocks take(and amount of coils the mega ebf takes). You might as well just make few more multi-blocks. It doesn't have to be as "OP" as GT++ but make it fucking rewarding for fucks sake. I have a similar gripe about the exxon mobile mutli because this pack is insanely polarized over GT++

>Who the hell would benefit from this except the 10 or so autists who have reached UV?

isn't criticism. Thats called complaining.

**Comment by Houstonruss** [comment]
Redmage, of course it caters to about 10 people. Those 10 people are the ones that need LASER HATCH SUPPORT to smelt shit faster than FTB normies could even imagine.
Those 10 people also realize that you need way less INFRASTRUCTURE to automate that amount of parallel.
The same 10 people that don't want their precious TPS EATEN by extra machines!

The only buff they need is to be less ugly, and that's something the player has to do.

**Comment by Prometheus0000** [comment]
There's at least 50+ if you go by UV+ tier roles.
