### ISSUE TITLE
Mod request: Streams

### ISSUE THREAD

**Issue by EldrinnElantey** [GTNewHorizons/GT-New-Horizons-Modpack#6766]
https://www.curseforge.com/minecraft/mc-mods/streams

**Comment by glowredman** [comment]
Why do you want it added? What justifies the additional loading time? Besides, this mod requires another mod as dependency and causes immense load (from my experience).

**Comment by GTNH-Afx237v7** [comment]
Plz no. The pack is already heavy enough in terms of performance...

**Comment by Ngar1** [comment]
I use steams in SP together with MoCreatures as an extention of GTNH and this rounded up the nature feeling.

**Comment by mitchej123** [comment]
The mod is ARR, making bug fixes annoying.  I vote no.

**Comment by Dream-Master** [comment]
if we get permission I would vote for maybe if not if vote like Mitch

**Comment by EldrinnElantey** [comment]
> if we get permission I would vote for maybe if not if vote like Mitch

https://www.minecraftforum.net/forums/mapping-and-modding-java-edition/minecraft-mods/2346379-streams-real-flowing-rivers

"May I include this mod in my modpack? You may include this mod and API in a modpack if you provide author credit and a link to this forum thread."

https://github.com/delvr/Streams

**Comment by mitchej123** [comment]
> > if we get permission I would vote for maybe if not if vote like Mitch
> 
> https://www.minecraftforum.net/forums/mapping-and-modding-java-edition/minecraft-mods/2346379-streams-real-flowing-rivers
> 
> "May I include this mod in my modpack? You may include this mod and API in a modpack if you provide author credit and a link to this forum thread."
> 
> https://github.com/delvr/Streams

We want permission to modify, fix bugs, and distribute a modified version.  The license, as provided, is ARR meaning we are unable to fix bugs or change anything without explicit action on their part.

**Comment by Glease** [comment]
Besides the licensing issue, it's **Scala** so I'm not expecting any of us being capable of fixing it even if the author says yes. Either someone can prove it is rock solid, free of bugs and feature complete or the author says explicitly he would still be maintaining the 1.7.10 branch (very unlikely). Otherwise, I'm aganist adding it. You are free to try adding it into your own game though.

**Comment by EldrinnElantey** [comment]
> Besides the licensing issue, it's **Scala** so I'm not expecting any of us being capable of fixing it even if the author says yes. Either someone can prove it is rock solid, free of bugs and feature complete or the author says explicitly he would still be maintaining the 1.7.10 branch (very unlikely). Otherwise, I'm aganist adding it. You are free to try adding it into your own game though.

I understand your doubts, version 1.7.10 is supported by few people.  Anyway, I wrote a letter to the author asking for permission.  I will transmit his answer here.  The decision to add this mod to GT New Horizons is yours.  I would really like to be able to add it because for me it suits the generation of the world

**Comment by repo-alt** [comment]
Scala is ok, license is not

**Comment by Prometheus0000** [comment]
Lag is bad

**Comment by GTNH-Colen** [comment]
Yea I see absolutely 0 reason we need this, just extra bloat.

**Comment by leagris** [comment]
There are a couple of show stopper issues with this mod that is great on its own but not for GTNH:

- Once a custom Stream's flowing water block is destroyed, it will not regenerate, making the streams, rivers with holes, ugly and unfixable over time. (like building bridge pillars across a river and changing your mind). Once  a stream flowing water block has been replaced/destroyed, it will never come back. Even regenerating a chunk will not as the stream flow spread is computed from the source of it. It is also totally random, so re-run of the flow (regeneration) will yield different streams at different locations.
- If one want to use shaders with Streams, it has to custom patch the fsh files with the ID of flowing stream blocks from his own words which can change for each world if block/items are added/removed. So no universally patched fsh file can be created. Each one need its own custom patch.

Unfortunately I vote **NO** because this mod really add something worth with its very good aesthetics, but the above mentioned issues are not worth the trouble and the overload.

**Comment by EldrinnElantey** [comment]
All of you are right there are more problems with this mod than good. He doesn't belong at GTNH.

There is still no answer from the author, if I come, I will write it separately.
