### ISSUE TITLE
One Ring Feedback

### ISSUE THREAD

**Issue by Prometheus0000** [GTNewHorizons/GT-New-Horizons-Modpack#6779]
Since the vote is split between the highest and lowest tiers, and mitch says LuV would make it useless, please give suggestions on how you would like it changed if the recipe was HV (or around there) so that it would be balanced with the rest of the pack. Or if you think it doesn't need to be changed, I guess.

Also please state what you think the ring should be used for (killing bosses, corpse runs, general invincibility, whatever) since some of these are kinda opposite.

**Comment by Prometheus0000** [comment]
So some possible suggestions, not necessarily meant to go together:
- Make it not possible to take off
- Make it harder to take off
- Have it kill you when taken off
- Have it add the ring warp to your character on unequip instead of building up
- Have your warp added to the ring each time you put it on so it builds up faster
- Have permanent effects, like blindness, slow, nausea
- Increased warp amount
- Remove invincibility, but keep invisibility
- Have a counter that ticks down, after which the ring is destroyed, not reset by taking it off
- Make it so you can't damage anything
- Causes permanent blood moon (if that's even possible) while wearing
- Drains hunger really fast
- Drains health while wearing

Personally, I see it as a corpse running item, rather than something to fight enemies with.

**Comment by Rakdarian** [comment]
So as probably the biggest user in the community of the one ring, I think I'm the most qualified to say this. The drawbacks for the average player are debilitating. Blindness+nightvision makes the game impossible to play until one of the effects expire which means consistent inventory juggling. And then theres the wither, water, and chest scramble warp effects which grief your base while using. As far as Invincibility goes, as is it's not foolproof since void and CG damage will still off you, and similar forms of Invincibility that require different kinds of investment, also at hv tier like thaumium fortress armor, nano, anything with last stand, DP poppets, I'm sure there are others and the drawbacks on those are limited by up front or ongoing resource investments, laststand being the biggest offender here as its also stone age viable and armor durability and xp are the only thing gs you need to spend to keep it. 

The main benefit of the one ring over other kinds of general Invincibility is that it doesnt require a lot of thought to actually make it work. And it pays for this simplicity by griefing your base and being an annoying little shit for as long as you wear it. Which none of the other forms of Invincibility have. Since we're nerfing it anyway a good way to go about it is to make the recipe for it gratuitously expensive but possible at the hv tier. It solves the issue of it being just a braindead beeline the ring I to so.ethi g that dedicated players can achieve. I dont think any of the effects of the ring need to be changed positive or negative.

**Comment by Prometheus0000** [comment]
But you can just put it on, do X, then take it off and wait for the effects to end can't you? Or do you leave it on for a long time?

**Comment by Rakdarian** [comment]
You can, which makes it good for death runs as an option but that's not something that people have a problem with, its wearing it for an extended period of time(which granted is something I do but I'm far from the average person) the most practical things you can do with it now is grind nether stars, grind components for nether stars, beeline the twilight cleaver, grind enchanting exp, avoid early game dangers, and do death retrievals. The last two are made obsolete by the time you get to HV thanks to torches and dream master armor and everything else requires you to use the armor for hours on end instead. Which can be done without drawbacks with other gear

**Comment by KiloJoel** [comment]
I believe the main purpose of the ring should be: Have access to warp effects more easily (star farming etc.) and stealth. I personally don't think the invincibility really fits/makes the item too bloated in terms of effects.

So I would propose: Remove invincibility, keep everything else the same.

I'm also not averse to the idea of removing the ability to attack while wearing it, so you'd have to become visible again to fight the wither yourself.

**Comment by KiloJoel** [comment]
Maybe there could be a lower tier ring with no invincibility, then an upgrade available at a later tier that adds the invincibility

**Comment by Rakdarian** [comment]
So couple of things, one the weighting of the warp effects isnt even. In the 400 or so hours of ringtime I have I have had the wither spawn twice.  That's not a reliable way to get stars.

As for the idea of removing the Invincibility, the Invincibility justifies the warp effects. Removing Invincibility and keeping it makes very little sense when chameleon skin exists. Especially when it's going to be a dire table craft. Also removing the ability to attack while granting that kind of Invincibility also exists in a WG cloak which doesnt have the drawbacks associated

**Comment by KiloJoel** [comment]
Yeah, I suppose I am thinking more in terms of where it is now i.e. chest loot item

**Comment by KiloJoel** [comment]
In terms of the wither, i wore it for about 3 hours and got 2 wither spawns, is it possible that some effects stop happening after a certain corruption level?

**Comment by Rakdarian** [comment]
Real warp has it spawning every 10 minutes or so at 500+ warp so I doubt jt

**Comment by KiloJoel** [comment]
According to this code, the ring currently doesn't always provide invincibility. After about 20 minutes, you start randomly stopping being invincible while wearing the ring. But after about 110 minutes, the chance of it happening becomes much lower.

![image](https://user-images.githubusercontent.com/17787093/95516448-23d8ad80-09b7-11eb-95f2-f694d8e8031a.png)
