### ISSUE TITLE
[Suggestion] Make feather duct-tape wings less expensive

### ISSUE THREAD

**Issue by KiloJoel** [GTNewHorizons/GT-New-Horizons-Modpack#6795]
#### Which modpack version are you using?
2.0.9.0
#
#### What happened instead? (Attach screenshots if needed)
As described before in https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/3466, they are very expensive. They take 124416l of glue (1245 sticky resin centrifuged) just for the tape rolls.

They also become available at the same time as the coal jetpack, which is much easier to make, and they have significant downsides that the coal jetpack doesn't: they break quickly, you lose 7 armour points if going from composite vest and they don't work well in rain.

I think right now they're not just expensive, they're simply not worth making.
#
#### What do you suggest instead/what changes do you propose?
I propose that each feather glued cardboard wing should take 1 feather mesh instead of 3. Or alternatively, a reduction in the amount of glue required to make duct tape.

**Comment by KiloJoel** [comment]
Issue still relevant

**Comment by Prometheus0000** [comment]
It sounds like they're terrible, and the recipe is too. So why improve it? To convince people to use something bad?

**Comment by KiloJoel** [comment]
I think that they are fun to use, and would serve quite nicely as a bridge item before you get full flight. Not for everyone, but I think they're cool to be able to make.

They can be used for things like getting extra height while hang-gliding or slowing a fall.

Right now the problem is that you expect more from them given how much effort you have to go through to make them.

**Comment by Prometheus0000** [comment]
Well, I suggest you make a PR for it yourself given that you're the one that cares. Also, I noted that this one takes 6 wing parts instead of 4 like thaumium, so you could change that instead/as well.

**Comment by leumasme** [comment]
The price is still pretty bad, but I think they could be a bit more viable if they weren't so terrible to use:
- Flying Up repeatedly while in mid-air stacks fall distance, making you die instantly from a fall that looks like it was only 10 blocks high
- The Glide ability makes you fall *very* slowly but also does not prevent fall damage
- The Glide ability collides with the glider fastglide. When sneaking while in a glider with these wings on, you move very slowly from the wings slow-fall ability instead of very quickly from the glider speed ability

It feels like all of these should be rather easy QoL fixes, and solving them could make the interesting and challenging (since you have to manually flap the wings) playstyle of the glider more viable.
