### ISSUE TITLE
[Quest] #915 Endermen killing quest only counts vanilla Endermen.

### ISSUE THREAD

**Issue by bedrill64** [GTNewHorizons/GT-New-Horizons-Modpack#6832]
Ver.: 2.0.9.0, Server: Eta

Quest #915 (Kill all the things tab) for killing endermen doesn't count special endermen as kills, only vanilla ones, it should count all of them as kills, for example, lightning ones, etc. Other killing quests do that.

**Comment by Methes** [comment]
Checked the code in betterquesting and Endermen have the same exact code as other killing quests so not sure where the issue is.

**Comment by bedrill64** [comment]
Maybe the issue lies in mobs tagging, nbt or whatever way they are described.

**Comment by Prometheus0000** [comment]
I tried wrestling with NBT and stuff for half an hour, and this just isn't possible. I don't know why it works with the other SMs, there's nothing different in the QB quests either. You can try fiddling with it yourself by going to edit -> tasks -> mob hunt task -> advanced -> targetnbt  ... next to it -> entity -> select an enderman type -> done -> targetnbt  ... next to it -> raw nbt to see all the nbt data. If you select a SM enderman, there's and entry under forgedata that has the SM info. Removing this (and other things) does nothing and does not allow wildcarding. You also can't select multiple entities. I would guess that the enderman are coded differently from the other SM mobs, maybe they don't extend the original enderman or something. If somone wants to (and we can) edit them to work, fine.

Otherwise, I can do is setup an OR for all the different enderman versions. This would reset the counter for all of the versions of enderman when you complete the quest thoug. Presumably we would lower the required amount. Or I could setup several trigger quests to trigger the enderman quest completion, but you wouldn't be able to see your progress, and if you completed another one before grabbing the rewards it would be wasted. I think. I haven't tried it yet.
