### ISSUE TITLE
The Vortex Stabilizer keeps crashing my world

### ISSUE THREAD

**Issue by Prometheus0000** [GTNewHorizons/GT-New-Horizons-Modpack#6870]
#### Which modpack version are you using?
2.0.9.1a dev
#
#### What did you try to do, and what did you expect to happen?
Test unrelated stuff
#
#### What happened instead? (Attach screenshots if needed)
Random crashes
[crash-2020-10-28_18.42.10-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/5455179/crash-2020-10-28_18.42.10-client.txt)
#
#### What do you suggest instead/what changes do you propose?
Fix it so it doesn't crash. Also see #6824, #6857. Which somewhat relate.
And https://github.com/GTNewHorizons/ThaumicHorizons/blob/9e43dc7ffce610051db30cb5fef9d1a272456a3b/src/main/java/com/kentington/thaumichorizons/common/blocks/BlockVortexStabilizer.java#L52 Which it's apparently pointing to?

**Comment by Glease** [comment]
Please check if you can replicate this in a new world. From the log it seems like your world is corrupted somehow.

**Comment by Prometheus0000** [comment]
Which part of the log indicates that? Does that mean it isn't fixed by getting rid of the blocks?

**Comment by Glease** [comment]
It basically says at that stabilizer tile entity's coordinate the world cannot find a tile entity, even when such entity already exists as the caller.

**Comment by Prometheus0000** [comment]
The block entity being ticked? Which it says is air, not the right block, like you said. But if I get rid of the block it's fixed, right? World corruption sounds like a persistent thing, rather than a particular block.

Is it a problem with this TE, or just something that happens do you think?

**Comment by Glease** [comment]
The block is air, but the block entity being ticked is vortex stabilizer. It's like the world is complaining because you fitted the soul of a chicken into a cow. I frankly have no idea how this would happen, unless some stupid mod is circumventing the vanilla code that remove the tile entity when a block is changed. I'd say this might have nothing to do with this particular TE, but some other tile entity, entity, tick handler or cosmetic ray doing stupid thing.

**Comment by Prometheus0000** [comment]
Maybe the planar vortex you stabilize with it?
