### ISSUE TITLE
Bulwark + regen infernals don't die in mob farms

### ISSUE THREAD

**Issue by KiloJoel** [GTNewHorizons/GT-New-Horizons-Modpack#6939]
#### Which modpack version are you using?
2.0.9.0QF4
#
#### If in multiplayer; On which server does this happen? 

#
#### What did you try to do, and what did you expect to happen?
I set up a mob farm using a diamond spike. Expected them to all die from the spike.
#
#### What happened instead? (Attach screenshots if needed)
Bulwark appears to reduce the damage dealt by more the lower the health of the mob. When this is combined with high health, mobs end up only taking 1 damage even from very high damage spikes (I gave one sharpness X wrath X in creative and it still happened).

Then when it also has regen, it regenerates health faster than it takes damage. Fire aspect on the spike helps somewhat, but there are still combos that lead to them surviving for a very long time if not forever.

This is an issue because it leaves more mobs in the world for the server to constantly process.
![image](https://user-images.githubusercontent.com/17787093/99185541-6d4cb300-2742-11eb-8bb0-cac2bfd6ea2a.png)

#
#### What do you suggest instead/what changes do you propose?
Stop bulwark from reducing the damage by so much at low health.

**Comment by leagris** [comment]
I suggest removing infernal mobs entirely.
Infernal mobs:
- Just needlessly annoy beginners (It is really not fun to die in a loop at server spawn, or to have to quit mining because an unkillable vengeance slime spawned in the vein that happens to be in a slime chunk)
- Are no challenge later in game
- Cause useless ticking stress on servers
- Don't really fit with modded.

Instead, players should be encouraged to produced mob drops resources by other means (crops, bees)

**Comment by Dream-Master** [comment]
we rewrite the mod allready a bit maybe we can do more. I think why the mobs not becomes harder the more armor and hearts you have. So they bartable at start and harder at mod game.

**Comment by Prometheus0000** [comment]
Or make them not spawn on the OW?

**Comment by Ethryan** [comment]
Make galacticraft oxygen system only work on players and passive mobs, then maybe tier harder and harder mobs with the different rocket tiers.

**Comment by KiloJoel** [comment]
https://github.com/GTNewHorizons/Infernal-Mobs/pull/5
