### ISSUE TITLE
Gregtech sword doesn't go in the mine and blade slots

### ISSUE THREAD

**Issue by KiloJoel** [GTNewHorizons/GT-New-Horizons-Modpack#6957]
#### Which modpack version are you using?
2.0.9.0QF4
#
#### If in multiplayer; On which server does this happen? 
Eta
#
#### What did you try to do, and what did you expect to happen?
Place the gregtech flint sword in a mine and blade weapon slot
#
#### What happened instead? (Attach screenshots if needed)
It did not allow it to be placed in the slot
#
#### What do you suggest instead/what changes do you propose?
Whitelist this item for use in the m&b slots

**Comment by Prometheus0000** [comment]
You can make a PR yourself you know?

**Comment by KiloJoel** [comment]
I have had a look, but I can't find how to add things to the m&b allowed list

**Comment by Prometheus0000** [comment]
It doesn't look like there's a way to add it to the battlegear2.cfg file, as there is no whitelist, only a blacklist.

**Comment by MrAkells** [comment]
Does this error affect further gameplay? As far as I understand, this devalues TConstruct weapons somewhat. This is true?

**Comment by dvdmandt** [comment]
(since I can't really fix this right now, I'll repost the relevant part of my Discord comment here for reference)

I took a quick look at the Battlegear code, and it seems like this check is what we need to pass to make them functional: https://github.com/GTNewHorizons/Battlegear2/blob/master/src/main/java/mods/battlegear2/api/core/BattlegearUtils.java#L128

It does have a WeaponRegistry in it's API, so I'm thinking we could perhaps register at least the most common early game weapons in NewHorizonsCoreMod or something? Thoughts on that? I could perhaps look into actually doing it if someone could help me with getting the item "id"s for swords, axes, knives, whatever..?
