### ISSUE TITLE
About the idea of resource server

### ISSUE THREAD

**Issue by Eason134HK** [GTNewHorizons/GT-New-Horizons-Modpack#6985]
#### Which modpack version are you using?
N/A
#
#### If in multiplayer; On which server does this happen? 
delta
#
#### What did you try to do, and what did you expect to happen?
N/A
#
#### What happened instead? (Attach screenshots if needed)
N/A
#
#### What do you suggest instead/what changes do you propose?
As i know Nether is going to be reset recently.
The resources required in GTNH is huge.
So there will definitely be more resets in the future.
I think it’s not a long-term solution to ask players to remove there building in Nether every time.
Many large servers are equipped with resource servers so that the main server does not need to be reset
=======================
Benefits of resource server
  0. The resource server can be reset once a month
  1. Since resource servers are to collect resources, resetting every month can ensure that the stock of resources is sufficient
  2. Resetting the resource server every month can prevent players buildings in it
  3. There are currently three official servers run but actually no need to set up three resource servers because three servers can connect to the same resource servers at the same time
  4. If three servers are connected to the same resource servers as mentioned in point 3, there will no longer be a gap between the three servers. Players on different servers can communicate with each other
 5. Player transferring their mining machine or miner that was originally in the main server to the resource server can be effectively and greatly improve the TPS of the main server
 6. Players no longer need to worry about their buildings in other worlds being wiped because only the resource server will be reset
 7. Due to the the world border, the resources of delta's/epsilon's/eta's OW will become less and less, and eventually will even be completely exhausted. (It is impossible to reset OW for granted. Although this may happen a long time later but it will happen oneday)

**Comment by yukieiji** [comment]
I think it very difficult to synchronize items between servers on a mod server such as Thermos (previously, I tried to add a resource server to my server but gave up because I could not synchronize items between servers)....
As there are #3631 as similar problems, wouldn't it be easier to deal with a plugin or a mod for the server?

**Comment by boubou19** [comment]
It's just 1 reset each time the oregen changes, that's not that common. Also, Delta's nether is destroyed as hell, we need to reset it more than the others. Dim reset won't happen often because it's a pain to reconfigure the stargate of each dim,  i will probably spend all my afternoon and my evening fixing the dim spawns.

1)the stock is sufficient on the current dims, because dims are big enough (even the overworld of delta still has plenty of oreveins despite the server being opened in like 2015)

2) Resetting such world needs to be set properly, you cannot just let the players regen the chunks,  rollbacking the dim seems to be the best solution, so you avoid the worldgen, but then there will be the same veins in the same spots, raising the question of the vein control. (like you always take the same vein close to the spawn, because you are lazy to go far away).

3) connecting 3 servers on a same map is a very bad idea: thermos + 250 mods is likely to be instable, + the fact that we need to configure a lot of stuff to make it work. It will also generate a huge cpu load on the "resource server" (we have like 45 cumulated players playing monthly on the officials). So you'll basically overlord the "resource server", making it having low tps, so it will be a pain for players to mine there, so they likely end up using the dimensions of the server they play on originially.

4) there is no gap between the users of the officials, you can go in server chat section of the gtnh discord, then pick the chat of another server to speak with them.(Also, some players had already played on multiple officials, like me for exemple)

5) as i mentionned in 3), the system would likely be unstable, so it may create issues with transferring stuff from 1 server to another, and it would also create inter server trading/tierskipping, which is fine, but would let the players move their stuff from one server to another, ruining the economy on the servers. It will even make inter server grieffing possible, which would be a nightmare to deal with as Operators.

In addition of that, there is a huge downside that makes me want to reject the suggestion without even trying to see if it's possible to setup: adding the cost of another server to the monthly goal. It would not just be a server like one of the official, but one stronger that the others to handle like 45 players on a 250+ modded minecraft in the worse case. So it would be expensive as hell.

**Comment by Prometheus0000** [comment]
Is this different from a mining dim? I assume if the OW ever got mined out one of those could be added that was a copy of the OW (or at least the same veins) instead of this ridiculous nonsense?

**Comment by boubou19** [comment]
i don't know what the mining dim are for, will test on one of the officials.

**Comment by Prometheus0000** [comment]
https://www.curseforge.com/minecraft/mc-mods/aroma1997s-dimensional-world
There's a 1.7.10 version. I believe this was also used in FTB: I. I' not sure about the customization options, but presumably we would just replace all the ore it genned anyway. It looks like we'd have to get permission if we needed to modify it, if that's necessary. There might be other mods that do the same thing though.

**Comment by boubou19** [comment]
the mining portal from utility worlds generate a dim full of dirt/cobble/gravel up to y=64, eternal day. So it's a useless dim. I say we will bother with that when the overworld will be depleted on the officials. (What i have in mind is to pregen an overworld, then upload the map as another dim, so we don't add any random mods to the servers)

**Comment by Prometheus0000** [comment]
Sounds good to me, I don't know how to do that without adding another mod. We'd also need to add something to get there and back, but that can wait until it's more needed.

**Comment by Dream-Master** [comment]
@Prometheus0000 if we need a extra dim we have multivers installed on the server.
