### ISSUE TITLE
Proposed optimisation for ender fluid conduit

### ISSUE THREAD

**Issue by KiloJoel** [GTNewHorizons/GT-New-Horizons-Modpack#7082]
#### Which modpack version are you using?
2.0.9.0QF4
#
#### What happened instead? (Attach screenshots if needed)
Currently ender fluid conduits scan the inventory they most recently input to last, which creates a round robin effect, but it causes a lot of unnecessary lag when repeatedly moving the same fluid.
#
#### What do you suggest instead/what changes do you propose?
Propose: adding a toggle between the current "round robin" scanning and a new type of scanning where it checks the most recent container first. This should allow for significantly less lag when transferring large amounts of fluid.

The button from the item conduit can be reused, so no additional art is needed
![image](https://user-images.githubusercontent.com/17787093/101682343-62dcbb00-3a5b-11eb-8797-60421fdaf75c.png)

**Comment by Prometheus0000** [comment]
Did you forget to link the PR?

**Comment by KiloJoel** [comment]
I haven't looked into how to do this yet. I've not looked at EIO code before, so maybe someone else might be able to do it much faster than I could.

**Comment by KiloJoel** [comment]
discord discussion relating to this:
https://discord.com/channels/181078474394566657/401118216228831252/785593681583013949

**Comment by Prometheus0000** [comment]
I thought you already did it, I was looking at dvdmandt's commits.

**Comment by dvdmandt** [comment]
Since there has been some confusion about what I did (https://github.com/GTNewHorizons/EnderIO/pull/26) and what was proposed here and some other things.. What I did was to make a simple implementation of channels to Ender Fluid Conduits. They act like on item conduits, channel of sender must match channel of receiver. It's mainly a usability thing that make them a bit easier to use and configure for multiple fluids, but if used, it can speed up searches a bit since it only checks filters and tank acceptance if the channels match. 

This issue is about a mode that will keep filling a tank as long as it can accept the fluid instead of (trying to) spread it out between all tanks/recipients accepting the fluid.
