### ISSUE TITLE
[Tooltip] Heat-proof casing count on EBF

### ISSUE THREAD

**Issue by GTNH-Afx237v7** [GTNewHorizons/GT-New-Horizons-Modpack#7115]
#### Which modpack version are you using?
2.0.9.5dev
#
#### If in multiplayer; On which server does this happen? 
SP
#
#### What did you try to do, and what did you expect to happen?
The new tooltip layout for the EBF states that 0 heat-proof machine casings are needed. While the EBF structure does not have a mininum casing count, I found this to be confusing from the perspective of a new player
![grafik](https://user-images.githubusercontent.com/64365566/102327178-a1a3d100-3f85-11eb-93cf-5b59265435f0.png)

#
#### What happened instead? (Attach screenshots if needed)

#
#### What do you suggest instead/what changes do you propose?
Suggest to move the info about the heat-proof casing at the end of the tooltip and change it to "remaining blocks need to be heat-proof casings" or a similar statement

**Comment by Prometheus0000** [comment]
> Suggest to move the info about the heat-proof casing at the end of the tooltip and change it to "remaining blocks need to be heat-proof casings" or a similar statement

The end? It's the 4th line? Move where? (minimum) is added automatically for casing lines assuming that's what you mean? Wouldn't it be better to just add a note below instead of changing every multi's (minimum) line if that's what you mean? Some of them do have a minimum after all. I can also use a different structure info line to put whatever, but replacing 0x heat... with remaining blocks... seems weird to me. Especially if the minimum is changed later.

**Comment by GTNH-Afx237v7** [comment]
Underneath: Output hatch Platline fluids:[...] was my idea.

Didn‘t know about the (minimum) being added automatically.

No, not every multiblock‘s tooltip line about minimum casing requirements. It’s just that this info seems confusing, especially for someone making their first EBF.
