### ISSUE TITLE
Extreme Combustion Generator consumes too much liquid oxygen

### ISSUE THREAD

**Issue by TheBrochacho** [GTNewHorizons/GT-New-Horizons-Modpack#7134]
#### Which modpack version are you using?
2.1.0.0-pre
#
#### If in multiplayer; On which server does this happen? 
Zeta
#
![image](https://user-images.githubusercontent.com/16054364/102705878-279f7080-4241-11eb-91ee-771e45f1d352.png)
![image](https://user-images.githubusercontent.com/16054364/102705892-46056c00-4241-11eb-97d9-0ebdd496aca6.png)

In order to run a single ECE, you'd need to make 1 cell of liquid oxygen every 3 seconds which translates to 20 Vac freezers running at HV (~10k eu/t). You'd be spending ~1/3 of the eu/t produced just to keep the boosted bonus up. If you overclock the liquid oxygen recipe to EV, you'd be spending ~2/3 of the eu/t produced.

#
#### What do you suggest instead/what changes do you propose?

reduce the required liquid oxygen requirement to maybe 32 L/s so that you'd only need 2 vac freezers running at HV per extreme combustion engine

**Comment by KiloJoel** [comment]
Even if it isn't rebalanced, the description is quite confusing by saying "400% efficiency", I think that should be changed to "400% speed" to more accurately reflect the functionality.

**Comment by botn365** [comment]
you need 9600 eu/t woth of VF power to get that mutch liquid oxygen
so its total eff is 70% and only 23K eu/t
lets compare to the large combustion engin
extreme 18L/t consumed 23K eu/t produced or 1300 eu/L
normal 2L/t 6144 eu/t produced or 3072 eu/L
and it only makes 3.7 times as energy netto while using 9 times the fuel

make it only consume 2 times the fuel in boost
this makes it 148% eff on netto energy (not counting energy used to make 320L of oxygen (not liquid oxygen))
so it is less eff then the lce and it still needs a lot of infra to make the liquid oxygen at this rate but also stil make it worth to make

**Comment by Prometheus0000** [comment]
Ok, but what's the suggested change?

**Comment by basdxz** [comment]
> Ok, but what's the suggested change?
> 
> The same as MatthewCOwen?
make it only consume 2 times the fuel in boost

**Comment by KiloJoel** [comment]
I think the oxygen use should maybe be lower too, 20 vac freezers seems a bit excessive

**Comment by botn365** [comment]
with the mega freezer thats not a problem so i dont mined staying the same

**Comment by GeicowithaBango** [comment]
@Prometheus0000 do you understand the issue bot described?

**Comment by 0lafe** [comment]
a powerloss like that seems reasonable given the simplistic nature of the machine. The fact it seems to be meant to be better than the LCE confuses me tbh. Usually copy/pasted tiered up power gen options loose efficiency, and also don't exist in the multi age. Considering you don't put much into this machine thats new, giving it such a bonus seems odd

**Comment by Prometheus0000** [comment]
> @Prometheus0000 do you understand the issue bot described?

Not entirely. I assume that it isn't good enough compared to the LCE I guess? It feels like part of the math is missing. I also think it's fine if it's only used to make LuV tier power until you have fusion up instead of making a bunch of LCEs and transforming up.

Ah, also, bot, when you said 

> make it only consume 2 times the fuel in boost

Do you mean the LOX or the HOG? Because reducing the HOG used that much sounds way too efficient. Or by

> so its total eff is 70% and only 23K eu/t
and it only makes 3.7 times as energy netto while using 9 times the fuel

> make it only consume 2 times the fuel in boost
this makes it 148% eff on netto energy (not counting energy used to make 320L of oxygen (not liquid oxygen))

Do you mean it's power negative right now?

**Comment by GeicowithaBango** [comment]
Bot tried to express the current state of the ECE. currently, the ece will have no efficiency bonus when in boosting mode. you messed up the code, it consumes  4x more Hog to produce 4x more power. that intuitively, doesn’t describe an efficiency boost as mentioned in the tooltip -its more of an free overclocking of voltage if you ask me. 
another issue is the current rate of liquid o2 required to „boost up“ the fuel. its just too high, numbers were proposed here already.

**Comment by Prometheus0000** [comment]
> you messed up the code, it consumes 4x more Hog to produce 4x more power

This is on purpose though. It's not hard to get oil, you can make the MB miner and ender tanks at IV, and setting up complex processing setups is what the pack is about after all, so you can just make more fuel. It's not like it can't be changed if people really want it though.

> that intuitively, doesn’t describe an efficiency boost as mentioned in the tooltip -its more of an free overclocking of voltage if you ask me.

I used the word efficiency because MBs say 100% efficiency when running at full speed, and it says 400% when it's fully boosted.

**Comment by GeicowithaBango** [comment]
> I used the word efficiency because MBs say 100% efficiency when running at full speed, and it says 400% when it's fully boosted.
 sounds very misleading then, i would suggest to change the tooltip then

**Comment by Glease** [comment]
> 
> 
> > I used the word efficiency because MBs say 100% efficiency when running at full speed, and it says 400% when it's fully boosted.
> sounds very misleading then, i would suggest to change the tooltip then

Code wise it works that way, but I guess UI and backend isn't the same thing. If all that's needed is to change tooltip I'll send a PR. No PR right now as I'm not sure if everyone here think that way.

**Comment by Steelux8** [comment]
I think this needs a proper look before the next stable comes out. The HOG cost is obscene, and nears 1 IV amp consumed in many vac freezers to supply the LOX needed for the boost. If I understand the correctly, the boost is just in speed and not efficiency, so the LOX cost is definitely too high. Either lower the needed input to something like 40-60 L/s (no real need to multiply the amount from what the LCE consumes, since Oxygen -> LOX is already a jump in cost) to do 4x speed with the same efficiency, or add a big efficiency bonus alongside the speed to cover that cost.

The pollution amount is also too high. Since pollution is coming back in the next stable, supposedly, that also needs to be addressed.

**Comment by bombcar** [comment]
Can you provide a table of what it does now? Eu/t produced and needed and pollution, alongside some values you think or more reasonable?

Show your work and compare to other similar gens around that tier 🤪. A bonus would be roughly the tps / server load - for example vacuum nukes have a stupid tps hit on the IV conveyors which could be an argument for making other power more usage

**Comment by Glease** [comment]
Read bot's reply above.
