### ISSUE TITLE
Natura Redwood Can't be used in Long wood stick recipe

### ISSUE THREAD

**Issue by Musicalpuzzle** [GTNewHorizons/GT-New-Horizons-Modpack#7143]
#### Which modpack version are you using?
2.0.9.0QF4
#
#### If in multiplayer; On which server does this happen? 
Official Epsilon
#
#### What did you try to do, and what did you expect to happen?
I Tried to craft the Natura Redwood Logs into Long wood sticks
#
#### What happened instead? (Attach screenshots if needed)
The recipe was invalid (see screenshot)
![2020-12-21_16 46 56](https://user-images.githubusercontent.com/54007613/102795032-7ddcf280-43ac-11eb-8563-14958cacc4e3.png)
#
#### What do you suggest instead/what changes do you propose?
I Suggest that the recipe becomes valid

**Comment by leagris** [comment]
This look like a redwood bark or root block which is not a log.

**Comment by Musicalpuzzle** [comment]
I can assure you that it's the log i'll post proof in a bit

**Comment by Musicalpuzzle** [comment]
![2020-12-21_18 22 40](https://user-images.githubusercontent.com/54007613/102804187-b0d9b300-43b9-11eb-92b8-32a69acb5148.png)

**Comment by mitchej123** [comment]
@Musicalpuzzle I don't see an oredict entry for woodLog or whatever it is.  Try looking at another log and see if it's there. 
 Otherwise try turning on advanced tooltips (F3+H) and see if it's on an oak log or this "log"

**Comment by Musicalpuzzle** [comment]
@mitchej123 yeah long Wood sticks has a recipe for each different log except this one

**Comment by Musicalpuzzle** [comment]
It isn't listed as a oredict

**Comment by mitchej123** [comment]
Probably because it uses oredict woodLog... which the redwood doesn't have.

**Comment by Prometheus0000** [comment]
We can add it in the coremod if we want

**Comment by Musicalpuzzle** [comment]
That's the thing the long Wood stick isn't using oredict instead it uses a different recipe for all logs

**Comment by draknyte1** [comment]
> That's the thing the long Wood stick isn't using oredict instead it uses a different recipe for all logs

The recipes are generated by iterating the oredict entries. No entry, no recipe.

**Comment by Dream-Master** [comment]
Guess it is not a bug it is intended. Maybe this wood can only be used for special cases/recipes and need to be processed to planks.
We can check the source no addition via core mod is needed.

**Comment by nman1300** [comment]
Hello, I recently ran into this issue on my playthrough and I did a fair bit of digging out of curiosity and I believe I know why this is occurring. As seen in the following images:

![2024-06-06_02 54 12](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/92449846/234f3120-aa87-4c0a-818b-af778736d7da)
![2024-06-06_02 54 14](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/92449846/2e0dba06-b9b1-4dfe-bca5-f6c4de9ddd1b)
![2024-06-06_02 54 17](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/92449846/e6b10a20-7efe-45b0-b34e-ac1ef7bb3bb4)
![2024-06-06_02 54 20](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/92449846/8a077f0c-d75d-41d0-aeb9-49180d54cc4f)

The Natura redwood blocks: bark, log, and root all have the logWood tag exactly like the standard oak log does. It's not a matter of being in the Forge ore dictionary since all of them are, but Gregtech 5 specifically excludes Natura items from being in the Gregtech-specific ore dictionary for some reason instead. I've reproduced the relevant code snippet below:

```
  @SubscribeEvent
  public void registerOre(OreDictionary.OreRegisterEvent aEvent) {
...
    if ((this.mIgnoreTcon || aEvent.Ore.func_77977_a()
        .startsWith("item.oreberry")) && (
        aOriginalMod.toLowerCase(Locale.ENGLISH)
        .contains("xycraft") || aOriginalMod
        .toLowerCase(Locale.ENGLISH)
        .contains("tconstruct") || (aOriginalMod
        .toLowerCase(Locale.ENGLISH)
        .contains("natura") && 
        
        !aOriginalMod.toLowerCase(Locale.ENGLISH).contains("natural")))) {
        if (GT_Values.D1)
          GT_Log.ore.println(aMod + " -> " + aEvent.Name + " is getting ignored, because of racism. :P"); 
        return;
      }
... 
```

Irrelevant code has been omitted for brevity; the full function can be found on line 1706 at [GT_Proxy.java](https://github.com/GTNewHorizons/GT5-Unofficial/blob/master/src/main/java/gregtech/common/GT_Proxy.java). I believe removing the natura line from this function would resolve the issue, but I don't know whether there would be any side effects from doing so. (All Natura wood logs run into this issue as well, but I presume redwood is the most common since you can get it as a quest reward.) I also don't know if this is a change you would even want to make in the pack, but I figured since the sacred oak and BOP redwood both work just fine, it may be worthwhile to add Natura redwood back in to not have one of the quest rewards be objectively worse than the other two.

**Comment by chochem** [comment]
hard to say why it was excluded as that goes back all the way to 'initial commit', meaning greg most likely. The printed log is concerning and confusing on top.

I guess try and see what happens?

**Comment by nman1300** [comment]
Yeah that seemed to have fixed it. I looked through the other Natura items to see if there were any unintended recipe additions, but all it seems to have done is make all logs, planks, and sticks from the mod properly oredict like expected. You can see the updated recipe below as the second recipe in the image (it cycles through all three kinds of redwood logs):

![2024-06-06_13 18 11](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/92449846/8a87fd31-781e-42d0-b4c3-7c36d7e678e2)

This was done by just removing the Natura restriction in the code from my previous comment. I've created a pull request with this change here: [PR 2641](https://github.com/GTNewHorizons/GT5-Unofficial/pull/2641).

**Comment by Musicalpuzzle** [comment]
Wow I never expected that this would've been fixed after all this time, hats off to you guys!
