### ISSUE TITLE
Lemonade not craftable

### ISSUE THREAD

**Issue by repo-alt** [GTNewHorizons/GT-New-Horizons-Modpack#7166]
#### Which modpack version are you using?
2.1.0.0
#
#### If in multiplayer; On which server does this happen? 
Zeta
#
#### What did you try to do, and what did you expect to happen?
![image](https://user-images.githubusercontent.com/23512002/103149800-180eb300-477e-11eb-80d7-ee2874074b03.png)
![image](https://user-images.githubusercontent.com/23512002/103149811-2957bf80-477e-11eb-8b50-5a922fd09570.png)

**Comment by repo-alt** [comment]
(Sugar/honey are interchangeable, just didn't catch the right recipe in NEI screen)
This also makes paneer uncraftable

**Comment by bluflared** [comment]
I am not too sure if it’s the case since I have started with this pack recently, but IIRC, juices like fruit juices and the such are crafted using either a juicer from Pam’s or the “**Soft** Mallet” to create said juice in a shapeless craft. Whether soft mallet exclusivity on juices is by design or a bug, I do not know. 

Hope that helps.

**Comment by repo-alt** [comment]
I was actually able to make it another day, so the recipes definitely may change order at reboot. But the output does not change within one session (at least I was not able to observe that), and that makes sense, because the recipes are stored in the list, and first found matching recipe is used.
