### ISSUE TITLE
Weird behavior of single block chemical reactor with EIO Item conduits

### ISSUE THREAD

**Issue by Nicouuuuu** [GTNewHorizons/GT-New-Horizons-Modpack#7179]
#### Which modpack version are you using?
2.1.0.0
#
#### If in multiplayer; On which server does this happen? 
Delta
#
#### What did you try to do, and what did you expect to happen?
Using EIO item conduits on top of a Chemical reactor.
Putting a circuit on the second slot of the CR like that :
![image](https://user-images.githubusercontent.com/62377720/103180418-e1c45700-4895-11eb-8ae2-5bff547821cc.png)
The extracting mode of the item conduit should insert the item in the 1st slot
#
#### What happened instead? (Attach screenshots if needed)
None of any item can be inserted into the 1st slot with the conduit setting in extract mode (with or without filters it doesn't matter), it's not working.
But if you put 1 item of what you want to insert into the 1st slot, it will work.
This means that you have to monitorate manually the system.
Indeed if the 1st slot gets empty, no more item would be available for the CR and you'll have to put it by hand.

**Comment by boubou19** [comment]
Happens to me with the advanced chemical reactor IV with sodium formate cells and the configuration 1, except that the input is done directly by another advanced chemical reactor IV with auto output. It was not happening before the 2.1.0.0 update so far i remember. A workaround is to put 1 cell and spam the cells in it so there is always 1 cell in it. 

Might be because of the GT recipe input filter, and it looks similar to https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/2892

**Comment by Nicouuuuu** [comment]
Okay apparently this is because of the GT recipe input filter, which is annoying because it blocks my setup.
Is it possible to fix this ?

**Comment by Nicouuuuu** [comment]
Firstly I put chlorine and then the propene cell, to make allyl chloride and this time it works.
So this is for sure the GT Recipe filter.

**Comment by alphaNOVAircraft** [comment]
That behaviour was kinda commen in previous versions as well.

**Comment by boubou19** [comment]
So it looks like the GT recipe input filter looks for the fluid first to determine the valid recipes. Could it be changed to filter based on everything already present?
