### ISSUE TITLE
Air Filter Multibock need a rewrite

### ISSUE THREAD

**Issue by Dream-Master** [GTNewHorizons/GT-New-Horizons-Modpack#7217]
Since 2.1.0.0 everything burning stuff makes pollution.
We need more versions of the Multi Air Filter (first Block available in LV) because ALks scrubber not works with the new turbine blades.
They need to be worth building and cleaning the pollution better.
Ideas thoughts?

**Comment by Dream-Master** [comment]
As an addition we have to design own single block scrubbers they work different then this one available in GT++

**Comment by Dream-Master** [comment]
Or maybe we can add a more chemical way to cleaning up the air like big factories doing in RL

**Comment by Dream-Master** [comment]
And i am against a turbine blade used up in a air filter. better we using a fan get dirty over time and need to be cleaned same as the air filters.

**Comment by boubou19** [comment]
Make it clean the air with some fibers retaining the carbon in the air. Low tier cleaning fiber could be coton for exemple? (i have no experience about this irl, so if coton does not work feel free to use better stuff).

We could make it more attractive by increasing the area of work according to the energy hatch tier. And why not use this multiblock as a way to get liquid air? because right now we have to vacuum freeze the compressed air cells or use the air intake hatch.

**Comment by Prometheus0000** [comment]
>  And why not use this multiblock as a way to get liquid air?

It would be very dirty air. And if it gave out liquid air instead of air, it would be weird. Also, it would probably be slow, since it has to filter the air, instead of just collecting it.

**Comment by boubou19** [comment]
>  And if it gave out liquid air instead of air, it would be weird. 
Yes my bad, air fluid is fine. Cleaning the air could be an alternative mecanic before air intake hatches which are gated at end of EV/ begining of IV. But anyways, that would be a side mecanic.

**Comment by Prometheus0000** [comment]
This type of discussion belongs in the pollution rewrite channel
