### ISSUE TITLE
Weird Yttrium-Barium Cuprate Recipe

### ISSUE THREAD

**Issue by alfooscxx** [GTNewHorizons/GT-New-Horizons-Modpack#7219]
#### Which modpack version are you using?
2100
#

####Recipe of Yttrium-Barium Cuprate in Mixer consumes 1008 L of Oxygen instead of assumed 7000
![cuprate](https://user-images.githubusercontent.com/51835571/103460344-875c4800-4d26-11eb-857c-f8d8e5f69a90.png)

#
#### What do you suggest instead/what changes do you propose?
1 Oxygen cell is not 144L. Fix the recipe.

**Comment by GTNH-Afx237v7** [comment]
Originally, the recipe was missing the oxygen completely (https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/6401). Fixed with https://github.com/GTNewHorizons/NewHorizonsCoreMod/pull/133/commits/f7ffbe4f63f6001c6f6cb403c35abb169685b517

The formula says YBa2Cu3O7.

The 1008L Oxygen takes into account proper division when doing the recipe with small dusts (252L Oxygen) or tiny dusts (112L Oxygen). With 7000L Oxygen, the small dusts become 1750L Oxygen (OK), the tiny dusts 777 7/9L Oxygen (would need to be rounded up to 778L.

Personally I am fine with as is, 1008L Oxygen,

**Comment by alphaNOVAircraft** [comment]
1008 is just a ugly number to automate. 
Sure the oxygen value sounds right in your calculation, but we are not balancing that recipe to be realistic. 

If you want you can do 2B of oxygen and the rest oxygen will be lost in the process. If you want to have realism: That compound gets its oxygen part in a furnace and not mixed into it in a mixer, so thats wrong anyways.

**Comment by Prometheus0000** [comment]
I made a mistake, I'll fix it when I get around to it if no-one else does.
