### ISSUE TITLE
Marshmallow Mold Steel Exploit

### ISSUE THREAD

**Issue by JohnDorianSmith** [GTNewHorizons/GT-New-Horizons-Modpack#7309]
#### Which modpack version are you using?
2.1.0.0QF1 (curseforge)
#
#### If in multiplayer; On which server does this happen? 
N/A
#
#### What did you try to do, and what happened?
It's not necessarily what I was trying to do. I believe I found an infinite steel exploit in the game. I noticed in NEI that when making a copy of the Marshmallow Mold in the HV forming press, the Empty Shape Plate is not consumed. Thus, that means as long as you have power you can create infinite Marshmallow molds. In turn, those Marshmallow molds can be processed back into steel dust and then back into steel of course. I doubt this is an intended behavior.

#
#### What do you suggest instead/what changes do you propose?
I think simply the Empty shape plate should be consumed when making a copy of the Marshmallow mold. That way, this infinite steel exploit would no longer exist.

**Comment by GTNH-Colen** [comment]
Shows how much people use this recipe 😛

**Comment by GTNH-Afx237v7** [comment]
This should be here:
https://github.com/GTNewHorizons/NewHorizonsCoreMod/blob/97ca6b34328ad37aacc61d5483833d7beb6555c3/src/main/java/com/dreammaster/gthandler/GT_MachineRecipeLoader.java#L1752

I think it must be

`GT_Values.RA.addFormingPressRecipe(ItemList.Shape_Empty.get(1L), CustomItemList.MarshmallowForm.get(0L), CustomItemList.MarshmallowForm.get(1L), 200, 256);`

instead of

`GT_Values.RA.addFormingPressRecipe(ItemList.Shape_Empty.get(0L), CustomItemList.MarshmallowForm.get(0L), CustomItemList.MarshmallowForm.get(1L), 200, 256);`

**Comment by Dream-Master** [comment]
make a pull request I merge it @GTNH-Afx237v7

**Comment by GTNH-Afx237v7** [comment]
I can do that, however I did not test it as I don't have the necessary knowledge/tools to do so.

**Comment by GTNH-Afx237v7** [comment]
see https://github.com/GTNewHorizons/NewHorizonsCoreMod/pull/154
