### ISSUE TITLE
Crash when placing/breaking Gt pipes

### ISSUE THREAD

**Issue by Samib100** [GTNewHorizons/GT-New-Horizons-Modpack#7324]
#### Which modpack version are you using?
2.1.0.0
#
#### If in multiplayer; On which server does this happen? 
GTNewHorizonsServer-1.7.10-2.1.0.0 hosted on a good host website
#
Hey,
When me or my friend are breaking or placing, there is a chance that the server crash. It's hard to estimate how often it happens but is is quite common (can happen several times a day if have to use a lot of pipe).
I'm linking you some crash logs (i've got tons of it, they are all similar)
https://pastebin.com/WguyqF1Y
https://pastebin.com/1JqdRBdZ

I didn't change anything special in the server (I tried to install fastcraft to solve the problem but it didn't work) . Oh and we are at the end of tier 3/beginning of tier 4 so not even that far in the game

Have you an idea on how i would be able to solve this ? 

#

**Comment by royalarmor** [comment]
I Had The same issue on my world a while ago... When breaking placing anything related to greg my world have chance to crash,  
and the crash in completly ramdom. Sadly, until now no solution
It seens the world get corrupted somehow and  had to start a whole new world to play. My biggest problem within is  that it a COMPLETLY silent problem, I only notice it far long my when old Backups were overwritten, because at time I was messing with Thaumcraft...

Anyway, my inglesh isn't good and I hope this is understandable.

#5856 my issue
#2510 another similar issue

**Comment by mitchej123** [comment]
Bot was having similar issues; it's the machine update thread -- looking into ways to prevent the concurrent modification issue.

**Comment by Glease** [comment]
We should add a config option in GT to not use threading as a temporary workaround for those who had such problems. It's not a ultimate solution but lag is better than an outright crash.

**Comment by Samib100** [comment]
Thx you guys for answering me !
Should I assume that my save is dead ? Or is it a possibility that the threading problem will be fixed one day ?

**Comment by mitchej123** [comment]
https://github.com/GTNewHorizons/GT5-Unofficial/pull/414
