### ISSUE TITLE
Mod Suggestion : Pressure Pipe

### ISSUE THREAD

**Issue by YoungGT** [GTNewHorizons/GT-New-Horizons-Modpack#7336]
https://www.curseforge.com/minecraft/mc-mods/pressure-pipes
Pressure Pipe offers rapid and easy transportation and storage, which can benefit throughout the whole game.

**Comment by Prometheus0000** [comment]
It sounds like liquid ender conduits, but with a completely unbalanced extraction speed. I don't see the point?

**Comment by 0lafe** [comment]
To be fair, this sounds like a better option for fluid AE than fluid AE. 

>Transfer any amount of fluid
Unlimited input/output
Works with all forge fluids and all pipe/tanks from other mods
Can transfer multiple liquids on the same pipe
Filtering by fluid type on input and outputs
Multiple inputs and outputs on the same pipe
Smart distribution between valid outputs
Fully supports Forge Multipart (1.7.2+ versions)

eio conduits super limited especially midgame+ due to their awful throughput. GT pipes are nice but horrible for long distance/lots of fluids. SFM can do it, but rarely do you have sfm networks large enough to reach fluid AE/eio size. Would be nice to have a higher throughput option instead of using things like fluid AE, e tanks, or transferring items instead, 

>completely unbalanced extraction speed

It's not like there aren't sections of the game this could fit well in, both in utility and balance. If it means we can possibly use some less fluid AE things as well,, that seems like a pretty big positive. 

I mean apparently we're probably adding the aether, this seems much more reasonable lol

**Comment by Glease** [comment]
I estimate this can find a good place in late IV+. Not sure about its tanks though.

**Comment by 0lafe** [comment]
looking at them, im not sure we need them. It doesn't list their storage, but they don't seem super unique beyond being a multi. We do have the TFFT which seems better suited for those tiers, as well as arguably too many huge singleblock fluid storages.

**Comment by repo-alt** [comment]
I wonder why people don't usually use controller-less p2p networks for like unlimited fluid transfer rates.

**Comment by GTNH-Afx237v7** [comment]
Probably because few know about this, even fewer how to set it up...

**Comment by repo-alt** [comment]
I can probably write a short wiki page about that.

**Comment by GTNH-Afx237v7** [comment]
That would be awesome!

**Comment by repo-alt** [comment]
https://gtnh.miraheze.org/wiki/Fluid_P2P_tunnels
