### ISSUE TITLE
It's better to move Quest"Data Bank"#2671 forwad to ZPM stage

### ISSUE THREAD

**Issue by iouter** [GTNewHorizons/GT-New-Horizons-Modpack#7365]
#### Which modpack version are you using?
2100
#
#### If in multiplayer; On which server does this happen? 
my server
#
#### What did you try to do, and what did you expect to happen?
--
#
#### What happened instead? (Attach screenshots if needed)
the Advance Data Access Hatch is not enough for your ZPM components. Using data bank to store data stick is suggested in assembler line.
#
#### What do you suggest instead/what changes do you propose?
move it forward to ZPM stage

**Comment by Prometheus0000** [comment]
Do you _really_ need it in ZPM though? I'd have to move around most of the TT quests if I move it to ZPM. Not to mention that since bart added the TT structure check thing I need to move the blueprint and scrench quest/text anyway, but it would make UV even emptier. I'd like to wait on bart doing the rest of the multis first though, so I don't have to type and retype what machines you can use them with though.
