### ISSUE TITLE
Project red autocrafting doesnt return tools

### ISSUE THREAD

**Issue by Ydrec** [GTNewHorizons/GT-New-Horizons-Modpack#7368]
#### Which modpack version are you using?
2.1.0.0
#
#### If in multiplayer; On which server does this happen? 
Singleplayer/Zvezdolet/presumably any server
#
#### What did you try to do, and what did you expect to happen?
When crafting fresh water from water bucket it should return an empty bucket as it does in normal craft tables
#
#### What happened instead? (Attach screenshots if needed)
But when using project red autocrafting bench or project bench any item which should return are deleted, pots, sausers, any tools.  This was working in 2090QF4 and broke somewhere on the way to 2100
![1ehhMHE5Pk](https://user-images.githubusercontent.com/53411693/105491611-9c921a00-5cc7-11eb-8979-61e8f400b66e.gif)

#
#### What do you suggest instead/what changes do you propose?
Unbreak it

**Comment by TheElan** [comment]
I've checked the commits, it supposed to be fixed in commit https://github.com/GTNewHorizons/ProjectRed/commit/20eb8b68e24fc94266df00bbdc91614fb49edd5e and the patch is still there. 

This was fixed somewhere in 2015 and should work, I am not sure why this is happening. @repo-alt do you haveany ideas?

**Comment by HyperCr4ft3r** [comment]
Issue is back in 2.8.4
