### ISSUE TITLE
some part missing in the T3 rocket quest (QoL)

### ISSUE THREAD

**Issue by Eason134HK** [GTNewHorizons/GT-New-Horizons-Modpack#7370]
#### Which modpack version are you using?
2.1.0.0
#
#### If in multiplayer; On which server does this happen? 
delta
#
#### What did you try to do, and what did you expect to happen?
![image](https://user-images.githubusercontent.com/59776356/105513966-ef8ec000-5d0d-11eb-9843-90b6c7f4bacd.png)
![image](https://user-images.githubusercontent.com/59776356/105513981-f4ec0a80-5d0d-11eb-957a-04c7e4fbe876.png)

#
#### What happened instead? (Attach screenshots if needed)
some part missing in the quest
#
#### What do you suggest instead/what changes do you propose?
Add these items to the task
Players can make the required items in one go without needing to find that some parts are missing at the end

**Comment by Prometheus0000** [comment]
No. This was asked to be removed before, we're not adding it back in.

**Comment by Prometheus0000** [comment]
Specifically, there are separate quests only for _new_ parts, and the rocket retrieval quest only asks for the rocket.

If this tier of rocket still asks for all the parts, but is missing some we can reopen it though. But you didn't make that clear.

**Comment by Dream-Master** [comment]
> Specifically, there are separate quests only for _new_ parts, and the rocket retrieval quest only asks for the rocket.
> 
> If this tier of rocket still asks for all the parts, but is missing some we can reopen it though. But you didn't make that clear.

I said you not remove it but you listen to those who dont like complex quests.

**Comment by Prometheus0000** [comment]
I'm not sure which rocket quest this is, or when it starts not requiring all the parts. I can't remember whether it's only the rocket at T4, T3, or T2.

**Comment by Prometheus0000** [comment]
Dream, if you're talking about https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/6448, you said you'd take care of it, but then didn't do anything for over a month. Then I changed it myself so that you don't have to collect all the parts in your inventory again for the actual rocket quest (since people were storing it in the DCT, when we were using that instead of the nasa workbench, and thus failed to complete the task, and had to make a second rocket's worth of parts to complete it), and very clearly stated what I did in a commit you merged: 'Made primary quests for rocket T3+ not require all the parts in case you craft the rocket beforehand because you stored the parts in the DCT or something'.

**Comment by GTNH-Colen** [comment]
> I said you not remove it but you listen to those who dont like complex quests.

This has nothing to do with quest complexity, removing all this junk from the main quest was a QoL improvement and stops users from accidentally crafting a rocket without putting all the crap in their inventory. It was annoying and often led to staff having to manually complete these on the officials.
