### ISSUE TITLE
Diluted Hydrochloric/Sulfuric Acid recipes in the distillation tower are bad

### ISSUE THREAD

**Issue by matt-159** [GTNewHorizons/GT-New-Horizons-Modpack#7418]
#### Which modpack version are you using?
2.1.0.3a
#
#### If in multiplayer; On which server does this happen? 
any

![image](https://user-images.githubusercontent.com/16054364/106395682-68e67c80-63b8-11eb-83af-ab99d73b7f35.png)
![image](https://user-images.githubusercontent.com/16054364/106395731-a4814680-63b8-11eb-8987-df8ec3483338.png)
2 LV distilleries will outperform the distillation tower recipe and use 1/2 the total energy cost

![image](https://user-images.githubusercontent.com/16054364/106395794-08a40a80-63b9-11eb-9852-b6dfcf2009f2.png)
![image](https://user-images.githubusercontent.com/16054364/106395802-1063af00-63b9-11eb-8aeb-fe1c654c4ca0.png)
The same applies for Hydrochloric Acid, 

#### What do you suggest instead/what changes do you propose?

adjust the distillation tower recipe times to make them more favorable to single block distilleries

**Comment by GTNH-Afx237v7** [comment]
Making more of the same tier machine to perform a task is always more energy efficient than overclocking, which the DT does. The DT processes more volume in shorter amount of time. But basically the DT does the exact same thing for these two recipes, if it were to run at LV instead of MV. Additionally, once you can (need) to make a DT you have progressed farther in terms of energy production and can afford the higher total EU cost.
Personally I don’t see why it would need a buff?

**Comment by MatthewCOwen** [comment]
You'd have to overclock the DT to ZPM before that recipe is faster than 40 LV distilleries in a PA for sulfuric or 50 LV distilleries in a PA for Hydrochloric

**Comment by alphaNOVAircraft** [comment]
I think buffing the DT recipe would be fine. Sure the OC are not for free, but a DT is more expensive then the equivalent LV machines, so you payed the price in building it.
