### ISSUE TITLE
Everfull Urn and RemoteIO Water Reservoir gated too high

### ISSUE THREAD

**Issue by Alastors** [GTNewHorizons/GT-New-Horizons-Modpack#7431]
#### Which modpack version are you using? 2.0.9.0 but this is also current in the latest build

#
#### If in multiplayer; On which server does this happen? N/A

#
#### What did you try to do, and what did you expect to happen? N/A

#
#### What happened instead? (Attach screenshots if needed) N/A

#
#### What do you suggest instead/what changes do you propose?
I suggest reducing the gate on the Everfull Urn, there are many items that would do the exact same thing as it and I propose that the titanium plating be shifted down to stainless steel plating as the ability to produce as much water as can be outputted is, to say the least, a very dull idea, with about 4-12 thirsty tanks you can achieve the same ideal of infinite water at a fraction of the cost, a reservoir from EnderIO, or as said earlier the thirsty tanks, in theirselves could fill the need for drilling fluid if that is the issue, for its power, of creating limitless water (which by hv is rendered mostly a voided byproduct) the everfull urn is gated much too high!

I would also like to extend this to the Water Reservoir from remoteIO as it does much the same as the Urn at the cost of much much more titanium!

**Comment by Prometheus0000** [comment]
The thing is, this is the endpoint for water creation, there's no higher level of such. And if it was any easier, people wouldn't even make the other ones. Why make the 4 block limited reservoir, when you can make the unlimited one at the same time?

**Comment by 0lafe** [comment]
>as the ability to produce as much water as can be outputted is, to say the least, a very dull idea

true. What if we introduce water treatment proc chains in LV/MV you need to preform on all in world water to get usable water for recipes?

**Comment by Prometheus0000** [comment]
Please don't suggest nerfing early game more. Also, you can distill water. Make distilled water required in olafecraft instead.

**Comment by Alastors** [comment]
Okay but why make the 4 block reservoir when thirsty tanks would do the same thing?

**Comment by Dream-Master** [comment]
There are always different ways you can progress.

**Comment by Prometheus0000** [comment]
Because 1) magic 2) magic is harder+disliked by some 3) harder to find out about, because magic (recipe locked, plus finding the research), and no quest (I think) 4) I'm not sure, but the recipe for the reservoir is easy, I'm not sure how hard the thirsty tank recipe is, but it might be harder? 5) magic?

**Comment by KiloJoel** [comment]
Also the thirsty tank goes slurp

**Comment by thenextelement** [comment]
sorry to necropost but calling the everfull urn the end point for water creation is genuinely psychotic lmfao, it literally cant output more than 100mb at a time! there is no good reason for it to be gated behind titanium especially considering the choice reward to get one is unlocked well before HV(if you trade with villagers instead of waiting 400 hours to be able to make an eye of ender, whoevers stupid choice that was) let alone the moon.
