### ISSUE TITLE
Wax on, Wax off quest 2405 will not complete

### ISSUE THREAD

**Issue by Obeliske1** [GTNewHorizons/GT-New-Horizons-Modpack#7456]
#### Which modpack version are you using?
1.7.10 The most recent one
#
#### If in multiplayer; On which server does this happen? 
Private server, confirmed in single player
#
#### What did you try to do, and what did you expect to happen?
1, Grew an Oak Bonsai as per the quest "Wax on, Wax off", waited for the seed to grow picked it
2,Waited for growth again picked it received the seed (confirmed item ID)
3, Spawned seed in via commands (confirmed item ID)
4, Force completed the quest
#
#### What happened instead? (Attach screenshots if needed)
1, Received nothing?
2, Quest did not progress
3, Quest did not progress

#
#### What do you suggest instead/what changes do you propose?
Not sure what's going on or what's making completion not count. Do not feel comfortable on this one making a suggestion as to what may be fixed to get it to work.

**Comment by Prometheus0000** [comment]
Did you scan it?

**Comment by Obeliske1** [comment]
> Did you scan it?

I'm sorry scan it? The quest makes no reference to scanning the seed, the item number confirms it's the right item and even spawning it didn't work. Am I missing something?

**Comment by Prometheus0000** [comment]
You scan seeds to identify them. It might require scanning even though scanning is a little later. You need an LV scanner or the cropnalyzer (run it through multiple times to get more info) to scan it. Please check if it works when scanned (in creative if necessary). I believe the magnifying glass causes it to be at scanned 1 level (but only 1) so you can see the name, so that might mess it up/be required?

**Comment by Prometheus0000** [comment]
I determined that it's because it wants the scanned seed (and specific stats). I changed it to ignore nbt like it should be.
