### ISSUE TITLE
[Suggestion] Rock breaker for other cobblestones

### ISSUE THREAD

**Issue by KiloJoel** [GTNewHorizons/GT-New-Horizons-Modpack#7494]
An idea from jimbno in discord which I think would be really good: "it would be nice if you could choose what kind of cobble the rock crusher gave"

The purpose of this would be to provide an alternative to stonelilies, which is not as good (lower yield, needs additional macerate+cleaning steps), but allows an alternative method for people that don't want to do the crops RNG grind.

My idea is that you would need that cobble in the input slot of the rock breaker to produce that type of cobble, and it either doesn't use up the cobble in the input slot, or does use it and outputs 2, so you can re-input to make more.

This would be for
-Red granite cobblestone
-Black granite cobblestone
-Marble cobblestone
-Netherrack
-End stone (longer recipe time or higher power req. than the others)

**Comment by botn365** [comment]
this would be prety OP
currently to get lots black/red granite and marbe is with crops 
these crops are  a must have if your doing crops becous these give realy good products like
oxygen,aluminium, fluorine and calcium
the only one i would be oke with is netherrack
endstone would make geting helium to easy

**Comment by Prometheus0000** [comment]
Even if they had a long time to make? Like 30s or 2m?

**Comment by KiloJoel** [comment]
> this would be prety OP
> currently to get lots black/red granite and marbe is with crops
> these crops are a must have if your doing crops becous these give realy good products like
> oxygen,aluminium, fluorine and calcium
> the only one i would be oke with is netherrack
> endstone would make geting helium to easy

The point of my idea is to make crops not be so mandatory for people that don't like them. But without being a better option. So naturally the recipes can be tweaked so that they are worse than crops to avoid them being OP.

**Comment by Leche-Caliente** [comment]
I'm not sure I understand the idea that crops must the /best/ option when it comes to passive resource generation, and anything that is just as good as them must be OP.

Is the game more interesting when all of one's resources are generated by different skins of the same mechanic (i.e. just a bunch of different crops which all act the same), or when various different resources have different and varied generation options?

**Comment by Prometheus0000** [comment]
> I'm not sure I understand the idea that crops must the /best/ option when it comes to passive resource generation, and anything that is just as good as them must be OP.

Because otherwise no one will use crops given how annoying they are. If you made it so the recipe is the same as getting cobble, no one would ever make a stonelily farm.

**Comment by Leche-Caliente** [comment]
> > I'm not sure I understand the idea that crops must the /best/ option when it comes to passive resource generation, and anything that is just as good as them must be OP.
> 
> Because otherwise no one will use crops given how annoying they are. If you made it so the recipe is the same as getting cobble, no one would ever make a stonelily farm.

Crops can still be useful without being optimal in all cases. Crops give the player a system that allows them to generate any resource in the game in the same way. A player who has enderblossom seeds for instance, will also have a number of other resource seeds which they gained in the process of creating enderblossoms (oilberries for instance), and a farm for each of those seeds can be created in exactly the same way that their current enderblossom farm operates: there is no need for them to spend time learning new mechanics and figuring out an optimal setup for them.

Your logic that the player will never make a stonelilly farm if there is another way of generating black cobble, because crops are so annoying, should also dictate that a player would never make an oilberry farm --bedrock pumps are clearly at least as optimal for passive oil generation as the berries-- yet we know that there are people who do in fact use oilbarries. Most players choose pumps it is true, but the key word is "choose." You purposefully restrict the player's ability to choose by trying to make crops the best choice for every resource.

Furthermore, I also take issue with the idea that crops need to be the best because of "how annoying they are." As I have made clear in the past, I do not think that balancing a mechanic around how much of a pain it is to use is good game design. If crops are truly in such a state that a player will not touch them unless they are the best possible option for generating almost every resource in the game, then the problem to fix is the mechanics of crops themselves.

**Comment by Prometheus0000** [comment]
Changing IC2 code needs ASM/mixins, so it's hard. There's almost no people who can do it. And still has been brought up many times, but little has been done relating to crops since people have other priorities.

If crops were easier, they would get the outputs nerfed into oblivion as a result, you can look up the previous discussions. Or look at bees. I don't always agree with the balance of the pack, crops and bees are one of those points.

You gave an example of an oilberry farm, but realistically how many people do that? Maybe not 'nobody' like I said, but they're probably not doing it for efficiency, but as a challenge instead. Also, stonelillies are one of the easier crops and one of the reasons to get into them, there'd likely be far fewer people using them if the RB option wasn't harder or more costly.

**Comment by botn365** [comment]
its not that crops should be the best but having a passif gen for most resources is somthing that should take efford to get and not 1 machine and with how usfull the products can be of black and red grannite (aluminium and fluorine)

**Comment by KiloJoel** [comment]
> 
> 
> not 1 machine

My proposal would require 3 machines to get what the crops give: rock breaker, macerator and washer

**Comment by 0lafe** [comment]
that's still pretty trivial tho, no?

crops are hard because breeding mechanics are difficult to do easily. rock breakers, and generally making Gt singles is hard to mess up. what if we gave it a mechanic that would rival crops in complexity, thus warranting competitive production? 

could do something like how cobble needs water/lava placed adjacent, but make it require fluids in stages? like it needs water, then lava, then methane in that order to produce granite. or water, lava, then oxygen to make black granite? 

i could also see it being complex enough if it could simply consume some of the fluids placed adjacent? you'd need to automate fluid placement as well as fluid production, which while not the hardest thing, seems more fair as a breeding bypass than a simple single block proc chain. 

seems like there's a bunch to play with here, that could introduce a bit more to the game, as well as provide a good alternative source of a useful item

**Comment by repo-alt** [comment]
Not all the fluids are placeable, but the idea sounds interesting.

**Comment by redmage17** [comment]
> Changing IC2 code needs ASM/mixins, so it's hard. There's almost no people who can do it. And still has been brought up many times, but little has been done relating to crops since people have other priorities.
> 
> If crops were easier, they would get the outputs nerfed into oblivion as a result, you can look up the previous discussions. Or look at bees. I don't always agree with the balance of the pack, crops and bees are one of those points.
> 
> You gave an example of an oilberry farm, but realistically how many people do that? Maybe not 'nobody' like I said, but they're probably not doing it for efficiency, but as a challenge instead. Also, stonelillies are one of the easier crops and one of the reasons to get into them, there'd likely be far fewer people using them if the RB option wasn't harder or more costly.

I've offer a few fixes such requiring different soils. Or making it so most crops don't produce raw resources but augment ore proccessing.However I've been shut down. Anyone thought of disabling IC2 crops and porting to agricraft?

**Comment by redmage17** [comment]
Also this would a tad OP. Free fluorine.
