### ISSUE TITLE
Witchery oven won't cook things other than saplings, making Foul Fume harder to get

### ISSUE THREAD

**Issue by McFrugal** [GTNewHorizons/GT-New-Horizons-Modpack#7499]
#### Which modpack version are you using?
2.1.0.0 with WitcheryExtras-1.1.1.jar so the witch's oven doesn't crash

#
#### What did you try to do, and what did you expect to happen?
I'm trying to get foul fumes, and expected to be able to cook things other than jungle saplings to get them.
#
#### What happened instead? (Attach screenshots if needed)
I can't seem to cook anything in the witch's oven except for saplings.  Can't cook meat or logs.
#
#### What do you suggest instead/what changes do you propose?
Pls fix.

**Comment by Prometheus0000** [comment]
This is the result of my test in 2.1.0.3a.
![image](https://user-images.githubusercontent.com/8517039/108456189-c6dee500-723d-11eb-8d0b-f535ee5df6a5.png)
Saplings other than acacia and dark oak work. Those two just become wood ash, probably because witchery was made before those were a thing. However, none of the logs work. And you can't cook stuff. There might be other recipes you used to be able to do I don't know about.
