### ISSUE TITLE
Add quest to explain how to manipulate fluid tanks in BasicMachine via GUI

### ISSUE THREAD

**Issue by Glease** [GTNewHorizons/GT-New-Horizons-Modpack#7509]
Related PRs: GTNewHorizons/GT5-Unofficial#428, GTNewHorizons/GT5-Unofficial#430, GTNewHorizons/GT5-Unofficial#432, GTNewHorizons/GT5-Unofficial#434
The feature is still under testing on zeta. There were a few bugs but they have all been resolved by now. As this feature is not very obvious we should probably mention it somewhere in quest.

Here is a breif summary of this feature:
1. Left click to attempt filling/emptying _all_ cells held on cursor.
2. Right click to attempt filling/emptying _one_ cells held on cursor.
3. All fluid containers that can be used in a standard gt tank (e.g. supertanks) are supported, including but not limited to water bottles, vanilla buckets, ic2 cells, volumetric flasks, large steel/titanium/chrome fluid cells, pressurized fluid tanks, etc.
4. Can fill/take less than one cell of fluid if the fluid container support doing so.
5. Works on all subclasses of BasicMachine. From a player view, this means all GT single block machines. Compatibility with machines from addons is not thoroughly tested but should work just fine.

**Comment by Prometheus0000** [comment]
I've been testing this and got a crash, do you want a separate issue for it @Glease ?
[crash-2021-02-21_23.35.53-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/6019516/crash-2021-02-21_23.35.53-client.txt)
I used a water bottle on a chemical reactor input.

**Comment by Prometheus0000** [comment]
These are the results of my tests. Anything I didn't mention worked properly.

1) Does not check if fluid is valid for machine
-Machines do not seem to run with invalid fluid though
2) Brewery does not work with regular cells because of size limit
-Probably should mention in quest, rather than something that needs changing
3) Blocks that already have a tank inventory do not work with it. This includes all the SB gens, tanks, and hatches
-I dunno if you want to change this or care. Seems fine as it is to me
4) Using a gigantic volumetric flask or large cell doesn't work right if it fills the inventory, but doesn't use all the fluid from the cell, you can't empty it again with the same cell.
-I guess it only transfers into a cell if it's empty? Working as intended?
5) Doesn't work with one of bart's auto-generated capsule types
-Since there's no recipe, I assume it's unfinished anyway
6) Attempting to use a water bottle on machine liquid input causes a crash!
-Pls fix (you already did)
7) The bottled items from Crops++ don't work with it
-No idea why, they have fluid canner recipes. They seem useless though
8) Seared Tanks don't work (checked with lava too)
-Does anyone care?
9) EIO tank and pressurized tanks freshly crafted or from creative NEI don't work until you place them and remove them.
-I also unconfigured them by running through the crafting grid but they still accepted the fluid so it's not that.
-I don't think you can fix this without messing with EIO, and I can just mention it in the quest, yeah?

**Comment by Glease** [comment]
> Does not check if fluid is valid for machine

You can put invalid *item* into input slots as well, e.g. dump wood into fermenter. If player is consciously placing stuff into the machine, I don't see why should we stop them from doing so.

> Blocks that already have a tank inventory do not work with it. This includes all the SB gens, tanks, and hatches

They have their own ways of emptying/filling. No need to change that.

> Using a gigantic volumetric flask or large cell doesn't work right if it fills the inventory, but doesn't use all the fluid from the cell, you can't empty it again with the same cell.

It only attempt to drain fluid from input tank if an empty cell is used. Probably could use some tweaking here. I'll change it to attempt to drain fluid from machine if an empty cell is used _**or if the input tank is full**_.

> auto-generated capsule types
> bottled items from crops++

What is that anyway? I have totally no idea what you are even talking about.

> Seared tank

It is probably not intended to be used as a fluid cell anyway. It's just a portable tank.

> EIO tank and pressurized tanks 

Yeah it can't be trivally fixed. Please mention it in the quest.

**Comment by repo-alt** [comment]
This is not really related, but after this change input hatch not allowing to take fluids out behaviour looks weird

**Comment by Glease** [comment]
@Technus made it that way in a 2017 commit. I'm not sure what was his intention.

**Comment by Prometheus0000** [comment]
This type does not work:
![image](https://user-images.githubusercontent.com/8517039/108667495-56d39780-74a7-11eb-823c-1275e3289165.png)
Works:
![image](https://user-images.githubusercontent.com/8517039/108667656-af0a9980-74a7-11eb-9d13-da51d7b44834.png)
Works:
![image](https://user-images.githubusercontent.com/8517039/108667670-b762d480-74a7-11eb-9164-93718fda5d3b.png)
You can't get the fluid back out:
![image](https://user-images.githubusercontent.com/8517039/108667737-d19cb280-74a7-11eb-8e48-173b4624c5c5.png)

**Comment by Prometheus0000** [comment]
Actually maybe it's just californium? Others of the same type worked. Probably bart's problem, or has something to do with how fusion fluids work?

**Comment by Prometheus0000** [comment]
These are some of the Crops++ items:
![image](https://user-images.githubusercontent.com/8517039/108668069-6bfcf600-74a8-11eb-80ff-ce2e7b369d9b.png)
![image](https://user-images.githubusercontent.com/8517039/108668115-8636d400-74a8-11eb-86ab-b32e0606c1a7.png)
![image](https://user-images.githubusercontent.com/8517039/108668126-89ca5b00-74a8-11eb-8168-c033e4c9c0da.png)

**Comment by Glease** [comment]
I'm not totally sure what's going on. It might be someone tampering fluid container data in an unintended way, or bart didn't properly registered stuff, or he consciously made these capsules to be automation only.

**Comment by Prometheus0000** [comment]
I don't think anyone will care if it doesn't work, honestly.

**Comment by Glease** [comment]
Then let's just label them as *Fluid Canner only* and call it a feature 🤣

**Comment by GTNH-Afx237v7** [comment]
I have always wondered why brewery allows 750L only...

**Comment by repo-alt** [comment]
3 bottles, like vanilla brewing stand
