### ISSUE TITLE
 server crashed logs

### ISSUE THREAD

**Issue by Varkaus** [GTNewHorizons/GT-New-Horizons-Modpack#7534]
2.1.0.0
[crash-2021-02-25_18.40.37-server.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/6045455/crash-2021-02-25_18.40.37-server.txt)
[fml-server-latest.log](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/6045456/fml-server-latest.log)
thermos server . The server cannot start

**Comment by Varkaus** [comment]
the server cannot start

**Comment by boubou19** [comment]
Can you take the time to fill a template report as shown when you open an issue? Also, it looks like your issue comes from a bad installation of java itself: `/opt/jdk/jdk1.8.0_261/jre/lib/amd64/libawt_xawt.so: libXrender.so.1: cannot open shared object file: No such file or directory`. In the future, for errors like that, ask in the #help channel on our discord server, thanks.
