### ISSUE TITLE
Add some recipes for the bricked blast furnace

### ISSUE THREAD

**Issue by maniifestantes** [GTNewHorizons/GT-New-Horizons-Modpack#7587]
make it so you can make steel using a block of iron with block of charcoal, coal and coke, so we don't have to always go check the bbf (specially if you use charcoal)

**Comment by Prometheus0000** [comment]
I'm pretty sure not using charcoal was done on purpose. And I think you can already use the other two?

**Comment by maniifestantes** [comment]
You can use block of iron, but not fuel blocks

**Comment by maniifestantes** [comment]
Also if you place a hopper, it'll also fill the output slot for some reason

**Comment by Prometheus0000** [comment]
Unfortunately the recipe looks like this:
```GT_Values.RA.addPrimitiveBlastRecipe(Materials.Iron.getBlocks(1), GT_Values.NI, 36, Materials.Steel.getIngots(9), GT_Values.NI, 64800);```
The 36 is the coal amount. None of the recipes are for 5 iron either. So doing this is harder than it sounds, since the recipes partly auto-generate. The code in GT_RecipeAdder would need to be changed, and I don't really feel confidant doing that. I tried adding a 63 and 64 ingot recipe, but it just divides that back down to 1. And I'm pretty sure it doesn't support partial coal blocks.

If someone wants to recode this, feel free. 

Also, you can use the blocks as fuel, just not with the iron blocks.

> Also if you place a hopper, it'll also fill the output slot for some reason

No support for automating it, it's not supposed to be.
