### ISSUE TITLE
RFC: Redstone transmitter in should read all block sides

### ISSUE THREAD

**Issue by repo-alt** [GTNewHorizons/GT-New-Horizons-Modpack#7593]
Currently redstone transmitter (in) cover reports redstone level at the side of the block it is placed at. There is no way to change that redstone level, so it makes the cover useless. I propose to change the cover behaviour to read redstone level at all the sides, so that covers like activity detector might transmit it's state wireless.

**Comment by repo-alt** [comment]
As I see no negative reaction (and not much reaction at all), I'll make it so

**Comment by leagris** [comment]
As-is it is an incompatible behaviour change.

In Gregtech4, there was the Redstone Conductor Cover that allowed selection of the input.
Here is part of the code it used:
```java
   public int onCoverScrewdriverclick(byte aSide, int aCoverID, int aCoverVariable, ICoverable aTileEntity, EntityPlayer aPlayer, float aX, float aY, float aZ) {
      aCoverVariable = (aCoverVariable + 1) % 7;
      switch(aCoverVariable) {
      case 0:
         GT_Utility.sendChatToPlayer(aPlayer, "Conducts strongest Input");
         break;
      case 1:
         GT_Utility.sendChatToPlayer(aPlayer, "Conducts from bottom Input");
         break;
      case 2:
         GT_Utility.sendChatToPlayer(aPlayer, "Conducts from top Input");
         break;
      case 3:
         GT_Utility.sendChatToPlayer(aPlayer, "Conducts from north Input");
         break;
      case 4:
         GT_Utility.sendChatToPlayer(aPlayer, "Conducts from south Input");
         break;
      case 5:
         GT_Utility.sendChatToPlayer(aPlayer, "Conducts from west Input");
         break;
      case 6:
         GT_Utility.sendChatToPlayer(aPlayer, "Conducts from east Input");
      }

      return aCoverVariable;
   }
```

Your implementation changes the Wireless Redstone In Transmitter behaviour to transmit the strongest signal only.

I think the default transmitted In-Signal should remain from the same side as the cover, but then:
1. Either allow selection of the input signal to transmit,
2. Or re-implement the Redstone Conductor Cover that defines what Redstone signal is received inside the Machine's Tile-Entity, and have the Wireless Redstone In Transmitter use this true in signal instead of making the choice itself.

**Comment by Prometheus0000** [comment]
Was the related PR merged, or not? It says closed instead, but says something about force-pushing? Should this be closed?

**Comment by repo-alt** [comment]
PR was not merged, Lea thinks that preserving broken exiting behaviour is more important than the proposed change. Her first suggestion cannot be implemented w/o changing coverdata from int to something bigger. As for redstone conductor - it had different purpose, it was literally a conductor. Anyway, looks like no one is interested in this cover working so we might just as well close that issue.
