### ISSUE TITLE
Let EV quest tab to be opened without moon.

### ISSUE THREAD

**Issue by bedrill64** [GTNewHorizons/GT-New-Horizons-Modpack#7604]
Eta 2.1

Currently, to unlock the EV quest tab there is a requirement to finish the quest related to one of the moon ores. I'd like to have this one requirement removed, so people that gather titanium in overworld can actually progress through EV quests, it will do no harm to quest progression overall, since there is still titanium requirement to open EV tab, and people get titanium from the moon in 95% of cases, making this ore requirement quest obsolete.

**Comment by Alastors** [comment]
Im currently doing that quest myself and honestly disagree with that. I mean would you suggest that adept thaumcraft not be gated by infusion because you can technically get to to the outer lands without infusion via eldritch guardian drops? Just because there is a work around to a specific task doesn't really make it part of normal progression. I mean gating tiers with dimensions starts all the way back in steam with the nether sulfur deal. Just because there are like the crops, and bees, and like the aluminium bauxite method to get titanium pre-moon but like, the moon is the ev gate *because* it is the intended source for titanium and progression. @ me if Im wrong I guess

**Comment by Prometheus0000** [comment]
> Titanium quest already can be done without moon, so I guess there are no reason to block EV by monazite ore

This was set to OR by accident. Or I forgot it doesn't work right. Either way.

@bedrill64 Please use this version of the QB for testing. Load this version in a new world, then hold 64 titanium ingots. It should run a command and complete the Titanium quest for _that player_, but I want to make sure the VAR_NAME works for other people. I also don't know how it would work in parties, but you'd probably have to pass the ingots around to complete it individually. Or it wouldn't work. Fortunately, that isn't hard if you've gotten there already.
[DefaultQuests.zip](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/6209274/DefaultQuests.zip)

Also, if someone else wants to try it, feel free.
