### ISSUE TITLE
constant lightining due to wither + mytown protection

### ISSUE THREAD

**Issue by maniifestantes** [GTNewHorizons/GT-New-Horizons-Modpack#7768]
#### Which modpack version are you using?
2.1.0.5
#
#### If in multiplayer; On which server does this happen? 
Zeta
#
#### What did you try to do, and what did you expect to happen?
I'm currently in my base, with unstoppable lightning because a wither is trying to spawn but it's being held back(it will spawn once i leave my base), but because he can't,you'll be hit by constant lightining( and that will persist even after death).
#
#### What happened instead? (Attach screenshots if needed)

https://user-images.githubusercontent.com/57275066/113647073-7e01b500-9660-11eb-8d4d-43def0d96b1a.mp4

**Comment by Prometheus0000** [comment]
Did lightning and withers have something to do with each other?

**Comment by maniifestantes** [comment]
Yeah, lightning will strike where the wither spawns, which will be where I am currently

**Comment by Prometheus0000** [comment]
Well, I'd say go out of your base and let it spawn? And then reduce your warp. Or go back in time and whack yourself for not listening to both the TC book and the QB's warning about warp.

**Comment by TA0MACHINE** [comment]
it's not a bug, it's hardcore xD
But, in this way I lost all my stuff.  Lightining hitting non-stop and destroy my graves was impossible.
I began destroy a grave on ~ 25% and lightning strike hit again, I died and after respawn I lost everything  (despite being enchanted on soulbound) and lost my previous grave.

**Comment by Prometheus0000** [comment]
That sounds like lighting warp, which is a different issue. Just tough it out (you need the lightning to activate), and put dirt blocks above if you want to be careful.

**Comment by TA0MACHINE** [comment]
I know about block above, but on that time I was in cave and was surprised that lightining hits through blocks

**Comment by ElNounch** [comment]
Can confirm that is wither trying to talk to you about all this warp...
As long as it can't spawn, you will get hit by lightnings, even underground.

First time it happened to me, took a while before I asked other players and understood what was happening...
This is all "by design", but I wish the lightnings be FX only, so you know something bad is happening, but not chain kill you in seconds in a place you expect to be perfectly safe (aka your claimed base...).

**Comment by boubou19** [comment]
Looks like the lightning is meant to be disabled after a wither is spawned, which is impossible if you don't allow mobs in your town: a work around is to /town perm toggle mobs twice: one to let the wither spawn, the other to remove it. 

The question is: is it a bug to wait for the wither to spawn before stopping the lightning, or is it a feature?

Making the wither warp having a defined amount of lightning strikes seems to be a double edged sword: if you spend a lot of time in your base but treat the wither warp as the lightning strikes warp because of the limited amount of lightning strikes, then you could end up being surprised by random withers spawning on you as soon as you quit your base.

**Comment by leagris** [comment]
I'd pose the issue as a more practical gameplay perspective:

- Once player is so warped that he wanders naked, starving and permanently fighting for life with a wooden stick because he is repeatedly dying haunted by lighting strikes,  withers spawning and the other warp effects…

What is the expected gameplay out of this deadly repeat circle except rage-quit or admin clearing warp with a command ?

**Comment by GTNH-Colen** [comment]
A temporary solution is to quickly toggle hostile mobs to be allowed then disable it after the wither spawns in (deleting it). But this is an issue which really could use some addressing, infinite death loops are just bad gameplay full stop.

**Comment by Cinobi** [comment]
https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/1126

ahh, old good issue xD

**Comment by interestingusernam3** [comment]
On servers with mytown, it is currently possible to protect yourself from 100% of possible warp-related deaths and setbacks at early HV.
I don't want to spoil everyone's !!FUN!!, so I'm not going to explain the details.
