### ISSUE TITLE
Plasma Rebalance [RFC]

### ISSUE THREAD

**Issue by johnch18** [GTNewHorizons/GT-New-Horizons-Modpack#7775]
At present, plasma is supremely overpowered. For LuV gen, you just need some deuterium production and a fluid drilling rig in order to reach millions of EU/t. At ZPM, you merely need to cycle molten silver through a system of machines in order to reach 10s of millions of EU/t. Power generation does not develop much from there. It's incredibly disappointing compared to pre-fusion power sources and I think it can be overhauled.
My suggestion:
- Remove Plasma Turbines
- Add Plasma Heat Exchangers that input some kind of metal in ingot or block form and output the liquid form of the plasma and vaporized metal fluid.
- Vaporized metal fluid can be put into an LHE with water (or some "better" fluid that gets bonuses in turbines when used with vaporized metal) to output Steam/SHSteam/etc and molten metal.
- This fluid is passed through turbines as per usual
This would greatly enrich plasma generation and make it far more interesting.

Another concept that could be useful is mixing plasmas to produce more energetic mixtures, requiring multiple Fusion Reactors and getting more energy as a result. 

Another thing that needs to be considered is adding plasmas post-ZPM. Tin Plasma should not be the end-all-be-all of power generation, especially in light of the molecular transformer and void miner.

I'm interested in all of your thoughts.

**Comment by johnch18** [comment]
As for the enhanced fluid, my idea was to use something along the lines of a solution of dissolved tungsten-naquadah alloy and IC2 coolant. Both metals have a high heat capacity so they would effectively "buffer" the heated solution.

**Comment by 0lafe** [comment]
can we address that Sn plasma at the moment is a pretty poor choice of recipe even in its tier? mk3+ plasmas would be nice, but so would removing this simplistic recipe and giving a real mk2 recipe

the rest of this seems good, my only thought would be to make some of the steps not so static. it could be cool to be able to push more fluid into the LHEs to get worse efficiencies, rather than the max throughput being the most beneficial.

**Comment by johnch18** [comment]
Sort of like how BW vats do with output buses?

**Comment by 0lafe** [comment]
nah more like how the LRE works. It doesn't exactly have an input cap, but the more throughput it does, the worse the efficiency

**Comment by johnch18** [comment]
![image](https://user-images.githubusercontent.com/42650497/113756306-74af3180-96ce-11eb-8183-a88173fc669c.png)
That could be cool, here was my idea for the processing chain.

**Comment by alphaNOVAircraft** [comment]
> This fluid is passed through turbines as per usual
This would greatly enrich plasma generation and make it far more interesting.

Judging by the conversion rates between steam and energy transporting that steam would be an absolute nightmare and you would probably need even more turbines then right now (and i already get depressed when i think of all the boring time i spend on my current 300 turbines) 

I also dislike the idea of removing plasma turbines, they are an essential part in all LuV+ bases => removing them would ruin all of them. 

Seeing a decent plasma for ZPM Fusions would be nice, and moving tin plasma to mk3 would also be a welcome change (but pls double the plasma mb/t otherwise it will again completely ruin setups). 

I like the steam idea, but i think it would be terrible to implement / make it balanced. E.g. to replace one large infinity plasma turbine you would need 8 200 000 mb/t, which is a bit stupid.

**Comment by johnch18** [comment]
![image](https://user-images.githubusercontent.com/42650497/113757262-a4ab0480-96cf-11eb-93ba-8ddd38eb6906.png)
Here's my idea for the HHE

**Comment by 0lafe** [comment]
it might be nice to get some mega steam turbine multi instead of using the EV ones

**Comment by johnch18** [comment]
Sort of like a BR turbine?

**Comment by alphaNOVAircraft** [comment]
Then again it would have to be balanced, cz i dont want all of my base to be turbine megas, the sad reallity is that we need plasma to be that op in extreme lategame, until we got a post fusion energy source all of those changes would just remove the pure existence of end game instead of making it more intresting

**Comment by johnch18** [comment]
Maybe at UV we could add "plasma fuel" which uses a mixing mechanic similar to what was mentioned and simplifies power gen? Although that would just delay the issue initially positited.

**Comment by johnch18** [comment]
I do think having single plasmas be less efficient and adding mixed plasmas would be good. It would require more fusion reactors and infrastructure.

**Comment by alphaNOVAircraft** [comment]
Like i said, until we have a bettery energy soruce post UV / UHV i wouldnt redo plasmas, cz e.g. having multiple stages will lead to even more fusion spam etc.

**Comment by johnch18** [comment]
One thing we should think about is people who don't use centralized power gen and transfer plasma

**Comment by alphaNOVAircraft** [comment]
> yea proc chains in reactors imo should be needed for the best fuels in all tiers. maybe even make another mk1 fuel that takes 2-3 fusion steps for people who wanna ball out
> 
> > spamming megas is bad
> 
> i guess if it's like 1:1 with a plasma turbine, but i'm not sure what the difference is between the same volume of blocks making the same power amount. if a 15x30x15 multi makes the same power as the same amount of plasma turbines, that seems like a win in my book. less small tedious setup of individual machines, but similar scale.

Yes having a multi that does the same amount would be fine (and way better for tps), but in that case it would be equal to around half a billion eu/t, so you cant make it "required to start with fusion"

Adding plasma chains for each fusion tier would be nice tho

**Comment by johnch18** [comment]
I'm not saying we completely invalidate plasma as is, I just think there's a lot more we can do with the mechanic. Plasma itself doesn't have to be a great fuel, it could be a component in something more useful.

100% tho tin plasma atm is hot garbage and I say that as someone who uses it.

**Comment by 0lafe** [comment]
>Yes having a multi that does the same amount would be fine (and way better for tps), but in that case it would be equal to around half a billion eu/t, so you cant make it "required to start with fusion"

you can if the rate of production from the turbine isn't static. like different rotor blades increasing eu/t, etc. it can be bulkier in the earlier tiers while equaling the current If blade plasma turbines we have atm. think like mekanism turbines for example, if there's different rotors, those can give different outputs. if the size of the turbine could vary as well, that could be even better

**Comment by 0lafe** [comment]
i also think balancing a zpm tier plasma fuel to generate >100M eu/t isn't a great idea, especially when it just relies on making more of the same thing

**Comment by johnch18** [comment]
![image](https://user-images.githubusercontent.com/42650497/113759929-e12c2f80-96d2-11eb-8424-ab850f7ddaa9.png)
Just as a way to communicate my issue with the way things are, this is a fully functional 20+ MEu/t power generation setup.

**Comment by 0lafe** [comment]
this is why imho we should remove Sn plasma as it is, and force at least a 2 stage fusion recipe for Mk2 gen. it would also be nice if the inputs didn't cycle so cleanly

**Comment by johnch18** [comment]
There's no real reason to be against multi-stage fusion recipes for T2+, because the player still gets 2x the fusion output by virtue of making the first T2

**Comment by leagris** [comment]
Please NO!

Stop reducing the service provided by existing machines instead of providing better alternatives!

**Comment by johnch18** [comment]
We are talking about providing better alternatives.

**Comment by johnch18** [comment]
> This pack is already unplayable by average players with a life.

The weak should fear the strong

**Comment by leagris** [comment]
> > This pack is already unplayable by average players with a life.
> 
> The weak should fear the strong

You wrote 2 hours ago:
> My suggestion:
>
>    Remove Plasma Turbines

NO!

**Comment by alphaNOVAircraft** [comment]
> We are talking about providing better alternatives.

Not really, you dont really want to give alternatives, you talked about removing plasma turbines... You substitute one option by another, not an alternative

**Comment by leagris** [comment]
> The weak should fear the strong

The destructors of the pack must go away for the sanity of the minded weighted persons with a life and no extended obsession with nerfing and microcrafting insanities!

**Comment by alphaNOVAircraft** [comment]
As long as we dont have any power option behind fusion we shouldnt fck fusion

**Comment by 0lafe** [comment]
If fusion is  the only lategame+ power source, shouldn't be resemble the complexity assumed by being in those tiers? Alternatives is great and all, but you don't need alternatives in the initial tiers of fusion. Any alternative would need to be easier to setup than the current fusion options, however the issue is that the current fusion options are way too easy when they appear. 

It's nice that we have lots of alternatives in earlier tiers, but it's also nice that each option fits the tier well. Fusion is a huge step back in complexity from what comes before it, and therefor needs to be adjusted to actually feel lategame.

**Comment by Dream-Master** [comment]
To make this clear. We just have a discussion here and collecting new ideas. We dont change the whole game. balance is very important.

**Comment by Florexiz** [comment]
We should focus on providing lategame energy options (like unfinished TT multis) before tweaking plasma balance imo

**Comment by 0lafe** [comment]
That makes sense for endgame, but doesn't address the issues of plasma in LuV-UV tiers. Imo it's more fun to have engaging mechanics sooner rather than needing to slog through tedium to reach the more enjoyable stuff

**Comment by johnch18** [comment]
Are we really going to pretend that Tin Plasma is not FUBAR'd?

**Comment by alphaNOVAircraft** [comment]
> That makes sense for endgame, but doesn't address the issues of plasma in LuV-UV tiers. Imo it's more fun to have engaging mechanics sooner rather than needing to slog through tedium to reach the more enjoyable stuff

then make a new complex one, but adding more machines to the already over 3000 tile entities (ticking ones) that my energy gen requires

Like i said we NEED tin plasma to be OP atm, cz there is nothing post fusion, i dont want endgame bases to be only limited by the processing power of the server they run on. Sure i can make all of them require 2 more fusions and add another 2500 TEs but i wont even notice the cost of the fusions but instead see my tps get lower and lower

**Comment by 0lafe** [comment]
>Like i said we NEED tin plasma to be OP atm, cz there is nothing post fusion, i dont want endgame bases to be only limited by the processing power of the server they run on. Sure i can make all of them require 2 more fusions and add another 2500 TEs but i wont even notice the cost of the fusions but instead see my tps get lower and lower

Isn't this more of an issue with trying to make LuV+ power gen viable all the way through UEV+? It would be nice for alternatives at that point, it seems wrong to allow such a simple mechanic to extend that far in utility

**Comment by alphaNOVAircraft** [comment]
> > Like i said we NEED tin plasma to be OP atm, cz there is nothing post fusion, i dont want endgame bases to be only limited by the processing power of the server they run on. Sure i can make all of them require 2 more fusions and add another 2500 TEs but i wont even notice the cost of the fusions but instead see my tps get lower and lower
> 
> Isn't this more of an issue with trying to make LuV+ power gen viable all the way through UEV+? It would be nice for alternatives at that point, it seems wrong to allow such a simple mechanic to extend that far in utility

sure it is (and its ZPM+ cz tin plasma, which i would be more then happy to see limited to UV), but there IS NO alternative atm, and as long as there is none we shouldnt nerf stuff. 

If we nerf a energy source in MV, you still have 20 other options, but if we nerf one in UV, that doesnt have an alternative nor a higher tier locked energy source, we just remove the end game

**Comment by 0lafe** [comment]
what is the endgame in this sense? just spamming more Sn plasma to power the same machines you've been using since LuV at slightly higher power levels?

**Comment by GeicowithaBango** [comment]
I wish I could point out to a github issue that i wrote couple months ago, unfortunately thats not possible -thanks for that.

Regarding the LHE to convert plasma into super heated steam, it exist already, its awufully slow and quite frankly, who can be bothered to set up more steam turbines instead of a couple plasma ones.
Tin plasma is absolut nuts as a fusion output, it can be perfectly recycled and it has the best energy density for whatever reason. 
Every change should be welcomed imo, an idea of mine for instance; prevent OC on fusion reactors so that the high-tier recipe will also become the better ones

**Comment by GeicowithaBango** [comment]
> > The weak should fear the strong
> 
> The destructors of the pack must go away for the sanity of the minded weighted persons with a life and no extended obsession with nerfing and microcrafting insanities!

Ah yes, less engineering and more cooking for blockheads. thats what gregtech new horizons needs

**Comment by johnch18** [comment]
Is it so bad to have a pack for people who just wanna nolife minecraft?

**Comment by GeicowithaBango** [comment]
Only people who made a pair of star gates can ask this question D:

**Comment by johnch18** [comment]
bot-sama... I kneel

**Comment by alphaNOVAircraft** [comment]
> Only people who made a pair of star gates can ask this question D:

So now i got a new deadline to finish my stargate, 3 months in case this issue goes stale :) (but should be doable ngl)

**Comment by Prometheus0000** [comment]
I skipped over most of this cuz it's long, so maybe this was explained, but what's with:

> Add Plasma Heat Exchangers that input some kind of metal in ingot or block form and output the liquid form of the plasma and vaporized metal fluid.

What does the fusion reactor have to do with plasma in that case? Nothing?

Also

> Vaporized metal fluid can be put into an LHE with water (or some "better" fluid that gets bonuses in turbines when used with vaporized metal) to output Steam/SHSteam/etc and molten metal.

I'm completely opposed to using steam at this level. The _plasma_ holds the heat, why do you need to pass it to something else?

**Comment by johnch18** [comment]
IRL, current models for producing fusion power involve cooling plasma by heating fluids. Plasma has too high of an energy density to be properly managed by conventional materials.

**Comment by alphaNOVAircraft** [comment]
> IRL, current models for producing fusion power involve cooling plasma by heating fluids. Plasma has too high of an energy density to be properly managed by conventional materials.

Which would be an argument when i wouldnt pass my plasma through fictional materials capable of withstanding million of kelvin and then passing it through a turbine that is made out of the totaly realistic infinity material...........

**Comment by Prometheus0000** [comment]
This isn't real life, we can make it out of neutronium or unobtanium or w/e.

**Comment by johnch18** [comment]
Yes, I am fully aware that we are playing a sci-fi/magical block game for children. I'm just using real life as a model.

**Comment by Prometheus0000** [comment]
Also, I think you asked about other power options? Somewhere? A naquadah rework (see the incomplete GT++ fluid nq if you search discord) and also suggestions around the black hole generator have come up. Both impossible in real life.

**Comment by johnch18** [comment]
Again, me using reality as a blueprint doesn't mean I'm averse to sci-fi stuff.

**Comment by Anarack** [comment]
Another option that does not change how fusion is in the end game is to change how the reactor itself scales. You can tweak the speed multi given by going up one level of reactor. this allows you to keep endgame power output the same if you tweak the recipe to match.

Ex lets say 1 mk 3 reactor makes 1000 KEU/t base before turbines and this same recipe makes 250 KEU/t in a mk2. If you wanted to keep the same mk3 output while nerfing the initial recipe you could change the multi to scale by lets say 4x speed per reactor instead of 2x. This means a mk I would have to produce 62.5 KEU/t of plasma. This scaling could be anything as long as the tick times mostly line up.

**Comment by Glease** [comment]
> 3 months in case this issue goes stale

@alphaNOVAircraft Please stop spreading false information. As we have stated in that bot response (!stalebot) and various other places, any activity inside an issue will reset the stale counter. You can just post a message like `this is still relavent` and bot will be held off for another 3 month. It's not like we require every issue to be resovled inside 3 month since it's made.

**Comment by alphaNOVAircraft** [comment]
> > 3 months in case this issue goes stale
> 
> @alphaNOVAircraft Please stop spreading false information. As we have stated in that bot response (!stalebot) and various other places, any activity inside an issue will reset the stale counter. You can just post a message like `this is still relavent` and bot will be held off for another 3 month. It's not like we require every issue to be resovled inside 3 month since it's made.

Shall i write the IF IT GOES STALE in fckn caps for you to be able to read it?!?!?!?!?!?!?!?!?!?!?!?!?!?!?!?!?!? Where the fck is false information when i explecitly mention that it gets closed IF IT GETS STALLED, like how can you quote me on a correct statement with stop spreading false information? 

IF IT GOES STALE => NOONE RESETS THE COUNTER; NEXT TIME I DO MY BEST TO DELIVER A FCKN EXPLANATION FOR AN IF STATEMENT

**Comment by Glease** [comment]
The way you formulated your sentence make me confused. Maybe I'm dumb after all.

**Comment by botn365** [comment]
i like this idea but instead of water and steam maby carbon dioxide can be used wich needs a more complex cycle
heating -> turbine -> heat recoup -> cooling -> compressor -> heating
and sinse that requires way higer temps to work compared to steam

**Comment by GeicowithaBango** [comment]
isnt it already: plasma —> hit coolant—>steam + water?

**Comment by johnch18** [comment]
Nope, it's plasma -> turbine

**Comment by GeicowithaBango** [comment]
lol yeah, i mean you go the LHE way

**Comment by johnch18** [comment]
The LHE is not involved with plasma power at all

**Comment by Hikari1nVoid** [comment]
Stop these laggy nerfings unless you have a better alternatives.
Multiplayer servers are suffering from these extra machines due to nerfing.(tps:4~7)
Maybe we should have a command for extremely hardcore single players to enable these insane rebalancing.

**Comment by 0lafe** [comment]
maybe people continuing to spam things when they beat the game shouldn't be encouraged?
