### ISSUE TITLE
game crashed whilst ticking entity everburn urns/vis relays

### ISSUE THREAD

**Issue by crystal211** [GTNewHorizons/GT-New-Horizons-Modpack#7801]
#### Which modpack version are you using? 2.1.0.0qf1

#
#### If in multiplayer; On which server does this happen? 

#
#### What did you try to do, and what did you expect to happen? umm it crashed both times while just doing random stuff around the base like looking in ae2 system 

#
#### What happened instead? (Attach screenshots if needed) the game crashed giving me this crash report https://pastebin.com/0QYPNnEH

#
#### What do you suggest instead/what changes do you propose? i realy dont know it says something to do with vis relays/everburn urns

#

**Comment by Glease** [comment]
Doesn't sound like a problem with everburn urn per se, but more or less a victim of someone modifying the world not on main thread. Might be related to #7324?

**Comment by crystal211** [comment]
yea i thouth it might be related to an ae2 dense cable i used to have around the vis relay that a friend mentioned might be a problem but those crashes happened after moved it

**Comment by crystal211** [comment]
scratch that litteraly just crashed again now says everburn urns and tilevisrelay same as last time

**Comment by kozachok3000** [comment]
Bump. 
I got the same issue. The problem is exactly in everburn urns or alchorithm of building node trees. There is a couple of urns connected to one node in my setup without vis relays. I'v got a couple of differend crash reports, and hope that it can help to solve the problem. I've tried to disable urn rendering by opticube but the problem is deeper.
[crash-2022-02-19_23.55.50-server.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/8103858/crash-2022-02-19_23.55.50-server.txt)
[crash-2022-02-19_23.55.58-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/8103859/crash-2022-02-19_23.55.58-client.txt)
[crash-2022-02-20_14.10.51-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/8103860/crash-2022-02-20_14.10.51-client.txt)

**Comment by Glease** [comment]
@kozachok3000 see if this fix your problem: http://jenkins.usrv.eu:8080/job/ThaumicExploration/25/artifact/build/libs/Thaumic-Exploration-1.7.10-1.1.83-GTNH-2-g4f59fab.jar

**Comment by kozachok3000** [comment]
@Glease Thanks, it seems like crashes are gone.
