### ISSUE TITLE
Overtuned Health Pools on High Level Galacticraft Dungeon Bosses

### ISSUE THREAD

**Issue by Erik4556** [GTNewHorizons/GT-New-Horizons-Modpack#7804]
#### Which modpack version are you using?
2.1.0.0

#
#### If in multiplayer; On which server does this happen? 
Private

#
#### What did you try to do, and what did you expect to happen?
Attempted to kill the Io boss, expected to kill it in a reasonable timeframe.

#
#### What happened instead? (Attach screenshots if needed)
Spent 5 minutes spamming left click in a corner as the boss has a 1500 HP pool with an extreme >95% damage reduction (rough estimate through testing).

#
#### What do you suggest instead/what changes do you propose?
Reduce the HP pool of high level GC bosses or remove/reduce the damage reduction  (Ceres and above, only have experience fighting Ceres/Io but I presume the rest follow the same pattern).

#
#### What is your GTNH Discord username?
erik4556

**Comment by Prometheus0000** [comment]
Ok, so the blaze one won't even shoot at me directly, so there's no way to reflect fireballs. The ghast only takes 6 instead of 3 damage. And he's shooting the floor out so you fall in lava too. And the crystal one only shoots at the ceiling, then immediately disappears. 

So they all suck. Also, so does the chest loot.

Weirdly enough, the slime boss has more than twice as much health as the later wolf one.

Maybe someone else who's gone through them all can make some suggestions.

**Comment by Hikari1nVoid** [comment]
All these boss with damage reduction sucks.I'll suggest some armor-piercer weapons.
lawsword from exu may help.That will ignore all fireballs,So be well prepared for a 15-minute-clicking task.

**Comment by Prometheus0000** [comment]
It's not 'damage reduction', it's 'damage set to x max'.

**Comment by glowredman** [comment]
October last year I changed some aspects of the GS bosses because they were a joke. They were far to easy to beat, though with hindsight I didn't necessarily make it better. This is the current situation:

Blaze Boss:
- 300 base-HP
- is vulnerable to fireballs, otherwise takes base boss damage
- shoots small fireballs

Ghast Boss:
- 450 base-HP
- is vulnerable to fireballs, otherwise takes base boss damage
- shoots large fireballs

Crystal Boss:
- 650 base-HP
- is vulnerable to fireballs, otherwise takes base boss damage
- shoots large fireballs
- makes itself invisible for 60 ticks each 100 ticks with a probability of 50% (all three can be configured in GS core config, although I just noticed that two properties have the same name...)

Slime Boss:
- 900 base-HP
- jumps on the player and deals [slimeSize + 5] damage (smallest slime deals no damage, initial slime size is 8)
- on collision: can light the player on fire

Wolf Boss:
- 1200 HP
- deals 5 damage

The effective HP are calculated by multiplying the base-HP with the bossHealthModifier (default is 1, GTNH is 3; GC core config). The Wolf Boss has less effective HP than the Slime Boss because it doesn't factor in the bossHealthModifier (this is a mistake and not intended).
The base boss damage can be configured in the GS core config.

At the current sate the GC/GS bosses are neither challenging nor interresting, they are just boring and tedious. At the moment I don't have the time to do any major changes myself but I'd support any effort.

My thoughts on what could/should be done:
- The bosses and dungeons should not be removed.
- The fight should not take 5 seconds or so just with equipment which the player has at that point anyway.
- Finding and defeating the bosses should not be mandatory but visiting the planet(s?)/moon(s?) should still be required to unlock the next rocket. This could be done by combining items *only* found on the specific planet(s?) or moon(s?) to acquire the next schematic. It would be fitting to do this in some kind of research station but the only one I can curently think of is the TecTech Quantum Computer which is far to late.
- If some form of the above point is done, the loot found in the dungeons should be adjusted to reward players who decide against the "easy" route.
- The bosses should have different strenghts and weaknesses, for example only being vulnerable to one type. Example vulnerabilities explosions, projectiles, certain liquids, extreme damage through potions, certain tools, only electric tools, only non-electric tools, ... Example strenghts: piercing damage (in general / to electric armor / to non-electric armor), (partly) discharging of random/all electric items in the players inventory, throwing potions, summoning mobs, ...
- If the Botania license allows it, we could implement the Gaia as one boss.

**Comment by Prometheus0000** [comment]
The thing is you can't even reflect the fireballs back at them since they don't shoot at you. And for the ghast that did, it did only 6 damage. Why even bother? I'd just make some buckets of liquid death and put it in the ceiling and afk or something.

**Comment by Pxx500** [comment]
I've found that heavy bolts have very high armor penetration values and my full neutronium bolt does 150DMG (base damage is lower and its range is 10 blocks or less, but penetration increases overall damage on high armor targets).

I haven't tested any other bolts but I believe that there can be cheaper combinations that make bosses trivial. Last two or three bosses took me seconds to take down.

One big disadvantage it that if you shoot too fast the boss will deflect a bolt and since it penetrates nearly any armor even with quantum suit you will die immediately or barely survive (depending on your crossbow and bolt) although it never happened to me so I can't say for sure if that's the case.
