### ISSUE TITLE
Common metal saw blades do not show up in NEI when searched for (iron, bronze etc)

### ISSUE THREAD

**Issue by meetchal** [GTNewHorizons/GT-New-Horizons-Modpack#7840]
#### Which modpack version are you using? 2.1.0.6

#
#### If in multiplayer; On which server does this happen? Singleplayer

#
#### What did you try to do, and what did you expect to happen? Searched for Iron saw blade and those common metal blades.
#
#### What happened instead? (Attach screenshots if needed) Nothing showed up in NEI

#
#### What do you suggest instead/what changes do you propose? Make them show up in NEI

#
#### What is your GTNH Discord username? Mitch 0483

![Saw blade](https://user-images.githubusercontent.com/82561803/115638181-e1861680-a2df-11eb-98b8-b53e5e210591.png)

**Comment by Glease** [comment]
these are intentionally hidden to reduce clutter.

**Comment by meetchal** [comment]
> 
> 
> these are intentionally hidden to reduce clutter.

I struggled to find recipes as a new player.. that's unfortunate

**Comment by Glease** [comment]
Search the tool you want to build instead in that case. IIRC there is a quest mentioning this.

**Comment by meetchal** [comment]
> 
> 
> Search the tool you want to build instead in that case. IIRC there is a quest mentioning this.

Maybe a toggle for clutter feature would be good

**Comment by enki1337** [comment]
I'm going to +1 on this. The quest that I think you're referring to which mention this is "Important Tools". Here's the verbiage:

> You can use whatever materials you want. The gem version of saw is crafted differently to metal versions. Higher tier tools need steel or tungstensteel rods instead of sticks.

There's no mention of how to the recipe for metal blades is different, or how to find the different recipe. It's not particularly obvious or discoverable that the way to find the iron saw blade recipe is by searching for saw, and going through the recipes page by page.

Also, that you can't search for "Iron Saw Blade" directly causes a significant discrepancy in the process of making the screwdriver vs making the saw, since you can search for "Iron Rod" to build the screwdriver, but not the saw.

Since the directly preceding quest is Getting Iron, which is to amass 72 iron to build tools (presumably), I think at least the iron blade should be easily searchable. But if that's impossible/undesirable, what about just adding a bit of extra explanation to that quest's text? Maybe something along the lines that some recipes are hidden to reduce clutter, and recipes such as the Metal Saw Blades can only be found in the list of saws.
