### ISSUE TITLE
Fluix AE cable

### ISSUE THREAD

**Issue by Eason134HK** [GTNewHorizons/GT-New-Horizons-Modpack#7856]
#### Which modpack version are you using?
2.1.0.0
#
#### If in multiplayer; On which server does this happen? 
delta
#
#### What did you try to do, and what did you expect to happen?
i have some AE dyed AE cable i want to turn them back to fluix color 
#
#### What happened instead? (Attach screenshots if needed)
there is no fluix color recipes for AE cable 
#
#### What do you suggest instead/what changes do you propose?
add it 
#
#### What is your GTNH Discord username?
LoliNeko (Eason1134HK)

**Comment by repo-alt** [comment]
use snowball as a paint

**Comment by GTNH-Afx237v7** [comment]
Apparently in vanilla AE you can craft a dyed cable with a water bucket to get rid of the dye. Or with a color applicator and snowballs.

**Comment by GTNH-Afx237v7** [comment]
So just tested, it is possible to turn colored cables back into fluix cables using a color applicator.
Albeit this is somewhat of a PITA, as you need to put the applicator into an ME chest, set this chest to a high priority, then put snowballs into your AE system for the color applicator to be filled; then place the cables and click on them with the applicator and they are back to fluix. Indeed a crafting recipe would be nice, guess this is doable via MT script?
Would need a variable for the different metas of the colored cable so that any combination can be colored back to fluix.

**Comment by repo-alt** [comment]
To charge color applicator you don't need to connect to ME network, just attach power to the chest, put applicator inside and access it from the top grid

**Comment by GTNH-Afx237v7** [comment]
Shows how little I know about ME chests... ;) I looked at how recipes are defined inside AE2 code but I have too little knowledge to add such a recipe in there. What surprised me is that the colored variants are in the code, using oredicted dyes, however the brown smart cable had to be added via MT script?

**Comment by repo-alt** [comment]
iirc we don't use the recipes defined in AE code

**Comment by GTNH-Afx237v7** [comment]
done: https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/pull/7954
