### ISSUE TITLE
Add a new item to enderStorage to check the EnderStorage fluid in a GUI

### ISSUE THREAD

**Issue by DSLM** [GTNewHorizons/GT-New-Horizons-Modpack#7860]
#### Which modpack version are you using?
2.1.0.6
#
#### What do you suggest instead/what changes do you propose?
the pr: https://github.com/GTNewHorizons/EnderStorage/pull/4
There is how it looks like:
the right button choose the first color, and the left side show the 16*16 enderStorage tank with the first color (empty tank would not show);
![2021-04-25_02 19 37](https://user-images.githubusercontent.com/12635058/115983267-35a62a80-a56e-11eb-84ee-82837966d34e.png)
Sneak + right click the item will changed the mode between public to private.
(there is just a temporary texture)
![2021-04-25_02 19 50](https://user-images.githubusercontent.com/12635058/115983268-363ec100-a56e-11eb-991b-0f52950d8b56.png)

**Comment by Glease** [comment]
Would be a good feature overall, but the look still maybe needs a bit polishing. 

* Could you please change the color of the button's label to match its meaning? like "Red" will be rendered in red. 
* The font looks a bit too large.
* The textbox shown when you hover over a fluid looks a bit werid. A lazy way to do this would be copy over the GT's GT_Item_FluidDisplay and just render a slot with an item instead. Of course if you could come up with a better cleaner solution I'd be all for it, but this seems to be far easier to do.

**Comment by Prometheus0000** [comment]
- Why is this on a white background? To make it impossible to see white? Use a color not used by ES if possible.
 - The icon for the item looks bad. Is this what you mean by temporary?
 - It should list if it's in public or private mode (as well as what player) in the GUI. You can hand it to another player presumably, and see their stuff too, or does it switch automatically? In that case the name might not be needed.
 - I seriously doubt you can list all possible combinations like this, so a scrollbar and/or search function would be needed.
 - You should put some kind of border around the window to make it look nicer.
 - Consider listing the fluid in the GUI instead of only on hover. Or as an option. If you have to search through a large number of items, that would be better for searching for something. Or also add that to the previously mentioned search function.
 - It's unclear as to how you would use it.
 - If there was a way to list average I/O that would be useful.
 - Consider a block version, for OC compat (or however that would work).

**Comment by DSLM** [comment]
> * Why is this on a white background? To make it impossible to see white? Use a color not used by ES if possible.
> * The icon for the item looks bad. Is this what you mean by temporary?
> * It should list if it's in public or private mode (as well as what player) in the GUI. You can hand it to another player presumably, and see their stuff too, or does it switch automatically? In that case the name might not be needed.
> * I seriously doubt you can list all possible combinations like this, so a scrollbar and/or search function would be needed.
> * You should put some kind of border around the window to make it look nicer.
> * Consider listing the fluid in the GUI instead of only on hover. Or as an option. If you have to search through a large number of items, that would be better for searching for something. Or also add that to the previously mentioned search function.
> * It's unclear as to how you would use it.
> * If there was a way to list average I/O that would be useful.
> * Consider a block version, for OC compat (or however that would work).

1. I will add a better icon but it is lowest priority.
2. For now, it will not show others' storage, I don't know whether it is fine to show everyone's storage on the server.
3. it is able to show all 16*16*16 combinations but there will be not any space for show fluid info, so I plan add search function.
4. What's the "average I/O" you mean?

**Comment by Prometheus0000** [comment]
Average input/output, like on the enderIO capacitors.

**Comment by Dream-Master** [comment]
@DSLM are you still working on this ?

**Comment by DSLM** [comment]
> @DSLM are you still working on this ?

I'm working slowly.

**Comment by Dream-Master** [comment]
np

**Comment by Dream-Master** [comment]
@DSLM any update on this ?

**Comment by Dream-Master** [comment]
@Dev are you able to help on this PR ?

**Comment by D-Cysteine** [comment]
Hmm, I might be able to add some NEI diagrams for this. Honestly I don't feel like NEI diagrams would be the right place to show something like this, but this solution has the benefit of being minimal work (don't need to add an extra item or GUI), and we can always just delete the diagrams later if we ever get around to adding this properly.

**Comment by D-Cysteine** [comment]
The work on this is complete:
![EnderChest](https://user-images.githubusercontent.com/54219287/132808758-f93c157c-85c2-4c28-946d-5cf8c1182c11.png)
![EnderTank](https://user-images.githubusercontent.com/54219287/132808765-24e057e4-cbeb-4610-bc89-96d1bff9848f.png)

However, before we release this, we should warn players on servers that they need to lock down their ender storage. Otherwise, with this new feature, it becomes very easy to find global frequencies that are in-use and steal items / fluids.

Locking can be done with right-clicking (consumes!) a diamond onto the latch / dial for chests / tanks, respectively, and will change the frequency on that ender storage to player-personal frequencies.

**Comment by D-Cysteine** [comment]
DreamMaster helped me test this on dedicated servers, and turns out that the Ender Storage diagrams just don't really work on dedicated servers. So we probably don't need to worry about this being used to steal items or anything. Unfortunately, this does mean that the diagrams will only really be useful for finding misplaced or forgotten items / fluids in single-player, or for the host of the game, in LAN.

The detailed explanation is, currently, the Ender Storage API returns only incomplete information about the contents of ender storage items to clients. Clients will only receive information about the contents of an ender chest when the player opens that chest, and ender tank information is never sent at all. If you're curious, the code for this is here:
 * https://github.com/GTNewHorizons/EnderStorage/blob/master/src/codechicken/enderstorage/storage/EnderItemStoragePlugin.java#L37-L43
 * https://github.com/GTNewHorizons/EnderStorage/blob/master/src/codechicken/enderstorage/storage/EnderLiquidStoragePlugin.java#L27-L29

**Comment by Prometheus0000** [comment]
I assume fakeplayers can also check, or they wouldn't work with automation? Can a check be done to see if a channel is in use at least? And/or display used channels? Also, can the API be changed without messing up everyone's stuff?

**Comment by D-Cysteine** [comment]
I'm not sure how fake players work with the ender storage blocks. Maybe there is some special handling for them, or maybe they just work because the ender storage blocks do behave just like regular inventory blocks (as far as I can tell). The particular issue that we run into with this feature is that we're trying to check all channels, and don't have an actual ender storage block in-world that we can query the inventory of. So, as far as I know, we have to rely on Ender Storage's API, and it doesn't provide full data to clients (which honestly makes sense: I don't think the mod was designed with this particular usage in mind, and for what the mod itself needs, its API works fine).

I think to fix this, we'd need to add support for this to the Ender Storage API, by adding some way to request it to send complete data to the client. I haven't looked too closely, but I would guess that there really aren't any other ways to do this that don't require modifying the API, besides doing something hacky like temporarily placing an ender storage block so that we can check its inventory.

I think it should be fine to change the API in this way without worrying about breaking existing storage. All we need to do is just increase the amount of data the server sends to the client, which shouldn't affect existing storage data.
