### ISSUE TITLE
Disposable Crystalline Wand OP

### ISSUE THREAD

**Issue by Prometheus0000** [GTNewHorizons/GT-New-Horizons-Modpack#7929]
#### Which modpack version are you using?
2.1.0.6
#
1) 250 vis when crafted. Also 10% discount. You can't recharge it, but you just make another one instead.
2) Super easy to make, also only costs 35 vis before discounts.
![image](https://user-images.githubusercontent.com/8517039/118370091-177f8900-b574-11eb-8610-285c73d171d3.png)
![image](https://user-images.githubusercontent.com/8517039/118370096-1c443d00-b574-11eb-8022-18dc18a7a26b.png)
![image](https://user-images.githubusercontent.com/8517039/118370098-1f3f2d80-b574-11eb-8690-67e8fc924177.png)
Toss in the planar vortex to make into a usable one.
You do need to setup a planar vortex, but that isn't _that_ hard, and has no upkeep once done.
3) Allows you to skip crafting a whole bunch of wands, basically skipping right to the end.

My suggestion is to:
1) Reduce amount to 50-100.
2) Maybe make the discount higher to compensate.
3) Alternatively, make it cost more vis to craft, like 150-200. You would probably have wand auto-refilling stuff at this point though.

**Comment by Glease** [comment]
No. You are just saying "Let's remove this"

**Comment by Prometheus0000** [comment]
What do you suggest then?

**Comment by Glease** [comment]
It's fine where it was. I never found a reason it being too hard. 

If you think this huge vis cap is allowing tier skipping then please point out an instance. If you think this huge vis cap is making something unusually easy than please point out as well. 

IIRC vis recharging is never an issue. In low tier you have vishroom and also mob grinders. In high tier you recharge with energized nodes. Neither of which are inferior.

**Comment by Prometheus0000** [comment]
If you have a good wand
![image](https://user-images.githubusercontent.com/8517039/118372443-a04ff200-b57f-11eb-9b0c-85551220083a.png)
You can make this in HV, so you don't need to make any of the titanium or tungstensteel wands at all, and you can use it until you do the research for the ichor one (and can make ichorium) and just make it, skipping all the ones inbetween.

This goes against the tiering of the wands, or why did they require tiered metals in them? And TF drops.

One of the ways of gating TC stuff is by making it require a certain amount of vis, and this lets you skip past all that. I don't have any good examples for you though. It does look like most of the 100+ cost stuff is wands admittedly.

We should at least make it require TS screws, like the only other 250 vis one (warpwood), which is absurdly more difficult to get.

**Comment by Glease** [comment]
Then make the required infra blocks (forget the name sorry) to take 200 vis to craft. This is disposable wand and adding cost to it can impact its effectiveness a lot.

**Comment by Prometheus0000** [comment]
It's pretty much the same, but has TS screws and such.
![image](https://user-images.githubusercontent.com/8517039/118378033-e799ab00-b59e-11eb-8e9f-5d9f71d0ec43.png)
Just barely uncraftable with 
![image](https://user-images.githubusercontent.com/8517039/118378064-1152d200-b59f-11eb-98fc-e9ad22dc47fc.png)
Which is the best you can make before TS. Also, the best discount gear at the time. You can make it as soon as you get a TS wand though.

**Comment by Glease** [comment]
I'm still against adding TS into it. It will make it the same tier with warpwood, which is strictly superior to this disposable wand.

**Comment by Prometheus0000** [comment]
Almost all of them are TS
![image](https://user-images.githubusercontent.com/8517039/118378435-dbfbb380-b5a1-11eb-93f8-2c77bd71dfae.png)
You still need to make ~5 TS wands before you get to warpwood. Or at least, that's how many I need(ed).

BTW, I'm not sure the profane one can be dismantled and remade or not. Supposedly it can, but I never got it to do so.

**Comment by Glease** [comment]
Hmm somehow thought silverwood was titanium, my bad then. I'm somewhat ok with the recipe you gave above now.

**Comment by yukieiji** [comment]
A Planar Vortex is needed to activate the Crystalline Wand (change to Disposable Crystalline Wand).
I think you will most likely craft a Wand with close to 250 vis before building a Planar Vortex, but even if you don't, I don't see the benefit of continuing to craft this Wand that can't be filled when you have the infra to build a Planar Vortex.

**Comment by Alastors** [comment]
Look at all the stuff you have to make in order to be able to make the Crystalline wands, you have to make an entire huge infrastructure and build up and everything, the Disposable is fine where it is currently.

<img width="947" alt="Screen Shot 2021-05-15 at 9 19 35 PM" src="https://user-images.githubusercontent.com/78517796/118382422-407b3a80-b5c3-11eb-8604-195c95dbe456.png">
You have to make 12 of these. Sure they don't seem to bad to a later game player, but those 36 ender eye plates, 36 void metal plates and 12 primal charms really hurt a lot to the few players who already do this.

<img width="948" alt="Screen Shot 2021-05-15 at 9 49 19 PM" src="https://user-images.githubusercontent.com/78517796/118382850-67d40680-b5c7-11eb-9c99-eca86d1dcafc.png">

You need 6 of these, which you should note require "Advanced Node Stabilizers" now which aren't exactly duck soup to the average thaumaturge. 

<img width="965" alt="Screen Shot 2021-05-15 at 9 50 26 PM" src="https://user-images.githubusercontent.com/78517796/118382874-8fc36a00-b5c7-11eb-9bff-e6369872cfbd.png">

Furthermore you need 4 of these! They aren't exactly expensive per se. But they def take a hell of a long time to create.

And on top of that, you need the 2 machines to energize the node in the first place!

Sure you could argue that "Why don't you just make the 'Void Plant Seeds'? they'd cut into that a lot"

Tiers of warp
Mostly harmless (1 perm?)
Minor                   (2-3 perm?)
Moderate             (3-4perm?)
Dangerous           (4-5 perm?)
Taboo                    (6+ perm?)

These may not be right since I'm not entirely sure but still.

To which I'd tell you, look at the warp costs, a fair amount of y'all (Prometheus you in particular) don't support the use of warp tumors, so I'd ask you, "What better way do you have to reduce warp then?" I ask this because you are almost certainly guaranteed to rack up a hell of a lot of warp making these since they have so many directly required forbidden pre-reqs.         (2 mostly harmless (Void metal, Planar Theory), 3 Minors (Advanced Node Stabilizer, Transduction Amplifier, Vortex Attenuation), 2 Moderates (The Crimson Cult, New Horizons)) at the very least! And if you want things such as the Void plant seeds you have to go into Taboo research! And all of this is assuming you wasted tons of time to get warp with normal warp gaining methods instead of doing tons and tons of research, and just absolutely ignored pretty much every other research! 

My point here being, you don't just make the CDW just to be making the CDW you make it for other forbidden knowledge stuff so you are already going to have a hell of a lot of warp on top of the at least 14-19 perm warp you are going to be getting from these researches alone! So the warp costs here are high too!

I am one of the few people who have used the CDW myself and to tell you the truth, it really isn't as OP as you'd think.
Take for example the way you already craft it. When I was making the planar vortex, it took me a full two weeks of wasted time just to make it, and that was before the huge nerf we have now! And even if you do push the vis cost up to 200, some dumbass like me will come around and dick around until they can push the vis discount even further than the 50%, hell with tungstensteel capped at EV (accessible at hv right now but whatever) 

My point is, to nerf this into the ground as you propose. It would just become another "badly nerfed" thaumcraft multi like so many others are.

There is no reason to touch this, even if you are looking at "tier skipping wands" because this isn't broken as is, it takes wayyyyyyy too long to make for it to be worth it.

As of right now the Disposable Crystalline Wand is the solar panel equivalent of thaumcraft wands to tell you the truth, huge early investment for long term gains, and do we hear people saying that we should nerf solar panels out of existence? No, not people we listen to anyway!

My point is, with the way the research and crafting is now, you need a hell of a lot of stuff and warp just to do this by itself including the eldritch tab, so as is there isn't a reason to nerf the DCW as it isn't op, it just puts the vast majority of it's cost in the initial for a cheaper long term cost such as many machines do in the pack!

-Alastor

**Comment by Alastors** [comment]
To tell you the truth, even though I have the ability to make the CDW I barely use it even though I could, just because it is more annoying to use a wand that you can't ever charge to craft stuff than it is to use it for the very few big crafting things you might occasionally use it for, way more annoying than just energizing a node and charging a normal wand using that.

#notasusefulasyou'dthink

**Comment by greesyB** [comment]
A little more perspective from a player who did a lot of thaumcraft pre EV/IV, when I unlocked the research for CDW my only thought was "oh that's kinda neat, too bad it takes too much infrastructure to be worth making".

Most of thaumcraft is already hard to justify pursuing over just going pure tech progression. At the stage the CDW could be considered OP the time needed to research, create, and setup the infrastructure to make it could just be spent tier progressing to acquire a similar capacity real wand.

**Comment by Prometheus0000** [comment]
You say you need a ton of stuff, but it's not like it's harder than making 1 IV circuit? Getting the essentia for the infusion would take a while, but that's just time, not difficulty. It's also only 8 points of warp, half of which is probably sticky, and thus removable relatively easily. You need void, but if you're serious about TC, why wouldn't you have it? Or use this to get to the point where you can.

> Furthermore you need 4 of these! They aren't exactly expensive per se. But they def take a hell of a long time to create.

I have no idea why you think it takes a long time. The vis? Use shrooms+watering can.

> "What better way do you have to reduce warp then?"

Soap+suck it up. Or use impure tears if you can.

> Void plant seeds

I dunno why you'd need these? Just make void metal the normal way. You can also use the IC2 crop to get nuggets once you have a block if you want.

> And all of this is assuming you wasted tons of time to get warp with normal warp gaining methods instead of doing tons and tons of research, and just absolutely ignored pretty much every other research!

I dunno why you would assume people would _have_ to focus on warp research? It's the other way around, you avoid anything you don't _need_.

> it took me a full two weeks of wasted time just to make it

I dunno how long you play a day, so this is kind of a meaningless comparison. I would think it to be maybe a couple hours, maybe 1 day.

> do we hear people saying that we should nerf solar panels out of existence?

I've always hated solar panels. I think we should just chuck all the ones above HV. Especially the compressed ones.


BTW, I don't care about filling wands easily, just that it allows skipping wands. If possible, I'd rather it just fill a normal wand rather than creating a new one.

**Comment by Alastors** [comment]
> I have no idea why you think it takes a long time. The vis? Use shrooms+watering can.

I literally did, I had over 40 Primal Shrooms at this point, its just the fact you have to craft it so many times that makes it take forever. Plus shrooms and a watering can do _not_ grow as fast as you would initially think! Especially since they do not give all that many aspect orbs on breaking anyway. 

> 
> > "What better way do you have to reduce warp then?"
> 
> Soap+suck it up. Or use impure tears if you can.

^ This is just bad advice, the warp affects are the downfall to many in the pack, especially considering how there isn't a better way to deal with them besides the warp tumor until like what IV? 

> 
> > Void plant seeds
> 
> I dunno why you'd need these? Just make void metal the normal way. You can also use the IC2 crop to get nuggets once you have a block if you want.

You need 36 warp seeds, and exactly how many people do you think use both IC2 and thaumcraft? At that rate, you could just use bees or hell you could farm crimson cultists, but the base warp seed recipe is kind of a pain in the ass for repeated crafting without the void plant seeds.

<img width="476" alt="Screen Shot 2021-05-16 at 12 56 44 PM" src="https://user-images.githubusercontent.com/78517796/118405491-2c2c5180-b646-11eb-8db2-4b06ee4d4e18.png">

> 
> > And all of this is assuming you wasted tons of time to get warp with normal warp gaining methods instead of doing tons and tons of research, and just absolutely ignored pretty much every other research!
> 
> I dunno why you would assume people would _have_ to focus on warp research? It's the other way around, you avoid anything you don't _need_.

Why the hell would you waste time making a Planar vortex just to make a CDW? You only ever feel the desire to do so if you have a big project that requires a hell of a lot of warp, and the vast majority of those all fall under higher levels of warp researches.


> > it took me a full two weeks of wasted time just to make it
> 
> I dunno how long you play a day, so this is kind of a meaningless comparison. I would think it to be maybe a couple hours, maybe 1 day.

A _couple hours_? Really? That's just insulting. The crafting of the Planar vortex would take at _least_ 3 days if you focused specifically on that, had no life, and had a extremely large Primal Shroom farm. Theres no way in hell someone finishes that shit in just a couple hours at hv or mv. And by EV you can make much better wands
> 
> > do we hear people saying that we should nerf solar panels out of existence?
> 
> I've always hated solar panels. I think we should just chuck all the ones above HV. Especially the compressed ones.

Then like you said with my 2 week thing, this is just "meaningless comparison" they exist, why would you want to nuke them out of existence? That's just dumb since it restricts all the different things you can do in the pack.
> 
> BTW, I don't care about filling wands easily, just that it allows skipping wands. If possible, I'd rather it just fill a normal wand rather than creating a new one.

Yeah it allows a little wand skipping, but realistically y'all don't have wands spread out between enough materials, I mean you can note it yourself, over half of the wands use flippin _tungstensteel_. The issue lies here that wands are badly balanced as is, so instead of fixing the issues with wands, you want to nuke something that sort of solves the issue itself, albeit taking almost as much time to make just to use than it would just to craft the wands themselves.

Hell even with your gross underestimation of "A few hours" to craft the infrastructure, it would still be more time efficient just to craft the _tungstensteel screwed wands_ as it was since they don't take all that long to makes themselves compared to the time spent on infrastructure.


Overall my recommendation for you would be to try to play a little bit with crafting the planar vortex with what you would have available to you at hv or mv. Its a hell of a lot harder than you think it is.

**Comment by repo-alt** [comment]
Planar vortex is indeed quite a pain to make at low tiers, so if someone really wants to skip some wands, idk, maybe it's ok?

**Comment by Prometheus0000** [comment]
I guess if there's no support for it, I'll give up.

**Comment by Dream-Master** [comment]
The wand recipe isnt nerfed so maybe we do that first before we close the issue

**Comment by Dream-Master** [comment]
some mods i left to other like zoko who did much stuff but i guess he missed some part of the mod

**Comment by Alastors** [comment]
> The wand recipe isnt nerfed so maybe we do that first before we close the issue

Highkey though y'all already nerfed the infrastructure required to make the wand by tenfold, why would you go ahead and further nerf the wand though? The infrastructure is part of the wand crafting thing so by proxy the wand recipe has been nerfed.

**Comment by Alastors** [comment]
> The wand recipe isnt nerfed so maybe we do that first before we close the issue

As stated before, the infrastructure itself is already quite expensive so why kill the wand? if you nerf it, there would literally be no reason to craft it whatsoever, because if you make it on terms with wands of it's like, it won't have any chance to compete as it is literally _unfillable_ it's in the name Crystalline _Disposable_ Wand, it has no ability to be used after you drain it. and further there is no way to get anything back from it once it is gone, such as being able to macerate it to maybe get some salis mundus.

**Comment by maniifestantes** [comment]
how about increasing the vis needed on the wand crafting? for something like 100 or 125?

**Comment by Alastors** [comment]
> how about increasing the vis needed on the wand crafting? to something like 100 or 125?

bad idea, as said before, the infrastructure is already nerfed. why make a wand that has a max cap of 250 without being able to be charged require 100 or more vis to craft?

**Comment by repo-alt** [comment]
250 and 100 is still a big difference, and allows to skip quite a few wands. Not being chargeable is not a big deal if you use it to make a new wand/scepter. Yes, it will require titanium, but having 250 wand before titanium sounds a bit too early. I understand the argument about infrastructure, like, attempting this build at HV is a whole alternative development way, but it feels a bit OP there

**Comment by ScriptedPiky** [comment]
250 could allow the player to go and make a very powerful scepter, such as a Silverwood Thaumium capped scepter (or other considerably powerful caps), and allows you to skip a considerable amount of progression. Additionally, the cost of making a 250 disposable wand itself is considerably cheap. Maybe a form of balance could be requiring Titanium in prior infrastructure parts of some recipes to gate it? Sure it's still a pain in the ass to ultimately get, however, 250 vis capacity is an incredible amount for the tier you can get it in.

**Comment by yukieiji** [comment]
If that is the OP, then many people will actually be using it. However, as far as I can see, there is no one here who has assembled a Planar Vortex to make and use a Disposable Crystalline Wand(I'm not using it either).
It makes me wonder if anyone is really thinking of building a Planar Vortex early and using a Disposable Crystalline Wand....

**Comment by repo-alt** [comment]
Not many know about it. I built it on my second playthrough in EV and found it very useful.

**Comment by Dream-Master** [comment]
@repo-alt any recipe suggestions ?

**Comment by Alastors** [comment]
@Dream-Master as yukie noted, I am like literally the only person who really ever uses it, sure repo may have used it, but the recipe is fine. Why are you wanting to fix something that is not broken. Its not as useful as repo is making it out to be. Really, if it was OP why _wouldn't_ more people use it instead of how it is now where basically nobody does? Hell people don't even think CDW when they think planar vortex, they think of the planar gate!

**Comment by Alastors** [comment]
> Not many know about it. I built it on my second playthrough in EV and found it very useful.

I will note, when was your second playthrough? It's been nerfed since 2.1.0.0 or so, and it is deffff a lot harder to make now

**Comment by repo-alt** [comment]
Less than a year, so probably after 2.1. But at EV it is more manageable anyway.
