### ISSUE TITLE
Cant use Elevator with nano Boots of Traveller equipped

### ISSUE THREAD

**Issue by TrainerSnow** [GTNewHorizons/GT-New-Horizons-Modpack#7973]
#### Which modpack version are you using?
2.1.0.6b
#
#### If in multiplayer; On which server does this happen? 
Private Server
#
#### What did you try to do, and what did you expect to happen?
Tried to elevate up, using Openblocks Elevator blocks while wearing the Nano Boots of the Traveller (Electro-Magic Tools)
#
#### What happened instead? (Attach screenshots if needed)
I wasnt able to elevate up. Instead of teleporting me to the elevator directly over the elevator im standing on, i jumped upwards. When i take the NBotT off, without changing my position, the elevators work perfectly. If i make it so that my character doesnt have room to jump up, the elevator works aswell.
#
#### What do you suggest instead/what changes do you propose?
Fix the Elevator/Nano Boots of the Traveller
#
#### What is your GTNH Discord username?
TrainerSnow
#5086

**Comment by leagris** [comment]
The Nano Boots of Traveller are making player hover the ground to avoid slowness of SoulSand/Biomes-O'Plenty Mud and other block below interactions, unless player crouches.

The OpenBlocks elevator need player to be in direct contact with the block (inside the block's hit-box) to be able to interact and intercept the jump command to teleport player up to next elevator block.
It still can teleport player down because when player crouches, The Nano Boots of Travellers stops hovering the player, and the Crouch action can be captured by the Elevator Block to teleport player down.

Because of their Hovering effect, the Nano Boots of Traveller are unfortunately technically incompatible with how Minecraft deals with block interaction mechanic needed by the elevator block.

Cannot be fixed
