### ISSUE TITLE
Add Deep Mob Learning To The Pack. Requires Porting but it's MIT License. 

### ISSUE THREAD

**Issue by KaneHart** [GTNewHorizons/GT-New-Horizons-Modpack#7979]
The Mod Curse Page: https://www.curseforge.com/minecraft/mc-mods/deep-mob-learning
Github Page check Forks also: https://github.com/xt9/DeepMobLearning 

Reason: Reduce TPS
Usages: Everything From Vanilla Material Grinding, To Blood Magic Blood Farming, To HighTech Grind you name it. If I run a Vanilla Server or the most advance modpack in Minecraft, people will always make mob farms no matter what.

I'm not saying this will be the cure or even should be the cure for example the grind / need for BM Blood. But it's another Option and even outside of the Magic world I think it be a very valuable mod period. 

Weather or not it's worth porting or is stable enough is another question.

I decided to make this it's own post rather then tie it into Blood Magic, is because I like to see it no matter what we decide in the future of BM Blood Farming. Like I said no matter what people will always make big laggy farms for one reason or another. So let's give them an option to not destroy the performance.

**Comment by ALongStringOfNumbers** [comment]
To add a bit more to the discussion of Deep Mob Learning, there is a Fork/Rewrite located here, [Curseforge](https://www.curseforge.com/minecraft/mc-mods/dml-relearned), [GitHub](https://github.com/mustapelto/DML-Relearned) that is in progress, but rewrites Deep Mob Learning to be more extensible.

I am putting this forward as another mod to gather ideas from, because it most likely will not fit the current design choices completely, and could have some of the parts from Deep Mob Learning that are not desired to be in the pack.

**Comment by Ethryan** [comment]
This is a mod for 1.12.2, it makes me doubt it can be added to this pack.

**Comment by shawnbyday** [comment]
Not that this is an opinion piece but I love Deep Mob Learning and would love to see it ported and added. :D

**Comment by johnch18** [comment]
It's a poor mod in OmniFactory and it's a poor mod here. I definitely understand why mob grinding is obnoxious but DML is just a terrible solution.
