### ISSUE TITLE
Steves Carts 2 

### ISSUE THREAD

**Issue by lobiita24** [GTNewHorizons/GT-New-Horizons-Modpack#7991]
#### Which modpack version are you using?
2.1.0.p
#
#### If in multiplayer; On which server does this happen? 
Yes
#
#### What did you try to do, and what did you expect to happen?
My cars the steves cars 2 despawning
#
#### What happened instead? (Attach screenshots if needed)

#
#### What do you suggest instead/what changes do you propose?
Fix this bug the mod
#
#### What is your GTNH Discord username?
SakkuraWolf

**Comment by Prometheus0000** [comment]
Vanilla bug, also probably duplicate.

**Comment by Prometheus0000** [comment]
Read the QB about covering up carts and duping/despawning.

**Comment by boubou19** [comment]
already reported in #3825, this bug can also dupe the cart (#3258). If anyone is interested, a lead to fix this has been proposed in #5406. This bug happens when the cart crosses chunk borders while the chunks are unloaded. An easy work around is to avoid the cart crossing chunks by making a farm in one chunk.

**Comment by lobiita24** [comment]
Yes but in 1 chunk is very small for 2 advanced coke oven

**Comment by lobiita24** [comment]
Steves carts no have open code?

**Comment by KamenriderZO** [comment]
you can make a cart line with an anchor cart to keep chunk loaded(Railcraft train)

**Comment by lobiita24** [comment]
Tell me id
