### ISSUE TITLE
Mega DT outputs fluids to hatches locked to other fluids

### ISSUE THREAD

**Issue by sintken** [GTNewHorizons/GT-New-Horizons-Modpack#8007]
#### Which modpack version are you using?
2.0.9.0
#
#### If in multiplayer; On which server does this happen? 
Prospercraft
#
#### What did you try to do, and what did you expect to happen?
Ran Hot Ruthenium Tetroxide Solution -> Ruthenium Tetroxide recipe in mega DT (hot RT solution in, water out in first output layer and RT out in second output layer); had one output hatch in 2nd output layer and two output hatches in 1st output layer, with one locked to water and one locked to osmium solution. Expected water to be output only in the water-locked hatch, not in the hatch locked to osmium solution.
#
#### What happened instead? (Attach screenshots if needed)
Water was output evenly in both 1st layer hatches (both the one locked to water and the one locked to osmium solution). Second output layer worked fine with the ruthenium tetroxide.
#
#### What do you suggest instead/what changes do you propose?
Make locking hatches work properly with mega DT
#
#### What is your GTNH Discord username?
sintken (taintstainer) #1312

**Comment by GTNH-Afx237v7** [comment]
The Bartworks mega Distillation tower? Isn’t that still in a WIP phase?

**Comment by ScriptedPiky** [comment]
Bartworks fluids have a rather obscure bug that causes them to not properly accept 'locked fluid' selection and will otherwise completely ignore locked hatches and go for "Hatch 1" or the "first possible" hatch that is empty. Say that you have Hydrogen on Hatch 1 and then Ruthenium Tetroxide on Hatch 2. Obviously, Hatch 1 has Hydrogen in it and cannot be inserted, so Hatch 2 is preferred and you decide to lock both fluids; all is good. That is until the Hydrogen is automatically pumped out and then Ruthenium Tetroxide decides to ignore said locked hatch and goes for Hatch 1 the moment you run the required recipe.

**Comment by Pxx500** [comment]
Why did you have 2 hatches on one layer? Distillation tower is supposed to output fluids at certain layers and even if it puts bad fluid to a locked hatch it shouldn't even matter. Change your setup. @Prometheus0000 can decide whether this issue is worth fixing since it doesn't impact gameplay when used properly.

**Comment by Prometheus0000** [comment]
What? Why me?

**Comment by Pxx500** [comment]
I see you everywhere so I just thought you might do it lol

**Comment by Glease** [comment]
Multis with special output rules (e.g. DT, EBF) won't respect hatch locking or restrictive setting, because the locking are invented after those multis exist. They simply have no knowledge of these settings. They will be fixed as I push forward the structurelib integration. I won't object anyone to go fix it before the structurelib integration lands though.

**Comment by Glease** [comment]
Should have been fixed by now.
