### ISSUE TITLE
Quest:Cough Cough - Something needs to Be Done About the Smell is missing

### ISSUE THREAD

**Issue by yukieiji** [GTNewHorizons/GT-New-Horizons-Modpack#8064]
#### Which modpack version are you using?
2.1.1.0Pre2
#
#### If in multiplayer; On which server does this happen? 
Single
#
#### What did you try to do, and what did you expect to happen?
I opened the GT++ tab Cough Cough - Something needs to Be Done About the Smell
#
#### What happened instead? (Attach screenshots if needed)
The quest icon and some items were unspecified.
![2021-06-16_20 57 13](https://user-images.githubusercontent.com/40425798/122215111-d4536580-cee5-11eb-90dc-0d36fead45f5.png)
![2021-06-16_21 00 14](https://user-images.githubusercontent.com/40425798/122215174-e0d7be00-cee5-11eb-8420-e2b695f0d044.png)
#
#### What do you suggest instead/what changes do you propose?
Fix it.
#
#### What is your GTNH Discord username?
yukieiji

**Comment by querns** [comment]
This happens when pollution is disabled. The `.name` items are blocks that don't get registered when pollution is disabled in the config.

**Comment by Prometheus0000** [comment]
There's nothing I can do here without messing with the GT/GT++ internals around pollution. If you can convince someone to mess with the code to let pollution dissipate with pollution disabled, get them to fix this at the same time.

**Comment by KaneHart** [comment]
This is an older quest and sounds like it is meant to be replaced. From my understanding it's also GT++.

Since turning Pollution on server side does not sync those meta blocks/items to the Client side and make this work, I think it's best to just hide/disable this quest till the pollution work is redone or just forgotten. 

Right now it would serve no purpose besides confuse some players and or maybe it look like a bug that will end up with more reports anyways.

My personal thought on it.
