### ISSUE TITLE
Is Dreams a Cat Person? - Missing Kill Quest!

### ISSUE THREAD

**Issue by KaneHart** [GTNewHorizons/GT-New-Horizons-Modpack#8079]
This cat says he has no value and not worth any coins. I wonder if we can change that. 

![image](https://user-images.githubusercontent.com/425853/122558445-170f5d80-d00c-11eb-95e0-a9303899d199.png)

**Comment by Dream-Master** [comment]
ok I'll kill the cat 😎

**Comment by Glease** [comment]
No, don't.

**Comment by GTNH-Afx237v7** [comment]
How about this: Use end-game blocks in the shape of an iron golem to spawn the DreamMasterXXL end-boss ? Details tbd...

**Comment by Prometheus0000** [comment]
To be honest, all the kill critter quests are a little pointless. We could've just had one explanatory quest that said that we added stuff like venison to the TF deer instead of requiring you to kill a hundred or w/e of them. You should be able to get the items the normal way still, so it's not like you need to kill them for anything other than the quest.

Also, I don't think the ocelots have anything added to their drop table, but I could be wrong. Lastly, ocelots are rare, and hard to find.

**Comment by Dream-Master** [comment]
we can add stuff ocelots should drop 😎😎

**Comment by KaneHart** [comment]
You kill them for coins. They are fun repeatable RPG like Coins. They don't serve a purpose more than just another thing to kill. At this time they do drop some sort of GT++ Meat lol.

**Comment by tommy307507** [comment]
Can't waut to have my cat-human soup this evening
