### ISSUE TITLE
Safe mode for the machine controller cover doesn't work

### ISSUE THREAD

**Issue by Prometheus0000** [GTNewHorizons/GT-New-Horizons-Modpack#8104]
#### Which modpack version are you using?
2.1.1.0
#
The setting is completely ignored, or I'm using it wrong. @johnch18
![image](https://user-images.githubusercontent.com/8517039/123174164-b342c580-d44d-11eb-9809-6b11da30251b.png)
![image](https://user-images.githubusercontent.com/8517039/123174177-b8a01000-d44d-11eb-821f-a477b7541a19.png)
It just keeps going on and off voiding everything, as you'd expect without the setting.

https://github.com/GTNewHorizons/GT5-Unofficial/pull/486
https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/7811

**Comment by Glease** [comment]
I just did a test (20 seconds ago), and it is working just fine. Could you please describe the way you used it in greater detail?

**Comment by Prometheus0000** [comment]
I put in some titanium dust with a 1 circuit, and set the machine controller as shown in the image. I have a IV energy hatch and an EV output from the creative source (or something like that, purposely not enough). After placing a heat-proof block in the missing spot, the machine rapidly flipped between on and off, voiding everything.

My understanding is that it should change the setting to disable machine after the first time this happens?

**Comment by Glease** [comment]
How exactly did you configure the controller cover though?

**Comment by Prometheus0000** [comment]
Like shown in the image? I opened the GUI and set it to disable with redstone, and turned safe mode on.

**Comment by sxtyzhangzk** [comment]
I have the same issue with EBFs and Vaccum Freezers, while the same setups on LCRs work correctly. Since both EBF and Vaccum Freezer are modified by TecTech (they have TecTech GUI), I suspect this issue is probably related to TecTech, which does not update the `mWasShutdown` flag (by calling `criticalStopMachine` instead of the normal `stopMachine` if my understanding is correct) when there is not enough energy.
