### ISSUE TITLE
[Suggestion] Move AE2 Later or move LP to late MV/early HV

### ISSUE THREAD

**Issue by Irgendwer01** [GTNewHorizons/GT-New-Horizons-Modpack#8122]
#### Which modpack version are you using?
2.1.1.0
#
#### What is your GTNH Discord username?
Irgendwer#5308
#
#### Which Changes do you suggest?
At the point where you have access to LP, you only need to wait a bit till you get access to AE2 which makes LP basically useless, that's why I suggest moving AE2 later or LP to late MV/early HV.

**Comment by Glease** [comment]
Much of LP is unlocked at LV. Not sure what are you talking about. See #7005 for discussions on how it was gated.

**Comment by Prometheus0000** [comment]
I vote to remove LP then.

**Comment by Dream-Master** [comment]
we can move lp to mv/hv sure. If no one use it or it not fit into the pack we can remove it idk

**Comment by Irgendwer01** [comment]
Also tbh I don't think the author really knows about LP, for whatever reason he moved the Requesting table to HV which is needed to even requests items out of the System lol.

**Comment by Irgendwer01** [comment]
> I vote to remove LP then.

@Prometheus0000 We don't need to remove LP because of recipe issues, but the Recipes should definetly be modified since when it's gonna be like this definelty none will use it.

**Comment by Ydrec** [comment]
I think issue author doesn't understand purpose of LP, rhey are not meant to replace AE2, there is also project red system for early inventory managments.
LPs are means of automation, they allow some high level logistics which no other mod in pack can currently, at best robots from OC. 
There is no reason to ever balance them based on ae2

**Comment by Prometheus0000** [comment]
It was a joke.

**Comment by querns** [comment]
Regarding logistics pipes: I'd suggest a slight change to the Request Logistics Pipe. This is the current recipe:

![javaw_sftwPn20VZ](https://user-images.githubusercontent.com/33518699/123528684-05365600-d6af-11eb-92a7-885b3b8cc007.png)

The item circuit in this recipe is an HV recipe, while the rest of the components are MV:

![javaw_NlYyVhMCbl](https://user-images.githubusercontent.com/33518699/123528694-10898180-d6af-11eb-9a88-ad29e6708c58.png)

Changing the Item Circuit Tier I to just a Golden Chipset, an MV forming press recipe, would lower the request logistics pipe's tier to MV, allowing users to pull items from their LP network.

The logistics request table has a similar malady -- its quicksort module ingredient is HV gated, but it uses an MV hull. I'd actually suggest making it use an HV hull instead -- it's a logical upgrade from the request logistics pipe, because it has integrated crafting using network items, as well as an integrated QuickSort module in the GUI. Since one of its components requires multiple HV items anyways, making the hull itself HV provides a much clearer signal to the user that it's an HV item.

**Comment by Dream-Master** [comment]
LP need a rework and maybe some parts from ae2 as well
