### ISSUE TITLE
quests that are still wrong after the update

### ISSUE THREAD

**Issue by Eason134HK** [GTNewHorizons/GT-New-Horizons-Modpack#8133]
#### Which modpack version are you using?
2.1.0.0
#
#### If in multiplayer; On which server does this happen? 
delta
#
#### What did you try to do, and what did you expect to happen?

#
#### What happened instead? (Attach screenshots if needed)
![image](https://user-images.githubusercontent.com/59776356/123542684-8fe58680-d77d-11eb-9c37-4389dc257973.png)
Crop-Matron work in 11*11*3 not 9*9*3 
![image](https://user-images.githubusercontent.com/59776356/123542703-adb2eb80-d77d-11eb-8556-5da55b3a2238.png)
Radioisotope Thermoelectric Generator give only 16eu/t
#
#### What do you suggest instead/what changes do you propose?

#
#### What is your GTNH Discord username?
Eason1134HK#5098

**Comment by Prometheus0000** [comment]
I tested it _again_, and it's 5 out, so 11.

Can you prove it's 16, other than the tooltip? Also, if it was 16 out, but generating 32, it would back up.
![image](https://user-images.githubusercontent.com/8517039/123556882-b2ff3e80-d75b-11eb-927b-5641ea22bd89.png)
![image](https://user-images.githubusercontent.com/8517039/123556893-bd213d00-d75b-11eb-87f8-1561d8addf1d.png)

In the future, please test things yourself instead of trusting a wiki or whatnot.

**Comment by Prometheus0000** [comment]
Actually the quest says 9, I thought it was the other way around, sorry.
