### ISSUE TITLE
make tantalum a ebf recipe

### ISSUE THREAD

**Issue by botn365** [GTNewHorizons/GT-New-Horizons-Modpack#8145]
tantalum has a melting point realy close to that of tungsten so it makes no sense that tungsten needs a ebf but tantalum is a furnace recipe

so tantalum should get a 500 second ebf recipe to be more the same as tungsten

**Comment by Prometheus0000** [comment]
That would really screw over EIO wouldn't it? Since all the capacitors use it. Also, one of the SMDs.

**Comment by ScriptedPiky** [comment]
Would also make the creation of SMDs extremely painful. Granted it could be a 120-volt/EU/t recipe & require CuNi coils, that'd still be a very heavy time sink for early game shenanigans. Though I can definitely see the implication of it & its relation to extremely high temperatures.

**Comment by iouter** [comment]
gtnh is not realistic, for example, the aqua regia in gtnh is a 1:1 mixture of nitric acid and dilute sulfuric acid. maybe you can go to make gt6nh.

**Comment by Dream-Master** [comment]
Make it a ebf is a good idea but maybe with a smaller ebf time as you mentioned @botn365

**Comment by Alastors** [comment]
> tantalum has a melting point realy close to that of tungsten so it makes no sense that tungsten needs a ebf but tantalum is a furnace recipe
> 
> so tantalum should get a 500 second ebf recipe to be more the same as tungsten

pls no <3

Though on the other hand... that would bolster TC (witching gadgets in particular) since it has a duplication recipe (that does cost that one extremely hard to get yellow aspect (nebrisium was it's name I think?) but thats not the *hardest* bit to get around if you don't care about nickel/ find a good node/create a node with.) So actually maybe since I'm always down for TC boosting and/or redirection of certain aspects to it.

**Comment by Alastors** [comment]
I mean technically the metal duplication of it is thaumic transmutation alchemy of molecular assembly, perhaps even akin to real world nuclear transmutation, but instead being understood under the lens of magic instead of science in a way that could have mirrored our real world in some other timeline or another where magnetism and other forces being described as magic with scientists being mages/thaumaturgists/whathaveyou. That would at least explain the use of goggles to see nodes, and perhaps would explain nodes as a force akin to nuclear radiation or something of the like as some will note. The thaumic alchemy being more like a primal form of chemistry (alchemy, for lack of a better word I suppose although it doesn't quite capture the thought perfectly) to get kind of off topic but still relate to the idea.

**Comment by Dream-Master** [comment]
will Change this
