### ISSUE TITLE
Moon lander didn't spawn until relogging then blew me up.

### ISSUE THREAD

**Issue by Nrin123** [GTNewHorizons/GT-New-Horizons-Modpack#8170]
#### Which modpack version are you using?
2.1.1.0
#
#### If in multiplayer; On which server does this happen? 
mc.stonelegion.com
#
#### What did you try to do, and what did you expect to happen?
Tried going to the moon and expected it to work.
#
#### What happened instead? (Attach screenshots if needed)
Spawned in the moon dimension at height ~800 without a lander and landed on the ground with my thaumostatic harness. I logged out and back in and a few moments later my lander landed on my head and blew up, instantly killing me.
#
#### What do you suggest instead/what changes do you propose?
Fix it because this feels awful.
#
#### What is your GTNH Discord username?
Nrin#7237

**Comment by KaneHart** [comment]
Thanks Nrin for reporting this.

So we have too many bloody theories on this issue.

1: The world needs to be loaded once and not pregened to prevent this. Not sure if I believe this one...
2: The World needs to be pregenerated... This is too costly and taxing... As a Server Admin this is not fair or fun to have to do this especially since you are sent via relative coordinates right? Meaning if he takes of at 8k out on the OW it's 8K on the Moon?
3: The last one someone said was the world needed to be loaded all the time. Just the spawn? 


My suggestion is the following:
1) Allow a Server Option to remove the relative coordinates when using rockets from any location besides back to the OW... (To prevent spawn from getting hit hard haha.... Maybe a system where they get placed maybe via a config random 500 x 500 area of the Moon Spawn,... I be happy to pregen that for each world...

2) Fix the issue.... Yeah not going to happen. You guys claimed this was fixed with your newest server a couple years ago and then you added SG's back so I assume it actually was not fixed?

3) Remove the mod :) I mean honestly I bitched about GC so often and I'm a jerk / sarcastic about Magic Mods. But why the hell is the biggest climax of the gameplay sending a shitty Fisher Price Rocket into Space one the most broken issues I have heard about?  No offense the Rocket itself never fit well just because it's like a Fisher Price Toy Model in a Complex GT Universe haha. PS yes I know were not getting AR  and not saying we are... But maybe we can do something both for SP / MP that is something other then adding bunkers.


For our server to attempt to resolve the issue will be adding 4 bunkers in the Overworld and letting players teleport using the Rocket as a Key... Not sure if there is a way to add fuel to it to make it more fun / legit... Sadly this is even more anti climatic... Rather just have a damn portal key you take and remove the ideas of rockets haha. 


Nrin, I'm sorry you experience this. You will not be the first no last that suffers this. Best we can do is attempt to fight for attention on the issue.
