### ISSUE TITLE
Muffler upgrades don't work on (certain) multiblocks

### ISSUE THREAD

**Issue by Sovereignty89** [GTNewHorizons/GT-New-Horizons-Modpack#8180]
#### Which modpack version are you using?

# 2.1.1.0
#### If in multiplayer; On which server does this happen? 

# N/A
#### What did you try to do, and what did you expect to happen?
I noticed that my EBF, Multi-Smelter and Vacuum Freezer all make a distinct hum and pulse sound when processing an item. I tried turning this off by applying a muffler upgrade but they don't seem to work on the 3 multi-blocks I tried it on.

#### What happened instead? (Attach screenshots if needed)

Muffler upgrade doesn't work on (certain) multiblocks

#### What do you suggest instead/what changes do you propose?
Could this functionality be added? I added the '(certain)' because I don't have a lot of multiblocks yet but it's possible it doesn't work on others not mentioned here either.

#### What is your GTNH Discord username?
`Spotless_Mind#0001`

**Comment by leagris** [comment]
In current version of GTNH, some Gregtech machines are overwritten by Bartworks and TecTech to support arbitrary rotation. The implementation is not the same as with base Gregtech.

@Glease is working on returning these machine under full Gregtech control \(See: https://github.com/GTNewHorizons/GT5-Unofficial/pull/551\) with the help of a new dedicated library he wrote, to have Gregtech natively support arbitrary rotation of multi-blocks structures.

It will likely be released with next version and muffling sounds should work again with those multi-blocks returned to total Gregtech control.
--
_P.S.: @Sovereignty89 I had to edit your issue because it was all wrongly formatted in Title1 which is the biggest, bold and inappropriate. Please, don't forget to click on the Preview tab before submitting an issue next time._

**Comment by Sovereignty89** [comment]
When you create a new issue it has these separate hash symbols and I thought that's the line you used to write your own words. But apparently it makes everything big. Sorry about that.

**Comment by Prometheus0000** [comment]
Shouldn't this be fixed/closed now with the dev versions like 2.1.1.2 out? Could someone check?

**Comment by Sovereignty89** [comment]
Tested it on 2.1.1.3 dev version. Whether a multiblock has a muffler upgrade or not, they have stopped making sounds. I've tested the three I mentioned in my original post and they are all quiet.
