### ISSUE TITLE
Idiots text makes me feel worthless and want to stop playing

### ISSUE THREAD

**Issue by Ambaire** [GTNewHorizons/GT-New-Horizons-Modpack#8189]
#### Which modpack version are you using?
2.1.1.0
#
#### What did you try to do, and what did you expect to happen?
I looked at the backpack and expected to see a helpful tooltip for it.
#
#### What happened instead? (Attach screenshots if needed)
I felt like I was being called an idiot and got depressed.
#
#### What do you suggest instead/what changes do you propose?
Remove the 'Idiots' part.
#

**Comment by Skiftcha** [comment]
cant we just move backpack contents to new crafted backpack and remove tooltip?

**Comment by Dream-Master** [comment]
@Skiftcha it was a meme

**Comment by Prometheus0000** [comment]
It was also referring to people who _did_ void everything in their backpacks.

**Comment by Dream-Master** [comment]
Lea mean it wasnt fixed with the script so the info make sense

**Comment by leagris** [comment]
Please do not remove the tooltip until the crafting recipe is fixed to preserve the backpack content (can be done with MineTweaker function recipe or in code with a crafting handler but I did not do this. I know there a developers who know this and can fix.

Remember this alienating meme tooltip saved server admins to deal with angry players loosing their backpack. It was added because it happened enough time. Since then, admins were able to point the writing on the wall.

Now since the recipe can be fixed, please fix the recipe. And only then, remove the tooltip when it is no longer needed.

**Comment by Prometheus0000** [comment]
https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/pull/7137#issuecomment-748650494 Says it's already done though? Is it not?

**Comment by Dream-Master** [comment]
@Prometheus0000 is this tested ?

**Comment by Prometheus0000** [comment]
They literally said they tested it? If you don't believe them, why did you merge the PR?

**Comment by Dream-Master** [comment]
@Prometheus0000 i did not have the time tested all prs sorry.

**Comment by Glease** [comment]
Dream has decided to close all FixedInDevs immediately after it's fixed instead of until a release is made.
