### ISSUE TITLE
The primordial armor is too strong for its tier

### ISSUE THREAD

**Issue by maniifestantes** [GTNewHorizons/GT-New-Horizons-Modpack#8202]
#### Which modpack version are you using?
2.1.1.0
#
#### If in multiplayer; On which server does this happen? 
zeta
#
#### What did you try to do, and what did you expect to happen?
The primordial armor gives you near immortality, the only things that can kill you is getting damaged by the lack of LP from blood magic, since that doesn't trigger the healing effect, getting hit by an weapon that deals millions of dmg, the avaritia sword or the /kill command. it protects you against void damage, so you can just tank the chaos dragon with it. Also, if you get hit you'll instantly get your health back to full in  an instant. The only drawbacks is that you don't get to fly or have move speed bonus. You still get the jump assist though.
I should note that this armor has 6 effects depending on the affinity (you can change it anytime), but the void resistance and instant heal are the effect of the same affinity, Terra. 
All that at iv, after you get some PBI. I'd say this should be tiered higher, or maybe nerf its effect somewhat.

**Comment by Alastors** [comment]
bro its not, do you realize how many bits you have to jump through just to make it? The Primordial amor isn't op on the sheer basis that it is an actual nightmare to craft, and then, even then, if you want to use it, you have to take ordo to consistently use it and shift as needed since ordo alone give 20 temp warp while wearing, no thank you, do not tier this higher or nerf it.

**Comment by Alastors** [comment]
<img width="1169" alt="Screen Shot 2021-07-07 at 7 54 49 PM" src="https://user-images.githubusercontent.com/78517796/124842275-30e1f780-df5d-11eb-9d9e-76d5d9b469c0.png">
<img width="1198" alt="Screen Shot 2021-07-07 at 7 54 57 PM" src="https://user-images.githubusercontent.com/78517796/124842284-35a6ab80-df5d-11eb-8e99-cc93665b7529.png">
In what world, with a crafting recipe like this, is this dip OP?

**Comment by Prometheus0000** [comment]
Tier != difficulty. Also, it doesn't really look that hard if you already have the shadow gear and do crops.

**Comment by Alastors** [comment]
The Armor is meant to take on the Eldritch gods, the crap is going to be good, this is full endgame TC crap.

 "Also, if you get hit you'll instantly get your health back to full in an instant. The only drawbacks is that you don't get to fly or have move speed bonus. You still get the jump assist though.
I should note that this armor has 6 effects depending on the affinity (you can change it anytime), but the void resistance and instant heal are the effect of the same affinity, Terra." 

This is assuming that you can shift from the one affect active at a time (which it is only a single effect active at a time) at the speed of the first three digits of Bill Gate's bank account ticking up. 

<img width="466" alt="Screen Shot 2021-07-07 at 7 58 48 PM" src="https://user-images.githubusercontent.com/78517796/124842532-bf567900-df5d-11eb-9ee0-bc744bb52df5.png">

Ordo itself only reduces the innate warp added by half.

and if you don't have ordo on constantly you have to deal with that constant 40 warp from the armor itself.

Aqua is just a worse form of the Silverwood heart from thaumic horzions

Ignis is just potion effects and blast resistance.

Perditio, is that really all that OP when you are going to be fighting mobs, almost certainly with a crossbow considering how OP the crossbow itself is as many will note.

And Aer isn't even useful if you aren't dealing with PVP, by the point you can make this armor, you can tank almost any projectile without armor tbh, leaving only terra and ordo useful.

My point is, the armor isn't OP for what it is, honestly tanking the kill command and sword probably relates to how it deals with damage and not it's resistance itself.

If someone could check me on this I would appreciate it, but tanking a lot of damage doesn't mean much if it A. works like how sturdy from Pokemon works or B. changes incoming damage into a max cap damage based off how many hearts you have or C. changes damage into a relative percentile instead of dealing the damage itself.

**Comment by Alastors** [comment]
I am sorry for the mess that all is, it is probably incoherent and ranty but whatever, other things can do everything this armor can do is my point, hell even look at the poppets from witchery with their near death save shit

**Comment by Glease** [comment]
The stupid thing with this armor is, it applies Heal potion effect instead of Regeneration WHILE it applies it as a non-instant potion effect. It thus makes you regen health several hundred times faster than a Regeneration II can do. Primordial armor can regen 4/8/16/32 health point every single tick, depending on how many terra attuned armor you have, while Regen II can only heal 1 healt point per 25 ticks.

**Comment by KiloJoel** [comment]
I don't think it should be gated later than it is (PBI). Ichorium gear has creative flight and fast boots and all that. All primordial armour does is be armour. The boots don't even give extra jump height or speed like piston/traveller boots do.

**Comment by Ydrec** [comment]
1. Barely anybody does thaum
2. Even less craft this armor
3. You get ways of creative flight much earlier both in nano jetpack and harness
4. You can become invincible at mv by enchanting armor with last stand

So just needs fix to apply regen instead of heal and no recipe changes?

**Comment by ScriptedPiky** [comment]
I believe I found the specific culprit of the line that gives the player healing?
https://github.com/GTNewHorizons/WitchingGadgets/blob/dac3f276e58b2927d13f012e92bbd4ad858fcde3/src/main/java/witchinggadgets/common/items/armor/ItemPrimordialArmor.java#L566
