### ISSUE TITLE
Kick from bibliocraft Atlas

### ISSUE THREAD

**Issue by wildejackson** [GTNewHorizons/GT-New-Horizons-Modpack#8251]
#### Which modpack version are you using?
2.1.1.0 Stable

#### If in multiplayer; On which server does this happen? 
Prospercraft or Singleplayer

#### What did you try to do, and what did you expect to happen?
After using the Atlas, (and placing my clipboards with all my stuff in there!) I switched to "map view" by clicking the little map icon in the bottom right. Upon clicking back to "inventory mode" I was kicked from the game back to the main menu. It says different things depending on if Im in singleplayer or multiplayer, but the kick occurs at the exact same time.

Inventory view (totally normal):
![image](https://user-images.githubusercontent.com/16457653/125889774-b24985b7-9c5d-4244-8c83-aa6b07a43c3d.png)

Map view (kick occours when you click this button):
![image](https://user-images.githubusercontent.com/16457653/125889939-628e4d29-fdd6-408a-8c23-70a19ace2407.png)

#### What happened instead? (Attach screenshots if needed)
Singleplayer:
![image](https://user-images.githubusercontent.com/16457653/125889229-f83f7b91-8822-4cec-acf6-e41ee192861d.png)
Multiplayer:
![image](https://user-images.githubusercontent.com/16457653/125889365-fe9b7367-f1ad-4410-98eb-9a9509fe7ff6.png)

#### What do you suggest instead/what changes do you propose?
I cant be sure if this is bibliocraft's fault or GTNH but the kick seems to be some explicit exception in an attempt to prevent an exploit of some kind.  No idea what can be done to fix this without knowing whats going on behind the scenes.

#### What is your GTNH Discord username?
The Wilde Jackson

**Comment by boubou19** [comment]
multiplayer kick is intended. It's here to flag you in the logs when you are trying to cheat with it.

**Comment by wildejackson** [comment]
Its just clicking back to inventory? How is that a cheat? Without any indication its very easy to have the items stuck in the atlas. Prehaps a warning on the item label or anything to indicate that using the item (clicking the button) will result in a kick and items not being retrievable.

**Comment by boubou19** [comment]
Bibliocraft is a good looking mod, but also an heavy one for rendering and more importantly, an easy mod to abuse because the mod trusts the client where it should not. So we put some kicks and logs in the console when using particular stuff that is known to trust the client. That was done mainly to counter cheaters with hacked mods/clients. Putting a big red warning saying "don't use this item you may be flagged for cheat" will just ease the life of cheaters. Now i agree that if it flags you when using it normally, that sucks, but i doubt there is much we can do without rewritting the atlas logic, and i'm not sure i'll happen because the mod is all right reserved, so one must use ASM or mixins, like ModMixins does to patch bibliocraft.

**Comment by wildejackson** [comment]
Alright, well I'll close the ticket, but I think that this particular solution should definitely be looked into in the future. It is a brute force solution that I'm sure could result in players getting frustrated but I don't think many players other then myself even use the atlas so I suppose its not that high of a priority at the moment.
