### ISSUE TITLE
High Pressure Solar Boiler - wrong visual volume

### ISSUE THREAD

**Issue by Volkoff96** [GTNewHorizons/GT-New-Horizons-Modpack#8253]
#### Which modpack version are you using?
2.1.1.1
#
#### If in multiplayer; On which server does this happen? 
Solo/Server
#
#### What did you try to do, and what did you expect to happen?
High Pressure Solar Boiler show max 32000 mB
![HPSB_out](https://user-images.githubusercontent.com/73396969/126037295-0e9ab709-0d2c-4c80-8aff-61fe565141a1.PNG)

#
#### What happened instead? (Attach screenshots if needed)
But the internal scale fills up as if maximum 16000 mB
![HPSB_in](https://user-images.githubusercontent.com/73396969/126037298-cdf80878-7034-4d55-b070-29151de3e3e7.PNG)

#
#### What do you suggest instead/what changes do you propose?
This is one of the extremely minor things, but still, I want you to be aware of it.
#
#### What is your GTNH Discord username?
Volkoff96#0079

**Comment by Dream-Master** [comment]
guess it used the gui from the bronze one.

**Comment by Volkoff96** [comment]
> guess it used the gui from the bronze one.

Well, it's a small thing, but my friend and I have fallen for it 3 times already, it wasn't immediately clear where the water was going, if it's hard to fix, just close the "Issues" :-)

**Comment by Dream-Master** [comment]
i guess it need a new gui and some code changes.

**Comment by D-Cysteine** [comment]
I think this might be fixed by replacing `15900` here:
https://github.com/GTNewHorizons/GT5-Unofficial/blob/experimental/src/main/java/gregtech/common/gui/GT_Container_Boiler.java#L54
with `((((GT_MetaTileEntity_Boiler) this.mTileEntity.getMetaTileEntity()).getCapacity() - 100)`

It looks like most boilers inherit a default capacity of `16000`:
https://github.com/GTNewHorizons/GT5-Unofficial/blob/experimental/src/main/java/gregtech/common/tileentities/boilers/GT_MetaTileEntity_Boiler.java#L362
but this is overridden to `32000` for the HP solar boiler:
https://github.com/GTNewHorizons/GT5-Unofficial/blob/experimental/src/main/java/gregtech/common/tileentities/boilers/GT_MetaTileEntity_Boiler_Solar_Steel.java#L64

**Comment by Volkoff96** [comment]
Checked, it worked, I just replaced 15900>32000
![Dokit1](https://user-images.githubusercontent.com/73396969/126051905-0e877d77-afc2-403f-83ea-8f2f567b0bbf.PNG)
![Dokit2](https://user-images.githubusercontent.com/73396969/126051906-3dc754a1-3d09-4977-ae13-47b97f9d3c74.PNG)

**Comment by Volkoff96** [comment]
Upd: I forgot, a simple boiler also visually changes the volume, it turns out it is necessary to change the code, but I'm not good at this, good luck! :< 
![asrg](https://user-images.githubusercontent.com/73396969/126052053-08493cb5-364e-48ea-b4c3-1e3e811cb69d.PNG)
