### ISSUE TITLE
[suggest] add new Material Tree nei page like gtce

### ISSUE THREAD

**Issue by Pnc6lx** [GTNewHorizons/GT-New-Horizons-Modpack#8300]
i find this cool thing in gtce, so if gtnh can have similar page like gtce?
[](https://github.com/Gregicality/GregTech/pull/48)

**Comment by Prometheus0000** [comment]
? There's nothing there?

**Comment by Pnc6lx** [comment]
oh i get a mistake 
https://github.com/Gregicality/GregTech/pull/48
so [](https://github.com/Gregicality/GregTech/pull/48)

**Comment by Prometheus0000** [comment]
It definitely looks cool, and seems based off a certain wiki page type https://ftbwiki.org/Aluminium_(GregTech_5_Material) which also includes ore to dust parts (if it listed byproducts as well that would be great). But this is for JEI, and thus 1.12, so I have no idea whether it could be used in NEI or not. @mitchej123

**Comment by kumquat-ir** [comment]
author of that pull here!  it is in fact based off of that wiki page layout

the first draft layout did have ore to dust in it, but that was removed because of space concerns (as well as ore processing and byproducts already having their own JEI page, I'm going to rework that one as well)

no idea what the differences in api between NEI and JEI are, so I can't really say whether it can be done in NEI

**Comment by D-Cysteine** [comment]
Thanks for the suggestion! This has been implemented in:
 * https://github.com/GTNewHorizons/nei-custom-diagram/commit/3f61b114261b9ca1178e88b4c558ce1299e23f1a

Not quite as nice-looking as the JEI version, but I tried to pack as many things onto that page as I could.

Screenshot:
![BlastFurnaceTemp](https://user-images.githubusercontent.com/54219287/131233028-775ff461-c38c-428a-b0a1-0bfbfd73cee5.png)

**Comment by Prometheus0000** [comment]
- Could you say what two icons not highlighted do? Also, are there more hidden?
 - There's also the mostly useless double+ ingots and the other plates.
 - Wouldn't it be better to display the fluids as cells? Also, I'm not sure why there's 4 slots there? Plasma? Or two used for titanium.
 - If you can, showing which coil you need would be nice, but some would end up saying inaccurate stuff later on, as you need to use the heat bonus. But I think that's only for Dr* in UHV.
 - The frame alignment bothers me
 - I guess there wasn't room to make it fancy with all the arrows? Or you don't feel like it right now.
 - I hope you can check recipes linking from them?

Looks good though.

**Comment by D-Cysteine** [comment]
* Gear icon: shows all diagrams. Book icon: shows basic info about the material on hover (name, chemical formula, and warnings about radioactivity, hot, cold). There aren't any more buttons hidden, though there is a related materials box to the right that doesn't show for titanium. This shows stuff like iron -> wrought iron, magnetic iron.
 * They're added in, though I'm not sure how useful they are. They do take up quite a bit of space. I took that screenshot on a minimal set of mods, so it's missing a bunch of stuff. See screenshot below for a complete view.
 * There's 4 slots because for some things, like water, up to 3 fluids are shown in there (water, steam, ice). Some of these fluids don't have cell forms available (e.g. steam), so it won't always be possible to show cells for them. Most of them (like probably 95%+) could be shown in cell form, though. Also, the blank space to the right of the fluids is used to show cracked fluids, if those exist for the material; and further to the right of that would be gems and lens, if those exist.
 * Yeah, that would be a nice feature to have. I need to see if there is a way to get the temps for the coils without hard-coding them, in case they change. Also note that the temperature display is actually not always accurate: I noticed that it says 3,600K for end steel, but the actual recipe requires 4,500K. I'm reading the property off of the GT material enum so I think it's just not getting set right (or is being overridden) in at least that one case.
 * Lol, yeah, now that you mention it it does look a bit off. The alignment makes more sense in a view with more parts shown; see screenshot below. Though I do think that that particular row could probably be arranged a bit better.
 * Not enough room, plus there's a lot of different ways to make certain things (e.g. lens can be made from flawless gem or plate), so I wasn't sure how to handle that.
 * Yup, everything is fully linked, even the fluids!

![AllParts](https://user-images.githubusercontent.com/54219287/131233463-15c4b041-1199-48f2-90d8-2ed98b2f37c4.png)

**Comment by glowredman** [comment]
Is NEICustomDiagram already in the dev pack?

**Comment by bombcar** [comment]
> 

Should be since 2.1.1.4

**Comment by YannickMG** [comment]
Good to close?

**Comment by boubou19** [comment]
yup
