### ISSUE TITLE
Creative Essentia Cell

### ISSUE THREAD

**Issue by hucking** [GTNewHorizons/GT-New-Horizons-Modpack#8305]
I suggest adding a recipe for this. Making enough essentia for the octuple compressed solar is extremely laggy, I suggest adding a recipe for the creative essentia cell beacuse there is almost no way it would be more annoying to craft than the actual solars themselves. I also just don't see why this wouldn't be craftable in addition to all the other currently craftable creative items.

We're honestly just thinking of voiding the items directly and cheating in the creative cell just to avoid the massive amounts of lag that the alchemical furnaces would create. If you don't like this idea I suggest adding alternatives to the recipes either without infusion crafting or giving us better ways to make essentia that isn't as laggy, but again I don't see why it wouldn't have a recipe.

**Comment by yukieiji** [comment]
If the alchemical furnaces causes a lot of lag, why not just fix it?

**Comment by repo-alt** [comment]
You would need to rewrite TC to really fix it, but some improvement probably may be achieved

**Comment by boubou19** [comment]
the point of the octuple compressed solar panel is that it's a meme item that wasn't supposed to be craftable. So yeah, the pain of making that much amount of essentia is intended. Creative cells are meh because it's as if you were cheating the essentia. Also for the lag, i think Glee8e partially fixed it with his thaumcraft mod. Be sure to have latest TC4Tweaks on the server side. And if it's not fixed by that mod, then please provide a warmroast report incriminating the alchemical furnaces, because the pack would benefit more from fixing lag than adding a way to bypass it.

**Comment by yukieiji** [comment]
I think it's wrong to make it easy to craft a UMV generator(octuple compressed solar panel) in the current GTNH, which is only implemented up to UEV.

**Comment by hucking** [comment]
Well what is the logic behind making the other creative items craftable then? You're "cheating" the free energy with the infinite energy cell from AE2, you're "cheating" the free aspects in the arcane crafter with the creative wand and the infinity armor (which alongisde the sword and the pickaxe gives u "cheating" amounts of power anyway). In my opinion if you make the creative essentia cell a hard enough recipe you absolutely have "earned" the right to have infinite amount of essentia, especially because it bypasses the problem of the lag.

Also if the octuple solar really is meant to be a meme item that is "uncraftable" as you yourself said, why is it part of the questbook and why is it in the pack in the first place. If the intended way for you to get power in the pack is to spam dozens or even hundreds of fusion reactors and hundreds or thousands of plasma turbines to get stargate in less than multiple years, which I will add my personal take that it's uninteresting and tedious, I think adding this way to get essentia is actually a great way to balance the pack.

I also don't see why the recipes to make it have to be infusion or require that much essentia, you could easily make the recipe require an equal amount of items without taking a mod that clearly isn't meant to be used in this way to the extreme and being extremely laggy. I would actually welcome a world in which you have to use twice the amount of materials but none of the crafts are through the fusion matrix personally.

Basically all I'm saying is, instead of trying to fix a problem that is created by the recipes being the way they are, why not give us a reasonable way to make this essentia, or require an amount that is consistent with the way the mod is supposed to be used, or dont make it an infusion recipe at all?

This is just my personal take anyway you're welcome to disagree but I dispute your reasoning. Also this pack may be "implemented" up to UEV but currently if you run your MEBF at UEV it will take you 9 months (with radon) to cook enough neutronium (JUST THE NEUTRONIUM) to get a single stargate (and I assume that since they're meant to be linked up the intent is for you to make 2 of em, meaning that's 1.5 years).

Now don't get me wrong, I'm not arguing that the octuple should be easy to craft, nor do I think it is actually easy to craft anyway even with the creative essentia cell, which btw you arguing that it's going to be "easy" is up to what the recipe to make it will be... not to mention that it's arguably not that difficult to obtain the necessary items to make the essentia (6.5mil salis and 3.3mil charcoal) it's just that making them into essentia is laggy, which as far as I am concerned, shouldn't be the "difficulty" of anything in any pack.

Regardless we will craft the solar even with the current methods, as our dedicated server is quite beefy and can probably handle this, even though it's 1.7 so it's gonna be laggy no matter what we do probably. This is just a suggestion as I consider this a flaw in the pack that endgame power is basically only fusion or solar and both seem to me at least, tedious and uninteresting and I think adding the essentia cell will be a fun way to make solar more interesting of a challenge (assuming you give it an interesting recipe at least) rather than just tick accelerating alchemical furnaces and the infusion matrix.

**Comment by boubou19** [comment]
> Well what is the logic behind making the other creative items craftable then? You're "cheating" the free energy with the infinite energy cell from AE2, you're "cheating" the free aspects in the arcane crafter with the creative wand and the infinity armor (which alongisde the sword and the pickaxe gives u "cheating" amounts of power anyway). In my opinion if you make the creative essentia cell a hard enough recipe you absolutely have "earned" the right to have infinite amount of essentia, especially because it bypasses the problem of the lag.

If you look carefully, the only creative stuff that is provided is giving power or instant speed. And in no case the creative items are removing a core mecanic from a mod (neutronium energy cell is here to make you be able to keep up with AE power cost, otherwise you'll spend forever making enough energy to sustain your AE while you progress for exemple, Chaotic capacitor bank is giving you infinite RF, but please find me an item/block needing gigantic amount of RF that cannot be easily fed with EU). You are asking for an item that gives infinite essentia, a thing linked to the core of thaumcraft, so once you have it, boom, infinite essentia, you can remove all the infra needed to make essentia.

>Also if the octuple solar really is meant to be a meme item that is "uncraftable" as you yourself said, why is it part of the questbook and why is it in the pack in the first place. If the intended way for you to get power in the pack is to spam dozens or even hundreds of fusion reactors and hundreds or thousands of plasma turbines to get stargate in less than multiple years, which I will add my personal take that it's uninteresting and tedious, I think adding this way to get essentia is actually a great way to balance the pack.

You will surely have understood by yourself that the pack is unfished past UHV: UEV is only here to justify the deep dark recipe, and there is no real content. Also, if you want to craft the octuple solar panel, i think you somehow like the tediousness of it, because the recipe is not hard, but it needs some crafts to be spammed more than a few M times. So a bit more tedium at that point is nothing. We are on our way to get cool generators via Good Generators. 

>I also don't see why the recipes to make it have to be infusion or require that much essentia, you could easily make the recipe require an equal amount of items without taking a mod that clearly isn't meant to be used in this way to the extreme and being extremely laggy. I would actually welcome a world in which you have to use twice the amount of materials but none of the crafts are through the fusion matrix personally.

That i can agree with, but i guess that is because the mod providing it is a thaumcraft addon, so it uses thaumcraft crafting mecanics. Tho lag shouldn't be an excuse to avoid certain stuff, because if lag isn't purely tied to the scale of it, then it means it can be improved, but we can't really do that if no profiling report are made. There is a huge difference between saying something is laggy and giving something that quantifies how laggy it is, with what part of it is laggy. In the latter case, we can actually do something.

> Basically all I'm saying is, instead of trying to fix a problem that is created by the recipes being the way they are, why not give us a reasonable way to make this essentia, or require an amount that is consistent with the way the mod is supposed to be used, or dont make it an infusion recipe at all?

You are asking something to ease the craft of a block that generates UMV power. Let's say it once again: The pack is not finished after UHV, 3 tiers below UMV. So yeah, it's not supposed to be crafted, because there is no content matching this generator. But the pack still provides a recipe for it for those who are motivated enough to get it. Maybe we could rework it to use materials from the UMV tier when it will exist instead of this insane set of recipes.

> This is just my personal take anyway you're welcome to disagree but I dispute your reasoning. Also this pack may be "implemented" up to UEV but currently if you run your MEBF at UEV it will take you 9 months (with radon) to cook enough neutronium (JUST THE NEUTRONIUM) to get a single stargate (and I assume that since they're meant to be linked up the intent is for you to make 2 of em, meaning that's 1.5 years).

You are highlighting one of the worse aspects of the endgame: it's current balance. (even if the stargate is also a meme item and wasn't really meant to be crafted too. Originally, the recipe was wayyyy too hard to be even considered worth crafting, so we ended up with the actual recipe) But this is more general and should be reworked one day i hope.

> Now don't get me wrong, I'm not arguing that the octuple should be easy to craft, nor do I think it is actually easy to craft anyway even with the creative essentia cell, which btw you arguing that it's going to be "easy" is up to what the recipe to make it will be... not to mention that it's arguably not that difficult to obtain the necessary items to make the essentia (6.5mil salis and 3.3mil charcoal) it's just that making them into essentia is laggy, which as far as I am concerned, shouldn't be the "difficulty" of anything in any pack.

Yeah, at no point i thought you wanted to ease the recipe, it's just that i really want the pack to be lagfixed than having alternatives to bypass the lag. Players shouldn't need to play according to the lag they make, but at endgame it's nearly impossible sadly. So best thing we can do is make a profiling of the server and report laggy parts of code.

> Regardless we will craft the solar even with the current methods, as our dedicated server is quite beefy and can probably handle this, even though it's 1.7 so it's gonna be laggy no matter what we do probably. This is just a suggestion as I consider this a flaw in the pack that endgame power is basically only fusion or solar and both seem to me at least, tedious and uninteresting and I think adding the essentia cell will be a fun way to make solar more interesting of a challenge (assuming you give it an interesting recipe at least) rather than just tick accelerating alchemical furnaces and the infusion matrix.

As i said above, we are getting a mod Called Good Generators that will, i hope, give more choices in the power gen options.


Now, i have one question: why don't we make a multismelter-like multiblock to bake the essentias? Because i'm sure it'll be more efficient than just drop a lot of items in the advanced alchemical boiler and world accelerate it.

**Comment by hucking** [comment]
yes a multiblock will be very welcome and I will be happy to provide profiling once we have set up the infrastructure for the octuple. I also can see the logic behind your last message far more than your first message, and for that I am thankful.

**Comment by hucking** [comment]
You seem to have set your mind to not add this so I will not argue my point further but I will point out that you have added multiple items that "break the core" of the 2 mods, thaumcraft has 0% vis cost in the arcane crafter with infinity armor which bypasses the "intended" way for u to obtain the vis, and blood magic has the infinite orb which gives u infinite LP (which I assume was added because it reduces the amount of lag the well of suffering would create? which seem to contradict your points)
I still stand behind what I said tho, multi would be very welcome and a great fix instead of creative essentia cell, I guess you devs don't like shortcuts I'll hand that to you.

**Comment by boubou19** [comment]
My point is not absolute: i'm giving my opinion like you do. If Dream says it's worth adding, it will be added. The infinity armor trick in the arcane assembler is more the result of an unintended feature imo, and makes no real sense, because at that point, why go through an arcane assembler if it's to craft the items without vis cost? Blood Magic is super laggy when automated so yeah you are right, this seems to be an exception to my reasonning.

**Comment by GTNH-Colen** [comment]
You are not truly supposed to be able to reverse the LP out of an orb of armok iirc but you can with one extra ritual I believe. It's more to prevent you needing to charge your personal LP network than craft with.

I'm not against a recipe for this time, at least until we get something that could output essentia in insane quantities like a GT multiblock. However it would need to be a meme item in itself given it's quite powerful and would bypass a core TC mechanic. (Finally somewhere to use a quatum circuit? :yobaface: )

**Comment by hucking** [comment]
well I'm still for the recipe being a thing but I might have been wrong on how laggy the furnaces are, I still need to do more testing.
