### ISSUE TITLE
Add view cell support to the wireless crafting terminal

### ISSUE THREAD

**Issue by S4mpsa** [GTNewHorizons/GT-New-Horizons-Modpack#8332]
#### Which modpack version are you using?
2.1.1.0
#
#### If in multiplayer; On which server does this happen? 
Private Server
#
#### What did you try to do, and what did you expect to happen?
Filter the wireless crating terminal.
![image](https://user-images.githubusercontent.com/69092953/127871113-d6521453-b45f-47ce-a4d4-427092db2678.png)

#
#### What happened instead? (Attach screenshots if needed)
Does not have view cell slots.
![image](https://user-images.githubusercontent.com/69092953/127871146-9a2aa2b1-7f59-4151-9e33-fc443b144d7e.png)

#
#### What do you suggest instead/what changes do you propose?
Add view cell slots to the wireless crafting terminal, like all other terminals have.
#
#### What is your GTNH Discord username?
Sampsa

**Comment by Retster** [comment]
Would be wery cool. And if it's posible please add also posibility to enable/distable view cells that already in the terminal, because its not wery convinient every time get it from some inventory and put in to view slot. In the standart terminal that problem is solved with just making another one terminal but in wireles wersion that not possible. Thanks.

**Comment by Dream-Master** [comment]
Guess this was added @D-Cysteine ?
