### ISSUE TITLE
Bartworks dusts take too long to centrifuge

### ISSUE THREAD

**Issue by Pxx500** [GTNewHorizons/GT-New-Horizons-Modpack#8366]
#### Which modpack version are you using?
2.1.1.1a
#
#### If in multiplayer; On which server does this happen? 
Private
#
#### What did you try to do, and what did you expect to happen?
I wanted to use bartworks ores
#
#### What happened instead? (Attach screenshots if needed)
They clogged my entire ore system
#
#### What do you suggest instead/what changes do you propose?
- Lower time it takes to centrifuge bartworks dusts, some take even 400 sec@LV
- Add option to wash them in a simple washer
- Add option to wash them

Something else maybe?
#
#### What is your GTNH Discord username?
Pxx500#6984

**Comment by Sphyix** [comment]
Workaround for now, use thermal centrifuges for bw ores, maybe GT++ to keep it efficient

**Comment by GTNH-Afx237v7** [comment]
Make more or better centrifuges?

**Comment by Pxx500** [comment]
The question is why are their base times so high compared to other dusts?

**Comment by Sphyix** [comment]
> The question is why are their base times so high compared to other dusts?

bw :)

**Comment by Pxx500** [comment]
> > The question is why are their base times so high compared to other dusts?
> 
> bw :)

Just because it's bartworks doesn't mean it should be longer than comparable dusts for no reason

**Comment by GlodBlock** [comment]
because the way bart used to calculate material mass is different from gt5

this is how bart calculate mixture's mass, he simply adds up the contents' mass
https://github.com/GTNewHorizons/bartworks/blob/master/src/main/java/com/github/bartimaeusnek/bartworks/system/material/Werkstoff.java#L221
this is how gt5 calculate the mass, the mixture's mass is the average mass of its contents
https://github.com/GTNewHorizons/GT5-Unofficial/blob/experimental/src/main/java/gregtech/api/enums/Materials.java#L2450

as a result, all bart's alloys or compounds have a ridiculous process time, since the material's mass determine it
maybe change the mass calculation into gt5 way can make it more reasonable
