### ISSUE TITLE
Reset all quests after reinstall GTNH

### ISSUE THREAD

**Issue by JohnWarrior01** [GTNewHorizons/GT-New-Horizons-Modpack#8404]
Latest
Solo
BackUp, Edit json files
Nothing

HI there, after re-install GTNH all quests was reset. I tried load backup, default load, load another backup - nothing

Went into save-folder, file namecache. BQ creates new profile in it with my name, but another ID. Changing id by previous - nothing.

What can I do with that.

**Comment by boubou19** [comment]
it happens when you play without retrieving the auth token from mojang, so either connect to internet before logging in or use the reath button in the multiplayer screen if your game is already loaded. If you use cracked minecraft then you can't do nothing. Also, this is not the place to ask this kind of questions, prefer asking them in #help in discord, or in #russian-general.
