### ISSUE TITLE
Bats perhaps shouldn't explode.

### ISSUE THREAD

**Issue by Logos-Askrson** [GTNewHorizons/GT-New-Horizons-Modpack#8405]
#### Which modpack version are you using?
2.1.1.0
#
#### If in multiplayer; On which server does this happen? 
Eta
#
#### What did you try to do, and what did you expect to happen?
When a swarm of bats spawned due to the warp event, I tried removing them with my sword in an attempt to minimize lag and squeaking. I expected no issues in doing so.
#
#### What happened instead? (Attach screenshots if needed)
Bats, as it turns out, are effected by the passive mob rule where mobs can explode if slain without a knife. Given that 20-ish bats spawned, this resulted in a fair few explosions in clearing them.
#
#### What do you suggest instead/what changes do you propose?
As the explosions seem meant to encourage players to use proper tools to slaughter animals for food in the early game, and bats aren't an early-game food source, I'd propose that bats be exempted from the rule of causing explosions randomly when slain.
#
#### What is your GTNH Discord username?
Logos

**Comment by leagris** [comment]
Once again, Gregtech employs mafia methods by creating threat, degrading conditions, and then subjecting the player to a technology tax that merely returns what was usurped from the player at forced price.

Instead of making its slaughtering knife and butchery knife relevant by improving yield, durability, ease of use, it degrades the other tools with explosions and merely provide the service it degraded.

I'd suggest instead of exploding mobs, to significantly multiply the drops of passive mobs slaughtered with Gregtech knives as if these had a looting X.

**Comment by Prometheus0000** [comment]
I don't think anyone likes the kamikaze-ing, except namikon and dream. But no one's made a PR to turn it off. I'm pretty sure the butcher's knife has looting on it, but I dunno about the knife. Really, mobs exploding adds nothing to the game.

**Comment by TimeConqueror** [comment]
We could also turn it off when the player reaches some tier. As if he's in HV, he knows more about the world, so the cows now won't cause explosions.

**Comment by Prometheus0000** [comment]
Discussions on how to determine what tier someone is at before went nowhere though. Also, that doesn't make sense. Also, it would be pointless, since you basically don't need leather anymore at that point.
