### ISSUE TITLE
[Draconic Evolution] EU energy multiblock proposal

### ISSUE THREAD

**Issue by SteamDoge9000** [GTNewHorizons/GT-New-Horizons-Modpack#8424]
~~Like seriously, the energy multiblock can store only RF and not EU and not even its reactor gernerates the power unit that gt machines uses, so what is the purpose of having a mod that can store and generate massive amounts of power if its not a power unit that is used for its machines? Its just dead-weight unless someone is willing to make its power generation and storage into EU instead of RF~~

What if the dopeness of the multiblock energy storage could be made into a gt structure

like a Multiblock working within a multiblock so that it still renders the cool effects but it also being able to store EU in lage amounts depending on the energy multiblocks core

think of this like gregifying the existing multiblock for the RF multiblock with a Housing using GT stuff

**Comment by SteamDoge9000** [comment]
even its energy relays are pointless

**Comment by boubou19** [comment]
can't you just ask this on #general in the discord instead of opening tickets for that kind of stuff? To anser your question, DE is here because of all the useful items it has, like armors, mobspawner, distortion flame, draconic staff, charm of dislocation... DE is not here for powergen. Also, we already have several ways to store energy on this pack: the LSC, the PSS, active transformers, LESU, or the ultimate batteries for exemple.
