### ISSUE TITLE
Large Essentia Generator Hint block is missing

### ISSUE THREAD

**Issue by yukieiji** [GTNewHorizons/GT-New-Horizons-Modpack#8427]
#### Which modpack version are you using?
2.1.1.2
#
#### If in multiplayer; On which server does this happen? 
single
#
#### What did you try to do, and what did you expect to happen?
I tried to build Large Essentia Generator(Good Generator)
#
#### What happened instead? (Attach screenshots if needed)
This wasn’t assembled because the hint blocks that go out where the hatches should be placed were not placed.
#
#### What do you suggest instead/what changes do you propose?
Fix it
#
#### What is your GTNH Discord username?
yukieiji

**Comment by GlodBlock** [comment]
can you provide me with some screenshots?
it can be assembled well and run at my side.

**Comment by yukieiji** [comment]
Where are hint blocks?
![2021-08-20_00 13 32](https://user-images.githubusercontent.com/40425798/130094524-8f21cce4-d6b0-414a-8ec5-5b9e359590e3.png)
![2021-08-20_00 13 55](https://user-images.githubusercontent.com/40425798/130094486-3c214caf-2f67-4286-b444-fda005d8d9cd.png)

**Comment by GlodBlock** [comment]
you can right click the controller block with the blueprint to see the projection.
![2021-08-20_10 16 54](https://user-images.githubusercontent.com/60341015/130168733-ba72ca88-015a-4660-b2f1-d5b55888cc6a.png)
and you could see the hint block.
if you hold shift to place the block, these hint blocks will be replaced by casing blocks because most blueprint-supported machines follows this rule. i am sorry if it bothers you.
by the way, the LEG has some problems in current version, it will explode if there are too much essentia in the hatch. this will be fixed in next version.

**Comment by Glease** [comment]
Make sure you weren't accidentally using the blueprint from structurelib. currently the two items are incompatible with each other.

**Comment by Glease** [comment]
@yukieiji Can you verify you aren't using the structurelib version of blueprint? If you are using that we will be closing the issue as it is indeed not a bug.

**Comment by yukieiji** [comment]
I've confirmed that using TecTech's blueprints place a hint block.
Looks like it was replaced hint block by a casing because it was used with the shift.
