### ISSUE TITLE
GT oil/gas/fluid pumps don't save their pumping changes on server reboot

### ISSUE THREAD

**Issue by boubou19** [GTNewHorizons/GT-New-Horizons-Modpack#8466]
### Your GTNH Discord Username

boubou_19#2706

### Your Pack Version

2.1.1.0

### Your Server

Delta

### Type of Server

Thermos

### Your Expectation

I was pumping molten copper on alpha centauri Bb, everything was fine, It finished, decided to move it to a near max molten copper zone, pumped it again, it finished as well. Then server reboot happened. I expected the zone to be empty after reboot, because that's what was the area supposed to be before reboot.

### The Reality

When i came back, i misclicked with my electric prospector scanner, and i saw that outside of the chunk where my 7 pumps are, they all came back to the state before i started to pump. So that makes me 17M copper with every reboot. If i just use one pump and fine tune its speed to not finish before the reboot, that's an endless pumping zone.

![image](https://user-images.githubusercontent.com/12850933/131216758-cb127d06-54c5-48dd-a144-7ec20e786084.png)

I use default configuration for the multi block controllers, and i put a passive anchor in the chunk if that matters.

I'm not the only one having this, as i toyed with this after i received a weird report saying there was endless fluid coming out of the pumps.

### Your Proposal

Looks like the fluid data in chunks aren't properly saved, So maybe ensure to save the fluid data in the chunk every X secs.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by GTNH-Colen** [comment]
Tbh I'm not sure I'd classify this as a minor bug given it dramatically increases the output of a potential field of fluids or potentially makes it near infinite completely undermining the purpose of having finite fluid in a field.

**Comment by bombcar** [comment]
Especially since many servers have periodic reboots (mmcc does four hours which seems it would be real easy to exploit).

**Comment by Prometheus0000** [comment]
Don't they already basically last forever anyway?

**Comment by boubou19** [comment]
No: they just have a random chance to decrease the field value each pumping operation. For exemple, with a near max molten copper field (~285) i am able to pump it all in less than 2h with 7 pumps. I suspect this bug is here since a very long time, and that could explain why everyone has the feeling that a fluid field is lasting very long.

**Comment by Sphyix** [comment]
> Don't they already basically last forever anyway?

Have you actually ever played this game?

**Comment by Prometheus0000** [comment]
That's what I heard from others, I never finished using the one or two oil spouts I collected since it wasn't my primary power source.

**Comment by GTNH-Colen** [comment]
Pumps are used for way more than just oil later on so this is quite important honestly.

**Comment by Prometheus0000** [comment]
I'm not complaining about fixing it, I just don't know if it's worthy of being called 'major' bug, that's all.

**Comment by Sphyix** [comment]
> I'm not complaining about fixing it, I just don't know if it's worthy of being called 'major' bug, that's all.

Look at this bug like being able to make 500+ ingots of copper, iron, lead per second (and something else I believe, I don't remember) and being able to restart it at every server reboot, making million of ingots every reboot without even needing to do anything

**Comment by Prometheus0000** [comment]
OK? Why do you feel the need to convince me? I've never even used one? I guess there's some setting that makes them run out way faster than oil, or the reverse.

**Comment by GTNH-Colen** [comment]
> I just don't know if it's worthy of being called 'major' bug, that's all.

> OK? Why do you feel the need to convince me?

You literally said you aren't sure if it's worthy of being called a major bug, he tries to convince you and your response is to ask why he wants to convince you? What are you even on about? Please just stay out of the matter if you don't have any experience with it, otherwise we're all just going round in circles wasting time over pointless pedantry.

**Comment by Glease** [comment]
I still can't identify why this is not saved, nor can I replicate in my test worlds and on my own server (forge though). If it is not saved unconditionally then it's obviously we have a bug here, but now it just seems like a thermos problem to me again. 

Due to how fluid data is stored on disk, you can't really save it every X seconds without forcing a world save every X second, which would obviously just cause too much lag.

**Comment by Glease** [comment]
Basically, fluid data is associated with chunks. If a chunk never loads, it will use the default, i.e. as if it has got a reset.
Since high tier fluid drills never actually load all the chunk it operates on (which would be absolutely stupid), the data is never loaded NOR saved.
To fix it, either we force load the chunk once a while (which is .. well, bad), or we need to move the fluid data out of region files, which would come with a ton of migration problems and the need to design an efficient storage layout.
I don't quite have a good idea on fixing this without . I'll just leave the info here and see if others got some better ideas.
