### ISSUE TITLE
Binnie, Renaming a drawer in Compartment is Extremely Bugged and needs better support for managment

### ISSUE THREAD

**Issue by Shibva** [GTNewHorizons/GT-New-Horizons-Modpack#8483]
### Your GTNH Discord Username

Shibva_

### Your Pack Version

2.1.1.0

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

Renaming A drawer; Trying to use NEI and Inventory Sort on it; expecting renaming and NEI recipie lookup and inventory sorting to work like with chest

### The Reality

unable to use NEI in its GUI nor the "sorting" hotkey for inventory sorting (Inv Tweaks)

The feature on renaming the compartment you sellected is gliched as fuck and makes it near impossable to type comprehencable lables without it glitching the fuck up on its pos (like when you try to name a shelf, "components" it will instead bug out and make it say "sntenopmco"

### Your Proposal

please fix this issue, even if its a small thing

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [x] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by SteamDoge9000** [comment]
https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/8483
video documentation of the 2 issues (note: the seemingly long pause was me using the Recipie and Uses keybind for nei [R and Shift + R])

**Comment by SteamDoge9000** [comment]
Update: Aura Helped me out with checking to see if it was one their client and both the NEI functionality bug and the Tab renaming thing on the binne compartment fucked up when he/she tried to rename the compartment 

checking off that it was reproduced with others

**Comment by leumasme** [comment]
Why was this closed? Very annoying issue, makes working with the Compartment UI a massive pain.
- Typing in the compartment tab renaming box triggers hotkeys when letters are pressed
- Renaming/Recoloring compartment tabs lags back and forth (bad server-client sync implementation?) and makes typing nearly impossible
- Effectively all inventory actions do not work (Neither modded like NEI sort+multi-stack transfer; nor Vanilla like double-click to stack+drag to spread). It seems like the mod author made completely custom inventory logic? Probably wont be too easy to fix in this case.

https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/29953391/59ed6b77-561f-4ba9-987a-729b52c87f53

**Comment by mitchej123** [comment]
Because it's a 2+ year old issue that nobody has followed up on or seems interested in working on?

**Comment by boubou19** [comment]
Closed is just a state for a ticket. Sadly no one is interested in fixing it, so it'll stay as is until someone come and pick this issue. Maybe it will be you?

**Comment by leumasme** [comment]
So closing (as "not planned") for you does *not* mean that the issue requires no further attention / has been resolved?  
I personally believe that a bug report should not simply be closed because noone is working on it, even if just for documentations sake (e.g. someone searching to see if this issue was already reported having an easier time finding it) - it's still a bug (unlike a feature request, which does *not* exist until implemented and will thus have no effect if ignored);  
I guess I was not aware what Closing an issue means to you / how you handle bugs that noone is working on.

**Comment by Shibva** [comment]
There is a newer version for 12.2 that is receiving bug fixes so I'm not exactly sure how much work it would need to back those fixes

**Comment by boubou19** [comment]
> So closing (as "not planned") for you does _not_ mean that the issue requires no further attention / has been resolved? I personally believe that a bug report should not simply be closed because noone is working on it, even if just for documentations sake (e.g. someone searching to see if this issue was already reported having an easier time finding it) - it's still a bug (unlike a feature request, which does _not_ exist until implemented and will thus have no effect if ignored); I guess I was not aware what Closing an issue means to you / how you handle bugs that noone is working on.

@leumasme We are all working on the pack on our free time, without getting paid. The important thing is that the bug is reported. You have no idea of how much stopping it is to just open the tracker and see the sheer amount of open tickets. So we stick to the main bugs that we want to fix and / or care about. If you aren't happy then take some time to learn how to mod and fix the issue yourself. We will happily help you in learning how to mod the 1.7.10 over our discord. If you don't intend to fo that, then stop wasting our time and yours by complaining. We made our mind.

**Comment by mitchej123** [comment]
> I personally believe that a bug report should not simply be closed because noone is working on it

Your opinion has been noted and rejected.  Feel free to run your own projects that way.   We have decided that having 700+ stale issues that nobody wants to work on is not helpful.  


If you or someone else wants to pick it up and fix it great, please do.  If not it stays closed.

**Comment by SenkJu** [comment]
> Your opinion has been noted and rejected.  Feel free to run your own projects that way.   We have decided that having 700+ stale issues that nobody wants to work on is not helpful.  
> 
> 
> If you or someone else wants to pick it up and fix it great, please do.  If not it stays closed.

Now nobody digging through issues will even consider working on this one since it is already closed. Why is having an open issue for an actual, unresolved bug a problem? Even if *you* aren't going to fix it. I'm struggling to understand what kind of thought process led to the decision to simply close issues and not even labeling them as 'Won't fix'.

**Comment by mitchej123** [comment]
1) It's labeled "comment to reopen" and "stale"
2) Bugs often do inadvertantly get solved between versions, We're not going to re-check every single open bug -- If you want to, by all means
3) You're not the first person to bring this up and unless you're going to step up and do it, then stop telling us how to handle our issues.
