### ISSUE TITLE
Allow high-tier Glass in the Cleanroom

### ISSUE THREAD

**Issue by Savallator** [GTNewHorizons/GT-New-Horizons-Modpack#8487]
### Your GTNH Discord Username

Boldar#1676

### Your Pack Version

2.1.1.2

### Your Proposal

I quite like having windows to look into the Cleanroom and making even bigger windows.
I see the need of being forced to craft a large amount of Plascrete for your first cleanroom, but what about allowing Higher Tier glass (like, starting with Tungsten-Reinforced Borosilicate Glass) just flat out replacing Plascrete? Since that is available starting with EV and costs quite some ressources.
It would not change the first cleanroom experiences, but allow for a more interesting Design later on.
I already looked at the source, it should not be that hard to implement. If this gets approval, i can make a PR for it.

### Your Goal

Moar fancy Cleanrooms.

### Your Vision

Make Moar Fancy Cleanrooms.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by bombcar** [comment]
We can already use the reinforced glass but it's kinda ugly with bars etc.

If we're considering allowing more higher-tier glass I also propose that we allow ONE block on the floor to be Elevator 2461 (or require it to be combined with a plasticrete block to make a cleanroom elevator). Having an elevator sitting on the floor of the cleanroom just looks silly.

**Comment by Savallator** [comment]
That is a really great idea...

**Comment by Savallator** [comment]
Also, the point of the Issue was to allow for bigger windows.

**Comment by leagris** [comment]
> We can already use the reinforced glass but it's kinda ugly with bars etc.
> 
> If we're considering allowing more higher-tier glass I also propose that we allow ONE block on the floor to be Elevator 2461 (or require it to be combined with a plasticrete block to make a cleanroom elevator). Having an elevator sitting on the floor of the cleanroom just looks silly.

People use elevator in clean-room to circumvent the door missing a proper airlock to preserve the contaminant-free environment.
If rather than suggesting a better elevator…
you suggested a better system to enter and exit the clean-room without the door opening penalty and have all teleportation devices banned from the clean-room?

**Comment by Savallator** [comment]
I would really like to be able to construct a kind of "greyroom" as an airlock like in the real world, and then have that special elevator or stuff like travel anchors later in the game. Maybe at first just a special door would be enough. But i also have no problem with what bombar said, having the elevator nicely in the floor.It would at least make it look better.

**Comment by Prometheus0000** [comment]
> People use elevator in clean-room to circumvent the door missing a proper airlock to preserve the contaminant-free environment.
If rather than suggesting a better elevator…
you suggested a better system to enter and exit the clean-room without the door opening penalty and have all teleportation devices banned from the clean-room?

This would involve _way_ more coding though. Feel free to do it yourself though, as I'm not sure anyone else is really interested. Having an airlock is a good way, but I have no idea how to code that without making it required in a specific spot, which would defeat the purpose.

**Comment by Savallator** [comment]
one idea would just be having a seperate door block, that is allowed and won't loose cleanliness. But i am not sure if all that is worth it. My Ideas here were mainly aimed at making it look better, that is why i liked bombcars idea of having something like a "Plascrete covered elevator" allowed as part of the floor. That should be fairly easy.

**Comment by hohounk** [comment]
> Having an airlock is a good way, but I have no idea how to code that without making it required in a specific spot, which would defeat the purpose

Could be a dumb idea but how hard would it be to implement the airlock as just another cleanroom and when one enters a cleanroom just have a check if the door they just opened is between cleanrooms or cleanroom and the world outside?

**Comment by Savallator** [comment]
I already thought about that, and i hink that is a really great idea, but there is one problem: chunk-alignment. The GT-Multis don't like to span multiple chunks, because on load, when the chunk with the controller loads first, it can not recognize the structure. 
If that can be fixed for the cleanroom, it would be a very good idea. But it would still need a significant amount of coding, as there is no easy way to detect if there is a cleanroom behind that block. Right now, iirc the Cleanroom controller notifies the machines inside.

**Comment by hohounk** [comment]
I know nothing about how cleanrooms are implemented in code but I would imagine things triggered only* by people moving in and out of them shouldn't have too much problems with chunk borders as it is unlikely that the chunk right next to the player isn't loaded. I guess the only way it may happen is when someone logs in/out while standing on the pressure plate opening the door.

*) that presumes mobs aren't triggering the doors and some weirdos aren't using redstone to remotely open the cleanroom doors for no reason :)

**Comment by Houstonruss** [comment]
> People use elevator in clean-room to circumvent the door missing a proper airlock to preserve the contaminant-free environment.
> If rather than suggesting a better elevator…
> you suggested a better system to enter and exit the clean-room without the door opening penalty and have all teleportation devices banned from the clean-room?

Cleanroom maybe loses 5% if the door gets opened when entering or exiting IF the cleanroom is doing its check at the same time the door is open. People are too paranoid about losing the clean%. Early on just use a pressure place and check the % on the machine controller right above you before you craft your circuits 👍 

But in the config please allow ~ 25% glass percentage in cleanroom.

**Comment by Savallator** [comment]
> 
> But in the config please allow ~ 25% glass percentage in cleanroom.

This issue was about Having higher Tier glassed without any limit. They also have a cleaner look because they don't have the frame.

**Comment by Houstonruss** [comment]
> Allowing more reinforced glass would be a balancing issue, because you would need less plascrete.
Saying that it's a balance issue is fair, but also its a minor amount, and complaining that someone can save 20 plastic is weak compared to the benefit of having glass on a side of the multi. Nitpicking these minute balance changes isn't worth it, rule of fun should win.

**Comment by Prometheus0000** [comment]
I think the tungsten borosilicate is more expensive than the plascrete even? And not available when you first make a cleanroom. Another glass block using plascrete in it could also be added I guess. I'd still forbid the floor+ceiling+corners, and allow only up to a certain % of the structure.

**Comment by Savallator** [comment]
Yeah, the point was when you later redesign the Cleanroom, you can have more glass. I was thinking like Reinforced 5%, or Nickel Reinforced 10%, or Tungsten reinforced 20%, or Chome Reinforced 40% (or a mix of them)

**Comment by observeroftime01** [comment]
> If we're considering allowing more higher-tier glass I also propose that we allow ONE block on the floor to be Elevator 2461 (or require it to be combined with a plasticrete block to make a cleanroom elevator). Having an elevator sitting on the floor of the cleanroom just looks silly.

I solved this problem by simply placing another layer of plascrete blocks down on the floor, making it 2 layers thick. Sure, it's a decent waste of materials, but at least my elevator / travel anchor will be flush with the floor. Ultimately, I suppose you could also just build your cleanroom 1 layer higher, and then place down whatever block you desire for flooring on top of the plascrete. This is probably the cheaper option, but you forego the clean look of your clean room.

**Comment by leagris** [comment]
@observeroftime01 I ready you about the ugly elevator block. So what you are asking is a way to be free to enter and exit the clean-room without having to pay for re-cleaning.

This is an abuse of OpenBlock elevator to circumvent an intentional mechanic. I say this while I agree with you all that the Clean-Room as-is is a burden.

Please if you ask for an implementation change to circumvent current design, then just change current design to not have to pay cleaning when you enter or exit the clean-room. It is as much work to implement plascreate elevator or change the structure to allow an elevator, than it is to fix the structure to allow opening the door without penalty.

Cleanroom is another poor design from Gregteh; A device that offers no service, but is in the way of player, intentionally annoying, dedicated material that is a pain to craft and has no other use. Plascreate that need special tool to remove and cannot be re-used.

This thing is here intentionally designed to annoy the player. You asking to make it fancy with glass or convenient with teleporting are just fighting the wrong issue that this device is broken by design.

**Comment by mitchej123** [comment]
We had talked about, and agreed (in discord a while back), to add the openblock elevator as an eligible block on the bottom of the structure... but then I got lazy and never implemented it.

**Comment by Prometheus0000** [comment]
> Cleanroom is another poor design from Gregteh; A device that offers no service, but is in the way of player, intentionally annoying, dedicated material that is a pain to craft and has no other use. Plascreate that need special tool to remove and cannot be re-used.

I fixed the plascrete tool thing BTW. I agree that allowing people to completely circumvent the mechanic is kind of lame, but no one seems interested in making it more interesting. Maybe if the door had to be open 3s, instead of losing % immediately?

**Comment by observeroftime01** [comment]
@leagris as long as you can put travel anchors or elevators inside the cleanroom, you can make it look as though they are flush with the floor. I don't care one bit about the efficiency loss when using the door. I wouldn't care if using an elevator or teleporter does the same, because the effect is so minimal (1% efficiency loss or something when entering) it's not even noticeable. If that's not wanted, come up with a way to blacklist those items from being placed inside a cleanroom. Still wouldn't care, as my elevator would simply take me to the door instead.

**Comment by Prometheus0000** [comment]
> If that's not wanted, come up with a way to blacklist those items from being placed inside a cleanroom. Still wouldn't care, as my elevator would simply take me to the door instead.

```
# Defines blocks that are handled specially by elevators. Entries are in form <modId>:<blockName>:<action> or 
id:<blockId>:<action>. Possible actions: abort (elevator can't pass block), increment (counts for 
elevatorMaxBlockPassCount limit) and ignore
    S:specialBlockRules <
     >
```
in the openblocks config. Plascrete and the grates could be added. Though that might affect all GT blocks because of the meta thing, I dunno. But I think this would make many people upset.

I wrote it into the QB because people were already doing it, not because it's what you're supposed to do. It's like wallsharing.

**Comment by observeroftime01** [comment]
That would certainly solve elevators.
```
    S:specialBlockRules <
	gregtech:gt.blockcasings3:abort
	1757:11:abort
     >
```
Works and stops me from using the elevator to get into the cleanroom. My block ID might be different from everyone else's, so using the name of the block specifically seems like a good solution. This prevents you from going through all  gt.blockcasings3, not sure what ramifications this has. Seems pretty minor. 
I checked the EIO config for a similar blacklist for the travel anchor, but found none. 

Not that I would want that. With elevators being easy to blacklist, this will just further annoy players, create more inconsistencies (teleporter doesn't work, EIO teleporter works, portals, dislocators, etc.) and so forth, the pack has enough already. 

A better (and probably easier to implement) idea on how to deal with teleportation and efficiency loss would be for the MB Controller to check if a player has entered / left since the last cycle (by checking for player entity), and treating that event the same way an open door is treated.

**Comment by Savallator** [comment]
> A better (and probably easier to implement) idea on how to deal with teleportation and efficiency loss would be for the MB Controller to check if a player has entered / left since the last cycle (by checking for player entity), and treating that event the same way an open door is treated.

Or just... don't do it? I mean, if we just want to artificially annoy the player, why not make it so that the Cleanroom only work at night? Or only when the moon is full?

That was exaggerated of course, but you might get my point: A game mechanic should actually add something to the game, and not just randomly annoy the player. 
A real world cleanroom also does work even with people leaving and entering, there are even special airlocks for that.

Maybe just blacklist the elevator, and make a special one that blends in with the casings and is not blacklisted, but needs IV circuits to gate it to HV tier. Traven anchors would then work normally, but iirc they are later tier anyways.

**Comment by observeroftime01** [comment]
> Maybe just blacklist the elevator, and make a special one that blends in with the casings and is not blacklisted

Sounds great, any idea how to accomplish this?

**Comment by GTNH-Colen** [comment]
How has this conversation been twisted from allowing the elevator in a cleanroom to blacklisting it and adding a new elevator block?

**Comment by repo-alt** [comment]
What's the point, just allow the usual elevator. I may do that later this week. Also relax mandatory door requirement, there seems to be a consensus about that.

**Comment by observeroftime01** [comment]
There is a config option to allow a percentage of plascrete blocks to be set to some sort of glass in gregtech.cfg unless my memory betrays me, I haven't tried setting it to 100%. If that actually worked it would be one way to have a glass-only cleanroom in your SSP and private SMP servers. That of course is going to allow the player to skip the plascrete almost entirely.

**Comment by repo-alt** [comment]
![image](https://user-images.githubusercontent.com/23512002/132546452-4e7b1073-6bd7-4bae-a2d7-0be369d511fa.png)
![image](https://user-images.githubusercontent.com/23512002/132546545-ead3745e-d98e-41f3-a440-8122c047181f.png)

**Comment by boubou19** [comment]
i need this

**Comment by repo-alt** [comment]
`# Configuration file

cleanroom_allowed_blocks {
    reinforced_glass {
        S:Name=blockAlloyGlass
        I:Percentage=5
    }
    bw_reinforced_glass {
        S:Name=BW_GlasBlocks
        I:Percentage=80
    }
    elevator {
        I:Count=1
        S:Name=tile.openblocks.elevator
    }

    travel_anchor {
        I:Count=1
        S:Name=tile.blockTravelAnchor
    }
}
`

**Comment by Pnc6lx** [comment]
quantum glass in tectech is UV glass in bartwork, so can it also use in it? it is much more expensive than Os glass.

**Comment by Prometheus0000** [comment]
Looks like the bot failed to close it after being fixedindev? And then decided it was stale somehow?
