### ISSUE TITLE
Changes in the logic of the mechanisms

### ISSUE THREAD

**Issue by bamik69** [GTNewHorizons/GT-New-Horizons-Modpack#8535]
### Your GTNH Discord Username

bamik

### Your Pack Version

2.1.1.0

### Your Proposal

I propose to teach the mechanisms to perform several similar operations at a time, based on the input materials and output capabilities. For example, if 10 metal dust particles are put into the furnace, they are processed immediately with time and energy costs corresponding to the melting of this metal discretely.

### Your Goal

I assume that this will reduce the load on the server. I noticed that if a low-level recipe is executed in a high-level mechanism, when the estimated execution time is close to 1 tick, there is a significant load of this mechanism on the server with a large volume of production. Processing a large volume at once will increase the operation time, which will reduce the load.

### Your Vision

This will increase the server performance, which will improve the quality of the game.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by boubou19** [comment]
looks very similar to the parallel you get in the multiblocks when you progress.

**Comment by GTNH-Afx237v7** [comment]
Indeed. Mega vacuum freezer, mega blast furnace, multi-smelter, single blocks in processing arrays, the GT++ Multis...

**Comment by bamik69** [comment]
This is not a parallel. This does not bring any changes from the point of view of the gameplay. Purely unloading the server.

**Comment by bamik69** [comment]
If 10 identical processes require 1 minute and 100000EU each to be executed, then in the proposed version these 10 processes are combined into one that will be executed in 10 minutes and 1000000EU.

**Comment by Ydrec** [comment]
Multis cache last recipe so repeated recipes in them doesn't lag from being taken in.(recipemap lookup doesn't   happen) And lag from multis structure checking and actually "thinking" doesn't care if it processes 100 ingots at once or one

**Comment by bamik69** [comment]
This is a theory. OPIS shows otherwise.

**Comment by boubou19** [comment]
Most lag from multis endgame comes from speed: looks like the game is having a hard time to process the recipes in a few ticks. Opis only show high ticktime, not from where it comes in the code. That does mean that the multis can lag in multiple ways, you wont be able to say the difference. So saying "Opis shows otherwise" is wrong. If you want to say that, you need to combine opis observations with something like a warmroast report or a jvm profiling. IIRC, most of the lag comes from the "checkRecipe" method of the multis, but even if the recipe is cached, the multi must check recipe matching in buses/hatches. If last recipe is matched then the lookup in the recipe map is avoided, otherwise it's not. But it still lags from the recipe matching itself.
