### ISSUE TITLE
Make singularities more expensive

### ISSUE THREAD

**Issue by idkimanerd** [GTNewHorizons/GT-New-Horizons-Modpack#8539]
### Your GTNH Discord Username

Some Nerd With a Keyboard#4823

### Your Pack Version

2.1.1.3 Dev 2

### Your Proposal

Make singularity cost equal, and maybe more singularities? I know PO3 has something like what I'm thinking of, but maybe require an AE2 singularity as well? 

### Your Goal

Some singularities only take about 250 blocks, which isn't enough, because instead of requiring 40000 for a stargate, I am evil and want it to cost at least 1000000 per ore, depending on the difficulty of getting said ore. The ideal amount of singularities, in my opinion, would be to make the recipe for the eternal singularity look like the recipes for the tier 2 singularities instead of missing two. Another way to do this would be adding singularities to the avaritia ultimate. 

### Your Vision

It would make ore chunks even more valuable. 

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Alexdoru** [comment]
no

**Comment by boubou19** [comment]
> I am evil
This explains all i guess

**Comment by idkimanerd** [comment]
Ok maybe only add more of then

**Comment by boubou19** [comment]
More seriously, that just make the time gate for getting a stargate bigger, without any actual content to it. Players will just avoid the update if it hypothetically reach to a pack update, or they'll just spam some machine to compensate the increase of the time gate. The very endgame lacks of content, and the stargate meme recipes are here to keep you busy by dumping all your materials into it, making the ultimate challenge automation wise. Same for the octuple solar panel, that was not supposed to be doable. Time gates are a very poor mecanic, and we tend to replace them with actual content when we can, because afk-ing is not fun.

**Comment by idkimanerd** [comment]
Ok that’s fair, but why not add more singularlties for a total of 81 to make the recipes look more similar

**Comment by boubou19** [comment]
Did you actually made a stargate first before trying to mess with the current balance of the things?

**Comment by idkimanerd** [comment]
Meh GP

**Comment by Prometheus0000** [comment]
BTW, if you look in the code, it says the author used a randomizer to decide the amounts. I dunno about making it harder, but making it more balanced sounds fine. Like, 1 for Dr*, seriously?

**Comment by idkimanerd** [comment]
Also, I forgot PO3 has EMC
