### ISSUE TITLE
Uncomfortable GUI in NEI GT material 

### ISSUE THREAD

**Issue by KamenriderZO** [GTNewHorizons/GT-New-Horizons-Modpack#8561]
### Your GTNH Discord Username

GregTechDriver

### Your Pack Version

2.1.1.3 dev

### Your Proposal

The GUI is not completely shown when in full screen.
like the picture
![55$DB5_Q RW_MA@0`N%H~FK](https://user-images.githubusercontent.com/77818313/133943859-80fa80aa-0299-4076-b86b-258dd8185036.png)
 
![__ S0}8F)AK~I_PP1B`74`D](https://user-images.githubusercontent.com/77818313/133943862-5abcd11b-3141-44a8-b270-971390661ed3.png)

### Your Goal

optimize the GUI

### Your Vision

It's sure

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Pxx500** [comment]
If you want a hotfix then make your GUI smaller in settings.
This should help until someone adds pages

**Comment by GTNH-Colen** [comment]
Honestly I don't see the big issue here, maybe it should just display an error stating "gui too small" instead but I also don't think we should be supporting super low res monitors or absurd gui sizes.

I have a fairly shit HD monitor and play on normal GUI size, this isn't even close to being an issue on it.

**Comment by Pxx500** [comment]
> Honestly I don't see the big issue here, maybe it should just display an error stating "gui too small" instead but I also don't think we should be supporting super low res monitors or absurd gui sizes.
> 
> I have a fairly shit HD monitor and play on normal GUI size, this isn't even close to being an issue on it.

I thought the same but maybe he has poor eyesight or something like that idk
Normal GUI is the normal one lol

**Comment by Prometheus0000** [comment]
I think this was brought up in discord and @D-Cysteine said he was going to try to collapse the tools into each other with cycling through the tier and battery type, reducing 9 to 1 for those ones.

As for not fitting at all, maybe add a scroll bar if it's possible? I think lea gave up on the chisel one because of problems adding one though? So it may not be possible, or really hard to do. I could be remembering wrong though.

**Comment by KamenriderZO** [comment]
If ti has a sroll bar will be perfect!

**Comment by KamenriderZO** [comment]
> Honestly I don't see the big issue here, maybe it should just display an error stating "gui too small" instead but I also don't think we should be supporting super low res monitors or absurd gui sizes.
> 
> I have a fairly shit HD monitor and play on normal GUI size, this isn't even close to being an issue on it.

Yes,it made my eyes hurt when i switch it to "normal" .Items are too small ,i can't play the game relaxly

**Comment by D-Cysteine** [comment]
Yeah, I'm working on fixing this, but it seems like it's a bit tricky to fix so will probably take a while to get a good solution. Will probably either be a scrollbar or extra pages.

**Comment by leagris** [comment]
> > Honestly I don't see the big issue here, maybe it should just display an error stating "gui too small" instead but I also don't think we should be supporting super low res monitors or absurd gui sizes.
> > I have a fairly shit HD monitor and play on normal GUI size, this isn't even close to being an issue on it.
> 
> I thought the same but maybe he has poor eyesight or something like that idk
> Normal GUI is the normal one lol

I have poor eye-sight that a birth deffect from my retina, so it cannot be helped by optical correction.

I **do need things big enough** on screen, especially GUI.

Minecraft natively supports GUI Scale AUTO and all other GUI scales down to small.
If mods cannot layout their GUI in this GUI Scale AUTO and a default smallest Minecraft window size, then mod is broken and the modded GUI need fixing.

You know, I am not asking support for AUTO GUI Scale as a fantasy for my own comfort.
1. Other GUI scales are not an option to me.
2. It is not even a fantasy selfish request from an annoying lady with a very low eye sight disability, and who could consider moving to other free time occupation than coding, modding and sometimes playing modded with GTNH.
3. This is fixing a broken GUI layout.

Period!

I am pretty sure @D-Cysteine will find a way to fix this GUI layout issue, because He is a smart and capable modder, and his NEI add-on with Gregtech materials is absolutely clever and useful.

**Comment by D-Cysteine** [comment]
Sorry for the long wait, but the scrolling feature is finally done! Please give it a try and let me know if it works for you, or if it needs changes. Right now, the scrolling works purely off of the mouse wheel. Let me know if that's an issue for you.

Get the latest release here:
 * [NEI Custom Diagram](https://github.com/D-Cysteine/nei-custom-diagram/releases/download/v1.0.0/NEICustomDiagram-1.0.0.jar)
 * [New build of NEI, which is needed for the new features](https://github.com/D-Cysteine/nei-custom-diagram/releases/download/NEI-2.1.13/NotEnoughItems-1.7.10-2.1.13-GTNH-universal.jar)

**Comment by KamenriderZO** [comment]
> Sorry for the long wait, but the scrolling feature is finally done! Please give it a try and let me know if it works for you, or if it needs changes. Right now, the scrolling works purely off of the mouse wheel. Let me know if that's an issue for you.
> 
> Get the latest release here:
> 
> * [NEI Custom Diagram](https://github.com/D-Cysteine/nei-custom-diagram/releases/download/v1.0.0/NEICustomDiagram-1.0.0.jar)
> * [New build of NEI, which is needed for the new features](https://github.com/D-Cysteine/nei-custom-diagram/releases/download/NEI-2.1.13/NotEnoughItems-1.7.10-2.1.13-GTNH-universal.jar)

excellent!The scroll bar works fine.
![$0WVSK0ANF`HY`OS$ON16`3](https://user-images.githubusercontent.com/77818313/135601271-2453b8dd-bef6-4787-985f-056d579fa999.png)

![RJG(XD$ T6 VGYHDQG(LK)G](https://user-images.githubusercontent.com/77818313/135601294-bf25d37c-f720-48fe-bc7b-1d93505c2333.png)
