### ISSUE TITLE
IV cabled power centralization too heavily gated

### ISSUE THREAD

**Issue by Elisis** [GTNewHorizons/GT-New-Horizons-Modpack#8584]
### Your Pack Version

2.1.1.0

### Your Proposal

That the cost of the IV 1A dynamo hatch be reduced significantly.

### Your Goal

To allow for power centralization using IV cabling at mid-late EV, with e.g. the LSC.

### Your Vision

Currently there are many hoops to go through, including needing HSS-G coils, IV cutting machine, IV chem reactor, IV assembler, iridium, in order to run a functioning LSC that outputs IV power, which is desirable in EV.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Prometheus0000** [comment]
You can just use two EV hatches, can't you? Or a 4A EV one?

It also sounds like you want the IV hatch to be craftable in EV? But that's ridiculous, it's the IV hatch, so it should be crafted in IV.

**Comment by Elisis** [comment]
> You can just use two EV hatches, can't you? Or a 4A EV one?
This straight-up doesn't work because transforming up after the fact fucks with machines

> It also sounds like you want the IV hatch to be craftable in EV? But that's ridiculous, it's the IV hatch, so it should be crafted in IV.
Given mid-late EV crosses over with IV, no. I want it to be less of a chore to do it early IV.

**Comment by Prometheus0000** [comment]
> This straight-up doesn't work because transforming up after the fact fucks with machines

I have no idea what you mean by this? If it's transformed, it's IV power, so where's the problem?

> Given mid-late EV crosses over with IV, no.

???

> I want it to be less of a chore to do it early IV/mid EV.

The hatch/dynamo is one of the goals of the tier along with the assline, making it easier would invalidate all of that. Not to mention allowing making it in the _previous tier_. You make the EV hatches in the EV tier, not the IV hatches.

**Comment by observeroftime01** [comment]
> This straight-up doesn't work because transforming up after the fact fucks with machines

A 1x bat buffer after the transformer _usually_ helps this out, because it smoothes out any packets containing < 1A of IV and provides a buffer should your 4x EV dynamos not provide 4x full 1A EV packets every tick.

I do agree though, the IV hatch and dynamo belongs in the IV tier, not EV. You can certainly generate IV power in EV, but how you handle that is up to the player. Letting you easily craft IV hatches and dynamos in EV opens up a can of worms I'm not prepared to debate at this point.

**Comment by Prometheus0000** [comment]
> A 1x bat buffer after the transformer usually helps this out, because it smoothes out any packets containing < 1A of IV and provides a buffer should your 4x EV dynamos not provide 4x full 1A EV packets every tick.

I still don't understand, is there something wrong with transformers? Maybe someone should make a ticket? And state what the actual problem is, because it's still a mystery.

**Comment by observeroftime01** [comment]
There is nothing wrong with transformers. It's the cable loss that causes issues. If your 4 hatches output 512v, but because of cable loss let's say only 490v arrive at the transformer every tick. That means the transformer has ticks where it can not output a full 2048v packet. That is the chief issue I believe OP is referring to. And it can be solved by placing a bat buffer behind the transformer. 

There is no bug at play here or anything, just the way people set up their power delivery.

**Comment by Prometheus0000** [comment]
Then you just use a transformer immediately after exiting the LSC and use a battbuff further on near your machines to handle lows if you need it. I don't see any problem here, this is just how EU packets work? Nor is this problem specific to just IV tier power.
