### ISSUE TITLE
Easier Calcium

### ISSUE THREAD

**Issue by yukieiji** [GTNewHorizons/GT-New-Horizons-Modpack#8600]
### Your GTNH Discord Username

yukieiji

### Your Pack Version

2.1.1.1

### Your Proposal

Calcium is needed in large amounts after IV(Platinium Line, Oganeson, Raw Growth Medium), but we don't have the way to mass produce it, so I think we should add Calcium ore and Calcium Comb(after LuV or ZPM).

### Your Goal

The main ways to get calcium now are BoneMeal and Calcite, but Calcite is hard to get, and trying to get large amounts of BoneMeal requires large Mob traps and fields, which can cause lag.

### Your Vision

It reduces the time spent on calcium production and the lag it causes.
Easier calcium availability will help ensure long-term stable operation of the Platinum Line.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Elisis** [comment]
Quicklime from lava?

**Comment by King65868** [comment]
Also there is a bee that directly gives bone meal

**Comment by yukieiji** [comment]
>Quicklime from lava?

The probability of getting it is low and only small dusts are available, so parallelization is needed to get large amounts.

>Also there is a bee that directly gives bone meal

If you want to get a lot of these, you'll need a lot of Apiary

Both methods require parallelization, which increases the cause of lag.
Also, because it's not pure calcium that is available, the amount available is small compared to the amount of Calcium they produce

**Comment by Prometheus0000** [comment]
Calcite should probably be in more than the lazurite vein, and add a calcium ore at like UV or something.

**Comment by Ngar1** [comment]
- Bone meal by bee: industrial apiary, and world accelerator
- Calcium by tricalcium phospat (Apatite vein), Grossular, Betonite,...
- classical mobfarm (Skeleton)
- Fishtank -> bones and many more
- later: endless calcium by void miner

**Comment by Dream-Master** [comment]
Maybe we can add or change a oremix ?

**Comment by Pxx500** [comment]
From my experience there are enough sources of calcium to run the platline with little problems, I always thought calcium is a limited resource and I like it. I oppose adding pure calcium ore, it removes the challenge and would make getting calcium too easy, also calcium is too reactive to have a pure ore, just like sodium and potassium (why Ross?). I think that right now the amount of calcium is just right and does not need any changes. (One octadic spawner is enough to supply calcium for 1 full IV platline iirc)

**Comment by Prometheus0000** [comment]
So, 1024 for UEV?

**Comment by Pxx500** [comment]
> So, 1024 for UEV? That sounds like lag.

Why in the world would you want to do that?
You have VMs at UEV, spawners are very inefficient so their use at UEV is insane to say the least.
VMs create calcium as a byproduct that has pretty much only one use - platline. There is quite a lot of it and platline recycles 1/3 (not sure) of calcium needed making it easy to get. I would wait for more advanced players until they change their platlines to the newer version and wait for their feedback, instead of adding more calcium to the world the rate of recycling could be changed to something better (maybe at the expense of chlorine but this might be a very bad idea)

**Comment by Prometheus0000** [comment]
I don't think multiplying a single recipe is going to change the balance of the platline, there's no difference in how much materials are used.

**Comment by Pxx500** [comment]
> I don't think multiplying a single recipe is going to change the balance of the platline, there's no difference in how much materials are used.

They are used 9x faster now since platinum recipe got buffed from tiny piles to dusts, also I don't understand how changing the rate of recycling wouldn't change the balance? More recycling = more platinum/calcium

**Comment by Prometheus0000** [comment]
They take 4.5x as long, as well as using 4.5x the materials, don't they? So it's the same.

**Comment by Pxx500** [comment]
> They take 4.5x as long, as well as using 4.5x the materials, don't they? So it's the same.

9x more per recipe but yes, overall balance is the same

**Comment by Elisis** [comment]
> 9x more per recipe

It's 4.5x the recipe material cost

**Comment by Pxx500** [comment]
> > 9x more per recipe
> 
> It's 4.5x the recipe material cost

My bad but it's not relevant for this issue. Important is that ratio is the same

**Comment by observeroftime01** [comment]
The only vein that currently has calcite is the lapis / lazurite vein, and here it only spawns as a sporadic ore. Instead of adding calcium as a pure ore, maybe have a dedicated calcite vein, or at least a vein that spawns calcite as primary or secondary. Doing this avoids adding a pure ore, and increases calcium availability by increasing calcite availability. Adding Calcite as a primary or secondary to something would increase the VM's calcite output, and then the player can process all the calcite into calcium to their hearts content. Those without a VM can directly mine calcite veins and get a decent output.

Sure, the 5 calcite to 1 calcium ratio is quite bad, on the other hand you won't ever have to worry about oxygen again. Or, just add calcium as a pure ore, but as others have pointed out this is not an ideal solution.  

There is also the Tricalcium Phosphate vein, and here the ratio of Tricalcium Phosphateto Calcium is 5:3, another candidate that can be added. Why not have a dedicated Tricalcium Phosphate / Calcite vein, that would solve the Calcium shortage. There's other options to explore before adding calcium as a pure ore.

**Comment by Pxx500** [comment]
> The only vein that currently has calcite is the lapis / lazurite vein, and here it only spawns as a sporadic ore. Instead of adding calcium as a pure ore, maybe have a dedicated calcite vein, or at least a vein that spawns calcite as primary or secondary. Doing this avoids adding a pure ore, and increases calcium availability by increasing calcite availability. Adding Calcite as a primary or secondary to something would increase the VM's calcite output, and then the player can process all the calcite into calcium to their hearts content. Those without a VM can directly mine calcite veins and get a decent output.
> 
> Sure, the 5 calcite to 1 calcium ratio is quite bad, on the other hand you won't ever have to worry about oxygen again. Or, just add calcium as a pure ore, but as others have pointed out this is not an ideal solution.
> 
> There is also the Tricalcium Phosphate vein, and here the ratio of Tricalcium Phosphateto Calcium is 5:3, another candidate that can be added. Why not have a dedicated Tricalcium Phosphate / Calcite vein, that would solve the Calcium shortage. There's other options to explore before adding calcium as a pure ore.

I'm not sure whether you did it on purpose or not but you ignored the fact that lapis vein has 3 ores that contain calcium, the fact that calcite has so much attention suggests that people want more of it maybe not only for the calcium, iirc it's gating few things so I don't think the amount of calcite will be increased anytime soon.

There are many veins that contain calcium and just because you thing that 5 to 1 ratio is bad doesn't mean it really is, calcium is mined with many things and it is a quite abundant byproduct if you know where to look, lazurite vein has massive amounts of calcium, all you need to do is to electrolyze lapis(or was it lazurite?) and lapis lazuli, both give calcium (lapis lazuli is worst since it gives both lapis and lazurite)

Also apatite, tricalcium phosphate and pyrochlore all contain calcium so this vein is literally PACKED with calcium.

To me this issue looks like an attempt to make the game unnecessarily easier. Getting calcium is already easy and overworld probably has the most of it overall (those 2 veins are not the only ones, I consider most sources of calcium viable[ores only] since processing them gives you good materials and is cheap, most of them are also mined anyway so why void them instead of processesing?

**Comment by observeroftime01** [comment]
> To me this issue looks like an attempt to make the game unnecessarily easier.

Well yes, this is what is being discussed. The contentious point is "unnecessary". Your opinion is shaped by your subjective experience, and so is everyone else's. 



> I'm not sure whether you did it on purpose or not but you ignored the fact that lapis vein has 3 ores that contain calcium

Yes, that was on purpose, since I specifically talked about Calcite, not Calcium. I am using Calcite as an option to add more Calcium without directly adding pure Calcium as an ore, in response to the OP who raised an issue about Calcium shortage. I am neither for this nor am I against it. I _am_ against adding Calcium as a pure ore however. 



> Also apatite, tricalcium phosphate and pyrochlore all contain calcium so this vein is literally PACKED with calcium.

I did mention the TCP vein as another option to Calcite. 

Frankly, if more calcium is needed, I'd rather see it added through increasing or adjusting existing ore mixes, rather than adding a pure version of the ore. If a pure calcium source is added, I would prefer bees or crops over pure ores. Personally, I never have enough Calcium for the amount of PGM's I process, but I make it work out regardless by going to bed and letting the server run. I can't comment on how this works for those that play SSP.

**Comment by Pxx500** [comment]
> Frankly, if more calcium is needed, I'd rather see it added through increasing or adjusting existing ore mixes, rather than adding a pure version of the ore. If a pure calcium source is added, I would prefer bees or crops over pure ores. Personally, I never have enough Calcium for the amount of PGM's I process, but I make it work out regardless by going to bed and letting the server run. I can't comment on how this works for those that play SSP.

So maybe a add calcite ore to a vein but later in the game, T5-6 planets maybe? Sonds reasonable to me since calcite specifically is not needed at that stage and probably won't break balance. But I don't see why would anyone want to use it since apatite has more % calcium in every dust, also more calcium/ore mined

**Comment by yukieiji** [comment]
If pure calcium ore is added to GTNH(after UV(LuV or ZPM) or DD only), what content would be out of balance?

**Comment by Pxx500** [comment]
I don't think adding pure calcium ore is good because it shouldn't exist because of the reactivity of calcium. As I said existing ores are good enough to get calcium

**Comment by querns** [comment]
Ghostwood logs and saplings yield a disgusting amount of bone meal, and grow like crazy in an ender IO farm. 

It would be nice if there was a comparable bonsai for this tree, come to think of it.

**Comment by Sphyix** [comment]
I don't see the issue with calcium lategame
14 lazurite dust is 4 calcium dust and 1 lazurite ore is 12 crushed
That means, with tiny dusts and extra outputs from the sifter, you get 4 calcium dust for every lazurite ore
A single VM1 on a good planet for lazurite can totally make enough to feed a platline, probably even after the buff.

If there's a need for calcium at IV, that's another issue, but at LuV you can make the void miner, so I don't see why we need more calcium than what we can get now

**Comment by GlodBlock** [comment]
> If there's a need for calcium at IV, that's another issue, but at LuV you can make the void miner, so I don't see why we need more calcium than what we can get now

void miner is unlocked in ZPM because it needs MK2 fusion

**Comment by Sphyix** [comment]
> void miner is unlocked in ZPM because it needs MK2 fusion

Mh didn't remember that, sorry
Rest then still stands but at zpm+

**Comment by S4mpsa** [comment]
How has nobody commented about the White Stonelily?

The thing spits out more calcite than you know how to handle!

**Comment by boubou19** [comment]
16 lazuli dusts give 12 lazurite dust + a calcite dust. so lazulia fields + farming station + a world accelerator (optional) can easily sustain your needs if scaled up enough. Also white stonelily is a thing too iirc.

**Comment by querns** [comment]
I'm not really sure how you can get easier than this:

![image](https://user-images.githubusercontent.com/33518699/135624371-86b3271a-4898-4e00-9197-5aca7c1f108c.png)

![image](https://user-images.githubusercontent.com/33518699/135624385-8275e634-1690-425a-8d72-63f66ed0575d.png)

**Comment by YinScape** [comment]
Late bump, but 
Plants -> Plant Ball -> Plant Mass -> Bio Chaff -> Fermented Biomass in Distillation Tower -> Fertilizer -> Calcite -> Calcium?

**Comment by Pxx500** [comment]
@Dream-Master can this issue be closed? The response is pretty much "there is no problem with calcium" so this issue is pointless.
