### ISSUE TITLE
Change AE2 Memory Card Circuit Cost

### ISSUE THREAD

**Issue by Elisis** [GTNewHorizons/GT-New-Horizons-Modpack#8602]
### Your Pack Version

2.1.1.0

### Your Proposal

That the EV circuit in the crafting recipe for the AE2 memory card be changed to MV or HV.

### Your Goal

Currently the memory card is a pain to craft in large quantities, as would be needed for large-scale fluid movement. In comparison, using Fluid AE2 seems much easier.
![image](https://user-images.githubusercontent.com/28530295/134763889-5f99824b-eb78-42a7-8804-8ff58516b0e2.png)
![image](https://user-images.githubusercontent.com/28530295/134763891-b9fda4a3-eef7-4826-ae25-7677e1c6b076.png)

### Your Vision

By doing so, the effort required to get AE-based fluid movement setup would be lessened while also encouraging Fluid AE2 to a lesser degree.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by boubou19** [comment]
why do you need it in large quantities? 2-3 max shoumd be enough no?

**Comment by Dream-Master** [comment]
we could add a assembler recipe to automate it

**Comment by GTNH-Afx237v7** [comment]
With more and more people using fluid P2P and the amount of fluids to handle, it makes sense to have a dedicated card for each fluid. A while ago I suggested to allow a memory card to hold multiple entries (See #7568). 
An assembler recipe may make it slightly more attractive. The cost seemed high but once you start with fluid P2Ps you don’t actually have that many fluids, so I believe EV circuit is ok.

**Comment by observeroftime01** [comment]
I don't think I have ever used more than 1 of those cards at any given time. Can you explain why you would need a _large_ quantity of those cards? What does it have to do with Fluid AE?

The outputs of fluid export buses can be set using fluid cells, completely negating the use of a memory card. And you would have had to set the bus with a fluid cell beforehand anyways, otherwise there's nothing to copy. 

I really don't understand the issue at hand here. If you have fluid cells, you don't need a memory card. If you're setting multiple output buses to the same fluid, then that can be done with fluid cells as well, and slightly faster with a memory card if you don't have to insert acceleration cards as well.

Please elaborate on your reasoning as to why a large quantity of AE2 memory cards is needed, and what possible benefit it brings. Maybe I've been playing the game wrong the entire time.

**Comment by Alexdoru** [comment]
you are thinking of extra cells fluid AE, people here are talking of fluid P2P. 
With fluid P2P you set a frequency for each type of fluid and you rename the input p2p with the name of the fluid and then you attribute a memory card for each fluid, this way when you need to quckly get set a fluid p2p output to a certain fluid you just right click it with the appropriate memory card

**Comment by Elisis** [comment]
It's just inconvenient to run around your base with three memory cards needing to reset each one depending on what you're setting your new P2P up to be. A large number of memory cards just makes the whole business so much less awful.

**Comment by observeroftime01** [comment]
> you are thinking of extra cells fluid AE, people here are talking of fluid P2P.

Never mind me... Yep, I completely missed the point.
