### ISSUE TITLE
NEIDiagram Bugs + Suggestions

### ISSUE THREAD

**Issue by TimeConqueror** [GTNewHorizons/GT-New-Horizons-Modpack#8622]
### Your GTNH Discord Username

TimeConqueror#5294

### Your Pack Version

2.1.1.2

### Your Server

-

### Type of Server

Thermos

### Your Expectation

-

### The Reality

-

### Your Proposal

- [ ] 1) When I clicked "Show all diagrams" button I saw 672 pages, but when I tried to scroll to another page, instead of this the page tried to scroll down. Maybe add Shift functionality?
![image](https://user-images.githubusercontent.com/25156941/135609385-6718ad2b-e70e-4980-b48c-0cd6a33ab5ab.png)

- [ ] 2) Ctrl or any other key should speed up scrolling down, because regular scrolling is too slow. 
![image](https://user-images.githubusercontent.com/25156941/135609694-d105e185-955d-4edb-b562-076f5fccb08a.png)

- [x] 3) How would people with broken scrolling wheel do the scroll? Maybe if the mouse is over the slider, make it to not dissapear and add the ability to drag it with LMB.

- [ ] 4) Move GregTech Material Tools to the end of recipe list.
![image](https://user-images.githubusercontent.com/25156941/135610988-44d94e7e-8b8c-4ae7-8967-247506fbc600.png)
Because it will be used very very seldom, so if you really want to make the tools, it's acceptable to go to the last page.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Prometheus0000** [comment]
If you have a broken mouse wheel, you should get a new mouse.

**Comment by boubou19** [comment]
> If you have a broken mouse wheel, you should get a new mouse.

How helpful your comment is... Seriously this is a valid suggestion and not everyone can instantly afford a new mouse

**Comment by TimeConqueror** [comment]
4. Move GregTech Material Tools to the end of recipe list.
![image](https://user-images.githubusercontent.com/25156941/135610988-44d94e7e-8b8c-4ae7-8967-247506fbc600.png)
Because it will be used very very seldom, so if you really want to make the tools, it's acceptable to go to the last page.

**Comment by Prometheus0000** [comment]
> not everyone can instantly afford a new mouse

A mouse is like the cheapest part of a computer (along with the keyboard), if someone can't afford a new mouse I'm not sure how they got a computer in the first place.

**Comment by TimeConqueror** [comment]
You missed the word 'instantly' 🤦‍♂️

**Comment by leagris** [comment]
I fully approve all these considerations and suggestions regardless of some trollish invitation to replace a computer peripheral.

Having a mouse with an operational wheel is indeed handy, and I can appreciate some recommendation about proper maintenance or replacement of computer devices if these are defective. I even admire someone voluntary trying to help with advices. Thank you @Prometheus0000 for your attempt at helping.

Thank you so much @D-Cysteine for the scroll functionality. It is helpful and a really great contribution overall. I hope you will not take offence because someone point some rough corners.

**Comment by D-Cysteine** [comment]
Thanks for the suggestions and feedback! Sorry, I should have included some alternate scrolling control method in the first release.
 1. This is actually already supported! If the mouse is over the page indicator area ("Page 1/1"), then scrolling will always scroll pages. There is also a config option to disable scrolling pages while the mouse is over the main diagram area, so that players who need to scroll vertically a lot can ensure that the scrolling behavior is always consistent.
 2. This is actually already supported! There is a config option to adjust the scroll speed, as well as invert the controls if desired.
 3. I will look into some alternate means of control. Unfortunately I am not sure if NEI supports controls which use dragging / holding the mouse button down, but at the very least, I can add a keyboard control for scrolling.
 4. I was planning to add a way to reorder handlers to the NEI config, so that should take care of this.

For (1) and (2), sorry I should have linked this earlier, but I wrote some instructions about the controls and config options here:
https://github.com/D-Cysteine/nei-custom-diagram/wiki

**Comment by bombcar** [comment]
Not all computers/mice even have a scroll wheel (laptops especially).

**Comment by hohounk** [comment]
every single laptop released in past 10 years I've seen that doesn't have a physical scrollwheel has had the functionality emulated with other means, usually by two-finger swipe on trackpad. Some had a special key you held down to simulate the wheel.

**Comment by D-Cysteine** [comment]
To address (3), I've added improved mouse controls for scrolling with the latest release, here:
 * https://github.com/D-Cysteine/nei-custom-diagram/releases/tag/v1.1.0

See instructions on how to use the mouse controls here:
 * https://github.com/D-Cysteine/nei-custom-diagram/wiki/Controls

Will leave this open to track (4), which will be solved by adding a config to NEI.

**Comment by D-Cysteine** [comment]
For (4), https://github.com/GTNewHorizons/NotEnoughItems/pull/165 will add the NEI config. Also, I forgot to mention this earlier, but another option is to set the visibility of the unneeded diagrams to `SHOW_ON_SHIFT` or something. That way, they will hide themselves unless `<Shift>` is held when invoking NEI, so they'll only show up when you need them.

**Comment by D-Cysteine** [comment]
I think this should be done?
