### ISSUE TITLE
Frequent crashes with unknown cause

### ISSUE THREAD

**Issue by Prometheus0000** [GTNewHorizons/GT-New-Horizons-Modpack#8639]
### Your Pack Version

2.1.1.3 modified, stripped

### Your Server

SP

### Type of Server

Single Player

### Your Actions

Launch game.

### Crash Report

[crash-2021-10-03_09.20.44-server.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/7273391/crash-2021-10-03_09.20.44-server.txt)
The above is a generic seeming error. The fml-latest has more interesting info
[fml-client-latest.log](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/7273392/fml-client-latest.log)
o

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by boubou19** [comment]
Did you managed to get this on a full instance yet? because could be a weird interaction happening only in the stripped pack.

**Comment by Prometheus0000** [comment]
No, I'm only really testing with a stripped pack since it takes so long to open the full one, and I don't really need it for testing.

**Comment by D-Cysteine** [comment]
I've been seeing this occurring very rarely since the last update to NEI Custom Diagram. I really can't figure out how, but maybe the latest version is causing this somehow?

IIRC I've only been seeing it happening on the full 2.1.1.3 modpack (slightly modified), so I can confirm that it does happen there.

Stacktrace:
```
Exception caught during firing event cpw.mods.fml.common.gameevent.PlayerEvent$PlayerLoggedInEvent@451e73b9:

java.util.ConcurrentModificationException
	at gnu.trove.impl.hash.THashIterator.nextIndex(THashIterator.java:156) ~[THashIterator.class:3.0.3]
	at gnu.trove.impl.hash.THashIterator.hasNext(THashIterator.java:103) ~[THashIterator.class:3.0.3]
	at cofh.core.util.oredict.OreDictionaryArbiter.initialize(OreDictionaryArbiter.java:60) ~[OreDictionaryArbiter.class:?]
	at cofh.core.util.FMLEventHandler.handleIdMappingEvent(FMLEventHandler.java:47) ~[FMLEventHandler.class:?]
	at cofh.core.util.FMLEventHandler.onPlayerLogin(FMLEventHandler.java:38) ~[FMLEventHandler.class:?]
<trimmed>
```

I *think* this is where the exception is coming from:
 * https://github.com/CoFH/CoFHCore-1.12-Legacy/blob/3119c11b853a04a5ff8fa76b97199291f6a40699/src/main/java/cofh/core/util/oredict/OreDictionaryArbiter.java#L61

which makes sense that this would throw `ConcurrentModificationException` as `stackIDs` is being modified while it's being iterated over. But why would it only start breaking now? And why only sometimes? (I think that code is for the 1.12 version of the mod, so not sure if that particular file has been changed since 1.7)

Possibly related:
 * https://github.com/GTNewHorizons/GTplusplus/blob/master/src/Java/gtPlusPlus/preloader/asm/transformers/ClassTransformer_COFH_OreDictionaryArbiter.java#L150

While the ASM does not appear to modify the `initialize()` method directly, it does look like it is changing the type of `stackIDs` to `THashMap`, and that is the type that we are seeing in the exception message.

If anyone is getting this often enough to be able to tell if a change fixed it, please let me know as then we can test changing things to see if it gets fixed.

**Comment by Prometheus0000** [comment]
It seemed like maybe changing the config settings might have caused it. Or maybe not.

**Comment by idkimanerd** [comment]
This has been happening to me as well, but in my instance (2.1.1.4 dev), it only happens randomly on creating/loading a world. It is not world-based.

**Comment by Prometheus0000** [comment]
Cryotheum and pyrotheum are needed to run the cryogenic freezer and volcanus. I'm not sure about the rest. I guess having them enables thermal expansion compat?
