### ISSUE TITLE
Make CAL accept all sizes of input bus

### ISSUE THREAD

**Issue by Alexdoru** [GTNewHorizons/GT-New-Horizons-Modpack#8650]
### Your GTNH Discord Username

Alexdoru

### Your Pack Version

dev 2.1.1.3

### Your Proposal

Make CAL accept all sizes of input bus

### Your Goal

When you overclock your CAL a lot you need to input the items really fast in the ULV input bus because if you don't the multi will start and stop all the time. To do that you need to use methods that aren't performance friendly. Adding support for larger input bus would solve this issue.

### Your Vision

This would allow players to save performance and not spend time figuring out why their CAL is stoping and starting all the time

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Prometheus0000** [comment]
Didn't someone already do this?

**Comment by GTNH-Colen** [comment]
It was done but had issues as the CAL was not designed for this, so you ended up with you being able to put everything in 1 slot. It would need to be recoded quite significantly to mitigate this issue.

**Comment by boubou19** [comment]
it was done in https://github.com/GTNewHorizons/bartworks/commit/8cacc4d0a3e9607959282d452da7c9b189fc7e1d and as Colen said, it was reverted to avoid 2 slice CALs. A good way to mitigate imo this issue is to simply make the CAL detect one of the materials of the recipe in the bus, but in case of multiple recipes possible or the same recipe but with all the materials in all the hatches, how to decide which one of each material will be used?

**Comment by bombcar** [comment]
Make input hatches that work like the superchest? Can’t load more than one type in those
