### ISSUE TITLE
Disable wand charging station

### ISSUE THREAD

**Issue by Prometheus0000** [GTNewHorizons/GT-New-Horizons-Modpack#8661]
### Your Pack Version

2.1.1.3

### Your Proposal

Disable this cheaty device that allows charging wands with EU.

### Your Goal

Do not allow users to skip thaum with tech.

### Your Vision

Let users enjoy thaum more. Would feel less unfair to people who actually invest time in thaum.

Also see #8524, it doesn't even work right now anyway.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Prometheus0000** [comment]
Again, what is the problem? I don't see any? More options is _not_ always better, that's completely wrong. It's completely unbalanced, and should be removed.

**Comment by Retster** [comment]
> Again, what is the problem? I don't see any? More options is _not_ always better, that's completely wrong. It's completely unbalanced, and should be removed.

What is your argument about unbalancing this stuf its IV Tier replicatorand making from magic stuff!

**Comment by Prometheus0000** [comment]
It makes vis from EU, this should not be possible, the end.

**Comment by Prometheus0000** [comment]
It's the opposite, it's magic. This is not a purely tech pack or it wouldn't have magic mods. This conversation is going nowhere, let's just agree to disagree.

**Comment by Retster** [comment]
Btw, yesturday i talking with guys about similiar trouble with Tesla coils and one saying that it is working fine with IC2 transformers. I checked it and it's true, after this i check Inddustrial wand charger with IC2 EU source, and it also working fine(but wery slowly, because it use only 1 A, instead of all posible Amperage from GT sources before). So technicaly it's already working and i close old issue and this one also may be closed. 

If it posible to add toltip about working with IC2 energy source would be cool. To not make people confusing with it.

**Comment by Steelux8** [comment]
You said "let users enjoy thaum more", but what if thaum is straight up not enjoyable for them? The reason to have multiple ways to achieve a goal is for everyone to get there while having as much enjoyment as possible. It's also possible to turn TC items into EU, so I see no reason to allow EU to recharge wands with the right setup.

**Comment by greesyB** [comment]
>The tech way is way easier though isn't it? You don't need to make a node AFAIK.

The tech way is gated by late IV, thus most players that "enjoy thaum" will have made a node long before being able to make the wand charger. The wand charger doesn't even obsolete energized nodes as there are still plenty of reasons to have one (notably the advanced alchemical furnace and to recharge arcane assemblers).

Also, thaumic energistics is one of my favorite addons precisely because it crosses tech and magic. Removing things like this would lower the enjoyment of players like me, who I imagine there are quite a few of given that this is a tech-based pack.

As for where the vis comes from, the canonical answer given by the research note is UU-Matter, hence why it takes a replicator (mass fab? can't remember off-hand) as part of the recipe.
