### ISSUE TITLE
RFC: Infinity Chest + AE

### ISSUE THREAD

**Issue by repo-alt** [GTNewHorizons/GT-New-Horizons-Modpack#8671]
### Your Pack Version

2.1.1.3

### Your Proposal

Infinity chest when used with a storage bus may also interafct with pipes and conduits, which makes it effectively impossible to write a special AE handler for it (it would lag a lot). For the quantum chests we introduced a restriction so that a quantum chest with a storage bus stops working with any other automation.
I propose to apply the same restriction to the Infinity chest because it seems to be the most realistic use case anyway.

### Your Goal

E.g. https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/8491

### Your Vision

Why the fuck "goal" and "vision" are both required?

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by repo-alt** [comment]
If a chest works like a buffer before a multiblock consuming some insane quantitites of stuff, then indeed why to you need a storage bus on it? Maybe describe the situation in more detail?

**Comment by GTNH-Colen** [comment]
I didn't like the quantum/super chest restriction as that does have use cases but I get why it needs to happen. Realistically this case makes much more sense as the inf chest is basically just a huge AE cell for 99% of the 0.1% of players who even have one.

**Comment by GTNH-Afx237v7** [comment]
I’d suggest make it connect directly to AE and allow a Limited configuration, say 9 items like in an interface. That would decrease the need of participant A talking to participant B.

**Comment by boubou19** [comment]
i'd like to see this happen eventually, even tho now that we know that using both external piping and AE storage bus is laggy, avoiding it works too to reduce the lag

**Comment by Sphyix** [comment]
I can see this causing issues, at least in my situation.

Example is, I'm using ME Output Bus for 16 MBFs, only storage for the AE system for those MBFs is an infinity chest.
I'm then extracting from the chest with type filters, to separate what needs to be cooled down vs what needs to go into the main AE system.
Tested everything, this method causes the least amount of lag, mostly due to ME Output buses being too laggy with big AE systems, and normal output buses needing conveyors for the speed of the MBFs.
If the chest is restricted, this setup wouldn't be possible. 

Other thing that I'm not sure if would break, I separated my main AE system from the AE that receives massive amount of items. Mostly cause of the ME Output Buses again, and cause it was easier to deal with filtering stuff that needs to go into infinity chests.
Setup is like this:
![xdYpikP](https://user-images.githubusercontent.com/17811922/149149045-d369d478-c22d-4555-b387-fd993a4cd9ea.png)

Are both system going to be able to insert/extract from the infi chests after this limitation is implemented?
