### ISSUE TITLE
Compact Machines Mod?

### ISSUE THREAD

**Issue by Minepolz320** [GTNewHorizons/GT-New-Horizons-Modpack#8782]
### Your GTNH Discord Username

Minepolz320#9473

### Your Pack Version

2.1.1.0

### Mod Name

Compact Machines

### The Mod to Add

Compact factories i like this idea 
https://github.com/compactmods/compactmachines/tree/1.7.10

### Your Reason

It would be nice to have this in late game

### Preliminary Investigation

- Make recipes harder 
- Customize chunk loading 
- Disable drop items from the block after its destruction

### Final Checklist

- [X] This mod is released under an open source license. Yes, this is required now.
- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this mod, please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.
- [ ] I'm the official maintainer or original author of this mod for minecraft 1.7.10.

**Comment by RinWate** [comment]
Compact Machines? It can be very usuful for FPS optimization! Need to be added

**Comment by boubou19** [comment]
I'm not sure it's needed in this pack: it just hides your setups in a remote place while this pack is all about big automations. So quickly you'll get a lack of space in those boxes provided by this mod. In addition, we have utility dims that adds entire personal dims (reward in the IV quest tab). Also, Random Things has the spectre dim that does the same thing.

> Compact Machines? It can be very usuful for FPS optimization! Need to be added

If you want to hide the automations just to avoid FPS lag, then why not hide them somewhere? It has the same effect. Now if you have FPS issues while looking at something, the best to do is to try profiling your client to see what causes the drop, and make a ticket about it.

In addition of that, the mod hasn't been touched since several years, so we would need to provide support for it, as well as proper pack integrations (recipe changes, tiering of the items) That seems to be a non neglictible amount of work for something that is already covered by the pack at 100%.

So please explains what's very unique to this mod.

**Comment by Minepolz320** [comment]
I very like core idea how Sided I/O works, sometimes you need a bit extra space for single block machines.
btw if the support of the mod causes problems, then you can refuse it
