### ISSUE TITLE
Add multiplied recipes (mainly for LCR stuff)

### ISSUE THREAD

**Issue by Savallator** [GTNewHorizons/GT-New-Horizons-Modpack#8806]
### Your GTNH Discord Username

Boldar#1676

### Your Pack Version

2.1.1.4.QF2

### Your Proposal

Some recipes already got the multiply treatment (especially LCR recipes).
I want keep a list here which should still be added and get a x8 or x9 recipe with the correct circuit (taking 8x or 9x longer of course). I think even recipes not involving tiny piles could profit from this, since it makes machines run longer, decreses lag and makes recipes behave better when highly overclocked (reaching the 1-tick barrier will come later, so the need to build multiple machines will arise later or not at all, especially with the LCR)

- [x] Sulfur Trioxide + Water -> Sulfuric Acid
- [x] Sulfur Dioxide + Oxygen -> Sulfur Trioxide
- [x] Sulfur dust + Oxygen -> Sulfur Dioxode (also, this is broken: the numbers of the LCR and the single block recipes don't match)
- [x] Hydrogen Sulfide + Oxygen -> Sulfur Dioxide
- [x] Sulfur + Oxygen + Water -> Sulfuric Acid
- [x] Sulfuric Acid + Purified Sphalerite Ore+ Purified Galena Ore -> Indium Concentrate
- [x] Nitrogen Dioxide + Water -> Nitric Acid + Nitric Oxide
- [x] Nitric Oxide + Oxygen -> Nitrogen Dioxide
- [x] Ammonia + Oxygen -> Nitric Oxide
- [x] Hydrogen + Chlorine -> Hydrochloric Acid
- [x] Hydrogen + Fluorine -> Hydrofluoric Acid
Especially the first few would be nice, since that will be crafted in bulk.

Please feel free to comment other recipes for this, i can then edit them into this list.

### Your Goal

Have Recipes with higher input for stuff

### Your Vision

It would help reduce lag.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Elisis** [comment]
Mega LCR when :yobaface:

**Comment by Savallator** [comment]
It is not really needed because the LCR overclocks perfectly^^

**Comment by Elisis** [comment]
Still doesn't parallelize, nor multiply the recipe

**Comment by Savallator** [comment]
The multiplying would also mainly help with lag and overhead... Machines won't toggle on and off so rapidly with them

**Comment by Savallator** [comment]
Mega PA would be nice, supporting 256 machines :D

**Comment by Elisis** [comment]
Yeah, which is why I facetiously suggested gating it behind a mega LCR as a new solution to the said lag and overhead.

**Comment by Sphyix** [comment]
I don't think doubling the recipes to make a "parallel" version of it is a good idea.
The real fix here is to allow the LCR to do every recipe parallel instead of picking which recipe should get it.
This could easily be done by just upgrading the coil on it and doing like 4 parallels each voltage + coil tier

**Comment by boubou19** [comment]
LCR must not receive any buff at all, or it'll mess with the balance. Imo we should add a new multi that does parallel based on the coils, and availiable at early LuV.

**Comment by Sphyix** [comment]
I don't agree on the banale being messed up, but I agree on the new multi.
Balance can't be messed up if a machine can act like 4 machines, it just reduces the processing time of stuff.
If a time gate is considered a balancing thing, then yes it can mess with it lol

**Comment by Savallator** [comment]
> LCR must not receive any buff at all, or it'll mess with the balance. Imo we should add a new multi that does parallel based on the coils, and availiable at early LuV.

But adding Paralell is literally changing nothing in early tiers, as it is basically the same as perfect OC for the tiers where you don't hit 1-Tick limit anyways.
The throughput is exactly the same if you have 4x paralell or one perfect overclock. And if it does not get any energy reduction, but paralell per coil tier (+4 per coil for ecample), it would functionally only buff it for cases where it would hit the 1-tick barrier otherwise.

**Comment by Sphyix** [comment]
All the recipe times are divided by 4 if there's a 4 parallel, no matter the limit.
The absurd thing is that the time reduction is considered game breaking.
Boubs saying that reducing the time to process something destroys the difficulty means the only difficult thing in this game is waiting for stuff to process

**Comment by Savallator** [comment]
> All the recipe times are divided by 4 if there's a 4 parallel, no matter the limit.

But it still needs the power for it? So to do a MV recipe with 4 paralell, it needs HV. In its current state, it would just run 4x faster because of perfect OC.

**Comment by Savallator** [comment]
So basically, it is the same. And of course there are some edge cases like with recipes needing only half an amp, or 2EU/t recipes, but apart from that paralell is basically the same as perfect OC.

**Comment by boubou19** [comment]
> Boubs saying that reducing the time to process something destroys the difficulty means the only difficult thing in this game is waiting for stuff to process

Yeah sure let's give every recipe instant craft 🤦‍♂️ absurd recipe time is dumb, but so is the instant recipes. And LCRs are meant to run continuously in most setups. Stop trying to deform my words pls 😄

**Comment by Sphyix** [comment]
> Yeah sure let's give every recipe instant craft 🤦‍♂️ absurd recipe time is dumb, but so is the instant recipes. And LCRs are meant to run continuously in most setups. Stop trying to deform my words pls 😄

Literally everything needed for the recipe doesn't change, only thing is it gets done 4x faster for every tier.
Limit at lower tiers will still be power. You can't do IV recipes at 4x parallel since you need LuV power.
LuV power is achievable by using 2 hatches, but you need to feed LuV to it, so you need to produce enough power.
Plus you'd still need next tier coils to be able to do the 4x of your current tier. That's a big limit when starting the new tier, meaning it'd be possible to achieve the parallels only when close to the end of the tier.
I still see a lot of limits by doing a 4x parallels per tier, and I can't see at all how it would break the balance of the game
I can do the same by setting up 4 LCRs instead of 1, is that considered game breaking? Only thing that I can see is an added PTFE cost for the setup (not even that big since wall sharing is a thing), and that is balanced by the added coil cost.

**Comment by Savallator** [comment]
Also, the initial point of the Issue was just add multiplied recipes, and it should be a easy change. I don't see how anyone can be opposed to that?
Maybe we can split the LCR rework off into a seperate Issue?

**Comment by Sphyix** [comment]
> Also, the initial point of the Issue was just add multiplied recipes, and it should be a easy change. I don't see how anyone can be opposed to that? Maybe we can split the LCR rework off into a seperate Issue?

I don't see the point of having a list of recipes that can overclock only partially.
Like 8x Hydrochloric Acid can be good for some, it's totally useless for my base at UEV for example, since I'm 1 ticking it with a PA, doing 64/tick, 8/tick wouldn't be enough.
Just an example obviously, but the point of it is that it doesn't cover higher tier needs.

That's why it should scale for every tier, and not be something fixed only for some recipes.

**Comment by Savallator** [comment]
But it IS already fixed for some recipes. And "overclock partially"? What do you mean? Can we please be precise with the wording here? They will overclock like any other recipe as well, and you can at least do 8x the amount per tick without spamming 8 LCR's.
I do realise the need for a LCR with paralell, but apparently some people here don't, and i rather want a quick fix now than lengthy discussions guided by people that don't realize the material flow of endgame bases.

**Comment by boubou19** [comment]
As usual, we want to tweak something to somehow keep up with the unbalanced needs for some materials or for some player flex.
You know something is very wrong when you need several LCRs 1ticking stuff. The LCR had been made a central thing in this pack by having a perfect overclock, which is one of the rare machines to have one. It's already OP in comparison to the multiblock. The one tick with parallel is already doable with a PR of chemical reactors, but everyone doesn't want to go that route because in comparison to the LCRs, it uses too much power, but imo that's a faire price to pay.

From my limited knowledge in chemistry, iirc copper can be a catalyser for some reactions, but i highly doubt the other coils can have the same properties thematically wise. So this would just not make any sense. But let's suppose it does. I don't see why players should be allowed to have free parallels based on the coil they plug in at HV for exemple. Many GT++ are gated at IV/LuV to somewhat avoid too easy parallelism before in the game. Why not an upgraded version of the LCR? It doesn't really matter because before LuV, you don't need such high speed. The only reason i can come up with is that you guys are too lazy to rebuild the multis and just want to change one coil that is usually wall shared.

As to buffing some recipes, i don't see the point in that, because depending on how it's done, either you end up buffing a recipe, or you end up adding an additional recipe, which will take a lot of time because you need to list exactly what recipe needs to be buffed. But then players will start bitching about it because why only some recipes are buffed and not all?

**Comment by Savallator** [comment]
This issue was about making a list of the recipes... and i don't want them to be "buffed", just multiplied, like it was done with some others already, like the platinum Concentrate recipe for example that got an additional 9x recipe added with circuit 9.

**Comment by boubou19** [comment]
yeah in that case it seems more fair, but again, either you do that for any recipe or you don't do it. Arbitrary changes like that are just frustrating

**Comment by Sphyix** [comment]
> This issue was about making a list of the recipes... and i don't want them to be "buffed", just multiplied, like it was done with some others already, like the platinum Concentrate recipe for example that got an additional 9x recipe added with circuit 9. Also, the coil in the LCR is not "catalyst", but heating.

platinum concentrate got multiplied to remove the tiny dust, not to buff it

**Comment by Savallator** [comment]
> platinum concentrate got multiplied to remove the tiny dust, not to buff it

No.

**Comment by bombcar** [comment]
> yeah in that case it seems more fair, but again, either you do that for any recipe or you don't do it. Arbitrary changes like that are just frustrating

Perhaps this could be rolled into the coil tier - you up tier the coil, and the LCR multiplies the recipe as needed. Tier 9 coil, 9 times everything in all LCR recipes.

**Comment by Sphyix** [comment]
> > platinum concentrate got multiplied to remove the tiny dust, not to buff it
> 
> No.

![javaw_rMJ7L2WOgo](https://user-images.githubusercontent.com/17811922/149529550-93aa3851-a087-43ed-a110-78bd03a7649f.png)
![javaw_N9qOHvJ4Cj](https://user-images.githubusercontent.com/17811922/149529605-954ecd4a-cbe5-4ec3-b173-85ce0f986fa1.png)

yes...

**Comment by boubou19** [comment]
linear parallelism is good indeed, as it doesn't make it absurdly OP. Who ever needed more than 9 LCRs for the same recipe at one tick? I might be ok to give linear parallel. That reduces the needs for spamming, and everyone is happy.

Also, platline was indeed changed to remove the usage on tiny piles, like plenty of other recipes. If you find one, please tix it.

**Comment by Savallator** [comment]
> yes...

I just gave an example of an recipe that was multiplied without it being needed to remove tiny piles. There are other such recipes outside of Platline as well, that have atlernate recipes with larger batches.

**Comment by Savallator** [comment]
> linear parallelism is good indeed, as it doesn't make it absurdly O

Also, can you give me an example why more paralell would make it OP in any kind? It does only matter for endgame stuff anyways, for earlier tiers it is literally the same as having perfect OC. At least make it 4xCoil Tier or something.

**Comment by GTNHAfx237v7** [comment]
Sorry to necro this but can we also get a multiplied recipe for ammonia?
Current recipe is 1,000L nitrogen + 3,000L hydrogen -> 1,000L ammonia - 384 EU/t - 320 ticks.
