### ISSUE TITLE
General Server Performance Optimisation

### ISSUE THREAD

**Issue by ChrisLua** [GTNewHorizons/GT-New-Horizons-Modpack#8836]
### Your GTNH Discord Username

ChrisLua

### Your Pack Version

2.1.1.0

### Your Proposal

Hello,

We started a discussion on discord about generell server performance increase of selfhosted servers.
we ended up that there should be a wiki page about it, advices could be given about it.
bombcar pointed out there are several ways people increase their server performance, but they are not collected at one place.
Everybody seem to run through this topic himself.

### Your Goal

To get or create a list of all options/Mods/Commandblocks/etc... to increase server performance.

### Your Vision

server performance is allways good!
pretty self explaining

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by boubou19** [comment]
Good idea.

**Comment by bombcar** [comment]
I would update https://gtnh.miraheze.org/wiki/Low_End_PCs based on results from this yes.

**Comment by ChrisLua** [comment]
could be a good place to start. But not only low end PC/Servers tend to run into server lag at some point

**Comment by boubou19** [comment]
We should also have a page explaining how to trackdown lag sources imo, as it's complementary.

**Comment by ChrisLua** [comment]
> 
> 
> We should also have a page explaining how to trackdown lag sources imo, as it's complementary.

i added Opis-1.2.5_1.7.10 and MobiusCore-1.2.5_1.7.10 to client and server to find lag sources.
Pretty helpful

**Comment by yukieiji** [comment]
In order to maintain and optimize the performance of my server, I'm doing the following
・Use a server that is still being maintained and updated(like [Crucible](https://github.com/CrucibleMC/Crucible))
・Optimizing JVM options
・Using the RedHat JDK to use ShenandoahGC
・Constantly monitor the performance of the server by using [Plan Plugin](https://github.com/plan-player-analytics/Plan)
・Survey of lags using VisualVM

**Comment by boubou19** [comment]
We should breakdown this into several categories, as people ranting servers from normal MC server hosters may not be able to change their java version like they want for exemple.

**Comment by bombcar** [comment]
> could be a good place to start. But not only low end PC/Servers tend to run into server lag at some point

Yeah we’d get a new page at some point but the bot links this one so we use it for now. A whole lag finding page is good too

**Comment by ChrisLua** [comment]
So how is this going to continue?
For creating a new Page we need rights at the wiki? or do we just create one, and they decide if its going to stay?

@yukieiji could you give us a hint what your JVM optimizations are?

Currently we dont realy have a lot stuff pinned down here.
What i can add is a suggestion from bombcar to install Fastcraft which did increase serverperformance drastically. 
Was a easy thing to do, and helped a lot. i think a lot of people should notice

**Comment by bombcar** [comment]
The goal is for people to post things here, and then I can (or anyone really) collect the info into a new page.
In fact I made one: https://gtnh.miraheze.org/wiki/Server_Performance

**Comment by bombcar** [comment]
> ・Optimizing JVM options

Would you be willing to post your JVM options that you've finalized on?

**Comment by bombcar** [comment]
Of course - the idea is to collect various flags and discuss what they do (and if they help) similar to the discussions we had on the 🥔 page.

**Comment by yukieiji** [comment]
@ChrisLua @bombcar Here are the JVM options I'm using on my server(`-XX:+UseShenandoahGC` can only use RedHat JDK)
`-server -noverify -Xmx24G -Xms24G -XX:+UseShenandoahGC -XX:+UseTLAB -XX:+UseFastAccessorMethods -XX:+AggressiveOpts -XX:+UseBiasedLocking -XX:+UseStringDeduplication -XX:SurvivorRatio=8 -XX:MetaspaceSize=512M -XX:MaxMetaspaceSize=512M -XX:CompressedClassSpaceSize=512M -Xss1G -XX:-UseGCOverheadLimit -XX:+DisableExplicitGC -XX:ParallelGCThreads=12 -XX:ConcGCThreads=12 -Dfile.encoding=UTF-8`

**Comment by bombcar** [comment]
I’ve heard xx:+UseStringDeduplication isn’t that great

**Comment by boubou19** [comment]
@yukieiji if you could give the explainations of what does each flag, would be great for filling the wiki with descriptions, and eventually elaborate methods to tweak the params for one's server.

**Comment by yukieiji** [comment]
@boubou19 I believe it looked something like this. (I'm also referring to my own articles that I've written. https://yukieiji.hatenablog.com/entry/ar1124570)
- `-server` : Running the JVM with options for servers
- `-noverify` : To solve the problem of new Thermos servers (like Crucibe) not booting due to Apple Core.
- `-Xmx` : Maximum value of the JVM's main processing space (heap space (New space + Old space))
- `-Xms` : Minimum value of the JVM's main processing space (heap space (New space + Old space))
- `-XX:+UseShenandoahGC` : Use ShenandoahGC. This GC doesn't change the stopping time between 100GB and 2GB
- `-XX:+UseTLAB` : Use thread-local object allocation blocks.
- `-XX:+UseFastAccessorMethods` : Use optimized versions of Get<Primitive>Field.
- `-XX:+AggressiveOpts` : Turn on point performance compiler optimizations that are expected to be default in upcoming releases.
- `-XX:+UseBiasedLocking` : Enables a technique for improving the performance of uncontended synchronization.
- `-XX:+UseStringDeduplication` : Enable String deduplication.　Memory usage will be reduced but CPU usage will be increased.
- `-XX:SurvivorRatio` : Desired percentage of survivor space used after scavenge.
- `-XX:MetaspaceSize` : Set the space for MOD class and other information (Metaspace area).
- `-XX:MaxMetaspaceSize` : Set the maximum space for MOD class and other information (Metaspace area).
- `-XX:CompressedClassSpaceSize` : Size of the space to store the compressed data.
- `-Xss` :  Set the stack size
- `-XX:-UseGCOverheadLimit`  : Use a policy that limits the proportion of the VM's time that is spent in GC before an OutOfMemory error is thrown. 
- `-XX:+DisableExplicitGC` : Disable calls to System.gc()
- `-XX:ParallelGCThreads` : Sets the number of threads used during parallel phases of the garbage collectors.
- `-XX:ConcGCThreads` : Number of threads concurrent garbage collectors will use
- `-Dfile.encoding` : Set default character encoding

**Comment by Glease** [comment]
It sounds like your are using a set of VM flags for another minecraft version - Isn't UseShenandoahGC from Java 9+? We don't have this one on Java 8 iirc. Biased locking is on by default for Java 8 anyway.

**Comment by bombcar** [comment]
RedHat backported it for their JVM

**Comment by yukieiji** [comment]
Yes, I can use UseShenandoahGC with OpenJDK8.
![redhat](https://user-images.githubusercontent.com/40425798/142338890-e05823db-7710-4e29-8f5e-343f00d2d9b8.PNG)

**Comment by Glease** [comment]
Good to know then.

**Comment by Skiftcha** [comment]
ubuntu + ultramine core
if you see some thread is using 100% cpu i recommend to add
```
-DAsyncLogger.WaitStrategy=Block \
```
to ultramine_server_run_line.sh
this reduced 130% cpu usage to 30% for me

**Comment by TheElan** [comment]
> @ChrisLua @bombcar Here are the JVM options I'm using on my server(`-XX:+UseShenandoahGC` can only use RedHat JDK) `-server -noverify -Xmx24G -Xms24G -XX:+UseShenandoahGC -XX:+UseTLAB -XX:+UseFastAccessorMethods -XX:+AggressiveOpts -XX:+UseBiasedLocking -XX:+UseStringDeduplication -XX:SurvivorRatio=8 -XX:MetaspaceSize=512M -XX:MaxMetaspaceSize=512M -XX:CompressedClassSpaceSize=512M -Xss1G -XX:-UseGCOverheadLimit -XX:+DisableExplicitGC -XX:ParallelGCThreads=12 -XX:ConcGCThreads=12 -Dfile.encoding=UTF-8`

Could you please share machin spec?
Also would you mind roughly describe how did you measure and how much of improvements you notice when experimenting with flags?

**Comment by yukieiji** [comment]
@TheElan 
>How does machine spec looks like? If it's linux you can just run lsb_release -a; free -mt; lscpu

OS:Cent OS7
CPU:Core i7-5820K
Mem:32GB
GPU:Quadro P400

>How did you measure improvements?

I don't know if it's improved or not, because it hasn't changed much since the server starting, but even with a world size of over 14GB, the TPS is stable at 20, and there are multiple bases.

>How much improvement did you notice when experimenting with flag(s)\set of flags?

When I switched to ShenandoahGC, I think the game more stable and faster to start up.
