### ISSUE TITLE
Crops on void world are crashing zeta

### ISSUE THREAD

**Issue by maniifestantes** [GTNewHorizons/GT-New-Horizons-Modpack#8964]
### Your GTNH Discord Username

2.1.1.4QF2

### Your Pack Version

Maniifestantes

### Your Server

Zeta

### Your Actions

I'm growing some crops on the void dimension, but they are crashing zeta(4 times as I make this ticket)

### Crash Report

[crash-2021-11-30_14.33.26-server.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/7626128/crash-2021-11-30_14.33.26-server.txt)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by repo-alt** [comment]
```
            if (this.crop == null) {
                if (!this.upgraded || !this.attemptCrossing()) {
                    if (IC2.random.nextInt(100) != 0 || this.hasEx()) {
                        if (this.exStorage > 0 && IC2.random.nextInt(10) == 0) {
                            --this.exStorage;
                        }

                        return;
                    }

                    this.reset();
                    this.crop = IC2Crops.weed;
                    this.size = 1;
                }

                assert this.crop != null;
            }

            this.crop.tick(this);
```
No wonder.

**Comment by jack-french** [comment]
This issue is still present on at least 2.7.0.

I am encountering it when either growing or crossbreeding terra wart and nether wart with snow underneath, I am doing it in a void dimension. It was crashing very frequently before I broke all the crops I have 3 crash reports. This is on a private server with Java 21.

[crash-2025-02-10_02.33.54-server.txt](https://github.com/user-attachments/files/18736819/crash-2025-02-10_02.33.54-server.txt)
[crash-2025-02-10_10.15.46-server.txt](https://github.com/user-attachments/files/18736820/crash-2025-02-10_10.15.46-server.txt)
[crash-2025-02-10_10.38.02-server.txt](https://github.com/user-attachments/files/18736818/crash-2025-02-10_10.38.02-server.txt)
