### ISSUE TITLE
ceramic block change ID by picking from ground

### ISSUE THREAD

**Issue by Ngar1** [GTNewHorizons/GT-New-Horizons-Modpack#9061]
### Your GTNH Discord Username

Ngar

### Your Pack Version

2.1.1.0

### Your Server

myFTB

### Your Expectation

picking a block from ground or out of a barrel shall get into inventory 
![grafik](https://user-images.githubusercontent.com/7759876/145673101-f76cdb0b-55b5-47ab-b396-61c9b97e4c09.png)

### The Reality

ID of picked block change to the same, than in inventory!
![grafik](https://user-images.githubusercontent.com/7759876/145673158-a535438d-c1e3-4848-b5c5-3dbb20e2068e.png)

If no ceramic block is in inventory, the ID will not changed by pickup.

### Your Proposal

please fix

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by DarkAmbientNoise** [comment]
Figured I'd give an update and say this is still happening in 2.1.2.0, this also happens when you pull two different colors of any type it seems, from any inventory or from a Crafting Table (More below). These blocks seem to not be accepted by the questbook as well, despite having the same IDs even if you manually detect them.

Specifics:
Block IDs are changing, something isn't respecting the block's metadata value, but If you pick them up individually from an inventory it is possible to have two different colors in your inventory at once. However, you can't pick two different colors up from anything that automatically places a block in your inventory. You have to manually click it to a separate slot yourself. Shift click dragging across two colors into a Vanilla Chest, will cause them to go to the first color dragged over. Crafting two colors of Pigmented Glass without removing the first type from your inventory seems to also be an issue. But smelting two colors of Clay which automatically export to a chest, will give you both colors to manually collect.

The Colored Clay items, DO respect the metadata value and don't have these problems. But the Ceramic Blocks and Pigmented Glass blocks are cursed with this issue.

Proposal:
See if there is a difference in the way the game handles the final products (Ceramic Blocks and Pigmented Glass) and see if it differs from the Clay items.

GTNH : 2.1.2.0
Singleplayer world
Independently installed through MultiMC
Running Optifine (I understand it's not recommended, but I doubt that's the issue).

Would love to use these in a build, love the concept of "researching" flowers for pigments, but it's made unnecessarily tedious to use the results due to the bug. Hope a second opinion on the matter helps!

**Comment by DianeXD** [comment]
I think it has been fixed in the dev

**Comment by Ngar1** [comment]
This ist solved (2.1.2.4.-18) for every new molten or manual mined old block (somthing was added to block info).

Can be closed, thank you!

**Comment by Ngar1** [comment]
Is there a trick to change blocks to the new condition without to mine them? (I have 80 barrels with many stacks)

I tested the "Name Remover" but no change of this behave
