### ISSUE TITLE
Rework UUM mecanics

### ISSUE THREAD

**Issue by boubou19** [GTNewHorizons/GT-New-Horizons-Modpack#9062]
UUM production gets more and more ridiculous when you progress in the tiers. This should be changed for 2.1.3.0.
Maybe also rework the UUM replication costs a bit (hello Og).

**Comment by bombcar** [comment]
What is UUM used for and what could we provide as alternative methods? Perhaps utilizing underutilized MBs such as the aforementioned high-tier quantum computers?

**Comment by Elisis** [comment]
> What is UUM

Indium and Oganesson

**Comment by querns** [comment]
The main problem with UUM is mostly related to making it. It's probably easier with crops, since you can breed and spam UUM berries and whatnot, but non-crop pathways are pretty spammy. Since you can't put mass fabs in a PA, you're forced to spam single blocks all over the place. The higher tier you get, the more spam you have to do, since the overclocks are so ridiculously good. (E.g. a ZPM mass fab operates on 0.125A of ZPM, and a UV mass fab on 0.0625A UV.)

Making UUA with scrap is even spammier. Currently, the meta for making scrap is to use remote IO water sources outputting to AE2 matter condensers making paint balls. You feed these items into a PA of recyclers.

Furthermore, UUM is not optional. You need it to craft ZPM-tier wetware circuits.

Reworking the mechanics, to me, would take the form of creating an alternate pathway to production of UUM, one that doesn't involve PA recycler spam and single block massfab spam.

**Comment by Florexiz** [comment]
Crops are even worse for UUM production
Just add masfabs and replicators to PA maybe?
