### ISSUE TITLE
Unable to load old save

### ISSUE THREAD

**Issue by 4rchie20** [GTNewHorizons/GT-New-Horizons-Modpack#9123]
### Your GTNH Discord Username

4chie20

### Your Pack Version

2.1.2.0

### Your Server

SP

### Type of Server

Single Player

### Your Actions

Using MultiMC.
Trying to load my world on GTNH 2.1.2.0 and getting crash on startup. New world generating and starts with no problems.

### Crash Report

https://paste.ee/p/nA7hp

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by mitchej123** [comment]
This seems to be the root cause of the crash.  Not clear why it's throwing a CME.

```
04:26:35] [Client thread/INFO] [NEI Custom Diagram]: Generating diagram group [neicustomdiagram.diagramgroup.gregtech.materialtools]...
[04:26:35] [Client thread/ERROR] [FML]: Exception caught during firing event cpw.mods.fml.common.network.FMLNetworkEvent$ClientConnectedToServerEvent@d0c690c:
java.util.ConcurrentModificationException
	at java.util.ArrayList.forEach(ArrayList.java:1262) ~[?:1.8.0_312]
	at com.github.dcysteine.neicustomdiagram.generators.gregtech5.materialtools.RecipeHandler.initialize(RecipeHandler.java:158) ~[RecipeHandler.class:?]
	at com.github.dcysteine.neicustomdiagram.generators.gregtech5.materialtools.GregTechMaterialTools.generate(GregTechMaterialTools.java:72) ~[GregTechMaterialTools.class:?]
	at com.github.dcysteine.neicustomdiagram.main.Registry.generateDiagramGroups(Registry.java:223) ~[Registry.class:?]
	at com.github.dcysteine.neicustomdiagram.main.NeiCustomDiagram.onClientConnected(NeiCustomDiagram.java:94) ~[NeiCustomDiagram.class:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_1587_NeiCustomDiagram_onClientConnected_ClientConnectedToServerEvent.invoke(.dynamic) ~[?:?]

```

**Comment by 4rchie20** [comment]
> This seems to be the root cause of the crash. Not clear why it's throwing a CME.
> 
> ```
> 04:26:35] [Client thread/INFO] [NEI Custom Diagram]: Generating diagram group [neicustomdiagram.diagramgroup.gregtech.materialtools]...
> [04:26:35] [Client thread/ERROR] [FML]: Exception caught during firing event cpw.mods.fml.common.network.FMLNetworkEvent$ClientConnectedToServerEvent@d0c690c:
> java.util.ConcurrentModificationException
> 	at java.util.ArrayList.forEach(ArrayList.java:1262) ~[?:1.8.0_312]
> 	at com.github.dcysteine.neicustomdiagram.generators.gregtech5.materialtools.RecipeHandler.initialize(RecipeHandler.java:158) ~[RecipeHandler.class:?]
> 	at com.github.dcysteine.neicustomdiagram.generators.gregtech5.materialtools.GregTechMaterialTools.generate(GregTechMaterialTools.java:72) ~[GregTechMaterialTools.class:?]
> 	at com.github.dcysteine.neicustomdiagram.main.Registry.generateDiagramGroups(Registry.java:223) ~[Registry.class:?]
> 	at com.github.dcysteine.neicustomdiagram.main.NeiCustomDiagram.onClientConnected(NeiCustomDiagram.java:94) ~[NeiCustomDiagram.class:?]
> 	at cpw.mods.fml.common.eventhandler.ASMEventHandler_1587_NeiCustomDiagram_onClientConnected_ClientConnectedToServerEvent.invoke(.dynamic) ~[?:?]
> ```

Could this be for a reason neicustomdiagram was installed on version 2.1.1.0?
(folders "config" "mods" "resources" and "scripts" was cleared before updating)

p.s. everything works fine now with neicustomdiagram disabled, thanks!

**Comment by D-Cysteine** [comment]
You should also be able to just disable the `generate_diagrams_on_client_connect` option, and the crash should no longer occur. Though, this will cause the diagrams to no longer pick up Minetweaker scripts, so I think in particular the lens diagrams will be a bit inaccurate.

I think the root cause is that some mod is modifying crafting table recipes during client connect. I think I ruled out Minetweaker by checking the log output timing, so it's some other mod that's doing it, but no idea which one.

**Comment by D-Cysteine** [comment]
Okay, I hunted down the source of the concurrent modification:
 * https://github.com/GTNewHorizons/ForestryMC/blob/master/src/main/java/forestry/core/recipes/RecipeUtil.java#L209
 * https://github.com/GTNewHorizons/ForestryMC/commit/2af41cf68dcfa619249114e3212e86baca6c36be

Full stacktrace:
 * https://pastebin.com/qnkfKXdb

Not sure yet what should be done here, but wanted to record what I discovered.

**Comment by KiloJoel** [comment]
I think this may not be fully fixed. Or perhaps a related issue. Had someone get a CME even after updating to the latest NeiCustomDiagram from Jenkins

From their log: https://pastebin.com/g2r4rc0a

**Comment by bombcar** [comment]
Did you also grave the latest NEI? It may also be needed

**Comment by KiloJoel** [comment]
They just tried with latest nei and still getting crash

**Comment by D-Cysteine** [comment]
The fix for this was actually in Forestry configs rather than NEICustomDiagram, so updating mod versions would not fix it. Can you have them try with this added to their config?
 * https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/pull/9197/files

The important option there is `B:promote.worktable.recipes=false`. This shouldn't have any gameplay effect - it should only disable some worktable lag optimization, so the Forestry worktable may be a bit slower after turning it off. But it should also fix the CME.

Alternatively, it should also be possible to avoid the CME by turning off the `generate_diagrams_on_client_connect` option in NEICustomDiagram, though this will also make the diagrams no longer pick up recipe changes in Minetweaker scripts, so they may be a bit inaccurate with it off.
