### ISSUE TITLE
Wood Plank (plate) recipe

### ISSUE THREAD

**Issue by dandie** [GTNewHorizons/GT-New-Horizons-Modpack#9172]
### Your GTNH Discord Username

dandie#6829

### Your Pack Version

2.1.2.0

### Your Server

Delta

### Your Expectation

Crafting Wood Plank (plate) in compressor. Crafting should be 8 Wood Pulp for 1 Wood Plank

### The Reality

Crafting takes 1 Wood Pulp for 1 Wood Plank.

### Your Proposal

Consume 8 Wood Pulp.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [x] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Dream-Master** [comment]
I would suggest make it more than one . Maybe two or four

**Comment by dandie** [comment]
I made stack and still it was 1:1

**Comment by combusterf** [comment]
For added clarity: it was 8:1 before the update, and NEI still says 8:1, but the actual production only consumes 1 instead of 8.

**Comment by GlodBlock** [comment]
i found two same recipe. appaerently someone added it
![image](https://user-images.githubusercontent.com/60341015/146642825-4faab258-9cfa-499f-9d12-6be34d687a89.png)
![image](https://user-images.githubusercontent.com/60341015/146642833-456f8c1c-3cdd-4fb6-955b-26dbdb25db28.png)

**Comment by bombcar** [comment]
Suggestion is to make it 2/4/8 or similar. 

Is there a crafting table for this? If so it should be the worst at 8, compressor 4, and then add a MV or HV assembler recipe using 64 pulp and a cell of glue = 64 wood plank

**Comment by leagris** [comment]
@bombcar Medium Density Fiberboard wood panels don't use glue IRL. The first recipes at Steam, and Compressor use wood pulp only. Why would you add glue at HV?

- There is no leftover material output of chance or tiny dusts.
- Pulverizing a log block gives 6 wood pulp.
- Slicing a log block gives up to 6 wood planks if lubricated.
- Pulverizing a plank gives 1 wood pulp.
⇒ 1 wood pulp = 1 plank in material quantity.

Now lets compare the MDF Panel to the Sliced Wood Panels in term of material amount:
- 1 plank silces into 2 slabs, 1 slab slices into 2 wood panels
⇒ 1 wood plank = 4 wood panels

Wood panels are indeed thinner than MDF wood plank (the compressed one)
No the assembler is not able to compress. MDF is compressed, os need a compressor.

Don't make recipes more complicated than IRL or use incoherent amount of material. There is no reason to do so.

Remember the wood panel is oredicted `plankWood` for the reason that **it is** an actual wood plank, or at least it has the very same properties and usages as a wood plank, except it cannot be placed in world. Except it can be placed as a cover but standard wood planks can't.

GTNH perverted use of the GT wood plank to force its use in crafting pistons. I say perverted because it really changed the meaning of it and its initial design.

Come on, this is a low tech wooden plank made of compressed wood pulp that is mildly another wood plank variation and a decoration stuff!

KISS ⇒ Keep It Straight Simple

In a compressor, 1 wood pulp compresses into 1 MDF wood plank/panel.

The assembler does not need another entry in its already huge recipe map.
Players don't need tiered compressed wood pulp planks, really!

**Comment by Glease** [comment]
Let's not get overboard until there is a need.

---

Presumably this is also a problem from aDontCheckStackSizes changes (apparently also by *someone*😉). The 8 dust recipe is probably explicitly added first, then the 1 dust recipe is added from some automatic process later. In the old collision checking the later would be filtered out, but now with size checking turned on it is allowed to go through.

**Comment by bombcar** [comment]
True, it uses wax and resin, but I thought glue might be easier.

> Medium-density fibreboard (MDF) is an engineered wood product made by breaking down hardwood or softwood residuals into wood fibres, often in a defibrator, combining it with wax and a resin binder, and forming it into panels by applying high temperature and pressure.

**Comment by leagris** [comment]
@Glease does it restore the recipe with 1 wood pulp → 1 wood plate?

**Comment by Glease** [comment]
1 pulp 1 plate is the wrong recipe. It will be removed.

**Comment by bombcar** [comment]
64/64/144 comin' up
