### ISSUE TITLE
Gas Turbines should produce cleaner energy than Diesel Generators

### ISSUE THREAD

**Issue by Steelux8** [GTNewHorizons/GT-New-Horizons-Modpack#9255]
### Your GTNH Discord Username

Steelux#1934

### Your Pack Version

2.1.2.0

### Your Proposal

Gas Turbines should output less pollution than Diesel Generators of the same tier.

### Your Goal

This change would give incentive to early benzene setups when oil processing makes everything else obsolete because there's little reason not to do it.

### Your Vision

![image](https://user-images.githubusercontent.com/70096037/147237904-1a056ae9-ae92-47bc-bf7f-a44f4dd80bce.png)

This was just a simple Google search, but I believe that there's a big difference in pollution amounts when burning liquid fossil fuels from oil processing, and burning natural gas. In GTNH, just like in real life, oil processing is more popular because it's much easier to get large amounts of energy from it. Given that, and since we have pollution active once more, this mechanic should work in a way that slightly pushes players to cleaner, more challenging powergen options.

Currently, the LV singleblock generators of both kinds output 40 pollution, and the MV and HV options are a bit cleaner than the one before them. I believe the numbers should be changed so that diesel generators start at 80, and gas turbines at 20.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Pxx500** [comment]
You know benzene is not only not present in natural gas but also the opposite of clean burning right? Even worse than diesel. Diesel (according to wikipedia) is 86,1% carbon and benzene is 92,3%! For reference standard gasoline should be about 84,2% (for some reason I can't find any information about that so I assumed 100% octane).
Hydrocarbons have formula C(n)H(n+2) while benzene is aromatic and has formula C6H6. The longer the hydrocarbon the closer it is to benzene but it is never as bad as benzene (carbon to hydrogen wise).
Of course this doesn't work when we're talking about unsaturated hydrocarbons (same as benzene) and polyunsaturated hydrocarbons whitch are worse than benzene (but they are processed and are a very small part of the final fuel composition so they pretty much don't make any difference (at least in this case).
The most obvious solution is to make machines pollute depending on fuel type and not machine type since pollution depending on machine type is very inaccurate.
I also wonder why is benzene even burnt in the turbine, it's a fluid and a heavy one at that(carbon wise) and should be used in semi-fluid generator (not even combustion).
