### ISSUE TITLE
Adding Modular Powersuits to GTNH

### ISSUE THREAD

**Issue by Runakai1** [GTNewHorizons/GT-New-Horizons-Modpack#9343]
### Your GTNH Discord Username

Runakai ~ Docsyᵇᵒᵗ#7676

### Your Pack Version

2.1.1.0

### Mod Name

Modular Powersuits

### The Mod to Add

It adds a power suit that can be upgraded. It is a high functional armour with very unique features. Looks like the iron man armour

https://github.com/MachineMuse/MachineMusePowersuits/tree/1.7.10-Java

### Your Reason

It looks like it suits Gregtech. It was also used in packs that used Gregtech such as in FTB ultimate. 
We do have the gravisuit and much more. Yet, I believe the power suit mod will provide way more features than we already have. Every part of the armour including the weapon is upgradable. Using the railgun for the weapon for example doesn't just add another weapon type to it but you can also launch yourself up and use that in combination with your chest plate to fly. 

In this thread, https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/1196#issuecomment-334993275
this mod was already mentioned but since it wasn't solely about this mod pack I'm opening up another ticket.

### Preliminary Investigation

I didn't test it but given how powerful the armor could be it needs to be achievable harder armour

### Final Checklist

- [X] This mod is released under an open source license. Yes, this is required now.
- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this mod, please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.
- [ ] I'm the official maintainer or original author of this mod for minecraft 1.7.10.

**Comment by glowredman** [comment]
Note: Both Modular Powersuits and Numina (the required library mod) are licensed under the BSD license

**Comment by Runakai1** [comment]
In addition to my previous statements: I think it would be a great idea to implement modular powersuits to later game (after you get your quantum suit and gravi chestplate) because there seems to be no evolution of armor after reaching the gravi chest plate. Would be a nicer roundabout addition to the game in my opinion

**Comment by Nilau1998** [comment]
This mod really would add to the armor progression within GT:NH and add another way for the player to choose.
Especially the upgrade system makes this mod really appealing and probably a good addition to the pack. The player could unlock the basic armor somewhere along EV/IV and already unlock basic upgrades that make it rather equal to a nano suit. More upgrades then follow along the player's progression through the pack.
The most interesting actually comes into play here, because of the upgrade aspect of the armor there is no requirement for the player to make a whole new armor set just to unlock more features/progress in the armor tree. Instead the player could reach a stage where better batteries are viable and therefore add better batteries to their armor. Another example would be better power generation for the armor itself, like getting access to solar power from the helmet, or the kinetic energy generation from the legs.
The biggest workloud would be the balance of the armor and its upgrades because due to the low amount of components that are actually being added by the mod. I'd suggest adding more components to spread the whole upgrade progression over the pack.

**Comment by GTNH-Colen** [comment]
I just think we need to stop slapping mods on for the sake of it. I don't think this will add anything significant to the pack, we have tons of flexible good armour options as it stands.

**Comment by boubou19** [comment]
MMPS is fun and all, but i think it'll just be the tinker construct of the armors: you just make it then all the others armors become useless. Also, as Colen said, we should stop adding all the mods of 1.7 just for the sake if it. I vote against too.

**Comment by Runakai1** [comment]
> MMPS is fun and all, but i think it'll just be the tinker construct of the armors: you just make it then all the others armors become useless. Also, as Colen said, we should stop adding all the mods of 1.7 just for the sake if it. I vote against too.

I disagree. Once you build your Gravisuit, everything else pretty much becomes redundant right now. Modular Powersuits would allow Armor that can be built upon by adding new components that match new difficulties, as they may come or be developed. e.g harder bosses needed for further progression or such

**Comment by Dream-Master** [comment]
When Botania is done we can have a new toy like this. We are not focus on one project and adding every time new stuff instead of finish stuff.
