### ISSUE TITLE
MEBF Miscellaneous issues

### ISSUE THREAD

**Issue by GTNH-Colen** [GTNewHorizons/GT-New-Horizons-Modpack#9346]
### Your GTNH Discord Username

Colen UwU

### Your Pack Version

2.1.2.0

### Issue

This is somewhat of a follow up on #8346 as it appears those issues haven't been fully resolved and more have made their way up through the woodwork. Not by virtue of no attempts though as @D-Cysteine did make a valiant attempt at this previously.

I tried running a MEBF with 512A of UXV and got the following issues,

![image](https://user-images.githubusercontent.com/54497873/147905863-2d79dd6f-9875-42d4-8b81-88a39a163b0f.png)

It appears the timer is overflowing somehow, that and the items seem to bug out in the input hatch. I put 256 raw neutronium in and got the above timer and the following weirdness in the input bus,
<img width="348" alt="Screenshot 2022-01-03 at 07 00 39" src="https://user-images.githubusercontent.com/54497873/147905907-156a4cbc-04bf-432b-81eb-748199bb2fdc.png">

<img width="487" alt="Screenshot 2022-01-03 at 07 00 48" src="https://user-images.githubusercontent.com/54497873/147905921-70302bd3-f9d3-4a9f-a64e-4865959bdb1f.png">

However the items aren't even there, if you try take one out then it will vanish. There is clearly something odd going on here because of the fact that I relogged and those items were still there, so it's not as simple as a ghost item issue by the looks of it.

<img width="407" alt="Screenshot 2022-01-03 at 07 05 23" src="https://user-images.githubusercontent.com/54497873/147906185-1a7a825b-ad06-4447-a873-b49f1d19d372.png">

Lastly the MEBF cannot be rotated with structurelib despite being ported, is this a bug or intentional? 

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by D-Cysteine** [comment]
Just some quick notes:
 * The time `107374182 s` is `2147483647 / 20`. In other words, this is `Integer.MAX_VALUE` ticks, converted to seconds, which is rather suspicious. Might not be an overflow, though, as if it did overflow we'd expect to see something negative? `MAX` voltage is set to `Integer.MAX_VALUE`, so maybe it's using that number somehow?
 * The weird items disappearing yet persisting on world reload could maybe be due to those item stacks really existing, but having a stack size of `0`? Then they'd only vanish once they get validated, which would explain why they disappear when picked up. Not sure how often item stacks in input buses get validated, though I think it's supposed to be done pretty often, so that might be breaking somehow? If you open up those stacks in NEI Custom Diagram's debug ruler (enable the debug ruler then press `R` on the stack), I think it should show the true stack size, so we can confirm if it's `0` that way.
