### ISSUE TITLE
Switch out or remove the beacon from Magic Energy Absorbers (At least the lv and mv ones)

### ISSUE THREAD

**Issue by Alastors** [GTNewHorizons/GT-New-Horizons-Modpack#9387]
### Your GTNH Discord Username

Alastor's Game

### Your Pack Version

2.1.2.1

### Your Proposal

I propose we remove the beacon from at least the lv and mv tiered Magic Energy Absorbers, for a reference, I am the thaumcraft guy as you all know. And even I think the recipe is too damn expensive to waste time with, and it's much cheaper just to make an LEG for 4x the power and much more potential for later tiers at that. I tried but ended up giving up after making a total of 5, but I've already made 2 LEGs in two days for almost 2x the power output.
<img width="439" alt="Screen Shot 2022-01-06 at 6 00 01 PM" src="https://user-images.githubusercontent.com/78517796/148469282-3838d7e5-0357-4074-936c-480199458406.png">

<img width="457" alt="Screen Shot 2022-01-06 at 6 00 17 PM" src="https://user-images.githubusercontent.com/78517796/148469305-0442cae6-cb25-4ed6-80cb-077fe0bbc7c4.png">
<img width="969" alt="Screen Shot 2022-01-06 at 6 00 22 PM" src="https://user-images.githubusercontent.com/78517796/148469310-bb27e79b-046f-4e30-a2f9-8c96c004b0c4.png">

For context, this is the LV tiered Magic Energy Absorber, notice how it requires beacons itself, FOR A SINGLE AMP OF *LV* POWER! 

I think we can all agree that is an overkill.

<img width="435" alt="Screen Shot 2022-01-06 at 5 59 27 PM" src="https://user-images.githubusercontent.com/78517796/148469234-a2ae7c3f-29ab-4a54-ab3d-11a8cd3baef2.png">

I was discussing it with a few people on general, and Bombcar made a great suggestion, why not switch the beacon out for the similar light like we use on the nosecone for rockets? Overall I think switching it out might be a better longterm solution, because the beacon requirement is just way overkill.

<img width="696" alt="Screen Shot 2022-01-06 at 6 03 46 PM" src="https://user-images.githubusercontent.com/78517796/148469600-fd65a50c-17e5-4b46-a333-33e2632a58cd.png">

Aura also made the note that maybe just the diamond block used to make the beacon, instead of the beacon itself would be a worthy switch in itself.

### Your Goal

The MEA as it is, is being overshined by lots of other techs, and unlike others, it take a lot of preparations to use at all! Lots of specialized infrastructure just to use compared to every other power producing techs! Sure it is infinite power, but it is also infinite overkill. Even the LEG outshines the MEA in recipe by far, and somehow manages to not only be cheaper than the MEA itself, but also produces 4x the power!! 

So in terms of this, I think we need to give the MEA line a buff and rid it of the beacon, because if this wasn't the case, it would at least give some room to use it instead of the LEG in some cases, even when the LEG is a much better option overall!

### Your Vision

I think it would give some use to an older machine that has been buffed once already to tier it down once, but with the addition of many new power techs, has been left in the shadows even when compared to similar power techs, and as such I think that a boost to this line would be vital if it should continue to remain in the pack. 

As it currently is, many don't even recognize that the lower levels of the MEA lines exist, only knowing the Grandmaster variant from Ross, and might I ask to why that is? 

I'll tell you what I think is the root of the cause: the line is just too expensive to make, so no one does, and even when people use it, it is literally only because they find it on Ross because of the former!

### Final Checklist

- [X] I believe this feature would make the pack better.
- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.

**Comment by PolkageistHS** [comment]
If we wanted to keep it thaum-y, why not swap the beacon with an arcane lamp, hyperenergetic nitor, or maybe electric cloud?  Or maybe a block like the Automagy Vis Reader or the Deconstruction Table.

**Comment by Alastors** [comment]
> If we wanted to keep it thaum-y, why not swap the beacon with an arcane lamp, hyperenergetic nitor, or maybe electric cloud? Or maybe a block like the Automagy Vis Reader or the Deconstruction Table.

I personally like the arcane lamp part of that myself, it would fit a lot better than the beacon does! Though the deconstruction table would also make a lot of sense since it makes energy out of magic

**Comment by Aurastorm** [comment]
As a little more context to my contribution to this ticket, my thought is that the beacon is included in the recipe for 2 reasons. Firstly, it's a fitting thematic item that draws in energy from a source and expels it in a controlled manner. Secondly, it is infinite energy and, like solars, has a high upfront cost to balance said infinite energy.

However, a _beacon_ is a recipe that requires a good number of nether stars and 384 total essentia to create, around double the essentia required for both (non-beacon) infusions to make the machine.
Again. For 1 amp of 32 V.

Furthermore, one must also consider that the generator requires fuel (unlike solars), so its upfront cost should also include this. You only get 1 dragon egg per world without going through the tedious and expensive process of creating one yourself (something that is gated at EV), and while making an energized node isn't terribly expensive, it is still fairly expensive. Otherwise, it feeds off of essentia like the LEG does, which is not infinite (at least without yet more infra backing it).

If MEAs are to be seen as singleblock LEGs, then they absolutely should _not_ be even more expensive than its multiblock counterparts. It generates far less power for more stuff, after all.
If MEAs are to be seen as dragon egg power, then it should be considered EV, maybe HV as its starting voltage. Also consider the dragon egg production when determining its recipe.
If MEAs are to be seen as node power, then the process of finding/manufacturing a proper node alongside moving it to the proper location _also_ alongside the cost of the node stabilizer and transducer should be considered.

I suggested a diamond block bc it is part of the beacon recipe. I like the above ideas of things like an arcane lamp better, as they fit better.

**Comment by Aurastorm** [comment]
Another potential change could be to separate the functionality of the MEA into a less expensive singleblock essentia generator and a little more expensive node/dragon egg generator (my vote is to call the former simply an Essentia Generator and keep the latter as a MEA). I still heavily say that a beacon is far too expensive for a single amp of LV or MV, though.

**Comment by Alastors** [comment]
I'm reopening this, I still think we should change the recipe, of course I'm still for removing the egg from MEA usage to allow better balancing and/or switching the egg to another generator, but whatever
