### ISSUE TITLE
warp tumor still broken

### ISSUE THREAD

**Issue by ahmetsad** [GTNewHorizons/GT-New-Horizons-Modpack#9401]
### Your GTNH Discord Username

Ahmetsa#1741

### Your Pack Version

2.1.2.1

### Your Server

SP

### Your Expectation

warp tumor should only remove 50 warp and give it back after death

### The Reality

it can remove all warp and give only 50 warp back after death.

### Your Proposal

.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by bombcar** [comment]
To be precise, it apparently will remove up to 50 as it is supposed to, but then a relog or restart it will continue to “trigger” until all warp is gone

the 50 returns on death as it should.

**Comment by Alastors** [comment]
bruh everyone knows that 

> ### Your GTNH Discord Username
> Ahmetsa#1741
> 
> ### Your Pack Version
> 2.1.2.1
> 
> ### Your Server
> SP
> 
> ### Type of Server
> _No response_
> 
> ### Your Expectation
> warp tumor should only remove 50 warp and give it back after death
> 
> ### The Reality
> it can remove all warp and give only 50 warp back after death.
> 
> ### Your Proposal
> .
> 
> ### Final Checklist
> * [x]  I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
> * [x]  I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
> * [x]  I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

bruh, not cool, everyone knows it is broken and it's been broken for a long time, do you actually do thaumcraft? Cause if you did, you would know this bug is a key defining feature to why so many people still use it because the other warp removing items suck absolute ass, and are wayyyyy high tier compared to how you get them.

Plus the warp tumor is a PiTA to get in the first place. So like bruh

**Comment by ahmetsad** [comment]
> bruh, not cool, everyone knows it is broken and it's been broken for a long time, do you actually do thaumcraft? Cause if you did, you would know this bug is a key defining feature to why so many people still use it because the other warp removing items suck absolute ass, and are wayyyyy high tier compared to how you get warp. And like, there should be early game warp removal things.
> 
> Plus the warp tumor is a PiTA to get in the first place. So like bruh

bug means bug. If you want to have it change to permanent warp removing item open another ticket. it should work as a intended way not some buggy mess.

**Comment by Alastors** [comment]
> > bruh, not cool, everyone knows it is broken and it's been broken for a long time, do you actually do thaumcraft? Cause if you did, you would know this bug is a key defining feature to why so many people still use it because the other warp removing items suck absolute ass, and are wayyyyy high tier compared to how you get warp. And like, there should be early game warp removal things.
> > Plus the warp tumor is a PiTA to get in the first place. So like bruh
> 
> bug means bug. If you want to have it change to permanent warp removing item open another ticket. it should work as a intended way not some buggy mess.

nah I was a dick in my post, so I do apologize. But my stance on it is, even other warp removal methods that have been fixed since they were broken still haven't been unnerfed from unuseability for some reason, such as that one pedestal thing in thaumic exploration, that's been fixed for as long as the first warp tumor fix was, but it's still not usable, even though it just holds your warp.
<img width="421" alt="Screen Shot 2022-01-08 at 10 25 18 AM" src="https://user-images.githubusercontent.com/78517796/148651803-ec08577d-afc4-4ad3-9267-8e96c3438677.png">


Overall, the state of warp removal as is, is an absolute nightmare, so in my opinion, until that situation becomes better, it's always good to have some items like the warp tumor that are kind of jank, but also help bandaid the issue until it actually needs to be fixed at a later date.

I did overreact, like a lot. And I am sorry for that. I know that doesn't change anything, but still. 

I did make a post that if the tumor is fixed, the limit should be increase, because honestly 50 warp isn't anything. But anyway I do see your point.
