### ISSUE TITLE
Lifestock Rain can spread the taint Biome

### ISSUE THREAD

**Issue by Savallator** [GTNewHorizons/GT-New-Horizons-Modpack#9411]
### Your GTNH Discord Username

Boldar#1676

### Your Pack Version

2.1.2.1

### Your Proposal

Some guy decided to add taint animals to lifestock rain, and since they can spread the taint biome (the sheep by eating grass, maybe others too), failing to notice a tainted sheep that survived by falling on a building or tree will lead to taint biomes spreading all over your base, even when you are offline (and the base is left chunkloaded).

### Your Goal

I honestly don't care because i will just disable the stupid warp effects, but i just wanted to post it here in the faint hope that someone might find it stupid to destroy whole bases by warp effects. If it is intended please close.

### Your Vision

I don't care.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Cata-bre** [comment]
#8611 

It was intended, and should only happen you have >210 warp.

**Comment by bombcar** [comment]
@D-Cysteine give that we do NOT warn on the new warp effect (same message as before) would it be worth adding a new message if a sheep spawns? https://github.com/GTNewHorizons/WarpTheory/blob/377dfe2949d25d98944af5e1a6d9ade820aa3ea6/src/main/java/shukaro/warptheory/handlers/warpevents/WarpLivestockRain.java#L48 would be where it would go I think ...

**Comment by Savallator** [comment]
But is it really meant to spread the taint biome, or was is just meant as a different version of the normal rain? Because then the sheep could just be removed, as it is only them (and the taint creepers) that actively spread the biome. Maybe add tainted villagers instead for adding a "dark" flavor (it is "lifestock" rain, isn't it?)

**Comment by bombcar** [comment]
```
                        case 0:
                            victim = new EntityTaintCow(world);
                            // Tainted cows have too much health to die, so reduce their HP.
                            victim.setHealth(20.0f);
                            break;
                        case 1:
                            victim = new EntityTaintPig(world);
                            break;
                        case 2:
                            // There is a chance that some of these entities may survive, due to
                            // landing on an adjacent block.
                            // Tainted sheep are capable of spreading taint, so be careful!
                            victim = new EntityTaintSheep(world);
                            break;
                        default:
                            victim = new EntityTaintChicken(world);
                            break;
```

The code mentions it, and it is why it's explicit above 200+

**Comment by Cata-bre** [comment]
> But is it really meant to spread the taint biome, or was is just meant as a different version of the normal rain?

Both; it was intended as a worse version of livestock rain and gives another severe consequence for being at high (>200) warp.

**Comment by Cata-bre** [comment]
I think the assumption is most people wouldn't do that until they had a pure tear from being in IV or getting one from a lootbag. Your only other option is to cheese the warped tumor.

**Comment by Savallator** [comment]
Guess i just don't like warp mechanics basically being like "You are forced to go to a remote place, do all the research and use this single-use item, or your base will get permanently destroyed"... Especially since the crafting of the pure tear needs an ichor ingot, which is not only bugged with regards to unlocking it but also really annoying to make.

**Comment by Cata-bre** [comment]
I'm in agreement with you. Changing the WarpTheory max warp from 80 to 200 was a good change, but Dream doesn't want to remove WarpTheory. Thaumcraft and WarpTheory aren't balanced when you add in all the big TC addons.

**Comment by Savallator** [comment]
Yeah, that is the root of the problem. With only Vanilla TC it is easier to balance, but as with every addon there is not only more warp, but the crafting of the pure tear gets harder as well... i thinkwe need a whole new vision for warp, because if warp only servers as an incentive to do as less thaum as possible it is not a good mechanic.

**Comment by bombcar** [comment]
Warp mitigation does need some work and the first tower is fixing the mitigators that don’t work correctly (or replacing them with equivalents) - soul brazier. 

Perhaps what we need as a stop gap is a base protection multi that stops any base altering effects in a given chunk radius thereby converting EU into antiwarp

**Comment by leagris** [comment]
This discussion about warp is going wild the same way as pollution:

1. Inflate values because early players don't want new players to have it so easy as they did.
2. Later realise the inflated values have inflated effects and new players complains of the damage/cost grind.
3. Realise counter-balance devices that exists in the base mod and add-ons are tuned for normal default value; turns out broken or inappropriately balanced when dealing with the inflated value.
4. Propose adding new devices because the other legacy add-on devices cannot be easily fixed/modified for the inflated values.
5. Several versions later, new players gave-up on accessing this part of the game or cheated-in custom disable config or creative because the inflated values causes them immoderate damages and impairment.
6. A Discord channel is created to discuss the value balance, but everyone has diverging view on what proper values should be.
7. After a while, someone wise enough points out that the base value was geared for the standard setting and before changing these values there is need for a clear mission statement, and the untold 'screw new players and secure veteran position as the only masters' turns out to not get great acceptance, and turns out to damage the game-play.
8. Finally someone points that all of this grown on the unsatisfied demand for new content and inflating numbers is not going to replace the missing content but piss-off everyone.

**Comment by Cata-bre** [comment]
> 1. Inflate values because early players don't want new players to have it so easy as they did.

Correct me if I'm wrong, but Dream set the values. This isn't about an "elite" group of veteran players. The recent warp change was made to introduce a better risk-reward curve and improve Thaumcraft gameplay. I don't know any players who are happy with Thaum's warp/benefit ratio or the "do minimal to no research until Pure Tear" gameplay. D-Cysteine's recent change to Warp Theory allows for far greater flexibility in warp effects. The WT max value can be changed from 200 to 666 for example.

**Comment by bombcar** [comment]
Warp values come from the original mods, and Dream just approves changes and says "don't remove warp entirely"

It's important and helpful for players to *actually* play the game as intended and report issues. A separate issue now is that *you cannot get to pure tear* without a ton of warp, is that intended, and should other mitigations be provided beyond what is available.

It sounds to me that @Savallator would (for example) much prefer that instead of any base-damaging warp, it would just straight up kill him (because player death is easy to handle) for example.

**Comment by Savallator** [comment]
Yes, and warp can be turned off altogether in the config, or i can make it so that tainted blocks look like cake and just ignore them... But the starting point of this was the current state of the pack, and there the Value is not actually changed to 666. But the main point is that even in the already existing warp rebalance issue the devs kind of failed to develop of a vision of what warp should be, at least if you say 

> I don't know any players who are happy with Thaum's warp/benefit ratio or the "do minimal to no research until Pure Tear" gameplay.

Because that is exactly what was decided upon. Either your statement is only reflecting part of the players, this is a serious case of conflicting interests between devs and playerbase, or the devs just don't care. Because in the other issue it was kind of a "consentaneous" decision that the process of "make second base, eat pure tear" was how it should be, and my critique that it will drive people away from doing thaum at all was not really reflected upon.

And also:
> Correct me if I'm wrong, but Dream set the values. This isn't about an "elite" group of veteran players
So wrong on the "group" part, but kind of true anyways.

**Comment by Savallator** [comment]
> It sounds to me that @Savallator would (for example) much prefer that instead of any base-damaging warp, it would just straight up kill him (because player death is easy to handle) for example.

I mean, the Wither warp effect does inded kind of kill you, giving you wither 3 effect for like a minute or so, but yeah, killing people can be recovered from, whereas converting the whole base into tainted land because a sheep landed on your roof and you missed it and logged of, and then the next day you log back in into purple madness. Decay and swamp are almost as bad, because they will permanently destroy your abse and make it very hard to fix. You will find random pockets of sand underground months later still. When i said that at least it should only affect visible blocks so it can be fixed more easily, that was neglected...

**Comment by Cata-bre** [comment]
> Warp values come from the original mods, and Dream just approves changes and says "don't remove warp entirely"

I should have been more specific; Dream changed the warp values of Blood Magic research and Witchery research in the Thaumonomicon. IIRC, the Blood Magic tab accounts for jusst under 1/3 of the Thaumonomicon's warp.

**Comment by D-Cysteine** [comment]
I'm not opposed to removing the tainted sheep from the effect. The idea of it was just to be a darker twist on the regular livestock rain, which would only occur at higher warp levels (this is why there is no special message - the different effect is meant to surprise the player). As I see it, here are the reasons to keep the sheep:
 * Parity with regular effect: regular one gives cow, pig, sheep, and twisted one gives tainted cow, tainted pig, tainted sheep
 * Only occurs at 210+ warp, in which case player is already getting withers and other base-destroying effects

And reasons to get rid of it:
 * The danger of this particular effect is not mentioned in the Thaumcraft warp warnings - player may not know about it
 * Spreading taint is potentially more dangerous / destructive than spawning a wither, or the other base-destroying effects

If we do want to get rid of it, it's a very easy change to remove it - just let me know and I can do it.

---

Since the discussion also wandered into balance, I wanted to mention the [Thaumic Sauna Stove](https://ftbwiki.org/Thaumic_Sauna_Stove), which just needs water and a healing axe to use and should prevent all warp effects while you are in the area of effect. Good to add to an AFK area. Another potential idea to make high warp less painful would be  to buff the impure tear: make its recipe cheaper and / or make it remove more permanent warp (maybe a percentage of the permanent warp that the player has?).

**Comment by bombcar** [comment]
Can you spawn one message per warpysheep? I kinda like the idea of the risk but get the base problems.

The AFK stove should be MUCH more prominent in the quest lines, I think it is *reasonable* to expect players diving into warp to have to setup some warp mitigation in some way.

**Comment by D-Cysteine** [comment]
Sure, we could definitely add a message instead. I kind of like just removing it altogether though, for purposes of flavor (sending a message ruins the surprise twist a little), and also because in the majority of cases, all of the tainted sheep will die from the fall - they generally will only survive if the player happened to be near trees or a cliff, or in water.

And yeah, the sauna is really nice, and would be good to tell the player about it in the quest book. Maybe we should just add a warp mitigation quest, similar to the warp warnings one, that lists off all of the various things that mitigate it, along with how hard they are to unlock? I think we already have something similar with the impure tear and pure tear quests, but maybe we can expand on those?

**Comment by draknyte1** [comment]
Just make the animals die after 5s.

**Comment by bombcar** [comment]
> Just make the animals die after 5s.

you mean detonate, and this is a good idea in general for ALL of these

**Comment by Alastors** [comment]
> Although 200 is like less than 1/3 of the total warp you get from all researches... I basically went straight for the pure tear and have >500 and can't even make the pure tear yet.

LMFAO I'VE BEEN SAYIN THIS FOREVER NOW

**Comment by Alastors** [comment]
> Can you spawn one message per warpysheep? I kinda like the idea of the risk but get the base problems.
> 
> The AFK stove should be MUCH more prominent in the quest lines, I think it is _reasonable_ to expect players diving into warp to have to setup some warp mitigation in some way.

bruhhhhh I've been saying this forever, it's why Im so passionate about the warp tumor

**Comment by D-Cysteine** [comment]
I came up with a different idea: make a custom tainted sheep that can't spread taint, and use that instead. Done in:
 * https://github.com/GTNewHorizons/WarpTheory/pull/22

**Comment by bombcar** [comment]
Hmm it doesn’t yell “I’m baaaaaaaaaaaad to the bone”

**Comment by Alastors** [comment]
> I came up with a different idea: make a custom tainted sheep that can't spread taint, and use that instead. Done in:
> 
> * [Add "safe" tainted sheep for tainted livestock rain warp effect WarpTheory#22](https://github.com/GTNewHorizons/WarpTheory/pull/22)

nooooooo

**Comment by Alastors** [comment]
booooo

**Comment by Alastors** [comment]
taint isnt even that hard to fightttt, give us a reason to fight itttt

**Comment by Alastors** [comment]
if you get above 210 warp you deserve itttt

**Comment by bombcar** [comment]
alastor=true config option when

**Comment by D-Cysteine** [comment]
Well, removing the tainted sheep danger from this warp effect doesn't preclude adding more warp effects at high warp levels which more explicitly spread taint. The main thing I didn't like about this one was that the quest book / thaumonomicon don't warn the player about the tainted sheep spreading taint, since it's a hidden effect of the livestock rain that occurs at higher warp levels. Having separate warp effects that explicitly spread taint would avoid this issue, as we could mention them specifically in the quest.

**Comment by Savallator** [comment]
Nice!
If we want an explicit warp spreading effect, if could also do it better than using the sheep. The speeh are also bad because they are kind of stealthy - they survive the fall, hide somewhere on a roof and eat grass hours later. There are also tain tendrils that could maybe be spawned with warp, that would require immediate attention, but could at least be easily cleaned up.
