### ISSUE TITLE
Add Freezer recipe for Americium Plasma

### ISSUE THREAD

**Issue by Savallator** [GTNewHorizons/GT-New-Horizons-Modpack#9521]
### Your GTNH Discord Username

Boldar#1676

### Your Pack Version

2.1.2.1

### Your Proposal

I would really like to have a freezer recipe for americium plasma.

### Your Goal

It feels bad to have the need for a dummy turbine just running to cool down the plasma (I don't care for that small amount of energy). Other Plasmas have freezer recipes already, just not the one where it is actually usefull.

### Your Vision

Would be nice.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Savallator** [comment]
Okay, apparently NEI trolled me and the recipe is there, just not showing when looking of uses of either the plasma fluid or the plasma cell...

**Comment by bombcar** [comment]
Reopening because NEI shouldn't be hiding it if it's important.

**Comment by GTNH-Colen** [comment]
This may be a consequence of trying to look up a recipe with the IC2 cell rather than the GT cell as that is useless for finding much information.

**Comment by Savallator** [comment]
I am not sure how i missed the recipe, as now i see it clearly in NEI... maybe i was just blind. Now i clearly see it^^

**Comment by Savallator** [comment]
Okay, weird. I clearly saw the recipe, but now i can't find it again: (Uses for a plasma cell, as well as uses for the plasma fluid not showing a freezer, also recipes for the molten neither)

**Comment by GTNHAfx237v7** [comment]
Still relevant imho

**Comment by Dream-Master** [comment]
@GTNHAfx237v7 recipe suggestion ? Tier , Duration?
@Savallator 
@GTNH-Colen 
@bombcar

**Comment by ScriptedPiky** [comment]
Maybe LuV tier input at 1 second?

**Comment by GTNHAfx237v7** [comment]
Haven’t played for a while, and don’t have the Time currently. So I can give a principal answer to this only. 
Voltage should at least be the tier that is needed to make americium plasma.
Duration and thus total EU cost should be balanced around the usual turbine this is run through so that freezing 1,000L of plasma is faster than using a turbine but not by a huge factor so that players still have a reasonable choice between using a turbine and the freezer.

**Comment by Sphyix** [comment]
If a player wants to freeze it, it's already wasting the energy that the plasma could make.
There's no point in making it a long recipe or requiring even more power, since time and power are already required to make the plasma.

That said,
Helium plasma (T1): MV, 1 tick? (<1sec)
Nitrogen plasma (T2): MV, 1.4sec
Oxygen plasma (T3): MV, 1.6sec
Radon plasma (T3): MV, 22sec

Not sure what's the idea behind those numbers, I'd say they all need to be aligned to something since they just have random values atm.
After aligning the already existing ones, just do the same for Americium plasma

**Comment by Dream-Master** [comment]
@Sphyix mv freezer recipe ?

**Comment by Sphyix** [comment]
> @Sphyix mv freezer recipe ?

yes, those recipes are the freezer recipes

**Comment by Dream-Master** [comment]
last one we can do hv i guess and a bit shorter ?

**Comment by Sphyix** [comment]
sure
