### ISSUE TITLE
NEI drag & drop into pattern terminal

### ISSUE THREAD

**Issue by Florexiz** [GTNewHorizons/GT-New-Horizons-Modpack#9547]
### Your GTNH Discord Username

FalseColor#8524

### Your Pack Version

2.1.2.2 and 2.1.2.1

### Your Server

Zeta

### Your Expectation

Drag and drop item with custom stack size in pattern terminal from NEI

### The Reality

It ignores stack size (always set item to 1) and drop item afterwards (previously it remained in hand)
https://discord.com/channels/181078474394566657/522098956491030558/928706387280797820

### Your Proposal

Fix

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by repo-alt** [comment]
There is a client side config turning this on: config/NotEnoughEnergistics.cfg B:useStackSizeFromNEI=true

**Comment by slprime** [comment]
@repo-alt why by default this config is off?

This commit change mod loading direction? Because before it neiaddons override handleDragNDrop and it work like in gif.
https://github.com/GTNewHorizons/NotEnoughEnergistics/commit/a7919fe70760028ff7264b2e973de011dfc23747

![ae-terminal](https://user-images.githubusercontent.com/31038811/150676865-4e4abdb3-8e03-4656-baaa-e040be439247.gif)

Maybe need remove handleDragNDrop  code from this mod and leave only in neiaddons?

**Comment by repo-alt** [comment]
I have no idea, I also find it weird that 2 mods (outside of AE2) handle it's drag & drop

**Comment by Florexiz** [comment]
> There is a client side config turning this on: config/NotEnoughEnergistics.cfg B:useStackSizeFromNEI=true

This setting does nothing for me

**Comment by miozune** [comment]
Fixed by https://github.com/GTNewHorizons/NotEnoughEnergistics/commit/d077b0a1f6f94ba3c358bec66045103c4ccf335f, https://github.com/GTNewHorizons/NotEnoughEnergistics/commit/8e481998399acb859174cd35f1815eaa52a3632a, https://github.com/GTNewHorizons/NotEnoughEnergistics/commit/37f181a8bd8e94234d8b80895ce472f172ab16be and https://github.com/GTNewHorizons/NotEnoughEnergistics/commit/a983a36e2f6aeff95f68b871db04b42c0b3a224b
