### ISSUE TITLE
[regression] Someone broke Glow Textures From Gregtech

### ISSUE THREAD

**Issue by leagris** [GTNewHorizons/GT-New-Horizons-Modpack#9574]
### Your Pack Version

2.1.2.2

### Your Server

irrelevant

### Your Expectation

https://discord.com/channels/181078474394566657/224191655375273985/935293648977940501

![](https://cdn.discordapp.com/attachments/224191655375273985/935293648092926013/2022-01-24_23.02.00.png)

### The Reality

Glow textures are no longer rendered

### Your Proposal

Repair regression

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by boubou19** [comment]
turns out it's just the basic miner not supporting the glow textures
![2022-01-25_00 32 37](https://user-images.githubusercontent.com/12850933/150882708-ba063094-4c7f-47e4-b968-9ecf8a42c872.png)
![2022-01-25_00 32 44](https://user-images.githubusercontent.com/12850933/150882711-e5b4d0db-158c-408f-a1ec-16557565e410.png)
:
