### ISSUE TITLE
Backbone cable recipe changes need more work

### ISSUE THREAD

**Issue by riking** [GTNewHorizons/GT-New-Horizons-Modpack#9625]
### Your GTNH Discord Username

Riking#6902

### Your Pack Version

2.1.2.2QF2

### Your Proposal

Dense covered cables shouldn't cost more than a smart cable because it's more FPS friendly

Backbone cables, however, should have a mildly difficult recipe because they're new and fancy but you still need them in high quantity

Exact proposals to go in replies

### Your Goal

Fix incentive regressions caused by #9523

### Your Vision

FPS/TPS incentives should be aligned with in game resource incentives.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by riking** [comment]
The PR changed dense smart cables from:
Lapis + Redstone
To
Energetic / Vibrant + HV / EV circuit

Overall this is a good change imo, just except for the reversal of covered cables

How about you can add smartness at any tier from the covered versions?

**Comment by bombcar** [comment]
imo "dumb" or "dense" cable + computer monitor cover or something like that = smart cable (adjust accordingly)

**Comment by bombcar** [comment]
And then you could "disassembler" the smart cable and get the monitor back (maybe)

**Comment by leagris** [comment]
These recipes are stupidly complex. What the point?

**Comment by Dream-Master** [comment]
The recipe where stupid easy and complete unrealistic logic wise. I add this new recipes not as a final recipe just as a first suggestion. We can change the circuit per 4/8/16 cables if they to expensive

**Comment by Dream-Master** [comment]
Still no new suggestions?

**Comment by KiloJoel** [comment]
I think the covered (dumb) cables definitely shouldn't be made from the smart cables. Since you're basically doing a recipe to remove functionality as it currently is. The other way round would make a lot more sense.

**Comment by KiloJoel** [comment]
Also, the new prices seem kind of unnecessary. They are just cables after all. Is distance what should increase costs? I would argue the costs of ME interfaces and other devices which use the cables' channels are the relevant part.

**Comment by Dream-Master** [comment]
So wich recipes need a change? I guess ae2 need more changes. The recipes are very old and can make now much better since we have a 9 slot assembler. And I mean not more expensive.

**Comment by joshaup1999** [comment]
Don’t see the need to make the ME cables have a new recipe honestly, they’re fine as is. Changing them for the sake of changing them isn’t something that should really be done…

**Comment by Dream-Master** [comment]
The recipe before make no sense. And we added the backbone cable so a change were needed.

**Comment by querns** [comment]
I recommend partially reverting the recipe changes for the covered ME cables. Making the dumb cables cost more than the smart cables, when the dumb cables are less laggy, is not a great idea.

# PROPOSAL:

## 8 Channel Cables
* ME Covered Cable: unchanged
* ME Smart Cable: 4 ME glass cables, 1 MV circuit, 144mB conductive iron, assembler (Current recipe has 1 ME glass cable = 4 smart cables.)

## 32 channel cables
* ME Dense Covered Cable: 4 ME covered cables in a 2x2, normal crafting
* ME Dense Covered Cable, alternate recipe: 4 ME covered cables, 1 stainless steel frame box, assembler
* 4 ME Dense Smart Cables: 4 ME Dense Covered Cables, 1 HV circuit, 144mB energetic alloy, assembler

## 128 channel cables
* ME Covered Backbone Cable: 4 Dense Covered Cables, 1 Titanium Frame Box, assembler
* 4 ME Smart Backbone Cables: 4 Covered Backbone Cables, 1 EV circuit, 144mB vibrant alloy, assembler

This provides some extra spend for the backbone cables in the form of 2 titanium per backbone, and making the laggier smart cables cost more to discourage their use.

**Comment by Dream-Master** [comment]
Will re check recipes

**Comment by chochem** [comment]
just 4 ME covered cables in a 2x2 for a dense cable looks way too easy to me, that doesn't fit the pack.

**Comment by fluffle** [comment]
I just ran into this change after upgrading from 2.1.2.0->2.1.2.3qf and wanted to note that IMO the changes as they stand in that pack version strongly incentivise the use of Ender IO dense ME conduits over AE dense cables, since they are considerably cheaper per block for transporting 32 channels.

**Comment by fluffle** [comment]
On reflection, I'm not completely averse to the changes. Since I'm here, this is my $0.02 on the discussion so far, should anyone care:

1.  I would drop all the circuits for smart cable 1 tier but leave the numbers unchanged.
    - **Rationale:** bootstrapping AE to a reasonable state of automation can happen considerably before a player has access to nanoprocessors, and they will most likely need at least half a stack of dense cables to manage channel aggregation for this bootstrapping. A CPU assembly per 4 smart cables is really quite costly at this stage in the pack, for something that is *essential* to making an ME network of any reasonable size.
2.  I agree with @querns that making covered cables depend on smart cables is backwards and distorts incentives.
    - I habitually use smart cables everywhere (single player) but if covered cables let me avoid the circuit cost of smart cables I would consider moving to only have them at intersections or in core parts of the network.
3.   I liked the addition of conductive iron / energetic alloy to the smart cable recipes -- it was the thing that finally made me set up an assembler with a fluid extractor next to it. GT is a very fluid heavy pack and IMO changing fluids in assembler recipes provides a nice automation alternative to using circuits.
4.  Using metal frame boxes in the dense / backbone recipes doesn't fit "cable", in my mind, and paying 8 stainless + 2 titanium *per block* to aggregate 128 channels seems pricey. Maybe that's the intent, but 
    - How about using molten glass and molten reinforced glass in the dense / backbone covered recipes? I considered suggesting higher glass tiers (EV for dense, IV for backbone) but they don't appear to have liquid variants and using glass blocks didn't make sense thematically.
    - How about adding polyphenylene sulfide foils to the covered cable recipe, and changing the conduit recipe to use conduit binder instead of these foils? The same could be done with dense cables. Drawing an equivalence between sulfide foils and conduit binder seems like a nice way of keeping the recipes approximately equivalent.
 
This would result in something like:

- 1 glass cable + 1 polyphenylene foil + 144mb rubber/106mb styrene-butadiene/72mb silicone -> 1 covered cable
- 1 glass cable + 1 conduit binder + 1 silicon plate + 144mb polyethylene -> 1 me conduit
- 4 covered cable + 1 LV circuit + 144mb conductive iron -> 4 smart cables
- 4 covered cable + 4 foil + 576mb glass -> 1 dense covered cable
- 4 me conduit + 4 conduit binder + 576mb glass + 1 titanium plate -> 1 dense me conduit
- 4 dense cable + 1 MV circuit + 144mb energetic alloy -> 4 dense smart cables
- 16 covered cable + 16 foil + 576mb reinforced glass -> 1 backbone covered cable
- 4 backbone cable + 1 HV circuit + 144mb vibrant alloy ->  4 smart backbone cables

Making backbone covered cable independent of dense covered cable provides more flexibility to add costs to one without affecting the other too much. If the above is still too cheap one additional idea I had was to have sheets of PVC (1) / PTFE (4) / Polybenzimidazole (16) in the covered cable recipe tiers -- using plastic rather than metals tiering.
