### ISSUE TITLE
Dislocation focus and transduction amplifier combo allow enlarging aura node infinitely

### ISSUE THREAD

**Issue by maniifestantes** [GTNewHorizons/GT-New-Horizons-Modpack#9669]
### Your GTNH Discord Username

maniifestantes

### Your Pack Version

2.1.2.2QF2 

### Your Server

zeta

### Your Expectation

The transduction amplifier is a neat machine from thaumic horizons that increases 10% of your node, but if you place 2 or 3, it'll shoot lightning around it(4 will turn your node into another thing, losing your node).

### The Reality

Here's the thing. With the dislocation focus, you can dislocate an energised node. And for some reason, if you do it and remove the amplifiers, and put the node back(it needs to be on a place ready to accept an energised node), it'll retain that additional vis bonus. And what's more, you can just keep doing that as much as you want to get, say, 69420k cvis.
(It was alastor who found out about this, i just came here to report cuz it's too broken)

### Your Proposal

![2022-02-03_08 59 29](https://user-images.githubusercontent.com/57275066/152339569-2597d6c7-1bca-42f2-aac4-ca076b5b6b83.png)
![2022-02-03_09 00 09](https://user-images.githubusercontent.com/57275066/152339576-11e80c89-97d2-47f8-9ded-0c53d33fd680.png)
![2022-02-03_09 00 32](https://user-images.githubusercontent.com/57275066/152339577-d9c626b5-0e9a-43c8-96e8-adc48abd250a.png)
![2022-02-03_09 00 39](https://user-images.githubusercontent.com/57275066/152339578-92fee336-1718-4c88-8490-a64330e3b286.png)
![2022-02-03_09 07 15](https://user-images.githubusercontent.com/57275066/152339884-7edd1f2c-49d8-43e2-84af-02d80d8bcd63.png)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by repo-alt** [comment]
tbh I would have just disabled/blacklisted moving energized nodes with a dislocation focus

**Comment by Alastors** [comment]
> tbh I would have just disabled/blacklisted moving energized nodes with a dislocation focus

You gotta do it completely by hand though (I think), so Idfk man it highkey might be a waste since it still follows the normal node growth rules and is thus slow as all fuck compared to normal node growth methods

**Comment by Alastors** [comment]
It only really has one benefit, that being the fact that it could be used to get a bit limit energized node which was previously impossible to reach, but it would take literal fucking ages to do

**Comment by repo-alt** [comment]
How long does that +10% buffing take place? Also please remind me what mod adds those transduction amplifiers

**Comment by Alastors** [comment]
> How long does that +10% buffing take place? Also please remind me what mod adds those transduction amplifiers

it's infinite, but you have to do it by hand every time so, they add the +10% after a certain threshold, though it's a slow rate so Idk if it's adding directly onto the node itself, or exactly what value it's adding to, since it only adds an additional point after placing it a few extra times after a certain quickly obtained threshold

**Comment by Alastors** [comment]
> It only really has one benefit, that being the fact that it could be used to get a bit limit energized node which was previously impossible to reach, but it would take literal fucking ages to do

However, if you fixed the focus rather than try to fix anything else, so that it didn't work with energized nodes, then the problem would be solved, and we wouldn't have to worry about anything else lmfao. (though I will not, if you remove the amplifiers, without taking the node into the focus, it removes the buff so)

**Comment by Alastors** [comment]
(not saying you wont, just saying, the dislocation focus is the thing glitching out here rather than the amplifiers)

**Comment by repo-alt** [comment]
Well, the amplifiers just unconditionally change the node, they leave no trace that it is their doing. (They diminish the node back when/if removed.) Dislocation focus checking for the amplifiers and the node would be strange and out of place. 
Currenty dislocation focus blacklist supports only block names, so we may only blacklist both kind of nodes and nitor (they differ in metadata). I'm not sure if normal node is even moveable with dislocation focus, so it may be not a problem. If it is and is supposed to be, then I may add metadata support to the blacklist.

**Comment by Alastors** [comment]
> Well, the amplifiers just unconditionally change the node, they leave no trace that it is their doing. (They diminish the node back when/if removed.) Dislocation focus checking for the amplifiers and the node would be strange and out of place. Currenty dislocation focus blacklist supports only block names, so we may only blacklist both kind of nodes and nitor (they differ in metadata). I'm not sure if normal node is even moveable with dislocation focus, so it may be not a problem. If it is and is supposed to be, then I may add metadata support to the blacklist.

normal nodes and planar vortexes are already blacklisted btw

**Comment by Alastors** [comment]
> is even moveable with disl

believe me I tried, I really wanted it to work like that

**Comment by Alastors** [comment]
I had a really cool plan, I think it should work for normal nodes personally, and not energized, but you know, that's whatever I guess

**Comment by Alastors** [comment]
> e amplifiers just unconditionally chan

tbf though, it's such a niche case caused by something that could be fixed on the foci, sorry if I'm being weird, I've still got ptsd from the last planar vortex nerf :kekw: (The amplifier is related to the planar vortex, since 4 amplifiers is what turns an energized node into a vortex, and being the only reason I'm worried about the amplifier in the first place lmfao, I trust you completely to fix this whenever, I'm not saying I don't, and I don't even think that's implied anyhow but whatever) Either way,  ping me if you have any questions about this or whatever (preferably on discord since I see on my phone and can get back to you whenever) I can record or document anything you have a question about related to it or whatevs

**Comment by Alastors** [comment]
Tbh, I get kinda nervous reporting a lot of thaumic glitches until I can figure out what exactly is glitching out first and fully documenting it first anyhow though, that's just me being weird I guess though...
