### ISSUE TITLE
Add Alfheim (botania addon)

### ISSUE THREAD

**Issue by FoKuCNiK** [GTNewHorizons/GT-New-Horizons-Modpack#9686]
### Mod Name

Alfheim

### The Mod to Add

A huge botany addon, adds a ton of new stuff. There may be errors due to a conflict with mobs, but I think NH coders will easily solve everything.

**Comment by Dream-Master** [comment]
@FoKuCNiK link?

**Comment by Ethryan** [comment]
[Here](https://www.minecraftforum.net/forums/mapping-and-modding-java-edition/minecraft-mods/2964004-alfheim-botania-addon) i think.

[source](https://bitbucket.org/AlexSocol/alfheim/src/master/) link

**Comment by bombcar** [comment]
Botania license so it passes that requirement

**Comment by Dream-Master** [comment]
https://github.com/GTNewHorizons/Alfheim

**Comment by FoKuCNiK** [comment]
great, you just need to fix the fact that the mod does not run on GTNH. The reason lies in the mods that add spawning mobs (I think so)

**Comment by Dream-Master** [comment]
> great, you just need to fix the fact that the mod does not run on GTNH. The reason lies in the mods that add spawning mobs (I think so)

need more infos

**Comment by FoKuCNiK** [comment]
when i start GTNH + alfheim minecraft starts successfully. Then when I create the world at that moment the game crashes.

**Comment by FoKuCNiK** [comment]
just try running GTNH + Alfheim.jar + ASJCore.jar once and then spawn a single player world and try to log in. So you will get a crash in the crash log with which you can familiarize yourself

**Comment by Dream-Master** [comment]
ASJCore.jar ? is this a file we use ?
if you not add a log how i can check what happend ?

**Comment by FoKuCNiK** [comment]
Just launch GTNH with the addition of the alfheim mod and you will see a crash when you try to create a world in a single game.

**Comment by Chaoschaot232** [comment]
> ASJCore.jar ? is this a file we use ? if you not add a log how i can check what happend ?

https://www.curseforge.com/minecraft/mc-mods/asjcore here is the missing Link to AJCore, it was added as required lib 18.02.2021 (from his own Discord announcement channel)

In edition another quote to this mod and the lib from there:

> I think it's time to announce all "officially":
Alfheim (and ASJCore) development is frozen indefinitely.  I'm sorry for any inconvenience it can cause and all bugs that will remain unfixed for unknown period. But I really have no time for that due to personal reasons.

The reason, why it is no longer available on CF (Alfheim mod):

> My dear users. Today is a very sad day, because Alfheim mod was banned on CurseForge. For three years I developed it, and for almost two and a half years I more or less actively supported, adding new and interesting mechanics, items, as well as references - all in order to make it pleasant and interesting to play with my creation.
But a critical vulnerability has recently been found that allowed a user with my nickname to obtain operator status on any server with Alfheim. It was reported on one certain forum, whose "kind" users immediately ran to report this possibility to CurseForge, probably explaining everything incorrectly, as a result of which there was apparently confusion, and the site administration considered that the mod was a potential threat and simply blocked it without additional proceedings and did not even notice that the vulnerability was fixed on the same day and a new version was posted with a request to urgently update the mod. - 04.06.2020

> Well, they replied to me saying that they won't be restoring my project. I asked moderator and he said that I can try to reupload my mod. But to be sure that both it and my account won't get banned I asked CurseForge directly for the permission. Now waiting for the reply... 12.06.2020

And on 13.06.2020 he postet a screen of the CF Teams response that he will get baned due to ban evasion if he attemps to reupload his mod as new project because of ban evasion.

If this is all correct what I grabbed from his DC, CF did a graet job in failing and ignoring the modder 👎 

Since the OP here hasn't responded with a crashreport I am starting the dev pack with it and post what I'll get soon :)

**Comment by Runakai1** [comment]
I'll just leave my nooby opinion but: shouldn't botania be integrated properly before adding new stuff

**Comment by Chaoschaot232** [comment]
> I'll just leave my nooby opinion but: shouldn't botania be integrated properly before adding new stuff

Right but if this should be a nice addition it could be integrated directly with Botania, depending on how hard
it would be to resolve the mentioned crash report. If it's to worse, simple let it sit here and add it later, if it's worth it I would say but finally it is a suggestion which can be issued at any point ;)

**Comment by Chaoschaot232** [comment]
1) There are at last 3 Files and not only the mentioned ones here. The 3rd one is pulled automaticly from the BitBucket if I have seen this correctly within the log and is called Alfheim-Modular-11.jar:

`[13:52:57] [main/INFO] [LaunchWrapper]: Loading tweak class name cpw.mods.fml.common.launcher.FMLTweaker
[13:52:57] [main/INFO] [LaunchWrapper]: Using primary tweak class name cpw.mods.fml.common.launcher.FMLTweaker
[13:52:57] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.common.launcher.FMLTweaker
[13:52:57] [main/INFO] [FML]: Forge Mod Loader version 7.99.40.1614 for Minecraft 1.7.10 loading
[13:52:57] [main/INFO] [FML]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_331, running on Windows 11:amd64:10.0, installed at C:\Program Files\Java\jre1.8.0_331
[13:52:57] [main/INFO] [FML]: [ALFHEIM] Trying to update Alfheim Modular...
[13:52:57] [main/INFO] [FML]: [ALFHEIM] Mode: master
[13:52:58] [main/INFO] [FML]: [ALFHEIM] Congrats! Alfheim Modular is up to date
[13:52:58] [main/INFO] [FML]: Loading tweaker org.spongepowered.asm.launch.MixinTweaker from AppleCore-1.7.10-3.1.9.jar`

It is automaticly loaded in `mods/1.7.10`

2) The crash seems to be a problem with how things where tweaked/ASM'ed or what ever was done to trigger `Caused by: java.lang.ClassNotFoundException: vazkii.botania.common.block.decor.IFloatingFlower$IslandType` because of `Caused by: java.lang.ClassFormatError: Duplicate method name "getColor" with signature "()I" in class file vazkii/botania/common/block/decor/IFloatingFlower$IslandType`

Full Crashlog: https://paste.ee/p/yhTp5

Since I don't know how both mods are written and what is changing IFloatingFlowe in which way I am lost at this. If somebody could take a look into this and maybe fix it, it would help a loot to see what it does and how it cahnges/interacts with Botania in the current state incl. BotanicHorizons :3

**Comment by Chaoschaot232** [comment]
> Botania license so it passes that requirement

Well there are two licenses after all:

Alfheim and the Modular Modfile as part of Alfheim are part of Botania license.
https://bitbucket.org/AlexSocol/alfheim/src/master/src/api/ is the ASJCore (no own repro yet) which has it's license on curse https://www.curseforge.com/minecraft/mc-mods/asjcore and is WTFPL

So it should pass all requirements for all three jar files.

Clearifyed it in the owners discord:

![image](https://user-images.githubusercontent.com/1703441/167316284-fe5cdede-8b92-4883-b3c3-c84cd25342c7.png)
