### ISSUE TITLE
Remove servers.dat from the shipped pack and generate it at runtime

### ISSUE THREAD

**Issue by nwmqpa** [GTNewHorizons/GT-New-Horizons-Modpack#9687]
### Your GTNH Discord Username

nwmqpa#9999

### Your Pack Version

All

### Your Proposal

I'm playing on a custom private server, and each time, with each update, my servers.dat get deleted and replaced with the default one.

This is annoying on the level of "I have to enter my server again", but it also remove the current JourneyMap binding if I don't exactly remember the name of the server I choose.

### Your Goal

This could enable players on custom servers to avoid losing journeyman data, and not having to resetup their servers all over again

### Your Vision

This could be created using a mod that generate servers.dat file at the runtime of a release, and could ease the add of new servers to the default dat file, by creating a configuration file which could be modified with a text editor.

Or simply query the list on github to add new servers in between releases

I could implement it, but I would like to know if it's an issue other people encounter

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by mitchej123** [comment]
Why not just keep a copy of your servers.dat and replace it after updating?

**Comment by mitchej123** [comment]
> This could be created using a mod that generate servers.dat file at the runtime of a release
Also are you aware of such a mod that currently exists?

**Comment by boubou19** [comment]
asking players about manually merging the update to avoid any loss can be a wall for some players. So if it can reduce the risks of losing JM data, that's worth the effort imo

**Comment by bombcar** [comment]
> > This could be created using a mod that generate servers.dat file at the runtime of a release
> 
> Also are you aware of such a mod that currently exists?

This could be the easiest mod ever - if servers.dat doesn’t exist, pull it from GitHub. If it does, leave it alone.

**Comment by glowredman** [comment]
Yeah, I looked a bit at the MC classes responsible for displaying servers, might do a mod for it later.

**Comment by glowredman** [comment]
Done: https://github.com/glowredman/DefaultServerList

**Comment by Savallator** [comment]
Who thought it would be a good idea to have undeletable items in the server list? The current state is beyond stupid.

**Comment by glowredman** [comment]
Any feedback is appreciated but it would be really nice if it is actually constructive instead of "this change sucks and the person who did it sucks". You at least commented on an old, related issue but if you could read the other comments too, you might understand why the change was made to begin with.

**Comment by Savallator** [comment]
But at the moment, there is a bunch of spam in the server list, and the delete button does not work.

**Comment by Savallator** [comment]
Keep in mind most people don't even play on officials, and even those who do only on one most of the time. So that list is even in the best case >94% spam. And since the average player won't find out which config to change/which mod to delete, they will live with it. Someone in discord said he clicked delete 18 times, then at least his own server was at the top... (it is not by default).
Honestly i don't see any point in the current behaviour.

**Comment by glowredman** [comment]
I've updated DefaultServerList to adress some problems:
- Many players had most server displayed twice, one loaded from `servers.dat`, one loaded from `defaultserverlist.cfg`. DSL now automatically deletes all entries from `servers.dat` that are also in `defaultserverlist.json`.
- Default entries can be deleted if `"allowDeletions": true` (default case)

**NOTE**: The version of DSL currently used in the pack is a pre-release which still uses Forge configs. The first version I uploaded to CF/Modrinth already used JSON, as does the version with the changes mentioned above. *This means that DSL 1.1 is not a drop-in replacement!*

> Someone in discord said he clicked delete 18 times, then at least his own server was at the top... (it is not by default).

I'll blame this on duplicate entries, I see no way the [code](https://github.com/glowredman/DefaultServerList/blob/9ab942c09be56db1ef0e26335421b9479119587c/src/main/java/glowredman/defaultserverlist/mixins/ServerListMixin.java) could allow that. Should be fixed by the deduplication.

> So that list is even in the best case >94% spam.

Unofficial servers being pre-added is a thing for a long time. If you think it is "spam" you'll need to convince Dream to only include officials. Personally, I think it is the best way of communicating that there even are unofficial servers and in which region there are, since the request for a server advertisement channel on Discord has been denied (which would not reach as many players anyway, it would only be better for small servers just looking for a few people).

Source: [GitHub](https://github.com/glowredman/DefaultServerList/tree/1.1)
Download: [CurseForge](https://www.curseforge.com/minecraft/mc-mods/defaultserverlist/files/3846751) - [Modrinth](https://modrinth.com/mod/defaultserverlist/version/1.7.10-1.1)

**Comment by Savallator** [comment]
Is there any reason to have a seperate List at all? Why not just pull the List and write to the servers.dat from github whenever it does not exist, like bombcar suggested? I don't see any gain in having it seperate... What exactly is the problem you are trying to solve with that?

**Comment by glowredman** [comment]
Because then the list of external servers is only synchronised when the pack is first launched and then never again. Having it in a sepperate file (or pulling from a URL, which DSL also supports) allows for independent updates.

**Comment by Savallator** [comment]
Do you see the need to synchronize it more often than the release of new versions? I don't see how that is necessary...

**Comment by mitchej123** [comment]
I'm not sure why a new server should only be added/removed upon an official release.  So yes, I do see a need for it to be updated more frequently.   Servers come and go.  

It sounds like it might already be possible, but the ability to delete servers and not have them come back would be great.
